prettier/prettier

package.json, tests_config/run_spec.js
~~https://github.com/demoneaux/prettier/commit/95a89e9cdf9a7eadbafad51f17e51c46ec1286c7~~ https://github.com/jlongster/prettier/pull/11/commits/258575af9ade68a28813ea79a829468b61c94f22 allows the tests to run on Windows.
~~https://github.com/demoneaux/prettier/commit/8e2eaccfc1c5c4c456d5787992d2d19b67e11b31~~ ~~https://github.com/jlongster/prettier/pull/11/commits/29334081d2f7cd0ffcd8535b145e36d2f266e3d4~~ https://github.com/jlongster/prettier/pull/11/commits/e72347e51b3cd9d1694462856fad0047c4c6b38f attempts to solve EOL problems with Windows. ~~but there are still some issues with that.~~
Closes #10.
=> Fix tests for Windows.

index.js, package.json
@hzoo Is this right?
I also updated my fork of babylon just in case. Let me know when there's a new published version and I'll switch to it.
=> Update options to babylon

src/printer.js, tests/binding/__snapshots__/jsfmt.spec.js.snap, tests/break/__snapshots__/jsfmt.spec.js.snap, tests/disjoint-union-perf/__snapshots__/jsfmt.spec.js.snap, tests/geolocation/__snapshots__/jsfmt.spec.js.snap, tests/init/__snapshots__/jsfmt.spec.js.snap, tests/locals/__snapshots__/jsfmt.spec.js.snap, tests/react/__snapshots__/jsfmt.spec.js.snap, tests/refi/__snapshots__/jsfmt.spec.js.snap, tests/refinements/__snapshots__/jsfmt.spec.js.snap, tests/switch/__snapshots__/jsfmt.spec.js.snap
=> fixes #56: indent cases inside switch statements

src/printer.js, tests/break/__snapshots__/jsfmt.spec.js.snap, tests/disjoint-union-perf/__snapshots__/jsfmt.spec.js.snap
=> fixes #71: don't indent block statements which are children of case clauses

src/printer.js, tests/declare_export/__snapshots__/jsfmt.spec.js.snap, tests/es6modules/__snapshots__/jsfmt.spec.js.snap, tests/es_declare_module/flow-typed/__snapshots__/jsfmt.spec.js.snap, tests/export_type/__snapshots__/jsfmt.spec.js.snap, tests/get-def/helpers/__snapshots__/jsfmt.spec.js.snap, tests/import_type/__snapshots__/jsfmt.spec.js.snap, tests/import_typeof/__snapshots__/jsfmt.spec.js.snap, tests/method_properties/__snapshots__/jsfmt.spec.js.snap
=> Add semicolons to `export` declarations.

src/printer.js
Closes #55.
Note: I didn't update the snapshots as all the tests were affected, and I didn't want to cause any major issues while merging.
=> Add newline to EOF.

src/printer.js, tests/prettier/__snapshots__/jsfmt.spec.js.snap, tests/prettier/directives.js
=> Fix misprinting of directives.

bin/prettier.js
This helps giving a sense of progress when printing a lot of files
=> Log the filename when --write is being used

README.md, bin/prettier.js, package.json
=> Enable reading from stdin

src/printer.js, tests/declare_export/__snapshots__/jsfmt.spec.js.snap, tests/es6modules/__snapshots__/jsfmt.spec.js.snap, tests/prettier/__snapshots__/jsfmt.spec.js.snap, tests/prettier/exports.js
This supercedes https://github.com/jlongster/prettier/pull/104 so that I can go ahead and get it in.
=> Break long `exports` into multiple lines.

bin/prettier.js, index.js, tests/shebang/__snapshots__/jsfmt.spec.js.snap, tests/shebang/jsfmt.spec.js, tests/shebang/shebang.js
When looking into adding a test, I realized that the logic was inside of bin/prettier.js and therefore only applying to the cli. Moving it to index.js and adding a test so that it's more robust :)
=> Add test for shebang and move to index.js

src/printer.js
See https://github.com/jlongster/prettier/pull/169#issuecomment-272530265
=> Wrap ForStatement in a block for const decls

src/fast-path.js, tests/async/__snapshots__/jsfmt.spec.js.snap, tests/async/await_parse.js
This is the first time I'm adding something inside of fast-path so I'm not sure if it's correct, but it seems more correct than before!
Fixes #164
=> Fix await parenthesis

src/printer.js, tests/abnormal/__snapshots__/jsfmt.spec.js.snap, tests/break/__snapshots__/jsfmt.spec.js.snap, tests/instanceof/__snapshots__/jsfmt.spec.js.snap, tests/nullable/__snapshots__/jsfmt.spec.js.snap, tests/path/__snapshots__/jsfmt.spec.js.snap, tests/plsummit/__snapshots__/jsfmt.spec.js.snap, tests/refi/__snapshots__/jsfmt.spec.js.snap, tests/refinements/__snapshots__/jsfmt.spec.js.snap, tests/super/__snapshots__/jsfmt.spec.js.snap, tests/tabWith/__snapshots__/jsfmt.spec.js.snap, tests/type-destructors/__snapshots__/jsfmt.spec.js.snap, tests/undefined/__snapshots__/jsfmt.spec.js.snap, tests/union_new/__snapshots__/jsfmt.spec.js.snap
=> Don't break to new line if logical/loop statements are without brackets.

src/fast-path.js, tests/new_expression/__snapshots__/jsfmt.spec.js.snap, tests/new_expression/jsfmt.spec.js, tests/new_expression/new_expression.js
Fixes #227.
(Wasn't entirely sure on the test naming, happy to rename/move as needed)
=> Fix cases of missing parens with NewExpression

src/fast-path.js, tests/arrows/__snapshots__/jsfmt.spec.js.snap, tests/arrows/arrow_function_expression.js
=> Fix missing parenthesis for typeof and arrow functions

src/fast-path.js, tests/arrows/__snapshots__/jsfmt.spec.js.snap, tests/arrows/arrow_function_expression.js, tests/function/__snapshots__/jsfmt.spec.js.snap, tests/function/function_expression.js
Fixes #244, Fixes #246.
(Meta: we should at some point, consider reorganizing tests :D)
=> Fix FunctionExpression parens issues

bin/prettier.js, index.js, tests/shebang/__snapshots__/jsfmt.spec.js.snap, tests/shebang/shebang-newline.js
Not too sure if this formatting is fine as a default, but personally I prefer it this way.
=> Add newline after shebang.

src/pp.js
Replacing the `_makeIndent()` function as talked in #286 😃
=> Use js native String.repeat()

src/printer.js, tests/es6modules/__snapshots__/jsfmt.spec.js.snap, tests/es6modules/export_default_arrow_expression.js, tests/es6modules/export_default_call_expression.js, tests/es6modules/export_default_function_expression.js, tests/es6modules/export_default_new_expression.js
=> Handle additional export default parens cases

src/fast-path.js, tests/async_iteration/__snapshots__/jsfmt.spec.js.snap, tests/function/__snapshots__/jsfmt.spec.js.snap, tests/function/function_expression.js, tests/predicates-parsing/__snapshots__/jsfmt.spec.js.snap
=> Fix parens around anonymous functions

src/printer.js
This variable was declared but never used. Getting rid of it.
=> Remove unused variable

.travis.yml
Hopefully it'll fix spurious errors.
=> Add --run-in-band to travis

src/printer.js, tests/prettier/__snapshots__/jsfmt.spec.js.snap, tests/prettier/jsx-significant-space.js, tests/prettier/jsx-split-attrs.js, tests/prettier/jsx-stateless-arrow-fn.js
Supersedes https://github.com/jlongster/prettier/pull/219 and intended to supersede https://github.com/jlongster/prettier/pull/220
Still hammering a few tricky trailing-whitespace situations out, but may be ready for 👀 nonetheless
=> [WIP] [JSX] Add newlines between elements, preserving spaces

bin/prettier.js, index.js, src/comments.js, src/fast-path.js, src/pp.js, src/printer.js, src/util.js
It's a good idea to run it right after we do a release when the number of outstanding pull requests is low :)
I ran the full test suite and a few manual tests using the binary, everything seems to work fine. I also reviewed all the changes and didn't see anything crazy.
=> Run prettier through the codebase

tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/issues.js, tests/comments/jsfmt.spec.js
This adds a snapshot test for all of the weird things I've seen happening with comments.
=> Add tests for comments

index.js, src/options.js, src/printer.js
I pushed the options handling and doc->string process one level above.
=> Remove Printer module in favor of single function

src/fast-path.js
Grepped in the codebase and ran the tests
=> Remove unused functions from recast

src/doc-builders.js, src/printer.js
This is a leftover from recast. But it doesn't do anything now.
=> Kill fromString

src/comments.js, src/fast-path.js, src/options.js, src/util.js
Make all the files have a single module.exports call at the end of the file.
I added a missing `"use strict";` and removed a few unused functions from utils at the same time.
=> Normalize exports

src/fast-path.js, tests/async/__snapshots__/jsfmt.spec.js.snap, tests/async/conditional-expression.js
=> Remove parens around AwaitExpression in ternary

src/printer.js, tests/while/__snapshots__/jsfmt.spec.js.snap, tests/while/indent.js
=> Indent while test the same way as if test

package.json, src/comments.js, yarn.lock
Usage is at https://github.com/jlongster/prettier/blob/21729d8207a789c110f54d85374856aedc41126e/src/comments.js#L40-L58
```js
} else if (node[childNodesCacheKey]) {
return node[childNodesCacheKey];
}
var names;
if (isArray.check(node)) {
names = Object.keys(node);
} else if (isObject.check(node)) {
names = types.getFieldNames(node);
} else {
return;
}
if (!resultArray) {
Object.defineProperty(node, childNodesCacheKey, {
value: resultArray = [],
enumerable: false
});
}
```
=> Use a Symbol instead of the private dep

src/fast-path.js, src/printer.js, tests/es6modules/__snapshots__/jsfmt.spec.js.snap, tests/es6modules/export_default_class_declaration.js, tests/es6modules/export_default_class_expression.js, tests/es6modules/export_default_function_declaration.js, tests/es6modules/export_default_function_declaration_named.js, tests/es6modules/export_default_function_expression_named.js
Fixes #344 and adds a test for FunctionDeclaration as well
=> Add parens for default export FunctionExpressions

src/printer.js, tests/export_extension/__snapshots__/jsfmt.spec.js.snap, tests/export_extension/export.js, tests/export_extension/jsfmt.spec.js
=> Fix export extension output

src/printer.js, tests/switch/__snapshots__/jsfmt.spec.js.snap, tests/switch/empty_switch.js
=> Ignore EmptyStatement inside of switch case

src/printer.js, tests/switch/__snapshots__/jsfmt.spec.js.snap, tests/switch/empty_switch.js
=> Empty switch should not have an empty line

src/fast-path.js, tests/class_extends/__snapshots__/jsfmt.spec.js.snap, tests/class_extends/extends.js, tests/class_extends/jsfmt.spec.js
This should fix all of the issues with the fuzzer :)
Fixes #387
=> Fix class extends parenthesis

src/fast-path.js, tests/classes/__snapshots__/jsfmt.spec.js.snap, tests/classes/binary.js
=> Fix class inside of binary expression missing parenthesis

src/printer.js, tests/rest/__snapshots__/jsfmt.spec.js.snap, tests/rest/trailing-commas.js
=> Remove trailing comma for array destructuring with rest

src/fast-path.js, tests/classes/__snapshots__/jsfmt.spec.js.snap, tests/classes/call.js
=> Add parenthesis around class expression when left side of call expression

src/fast-path.js, tests/yield/__snapshots__/jsfmt.spec.js.snap, tests/yield/conditional.js, tests/yield/jsfmt.spec.js
=> Add parenthesis for yield inside of a conditional

src/fast-path.js, tests/arrows/__snapshots__/jsfmt.spec.js.snap, tests/arrows/arrows.js
=> Add parenthesis around assignment for arrow function body

src/fast-path.js, tests/export_default/__snapshots__/jsfmt.spec.js.snap, tests/export_default/body.js
=> Add parenthesis around export default assignments

README.md
I have a feeling a lot of people are going to want to run prettier on save and it's a relatively lightweight addition to the readme. If you don't think it belongs in the readme, feel free to close this.
=> Improve vim integration section

README.md, bin/prettier.js, package.json, yarn.lock
Why? See this comment: https://github.com/jlongster/prettier/issues/362#issuecomment-274250544
Fixes #145. Fixes #362.
=> Add glob support to the CLI

bin/prettier.js, docs/rollup.config.js, index.js, package.json, src/parser.js, yarn.lock
=> Use babel-code-frame for syntax errors

src/comments.js, src/doc-debug.js, src/fast-path.js, src/options.js, src/parser.js, src/printer.js
I had to restore this manually, otherwise nothing seems broken.
=> Run prettier for 0.11.0

src/doc-utils.js
- Introduce `findInDocs` that avoids some annoying boilerplate when you want to get a value while traversing the docs
- Implement a `hasStopped` behavior that stops the traversal when you found the value you needed
It shaves off a few milliseconds so it's negligible, but the code feels right :)
```js
./bin/prettier src/printer.js
```
Before:
After:
=> Refactor traversal

README.md
Ref https://github.com/jlongster/prettier/pull/458#discussion_r97773557
Maybe something like this?
=> Explain that you can pass options to the spec runner

bin/prettier.js
See each commit message for details.
=> CLI improvements

src/printer.js, tests/jsx-stateless-arrow-fn/__snapshots__/jsfmt.spec.js.snap, tests/jsx/__snapshots__/jsfmt.spec.js.snap, tests/ternaries/__snapshots__/jsfmt.spec.js.snap, tests/ternaries/jsfmt.spec.js, tests/ternaries/test.js
Fixes the part of https://github.com/jlongster/prettier/issues/317 not covered by https://github.com/jlongster/prettier/pull/473 as mentioned in  https://github.com/jlongster/prettier/issues/467#issuecomment-275476597.
Should probably wait for #473 to merge first, as this will have conflicts in the test output. Alternatively, would be happy to just have @vjeux add this commit to his PR.
=> Indent ternaries

src/printer.js, tests/member/__snapshots__/jsfmt.spec.js.snap, tests/member/expand.js, tests/member/jsfmt.spec.js
=> Indent computed member

src/printer.js, tests/last_argument_expansion/__snapshots__/jsfmt.spec.js.snap, tests/last_argument_expansion/arrow.js
=> Add CallExpression to the last argument expansion whitelist

src/printer.js, tests/jsx-newlines/__snapshots__/jsfmt.spec.js.snap, tests/jsx-newlines/jsfmt.spec.js, tests/jsx-newlines/test.js
fixes https://github.com/jlongster/prettier/issues/444
Also add multiline support, so you can do things like this:
```jsx
<div>
<Elem>
<div>blah blah blah</div>
<div>blah blah blah</div>
</Elem>
<Elem>
<div>blah blah blah</div>
<div>blah blah blah</div>
</Elem>
</div>
```
Up to one newline between elements/paragraphs is allowed
=> [JSX] Handle each line of text separately, allow up to one extra newline

bin/prettier.js
=> Only write to files if the change

src/printer.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/dangling.js, tests/flow/this_type/lib/__snapshots__/jsfmt.spec.js.snap, tests/flow/traits/__snapshots__/jsfmt.spec.js.snap
=> Fix syntax error in empty object with dangling comment

editors/jetbrains/README.md
=> Fix Jetbrains example screenshot url.

src/printer.js, tests/jsx_escape/__snapshots__/jsfmt.spec.js.snap, tests/jsx_escape/jsfmt.spec.js, tests/jsx_escape/nbsp.js
addresses https://github.com/jlongster/prettier/issues/547
raises one or two minor questions, I think
=> [JSX] Handle non-breaking space

src/comments.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/if.js
While trying to figure out how to handle both MemberExpression comments and IfStatement comments, I ended up doing this one as well... Sorry @yamafaktory :(
The logic is a bit annoying but works.
Fixes #487
=> Make comments between if & else to look good

src/comments.js, tests/comments/__snapshots__/jsfmt.spec.js.snap
This is using the same technique as #544 and will conflict with it when we try to merge both :)
Fixes #200
=> Make comments inside of MemberExpression look good

src/printer.js, tests/jsx/__snapshots__/jsfmt.spec.js.snap, tests/jsx/object-property.js
=> 565 jsx parentheses fix

src/printer.js, tests/flow_comments/__snapshots__/jsfmt.spec.js.snap, tests/flow_comments/arrow.js, tests/flow_comments/jsfmt.spec.js
=> Add parenthesis around single argument arrow if comments

src/printer.js, tests/last_argument_expansion/__snapshots__/jsfmt.spec.js.snap, tests/last_argument_expansion/break-parent.js
=> Use breakParent inside of last arrow expansion

src/printer.js, tests/classes/__snapshots__/jsfmt.spec.js.snap, tests/classes/empty.js
=> Support dangling comments in ClassBody

src/printer.js, tests/method-chain/__snapshots__/jsfmt.spec.js.snap, tests/method-chain/this.js
=> Make all the member expressions but the last one part of the first group

src/printer.js, tests/import/__snapshots__/jsfmt.spec.js.snap, tests/import/long-line.js
=> Break long imports

src/fast-path.js, tests/expression_statement/__snapshots__/jsfmt.spec.js.snap, tests/expression_statement/jsfmt.spec.js, tests/expression_statement/no_regression.js, tests/expression_statement/use_strict.js
=> Fix use strict as expression statement

src/printer.js, tests/flow/constructor_annots/__snapshots__/jsfmt.spec.js.snap, tests/flow/object-method/__snapshots__/jsfmt.spec.js.snap, tests/flow/refinements/__snapshots__/jsfmt.spec.js.snap, tests/flow/taint/__snapshots__/jsfmt.spec.js.snap, tests/flow/type_only_vars/__snapshots__/jsfmt.spec.js.snap, tests/flow_method/__snapshots__/jsfmt.spec.js.snap, tests/flow_method/jsfmt.spec.js, tests/flow_method/method.js
Omg, after 10 unsuccessful tries, I finally managed to get it working! The deciding factor was a trick by @mroch <3
Fixes #310
=> Use arrow function when inputted that way for flow objects

src/comments.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/try.js
Uses the same technique as for if/then/else. Added a helper function to make it easier.
Fixes #601
=> Better support try/catch comments

src/printer.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/jsx.js
This one was pretty annoying to figure out but now it's working. All the crazy comments I could throw at jsx seems to be working fine now :)
Fixes #543
=> Fix single indented JSX comment

src/printer.js, tests/jsx-newlines/__snapshots__/jsfmt.spec.js.snap, tests/jsx-newlines/test.js
=> [JSX] Fix spurious newline (fixes #614)

src/printer.js, tests/flow/more_react/__snapshots__/jsfmt.spec.js.snap, tests/jsx-significant-space/__snapshots__/jsfmt.spec.js.snap, tests/jsx-significant-space/test.js
Fixes #622 
Previously also contained https://github.com/jlongster/prettier/pull/628 and https://github.com/jlongster/prettier/pull/629
=> JSX whitespace fixes

src/comments.js, tests/if_comments/__snapshots__/jsfmt.spec.js.snap, tests/if_comments/if_comments.js, tests/if_comments/jsfmt.spec.js
We already have the logic for fixing if/then/else comments but those ones are triggering another codepath.
Fixes #618
=> Stabilize comments inside of if/then/else before {

src/printer.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/flow/type-printer/__snapshots__/jsfmt.spec.js.snap, tests/flow/union-intersection/__snapshots__/jsfmt.spec.js.snap, tests/flow/union_new/__snapshots__/jsfmt.spec.js.snap, tests/union_intersection/__snapshots__/jsfmt.spec.js.snap
=> Fix Flow union type annotations indentation

README.md, bin/prettier.js, docs/index.html, src/options.js, src/printer.js, tests/jsx_last_line/__snapshots__/jsfmt.spec.js.snap, tests/jsx_last_line/jsfmt.spec.js, tests/jsx_last_line/last_line.js
Feel free to suggest a better name for the option. Otherwise it works great :)
Fixes #654
=> Add option for putting > on the last line in jsx

src/printer.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/return-statement.js, tests/flow/generics/__snapshots__/jsfmt.spec.js.snap
=> Fix comments in return statement argument

src/printer.js, tests/ignore/__snapshots__/jsfmt.spec.js.snap, tests/ignore/ignore.js, tests/ignore/jsfmt.spec.js
This was surprisingly easy to write!
`prettier-ignore` will leave the expression the comment is attached to printed as it was before.
Fixes #120
=> [RFC] Introduce prettier-ignore

src/printer.js, tests/binary-expressions/__snapshots__/jsfmt.spec.js.snap, tests/binary-expressions/inline-object-array.js
This is a common pattern to write default values.
=> Inline objects & arrays as right part of a boolean expression

src/printer.js, tests/flow/import_type/__snapshots__/jsfmt.spec.js.snap, tests/flow/import_type/import_type_specifier.js
=> Ensure importKind is printed

README.md
Added a link to Mads Kristensen's new VS extension for prettier
=> [Docs]: update Readme to reference VS extension

src/printer.js, tests/binary-expressions/__snapshots__/jsfmt.spec.js.snap, tests/binary-expressions/arrow.js
We already do it for if/... but it looks weird for arrow function body.
=> Align boolean inside of arrow functions

src/fast-path.js, tests/async/__snapshots__/jsfmt.spec.js.snap, tests/async/conditional-expression.js
=> Fix await ternary parenthesis

src/printer.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/dangling.js
=> Fix missing dangling comment in exports

src/printer.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/dangling_array.js
=> Fix missing dangling comments in arrays

src/printer.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/dangling_for.js
=> Fix missing dangling comments in for loop

src/printer.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/flow/intersection/__snapshots__/jsfmt.spec.js.snap, tests/flow/typeapp_perf/__snapshots__/jsfmt.spec.js.snap, tests/flow/union_new/__snapshots__/jsfmt.spec.js.snap
=> Fix leading & operators in flow types

package.json, yarn.lock
This fixes a loop that can happen when running Jest with `--watch` and `--coverage` https://github.com/facebook/jest/blob/master/CHANGELOG.md#jest-1901
=> Upgrade to Jest 19.0.1

package.json, tests/es6modules/__snapshots__/jsfmt.spec.js.snap, tests/es6modules/export_default_function_declaration_async.js, tests/es6modules/jsfmt.spec.js, yarn.lock
=> Bump babylon & add test for async func decl

src/printer.js, tests/method-chain/__snapshots__/jsfmt.spec.js.snap, tests/method-chain/square_0.js
=> Group [0] at the end of the previous chain instead of beginning of next one

src/printer.js, tests/trailing_comma/__snapshots__/jsfmt.spec.js.snap, tests/trailing_comma/es5.js
=> Do not put trailing commas for function declaration in es5 mode

src/fast-path.js, tests/update_expression/__snapshots__/jsfmt.spec.js.snap, tests/update_expression/update_expression.js
=> Fix extra parens for update expressions

src/comments.js, src/printer.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/function-declaration.js, tests/flow/binding/__snapshots__/jsfmt.spec.js.snap
=> Fix function declaration params comments

package.json, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/flow/classes/__snapshots__/jsfmt.spec.js.snap, tests/flow/constructor_annots/__snapshots__/jsfmt.spec.js.snap, tests/flow/disjoint-union-perf/__snapshots__/jsfmt.spec.js.snap, tests/flow/indexer/__snapshots__/jsfmt.spec.js.snap, tests/flow/interface/__snapshots__/jsfmt.spec.js.snap, tests/flow/jsx_intrinsics.builtin/__snapshots__/jsfmt.spec.js.snap, tests/flow/jsx_intrinsics.custom/__snapshots__/jsfmt.spec.js.snap, tests/flow/more_react/__snapshots__/jsfmt.spec.js.snap, tests/flow/new_react/__snapshots__/jsfmt.spec.js.snap, tests/flow/object_assign/__snapshots__/jsfmt.spec.js.snap, tests/flow/react_functional/__snapshots__/jsfmt.spec.js.snap, tests/flow/this_type/lib/__snapshots__/jsfmt.spec.js.snap, tests/flow/traits/__snapshots__/jsfmt.spec.js.snap, yarn.lock
This fixes the bug with comments swapped between `/*` and `//`
Fixes #755
=> Update flow to 0.40

src/printer.js, src/util.js, tests/break-calls/__snapshots__/jsfmt.spec.js.snap, tests/break-calls/break.js, tests/flow/object_api/__snapshots__/jsfmt.spec.js.snap
This one should fix #804. It tried to implement what you suggested @vjeux and I hope this corresponds to what you were expecting!
=> Fix function call args

docs/index.html, docs/rollup.config.js, package.json
I also added support for parser dropdown and stop minifying the bundle so that the flow parser actually works.
Fixes #816
=> Fix trailing commas in docs

src/printer.js, tests/jsx-significant-space/__snapshots__/jsfmt.spec.js.snap, tests/jsx-significant-space/test.js
Fixes https://github.com/prettier/prettier/issues/818
cc @vjeux
=> [JSX] Break before and after jsx whitespace

src/printer.js, tests/flow/declare_export/__snapshots__/jsfmt.spec.js.snap, tests/flow/es6modules/__snapshots__/jsfmt.spec.js.snap, tests/require/__snapshots__/jsfmt.spec.js.snap, tests/require/jsfmt.spec.js, tests/require/require.js
This has come up a couple times on the issue tracker on the react-native-web discussion about Twitter internals. It seems like there's a concensus that people don't break long require calls and they'd rather have it go > 80 columns.
Fixes #303
Fixes #752
=> Do not break require calls

src/printer.js, tests/binary-expressions/__snapshots__/jsfmt.spec.js.snap, tests/binary-expressions/short-right.js
In #605 I restricted it to binary operations as I didn't know how it would affect boolean operations but it turns out the same technique solves problems that people are reporting. So doesn't make sense to restrict it.
Fixes #824
=> Inline short expressions for boolean operators too

bin/prettier.js
gofmt has this option and it's very handy for commit-hooks.
Fixes #851
=> Introduce -l option

src/printer.js, tests/flow/abnormal/__snapshots__/jsfmt.spec.js.snap, tests/flow/for/__snapshots__/jsfmt.spec.js.snap
This is a leftover from the recast prototype, it hasn't been touched since then. I have never seen anyone not put the label on the same line.
Fixes #859
=> Do not put \n after label

src/comments.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/call_comment.js
This is a pretty exotic way to put a comment and it's been a long time since I have seen prettier output be as broken :)
Fixes #857
=> Fix comment for `call( // comment`

src/fast-path.js, tests/flow/arrays/__snapshots__/jsfmt.spec.js.snap, tests/flow/arrays/union.js
=> Fix paren removal on UnionTypeAnnotation

src/comments.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/assignment-pattern.js
=> Fix unprinted comments in destructuring

src/printer.js, tests/flow/import_type/__snapshots__/jsfmt.spec.js.snap, tests/flow/import_type/import_type_specifier.js
=> Fix bug with importing empty type

src/printer.js, tests/it/__snapshots__/jsfmt.spec.js.snap, tests/it/it.js
Fixes https://github.com/prettier/prettier/issues/892
As mentioned in the issue I'm not sure the consistency between string and template literal is wanted or not (feel free to close), but as it was a simple fix I decided to PR it.
=> Do not break long it/test calls when template literal

README.md
Should remove confusion like in #891
=> Update lint-staged docs to use husky for less config.

src/fast-path.js, tests/for/__snapshots__/jsfmt.spec.js.snap, tests/for/in.js
=> Fix `in` inside of a for in a nested way

src/printer.js, tests/jsx/__snapshots__/jsfmt.spec.js.snap, tests/jsx/hug.js
=> Inline BinaryExpressions inside JSXExpression

src/fast-path.js, tests/assignment_expression/__snapshots__/jsfmt.spec.js.snap, tests/assignment_expression/assignment_expression.js, tests/assignment_expression/jsfmt.spec.js
=> Remove parens from chained assignments

src/comments.js, tests/for/__snapshots__/jsfmt.spec.js.snap, tests/for/comment.js
This is pretty edge case-y so i'm taking the easy way out.
Fixes #886
=> Fix for of/in comment on its own line around in/of

src/printer.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/jsx.js
=> Print line/mixed comments on new lines inside JSXEmptyExpression

src/printer.js, tests/flow/arrays/__snapshots__/jsfmt.spec.js.snap, tests/flow/arrays/comments.js
=> Add support for breaks in TupleTypeAnnotation

README.md
=> Mention prettier-standard package

src/comments.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/flow_union.js
I was being very careful in #853 by checking all the surrounding types but it actually turns out we want this behavior all the time.
Fixes #931
=> Unrestrict flow union comments check

package.json, tests/flow_object_comment/__snapshots__/jsfmt.spec.js.snap, tests/flow_object_comment/flow_object_comment.js, tests/flow_object_comment/jsfmt.spec.js, yarn.lock
ast-types was missing a type, I sent a PR on ast-type ( https://github.com/benjamn/ast-types/pull/211 ) which was merged and released (thanks @benjamn for being super quick!). So I'm upgrading ast-types and add the test in this PR.
Fixes #1007
=> Fix comments inside of ObjectPattern

package.json, tests/es6modules/__snapshots__/jsfmt.spec.js.snap, yarn.lock
=> Update babylon to 7.0.0-beta.4

bin/prettier.js
@cpojer made a great suggestion to use `fs.readFileSync` instead of the async version. prettier is CPU-bound and if you want parallelism you can spin up many instances of prettier.
Fixes #994
=> Do not use more than one file descriptor at a time

src/comments.js, tests/assignment_comments/__snapshots__/jsfmt.spec.js.snap, tests/assignment_comments/assignment_comments.js
=> Fix unstable comments in assignment pattern

src/comments.js, tests/class_comment/__snapshots__/jsfmt.spec.js.snap, tests/class_comment/comments.js
=> Fix class method comments

README.md
Original PR: prettier/prettier#671
=> Document prettier-ignore

README.md
=> note on styled-with-prettier badge to README

package.json, src/printer.js, tests/flow_type_spread/__snapshots__/jsfmt.spec.js.snap, tests/flow_type_spread/jsfmt.spec.js, tests/flow_type_spread/spread.js, yarn.lock
Fixes https://twitter.com/ryyppy/status/844116626467438592
=> Add support for flow type spread in 0.43

tests/flow_type_spread/__snapshots__/jsfmt.spec.js.snap, tests/flow_type_spread/jsfmt.spec.js
See https://github.com/prettier/prettier/pull/1064#discussion_r109787248
=> Fix spread snapshot test

README.md
generate table of contents for readme.
closes #1122
=> docs(readme) added TOC

src/printer.js, tests/object_property_comment/__snapshots__/jsfmt.spec.js.snap, tests/object_property_comment/after-key.js
Fixes #1112
This is my first contribution, so let me know if there's something wrong/weird :-)
=> Print comment after key

src/printer.js, tests/flow/annot/__snapshots__/jsfmt.spec.js.snap, tests/flow/annot/annot.js
=> Fix printing of Flow type number literals (#1128)

src/printer.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/return-statement.js
Bug mentioned in comments of https://github.com/prettier/prettier/pull/955
cc @vjeux
=> Fix leading comment inside returned SequenceExpression

README.md
I'm glad I have to make this PR 😃 
Since Prettier now has support for tabs, I need to change the reason for my fork!
Thanks
=> Change prettier-with-tabs to prettier-miscellaneous

src/comments.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/variable_declarator.js
=> Stabilize VariableDeclarator comments

src/comments.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/if.js
In #544, I fixed it for all the cases but didn't check for else :(
Fixes #1161
=> Stabilize else comments

src/fast-path.js, tests/new_expression/__snapshots__/jsfmt.spec.js.snap, tests/new_expression/call.js
=> Fix parenthesis when call inside of new

src/comments.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/last-arg.js, tests/trailing_comma/__snapshots__/jsfmt.spec.js.snap
We already handle this but forgot to do it for FunctionDeclaration
Fixes #1166
=> Fix last argument comment for function declaration

src/comments.js, tests/label/__snapshots__/jsfmt.spec.js.snap, tests/label/comment.js
=> Stabilize label comments

editors/emacs/README.md
It took me a second to figure out the appropriate format for this customization variable. I've added an example to the docs.
=> Update emacs README with prettier-args example

src/comments.js, tests/flow_comments/__snapshots__/jsfmt.spec.js.snap, tests/flow_comments/object_type_annotation.js
=> Stabilize comments on ObjectTypeAnnotation

src/comments.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/last-arg.js
=> Preserve comment for last arg of ObjectMethod

src/printer.js, tests/switch/__snapshots__/jsfmt.spec.js.snap, tests/switch/empty_lines.js
=> Ignore empty statement in switch newline detection

src/printer.js, tests/method-chain/__snapshots__/jsfmt.spec.js.snap, tests/method-chain/comment.js
=> Do not merge member chain if there's a comment in-between

bin/prettier.js
Forgot to add the actual CLI options in https://github.com/prettier/prettier/pull/1129 ! Thanks @frol for reporting.
=> Add cli option for --no-semi

src/printer.js
A content is a node that isn't an empty statement.
=> Remove hasContent

docs/index.html
=> Support semi and useTabs options in docs

bin/prettier.js
Would fix an error I had 
It catch an error "e" but try to display "err"
=> Fix : ReferenceError: err is not defined

README.md
Sometimes, it is nice to debug prettier locally to get a sense of what's going on. This helps answer two primary beginner questions:
1. is this code path executed, and if so from where
2. what data is available locally and what does it look like
This PR adds some debugging tips for running prettier in the browser and node.
=> Document debugging strategies

src/printer.js, tests/method-chain/__snapshots__/jsfmt.spec.js.snap, tests/method-chain/break-last-member.js
This is a regression from #1036 and #1188.
Fixes #1241
Fixes #1236
=> Do not inline member expressions as part of assignments

src/printer.js, tests/flow_return_arrow/__snapshots__/jsfmt.spec.js.snap, tests/flow_return_arrow/issue-1249.js
Resolves #1249
My guess is that my fix is probably too specific. I wanted to share it early for feedback.
=> Fix flow union params

README.md
Prettier should be saved to `devDependencies`
=> Add --dev option to suggested install cmd

README.md
Apparently the old one was removed from YouTube
=> Update link to @vjeux's React London presentation

src/printer.js, tests/binary-expressions/__snapshots__/jsfmt.spec.js.snap, tests/binary-expressions/if.js
=> Break if () if conditional inside breaks

src/comments.js, src/printer.js, tests/empty_paren_comment/__snapshots__/jsfmt.spec.js.snap, tests/empty_paren_comment/empty_paren_comment.js
=> Don't inline paren at right of arguments

src/printer.js, tests/flow_function_parentheses/__snapshots__/jsfmt.spec.js.snap, tests/flow_function_parentheses/jsfmt.spec.js, tests/flow_function_parentheses/test.js
=> Skip trailing commas with FlowShorthandWithOneArg

src/printer.js, tests/while/__snapshots__/jsfmt.spec.js.snap, tests/while/indent.js
issue #1346 , it now creates new line and indent for very long conditional statements. 
I have also added test in the while test folder and updated snapshot.
=> fix do-while break

src/printer.js, tests/flow_generic/__snapshots__/jsfmt.spec.js.snap, tests/flow_generic/jsfmt.spec.js, tests/flow_generic/trailing.js
=> Fix missing trailing commas on flow generics

README.md
Not sure if the copy is great, but since this is mostly for n00bs, better to err on side of more information.
=> Add example of using yarn test with arguments

src/printer.js, tests/typescript/conformance/types/functions/__snapshots__/jsfmt.spec.js.snap, tests/typescript/conformance/types/functions/functionTypeTypeParameters.ts
Tests for this will fail until #1393 is merged.
=> fix TSFunctionType failing on TypeParameters

src/printer.js, tests/flow_generic/__snapshots__/jsfmt.spec.js.snap, tests/flow_generic/jsfmt.spec.js, tests/flow_generic/nullable.js
=> Inline nullable in flow generics

src/printer.js, tests/flow_type_declarations/__snapshots__/jsfmt.spec.js.snap, tests/flow_type_declarations/jsfmt.spec.js, tests/flow_type_declarations/long.js
=> Allow flow declarations to break on StringLiteralTypeAnnotations

package.json, src/printer.js, tests/typescript/conformance/classes/__snapshots__/jsfmt.spec.js.snap, tests/typescript/conformance/classes/classDeclarations/__snapshots__/jsfmt.spec.js.snap, tests/typescript/conformance/classes/classDeclarations/classAbstractKeyword/__snapshots__/jsfmt.spec.js.snap, tests/typescript/conformance/classes/classDeclarations/classAbstractKeyword/classAbstractProperties.ts, tests/typescript/conformance/classes/classDeclarations/classHeritageSpecification/__snapshots__/jsfmt.spec.js.snap, tests/typescript/conformance/classes/classDeclarations/classHeritageSpecification/classAppearsToHaveMembersOfObject.ts, tests/typescript/conformance/classes/classDeclarations/classHeritageSpecification/classExtendingClass.ts, tests/typescript/conformance/classes/classDeclarations/classHeritageSpecification/classExtendsItselfIndirectly.ts, tests/typescript/conformance/classes/classDeclarations/classHeritageSpecification/classIsSubtypeOfBaseType.ts, tests/typescript/conformance/classes/classDeclarations/classHeritageSpecification/jsfmt.spec.js, tests/typescript/conformance/classes/classDeclarations/classInsideBlock.ts, tests/typescript/conformance/classes/classDeclarations/jsfmt.spec.js, tests/typescript/conformance/classes/classExpression.ts, tests/typescript/conformance/classes/jsfmt.spec.js, tests/typescript/conformance/classes/mixinAccessModifiers.ts, tests/typescript/conformance/classes/mixinClassesAnnotated.ts, tests/typescript/conformance/classes/mixinClassesAnonymous.ts, tests/typescript/conformance/classes/mixinClassesMembers.ts, tests/typescript/conformance/classes/nestedClassDeclaration.ts, tests/typescript/conformance/types/thisType/__snapshots__/jsfmt.spec.js.snap, tests/typescript/conformance/types/typeParameters/typeParameterLists/__snapshots__/jsfmt.spec.js.snap, tests/typescript/custom/abstract/__snapshots__/jsfmt.spec.js.snap, tests/typescript/custom/abstract/abstractProperties.ts
Thanks for the fix on the parser side, @soda0289 (eslint/typescript-eslint-parser#234)
* Super type fix: eslint/typescript-eslint-parser#242
#1306, #1422
=> Add supertype tests and add TSAbstractClassProperty

src/printer.js, tests/arrow-call/__snapshots__/jsfmt.spec.js.snap, tests/arrow-call/arrow_call.js, tests/arrows/__snapshots__/jsfmt.spec.js.snap
Resolves:
* https://github.com/prettier/prettier/issues/1456
=> Break class expression returned by arrow calls

src/ast-types.js, src/comments.js, src/fast-path.js, src/printer.js, src/typescript-ast-nodes.js, tests/typescript/conformance/types/enumDeclaration/__snapshots__/jsfmt.spec.js.snap, tests/typescript/conformance/types/enumDeclaration/enumDeclaration.ts, tests/typescript/conformance/types/enumDeclaration/jsfmt.spec.js, tests/typescript/conformance/types/importEqualsDeclaration/__snapshots__/jsfmt.spec.js.snap, tests/typescript/conformance/types/importEqualsDeclaration/importEqualsDeclaration.ts, tests/typescript/conformance/types/importEqualsDeclaration/jsfmt.spec.js, tests/typescript/conformance/types/interfaceDeclaration/__snapshots__/jsfmt.spec.js.snap, tests/typescript/conformance/types/interfaceDeclaration/interfaceDeclaration.ts, tests/typescript/conformance/types/interfaceDeclaration/jsfmt.spec.js, tests/typescript/conformance/types/moduleDeclaration/__snapshots__/jsfmt.spec.js.snap, tests/typescript/conformance/types/moduleDeclaration/jsfmt.spec.js, tests/typescript/conformance/types/moduleDeclaration/moduleDeclaration.ts, tests/typescript/conformance/types/namespaceExportDeclaration/__snapshots__/jsfmt.spec.js.snap, tests/typescript/conformance/types/namespaceExportDeclaration/exportAsNamespace.d.ts, tests/typescript/conformance/types/namespaceExportDeclaration/jsfmt.spec.js, tests_config/run_spec.js
Not done at all, just opening it for early exposure.
Adds printer implementation for:
* `TSInterfaceDeclaration` 
* `TSNamespaceExportDeclaration`
* `TSEnumDeclaration`
* `TSEnumMember`
* `TSImportEqualsDeclaration`
* `TSExternalModuleReference`
* `TSModuleDeclaration`
* `TSDeclareKeyword`
* `TSModuleBlock`
fixes #1422 #13 #1306
=> [WIP] add TSNamespaceExportDeclaration

src/printer.js, tests/windows/__snapshots__/jsfmt.spec.js.snap, tests/windows/template.js
=> Fix windows line ending on template literals

src/printer.js, tests/flow/constructor_annots/__snapshots__/jsfmt.spec.js.snap, tests/flow/dictionary/__snapshots__/jsfmt.spec.js.snap, tests/flow/new_spread/__snapshots__/jsfmt.spec.js.snap, tests/flow/sealed_objects/__snapshots__/jsfmt.spec.js.snap, tests/flow_object_order/__snapshots__/jsfmt.spec.js.snap, tests/flow_object_order/jsfmt.spec.js, tests/flow_object_order/order.js
This is very sad, but we need to do this to get the correct result :(
Fixes #1448
=> Reorder flow object props

src/printer.js, tests/flow/dictionary/__snapshots__/jsfmt.spec.js.snap, tests/flow/enumerror/__snapshots__/jsfmt.spec.js.snap, tests/function_single_destructuring/__snapshots__/jsfmt.spec.js.snap, tests/function_single_destructuring/test.js
=> [RFC] Inline function declaration with single arg as object

src/printer.js, tests/flow_generic/__snapshots__/jsfmt.spec.js.snap, tests/flow_generic/union.js
=> Fix empty line with flow union

README.md
Put options into table in readme, showing clear defaults, cli and api usage.
=> Options readme

src/printer.js, src/typescript-ast-nodes.js, tests/flow_generic/__snapshots__/jsfmt.spec.js.snap, tests/typescript/conformance/internalModules/importDeclarations/__snapshots__/jsfmt.spec.js.snap, tests/typescript/custom/call/__snapshots__/jsfmt.spec.js.snap, tests/typescript/custom/call/callSignature.ts
=> Fix module block, add enum initializers and fix type parameters

src/printer.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/function-declaration.js
=> Do not put parens for single argument with end of line comment

src/printer.js, tests/binary-expressions/__snapshots__/jsfmt.spec.js.snap, tests/binary-expressions/jsx_parent.js, tests/jsx/__snapshots__/jsfmt.spec.js.snap
=> Inline chained conditionals inside of jsx attribute

README.md
Included info to use with yelp's pre-commit
=> Include pre-commit plugin 

src/fast-path.js, src/printer.js, tests/typescript/compiler/__snapshots__/jsfmt.spec.js.snap, tests/typescript/compiler/indexSignatureWithInitializer.ts, tests/typescript/conformance/types/union/__snapshots__/jsfmt.spec.js.snap, tests/typescript/custom/computedProperties/__snapshots__/jsfmt.spec.js.snap, tests/typescript/custom/computedProperties/jsfmt.spec.js, tests/typescript/custom/computedProperties/string.ts, tests/typescript/custom/computedProperties/symbol.ts
=> TypeScript: improve handling of computed properties

src/printer.js, tests/typescript/custom/modifiers/__snapshots__/jsfmt.spec.js.snap, tests/typescript/custom/modifiers/jsfmt.spec.js, tests/typescript/custom/modifiers/question.ts, tests/typescript/custom/modifiers/readonly.ts
=> TypeScript: print readonly and ? tokens in TSMappedType

src/parser.js
This makes uses the fancy babylon error printer instead of just printing the message and line/column.
=> Better syntax error message for typescript

src/printer.js, tests/typescript/custom/module/__snapshots__/jsfmt.spec.js.snap, tests/typescript/custom/module/global.ts
=> TypeScript: handle declare global syntax

tests/typescript/conformance/expressions/functionCalls/__snapshots__/jsfmt.spec.js.snap
Last couple of PRs had conflicting snapshots.
=> Fix the build by updating snapsots

package.json, src/parser.js, src/printer.js, tests/function/jsfmt.spec.js, tests/typescript/conformance/comments/__snapshots__/jsfmt.spec.js.snap, tests/typescript/conformance/comments/comments.ts, tests/typescript/conformance/comments/jsfmt.spec.js, yarn.lock
* updated `eslint-parser-typescript` to current master
* disable all failing tests in package.json
* changed parser option to parse comments (https://github.com/prettier/prettier/issues/1537)
* enable `TSInterfaceDeclaration` test again and fix printer
=> update typescript parser

src/printer.js
Following up on https://github.com/prettier/prettier/pull/1585, this
deduplicates some repeated code relating to Flow types.
=> (Flow) Extract helper functions

src/fast-path.js, tests/async/__snapshots__/jsfmt.spec.js.snap, tests/async/conditional-expression.js
=> Fix missing parenthesis for await &&

src/fast-path.js, tests/async/__snapshots__/jsfmt.spec.js.snap, tests/async/parens.js
Follow up to https://github.com/prettier/prettier/pull/1593
=> Ensure parens for more await cases

src/printer.js, tests/arrays/__snapshots__/jsfmt.spec.js.snap, tests/binary-expressions/__snapshots__/jsfmt.spec.js.snap, tests/binary-expressions/test.js
Fix for #1342
It's my first pr for Prettier 😅 So, I'm not sure if I've done all right.
Seems, like I've break `tests/arrays/__snapshots__/jsfmt.spec.js.snap` with oneline expression. Should I add check like `node.left.type !== "Identifier"` ?
=> Fix boolean for empty objects

src/fast-path.js, tests/assignment/__snapshots__/jsfmt.spec.js.snap, tests/assignment/sequence.js
=> Remove Parens from SequenceExpressions in ForStatements

.gitignore, bin/prettier.js, scripts/run-external-typescript-tests.js
Runs prettier on all TypeScript tests from `../TypeScript/tests`.
Groups error by type, prints counts, and writes the full details to files, one file per type of error.
Output (too fast to see in the gif):
```
$ node scripts/run-external-typescript-tests.js
13328 good, 1757 bad
13328/15085 files printed without errors.
624     ast(input) !== ast(prettier(input))
312     Error: Value undefined is not a valid document
110     Error: Comment "<omitted>" was not printed. Please report this error!
90      SyntaxError: ';' expected.
88      SyntaxError: Expression expected.
83      TypeError: Cannot read property 'type' of undefined
55      prettier(input) !== prettier(prettier(input))
46      SyntaxError: Invalid character.
44      SyntaxError: ',' expected.
35      SyntaxError: Identifier …
```
=> TypeScript: add script to run all TypeScript tests

src/clean-ast.js, src/comments.js, src/doc-builders.js, src/doc-debug.js, src/doc-printer.js, src/doc-utils.js, src/fast-path.js, src/options.js, src/printer.js, src/typescript-ast-nodes.js, src/util.js
This was done with the help of [lebab], by running:
lebab --replace src -t let
[lebab]: https://github.com/lebab/lebab
A handful of declarations were not automatically fixed by `lebab`, so
they had to be manually refactored.
=> Use `const`/`let` instead of `var`

editors/emacs/prettier-js.el
So we can get prettier-js.el into Melpa
=> Add Emacs package attributes for prettier-js.el

.eslintrc, .travis.yml, bin/prettier.js, package.json, src/clean-ast.js, src/comments.js, src/doc-debug.js, src/doc-printer.js, src/fast-path.js, src/parser.js, src/printer.js, src/typescript-ast-nodes.js, src/util.js, yarn.lock
This helps ensure that the source code for Prettier follows its own
formatting rules.
=> Add `lint` script, run it on Travis, prettify source code

src/printer.js, tests/arrows/__snapshots__/jsfmt.spec.js.snap, tests/arrows/comment.js
=> Do not inline arrow when argument has a leading comment

src/printer.js, tests/strings/__snapshots__/jsfmt.spec.js.snap, tests/strings/template-literals.js
This fixes https://github.com/prettier/prettier/issues/1662 and fixes https://github.com/prettier/prettier/issues/1626
It also affects https://github.com/prettier/prettier/issues/821 and https://github.com/prettier/prettier/issues/1183
=> Don't removeLines() from TemplateLiteral quasis

README.md
as per @vjeux request https://twitter.com/Vjeux/status/866688412136292352
=> Add example of `--list-different` flag usage to readme

src/printer.js, tests/typescript_class/__snapshots__/jsfmt.spec.js.snap, tests/typescript_class/generics.ts, tests/typescript_class/jsfmt.spec.js
This is the only issue with the typescript codebase itself :)
=> Print typescript class generics

src/typescript-ast-nodes.js, tests/typescript_comments/__snapshots__/jsfmt.spec.js.snap, tests/typescript_comments/jsfmt.spec.js, tests/typescript_comments/types.ts
This lets the comment traversal code discover it
=> Add expression node in TSAsExpression

src/printer.js, tests/typescript_import_require/__snapshots__/jsfmt.spec.js.snap, tests/typescript_import_require/import_require.js, tests/typescript_import_require/jsfmt.spec.js
I'm not sure why it was there but it makes the transform not stable
=> Do not put softline before TSImportEqualsDeclaration

src/typescript-ast-nodes.js, tests/typescript_comments/__snapshots__/jsfmt.spec.js.snap, tests/typescript_comments/abstract_class.ts
This lets the comment traversal code discover it
=> Fix TSAbstractClass base

src/printer.js, tests/method-chain/__snapshots__/jsfmt.spec.js.snap, tests/method-chain/comment.js
=> Break if the first group has an end of line comment

src/typescript-ast-nodes.js, tests/typescript_tuple/__snapshots__/jsfmt.spec.js.snap, tests/typescript_tuple/jsfmt.spec.js, tests/typescript_tuple/tuple.ts
=> Add TSTupleType to ast-types

.eslintignore, src/printer.js, tests/switch/__snapshots__/jsfmt.spec.js.snap, tests/switch/empty_statement.js
The indentation detection didn't discard empty statements
=> Do not indent for switch case with `;`

src/printer.js, tests/class_comment/__snapshots__/jsfmt.spec.js.snap, tests/class_comment/comments.js
We didn't call the helper that handles this use case
=> Handle comments at the beginning of ClassProperty value

src/typescript-ast-nodes.js, tests/typescript_class/__snapshots__/jsfmt.spec.js.snap, tests/typescript_class/generics.ts
The comment doesn't print in the right location so there's likely more types missing but at least it's not crashing anymore
=> Add support for TSQualifiedType in ast-types

README.md, bin/prettier.js
Make docs and `--help` output up to date.
=> Document --with-node-modules flag

.eslintrc.js, src/fast-path.js, src/printer.js, src/util.js
See https://github.com/prettier/prettier/pull/1718#discussion_r118382742
=> Enforce braces after `if`/etc

src/printer.js, tests/object-prop-break-in/__snapshots__/jsfmt.spec.js.snap, tests/object_property_comment/__snapshots__/jsfmt.spec.js.snap, tests/objects/__snapshots__/jsfmt.spec.js.snap, tests/objects/right_break.js
=> Use the same breaking rules for assignment and object values

src/printer.js, tests/binary-expressions/__snapshots__/jsfmt.spec.js.snap, tests/binary-expressions/unary.js, tests/flow/intersection/__snapshots__/jsfmt.spec.js.snap
This has been a longstanding issue and I thought it would be hard to do, but turns out it is pretty easy!
Fixes #774
=> Indent conditions inside of !()

package.json, tests/destructuring/__snapshots__/jsfmt.spec.js.snap, tests/destructuring/destructuring.js, tests/destructuring/jsfmt.spec.js, tests/flow/coverage/__snapshots__/jsfmt.spec.js.snap, tests/flow/declare_module_exports/flow-typed/__snapshots__/jsfmt.spec.js.snap, tests/flow/es_declare_module/flow-typed/__snapshots__/jsfmt.spec.js.snap, tests/flow/facebookisms/__snapshots__/jsfmt.spec.js.snap, tests/import_then/__snapshots__/jsfmt.spec.js.snap, tests/import_then/jsfmt.spec.js, tests/import_then/then.js, yarn.lock
Thanks @mroch and @gabelevi for this release, it fixes all the known issues with the flow parser <3
Fixes #1469
Fixes #1457
Fixes #425
=> Update to flow 0.47

package.json, src/printer.js, tests/destructuring/__snapshots__/jsfmt.spec.js.snap, tests/destructuring/destructuring.js, tests/destructuring/jsfmt.spec.js, yarn.lock
=> Upgrade typescript-eslint to 31ad3c

src/fast-path.js, src/printer.js
We're close to get rid of ast-types completely :)
=> Remove ast-types from printer.js

src/fast-path.js
I console.log'd when it passed and ran the test suite, then uniqui-fied the results :)
=> Remove last call site of ast-types

src/fast-path.js, tests/typescript_non_null/__snapshots__/jsfmt.spec.js.snap, tests/typescript_non_null/jsfmt.spec.js, tests/typescript_non_null/parens.ts
=> Add parens for expressions inside TSNonNullExpression

src/printer.js, tests/sequence_break/__snapshots__/jsfmt.spec.js.snap, tests/sequence_break/break.js, tests/sequence_break/jsfmt.spec.js
=> Add the ability for SequenceExpression to break

src/comments.js, src/printer.js
=> Don't pass too many arguments to functions

src/parser.js, src/printer.js, tests/css_inline_url/__snapshots__/jsfmt.spec.js.snap, tests/css_inline_url/inline_url.js, tests/css_inline_url/jsfmt.spec.js
We don't want them to break even if they go beyond 80 columns
=> Inline url('string')

src/clean-ast.js, tests/css_trailing_comma/__snapshots__/jsfmt.spec.js.snap, tests/css_trailing_comma/jsfmt.spec.js, tests/css_trailing_comma/trailing.css
This doesn't change the semantics
=> Ignore trailing comma from the ast

src/printer.js, tests/css_attribute/__snapshots__/jsfmt.spec.js.snap, tests/css_attribute/insensitive.css, tests/css_attribute/jsfmt.spec.js
=> Add support for insensitive attribute match

src/printer.js, tests/typescript/compiler/__snapshots__/jsfmt.spec.js.snap, tests/typescript/compiler/declareDottedModuleName.ts, tests/typescript/compiler/privacyGloImport.ts
Comments weren't printed between TSModuleDeclaration and TSModuleBlock.
#1643
=> TypeScript: fix namespace comment printing

package.json, src/parser.js, src/printer.js, tests/css_loose/loose.js, tests/stylefmt/custom-properties/__snapshots__/jsfmt.spec.js.snap, tests/stylefmt/font-shorthand/__snapshots__/jsfmt.spec.js.snap, tests/stylefmt/var-notation/__snapshots__/jsfmt.spec.js.snap, yarn.lock
Fixes https://github.com/shellscape/postcss-values-parser/issues/29
=> Enable loose mode for postcss-values-parser

src/printer.js, tests/css_indent/__snapshots__/jsfmt.spec.js.snap, tests/css_indent/indent.css, tests/css_indent/jsfmt.spec.js, tests/stylefmt/font-face/__snapshots__/jsfmt.spec.js.snap, tests/stylefmt/lowercase/__snapshots__/jsfmt.spec.js.snap
This way it looks less weird when they break
=> Indent groups

src/printer.js, tests/css_indent/__snapshots__/jsfmt.spec.js.snap, tests/css_indent/indent.css
We really want to parse those as binary expressions but it's not going to be trivial. A quick fix that should help is to not break before those.
=> Do not break before `+`

README.md
- a version of prettier to latest in README in pre-commit config yaml example
=> Update README.md version of prettier in pre-commit

package.json, src/printer.js, tests/typescript_class/__snapshots__/jsfmt.spec.js.snap, tests/typescript_class/methods.ts, yarn.lock
=> Update eslint-typescript again

editors/emacs/README.md, editors/emacs/prettier-js.el
This PR addresses some issues that @purcell commented in https://github.com/melpa/melpa/pull/4765
=> Fix some issues from melpa PR

src/printer.js, tests/css_comments/__snapshots__/jsfmt.spec.js.snap, tests/css_comments/bug.css
Workarounds https://github.com/postcss/postcss-scss/issues/63
=> Workaround a bug where the comment location is off for scss

src/printer.js, tests/flow_function_parentheses/__snapshots__/jsfmt.spec.js.snap, tests/flow_function_parentheses/test.js
=> Add parenthesis for single arg types with generics

src/printer.js, tests/classes/__snapshots__/jsfmt.spec.js.snap, tests/classes/break.js
This shouldn't break if it fits in one line.
Fixes #1818
=> Add group around implements

README.md
https://twitter.com/Vjeux/status/869681809138765824
=> added related projects Bookmarklet

src/printer.js, tests/typescript_trailing_comma/__snapshots__/jsfmt.spec.js.snap, tests/typescript_trailing_comma/jsfmt.spec.js, tests/typescript_trailing_comma/trailing.ts
=> Remove trailing commas for generics in TypeScript

bin/prettier.js
Auto populating the 'filepath' option with the filename from the CLI evaluation
=> Making cli infer parser based on filetype

src/printer.js, tests/flow_method/__snapshots__/jsfmt.spec.js.snap, tests/flow_method/method.js
=> Fix yet another form of class with the same ast

src/fast-path.js, tests/typescript_as/__snapshots__/jsfmt.spec.js.snap, tests/typescript_as/as.js
=> Add parenthesis around object inside of as

src/printer.js, tests/typescript/conformance/ambient/__snapshots__/jsfmt.spec.js.snap
=> TypeScript: print static before accessibility

src/printer.js, tests/decorators/__snapshots__/jsfmt.spec.js.snap, tests/typescript_decorators/__snapshots__/jsfmt.spec.js.snap, tests/typescript_decorators/inline-decorators.ts
=> Decorators: inline more types of decorators

package.json, src/printer.js, tests/typescript/conformance/classes/constructorDeclarations/constructorParameters/__snapshots__/jsfmt.spec.js.snap, tests/typescript_array/__snapshots__/jsfmt.spec.js.snap, tests/typescript_readonly/__snapshots__/jsfmt.spec.js.snap, tests/typescript_readonly/jsfmt.spec.js, tests/typescript_readonly/readonly.ts, yarn.lock
Fixes #1845
Not sure if the regex is too easy to pass?
=> TypeScript: temp fix for missing readonly keyword

src/printer.js, tests/typescript/compiler/__snapshots__/jsfmt.spec.js.snap
=> Hack to get export default work

src/printer.js, tests/typescript_export/__snapshots__/jsfmt.spec.js.snap, tests/typescript_export/export.ts
=> TypeScript: look at source to determine export = statement

package.json, src/comments.js, src/doc-printer.js, src/parser-babylon.js, src/parser-typescript.js, src/printer.js, yarn.lock
Where's the ouroboros emoji when you need one?
=> Upgrade prettier to v1.4.0, fix lint issues

bin/prettier.js
https://github.com/prettier/prettier/issues/1900#issuecomment-305894004
=> Include typescript and postcss in parser help

tests_integration/__tests__/__snapshots__/with-shebang.js.snap, tests_integration/__tests__/with-shebang.js, tests_integration/cli/with-shebang/issue1890.js
Following up on https://github.com/prettier/prettier/pull/1899
=> Add regression test for CLI shebang preservation

src/printer.js, tests/typescript_decorators/__snapshots__/jsfmt.spec.js.snap, tests/typescript_decorators/decorators.js
=> Inline decorators with no arguments

src/printer.js, tests/typescript/compiler/__snapshots__/jsfmt.spec.js.snap, tests/typescript_method/__snapshots__/jsfmt.spec.js.snap, tests/typescript_method/semi.js
=> Add semi for ts function declarations without body

src/printer.js, tests/variable_declarator/__snapshots__/jsfmt.spec.js.snap, tests/variable_declarator/multiple.js
=> Do not make variable multilines inside of for loop

src/fast-path.js, tests/typescript_as/__snapshots__/jsfmt.spec.js.snap, tests/typescript_as/as.js
=> Add parenthesis for yield and await inside of `as`

bin/prettier.js
This got broken with the cursor commit.
cc @josephfrazier, would be nice to add some end to end test here :)
=> Fix --debug-check

tests_integration/__tests__/debug-check.js
See https://github.com/prettier/prettier/pull/1916
=> Add regression test for --debug-check

src/printer.js, tests/typescript_union/__snapshots__/jsfmt.spec.js.snap, tests/typescript_union/inlining.ts
=> Port intersection inlining logic to TypeScript

scripts/build/build.sh
=> Remove eval for npm release

src/printer.js, tests/typescript_nosemi/__snapshots__/jsfmt.spec.js.snap, tests/typescript_nosemi/interface.ts, tests/typescript_nosemi/type.js
=> TypeScript: print semi with inline interfaces/types

src/printer.js, tests/typescript_export/__snapshots__/jsfmt.spec.js.snap, tests/typescript_export/export-class.js
=> TypeScript: no semi after export default abstract class

README.md
- Prettier has grown into a more general tool.
=> Make README more JavaScript agnostic

src/printer.js, tests/typescript_index_signature/__snapshots__/jsfmt.spec.js.snap, tests/typescript_index_signature/index-signature.ts, tests/typescript_index_signature/jsfmt.spec.js, tests/typescript_nosemi/__snapshots__/jsfmt.spec.js.snap, tests/typescript_nosemi/index-signature.ts
=> TypeScript: print semi in class index signatures

.eslintrc.js, scripts/run-external-typescript-tests.js, src/doc-debug.js, src/doc-printer.js, src/doc-utils.js, src/parser-postcss.js, src/printer.js, src/util.js
As mentioned in at the end of
https://github.com/prettier/prettier/pull/1983/files#r120222081
=> Remove unnecessary 'else' after 'return'

src/printer-graphql.js, tests/graphql_lists/__snapshots__/jsfmt.spec.js.snap, tests/graphql_lists/jsfmt.spec.js, tests/graphql_lists/lists.graphql
(Also, I forgot to run the linter last time. I guess the CI doesn't run it?)
=> GraphQL: Add support for list values

bin/prettier.js, tests_integration/__tests__/__snapshots__/with-parser-inference.js.snap, tests_integration/__tests__/with-parser-inference.js, tests_integration/cli/with-parser-inference/javascript.js, tests_integration/cli/with-parser-inference/stylesheet.css
=> Also infer parser when using `--list-different`

src/printer.js
I noticed the duplicated code while working on commit 0cfd772
(https://github.com/prettier/prettier/pull/2008)
=> Use printStatementSequence() to print SwitchCase consequent

src/printer-graphql.js, tests/graphql_kitchen_sink/__snapshots__/jsfmt.spec.js.snap, tests/graphql_kitchen_sink/jsfmt.spec.js, tests/graphql_kitchen_sink/kitchen_sink.graphql
Also, this means we pass the kitchen sink test case! 🎉 
I think that means the only thing we need to add is comments and we are good to go for an initial release!
=> Add alias and null value

src/printer-graphql.js, tests/graphql_union_types/__snapshots__/jsfmt.spec.js.snap, tests/graphql_union_types/jsfmt.spec.js, tests/graphql_union_types/union_types.graphql
Hey ! 
Just opinionated union type formatting (line break if more than 2 types)
I'm not too familiar with the API so don't hesitate to tell me if I'm doing things wrong :)
=> GraphQL: Add support for union types

src/printer.js, tests/typescript_decorators/__snapshots__/jsfmt.spec.js.snap, tests/typescript_decorators/inline-decorators.ts
=> Break decorator before content

src/comments.js, tests/typescript_comments/__snapshots__/jsfmt.spec.js.snap, tests/typescript_comments/jsx.ts
=> Do not throw for unprinted comments inside of JSX

src/util.js, tests/decorators/__snapshots__/jsfmt.spec.js.snap, tests/decorators/comments.js
We need to do the same location trick for export class unfortunately.
Fixes #1956
=> Fix decorator comments for export class

src/util.js, tests/typescript_comments/__snapshots__/jsfmt.spec.js.snap, tests/typescript_comments/location.ts
We should remove this hack once https://github.com/eslint/typescript-eslint-parser/issues/314 lands
Fixes #1946
=> Include typeAnnotation inside of node location

src/printer.js, tests/method-chain/__snapshots__/jsfmt.spec.js.snap, tests/method-chain/comment.js
=> Check if the next group has comments

src/printer-graphql.js
Forgot to lint my changes, fixes failing build
=> Fix lint errors

src/printer.js, tests/directives/__snapshots__/jsfmt.spec.js.snap, tests/directives/test.js
Looks like we were only doing it at the top level, we should do it everywhere.
Fixes #2067
=> Preserve lines after directives

src/printer.js, tests/typescript_interface/__snapshots__/jsfmt.spec.js.snap, tests/typescript_interface/long-extends.ts
=> TypeScript: Break on multiple interface extends

src/parser-parse5.js, src/printer-htmlparser2.js, tests/html_basics/__snapshots__/jsfmt.spec.js.snap, tests/html_basics/html-fragment.html, tests/multiparser_html_css/__snapshots__/jsfmt.spec.js.snap, tests/multiparser_html_js/__snapshots__/jsfmt.spec.js.snap, tests/multiparser_html_ts/__snapshots__/jsfmt.spec.js.snap, tests/multiparser_vue/__snapshots__/jsfmt.spec.js.snap, tests/multiparser_vue/jsfmt.spec.js, tests/multiparser_vue/vue-component.vue, tests_config/run_spec.js
We can now format basic Vue components! :tada:
=> Add support for HTML fragments

src/printer.js, tests/variable_declarator/__snapshots__/jsfmt.spec.js.snap, tests/variable_declarator/multiple.js
=> Indent first of many variable declarations in one-var scenario

src/printer.js, tests/typescript_new/__snapshots__/jsfmt.spec.js.snap, tests/typescript_new/jsfmt.spec.js, tests/typescript_new/new-signature.ts
=> TypeScript: use printFunctionParams for call/construct signature

docs/index.html
My design skills are quite poor, but I had a quick crack at cleaning up the website a bit. Changes visible on my fork: https://azz.github.io/prettier/
URLs are backwards compatible.
I think we reserve prettier.js.org, as mentioned in #1284.
=> Revamp the website a bit

package.json, src/printer.js, tests/dynamic_import/jsfmt.spec.js, tests/typescript_class/__snapshots__/jsfmt.spec.js.snap, yarn.lock
=> Upgrade typescript to 2.4

src/doc-utils.js, src/multiparser.js, src/parser-parse5.js, src/printer-htmlparser2.js, src/printer.js, tests/html_basics/__snapshots__/jsfmt.spec.js.snap, tests/multiparser_html_css/__snapshots__/jsfmt.spec.js.snap, tests/multiparser_html_js/__snapshots__/jsfmt.spec.js.snap, tests/multiparser_html_ts/__snapshots__/jsfmt.spec.js.snap, tests/multiparser_vue/__snapshots__/jsfmt.spec.js.snap, tests/multiparser_vue/template-bind.vue, tests/multiparser_vue/template-class.vue
For #2097, this is my **work-in-progress** attempt at pretty-printing the contents of binding attributes for Vue.
=> Vue: pretty-print binding syntax

src/fast-path.js, tests/typescript_non_null/__snapshots__/jsfmt.spec.js.snap, tests/typescript_non_null/parens.ts
=> TypeScript: keep parens around with yield/await non-null assertion

src/printer.js, tests/import/__snapshots__/jsfmt.spec.js.snap, tests/import/empty-import.js
=> Print {} in import if it's in the source

src/printer.js, tests/typescript/compiler/__snapshots__/jsfmt.spec.js.snap, tests/typescript_interface/__snapshots__/jsfmt.spec.js.snap, tests/typescript_nosemi/__snapshots__/jsfmt.spec.js.snap
=> TypeScript: always break interfaces onto multiple lines

src/printer.js, tests/typescript_ambient/__snapshots__/jsfmt.spec.js.snap, tests/typescript_ambient/ambient.ts, tests/typescript_ambient/jsfmt.spec.js
=> Fix extra semicolon in ambient typescript declaration emit (#2165)

src/printer.js, tests/typescript_new/__snapshots__/jsfmt.spec.js.snap, tests/typescript_new/new-signature.ts
=> TypeScript: group function params in call/construct signatures

package.json, yarn.lock
=> TypeScript: upgrade typescript-eslint-parser to latest ts-2.4 commit

bin/prettier.js, tests_integration/__tests__/__snapshots__/with-node-modules.js.snap, tests_integration/__tests__/with-node-modules.js
=> CLI: ignore node_modules with ./**-style glob

src/clean-ast.js, src/printer-postcss.js, tests/css_color/__snapshots__/jsfmt.spec.js.snap, tests/css_color/hexcolor.css, tests/css_color/jsfmt.spec.js, tests/stylefmt/color-hex-lowercase/__snapshots__/jsfmt.spec.js.snap
=> CSS: lowercase hex colors

src/printer-postcss.js, tests/css_media/__snapshots__/jsfmt.spec.js.snap, tests/css_media/jsfmt.spec.js, tests/css_media/overflow.css, tests/stylefmt/at-media/__snapshots__/jsfmt.spec.js.snap
=> Allow long media rules to break

src/printer.js, tests/template/__snapshots__/jsfmt.spec.js.snap, tests/template/call.js
I merged the implementation of new and call expressions in this PR.
Fixes #2215
=> Support inline template for new calls

src/parser-postcss.js, tests/css_scss/__snapshots__/jsfmt.spec.js.snap, tests/css_scss/import_comma.css
It's annoying that the less parser is so lenient that it drops things instead of throwing :(
Fixes #2125
=> First try scss when there's an @import with comma

src/printer.js, tests/conditional/__snapshots__/jsfmt.spec.js.snap, tests/ternaries/__snapshots__/jsfmt.spec.js.snap, tests/ternaries/binary.js, tests/typescript/webhost/__snapshots__/jsfmt.spec.js.snap
=> Handle conditions inside of a ternary

src/multiparser.js, tests/multiparser_comments/__snapshots__/jsfmt.spec.js.snap, tests/multiparser_comments/comments.js, tests/multiparser_comments/jsfmt.spec.js
Otherwise it doesn't print comments :(
=> Attach comments in multiparser

src/printer-graphql.js, tests/graphql_bracket_spacing/__snapshots__/jsfmt.spec.js.snap, tests/graphql_bracket_spacing/bracket_spacing.graphql, tests/graphql_bracket_spacing/jsfmt.spec.js
=> Add support for --no-bracket-spacing for GraphQL

src/options.js
Test Plan:
create a `test.graphql` file that has some graphql content
```js
fragment Visit on HighlightedVisit
@argumentDefinitions(
count: {type: "Int", defaultValue: 20}
) {
name
}
```
```
./bin/prettier.js test.graphql
```
make sure it doesn't syntax error because it's parsing it as js.
=> Add .graphql detection

src/printer-graphql.js, tests/graphql_trailing_comma/__snapshots__/jsfmt.spec.js.snap, tests/graphql_trailing_comma/jsfmt.spec.js, tests/graphql_trailing_comma/trailing.graphql
=> Add support for --trailing-comma for GraphQL

src/printer.js, tests/jsx-text-wrap/__snapshots__/jsfmt.spec.js.snap, tests/jsx-text-wrap/test.js
A fix for https://github.com/prettier/prettier/issues/2263
=> Fix a case where significant whitespace was dropped

scripts/build/build.sh
=> Copy README.md to the dist/ folder

src/multiparser.js, src/printer-graphql.js, tests/graphql_arguments/__snapshots__/jsfmt.spec.js.snap, tests/graphql_bracket_spacing/__snapshots__/jsfmt.spec.js.snap, tests/graphql_comments/__snapshots__/jsfmt.spec.js.snap, tests/graphql_definitions/__snapshots__/jsfmt.spec.js.snap, tests/graphql_directives/__snapshots__/jsfmt.spec.js.snap, tests/graphql_fields/__snapshots__/jsfmt.spec.js.snap, tests/graphql_fragments/__snapshots__/jsfmt.spec.js.snap, tests/graphql_hello/__snapshots__/jsfmt.spec.js.snap, tests/graphql_kitchen_sink/__snapshots__/jsfmt.spec.js.snap, tests/graphql_lists/__snapshots__/jsfmt.spec.js.snap, tests/graphql_objects/__snapshots__/jsfmt.spec.js.snap, tests/graphql_trailing_comma/__snapshots__/jsfmt.spec.js.snap, tests/graphql_union_types/__snapshots__/jsfmt.spec.js.snap, tests/graphql_variable_definitions/__snapshots__/jsfmt.spec.js.snap
We need to use the same hack as CSS unfortunately.
Fixes #2275
=> Add \n at the end of .graphql files

src/printer.js, tests/import_then/__snapshots__/jsfmt.spec.js.snap, tests/import_then/long.js
=> Inline import('x') to avoid having trailing ,

package.json, tests/flow_jsx/__snapshots__/jsfmt.spec.js.snap, tests/flow_jsx/func_inside_attr.js, tests/flow_jsx/return_type.js, yarn.lock
=> Go back to babylon beta 13

src/printer-graphql.js, tests/graphql_object_type_def/__snapshots__/jsfmt.spec.js.snap, tests/graphql_object_type_def/jsfmt.spec.js, tests/graphql_object_type_def/object_type_def.graphql
It appears in some files inside of fb codebase
=> Initial support for GraphQL ObjectTypeDefinition

README.md, editors/vim/README.md
I've been using ALE to run Prettier and it's pretty neat, thought it warranted documenting.
Thanks for all your work on Prettier + please let me know if I've done anything wrong :)
=> (docs): Document using Prettier + Vim using ALE

src/clean-ast.js, src/multiparser.js, tests/template_literals/__snapshots__/jsfmt.spec.js.snap, tests/template_literals/styled-components-with-expressions.js
=> Removed injectGlobal and keyframes

README.md
have a non trivial impact --> has a non-trivial impact
=> docs(README): hype train clarification

docs/lib/index.js, docs/worker.js, src/printer.js
Fixes #2328
[View diff without whitespace changes](https://github.com/prettier/prettier/pull/2374/files?w=1)
=> Fix multiparser in website

src/printer.js, tests/flow/more_react/__snapshots__/jsfmt.spec.js.snap, tests/jsx-significant-space/__snapshots__/jsfmt.spec.js.snap, tests/jsx-stateless-arrow-fn/__snapshots__/jsfmt.spec.js.snap, tests/jsx-text-wrap/__snapshots__/jsfmt.spec.js.snap
This is a possible fix for https://github.com/prettier/prettier/issues/2325
=> Ensure there is a line break after leading JSX white space

bin/prettier.js, package.json, scripts/sync-flow-tests.js, tests_integration/__tests__/__snapshots__/multiple-patterns.js.snap, tests_integration/__tests__/multiple-patterns.js, tests_integration/cli/multiple-patterns/directory/file.js, tests_integration/cli/multiple-patterns/directory/nested-directory/nested-directory-file.js, tests_integration/cli/multiple-patterns/node_modules/node-module.js, tests_integration/cli/multiple-patterns/other-directory/file.js, tests_integration/cli/multiple-patterns/other-directory/nested-directory/nested-directory-file.js, tests_integration/cli/multiple-patterns/other-regular-modules.js, tests_integration/cli/multiple-patterns/regular-module.js
Support multiple glob pattern with ignore pattern
Issue: https://github.com/prettier/prettier/issues/2332
After if your accept this, i will do PR implement `.gitignore` support https://github.com/prettier/prettier/issues/2294
=> feat(cli): support multiple glob patterns with ignore pattern

bin/prettier.js, tests_integration/__tests__/list-different.js
This fixes https://github.com/prettier/prettier/issues/2389
=> Make --list-different to work with --stdin

bin/prettier.js, tests_integration/__tests__/debug-print-doc.js
This fixes https://github.com/prettier/prettier/issues/2396
=> Fix --debug-print-doc

src/fast-path.js, tests/typescript_cast/__snapshots__/jsfmt.spec.js.snap, tests/typescript_cast/parenthesis.ts
=> Remove parens for type assertions in binary expressions

package.json, yarn.lock
As prettier only used the colors, none of the breaking changes apply
=> Upgrade chalk

src/printer.js, tests/typescript_as/__snapshots__/jsfmt.spec.js.snap, tests/typescript_cast/__snapshots__/jsfmt.spec.js.snap, tests/typescript_cast/hug-args.ts
=> TypeScript: allow type assertions to hug

bin/prettier.js
=> Fix ignore unknown --no-semi

bin/prettier.js, package.json, tests_integration/__tests__/__snapshots__/ignore-path.js.snap, tests_integration/__tests__/ignore-path.js, tests_integration/cli/ignore-path/.gitignore, tests_integration/cli/ignore-path/.prettierignore, tests_integration/cli/ignore-path/other-regular-modules.js, tests_integration/cli/ignore-path/regular-module.js
Add `--ignore-path` argument and support `.prettierignore`
Issue: https://github.com/prettier/prettier/issues/2294
=> CLI: Support .ignore files

src/printer.js, tests/jsx_ignore/__snapshots__/jsfmt.spec.js.snap, tests/jsx_ignore/jsfmt.spec.js, tests/jsx_ignore/jsx_ignore.js
=> Implement prettier-ignore inside JSX

src/util.js, tests/binary-expressions/__snapshots__/jsfmt.spec.js.snap
Might have been a bit overzealous with #2429 :wink:
Fixes #2445
=> Flatten x & y & z, and x ^ y ^ z

src/parser-typescript.js
Still not sure what's actually throwing this error (#2361), but this will help find it.
=> Don't mask TypeScript errors without position information

src/comments.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/trailing_space.js
Can't seem to think of any issues this may cause...
Closes #2422
=> Trim trailing whitespace from line comments

.codecov.yml, .gitignore, .travis.yml, index.js, jest.config.js, package.json, src/parser-typescript.js, src/printer.js, yarn.lock
Ran it locally and found a lot of branches we haven't got jest coverage on. What do you think about adding coverage to CI, @vjeux?
=> Enable code coverage in CI

.codecov.yml, src/printer.js, tests/typescript_keywords/__snapshots__/jsfmt.spec.js.snap, tests/typescript_keywords/keywords.js, tests/typescript_module/__snapshots__/jsfmt.spec.js.snap, tests/typescript_module/namespace_function.ts
I'll go through and comment on each change.
=> Improve coverage and remove some dead code

README.md, docs/en/editors.md, editors/vim/README.md, website/editors.json
updating plugin docs ref location
=> Updating docs ref location

src/printer.js, tests/flow_export/__snapshots__/jsfmt.spec.js.snap, tests/flow_export/jsfmt.spec.js, tests/flow_export/type.js
Support added in Babylon 7.0.0-beta.17
=> Add support for flow export type star

tests/flow_jsx/__snapshots__/jsfmt.spec.js.snap, tests/flow_jsx/func_inside_attr.js
Ref: https://github.com/prettier/prettier/issues/2289
=> Re-enable flow-jsx-func-attr test

src/parser-babylon.js, src/printer.js, tests/optional_catch_binding/__snapshots__/jsfmt.spec.js.snap, tests/optional_catch_binding/jsfmt.spec.js, tests/optional_catch_binding/optional_catch_binding.js
Stage 3 from July TC39 meeting!
Ref: https://github.com/babel/proposals/issues/7
=> Add support for printing optional catch binding

src/printer.js, tests/typescript_declare/__snapshots__/jsfmt.spec.js.snap, tests/typescript_declare/declare_interface.ts
=> Print declare for TSInterfaceDeclaration

src/fast-path.js, src/parser-babylon.js, src/printer.js, tests/optional_chaining/__snapshots__/jsfmt.spec.js.snap, tests/optional_chaining/chaining.js, tests/optional_chaining/jsfmt.spec.js
https://github.com/tc39/proposal-optional-chaining
I had to add code to more places that I would have liked. Might need to clean this up a bit.
Closes #2568 
cc. @bakkot @existentialism want to give this a sanity check?
@vjeux Think it is too early to add support for this?
=> Implement proposal-optional-chaining

src/clean-ast.js, src/multiparser.js, tests/multiparser_js_css/__snapshots__/jsfmt.spec.js.snap, tests/multiparser_js_css/styled-components.js
=> Support styled.div.attr({})`...`

scripts/build/build.js, website/static/worker.js, website/yarn.lock
=> Website: Load babylon parser for json formatting

src/printer-postcss.js, tests/css_import/__snapshots__/jsfmt.spec.js.snap, tests/css_import/nodes.css
=> Print sub-nodes of `@import` in Less

src/printer.js, tests/flow/async_iteration/__snapshots__/jsfmt.spec.js.snap, tests/flow/node_tests/crypto/__snapshots__/jsfmt.spec.js.snap, tests/flow/promises/__snapshots__/jsfmt.spec.js.snap, tests/member/__snapshots__/jsfmt.spec.js.snap, tests/method-chain/__snapshots__/jsfmt.spec.js.snap, tests/method-chain/break-multiple.js
This is one possible solution to #1565.
See my comment here: https://github.com/prettier/prettier/issues/1565#issuecomment-325130067
Fixes #1565
Fixes #1282
=> Print 3 or more chained calls on multiple lines

README.md
=> Un-comment config file documentation

package.json, yarn.lock
Fixes https://github.com/prettier/prettier/issues/2678
=> Bump babylon to 7.0.0-beta.22

src/printer.js, tests/typescript_union/__snapshots__/jsfmt.spec.js.snap, tests/typescript_union/with-type-params.ts
=> Fix: Union type with type params regression

bin/prettier.js, tests_integration/__tests__/__snapshots__/arg-parsing.js.snap, tests_integration/__tests__/arg-parsing.js, tests_integration/cli/arg-parsing/file.js
=> Fix CLI option parsing

src/resolve-config.js
=> Fix config file finding when using stdin

src/printer.js, tests/typescript_declare/__snapshots__/jsfmt.spec.js.snap, tests/typescript_declare/declare_enum.ts
=> Fix printing declare modifier for TS enum

bin/prettier.js
Fixes #2726
I'm not sure if there are more places should be cleaned up.
- more?
=> refactor(bin): use `resolveConfigFile.sync()`

src/clean-ast.js, src/parser-postcss.js, src/printer-postcss.js, tests/css_case/__snapshots__/jsfmt.spec.js.snap, tests/css_case/case.less, tests/css_case/case.scss, tests/css_case/jsfmt.spec.js, tests/css_combinator/__snapshots__/jsfmt.spec.js.snap, tests/css_quotes/__snapshots__/jsfmt.spec.js.snap, tests/stylefmt/lowercase/__snapshots__/jsfmt.spec.js.snap
=> Normalize CSS case

src/cli-util.js, src/comments.js, src/doc-builders.js, src/fast-path.js, src/multiparser.js, src/options.js, src/parser.js, src/printer-graphql.js, src/printer-htmlparser2.js, src/printer-postcss.js
- If statements for old deprecated stuff.
- "This should never happen" (and never happens in the tests) code paths.
=> Ignore some things in coverage

scripts/run-external-tests.js
... so it can run external Flow tests as well (or any external tests for
that matter).
=> Generalize run-external-typescript-tests.js

.gitignore, src/comments.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/dynamic_imports.js
Resolves dynamic imports issue https://github.com/prettier/prettier/issues/1489
=> fixes dynamic imports

package.json, tests/typescript_never/__snapshots__/jsfmt.spec.js.snap, tests/typescript_never/jsfmt.spec.js, tests/typescript_never/type-argument.src.ts, yarn.lock
=> Fix: TypeScript never keyword (fixes #2718)

src/printer.js, tests/binary-expressions/__snapshots__/jsfmt.spec.js.snap, tests/binary-expressions/arrow.js, tests/binary-expressions/inline-object-array.js, tests/binary-expressions/jsx_parent.js, tests/jsx/__snapshots__/jsfmt.spec.js.snap, tests/jsx/logical-expression.js
Fixes #2714 (though the issue isn't only with JSX expressions)
I believe the heuristics are correct now, but the code got a pretty ugly and I don't have that much experience with this codebase. I hope I can get some guidance on how to improve that huge if expression :-)
=> Fix chained logical expressions with objects/array/etc inlined

scripts/build/build.js
Ensure the version in issue template is always up to date.
=> chore(build): update ISSUE_TEMPLATE.md before publish

scripts/build/build.js
Address https://github.com/prettier/prettier/pull/2776#discussion_r137951126
=> fix(build): update ISSUE_TEMPLATE using regex `?:` instead of `?!`

src/cli-util.js, tests_integration/__tests__/__snapshots__/ignore-absolute-path.js.snap, tests_integration/__tests__/ignore-absolute-path.js, tests_integration/cli/ignore-absolute-path/.prettierignore, tests_integration/cli/ignore-absolute-path/depth1/ignored/module.js, tests_integration/cli/ignore-absolute-path/ignored/module.js, tests_integration/cli/ignore-absolute-path/regular-module.js
=> fix(prettierignore): support absolute filename

src/clean-ast.js, src/multiparser.js, tests/multiparser_js_graphql/__snapshots__/jsfmt.spec.js.snap, tests/multiparser_js_graphql/graphql.js, tests_integration/cwd-serializer.js
=> Support graphql(schema, `query`)

package.json, yarn.lock
Context: https://github.com/prettier/prettier/pull/2814#issue-257601178
=> chore(deps): pin cosmiconfig

src/clean-ast.js, src/printer-postcss.js, tests/css_import/__snapshots__/jsfmt.spec.js.snap, tests/css_quotes/__snapshots__/jsfmt.spec.js.snap, tests/css_quotes/quotes.css
=> Adjust quotes in some more cases of `@import` in CSS

package.json, tests/flow_type_declarations/__snapshots__/jsfmt.spec.js.snap, tests/flow_type_declarations/declare_var.js, yarn.lock
=> Bump Babylon

src/printer-postcss.js, tests/css_case/__snapshots__/jsfmt.spec.js.snap, tests/css_case/case.less, tests/css_case/case.scss
=> Don't lowercase `&class` in SCSS/Less selectors

src/printer-postcss.js, tests/css_case/__snapshots__/jsfmt.spec.js.snap, tests/css_case/case.less, tests/css_case/case.scss
=> Don't lowercase Less variables when parsed with SCSS parser

package.json, yarn.lock
see https://github.com/davidtheclark/cosmiconfig/issues/90
=> Update cosmiconfig to 3.0.1 to avoid memory leak

src/fast-path.js, src/parser-babylon.js, src/printer.js, tests/classes_private_fields/__snapshots__/jsfmt.spec.js.snap, tests/classes_private_fields/jsfmt.spec.js, tests/classes_private_fields/private_fields.js
Fixes https://github.com/prettier/prettier/issues/2810.
(I'll add `ClassPrivateMethod` in a separate PR since it's a diff Babylon plugin, and diff stage)
=> Add support for ClassPrivateProperty

src/printer.js, tests/binary-expressions/__snapshots__/jsfmt.spec.js.snap, tests/binary-expressions/inline-jsx.js, tests/binary-expressions/inline-object-array.js, tests/binary-expressions/jsx_parent.js
Fixes #2823
With the fix in #2770 I ended up introducing a bug when the chain has
different precedences.
=> Fix different precedence binary expression when inlining

src/printer-postcss.js, tests/css_case/__snapshots__/jsfmt.spec.js.snap, tests/css_case/case.less, tests/css_case/case.scss
=> Don't lowercase SCSS placeholder selectors

src/cli-util.js, src/errors.js, src/parser.js
=> fix: do not print stack trace for invalid option

src/cli-util.js, src/errors.js
Context: https://github.com/prettier/prettier/pull/2895#issuecomment-331975555
=> refactor: use custom error

package.json, tests/typescript_symbol/__snapshots__/jsfmt.spec.js.snap, tests/typescript_symbol/jsfmt.spec.js, tests/typescript_symbol/symbol.ts, yarn.lock
=> fix(typescript): allow symbol type

package.json, tests/typescript_arrow/__snapshots__/jsfmt.spec.js.snap, tests/typescript_arrow/arrow_regression.js, tests/typescript_arrow/jsfmt.spec.js, yarn.lock
Fixes #2702 
Think we should wait until 2.5.3 is released?
=> Upgrade to ts2.5.3-insiders

src/comments.js, tests/typescript_decorators/__snapshots__/jsfmt.spec.js.snap, tests/typescript_decorators/decorators-comments.js
=> Fix printing of comments between decorators and method names

src/printer.js, tests/test_declarations/__snapshots__/jsfmt.spec.js.snap, tests/test_declarations/test_declarations.js
This reverts commit 3703cb5b07a158c507b49c23ef5f7b4abb8a41fe.
Fix #2909. Fix #2910
=> Revert "Fix line break in test declarations"

README.md
Context: https://github.com/prettier/prettier/issues/2909#issuecomment-332708084
=> Recommend pinning prettier version

src/fast-path.js, tests/optional_chaining/__snapshots__/jsfmt.spec.js.snap, tests/optional_chaining/chaining.js
Not sure why I added this case in the first place?...
Fixes #2914
=> Don't use parens with optional chaining meber expressions

scripts/build/rollup.bin.config.js, scripts/build/rollup.index.config.js
Fixes  #2924 (hopefully). Not sure if this is the correct fix, but it seems to work. Please help me test! We should also write integration tests that catch the error...
=> Try to fix cosmiconfig in the built version of Prettier

.travis.yml
Context: https://github.com/prettier/prettier/pull/2930#issuecomment-333029192
> Unrelated question: our CI's `NODE_ENV=production job` is always failed, what does it want to test for?
=> Fix Travis production builds

package.json, yarn.lock
No changes to the code but we may as well be on the latest version.
=> Upgrade prettier to 1.7.3

src/cli-util.js, tests_integration/__tests__/__snapshots__/with-config-precedence.js.snap, tests_integration/__tests__/with-config-precedence.js
=> Respect --stdin-filepath, regardless of config source

package.json, yarn.lock
Update to fix this issue https://github.com/davidtheclark/cosmiconfig/issues/95.
=> chore(deps): update cosmiconfig to v3.1.0

package.json, tests_integration/__tests__/__snapshots__/write.js.snap, tests_integration/__tests__/stdin-filepath.js, tests_integration/__tests__/syntax-error.js, tests_integration/__tests__/with-config-precedence.js, tests_integration/__tests__/write.js, tests_integration/runPrettier.js, yarn.lock
Not sure why, but the build failed.
- remove `--no-color`
- use `strip-ansi` to enforce no colored snapshots
- update snapshots
Fixes #2956
=> test: fix snapshots

package.json, scripts/build/build.js
=> Ensure package is published from dist/ with correct version number

website/static/worker.js
=> Fix website getStream regression

src/cli-util.js, tests_integration/__tests__/__snapshots__/write.js.snap, tests_integration/runPrettier.js
Context: https://github.com/prettier/prettier/pull/2957#discussion_r142209753
=> Include duration in --write snapshots

.travis.yml
This helps ensure that it stays up to date.
See https://github.com/prettier/prettier/pull/2993#issue-263763893
=> Check Table of Contents on CI

README.md
They are switched to Less instead of LESS
=> LESS -> Less

README.md
=> docs(readme): fix description for `filePath` in `prettier.resolveConfig`

src/printer-markdown.js, tests/markdown/__snapshots__/jsfmt.spec.js.snap, tests/markdown_link/__snapshots__/jsfmt.spec.js.snap, tests/markdown_link/url.md, tests/markdown_spec/__snapshots__/jsfmt.spec.js.snap
=> fix(markdown): print auto-link as-is

src/resolve-config.js, tests_integration/__tests__/config-resolution.js, tests_integration/cli/config/filepath/.prettierrc
=> Resolve file paths relative to config file

README.md
Fixes #3044
I'm not sure that's very clear since English isn't my first language. Let me know what I can improve.
Thanks!
=> doc(resolveConfig): document options.config

src/fast-path.js, tests/typescript_as/__snapshots__/jsfmt.spec.js.snap, tests/typescript_as/as.js
=> Keep parens around TSAsExpression in ConditionalExpression

src/printer.js
=> Fix typo: ident -> indent

src/resolve-config.js, tests_integration/__tests__/config-resolution.js, tests_integration/cli/config/$schema/.prettierrc
=> Delete $schema from resolved config

src/multiparser.js, tests/multiparser_js_css/__snapshots__/jsfmt.spec.js.snap, tests/multiparser_js_css/styled-components.js
=> Fix formatting styled(Foo).attrs(...)``

src/printer.js, tests/intersection/__snapshots__/jsfmt.spec.js.snap, tests/intersection/intersection.js
Fixes #3064
I decided not do anything fancy here and just fix the broken case without changing anything else.
=> Fix indentation of intersection object types

README.md
=> Add prettier-tslint and stylelint-config-prettier to related projects

src/printer.js, tests/new_expression/__snapshots__/jsfmt.spec.js.snap, tests/new_expression/with-member-expression.js
=> Prevent breaking MemberExpression inside NewExpression

src/printer.js, tests/arrows/__snapshots__/jsfmt.spec.js.snap, tests/jsx/__snapshots__/jsfmt.spec.js.snap, tests/jsx/expression.js
=> fix(jsx): Don't inline trailing } for arrow functions attributes

src/printer.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/jsx-text-wrap/__snapshots__/jsfmt.spec.js.snap, tests/line_suffix_boundary/__snapshots__/jsfmt.spec.js.snap, tests/template/__snapshots__/jsfmt.spec.js.snap, tests/template_literals/__snapshots__/jsfmt.spec.js.snap, tests/template_literals/expressions.js
=> Improve template literal expresions line breaks

src/printer.js, tests/jsx/__snapshots__/jsfmt.spec.js.snap, tests/jsx/attr-comments.js
=> Prevent inlining JSXAttribute if it has comments

src/printer.js, tests/method-chain/__snapshots__/jsfmt.spec.js.snap, tests/method-chain/square_0.js
```js
// before
find('.org-lclp-edit-copy-url-banner__link')
[0].getAttribute('href')
.indexOf(this.landingPageLink)
// after
find('.org-lclp-edit-copy-url-banner__link')[0]
.getAttribute('href')
.indexOf(this.landingPageLink)
```
Fixes #3134
=> Consider [0] to be part of the first member group

src/printer.js, tests/jsx/__snapshots__/jsfmt.spec.js.snap, tests/jsx/expression.js
Fixes #3109 and supersedes #3110.
cc @vjeux
=> Don't inline trailing } for arrow functions in JSX

README.md
The correct naming is ZEIT :smile:
=> Zeit -> ZEIT

website/users.json
h/t @ikatyang for pointing it out :)
=> Zeit -> ZEIT in users.json

package.json, scripts/build/build.js, scripts/run-external-tests.js, scripts/sync-flow-tests.js, src/cli-util.js, src/parser-markdown.js, tests_config/run_spec.js, tests_integration/__tests__/multiple-patterns.js, yarn.lock
Context: https://github.com/prettier/prettier/pull/3022#issuecomment-340649831
=> chore(deps): update prettier to 1.8.0

.gitignore, docs/api.md, website/package.json, website/siteConfig.js, website/static/overrides.css, website/yarn.lock
=> Upgrade docusaurus to beta.10

src/printer-markdown.js, tests/markdown_heading/__snapshots__/jsfmt.spec.js.snap, tests/markdown_heading/unbreakable.md
=> fix(markdown): do not break on unbreakable place

src/printer.js, tests/trailing_comma/__snapshots__/jsfmt.spec.js.snap, tests/trailing_comma/jsx.js
=> Don't add trailing commas in JSXAttribute for arrow functions

src/printer-markdown.js
Context: https://github.com/prettier/prettier/pull/3172#discussion_r149451396 https://github.com/prettier/prettier/pull/3194#discussion_r149460006
=> refactor(markdown): simplify regex

src/fast-path.js, tests/typescript_as/__snapshots__/jsfmt.spec.js.snap, tests/typescript_as/as.js
=> Parenthesis around TSAsExpression inside TSAbstractClassDeclaration

src/comments.js, tests/json/__snapshots__/jsfmt.spec.js.snap, tests/json/top-block-comment.json, tests/json/top-line-comment.json, tests/markdown/__snapshots__/jsfmt.spec.js.snap
=> Print JSON top comments as leading comments of root node

src/cli-constant.js, src/options.js, src/printer-markdown.js, tests/markdown_paragraph/__snapshots__/jsfmt.spec.js.snap, tests/markdown_paragraph/jsfmt.spec.js, tests_integration/__tests__/__snapshots__/early-exit.js.snap
=> feat(markdown): add `--no-prose-wrap` option

src/printer-markdown.js, tests/markdown/__snapshots__/jsfmt.spec.js.snap, tests/markdown_code/__snapshots__/jsfmt.spec.js.snap, tests/markdown_link/__snapshots__/jsfmt.spec.js.snap, tests/markdown_link/long.md, tests/markdown_paragraph/__snapshots__/jsfmt.spec.js.snap
=> fix(markdown): no break on link

docs/options.md
=> docs(options): add note for available version

website/editors.json
=> docs(editors): sort alphabetically

website/pages/playground/index.html, website/static/playground.js
- add `--no-prose-wrap`
- add `--insert-pragma`
- add `--require-pragma`
- ~~reorder options~~
---
+ before
+ after
<details><summary><del>reordered version</del></summary><img src="https://user-images.githubusercontent.com/8341033/32598324-7ca08292-c574-11e7-8c13-5a05b5649bf8.png"></details>
---
Closes #2968 
Closes #3218
=> feat(playground): add options

src/printer-markdown.js, tests/markdown/__snapshots__/jsfmt.spec.js.snap, tests/markdown_inlineCode/__snapshots__/jsfmt.spec.js.snap, tests/markdown_inlineCode/long.md
Context: https://github.com/prettier/prettier/pull/3224#discussion_r149975854
=> fix(markdown): do not break `inlineCode`

package.json, src/printer-markdown.js, src/util.js, tests/markdown_paragraph/__snapshots__/jsfmt.spec.js.snap, tests/markdown_paragraph/cjk.md, yarn.lock
=> fix(markdown): handle punctuation variants

website/languages.json
It's not LESS anymore: http://lesscss.org
=> Rename LESS -> Less

src/parser-markdown.js, src/printer-markdown.js, tests/markdown_toml/__snapshots__/jsfmt.spec.js.snap, tests/markdown_toml/jsfmt.spec.js, tests/markdown_toml/simple.md
=> feat(markdown): support TOML

src/clean-ast.js, src/multiparser.js, src/printer-markdown.js, tests/multiparser_js_markdown/__snapshots__/jsfmt.spec.js.snap, tests/multiparser_js_markdown/single-line.js
=> fix(multiparser): fix markdown error and remove trailing new line

website/editors.json
https://github.com/t9md/atom-mprettier
@t9md
=> Add mprettier to website editor integration list

website/siteConfig.js
=> chore(website): ignore `<!-- prettier-ignore -->` before passing into Docusaurus

src/fast-path.js, tests/typescript_decorators/__snapshots__/jsfmt.spec.js.snap, tests/typescript_decorators/decorator-type-assertion.ts
=> Print parens around type assertions for decorators

src/printer-markdown.js, tests/markdown_heading/__snapshots__/jsfmt.spec.js.snap, tests/markdown_heading/mixed.md
=> fix(markdown): do not print linebreaks in heading

README.md, website/core/Footer.js
Related: #3127
<a href="https://twitter.com/PrettierCode">
</a>
or
[![Twitter Follow](https://img.shields.io/twitter/follow/prettiercode.svg?style=social&label=Follow+Prettier)](https://twitter.com/PrettierCode)
---
Closes #3127 (edited by @ikatyang)
=> Add Twitter social button

src/clean-ast.js, src/multiparser.js, tests/template_literals/__snapshots__/jsfmt.spec.js.snap, tests/template_literals/css-prop.js
=> Format CSS prop for emotion

package.json, yarn.lock
https://github.com/tjunnone/npm-check-updates
running the
```
ncu -u --semverLevel minor
```
=> chore: Update packages to the latest patches

src/doc-printer.js, tests/markdown_blockquote/__snapshots__/jsfmt.spec.js.snap, tests/markdown_blockquote/code.md
=> fix(doc-printer): respect indent/align order

.prettierrc, CHANGELOG.md, docs/ignore.md, package.json, scripts/build/build-docs.js, scripts/build/build.js, scripts/sync-flow-tests.js, src/cli-util.js, website/static/worker.js, yarn.lock
=> Upgrade Prettier to Prettier 1.9

src/printer.js, tests/jsx_fragment/__snapshots__/jsfmt.spec.js.snap, tests/jsx_fragment/fragment.js
=> Don't default print comments for JSXFragments

src/doc-printer.js, tests/ternaries/__snapshots__/jsfmt.spec.js.snap, tests/ternaries/jsfmt.spec.js
=> fix(doc-printer): no wrong function call

src/multiparser.js, tests/multiparser_markdown_js/__snapshots__/jsfmt.spec.js.snap, tests/multiparser_markdown_js/jsfmt.spec.js, tests/multiparser_markdown_js/trailing-comma.md
=> Fix multiparser trailing comma regression

package.json, yarn.lock
=> Bump editorconfig-to-prettier

website/static/worker.js
=> Fix multiparser on playground

docs/precommit.md
It's nice to have all extensions so we can easily copy paste :)
=> Add "md" extension in "Pre-commit hook" documentation

src/printer.js, tests/trailing_comma/__snapshots__/jsfmt.spec.js.snap, tests/trailing_comma/function-calls.js
=> Print trailing comma when last arg is arrow

src/printer.js, tests/no-semi/__snapshots__/jsfmt.spec.js.snap, tests/no-semi/no-semi.js
=> Only prevent lone `get` and `set` if property has no value

docs/precommit.md
=> Improve visibility of lint-staged usage warning

src/printer.js, tests/union_intersection/__snapshots__/jsfmt.spec.js.snap, tests/union_intersection/test.js
=> Fix printing union types inside a function param type

src/printer.js, tests/flow_intersection/__snapshots__/jsfmt.spec.js.snap, tests/flow_intersection/intersection.js, tests/flow_intersection/jsfmt.spec.js, tests/typescript_union/__snapshots__/jsfmt.spec.js.snap, tests/typescript_union/union-parens.ts
=> Fix closing parens on multi-line intersection/union type

src/printer.js, tests/flow/destructuring/__snapshots__/jsfmt.spec.js.snap, tests/function_single_destructuring/__snapshots__/jsfmt.spec.js.snap, tests/function_single_destructuring/array.js, tests/function_single_destructuring/object.js
=> Don't break single argument destructuring arguments

src/comments.js, src/printer.js, tests/flow_comments/__snapshots__/jsfmt.spec.js.snap, tests/flow_comments/arrow.js
=> Print comment after arrow function params

package.json, src/fast-path.js, src/printer.js, tests/typescript/compiler/__snapshots__/jsfmt.spec.js.snap, yarn.lock
Also has the bonus of fixing a bug by the looks of it!
=> Update tsep to v11 and update snapshot

README.md
I made a couple of grammatical suggestions to the `README.md`.
=> Update grammar in the README.md

.travis.yml
This reverts commit 675688c8147810359040a15b0369a69a394998c5.
See the following for context:
* https://github.com/prettier/prettier/pull/3349#issuecomment-350617020
* https://github.com/travis-ci/travis-ci/issues/7566#issuecomment-351514693
=> Revert "Set travis dist to "precise""

docs/precommit.md
I find it very convenient and very easy to config.
=> add js version pre-commit

README.md
Updated the alt attribute to reflect the image it is attached to.
=> Changed the alt attribute for monthly downloads

website/siteConfig.js
We all like statistics but we can also check where people are spending their time so we can improve different areas.. (mostly numbers though 😄) PM your email on [Twitter](https://twitter.com/lipis) and I'll give you access..
=> Add Google Analytics tracking ID

website/pages/playground/index.html, website/static/playground.js
Fixes #3542.
[<sub><sub><img 
height="20" src="https://avatars0.githubusercontent.com/oa/117514?s=40&u=f5bc93150a0ab17d693f6c71629caa3d07feb72a&v=4"></sub></sub> Live preview](https://deploy-preview-3562--prettier.netlify.com/playground/)
=> Make the playground header fit in with the rest of the site

docs/precommit.md
See more here : https://github.com/prettier/prettier/issues/2078.
=> fix recursive in script

src/clean-ast.js
Fixes build failure from #3563
=> Add content{Start,End} to massageAST

website/static/playground.js
Ref https://github.com/prettier/prettier/pull/3562#discussion_r158610668.
=> Change the changelog link to link to prettier/prettier

docs/configuration.md
I thought a JS example would help too especially since comments are then valid.
=> add an example .prettierrc.js config

package.json, tests/literal-numeric-separator/jsfmt.spec.js, yarn.lock
=> Bump TypeScript to 2.7-insiders

website/static/worker.js
Fixes #3581 
Not sure why the name changed from "index" to "prettier".
=> Fix PR Preview Playground

src/language-js/embed.js, tests/multiparser_js_graphql/__snapshots__/jsfmt.spec.js.snap, tests/multiparser_js_graphql/react-relay.js
This reverts commit e8551b994d313ea023855a790c87acc4833150f9.
=> Revert Relay Classic non-support

scripts/build/build-docs.js, website/static/worker.js
=> fix(playground): use `prVersion`

src/language-markdown/embed.js, tests/markdown_blockquote/__snapshots__/jsfmt.spec.js.snap, tests/markdown_blockquote/ignore-code.md
=> fix(markdown): replace newlines with hardlines in multiparser

src/cli/util.js, tests_integration/__tests__/__snapshots__/ignore-path.js.snap, tests_integration/__tests__/__snapshots__/stdin-filepath.js.snap, tests_integration/__tests__/ignore-path.js, tests_integration/__tests__/stdin-filepath.js
=> Output files as-is if ignored

src/language-graphql/printer-graphql.js, tests/graphql_string/__snapshots__/jsfmt.spec.js.snap, tests/graphql_string/string.graphql
context: https://github.com/prettier/prettier/pull/3632#discussion_r159293854
=> Print description of enum and input for GraphQL

src/language-js/printer-estree.js, tests/jsx-attr-element/__snapshots__/jsfmt.spec.js.snap, tests/jsx-attr-element/attr-element.js, tests/jsx-attr-element/jsfmt.spec.js
=> Don't wrap JSX elements as attribute in ()

src/language-js/printer-estree.js, tests/jsx/__snapshots__/jsfmt.spec.js.snap, tests/jsx/attr-comments.js
=> Prevent adding softline after arrow attribute with comments

src/language-css/parser-postcss.js, tests/css_comments/__snapshots__/jsfmt.spec.js.snap, tests/css_comments/selectors.scss
=> [scss] Print comments inside of selector as is

jest.config.js, package.json, scripts/build/rollup.bin.config.js, scripts/build/rollup.index.config.js, src/common/load-plugins.js, src/common/support.js, src/language-markdown/embed.js, src/main/options.js, tests_config/fs.js, tests_integration/__tests__/plugin-extensions.js, tests_integration/__tests__/plugin-resolution.js, tests_integration/plugins/automatic/file.txt, tests_integration/plugins/automatic/node_modules/@prettier/plugin-foo/index.js, tests_integration/plugins/automatic/node_modules/prettier-plugin-bar/index.js, tests_integration/plugins/automatic/package.json, tests_integration/plugins/extensions/file.foo, tests_integration/plugins/extensions/plugin.js, yarn.lock
Automatically loads plugins with the name `@prettier/plugin-*` or `prettier-plugin-*` from the nearest package.json up the file system tree.
=> Automatically load plugins from package.json

docs/plugins.md
* Add new [Swift Plugin](https://github.com/prettier/prettier-swift).
* Document automatic plugin loading.
=> Update plugins docs

website/pages/playground/index.html, website/static/playground.js, website/static/separate-css/playground.css, website/static/service-worker.js, website/static/worker.js
Fixes #3652
Preview: https://deploy-preview-3657--prettier.netlify.com/playground/
[Feel free to push examples to this PR directly as I'm not good at making examples.](https://github.com/prettier/prettier/pull/3657#discussion_r159911212) 😅
examples:
=> feat(playground): add example placeholder

src/common/fast-path.js, tests/spread/__snapshots__/jsfmt.spec.js.snap, tests/spread/spread.js
=> Wrap conditionals in parens in spread property

website/static/playground.js
see #3667
These are derived from Bootstrap, should there be a license comment?
=> playground: add (s)css examples

src/language-vue/parser-vue.js, src/language-vue/printer-vue.js, tests/vue_examples/__snapshots__/jsfmt.spec.js.snap, tests/vue_examples/self_closing.vue
=> Fix vue self-closing tags

src/language-vue/embed.js, tests/multiparser_vue/__snapshots__/jsfmt.spec.js.snap, tests/multiparser_vue/vue-component.vue
This PR enables the css parser for style blocks that have the lang attribute set to postcss
=> Enable PostCSS in VUE SFC

src/language-js/printer-estree.js, tests/test_declarations/__snapshots__/jsfmt.spec.js.snap, tests/test_declarations/test_declarations.js
Fixes #3706
https://api.qunitjs.com/QUnit/skip
=> Add support for skip() (#3706)

src/language-css/printer-postcss.js, tests/css_selector_list/__snapshots__/jsfmt.spec.js.snap, tests/css_selector_list/selectors.css
Issue: https://github.com/prettier/prettier/issues/3731
=> fix(scss/less): space after combinator operator

website/core/Footer.js
The interactive button links you to a page to follow the user directly, so I also added a direct link to the profile.
=> Use an SVG <object> tag to allow the Twitter button to be interactive

README.md
[Rendered version](https://github.com/j-f1/forked-prettier/tree/link-to-plugin-docs#readme)
Maybe it’s time to pare down this list.
=> Link to the plugin docs in the README

src/language-css/printer-postcss.js, tests/css_scss/__snapshots__/jsfmt.spec.js.snap, tests/css_scss/scss.css
=> fix: don't change case of function name

tests/css_media/__snapshots__/jsfmt.spec.js.snap, tests/css_media/media.css
=> tests: `@media` directive

src/language-css/printer-postcss.js, tests/css_import/__snapshots__/jsfmt.spec.js.snap, tests/css_import/url.css
=> fix: don't add comma after `url` in `@import` directive

tests/css_less/__snapshots__/jsfmt.spec.js.snap, tests/css_less/jsfmt.spec.js, tests/css_less/less.css
Seems we just don't run tests, also fix syntax and remove html tags
=> tests: `less` syntax

src/language-css/parser-postcss.js, tests/css_scss/__snapshots__/jsfmt.spec.js.snap, tests/css_scss/scss.css
=> fix: don't handle args of `@warn` and `@error` directives as media query list

tests/css_scss/__snapshots__/jsfmt.spec.js.snap, tests/css_scss/scss.css
Just many `scss` tests to make sure all work as expected. 
I would be glad to join `prettier` as contributor. I can take care of the problems associated with `css/less/scss`. I have many experience with `postcss` and his ecosystems, also i am top of contributors in `stylelint` :star:
=> tests: `scss` syntax

src/language-css/clean.js, src/language-css/printer-postcss.js, tests/css_attribute/__snapshots__/jsfmt.spec.js.snap, tests/css_attribute/insensitive.css, tests/css_attribute/quotes.css, tests/css_attribute/spaces.css, tests/stylefmt/attr-selector/__snapshots__/jsfmt.spec.js.snap
=> feat: remove extra spaces in attribute selector

tests/css_selector_list/__snapshots__/jsfmt.spec.js.snap, tests/css_selector_list/selectors.css
=> tests: multiple selector

src/language-css/clean.js, tests/css_attribute/__snapshots__/jsfmt.spec.js.snap, tests/css_attribute/spaces.css
Based on https://github.com/prettier/prettier/pull/3794#discussion_r163313410
=> fix(css): remove other types of whitespace in `clean`

tests/css_selector_list/__snapshots__/jsfmt.spec.js.snap, tests/css_selector_list/selectors.css
=> tests(css): newlines around multiple and combinator selectors

src/language-css/printer-postcss.js, tests/css_selector_list/__snapshots__/jsfmt.spec.js.snap, tests/css_selector_list/selectors.css
=> fix: keep space between deep selector `>>>`

tests/css_parens/__snapshots__/jsfmt.spec.js.snap, tests/css_parens/parens.css
=> tests(css): function parens

tests/css_atrule/__snapshots__/jsfmt.spec.js.snap, tests/css_atrule/namespaces.css
=> tests(css): namespace at rule

src/language-css/printer-postcss.js, tests/css_scss/__snapshots__/jsfmt.spec.js.snap, tests/css_scss/scss.css
Fixes #2554
[Playground]( https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASAtgQwA5IAQAUAOlHngNZwCee+BAxACYAcATI+wDR70Bs-ASk4kyEGAAs4AJwC0lGnXoBWVgCMAZgBZM3euv1CReMZNknpc6rUL0wrAMyb7S3fvUCSAgNwkMOfFjYMujSAOZwBH7Y3JHy+KgAbpgANgCucALeIJwgENgwAJbQAM7IoJhSUhAA7gAKFQilKJgJEAWM2SCYxTDI6inFcDmqUphglDAAythjBVChyDBS6TmMEGB9A0Mgc4NSMLWjoVibyYM5AFbFAB4AQqPjcFOYIQAyc3Cn57mpMNi-rC+2xmUj2yBAxTAxVKOWwUjmMAA6u0JMhmAAGWFVQaI0bYcFwuB7BKfHJSOAAR1SBXJh0wx0wQJyg3QBUWy22xTmoWScAAiqkxJ8kP0ztsYJhVMjGKikKwcktMAVktyAMIQdAnFBQaCkkCpQYAFUlTSW6QAvuagA)
Input:
```scss
$map: (
key : (#d82d2d, #666),
other-key : (#52bf4a, #fff),
other-other-key : (#c23435, #fff)
);
$map: map-merge($map, ($key: $value));
```
Output:
```scss
$map: (
key : (#d82d2d, #666),
other-key : (#52bf4a, #fff),
other-other-key : (#c23435, #fff)
); …
```
=> fix(css): remove whitespaces before ":" in scss maps

package.json, src/language-css/parser-postcss.js, src/language-css/printer-postcss.js, tests/css_yaml/__snapshots__/jsfmt.spec.js.snap, tests/css_yaml/jsfmt.spec.js, tests/css_yaml/yaml.css, tests/css_yaml/yaml.less, tests/css_yaml/yaml.scss, yarn.lock
=> fix: handle YAML front matter block

commands.md
=> docs(commands): fix malapropism 

tests/css_atrule/__snapshots__/jsfmt.spec.js.snap, tests/css_atrule/supports.css, tests/css_variables/__snapshots__/jsfmt.spec.js.snap, tests/css_variables/variables.css
Just tests to ensure we don't break `@supports` at rule code. But we can see some problems in snapshot. I think we should create separate issues on each problem (this merge as is for future tests). 
Wait comments on snapshots :smile:
=> tests(css): `supports` at rule

commands.md, src/doc/doc-builders.js, src/doc/doc-debug.js, src/doc/doc-printer.js, src/language-js/printer-estree.js, tests/ternaries/__snapshots__/jsfmt.spec.js.snap, tests/ternaries/indent.js, tests/ternaries/jsfmt.spec.js
Rewrite #3277, fixes #2771.
Rules:
- trailing alignments:
- still spaces.
- ~~middle alignments:~~ Removed, see https://github.com/prettier/prettier/pull/3745#issuecomment-357953038.
- ~~every `tabsWidth` spaces will be transformed into a tab.~~
Example:
- before
- `tabWidth = 2`
- `<tab><2 space><tab><2 space>` -> `<tab><tab><tab><tab>`
- `<tab><4 space><tab><2 space>` -> `<tab><tab><tab><tab>`
- `tabWidth = 4`
- `<tab><2 space><tab><2 space>` -> `<tab><tab><tab><tab>`
- `<tab><4 space><tab><2 space>` -> `<tab><tab><tab><tab>`
- after
- `tabWidth = 2`
- `<tab><2 space><tab><2 space>` -> `<tab><tab><tab><2 space>`
- `<tab><4 space><tab><2 space>` -> `<tab><tab><tab><2 space>`
- `tabWidth = 4`
- `<tab><2 space><tab><2 space>` -> `<tab><tab><tab><2 space>`
- `<tab><4 space><tab><2 space>` …
=> fix(javascript): ternary with `--use-tabs`

tests/css_atrule/__snapshots__/jsfmt.spec.js.snap, tests/css_atrule/font-face.css
=> tests(css): `font-face` at rule

src/language-css/parser-postcss.js, src/language-css/printer-postcss.js, tests/css_case/__snapshots__/jsfmt.spec.js.snap, tests/css_less/__snapshots__/jsfmt.spec.js.snap, tests/css_less/less.css
Fixes #3093
Also remove strange line from less tests
=> fix(css): don't remove semicolon in `less` ruleset declaration

docs/install.md
https://prettier.io/docs/en/install.html
=> docs: Same format for both options

docs/option-philosophy.md, docs/why-prettier.md, website/sidebars.json
Note to anyone finding this PR: This is not an attempt to impose _my_ philosophy on Prettier. I've tried hard to write down what I've gathered from the project during its ~1 year of existence.
=> Add option philosophy to docs

tests/css_atrule/__snapshots__/jsfmt.spec.js.snap, tests/css_atrule/custom-media.css, tests/css_case/__snapshots__/jsfmt.spec.js.snap, tests/css_case/case.css, tests/css_media/__snapshots__/jsfmt.spec.js.snap, tests/css_media/media.css
=> tests(css): custom media

src/language-css/printer-postcss.js
=> refactor(printer-postcss): use `node` name and implement helper functons

src/language-html/parser-parse5.js, src/language-html/printer-htmlparser2.js, website/core/Footer.js, website/pages/en/help/index.js, website/pages/en/index.js
We should either use it or remove it.. and in case that we need to find something we have the version control for it.
=> Remove commented out code

src/language-css/parser-postcss.js, src/language-css/printer-postcss.js, tests/css_comments/__snapshots__/jsfmt.spec.js.snap, tests/css_comments/declaration.css, tests/css_comments/variable-declaration.scss, tests/css_quotes/__snapshots__/jsfmt.spec.js.snap
Now we don't eat comments. We can merge this as is and in next PR discussion about place comments or do this here :+1: Welcome to feedback!
=> fix(css): declaration comments

tests/css_comments/__snapshots__/jsfmt.spec.js.snap, tests/css_comments/declaration.css
Fixes #2127
Just tests, we fixed this in https://github.com/prettier/prettier/pull/3897
Issue about pretty output comments https://github.com/prettier/prettier/issues/3905
=> tests(css): declaration comments

tests/css_comments/__snapshots__/jsfmt.spec.js.snap, tests/css_comments/selectors.css
=> tests(css): comments in selectors

tests/css_comments/__snapshots__/jsfmt.spec.js.snap, tests/css_comments/declaration.css, tests/css_comments/types.css
We don't eat standard comments :star: :star: :star:
=> tests(css): more comments tests

src/common/support.js, src/language-css/index.js, src/language-css/printer-postcss.js, src/language-graphql/index.js, src/language-graphql/printer-graphql.js, src/language-js/index.js, src/language-js/printer-estree.js, src/language-markdown/index.js, src/language-markdown/printer-markdown.js, tests_integration/plugins/options/plugin.js
Context: https://github.com/prettier/prettier/pull/3775#discussion_r162777806
=> feat(plugins): change external options to be plugin-level

website/static/worker.js
=> Set os.EOL in worker.js

docs/editors.md
=> Mention vscode-status-bar-format-toggle in the docs

src/language-css/parser-postcss.js, src/language-css/printer-postcss.js, tests/css_atrule/__snapshots__/jsfmt.spec.js.snap, tests/css_atrule/mixin.css, tests/css_atrule/return.css, tests/css_comments/__snapshots__/jsfmt.spec.js.snap, tests/css_parens/__snapshots__/jsfmt.spec.js.snap, tests/css_scss/__snapshots__/jsfmt.spec.js.snap, tests/css_scss/scss.css
Fixes #2128  fixes #2126
Notes:
1. Refactor logic around spaces
2. Add more tests
3. Fix stupid error around `...` in scss
After merge this i will do PR which improve arithmetic operators.
Right now we have simply logic and it is very maintainable.
=> fix(css): space and newlines before parenthesis

docs/plugins.md, index.js
* locStart / locEnd functions
* util-shared
=> Document new plugin API features

src/language-css/printer-postcss.js, tests/css_selector_list/__snapshots__/jsfmt.spec.js.snap, tests/css_selector_list/selectors.css
Ref: https://developer.mozilla.org/en-US/docs/Web/CSS/@namespace
=> fix(css): don't eat selector namespace

tests/css_case/__snapshots__/jsfmt.spec.js.snap, tests/css_case/case.css, tests/css_case/case.less, tests/css_case/case.scss, tests/css_color/__snapshots__/jsfmt.spec.js.snap, tests/css_color/current-color.css, tests/css_color/functional-syntax.css, tests/css_color/hexcolor.css, tests/css_color/whitespace-syntax.css
=> tests(css): colors

tests/css_case/__snapshots__/jsfmt.spec.js.snap, tests/css_case/case.css, tests/css_case/case.less, tests/css_case/case.scss
=> tests(css): more tests around pseudo-classes and pseudo-elements

src/language-css/parser-postcss.js, tests/css_postcss_plugins/__snapshots__/jsfmt.spec.js.snap, tests/css_postcss_plugins/jsfmt.spec.js, tests/css_postcss_plugins/postcss-mixins.css, tests/css_postcss_plugins/postcss-nested-props.css, tests/css_postcss_plugins/postcss-nested.css
=> tests(css): postcss popular plugins

tests/css_comments/__snapshots__/jsfmt.spec.js.snap, tests/css_comments/source-map.css
=> tests(css): source map comment

package.json, src/language-js/printer-estree.js, tests/typescript_unique_symbol/__snapshots__/jsfmt.spec.js.snap, tests/typescript_unique_symbol/jsfmt.spec.js, tests/typescript_unique_symbol/unique-symbol.ts, yarn.lock
=> fix(typescript): support `unique symbol`

website/data/editors.yml, website/data/languages.yml, website/data/users.yml
=> Remove unnecessary quotes from YAML configuration files

src/common/fast-path.js, tests/flow_type_cast/__snapshots__/jsfmt.spec.js.snap, tests/flow_type_cast/expression.js, tests/flow_type_cast/jsfmt.spec.js, tests/flow_type_cast/statement.js
=> Wrap ternaries in Flow typecasts in parens

src/language-css/parser-postcss.js, tests/css_modules/__snapshots__/jsfmt.spec.js.snap, tests/css_modules/jsfmt.spec.js, tests/css_modules/modules.css, tests/css_postcss_plugins/__snapshots__/jsfmt.spec.js.snap, tests/css_postcss_plugins/postcss-nesting.css
=> fix(css): `@nest` at rule

src/language-js/printer-estree.js, tests/flow/declare_export/__snapshots__/jsfmt.spec.js.snap, tests/flow_type_declarations/__snapshots__/jsfmt.spec.js.snap, tests/flow_type_declarations/declare_export.js, tests/flow_type_declarations/jsfmt.spec.js
=> Fix cases with missing semi when printing DeclareExportDeclaration

src/common/fast-path.js, tests/typescript_non_null/__snapshots__/jsfmt.spec.js.snap, tests/typescript_non_null/parens.ts
=> Keep parens around Unary and Update Expressions

website/core/Footer.js
Fixes #3980
I basically based this change on looking at the "Blog" link. Please let me know if there's a way to test the site, didn't get it by reading CONTRIBUTING.md.
=> Fix links in footer

website/static/playground.js
Not sure if this is a good or useful example case.
Fixes #3994.
=> Add JSON example

docs/plugins.md
Just to give a bit more exposure to some of the other plugins.. I'm aware of the fact that they might be far from done, but promoting them from here could attract more people.
=> Add more plugins to the plugins section

website/pages/googlefe164a33bda4034b.html
In order to enable the [webmaster tools](https://www.google.com/webmasters/) we need this file.
Once verified I can add owners to the project.
=> Add Google Site Verification file

docs/plugins.md, website/data/languages.yml
=> Add Ruby to homepage and <code>

website/package.json
=> Add license to website/package.json

package.json, src/language-js/printer-estree.js, tests/typescript_definite/__snapshots__/jsfmt.spec.js.snap, tests/typescript_definite/definite.ts, tests/typescript_definite/jsfmt.spec.js, yarn.lock
=> feat(typescript): support definite assignment (`!:`)

src/language-css/parser-postcss.js, tests/css_case/__snapshots__/jsfmt.spec.js.snap, tests/css_case/case.less, tests/css_comments/__snapshots__/jsfmt.spec.js.snap, tests/css_comments/at-rules.css
Fix and tests. Basic comments tested around 100%.
=> Css tests at rules

docs/webstorm.md
Webstorm now supports prettier!
=> Webstorm now supports Prettier

src/language-css/printer-postcss.js
=> refactor(css): printer

docs/precommit.md
As discussed in the [issue](https://github.com/prettier/prettier/issues/2978#issuecomment-350511918), here is my proposition of the documentation enhancement.
=> Enhancing pre-commit bash script documentation.

src/language-css/printer-postcss.js, tests/css_case/__snapshots__/jsfmt.spec.js.snap, tests/css_case/case.less, tests/css_case/case.scss
=> fix: don't lowercase nesting selector

docs/vim.md, package.json, yarn.lock
=> Bump own prettier dependency version to 1.11.0

src/main/options.js, tests_integration/__tests__/__snapshots__/deprecated-parser.js.snap, tests_integration/__tests__/deprecated-parser.js
=> fix(api): no regression for deprecated parser

.github/ISSUE_TEMPLATE.md
I've noticed many people apologizing for not using the issue template where there has been absolutely no reason to apologize! The issue template is not meant for _all_ types of issues.
=> Try to clarify when to use the issue template

website/pages/en/index.js
Hi! Was just looking through the documentation and noticed a typo on the landing page. Figured I'd make a quick PR. Thanks for all the work you all do on Prettier!
=> Fix typo on on landing page of site

src/language-markdown/embed.js, tests/multiparser_markdown_css/__snapshots__/jsfmt.spec.js.snap, tests/multiparser_markdown_css/css-comment.md, tests/multiparser_markdown_css/jsfmt.spec.js, tests/multiparser_markdown_js/__snapshots__/jsfmt.spec.js.snap, tests/multiparser_markdown_js/jsx-comment.md
Fixes #3889
<details>
<summary>playground</summary>
**Prettier pr-4083**
[Playground link](https://deploy-preview-4083--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEBDAzgEwDpVwA0IAcx11cA6AQQDdUZUAnAAmF2eYHoAqZi-5t0652zAGQB9CQEsAtqgDmcVqI48+AoSKgcOAAUixU0qHBYAKAO7TMMABbMAfMwCMABjdEAHgEoVO3TVuVV0AYTtUKCVmdAhZZXQYAE8AGzh0Zmhme2U5RWU4NPjYZks7BGzy5kMGEzNmaXIAwOtMevtI1w9vEI4tZuYAX1FhvACDaFrTCwwiODAYAFpGemkIJ2YAZj82AfVwyOjE1PTMnRzmVDoGFmkYdEKAMwAaUvLzqtn5pZWYNYaMgpfu0IjpNoJhAFRqIJkY6hZWvYNu5PL5LlBMMxzOVpAo7DBkd00btAup+BQISNcKNCPgQM8QBAiH9oOhkKAmIwIJYAApMBBslBXCA2eloRLIR6oFIPBkAIxWYAA1nAYABlIioMAmBTIGCMACucAZmAgYEl0tlIBMD0YMB5KwU8gtMuNIAAVugvAAhRUq9WoeIAGTqLqtEANMCIkYATHrDW7NYxbcgQPJGErTZYoGKiIwTDAAOo2ezIAAcbgZeYgD0LKyIqbz6TMNDgYsYcAAjgbpB2HYpnUgpa6GQ9ZNJ40bRzq0gBFA0QeBht0MOXF2x2ZAxhn64wpHWh …
=> fix(markdown): print literalline for newline instead of hardline

src/cli/util.js, tests_integration/__tests__/__snapshots__/ignore-path.js.snap, tests_integration/__tests__/ignore-path.js
=> Fix printing ignored files with --debug-check

package.json, tests/css_comments/__snapshots__/jsfmt.spec.js.snap, tests/css_comments/selectors.scss, yarn.lock
=> chore: update `postcss-scss` to latest version

docs/precommit.md, tests/markdown/__snapshots__/jsfmt.spec.js.snap, tests/markdown/real-world-case.md
This commit was automated with the following script:
```bash
git grep -l 'pre-commit\.com' |
xargs sed -i 's|http://pre-commit\.com|https://pre-commit.com|g'
```
=> pre-commit.com is now served on https

website/pages/en/index.js
=> More than 80,000 dependent repositories

docs/plugins.md
=> New links for plugin URLs

docs/rationale.md
I tried to write something down for common issues.
=> Add more stuff to the Rationale page

website/static/playground.js
Fixes #3667.
I tried to come up with examples that are somewhat real-world, not too complicated and that showcases some of Prettier's strengths.
=> Add playground examples for all languages

package.json, src/language-css/printer-postcss.js, tests/css_parens/__snapshots__/jsfmt.spec.js.snap, tests/css_parens/parens.css
=> fix: handle `unicode-range`

docs/plugins.md
Documents #3685
Context: #3557
=> Add docs on new pragma infrastructure

tests/html_aurelia/__snapshots__/jsfmt.spec.js.snap, tests/html_aurelia/basic.html, tests/html_aurelia/jsfmt.spec.js
Just tests.
@zakjan Nothing broken, only ugly :smile:
=> tests(html): aurelia non standard attributes

src/language-html/parser-parse5.js, tests/html_basics/__snapshots__/jsfmt.spec.js.snap, tests/html_basics/html-comments.html
=> fix(html): support comment on top

src/language-css/parser-postcss.js, src/language-css/printer-postcss.js, tests/css_modules/__snapshots__/jsfmt.spec.js.snap, tests/css_modules/modules.css
=> fix: don't lowercase variable in css modules

website/static/worker.js
I'm not sure how it happened, but *preview playground* seems broken:
(https://deploy-preview-4151--prettier.netlify.com/playground/)
=> fix(playground): no undefined parsers

src/language-js/printer-estree.js, tests/switch/__snapshots__/jsfmt.spec.js.snap, tests/switch/switch.js
:+1: 
Based on https://github.com/prettier/plugin-php/pull/229#discussion_r175168487
=> feat: indent in discriminant switch

website/static/playground.js
Mostly for the tables :)
[<sub><sub><img 
height="20" src="https://avatars0.githubusercontent.com/oa/117514?s=40&u=f5bc93150a0ab17d693f6c71629caa3d07feb72a&v=4"></sub></sub> Preview playground link](https://deploy-preview-4176--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEIA0IIAcYEtoDOyoAhgE5kQDuACuQkSiQG4S4Am6IJBMyAZiQA2BOBgBGZEmADWcGAGUs03FADmyGGQCuYkOwhgBw0RlWiyMGlLUBbEsZF6AVgQAeAISmz5CkrbgAGVU4R1NMbRgsSIAmML1lMgtkEHsyGQMqKC4sMlUYAHUOGAALZAAOAAYMXIhRAqksFNy4C2ZQjDI4AEdtXC7rEjsHJEEnDFFbXE0dPQJVNSE4AEVtCHh4jBgScSL2UuQYralcIQWAYQhbexSoaA6QbVEAFR3GMdEAX0+gA)
=> Richer markdown example in the playground

tests/css_comments/CRLF.css, tests/css_comments/CRLF.less, tests/css_comments/CRLF.scss, tests/css_comments/__snapshots__/jsfmt.spec.js.snap
=> tests: comments with `CRLF`

src/language-js/printer-estree.js
We now always return a conditional group.
=> Remove outdated comment

website/data/languages.yml
Supplements #4161
Sorry for not doing all in one PR – I thought the website is build from a different repo. Can there be other lists of plugins that I have missed?
=> Add Elm plugin to website's home page

package.json, src/language-css/printer-postcss.js, tests/css_comments/__snapshots__/jsfmt.spec.js.snap, tests/css_comments/lists.scss, tests/css_comments/maps.scss, yarn.lock
fixes #4074
Very ugly, but don't break code.
Issue around pretty output https://github.com/prettier/prettier/issues/3716
I will fix ugly format in other PR in near future.
=> fix: inline comments in lists and maps

src/language-css/parser-postcss.js, tests/css_inline_url/__snapshots__/jsfmt.spec.js.snap, tests/css_inline_url/inline_url.css
=> fix: don't break value property with inlined URL

package.json, yarn.lock
=> chore(deps): update `html-tag-names` package

docs/configuration.md, scripts/generate-schema.js
Fixes #4247
- generate schema: `node ./scripts/generate-schema.js > ./schema.json`
- test schema (vscode):
- Add a `./.vscode/settings.json`
```json
{
"json.schemas": [
{
"fileMatch": ["/schema-test.json"],
"url": "/schema.json"
}
]
}
```
- Add a `./schema-test.json` and type whatever you'd like to test.
cc @nbosscher
=> chore: add a script to generate schema

website/pages/playground/index.html, website/static/playground.js
=> fix(playground): correct rangeStart/rangeEnd value

website/blog/2018-04-09-plugin-php-0.1.md
[Rendered](https://github.com/czosel/prettier/blob/ae37dfa66112426dfe9e501c52681c93c493aa45/website/blog/2018-04-09-plugin-php-0.1.md)
@vjeux
=> Blog post announcing first alpha release of PHP plugin

src/language-js/printer-estree.js, tests/test_declarations/__snapshots__/jsfmt.spec.js.snap, tests/test_declarations/angular_async.js
=> Inline Angular async tests and beforeEach, etc.

package.json, src/language-js/parser-flow.js, tests/optional_chaining/jsfmt.spec.js, yarn.lock
Flow now support ?. so this PR enables it in prettier
=> [flow] Upgrade flow to 0.69 and enable ?. support

package.json, scripts/build/build-docs.js, website/package.json, website/yarn.lock, yarn.lock
Nothing relevant, just moving a dependency to its correct place
=> Move sw-toolbox to `website` dependencies

src/language-js/embed.js, tests/multiparser_js_css/__snapshots__/jsfmt.spec.js.snap, tests/multiparser_js_css/styled-components.js
fixes #4301
Recommend patch release, before we don't merge something
=> fix: correct prettier placeholder regex

src/language-markdown/embed.js
Fixes the playground crashing in #4306.
=> fix(markdown): null check for code.lang
