prettier/prettier

- src/language-js/print/literal.js
- src/main/core.js
> Fix for eslint-plugin-unicorn v36

- scripts/build/bundler.mjs
- scripts/build/config.mjs
It was broken, I was trying to fix it, ~but seems working...~ showhow we lost the `terserOptions`
> Minify `parser-postcss.js`

- CHANGELOG.md
Address https://github.com/prettier/prettier/pull/10961/files#r646808184
> Fix changelog for #10961

- scripts/release/steps/publish-to-npm.js
> Remove unnecessary text from `publish-to-npm` step

- docs/plugins.md
Add prettier-plugin-erb to documentation
> Add prettier-plugin-erb to documentation

- .eslintrc.js
- scripts/build/rollup-plugins/evaluate.mjs
- src/config/resolve-config.js
- src/document/doc-utils.js
- src/language-handlebars/printer-glimmer.js
- src/language-js/needs-parens.js
- src/language-js/print/jsx.js
- Update config
- Enable some new `unicorn` rules
> Update eslint config

- src/language-js/parse/espree.js
- src/language-js/parse/flow.js
- src/language-js/parse/meriyah.js
- src/language-js/parse/typescript.js
https://github.com/prettier/prettier/pull/11557#discussion_r715807885
> Remove unnecessary copying options for parsers

- package.json
- src/language-js/parse/babel.js
- src/language-js/print/module.js
- yarn.lock
I'll create Pull Requests to support new features later.
> Update to `@babel/parser` 7.16

- changelog_unreleased/typescript/11721.md
- src/language-js/print/module.js
- tests/format/misc/typescript-babel-only/__snapshots__/jsfmt.spec.js.snap
- tests/format/misc/typescript-babel-only/type-only-module-specifiers.ts
Base on #11722
Partial of #11600
> (only `babel-ts`) Support TypeScript 4.5 type-only module specifiers

- changelog_unreleased/javascript/11750.md
- src/language-js/parse/babel.js
- tests/format/js/sloppy-mode/__snapshots__/jsfmt.spec.js.snap
- tests/format/js/sloppy-mode/delete-variable.js
- tests/format/js/sloppy-mode/jsfmt.spec.js
> Fix error on deleting variables

- scripts/tools/eslint-plugin-prettier-internal-rules/no-identifier-n.js
> Fix internal ESLint plugin

- changelog_unreleased/javascript/11750.md
- tests/format/js/sloppy-mode/__snapshots__/jsfmt.spec.js.snap
- tests/format/js/sloppy-mode/function-declaration-in-lf.js
- tests/format/js/sloppy-mode/function-declaration-in-while.js
- tests/format/js/sloppy-mode/jsfmt.spec.js
https://github.com/prettier/prettier/pull/11778#discussion_r744426191 from @fisker 
> Add more tests, update changelog

- changelog_unreleased/javascript/11800.md
- src/language-css/printer-postcss.js
- src/language-css/utils.js
- tests/format/js/multiparser-css/__snapshots__/jsfmt.spec.js.snap
- tests/format/js/multiparser-css/issue-11797.js
> Respect spacing for between expressions and parentheses in embedded CSS

- scripts/release/package.json
- scripts/release/steps/install-dependencies.js
- scripts/release/steps/post-publish-steps.js
- scripts/release/steps/publish-to-npm.js
- scripts/release/steps/update-changelog.js
- scripts/release/utils.js
- scripts/release/yarn.lock
> Update execa to v6 for release script

- package.json
- yarn.lock
> Update typescript to 4.5.2

- .github/workflows/prod-test.yml
- changelog_unreleased/api/11830.md
- scripts/build/build.mjs
- scripts/build/bundler.mjs
- tests/integration/__tests__/early-exit.js
> Drop support for Node.js 10

- package.json
- yarn.lock
> Update `string-width` to v4.2.3

- scripts/build/README.md
- scripts/build/build.mjs
- scripts/build/bundler.mjs
- scripts/release/steps/generate-bundles.js
1. Add `--minify` and `--no-minify` flags, for debug purpose
2. Change `--purge-cache` to `--no-cache`
3. Add readme, closes #11817
> Update build script

- package.json
- yarn.lock
> Update `postcss-scss` to v4.0.2

- scripts/build/bundler.mjs
This should work the same as #11868
I didn't run test on local, let's see if the CI passes.
> Build: Remove aliases

- scripts/build/README.md
> Add build script requirements

- changelog_unreleased/javascript/11892.md
I'm not good at English, hope this is fine.
> Add changelog for #11892

- package.json
Removes `prepare-release` script that isn't used now.
> Remove `prepare-release` script

- src/language-js/parse/postprocess/visitNode.js
The new array path avoids creation of an `entries` iterator. The object path is something that has been
benchmarked to be a fast way to iterate over objects.
For an example case I had (about 2000 line .js file) this change brought
preprocess time down from 50ms to about 20ms.
Here are the `--debug-repeat` results for 100 iterations on Node.js v16.13.0. Before:
```
[debug] '--debug-repeat' option found, running formatWithCursor 100 times.
[debug] '--debug-repeat' measurements for formatWithCursor: {
[debug]   "repeat": 100,
[debug]   "hz": 7.541478129713425,
[debug]   "ms": 132.6
[debug] }
```
After:
```
[debug] '--debug-repeat' option found, running formatWithCursor 100 times.
[debug] '--debug-repeat' measurements for formatWithCursor: {
[debug]   "repeat": 100,
[debug]   "hz": …
```
> Optimize visitNode by specialising by node type

- .github/FUNDING.yml
- package.json
I also moved `open_collective` link to top.
> Add `funding` field to package.json

- package.json
- yarn.lock
> Update `tempy` to v2

- .eslintrc.js
- src/common/end-of-line.js
- src/language-html/parser-html.js
- src/language-js/parse/postprocess/index.js
> Enable `unicorn/prefer-switch`

- netlify.toml
"Ubuntu Focal 20.04" is the default build image, https://app.netlify.com/sites/prettier/settings/deploys, I tried to switch it before, but fails because of  https://github.com/netlify/build-image/issues/599, now that issue has been closed, let's see if it works.
> Update netlify config

- .pre-commit-hooks.yaml
It has been over a year, time to remove it. #8937
> Remove `.pre-commit-hooks.yaml`

- src/cli/context.js
- src/cli/expand-patterns.js
- src/cli/file-info.js
- src/cli/find-config-path.js
- src/cli/format.js
- src/cli/index.js
- src/cli/options/get-options-for-file.js
- src/cli/options/parse-cli-arguments.js
- tests/integration/__tests__/__snapshots__/arg-parsing.js.snap
- tests/integration/__tests__/arg-parsing.js
> Use camelCase cli arguments internally

- changelog_unreleased/css/9209.md
This was accidentally deleted somewhere I can't remember during revert, adding it back.
> Add changelog back

- src/cli/context.js
- src/index.js
> Simplify cli options stack

- docs/related-projects.md
- website/versioned_docs/version-stable/related-projects.md
[CSharpier](https://github.com/belav/csharpier) started as a prettier plugin, but I ran into performance issues with the overhead of starting a new .Net console app for each file. I ported the core prettier printing process to .Net instead and turned it into a .Net tool.
> Add csharpier to "Related Projects"

- .eslintrc.js
- scripts/tools/eslint-plugin-prettier-internal-rules/await-cli-tests.js
- scripts/tools/eslint-plugin-prettier-internal-rules/index.js
- scripts/tools/eslint-plugin-prettier-internal-rules/no-multiple-cli-tests.js
- scripts/tools/eslint-plugin-prettier-internal-rules/test.js
> Add internal ESLint rule `await-cli-tests`

- .eslintrc.js
- scripts/clean-cspell.mjs
- scripts/release/utils.js
> Enable `unicorn/prefer-json-parse-buffer` and `unicorn/no-useless-promise-resolve-reject` rule

- docs/precommit.md
- website/versioned_docs/version-stable/precommit.md
Dotnet developers should use a dotnet-tool solution along with prettier
> docs: Add Husky.Net option

- changelog_unreleased/javascript/12017.md
- src/language-js/comments.js
- src/language-js/printer-estree.js
- src/language-js/utils.js
- tests/format/js/if/__snapshots__/jsfmt.spec.js.snap
- tests/format/js/if/expr_and_same_line_comments.js
> Preserve end-of-line comment for if statement without blocks

- website/blog/2022-01-06-prettier-begins-paying-maintainers.md
Adds a new blog post "Prettier begins paying maintainers".
> Add a new blog post

- .eslintrc.js
- package.json
- yarn.lock
Enable https://typescript-eslint.io/rules/prefer-ts-expect-error
> Enable `@typescript-eslint/prefer-ts-expect-error`

- changelog_unreleased/javascript/12088.md
- src/language-js/print/jsx.js
- tests/format/jsx/jsx/__snapshots__/jsfmt.spec.js.snap
- tests/format/jsx/jsx/await.js
I went to introduce the changes made in #12088 to my project and noticed that I missed this case.
- ~(If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).~
> Collapse JSXExpressionContainer → AwaitExpression → JSXElement

- scripts/release/steps/bump-prettier.js
- scripts/release/steps/update-version.js
- src/language-html/embed.js
- src/language-js/parse/postprocess/typescript.js
https://lgtm.com/projects/g/prettier/prettier?mode=list
> Fix some lgtm alerts

- scripts/build/bundler.mjs
- scripts/build/shims/assert.cjs
> Exclude `assert` shim

- package.json
- scripts/build/build.mjs
- scripts/build/bundler.mjs
- scripts/build/config.mjs
- scripts/build/shims/assert.cjs
- scripts/build/shims/debug.cjs
- yarn.lock
> Exclude `process` shim

- scripts/build/config.mjs
Reduce minify file ~30k, I've done this before, but I thought people don't care package size that much.
> Remove `ts.sys` in `parser-typescript.js`

- scripts/build-website.mjs
- scripts/build/README.md
- scripts/build/build.mjs
- scripts/build/bundler.mjs
Add `--no-babel` flag for debugging purposes.
> Build: Add `--no-babel` flag

- package.json
- scripts/build/README.md
- scripts/build/build.mjs
- scripts/build/bundler.mjs
- scripts/build/esbuild-plugins/visualizer.mjs
- yarn.lock
Based on this comment https://github.com/prettier/prettier/issues/12144#issuecomment-1021335260
> Build: Add `--report` flag

- scripts/build/README.md
- scripts/build/build.mjs
- scripts/build/bundler.mjs
- scripts/build/esbuild-plugins/visualizer.mjs
Turns out there is a built-in method can analyze meta file, let's support it too. https://esbuild.github.io/api/#analyze
> Build: More reporter format

- scripts/build/config.mjs
- scripts/build/shims/babel-highlight.cjs
- scripts/build/shims/chalk.cjs
Fixes #12181
```diff
- standalone.js...................................................478 kB    DONE
+ standalone.js...................................................433 kB    DONE
```
> Drop color support for `standalone` build

- changelog_unreleased/javascript/12222.md
- src/language-js/comments.js
- src/language-js/print/class.js
- tests/format/js/class-comment/__snapshots__/jsfmt.spec.js.snap
> Preserve comment position before super class

- README.md
As far as I know, `raw.githubusercontent.com` is unreachable in some country. 
The SVG version is smaller, so I chose this one.
`.svg` file can also be able to switch to dark mode automatically (buggy in chrome), maybe I'll try later.
> Update banner image url

- tests/format/js/logical-assignment/__snapshots__/jsfmt.spec.js.snap
- tests/format/js/logical-assignment/jsfmt.spec.js
> Run tests for logical-assignment operators with `flow`

- scripts/sync-flow-tests.js
- src/language-js/parse/flow.js
- src/language-js/parse/postprocess/index.js
- tests/format/js/classes/__snapshots__/jsfmt.spec.js.snap
- tests/format/js/classes/asi.js
- tests/format/js/export-star/__snapshots__/jsfmt.spec.js.snap
- tests/format/js/export-star/export-star-as-default.js
- tests/format/js/export-star/export-star-as-string.js
- tests/format/js/export-star/export-star-as-string2.js
- tests/format/js/export-star/jsfmt.spec.js
> Follow up work for `flow-parser@0.171.0`

- yarn.lock
> Regenerate `yarn.lock`

- .github/workflows/validate-vendor-versions.yml
> Skip `validate-vendor-versions` on `push`

- package.json
- yarn.lock
> Remove `babel-loader`

- .eslintrc.js
- .github/workflows/dev-test.yml
- bin/package.json
- bin/prettier.js
- jest.config.mjs
- package.json
- src/cli/constant.js
- src/cli/context.js
- src/cli/expand-patterns.js
- src/cli/file-info.js
- src/cli/find-config-path.js
- src/cli/format.js
- src/cli/index.js
- src/cli/is-tty.js
- src/cli/logger.js
- src/cli/options/create-minimist-options.js
- src/cli/options/get-context-options.js
- src/cli/options/get-options-for-file.js
- src/cli/options/minimist.js
- src/cli/options/option-map.js
- src/cli/options/parse-cli-arguments.js
- src/cli/package.json
- src/cli/prettier-internal.js
- src/cli/usage.js
- src/common/load-plugins.js
- tests/integration/__tests__/early-exit.js
- tests/integration/__tests__/help-options.js
- tests/integration/run-prettier.js
> Migrate CLI to ES Module

- .eslintrc.js
- tests/config/install-prettier.js
I don't have infinity disk space to debug `yarn test:dist`
> Clean installed Prettier after test

- changelog_unreleased/javascript/12241.md
Address https://github.com/prettier/prettier/pull/12276#issuecomment-1036989099
> Add changelog for unicode set notation proposal

- package.json
- scripts/vendors/vendor-meta.json
- scripts/vendors/vendors.mjs
- tests/config/install-prettier.js
- tests/integration/__tests__/file-info.js
- vendors/execa.js
- vendors/tempy.d.ts
- vendors/tempy.js
- vendors/types.d.ts
- yarn.lock
It's a pure ESM package.
ref: https://github.com/sindresorhus/tempy/releases/tag/v2.0.0
> Update `tempy` to `2.0.0`

- scripts/vendors/README.md
> Update docs about `./scripts/vendors`

- .eslintrc.js
- src/language-yaml/utils.js
Improve readability
Ref https://github.com/prettier/prettier/pull/12305#discussion_r806796468
> Style: Minor refactor

- changelog_unreleased/cli/12320.md
- cspell.json
- src/language-js/index.js
- tests/integration/__tests__/__snapshots__/support-info.js.snap
- tests/integration/__tests__/with-parser-inference.js
SWC is a blazing fast JavaScript transpiler written with Rust.
`.swcrc` is a JSON file that configures SWC. Please see https://swc.rs/docs/configuration/swcrc for more details.
> Format `.swcrc` as a JSON file

- scripts/build/build.mjs
> Build: Fix `--compare-size`

- .eslintrc.cjs
- scripts/build/bundler.mjs
- scripts/build/config.mjs
- scripts/build/esbuild-plugins/evaluate.mjs
- scripts/bundle-eslint-config.cjs
- src/language-markdown/clean.js
- src/language-markdown/constants.evaluate.js
- src/language-markdown/embed.js
- src/language-markdown/index.js
- src/language-markdown/loc.js
- src/language-markdown/mdx.js
- src/language-markdown/options.js
- src/language-markdown/package.json
- src/language-markdown/parser-markdown.js
- src/language-markdown/parsers.js
- src/language-markdown/pragma.js
- src/language-markdown/print-preprocess.js
- src/language-markdown/printer-markdown.js
- src/language-markdown/unified-plugins/front-matter.js
- src/language-markdown/unified-plugins/html-to-jsx.js
- src/language-markdown/unified-plugins/liquid.js
- src/language-markdown/unified-plugins/loose-items.js
- src/language-markdown/unified-plugins/wiki-link.js
- src/language-markdown/utils.js
- src/languages.js
Based on #12278, should merge that one first.
Part of #10157
> Migrate Markdown language to ES Module

- .eslintrc.cjs
- scripts/build/bundler.mjs
- scripts/build/config.mjs
- scripts/bundle-eslint-config.cjs
- src/language-graphql/index.js
- src/language-graphql/loc.js
- src/language-graphql/options.js
- src/language-graphql/package.json
- src/language-graphql/parser-graphql.js
- src/language-graphql/parsers.js
- src/language-graphql/pragma.js
- src/language-graphql/printer-graphql.js
- src/languages.js
Part of https://github.com/prettier/prettier/issues/10157
> Migrate GraphQL language to ES Module

- .eslintrc.cjs
- scripts/build/bundler.mjs
- scripts/build/config.mjs
- src/language-yaml/embed.js
- src/language-yaml/index.js
- src/language-yaml/loc.js
- src/language-yaml/options.js
- src/language-yaml/package.json
- src/language-yaml/parser-yaml.js
- src/language-yaml/parsers.js
- src/language-yaml/pragma.js
- src/language-yaml/print-preprocess.js
- src/language-yaml/print/block.js
- src/language-yaml/print/flow-mapping-sequence.js
- src/language-yaml/print/mapping-item.js
- src/language-yaml/print/misc.js
- src/language-yaml/printer-yaml.js
- src/language-yaml/utils.js
- src/languages.js
> Migrate YAML language to ES Module

- .eslintrc.cjs
- scripts/build/bundler.mjs
- scripts/build/config.mjs
- src/language-css/clean.js
- src/language-css/embed.js
- src/language-css/index.js
- src/language-css/loc.js
- src/language-css/options.js
- src/language-css/package.json
- src/language-css/parser-postcss.js
- src/language-css/parsers.js
- src/language-css/pragma.js
- src/language-css/printer-postcss.js
- src/language-css/utils/has-scss-interpolation.js
- src/language-css/utils/has-string-or-function.js
- src/language-css/utils/index.js
- src/language-css/utils/is-module-rule-name.js
- src/language-css/utils/is-scss-nested-property-node.js
- src/language-css/utils/is-scss-variable.js
- src/language-css/utils/stringify-node.js
- src/languages.js
> Migrate CSS language to ES Module

- .eslintrc.cjs
- package.json
- scripts/build/bundler.mjs
- scripts/build/config.mjs
- src/language-handlebars/clean.js
- src/language-handlebars/index.js
- src/language-handlebars/loc.js
- src/language-handlebars/package.json
- src/language-handlebars/parser-glimmer.js
- src/language-handlebars/parsers.js
- src/language-handlebars/printer-glimmer.js
- src/language-handlebars/utils.js
- src/languages.js
- yarn.lock
> Migrate Handlebars language to ES Module

- package.json
- scripts/build/bundler.mjs
- yarn.lock
https://esbuild.github.io/api/#platform
Backport #12372
> Build: Add `platform: "node"`

- src/cli/options/get-options-for-file.js
- src/cli/options/parse-cli-arguments.js
- src/main/options-normalizer.js
> Remove `leven` from `standalone.js`

- package.json
- yarn.lock
https://github.com/sindresorhus/leven/releases/tag/v4.0.0
> Update `leven` to v4

- package.json
- yarn.lock
https://github.com/chalk/strip-ansi/releases/tag/v7.0.0
https://github.com/chalk/strip-ansi/releases/tag/v7.0.1
> Update `strip-ansi` to v7

- scripts/vendors/vendor-meta.json
- vendors/tempy.js
> Regenerate vendors

- changelog_unreleased/javascript/12349.md
- src/language-js/print/assignment.js
- tests/format/js/assignment-comments/__snapshots__/jsfmt.spec.js.snap
- tests/format/js/assignment-comments/call.js
- tests/format/js/assignment-comments/call2.js
> Fix idempotence issues caused by eol comments after = in assignments

- docs/index.md
According to https://prettier.io/blog/2021/05/09/2.3.0.html#ember--handlebars, Handlebars support has been officially released, whereas it is not vividly mentioned on the main docs page.
> Mention Handlebars in the docs

- scripts/build/esbuild-plugins/evaluate.mjs
- src/language-html/constants.evaluate.js
- src/language-html/utils/index.js
> build: Fix evaluate plugin

- scripts/build/bundler.mjs
- scripts/build/config.mjs
- scripts/build/esbuild-plugins/replace-module.mjs
> Build: Improve `replaceModule` plugin

- scripts/build/esbuild-plugins/umd.mjs
> Build: Improve umd bundle output

- scripts/build/bundler.mjs
> Build: Fix `require()` package.json file

- scripts/build/bundler.mjs
- scripts/build/config.mjs
> Build: Remove `isEsm` mark

- package.json
- scripts/build/bundler.mjs
- scripts/build/config.mjs
- scripts/build/esbuild-plugins/replace-text.mjs
- yarn.lock
Replace `esbuild-plugin-text-replace` with our own plugin, I'm planning to do more complex replacements.
> Add `esbuildPluginReplaceText`

- package.json
- scripts/vendors/vendor-meta.json
- scripts/vendors/vendors.mjs
- src/cli/format.js
- src/cli/logger.js
- src/cli/options/get-options-for-file.js
- src/cli/options/parse-cli-arguments.js
- tests/config/install-prettier.js
- vendors/chalk.d.ts
- vendors/chalk.js
- yarn.lock
Closes #12417
Bundled `cli.js` file reduces ~28kb
> Update `chalk` to v5

- src/main/options-normalizer.js
I added this in #12382 at first, but somehow lost it .. 
> Add `levenshteinDistance` option check

- tests/config/format-test.js
- tests/config/utils/create-snapshot.js
> Prevent plugin search on format test

- scripts/build/config.mjs
Fix broken comment added in #12462, sorry for the mistake.
> Fix comment

- scripts/build/bundler.mjs
- scripts/build/config.mjs
> Build: Remove `mainFields` override

- scripts/build/esbuild-plugins/umd.mjs
> Build: Remove an extra new line in UMD bundle

- scripts/release/release.js
- website/pages/en/index.js
> Run prettier after release

- scripts/build/config.mjs
- scripts/build/esbuild-plugins/replace-module.mjs
- src/cli/format.js
I'm not sure if this will work, let's make test pass before I commit to `next` branch.
> Build: Fix build script for `next` branch

- scripts/utils/generate-schema.js
- tests/integration/__tests__/__snapshots__/schema.js.snap
> Fix `pluginSearchDirs` schema

- website/blog/2022-03-16-2.6.0.md
> Minor tweak to the blog post

- scripts/build/esbuild-plugins/replace-module.mjs
> Build: Fix `esbuildPluginReplaceModule`

- cspell.json
- website/pages/en/index.js
> Minor tweak to the website

- .prettierrc
Can't believe we are using different parsers formatting js files..
> Fix `.prettierrc`

- scripts/release/steps/install-dependencies.js
Without this, `update-stable-docs` may fail.
> Install dependencies for website in release script

- .github/workflows/check-sizes.yml
- .github/workflows/prod-test.yml
The build script is fast enough, let's run this on every PR.
> Run size check on every PR

- package.json
- yarn.lock
> Use `jest-light-runner` from npm

- changelog_unreleased/cli/12603.md
- src/language-js/index.js
- tests/format/misc/parser-inference/__snapshots__/jsfmt.spec.js.snap
- tests/format/misc/parser-inference/test.importmap
- tests/integration/__tests__/__snapshots__/support-info.js.snap
> Format `.importmap` file with `json-stringify` parser

- package.json
- src/cli/options/create-minimist-options.js
- src/cli/options/parse-cli-arguments.js
- src/cli/usage.js
- src/cli/utils.js
- src/common/create-ignorer.js
- src/common/get-file-info.js
- src/common/load-plugins.js
- src/config/resolve-config.js
- src/index.js
- src/main/core-options.js
- src/main/multiparser.js
- src/main/options-normalizer.js
- src/main/support.js
- src/utils/partition.js
- src/utils/uniq-by-key.js
- tests/format/markdown/auto-link/jsfmt.spec.js
- tests/integration/__tests__/file-info.js
- website/playground/sidebar/SidebarOptions.js
> Remove `lodash`

- docs/ignore.md
- website/versioned_docs/version-stable/ignore.md
> Please describe what prettier ignores by default

- changelog_unreleased/vue/12584.md
- src/language-html/embed.js
- src/language-html/print-preprocess.js
- src/language-html/utils/index.js
- src/language-js/parse/babel.js
- src/language-js/parse/parsers.js
- src/language-js/print-preprocess.js
- src/language-js/printer-estree.js
- src/main/comments.js
- tests/format/vue/ts-event-binding/__snapshots__/jsfmt.spec.js.snap
- tests/format/vue/ts-event-binding/basic.vue
- tests/format/vue/ts-event-binding/jsfmt.spec.js
- tests/format/vue/ts-expression/__snapshots__/jsfmt.spec.js.snap
- tests/format/vue/ts-expression/basic.vue
- tests/format/vue/ts-expression/jsfmt.spec.js
- tests/format/vue/ts-expression/not-working-with-non-ts-script.vue
> Allow formatting for Vue template expression written in TypeScript

- .github/workflows/dev-test.yml
- .github/workflows/prod-test.yml
> Run tests on Node.js v18

- jest.config.js
- src/language-js/clean.js
- src/language-js/utils/index.js
- src/language-js/utils/is-block-comment.js
> Refactor JS utils

- src/language-css/utils/has-string-or-function.js
- src/language-css/utils/index.js
- src/language-css/utils/is-scss-variable.js
- src/language-css/utils/stringify-node.js
> Refactor CSS utils

- .github/dependabot.yml
> Target dependabot to `next` branch

- src/cli/constant.js
- src/cli/context.js
- src/cli/format.js
- src/cli/index.js
- src/cli/options/create-minimist-options.js
- src/cli/options/get-context-options.js
- src/cli/options/get-options-for-file.js
- src/cli/options/normalize-cli-options.js
- src/cli/options/option-map.js
- src/cli/prettier-internal.js
- src/cli/utils.js
- src/index.js
> Update prettier-internal.js exports for easier use

- website/playground/sidebar/SidebarOptions.js
> Fix website

- .github/workflows/dev-package-test.yml
- tests/config/install-prettier.js
> Try to fix pnpm error on Dev Package Tests

- package.json
- yarn.lock
> Remove `@babel/core` and `@babel/preset-env`

- .eslintrc.cjs
- website/siteConfig.js
> Simplify eslint config

- changelog_unreleased/api/12574.md
- docs/api.md
- src/cli/context.js
- src/cli/index.js
- src/cli/options/get-context-options.js
- src/cli/options/get-options-for-file.js
- src/cli/options/parse-cli-arguments.js
- src/common/load-plugins.js
- src/index.js
- src/standalone.js
- tests/format/misc/empty/jsfmt.spec.js
- tests/integration/__tests__/debug-api.js
- tests/integration/__tests__/format-ast.js
- tests/integration/__tests__/help-options.js
- tests/integration/__tests__/schema.js
- tests/integration/__tests__/support-info.js
- tests/integration/run-prettier.js
Prepare for ESM plugins support.
> Load plugins asynchronously

- scripts/build/config.mjs
- src/document/index.js
- src/index.js
- src/language-html/print/tag.js
- src/language-html/printer-html.js
- src/language-js/print/array.js
- src/language-js/print/binaryish.js
- src/language-js/print/block.js
- src/language-js/print/flow.js
- src/language-js/print/function.js
- src/language-js/print/module.js
- src/language-js/print/object.js
- src/language-js/print/statement.js
- src/language-js/print/ternary.js
- src/language-js/printer-estree.js
- src/language-markdown/printer-markdown.js
- src/language-yaml/print/block.js
- src/language-yaml/print/mapping-item.js
- src/language-yaml/printer-yaml.js
- src/standalone.js
> Use named export in doc.js

- src/cli/constant.js
> Sort options alphabetically by ESLint `sort-keys` rule

- .github/renovate.json5
- .github/workflows/lint.yml
> Validate renovate config

- src/cli/options/create-minimist-options.js
Reduce loops, improve readability
> Simplify `createMinimistOptions`

- src/common/create-ignorer.js
- src/common/get-file-info.js
- src/utils/read-file.js
> Simplify `getFileInfo()`

- website/static/worker.js
> Fix v3 website

- tests/config/format-test-setup.js
- tests/config/format-test.js
- tests/config/get-prettier.js
- tests/format/js/cursor/jsfmt.spec.js
> Improve format test setup

- changelog_unreleased/javascript/12860.md
- src/language-js/comments.js
- tests/format/js/comments/__snapshots__/jsfmt.spec.js.snap
- tests/format/js/comments/export-and-import.js
- tests/format/js/comments/export.js
> Fix exports comment formats.

- website/yarn.lock
> Refresh `yarn.lock` in `/website`

- README.md
- tests/format/markdown/markdown/__snapshots__/jsfmt.spec.js.snap
- tests/format/markdown/markdown/real-world-case.md
- website/core/Footer.js
Remove all references to the Gitter room
- ~I’ve added tests to confirm my change works.~
- ~(If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).~
- ~(If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.~
> Remove all references to Gitter

- changelog_unreleased/html/12882.md
- cspell.json
- src/language-html/utils/index.js
- tests/format/html/script/__snapshots__/jsfmt.spec.js.snap
- tests/format/html/script/script.html
Support Speculation Rules API in HTML.
**refs:**
- https://github.com/WICG/nav-speculation
- https://web.dev/speculative-prerendering/
> Support Speculation Rules API formatting in HTML

- tests/integration/cli-worker.js
> Test: Use `import()` to run CLI test

- package.json
- yarn.lock
I'll send some PRs to support new features later.
> Update `@babel/parser` to `7.18.0`

- changelog_unreleased/typescript/12896.md
Adds changelog for #12896, #12897, #12898, #12900
> Add changelog for TypeScript 4.7

- .github/renovate.json5
> Group `@babel/*` PRs except `@babel/parser`

- package.json
- scripts/build/bundler.mjs
- scripts/build/config.mjs
- scripts/build/esbuild-plugins/throw-warnings.mjs
- src/main/load-parser.js
- src/main/parser.js
- yarn.lock
Closes #12949
[`logOverride` option](https://github.com/evanw/esbuild/blob/HEAD/CHANGELOG.md#%E2%80%8B01442)
> Build: stricter warning check

- changelog_unreleased/vue/12895.md
- src/language-html/print/tag.js
- src/language-html/utils/index.js
- tests/format/vue/single-attribute-per-line/__snapshots__/jsfmt.spec.js.snap
- tests/format/vue/single-attribute-per-line/sfc-blocks.vue
> Avoid printing attribute per line in Vue SFC blocks

- package.json
- tests/format/js/regex/__snapshots__/jsfmt.spec.js.snap
- tests/format/js/regex/jsfmt.spec.js
- tests/format/misc/errors/flow/__snapshots__/jsfmt.spec.js.snap
- tests/format/misc/errors/invalid/__snapshots__/jsfmt.spec.js.snap
- tests/format/typescript/typeparams/consistent/__snapshots__/jsfmt.spec.js.snap
- yarn.lock
> Update dependency flow-parser to v0.180.0

- package.json
- tests/format/typescript/typeof-this/__snapshots__/jsfmt.spec.js.snap
- tests/format/typescript/typeof-this/decorators.ts
- tests/format/typescript/typeof-this/jsfmt.spec.js
- tests/format/typescript/typeof-this/typeof-this.ts
- yarn.lock
> Update dependency @typescript-eslint/typescript-estree to v5.30.0

- changelog_unreleased/cli/13076.md
- changelog_unreleased/cli/13081.md
- cspell.json
- src/language-yaml/embed.js
- src/language-yaml/index.js
- tests/integration/__tests__/__snapshots__/support-info.js.snap
- tests/integration/__tests__/with-parser-inference.js
Treat filename `.lintstagedrc` (without any extension) [as YAML/JSON format](https://github.com/okonet/lint-staged#configuration).
> Support `.lintstagedrc`

- .eslintrc.js
- package.json
- src/language-css/parser-postcss.js
- src/language-css/printer-postcss.js
- yarn.lock
[prefer-logical-operator-over-ternary](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-logical-operator-over-ternary.md)
> Enable `unicorn/prefer-logical-operator-over-ternary` rule

- changelog_unreleased/angular/13100.md
- src/language-js/print/binaryish.js
- tests/format/angular/angular/__snapshots__/jsfmt.spec.js.snap
- tests/format/angular/bracket-same-line/__snapshots__/jsfmt.spec.js.snap
- tests/format/angular/interpolation/__snapshots__/jsfmt.spec.js.snap
> Insert spaces in pipe

- scripts/build/README.md
We get error `[ERROR] [plugin replace-module] text.replaceAll is not a function` if run build script in node 14.18.
> Update requirements for build script

- .github/workflows/prod-test.yml
- changelog_unreleased/api/11830.md
- scripts/build/build.mjs
- scripts/build/bundler.mjs
https://github.com/prettier/prettier/issues/10157#issuecomment-1185483173
> Drop Node.js 12 Support

- .eslintrc.cjs
- scripts/tools/eslint-plugin-prettier-internal-rules/index.js
- scripts/tools/eslint-plugin-prettier-internal-rules/prefer-fs-promises-submodule.js
- scripts/tools/eslint-plugin-prettier-internal-rules/prefer-fs-promises.js
- scripts/tools/eslint-plugin-prettier-internal-rules/test.js
- src/cli/format.js
- src/cli/utils.js
- src/common/load-plugins.js
- src/utils/read-file.js
We can use `fs/promises` because we've dropped Node.js v12.
> [next]Enforce `fs/promises`

- src/config/get-prettier-config-explorer.js
- src/config/resolve-config.js
- src/config/resolve-editorconfig.js
- Simplify logic
- Improve readability
> Refactor `resolveConfig`

- jest.config.mjs
> Remove outdated code

- src/language-markdown/parser-markdown.js
We can use async parser now.
~This call seems not doing anything.~ 
> Migrate markdown parser to async

- src/index.js
This was planned when I migrate this module to ESM, but before we add `--cache` to CLI.
Rename this may cause confusing, let's keep it as it is in v3.
> Remove a TODO

- package.json
- tests/format/misc/errors/js/assignment/__snapshots__/jsfmt.spec.js.snap
- yarn.lock
> Update acorn to v8.8.0

- tests/config/format-test.js
- tests/format/js/strings/__snapshots__/jsfmt.spec.js.snap
- tests/format/js/strings/jsfmt.spec.js
For unknown reason, this test fails sometime, it's blocking https://github.com/babel/babel/pull/14779#discussion_r928137651
> Disable a test

- website/data/languages.yml
- website/versioned_docs/version-stable/plugins.md
Hiya! I made a prettier plugin for rust! 😄
https://github.com/jinxdash/prettier-plugin-rust
Note that I'm unsure as to whether the change at `website/data/languages.yml` is eligible as it does not list all community plugins
I'm `jinxdash#6529` on discord if someone in the core team wants to quick message questions or suggestions 🙂
> Add rust to community plugins

- tests/integration/__tests__/cache.js
- tests/integration/__tests__/log-level.js
- tests/integration/cli-worker.js
- tests/integration/run-prettier.js
> Refactor CLI tests

- .eslintrc.cjs
- jest.config.mjs
- src/common/ast-path.js
- src/language-js/print/call-arguments.js
- tests/unit/ast-path.js
Use `try/finally` in `AstPath`, make them `try/catch` friendly.
> Use `try/finally` in `AstPath`

- src/cli/context.js
- src/cli/format-results-cache.js
- src/common/ast-path.js
- src/main/options-normalizer.js
> Use private fields

- website/pages/en/index.js
- website/static/overrides.css
Just to make it a bit more discoverable.
> Link option philosophy from the main page

- tests/integration/run-prettier.js
Used the wrong flag. Ref https://github.com/prettier/prettier/pull/13211#issuecomment-1207277185
> Fix test on local

- src/document/invalid-doc-error.js
- tests/integration/__tests__/__snapshots__/print-doc-to-string.js.snap
- tests/integration/__tests__/print-doc-to-string.js
> Imporve error message for `InvalidDocError`

- changelog_unreleased/javascript/10714.md
- src/language-js/print/function-parameters.js
- tests/format/flow/last-argument-expansion/__snapshots__/jsfmt.spec.js.snap
- tests/format/flow/last-argument-expansion/break.js
- tests/format/flow/last-argument-expansion/decorated-function.js
- tests/format/flow/last-argument-expansion/edge_case.js
- tests/format/flow/last-argument-expansion/jsfmt.spec.js
- tests/format/typescript/last-argument-expansion/decorated-function.ts
- tests/format/typescript/last-argument-expansion/jsfmt.spec.js
> Support decorated function pattern

- .eslintrc.cjs
- scripts/build/config.mjs
- src/language-graphql/parser-graphql.js
- src/language-handlebars/parser-glimmer.js
- src/language-js/parse/angular.js
- src/language-js/parse/babel.js
- src/language-js/parse/flow.js
- src/language-js/parse/json.js
- src/language-js/parse/meriyah.js
- src/language-js/parse/typescript.js
- src/language-yaml/parser-yaml.js
Size change not because `import()`, I changed entry to more specific file.
**Size Change:** -131 kB (-1%) 
**Total Size:** 15.1 MB
| `./dist/esm/parser-angular.mjs` | 54.9 kB | +[197](https://github.com/prettier/prettier/runs/7740832606?check_suite_focus=true#step:4:209) B (0%) |  |
| `./dist/esm/parser-babel.mjs` | 295 kB | +143 B (0%) |  |
| `./dist/esm/parser-flow.mjs` | 1.04 MB | +65 B (0%) |  |
| `./dist/esm/parser-glimmer.mjs` | 129 kB | -57.6 kB (-31%) | 🎉 |
| `./dist/esm/parser-graphql.mjs` | 33.9 kB | -5.09 kB (-13%) | 👏 |
| `./dist/esm/parser-meriyah.mjs` | 147 kB | +24 B (0%) |  |
| `./dist/esm/parser-typescript.mjs` | 3.55 MB | -3.33 kB (0%) |  |
| `./dist/esm/parser-yaml.mjs` | 123 kB | +105 B (0%) |  |
| …
> Use `import()` in parsers

- src/language-html/ast.js
- src/language-html/conditional-comment.js
- src/language-html/parser-html.js
> Use `import()` for html parser

- docs/plugins.md
Add [`prettier-plugin-prisma`](https://github.com/umidbekk/prettier-plugin-prisma) by `umidbekk` to list of community plugins
> Add `prettier-plugin-prisma` to list of community plugins

- scripts/build/config.mjs
- src/language-css/parser-postcss.js
> Use `import()` for postcss parsers

- .eslintrc.cjs
[no-unused-expressions](https://eslint.org/docs/latest/rules/no-unused-expressions)
Prevent mistake like this https://github.com/prettier/prettier/pull/13268#discussion_r945879599
> Enable `no-unused-expressions` rule

- src/language-graphql/loc.js
> graphql: Explicit location getter

- src/language-graphql/parser-graphql.js
> Keep tokens in graphql AST

- src/document/printer.js
Ref: https://github.com/prettier/prettier/pull/13154#issuecomment-1193129381
//cc @thorn0
> Move `groupModeMap` into `printDocToString`

- cspell.json
- docs/plugins.md
Added `prettier-plugin-nginx` to Community Plugins list. Includes changelog and cspell update.
> Added `prettier-plugin-nginx` to Community Plugins list

- yarn.lock
> Fix lock file

- src/document/utils.js
Use one `switch` by using `getDocType`
> Minor refactor to `cleanDoc`

- src/document/utils.js
- src/language-html/printer-html.js
- src/language-yaml/printer-yaml.js
> Minor refactor to `mapDoc`

- src/document/invalid-doc-error.js
- src/document/utils.js
- src/document/utils/get-doc-type.js
> Check all doc types in `mapDoc`

- changelog_unreleased/api/12574.md
I built a sync version of Prettier APIs. Just in case people need.
[`prettier-sync`](https://github.com/fisker/prettier-sync)
> Mention `@prettier/sync` in changelog

- src/document/utils.js
> Check all types in `cleanDoc`

- docs/plugins.md
[Previous version can't be formatted. ](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEADdMDOAdKAzAVyjBgEtoAKXbGAeloAIAVACzgYEEBlJhqCACbtIAJxFxMAB2gDSUAOYMYEJWwaQAthoQxqu-Zu2wknHgBo99ZmsIAbWw0wQCIsMMHt4AD11Qa3mBNMGBE5eQs-OkZWdnlbCAAjAEMHCEkyaEwGRIArOBI9NIyoTBNc-JgImisY0yY9JOCTbiYqqIYAdTYYNhFVUizDHQYB1XZbRph1CC0dPQGAGUmAYRmjQIYEiAhbOCS-KABKEy2dvYP0VBAzECLyEuRQJLEIAHcABWeETGQQFNekgBPH43BIiJJgADWcBgXCS2gWcjgyDwKUwcFB4KhMK4kghYWQIQIGJAcA0CTgAiEAiWCgISXkcAAYhARBokjAyApfkkCMpriAWDANLYuqR4FIIXAuN9xaQAG7iwG-MCYEEgOTokQwd7g+TslFokk5TBeLhhXYARQIEHghts6JueJEWt+7JEkIEbygAskoVgHVIAh6yAAHAAGJ0iCDojrgyS-P0SOAieXIm4ARxt8F1aR+KEaAFooHBKZSBeIs6RxLqGQakKiHST0RpSISRMSbpgLXBrbbkQ2jTcYEkEoHgyxkAAmYfg0i2MKrLRJX4SACsAoI6KYo-zjcdIHlxIAklAhLAuGBQukOGeuDBAbt7eiAL4voA) …
> Docs: Fix handleComments function signature

- src/language-js/print/member-chain.js
- src/language-js/utils/index.js
Refactor `isSimpleCallArgument` and make it a bit stricter
> Refactor isSimpleCallArgument

- src/document/utils.js
- src/document/utils/traverse-doc.js
- tests/unit/traverse-doc.js
> Check all types in `traverseDoc`

- src/language-js/print/object.js
> Refactor printObject

- changelog_unreleased/javascript/13391.md
- src/language-js/print/function.js
- tests/format/js/arrows/__snapshots__/jsfmt.spec.js.snap
- tests/format/js/arrows/chain-as-arg.js
- tests/format/js/arrows/chain-in-logical-expression.js
> Fix arrow chain indentation in calls and binaries

- src/language-graphql/printer-graphql.js
- src/language-handlebars/printer-glimmer.js
- src/language-html/printer-html.js
- src/language-js/print/angular.js
- src/language-js/print/jsx.js
- src/language-js/print/typescript.js
- src/language-js/printer-estree.js
- src/language-markdown/printer-markdown.js
- src/language-yaml/printer-yaml.js
- src/language-yaml/visitor-keys.js
- src/utils/unexpected-node-error.js
- tests/unit/__snapshots__/visitor-keys.js.snap
> Add print pre-check to `handlebars`, `html`, `markdown`, `yaml`

- src/common/parser-create-error.js
- src/language-css/parser-postcss.js
- src/language-graphql/parser-graphql.js
- src/language-handlebars/parser-glimmer.js
- src/language-html/parser-html.js
- src/language-js/parse/acorn.js
- src/language-js/parse/espree.js
- src/language-js/parse/flow.js
- src/language-js/parse/json.js
- src/language-js/parse/meriyah.js
- src/language-js/parse/postprocess/index.js
- src/language-js/parse/postprocess/throw-ts-syntax-error.js
- src/language-js/parse/postprocess/typescript.js
- src/language-js/parse/typescript.js
- src/language-js/parse/utils/create-babel-parse-error.js
- src/language-yaml/parser-yaml.js
- src/main/parser.js
> Add `cause` to parse error

- src/language-css/printer-postcss.js
The test passed, but I'm not really confidence about this change, the AST we parsed into is very strange.
> Add print pre-check to CSS printer

- src/language-css/printer-postcss.js
- src/language-graphql/printer-graphql.js
- src/language-handlebars/printer-glimmer.js
- src/language-html/printer-html.js
- src/language-js/print/assignment.js
- src/language-js/print/class.js
- src/language-js/print/type-annotation.js
- src/language-js/printer-estree.js
- src/language-markdown/printer-markdown.js
- src/language-yaml/printer-yaml.js
- src/main/ast-to-doc.js
- src/main/create-print-pre-check-function.js
- src/utils/create-get-visitor-keys.js
> Move print pre-check into core

- scripts/generate-changelog.mjs
> Fix generated changelog comment for css like syntax

- src/document/printer.js
> Simplify print command `trim`

- website/playground/Playground.js
- website/playground/dummyId.js
- website/playground/panels.js
- website/playground/util.js
> Playground: press ctrl-q to generate a dummy id

- package.json
- src/language-js/traverse/union-visitor-keys.js
- src/language-js/traverse/visitor-keys.evaluate.js
- tests/unit/__snapshots__/visitor-keys.js.snap
- yarn.lock
[hermes](https://github.com/facebook/hermes) is a Meta(facebook) production.
> Use visitor keys from "hermes-eslint"

- .github/renovate.json5
> Group `@typescript-eslint/*` dependencies in renovate config

- scripts/draft-blog-post.mjs
Avoid to print multiple truncate comment to draft post
> Fix generate truncate comment

- .github/workflows/dev-package-test.yml
- .github/workflows/dev-test.yml
- package.json
- scripts/build/build.mjs
https://github.com/prettier/prettier/issues/13142#issuecomment-1238966462
> Drop Node.js 14 for development build

- src/language-handlebars/parser-glimmer.js
> Glimmer: Combine plugins to reduce traverse

- src/common/ast-path.js
> Avoid throwing in path getters

- src/common/ast-path.js
- src/main/create-print-pre-check-function.js
> Simplify print pre-check with `AstPath` getters

- scripts/tools/eslint-plugin-prettier-internal-rules/better-parent-property-check-in-needs-parens.js
- scripts/tools/eslint-plugin-prettier-internal-rules/test.js
- src/language-js/needs-parens.js
> Use `AstPath` getters in `needs-parens.js`

- docs/browser.md
- scripts/release/steps/update-version.js
- website/versioned_docs/version-stable/browser.md
> Fix unpkg link

- src/common/util.js
- src/language-html/parser-html.js
- src/language-html/utils/index.js
- src/language-markdown/embed.js
- src/utils/infer-parser-by-language.js
To reduce bundle size. Found this during #13482
**Size Change:** -60.8 kB (-1%) 
**Total Size:** 10.9 MB
| `./dist/esm/parser-html.mjs` | 116 kB | -16.1 kB (-12%) | 👏 |
| `./dist/esm/parser-markdown.mjs` | 121 kB | -14.4 kB (-11%) | 👏 |
| `./dist/esm/standalone.mjs` | 423 kB | +14 B (0%) |  |
| `./dist/index.js` | 1.3 MB | +137 B (0%) |  |
| `./dist/parser-html.js` | 117 kB | -16.1 kB (-12%) | 👏 |
| `./dist/parser-markdown.js` | 121 kB | -14.4 kB (-11%) | 👏 |
| `./dist/standalone.js` | 423 kB | +14 B (0%) |  |
> Extract `inferParserByLanguage` to seperate file

- src/language-css/utils/index.js
> Simplify `getAncestorNode` in css

- package.json
- scripts/build/modify-typescript-module.mjs
- yarn.lock
Improve string replace speed with `magic-string`. 18s -> 0.8s
> Improve typescript bundle speed

- scripts/build/bundler.mjs
- scripts/build/config.mjs
- tests/integration/env.js
> Bundle `third-party.js` in ESM

- scripts/build/bundler.mjs
> Use ESM version of parsers in bundles

- scripts/build/build-javascript-module.js
- scripts/build/build-license.js
- scripts/build/build-package-json.js
- scripts/build/build.mjs
- scripts/build/config.mjs
> Build: Refactor build script

- .eslintrc.cjs
- src/cli/format.js
- src/document/printer.js
- src/language-css/clean.js
- src/language-css/parser-postcss.js
- src/language-html/print/children.js
- src/language-js/clean.js
- src/language-js/utils/index.js
I was expecting more.. but we were already pretty good on that one. Another autofixable rule
> style: Add new ESLint rule `no-lonely-if` and `unicorn/no-lonely-if`

- .eslintrc.cjs
- src/language-html/parser-html.js
- src/language-markdown/printer-markdown.js
- tests/integration/__tests__/plugin-api-embed.js
`no-constant-binary-expression`
https://eslint.org/docs/latest/rules/no-constant-binary-expression
Should be able to prevent mistake
`object-shorthand`
Add option `avoidExplicitReturnArrows`
https://eslint.org/docs/latest/rules/object-shorthand#avoidexplicitreturnarrows
I think it's nicer
`unicorn/prefer-set-has`
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-set-has.md
It's useful, was removed for annoying, it's improved.
`import/no-anonymous-default-export`
https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-anonymous-default-export.md#options
Update to only check functions and classes, it's annoying sometimes.
> Enable some ESLint rules

- scripts/build/build-javascript-module.js
- src/language-js/pragma.js
> Reduce size of `standalone.js`

- .github/workflows/bundler-friendly.yml
- scripts/tools/bundle-test/index.js
> Fix "Bundler Friendly" test

- .eslintrc.cjs
- src/document/printer.js
- src/language-css/printer-postcss.js
- src/language-graphql/printer-graphql.js
- src/language-handlebars/printer-glimmer.js
- src/language-html/embed.js
- src/language-html/printer-html.js
- src/language-html/utils/index.js
- src/language-js/needs-parens.js
- src/language-js/parse/postprocess/index.js
- src/language-js/print/flow.js
- src/language-js/print/statement.js
- src/language-js/print/typescript.js
- src/language-js/printer-estree.js
- src/language-markdown/printer-markdown.js
- src/language-yaml/printer-yaml.js
[`unicorn/switch-case-braces`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/HEAD/docs/rules/switch-case-braces.md)
> Enable `unicorn/switch-case-braces` rule

- scripts/build/modify-typescript-module.mjs
https://github.com/prettier/prettier/pull/13592#issuecomment-1272471148
**Size Change:** -19.7 kB (0%) 
**Total Size:** 10.7 MB
| `./dist/plugins/typescript.js` | 1.43 MB | -9.87 kB (-1%) |
| `./dist/plugins/typescript.mjs` | 1.43 MB | -9.87 kB (-1%) |
<details><summary>ℹ️ <strong>View Unchanged</strong></summary>
| Filename | Size |
| :--- | :---: |
| `./dist/bin` | 4.1 kB |
| `./dist/bin/prettier.cjs` | 2.14 kB |
| `./dist/doc.js` | 61.9 kB |
| `./dist/doc.mjs` | 58.1 kB |
| `./dist/index.cjs` | 32.3 kB |
| `./dist/index.mjs` | 1.25 MB |
| `./dist/internal` | 4.1 kB |
| `./dist/internal/cli.mjs` | 440 kB |
| `./dist/internal/third-party.mjs` | 307 kB |
| `./dist/LICENSE` | [242](https://github.com/prettier/prettier/actions/runs/321721 …
> Reduce size of `typescript` plugin

- src/language-js/print/angular.js
> Minor refactor to angular printer

- changelog_unreleased/javascript/13621.md
- src/language-js/print/template-literal.js
- tests/format/js/template-literals/__snapshots__/jsfmt.spec.js.snap
- tests/format/js/template-literals/indention.js
> Fix template literal indention

- package.json
- scripts/build/build-javascript-module.js
- scripts/bundle-eslint-config.cjs
https://github.com/prettier/prettier/actions/runs/3240942212/jobs/5312224967#step:6:6
> Fix bundled `index.cjs`

- package.json
- scripts/build/build-javascript-module.js
- yarn.lock
> Update `yaml-unist-parser` to v2

- scripts/build/config.mjs
- scripts/build/reuse-document-module.js
**Size Change:** -34 kB (0%) 
**Total Size:** 10.7 MB
| `./dist/index.mjs` | 1.22 MB | -34 kB (-3%) |
> Reduce size of `index.mjs`

- scripts/build/config.mjs
**Size Change:** -108 kB (-1%) 
**Total Size:** 10.6 MB
| `./dist/LICENSE` | 241 kB | -1.84 kB (-1%) |
| `./dist/plugins/typescript.js` | 1.38 MB | -53.1 kB (-4%) |
| `./dist/plugins/typescript.mjs` | 1.37 MB | -53.1 kB (-4%) |
> Update `typescript` plugin build script

- src/cli/options/get-options-for-file.js
- src/cli/options/normalize-cli-options.js
- src/cli/prettier-internal.js
- src/index.js
- src/main/options-normalizer.js
- src/main/options.js
> Move `normalizeCliOptions` into `cli/`

- src/language-handlebars/printer-glimmer.js
- src/language-handlebars/utils.js
> Refactor `handlebars` print

- scripts/build/build-javascript-module.js
> Build: fix `outdent` entry

- src/language-graphql/print/description.js
- src/language-graphql/printer-graphql.js
> Minor refactor to `graphql` print

- package.json
- src/language-html/ast.js
- src/language-html/conditional-comment.js
- src/language-html/parser-html.js
- tsconfig.json
- yarn.lock
Pass `angularHtmlParser` around, instead of making everything async.
> Update `angular-html-parser` to v2.1.0

- src/document/utils.js
- tests/unit/strip-trailing-hardline.js
- Make the internal function pure.
- Check all doc types
> Minor refactor to `stripTrailingHardline`

- src/cli/expand-patterns.js
- src/cli/prettier-internal.js
- src/index.js
This module is quite big
**Size Change:** -180 kB (-2%) 
**Total Size:** 10.1 MB
| `./dist/index.mjs` | 1.18 MB | +91 B (0%) |  |
| `./dist/internal/cli.mjs` | 259 kB | -180 kB (-41%) | 🎉 |
> Share `fast-glob` module between core and CLI

- src/index.cjs
- tests/integration/__tests__/bundle.js
> Add `__debug` apis to cjs version

- scripts/build/esbuild-plugins/evaluate.mjs
> Fix `esbuildPluginEvaluate`

- scripts/draft-blog-post.mjs
> Fix generate truncate comment (backport #13437)

- .eslintrc.cjs
- scripts/build/shims/at.js
- scripts/build/shims/string-replace-all.js
- scripts/build/transform/index.js
- scripts/release/steps/update-dependents-count.js
- scripts/tools/eslint-plugin-prettier-internal-rules/jsx-identifier-case.js
- src/cli/expand-patterns.js
- src/language-css/clean.js
- src/language-graphql/printer-graphql.js
- src/language-html/embed.js
- src/language-html/printer-html.js
- src/language-html/utils/index.js
- src/language-js/print/jsx.js
- src/language-markdown/printer-markdown.js
- src/language-yaml/printer-yaml.js
- tests/unit/syntax-transform.js
- website/playground/VersionLink.js
> Enable `unicorn/prefer-string-replace-all` rule

- src/language-js/parse/postprocess/index.js
- src/language-js/parse/postprocess/typescript.js
- src/language-js/parse/typescript.js
- tests/format/misc/errors/typescript/__snapshots__/jsfmt.spec.js.snap
- tests/format/misc/errors/typescript/declare-getter.ts
- tests/format/misc/errors/typescript/declare-setter.ts
Ref: https://github.com/prettier/prettier/issues/9760#issuecomment-826302645
> TypeScript: Throw errors for 'declare' in accessors

- src/main/core.js
- src/main/massage-ast.js
- tests/unit/massage-ast.js
> Add test for `massageAst`

- package.json
- yarn.lock
> Remove `node-fetch`

- src/language-js/parse/postprocess/ts-syntax-kind.evaluate.js
- src/language-js/parse/postprocess/typescript.js
> Auto evaluate `ts.SyntaxKind`

- .github/codeql/codeql-config.yml
- .github/workflows/codeql.yml
- .github/workflows/eslint-rules.yml
- .github/workflows/release-script-test.yml
- src/language-markdown/printer-markdown.js
- tests/format/markdown/linkReference/__snapshots__/jsfmt.spec.js.snap
- tests/format/markdown/linkReference/title.md
- website/pages/playground/index.html
- website/static/service-worker.js
> Add CodeQL Analysis workflow

- changelog_unreleased/typescript/13764.md
I forgot to apply review by @kachkaev https://github.com/prettier/prettier/pull/13872#discussion_r1028606671
> Update changelog for `satisfies`

- .eslintrc.cjs
- src/language-js/printer-estree.js
- src/utils/create-get-visitor-keys.js
- website/playground/util.js
- [unicorn/no-typeof-undefined](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-typeof-undefined.md)
> Enable `unicorn/no-typeof-undefined` rule

- package.json
- yarn.lock
Changelog https://github.com/davidtheclark/cosmiconfig/blob/main/CHANGELOG.md#800
**Size Change:** -81.7 kB (-1%) 
**Total Size:** 9.63 MB
| `./dist/internal/third-party.mjs` | 225 kB | -83.2 kB (-27%) | 🎉 |
| `./dist/LICENSE` | 249 kB | +1.51 kB (+1%) |  |
> Update `cosmiconfig` to v8

- src/language-css/printer-postcss.js
- src/language-html/print/tag.js
- src/language-js/print/binaryish.js
- src/language-js/print/block.js
- src/language-js/print/jsx.js
- src/language-js/print/object.js
- src/language-js/print/statement.js
- src/language-js/printer-estree.js
- src/language-markdown/printer-markdown.js
> Use `AstPath` getters

- src/language-js/print/enum-members.js
- src/language-js/print/flow.js
- src/language-js/print/typescript.js
> Extract `printEnumMembers`

- package.json
- scripts/build/config.mjs
- scripts/sync-flow-tests.cjs
- src/language-js/needs-parens.js
- src/language-js/parse/postprocess/index.js
- src/language-js/print/flow.js
- src/language-js/print/literal.js
- src/language-js/traverse/visitor-keys.evaluate.js
- tests/format/flow-repo/enums/__snapshots__/jsfmt.spec.js.snap
- tests/format/flow-repo/enums/declared.js
- tests/format/flow-repo/enums/jsfmt.spec.js
- tests/format/flow-repo/enums/lib.js
- tests/format/flow/declare-opaque-type/__snapshots__/jsfmt.spec.js.snap
- tests/format/flow/declare-opaque-type/issue-13848-2.js
- tests/format/flow/declare-opaque-type/issue-13848.js
- tests/format/flow/declare-opaque-type/jsfmt.spec.js
- tests/unit/__snapshots__/visitor-keys.js.snap
- yarn.lock
https://github.com/facebook/flow/releases/tag/v0.194.0
- Support `DeclareEnum`
- Fixes #13848 
- Reduce package size
<details>
<summary>Details</summary>
**Size Change:** -663 kB (-7%) ✅
**Total Size:** 8.96 MB
| `./dist/index.mjs` | 1.18 MB | +165 B (0%) |  |
| `./dist/plugins/acorn-and-espree.js` | 149 kB | +103 B (0%) |  |
| `./dist/plugins/acorn-and-espree.mjs` | 148 kB | +103 B (0%) |  |
| `./dist/plugins/babel.js` | 308 kB | +103 B (0%) |  |
| `./dist/plugins/babel.mjs` | 308 kB | +103 B (0%) |  |
| `./dist/plugins/flow.js` | 713 kB | -332 kB (-32%) | 🎉 |
| `./dist/plugins/flow.mjs` | 713 kB | -332 kB (-32%) | 🎉 |
| `./dist/plugins/meriyah.js` | 157 kB | +103 B (0%) |  |
| `./dist/plugins/meriyah.mjs` | 157 kB | +103 B …
> Update `flow-parser` to v0.194.0

- src/language-js/parse/postprocess/typescript.js
- tests/format/misc/errors/typescript/__snapshots__/jsfmt.spec.js.snap
- tests/format/misc/errors/typescript/modifiers/__snapshots__/jsfmt.spec.js.snap
> Improve TypeScript error location

- .github/workflows/bundler-friendly.yml
- .github/workflows/dev-package-test.yml
- .github/workflows/lock.yml
- .github/workflows/no-response.yml
> Don't run scheduled workflows in forks

- docs/precommit.md
- website/versioned_docs/version-stable/precommit.md
Husky.Net has probably changed since this page was last written. These are the updated steps needed to add the tool.
Update documentation only.
> Update Husky.Net info

- website/pages/en/index.js
- Rewrite sentence on homepage:
- Use the verb `click` instead of `press` (actually we should use a input-neutral verb!)
- Change sentence order
> Rewrite sentence

- src/language-js/print/flow.js
> Remove useless condition

- src/language-js/print/class.js
- src/language-js/print/flow.js
- src/language-js/print/interface.js
- src/language-js/print/module.js
- src/language-js/print/type-annotation.js
- tests/format/misc/errors/flow/declare-export-interface/__snapshots__/jsfmt.spec.js.snap
- tests/format/misc/errors/flow/declare-export-interface/jsfmt.spec.js
> Minor refactor to flow printer

- src/language-js/print/array.js
- src/language-js/print/flow.js
- src/language-js/print/typescript.js
> Merge `printTupleType` into `printArray`

- src/language-js/print/ternary.js
> Minor refactor to `printTernary`

- src/language-js/print/function.js
> Minor refactor to `printReturnOrThrowArgument`

- src/language-js/print/class.js
> refactor: rename`printList` to `printHeritageList`

- src/language-js/print/misc.js
- src/language-js/print/type-annotation.js
> Use `printOptionalToken` in `printIndexedAccessType`

- changelog_unreleased/less/14103.md
- src/language-css/clean.js
- src/language-css/printer-postcss.js
- tests/format/less/case/__snapshots__/jsfmt.spec.js.snap
- tests/format/less/case/variable.less
Ref https://github.com/prettier/prettier/pull/14034#discussion_r1059312395
//cc @mvorisek
> Stop inserting space in LESS property access

- scripts/tools/eslint-plugin-prettier-internal-rules/prefer-create-type-check-function.js
- scripts/tools/eslint-plugin-prettier-internal-rules/test.js
- src/language-js/print/statement.js
> Improve internal ESLint rule

- src/language-js/print/jsx.js
- src/language-js/print/typescript.js
> Stricter node type check

- src/language-handlebars/parser-glimmer.js
- tests/format/misc/errors/handlebars/__snapshots__/jsfmt.spec.js.snap
> Improve handlebars parse error message

- jest.config.mjs
- src/language-css/index.js
- src/language-css/parsers.js
- src/language-graphql/index.js
- src/language-graphql/parsers.js
- src/language-handlebars/index.js
- src/language-handlebars/parsers.js
- src/language-html/index.js
- src/language-html/parsers.js
- src/language-js/index.js
- src/language-js/parse/parsers.js
- src/language-markdown/index.js
- src/language-markdown/parsers.js
- src/language-yaml/index.js
- src/language-yaml/parsers.js
- src/utils/create-parsers.js
- tests/integration/__tests__/plugin-parsers.js
- Improve readability
- Add test to ensure parsers currectly exposed.
> Refactors `createParsers`

- src/language-js/needs-parens.js
- src/language-js/print/statement.js
- src/language-js/utils/index.js
> Remove unused parameter

- src/language-js/parse/angular.js
> Simplify angular expression parser

- tests/integration/__tests__/bundle.js
> Import `fs/promises` directly in test files

- docs/options.md
- website/versioned_docs/version-stable/options.md
Update embedded language formatting options to comply with global writing regarding string typed options
Documentation update only
- [na] I’ve added tests to confirm my change works.
- [na] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [na] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [na] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).
> Update `embeddedLanguageFormatting` option documentation

- src/language-js/print/interface.js
According to https://github.com/typescript-eslint/typescript-eslint/pull/4863, it can't be `abstract`, can't have `modifiers`.
Tests already added in #13929 https://github.com/prettier/prettier/pull/13929/files#diff-469606e740b1d038844806c2d6ea48ebb97626f7847b11f375db648ed707388eR55
> Remove dead code for `TSInterfaceDeclaration`

- package.json
- src/language-js/parse/angular.js
- yarn.lock
https://github.com/prettier/angular-estree-parser/pull/241
> Update `angular-estree-parser` to v6

- src/language-js/print/class.js
- src/language-js/print/misc.js
- src/language-js/print/typescript.js
> Add `printTypeScriptAccessibilityToken`

- src/language-js/print/statement.js
> Avoid unnecessary `print()` in `printStatementSequence`

- src/language-js/print/block.js
- src/language-js/print/statement.js
- src/language-js/printer-estree.js
> Use `printStatementSequence` to print babel directives

- changelog_unreleased/misc/14206.md
> Add changelog for #14206

- src/common/ast-path.js
- src/language-js/print/class.js
- src/language-js/print/misc.js
- src/language-js/print/type-annotation.js
- src/language-js/printer-estree.js
> Add `printAbstractToken`

- src/language-js/clean.js
- src/language-js/parse/babel.js
- src/language-js/parse/postprocess/index.js
- src/language-js/printer-estree.js
- src/language-js/traverse/visitor-keys.evaluate.js
- src/language-js/utils/index.js
- tests/unit/__snapshots__/visitor-keys.js.snap
> Treat hashbang as comment in babel parser(like other parsers)

- docs/plugins.md
- src/common/util.js
- src/utils/text/skip-inline-comment.js
- src/utils/text/skip-newline.js
- src/utils/text/skip-trailing-comment.js
- src/utils/text/skip.js
> Rename variables for shared util

- src/common/util-shared.js
- src/common/util.js
- src/language-js/comments/handle-comments.js
- src/language-js/print/array.js
- src/language-js/print/binaryish.js
- src/language-js/print/block.js
- src/language-js/print/call-arguments.js
- src/language-js/print/class.js
- src/language-js/print/function-parameters.js
- src/language-js/print/function.js
- src/language-js/print/jsx.js
- src/language-js/print/member-chain.js
- src/language-js/print/module.js
- src/language-js/print/object.js
- src/language-js/print/property.js
- src/language-js/print/type-annotation.js
- src/language-js/print/type-parameters.js
- src/language-js/print/typescript.js
- src/language-js/printer-estree.js
- src/main/ast-to-doc.js
- src/main/comments/attach.js
- src/main/comments/print.js
- src/main/comments/utils.js
- src/main/core.js
- src/main/multiparser.js
- src/main/range-util.js
> Move comment attach/print code into `main/comments/`

- src/index.js
- src/main/core.js
- src/standalone.js
> Use named export in `core.js`

- src/language-js/parse/babel.js
- src/language-js/print/typescript.js
- tests/format/misc/errors/typescript/modifiers/__snapshots__/jsfmt.spec.js.snap
- tests/format/misc/errors/typescript/modifiers/jsfmt.spec.js
- tests/format/misc/typescript-babel-only/__snapshots__/jsfmt.spec.js.snap
- tests/format/misc/typescript-babel-only/declare-index-signature.ts
> Throw errors for index signature with `declare`

- .eslintrc.cjs
- scripts/release/run.js
- src/language-css/parser-postcss.js
[`no-duplicate-imports`](https://eslint.org/docs/latest/rules/no-duplicate-imports)
> Enable `no-duplicate-imports` rule

- scripts/build/config.mjs
**Size Change:** -14.7 kB (0%) 
**Total Size:** 9.01 MB
| `./dist/plugins/acorn-and-espree.js` | 145 kB | -3.83 kB (-3%) |
| `./dist/plugins/acorn-and-espree.mjs` | 145 kB | -3.83 kB (-3%) |
| `./dist/plugins/babel.js` | 308 kB | -3.5 kB (-1%) |
| `./dist/plugins/babel.mjs` | 307 kB | -3.5 kB (-1%) |
> Reduce bundle size

- src/cli/format.js
- src/language-css/parser-postcss.js
- src/language-graphql/parser-graphql.js
- src/language-handlebars/parser-glimmer.js
- src/language-html/conditional-comment.js
- src/language-html/parser-html.js
- src/language-js/parse/angular.js
- src/language-js/parse/babel.js
- src/language-js/parse/flow.js
- src/language-js/parse/meriyah.js
- src/language-js/parse/postprocess/typescript.js
- src/language-js/parse/typescript.js
- src/language-json/parser-json.js
- src/language-yaml/parser-yaml.js
- src/main/parser.js
Parsers already use dynamic import, no need inline those modules.
https://github.com/prettier/prettier/blob/31026862781e248bd519e73f2b462b3f799d18c1/src/language-js/parse/parsers.js#L3
As I tested, there is no significant time difference running CLI.
```
$ hyperfine "node dist/bin/prettier.cjs -v" "node dist.14369/bin/prettier.cjs -v"
Benchmark 1: node dist/bin/prettier.cjs -v
Time (mean ± σ):     162.8 ms ±   6.7 ms    [User: 146.5 ms, System: 24.3 ms]
Range (min … max):   154.3 ms … 182.3 ms    18 runs
Benchmark 2: node dist.14369/bin/prettier.cjs -v
Time (mean ± σ):     168.7 ms ±  11.8 ms    [User: 150.8 ms, System: 21.1 ms]
Range (min … max):   158.8 ms … 197.5 ms    17 runs
```
```
$ hyperfine "node dist/bin/prettier.cjs index.js" "node dist.14369/bin/prettier.cjs index.js" …
```
> Remove dynamic imports

- src/main/comments/attach.js
- src/main/core.js
- src/main/multiparser.js
> Reuse `attachComments`

- src/language-js/print/typescript.js
> Minor tweak to ts printer

- src/language-js/parse/acorn.js
- src/language-js/parse/babel.js
- src/language-js/parse/espree.js
- src/language-js/parse/meriyah.js
- src/language-js/parse/typescript.js
- src/utils/try-combinations.js
> Make `tryCombinations` throws `AggregateError(like)` error

- src/language-json/parser-json.js
- tests/format/misc/errors/json/__snapshots__/jsfmt.spec.js.snap
- tests/format/misc/errors/json/jsfmt.spec.js
Don't show missing plugin in error message. 
[Diff](https://github.com/prettier/prettier/pull/14398/commits/37d30c48f6e90490f67596b6168bf59643058e99)
> Improve JSON parse error

- src/language-handlebars/clean.js
- src/language-handlebars/printer-glimmer.js
- src/language-html/print-preprocess.js
- src/language-html/utils/index.js
- src/language-js/print/jsx.js
- src/utils/html-whitespace-utils.js
- src/utils/whitespace-utils.js
- tests/unit/whitespace-utils.js
> Add `WhitespaceUtils`

- scripts/build/build-javascript-module.js
- scripts/build/config.mjs
- scripts/build/utils.js
> Build: add utility to get package files

- src/language-html/parser-html.js
Improve readability a little bit.
> Refactor html parser

- src/language-html/pragma.js
- tests/format/html/pragma/__snapshots__/jsfmt.spec.js.snap
- tests/format/html/pragma/jsfmt.spec.js
- tests/format/html/pragma/no-pragma.html
- tests/format/html/pragma/with-pragma-2.html
- tests/format/html/pragma/with-pragma.html
> Don't trim in html `insertPragma`

- docs/install.md
- docs/precommit.md
> Add docs for pnpm

- src/language-js/parse/acorn.js
- src/language-js/parse/babel.js
- src/language-js/parse/espree.js
- src/language-js/parse/flow.js
- src/language-js/parse/meriyah.js
- src/language-js/parse/postprocess/index.js
- src/language-js/parse/postprocess/typescript.js
- src/language-js/parse/typescript.js
- src/language-js/parse/utils/wrap-babel-expression.js
- src/language-js/print/binaryish.js
- src/language-js/utils/index.js
- src/language-json/parser-json.js
> Stop manipulate `options` in parsers

- src/cli/format.js
- src/common/errors.js
> Move `DebugError` into `cli/`

- changelog_unreleased/javascript/14409.md
- src/language-js/needs-parens.js
- tests/format/js/decorators/__snapshots__/jsfmt.spec.js.snap
- tests/format/js/decorators/class-expression/__snapshots__/jsfmt.spec.js.snap
~This PR reverts #12260, the [original issue](https://deploy-preview-14409--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEAKAAgM1QSgARgA2AhgM6l7AC+OA3CADQgQAOMAltKcqMQE58IAdwAK-BNxTFCQ4gE9uTAEZ9iYANZwYAZWIBbOABl2UOMkzTScZao1btLNSYDmyGHwCu1kHD1K4ACYBgYbEUM4exM5wAGIQfHrEMBzhyCDEHjAQjCAAFjB6hADquezwpI5gcNoSZewAbmVyaWDkOSZWfDAiqs6J5pbeAFakAB7aLoRwAIoeEPADhFZMjnydaUrE-oQ5LHwmMEXsATC5yAAcAAwrglZFqixpe3Cd9WZMAI5z8D2skumkAC0pkCgRyfDgX3YEJ6UX6SAsS28Vj07DcnmRkzgAEFkvslJk4CI4HxjKZFssQKQsbN5mYEYMmDAtkcTmckAAmJmqdiEFwAYQgenh6UIOyYHisABUtpJEZT6l4AJJQYKwbRgfZsbGq7QwORTClwKhUIA) somehow fixed somewhere else.~
This was added in #12260, other changes in #12260 fixed the original issue, but the change in `needsParens` is wrongly added. …
> Remove unnecessary parentheses around class expression

- src/language-html/printer-html.js
- src/language-html/utils/index.js
- src/language-markdown/printer-markdown.js
> Reuse `getPreferredQuote`

- docs/options.md
I think it’s worth noticing for those who search for SmartTab-related tool (as I did, for example).
> Add note about SmartTabs

- src/language-js/needs-parens.js
- src/language-js/print/angular.js
- src/language-js/utils/index.js
- src/main/ast-utils.js
- src/main/comments/attach.js
- src/main/get-cursor-node.js
- src/utils/ast-utils.js
- src/utils/is-non-empty-array.js
- src/utils/is-object.js
- tests/unit/get-descendants.js
> Add utilities to get descendants

- src/document/utils.js
- src/language-js/print/decorators.js
- src/language-js/printer-estree.js
> Refactor estree main print function

- scripts/build/build-types.js
- src/language-css/parser-postcss.js
- src/language-graphql/parser-graphql.js
- src/language-handlebars/parser-glimmer.js
- src/language-html/parser-html.js
- src/language-js/parse/acorn-and-espree.js
- src/language-js/parse/angular.js
- src/language-js/parse/babel.js
- src/language-js/parse/flow.js
- src/language-js/parse/meriyah.js
- src/language-js/parse/typescript.js
- src/language-markdown/parser-markdown.js
- src/language-yaml/parser-yaml.js
- src/utils/create-parsers.js
- tests/dts/unit/cases/parsers.ts
- tests/integration/__tests__/plugin-parsers.js
> Fix builtin plugins

- package.json
- src/language-js/traverse/visitor-keys.evaluate.js
- yarn.lock
Closes #14497, the bot is overriding my change.
> Update dependency hermes-eslint to v0.10.0

- src/main/ast-to-doc.js
- src/main/comments/attach.js
- src/main/core.js
- src/main/multiparser.js
- src/main/parser.js
> Move comment attach into `printAstToDoc`

- src/language-js/print/flow.js
- src/language-js/print/type-annotation.js
- src/language-js/print/typescript.js
> Share logic between flow and ts

- src/language-js/print/decorators.js
- src/language-js/print/flow.js
- src/language-js/print/module.js
- src/language-js/print/typescript.js
- src/language-js/printer-estree.js
> Refactor export declaration print

- changelog_unreleased/vue/14542.md
- src/language-css/print/parenthesized-value-group.js
- src/language-js/print/binaryish.js
- tests/format/vue/interpolation/__snapshots__/jsfmt.spec.js.snap
- tests/format/vue/interpolation/bitwise-or-operator.vue
> Fix Vue filter detection

- src/language-js/print/flow.js
- src/language-js/print/typescript.js
- src/language-js/utils/index.js
- src/language-js/utils/is-flow-keyword-type.js
> Add `isFlowKeywordType`

- changelog_unreleased/css/14208.md
- src/language-css/print/parenthesized-value-group.js
- src/language-css/printer-postcss.js
- tests/format/css/atrule/__snapshots__/jsfmt.spec.js.snap
- tests/format/css/comments/__snapshots__/jsfmt.spec.js.snap
- tests/format/css/fill-value/__snapshots__/jsfmt.spec.js.snap
- tests/format/css/indent/__snapshots__/jsfmt.spec.js.snap
- tests/format/less/comments/__snapshots__/jsfmt.spec.js.snap
- tests/format/less/less/__snapshots__/jsfmt.spec.js.snap
- tests/format/scss/comments/__snapshots__/jsfmt.spec.js.snap
- tests/format/scss/scss/__snapshots__/jsfmt.spec.js.snap
- tests/format/stylefmt-repo/font-face/__snapshots__/jsfmt.spec.js.snap
- tests/format/stylefmt-repo/font-shorthand/__snapshots__/jsfmt.spec.js.snap
> Merge 14208 into next

- .github/workflows/dev-test.yml
- .github/workflows/prod-test.yml
> Unpin Node.js version

- changelog_unreleased/api/12740.md
- scripts/build-website.mjs
- scripts/build/build-package-json.js
- scripts/build/build-types.js
- scripts/build/config.mjs
- src/plugins/estree.js
- src/standalone.js
- website/static/service-worker.js
- website/static/worker.js
> Remove plugins from standalone build

- src/main/parser.js
> Throw errors when parser can't be found

- src/language-js/comments/handle-comments.js
- src/language-js/printer-estree.js
- src/main/comments/attach.js
> Move `avoidAstMutation` to `printer.experimentalFeatures`

- src/language-js/parse/postprocess/index.js
> Remove outdated workaround

- scripts/build/shims/at.js
- src/common/ast-path.js
Address https://github.com/prettier/prettier/issues/13142#issuecomment-1483883939
> Transform `.at` to property access to improve performance

- .github/dependabot.yml
- .github/renovate.json5
> Update dependabot and renovate to target main branch

- src/cli/expand-patterns.js
> Quote patterns in error message

- src/index.d.ts
> Fix signature of `embed`

- src/language-js/parse/babel.js
- src/language-js/traverse/visitor-keys.evaluate.js
- tests/format/js/decorators/__snapshots__/jsfmt.spec.js.snap
- tests/format/js/decorators/jsfmt.spec.js
- tests/format/js/decorators/multiple.js
- tests/unit/__snapshots__/visitor-keys.js.snap
> Forbid decorators on object property

- changelog_unreleased/html/14400.md
- src/language-html/utils/index.js
- tests/config/utils/check-parsers.js
- tests/format/html/svg/__snapshots__/jsfmt.spec.js.snap
- tests/format/html/svg/embeded/__snapshots__/jsfmt.spec.js.snap
- tests/format/html/svg/embeded/jsfmt.spec.js
- tests/format/html/svg/embeded/svg.html
- tests/format/html/svg/embeded/svg.svg
- tests/format/html/svg/script.svg
- tests/format/html/svg/svg.html
> Format `<script>` inside SVG

- src/language-js/print/type-annotation.js
No logic change, use `AstPath` getters.
> Simplify `printIntersectionType`

- changelog_unreleased/api/14718.md
- src/cli/format.js
- src/main/normalize-format-options.js
- tests/integration/__tests__/__snapshots__/infer-parser.js.snap
- tests/integration/__tests__/infer-parser.js
> Stop formatting unknown code with `babel` parser

- changelog_unreleased/api/12740.md
- docs/api.md
- src/standalone.js
- website/versioned_docs/version-stable/api.md
> Suggest use named import in docs and changelogs

- package.json
- scripts/build/config.js
- yarn.lock
> Update `@angular/compiler` to v16

- scripts/release/package.json
- scripts/release/yarn.lock
> Remove unused dependency from release script

- package.json
- tests/format/misc/errors/js/__snapshots__/jsfmt.spec.js.snap
- tests/format/misc/errors/js/import-assertions/__snapshots__/jsfmt.spec.js.snap
- tests/format/misc/errors/json/__snapshots__/jsfmt.spec.js.snap
- yarn.lock
Updates to https://babel.dev/blog/2023/05/26/7.22.0
I'll create PRs to add support for new syntaxes after this is merged.
> Update `@babel/parser` to 7.22.0

- website/versioned_docs/version-stable/plugins.md
related: https://github.com/prettier/prettier/pull/14851#issuecomment-1582599458
> Add `prettier-plugin-rust` to community plugin list (1)

- src/cli/utils.js
- src/config/get-prettier-config-explorer.js
- src/config/load-external-config.js
- src/language-css/parser-postcss.js
- src/language-js/parse/acorn.js
- src/language-js/parse/babel.js
- src/language-js/parse/espree.js
- src/language-js/parse/meriyah.js
- src/language-js/parse/typescript.js
- src/language-json/parser-json.js
- src/language-markdown/mdx.js
- src/language-markdown/parser-markdown.js
- src/language-markdown/unified-plugins/front-matter.js
- src/language-markdown/unified-plugins/liquid.js
- src/language-markdown/unified-plugins/wiki-link.js
- src/language-yaml/parser-yaml.js
- src/utils/read-file.js
- tsconfig.json
> feat: enable strict type checking

- website/yarn.lock
> Regenerate yarn.lock file for website

- scripts/release/run.js
- scripts/release/steps/index.js
- scripts/release/steps/run-tests.js
Our package is full tested on CI, I don't think it's necessary to test when release.
> Remove test step from release script

- website/blog/2023-07-05-3.0.0.md
> Fix 3.1 -> 3.0

- docs/plugins.md
- website/versioned_docs/version-stable/plugins.md
Update link to `prettier-plugin-svelte`
> docs: update link to `prettier-plugin-svelte`

- scripts/generate-schema.js
- scripts/release/steps/update-version.js
> Fix release script

- docs/api.md
- website/blog/2023-07-05-3.0.0.md
- website/versioned_docs/version-stable/api.md
- Fix a broken link.
- Fix a bad changelog
- Rename variable
> Update v3 blog post

- scripts/build-website.js
> Fix a TODO in website build script

- .prettierignore
No longer needed since they already ignore by git.
> Clean `.prettierignore`

- scripts/release/utils.js
Currently following code will fail:
```js
runYarn("install");
```
> Fix `runYarn` function in release script

- scripts/build/shims/assert.js
- scripts/build/shims/chalk.js
> Make chalk/assert shim a Proxy

- tests/format/misc/errors/typescript/mapped-type/__snapshots__/jsfmt.spec.js.snap
- tests/format/misc/errors/typescript/mapped-type/jsfmt.spec.js
- tests/format/misc/errors/typescript/mapped-type/mapped-type.ts
> Add test to close #14635

- scripts/build/README.md
- scripts/build/build.js
- scripts/build/parse-arguments.js
> Build: Use `node:util` to parse arguments

- src/utils/create-language.js
> Assert uniqueness in language properties

- src/cli/expand-patterns.js
> Minor refactor to `getSupportedFilesGlob`

- scripts/build/config.js
- src/language-js/parse/acorn.js
- src/language-js/parse/espree.js
- src/utils/try-combinations.js
> Get ride of `require()` in `acorn` and `espree` parser

- changelog_unreleased/typescript/15324.md
- src/language-js/comments/handle-comments.js
- tests/format/typescript/comments/__snapshots__/jsfmt.spec.js.snap
- tests/format/typescript/comments/ts-parameter-proerty.ts
> Fix comment around `TSParameterProperty`

- changelog_unreleased/api/15332.md
- docs/api.md
- src/config/resolve-config.js
- src/index.d.ts
- tests/integration/__tests__/config-resolution.js
- tests/integration/__tests__/resolve-config-file.js
> Accept `URL` in `resolveConfig`

- changelog_unreleased/api/15332.md
- docs/api.md
- src/common/get-file-info.js
- src/index.d.ts
- tests/integration/__tests__/file-info.js
> Accept `URL` in `getFileInfo`

- .github/workflows/dev-test.yml
- src/common/get-file-info.js
- src/index.d.ts
- src/utils/get-interpreter.js
- src/utils/ignore.js
- src/utils/infer-parser.js
- tests/integration/__tests__/file-info.js
> Refactor: Accept `URL` in `isIgnored` and `inferParser`

- src/cli/index.js
- tests/integration/__tests__/cache.js
> Minor tweak to CLI

- changelog_unreleased/javascript/9559.md
- src/language-js/print/ternary.js
- tests/format/flow/conditional-types-comments/__snapshots__/jsfmt.spec.js.snap
- tests/format/flow/conditional-types/__snapshots__/jsfmt.spec.js.snap
- tests/format/js/conditional/__snapshots__/jsfmt.spec.js.snap
- tests/format/js/ternaries/__snapshots__/jsfmt.spec.js.snap
- tests/format/js/ternaries/nested.js
- tests/format/js/throw_expressions/__snapshots__/jsfmt.spec.js.snap
- tests/format/jsx/jsx/__snapshots__/jsfmt.spec.js.snap
- tests/format/typescript/conditional-types/__snapshots__/jsfmt.spec.js.snap
- tests/format/typescript/keyword-types/__snapshots__/jsfmt.spec.js.snap
Reverts https://github.com/prettier/prettier/pull/5039/commits/a7580eb53b3f6983acaa713cb8843439b4a6c61f, which was intended to address https://github.com/prettier/prettier/issues/737
Fixes https://github.com/prettier/prettier/issues/5814
Alternative/complementary approaches were proposed in https://github.com/prettier/prettier/issues/9561, with https://github.com/prettier/prettier/pull/13183 emerging as the intended successor, as it addresses several of the shortcomings of this approach.
Headline examples, pulled from [the tests](https://github.com/rattrayalex/prettier/pull/12/commits/2a127d39970fba3a63c40d434d15d71f55e0c090#diff-6755425a75ca1290cf0caf067010b27eaad4bdfb8202c94bb2a21b55737ba02bL2340-R2389):
```jsx
const message =
i % 3 === 0 && i % 5 === 0
? "fizzbuzz"
: i % 3 === 0
? …
```
> Add indentation back to nested ternaries

- .github/renovate.json5
Babel config Renovate  with this option, it looks good.
- Babel PR setup Renovote https://github.com/babel/babel/pull/13337#issuecomment-843988134
- Dependency Dashboard `https://github.com/babel/babel/issues/13343` (I don't want leave a link to their issue, manually open it)
- `dependencyDashboardApproval` https://docs.renovatebot.com/configuration-options/#dependencydashboardapproval
> Enable `dependencyDashboardApproval` in Renovate config

- src/index.d.ts
Does this require documentation? I am not sure.
I discovered them while completing https://github.com/jestjs/jest/pull/14566.
> Fix type definitions for v3

- changelog_unreleased/javascript/15485.md
- package.json
- tests/format/misc/errors/invalid/__snapshots__/jsfmt.spec.js.snap
- tests/format/misc/errors/js/assignment/__snapshots__/jsfmt.spec.js.snap
- tests/unit/__snapshots__/visitor-keys.js.snap
- yarn.lock
Context: https://github.com/prettier/prettier/issues/15471
New language features will be supported by another PRs.
> Update `@babel/parser` to 7.23.0

- .gitignore
> Add `*.cpuprofile` file to `.gitignore`

- docs/options.md
- website/versioned_docs/version-stable/options.md
> Update `trailingComma: es5` document

- changelog_unreleased/javascript/15547.md
- src/language-js/print/assignment.js
- tests/format/angular/angular/__snapshots__/jsfmt.spec.js.snap
- tests/format/js/assignment/__snapshots__/jsfmt.spec.js.snap
- tests/format/js/assignment/issue-15534.js
> Improve formatting for assignment its left can break

- package.json
- yarn.lock
https://github.com/bcomnes/npm-run-all2
> Switch `npm-run-all` to maintenance fork

- .github/workflows/dev-test.yml
- .github/workflows/prod-test.yml
Node.js 20 is now latest LTS. https://nodejs.org/en/blog/release/v20.9.0
> Run full test on Node.js 20

- .github/workflows/dev-package-test.yml
- .github/workflows/dev-test.yml
- package.json
> Drop Node.js 16 for development build

- changelog_unreleased/javascript/15525.md
- src/language-js/utils/index.js
- tests/format/js/strings/__snapshots__/jsfmt.spec.js.snap
- tests/format/js/strings/escaped.js
> Consistently format strings containing escapes

- package.json
- yarn.lock
Updates `angular-html-parser` to v5.
> Update `angular-html-parser` to v5

- .github/workflows/dev-test.yml
- .github/workflows/prod-test.yml
> Make the CI job name shorter

- src/language-js/parse/utils/create-babel-parse-error.js
- tests/format/misc/errors/babel-flow/__snapshots__/jsfmt.spec.js.snap
> Fix babel error message

- package.json
- scripts/build/config.js
- src/language-handlebars/html-void-elements.evaluate.js
- src/language-handlebars/parser-glimmer.js
- src/language-handlebars/utils.js
- src/language-handlebars/visitor-keys.evaluate.js
- tsconfig.json
- yarn.lock
> Update glimmer to v0.85.8

- src/language-json/parser-json.js
> Skip comment attach when parse JSON

- README.md
In the current Readme the logo of twitter is not visible and is not updated to X.
This Fixes this issue 
> docs: fixed and updated twitter logo

- README.md
The background is little too dark.
Before:
After:
> Update twitter badge

- package.json
- scripts/build/transform/index.js
- yarn.lock
> Update `@angular/compiler` to v17

- src/language-html/clean.js
- src/language-html/embed.js
- src/language-html/embed/angular-control-flow-block-parameters.js
- src/language-html/parser-html.js
- src/language-html/print/angular-control-flow-block.js
- src/language-html/print/tag.js
- src/language-html/printer-html.js
- src/language-html/visitor-keys.js
- tests/unit/__snapshots__/visitor-keys.js.snap
- Change node type from 'block' to 'angularControlFlowBlock'
- Add an wrapper "angularControlFlowBlockParameters“ for parameters
> Refactor angular control flow block

- src/language-html/print/angular-control-flow-block-settings.evaluate.js
- src/language-html/print/angular-control-flow-block.js
> Simplify angular control flow syntax print

- scripts/build/build-package-json.js
Closes #15592
Closes #14766
Fixes #14765
> Add "browser" field in exports["."]

- src/language-js/parse/postprocess/index.js
I don't think this function is good for generic use.
> Remove `overrideLocEnd`

- website/blog/2023-11-13-3.1.0.md
- https://prettier.io/blog/2023/11/12/curious-ternaries
→
- https://prettier.io/blog/2023/11/13/curious-ternaries
> Fix link to "A curious case of the ternaries" blog post

- scripts/build/esbuild-plugins/umd.js
Had a look at the changes in the ternaries and noticed you forgot to update the UMD template (and probably others as well)
By the way, this particular one looks great in `experimentalTernaries`
> updating UMD template to reflect new ternaries

- docs/configuration.md
- tests/format/markdown/markdown/__snapshots__/jsfmt.spec.js.snap
- tests/format/markdown/markdown/real-world-case.md
- tests/integration/cli/config/$schema/.prettierrc
- website/versioned_docs/version-stable/configuration.md
> docs: update the JSON schema location to use https

- scripts/build/config.js
- scripts/release/yarn.lock
- scripts/tools/bundle-test/yarn.lock
- website/yarn.lock
- yarn.lock
> Refresh yarn.lock files

- changelog_unreleased/api/15363.md
> Fix changelog

- bin/prettier.cjs
- bin/prettier.js
- package.json
- scripts/build/build-package-json.js
- scripts/build/config.js
- yarn.lock
> Use `@prettier/next`

- .eslintrc.cjs
- scripts/build/config.js
- src/cli/format.js
- src/cli/is-tty.js
- src/cli/prettier-internal.js
- src/config/get-prettier-config-explorer.js
- src/index.js
- tests/integration/__tests__/bundle.js
- tests/integration/__tests__/mockable.js
- tests/integration/cli-worker.js
- tests/integration/env.js
> Simplify mockable

- changelog_unreleased/api/15666.md
- src/main/plugins/load-plugin.js
- tests/integration/__tests__/plugin-resolution.js
- tests/integration/cli/config/plugins/absolute-path/prettier.config.mjs
> Support absolute path in config file

- package.json
- yarn.lock
> Update `@prettier/cli` to 0.2.0

- cspell.json
- scripts/build/esbuild-plugins/visualizer.js
> Build: Fix html report

- src/language-js/print/module.js
> Simplify module attributes print

- src/language-js/print/type-annotation.js
No logic change, but avoid unnecessary calculation.
> Improve `shouldHugType`

- src/language-js/comments/handle-comments.js
- src/language-js/comments/printer-methods.js
- src/language-js/print/assignment.js
- src/language-js/print/function-parameters.js
- src/language-js/print/type-annotation.js
- src/language-js/utils/index.js
> Add `isUnionType` and `isIntersectionType` utilities

- scripts/build/config.js
- src/config/prettier-config-explorer/loaders.js
> Reduce size of bundled `json5`

- scripts/build/config.js
- src/config/prettier-config-explorer/loaders.js
> Reduce size of bundled `js-yaml`

- src/main/plugins/load-plugin.js
- Remove dead code `loadPluginFromDirectory`
- Simplify/Fix cache
> Simplify `loadPlugin`

- src/config/editorconfig/index.js
- src/config/find-project-root.js
- src/config/prettier-config/config-searcher.js
- src/config/prettier-config/index.js
- src/config/searcher.js
Extract `Searcher` for both "project root" and "prettier config" search. 
> Refactor config search

- scripts/build/shims/array-find-last.js
- scripts/build/transform/transforms/index.js
- scripts/build/transform/transforms/transform-array-find-last.js
- src/language-js/print/jsx.js
- src/language-js/print/statement.js
- src/main/parser-and-printer.js
- tests/unit/syntax-transform.js
> Use `Array#findLast()`

- scripts/build/transform/transforms/index.js
> Run `fix:eslint`

- .eslintrc.cjs
- package.json
- yarn.lock
> Remove deprecated ESLint rules

- .github/ISSUE_TEMPLATE/config.yml
> Add link for VSCode plugin issues

- .github/ISSUE_TEMPLATE/formatting.md
- website/playground/markdown.js
I'm not good at English, so it's a little difficult to read the expected behavior written in text only.
> Update issue template

- src/language-graphql/loc.js
- src/language-graphql/parser-graphql.js
- src/language-js/loc.js
> Simplify loc.js

- src/language-js/print/cast-expression.js
> Simplify `printBinaryCastExpression`

- scripts/release/steps/show-instructions-after-npm-publish.js
@sosukesuzuki Did you follow it in the previous release? I didn't notice it until today. I don't think it's necessary.
> Remove manual test step from release script

- package.json
Remove `\"!test*\"` since they are ignored by `.gitignore`, and we skip them by default now.
> Improve `lint:prettier` script

- scripts/generate-schema.js
- scripts/release/steps/post-publish-steps.js
- scripts/release/utils.js
- scripts/utils/generate-schema.js
- tests/integration/__tests__/__snapshots__/schema.js.snap
- tests/integration/__tests__/schema.js
https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/prettierrc.json
is outdated.
> Fix schema

- changelog_unreleased/angular/15969.md
- src/language-js/embed/utils.js
- tests/format/typescript/angular-component-examples/15969-computed.component.ts
- tests/format/typescript/angular-component-examples/__snapshots__/jsfmt.spec.js.snap
> fix: do not format computed template which could be unexpected

- .github/FUNDING.yml
> Add GitHub sponsor info

- docs/api.md
> Add `@prettier/sync` to docs

- docs/install.md
Changes according to https://github.com/typicode/husky/releases/tag/v9.0.1
> Update install script for husky v9

- src/language-js/print/estree.js
> Simplify `UpdateExpression` print

- src/language-js/comments/handle-comments.js
- src/language-js/print/block.js
- src/language-js/print/estree.js
- tests/format/js/module-blocks/__snapshots__/jsfmt.spec.js.snap
> Refactor `ModuleExpression` print

- src/language-markdown/print/table.js
- src/language-markdown/printer-markdown.js
> Extract and simplify `printTable`

- CHANGELOG.md
> fix url to old version in the changelog

- src/utils/print-number.js
The `printNumber` function has become complex for edge cases. From my experience, most of the numeric literals that appear in the source code are single-digit numbers. Therefore, it makes sense to provide a fast path for those cases.
Below are the total execution times of the printNumber function when running on the `main` branch and this PR for the source code of Prettier, Babel, and Excalidraw:
|repo |  `main`  | this PR |
|--------|-------|---|
|prettier | 1.9389689999988775 ms   | 0.759684000002693 ms |
|babel | 5.473972999931675 ms | 1.4176010000458064 ms |
|excalidraw | 8.948650999990122 ms | 4.885992999990378 ms |
<details>
<summary>Numbers of number literals in the source code(we can see that there are many single digit numbers):</summary>
**Prettier:**
```
Map(22) {
'0' => 656, …
```
> perf: Add fast path for `printNumber`

- .github/renovate.json5
> Group ESLint releated packages

- changelog_unreleased/typescript/16031.md
- src/language-js/needs-parens.js
- tests/format/typescript/infer-extends/__snapshots__/jsfmt.spec.js.snap
- tests/format/typescript/infer-extends/basic.ts
> Add missing parentheses to `TSInferType`

- src/language-js/print/class.js
- src/language-js/print/property.js
- src/language-js/utils/index.js
No logic change, just move functions into property.js
> Refactor `printPropertyKey`

- src/language-js/print/property.js
> Improve readability of `isStringKeySafeToUnquote`

- src/main/core-options.evaluate.js
- src/main/normalize-options.js
related https://github.com/Sec-ant/prettier-plugin-embed/pull/74#issuecomment-1928762028
> feat: support redirect to another option directly without value

- eslint.config.js
> Simplify eslint-plugin-jest config

- package.json
- yarn.lock
> Update `angular-estree-parser` to v10.0.1

- src/language-js/clean.js
Instead of delete the whole node, check stringified value is equal.
> Stricter AST check for property keys

- CHANGELOG.md
I only fixed a small error in the CHANGELOG.
> fix: corrected the error in config file name

- FUNDING.json
Adding this file to verify Open Source Collective's wallet address  on Drips. Open Source Collective will periodically collect and allocate funds from https://www.drips.network/app/projects/github/prettier/prettier to https://opencollective.com/prettier
> Claim prettier/prettier on Drips

- docs/configuration.md
> docs: add `@see` to improve self-documentation

- package.json
- yarn.lock
> Remove `@types/find-cache-dir`

- .github/workflows/dev-test.yml
- .github/workflows/prod-test.yml
> Run tests on Node 22

- .github/workflows/prod-test.yml
> Fix tests on Node.js 14 x MacOS

- eslint.config.js
> Switch `eslint-plugin-regexp` to `flat/recommended` preset

- src/language-handlebars/printer-glimmer.js
> Print `AtHead` node from glimmer via `print()`

- src/language-js/print/assignment.js
- src/main/range-util.js
`while (true)` is allowed in `no-constant-condition` now, https://github.com/eslint/eslint/pull/18286
> Use `while (true)` instead of `for (;;)`

- scripts/build/transform/transforms/create-method-call-transform.js
- tests/unit/syntax-transform.js
> Minor tweak to syntax transform script

- eslint.config.js
- src/utils/front-matter/parse.js
- src/utils/front-matter/print.js
Remove the regexp which is hard to understand.
> Refactor front matter parsing

- scripts/tools/eslint-plugin-prettier-internal-rules/no-identifier-n.js
- scripts/tools/eslint-plugin-prettier-internal-rules/test.js
> Fix test for internal eslint rules

- cspell.json
- scripts/build/build-javascript-module.js
- scripts/build/config.js
- scripts/build/esbuild-plugins/replace-module.js
- scripts/build/esmify-typescript-eslint.js
- scripts/build/modify-typescript-module.js
- src/language-js/parse/typescript.js
> Transform `@typescript-eslint/*` to ESM

- package.json
- scripts/build/build-javascript-module.js
- scripts/build/transform/index.js
- yarn.lock
> Update `jest-docblock` to v30

- eslint.config.js
- package.json
- yarn.lock
> Update `eslint-plugin-unicorn` to v54

- scripts/build/build-javascript-module.js
- src/language-markdown/constants.evaluate.js
- src/language-markdown/utils.js
Reverts prettier/prettier#15643
> Revert "Revert "Switch `kRegex` to use RegExp with `u` directly""

- .github/workflows/dev-test.yml
- .github/workflows/prod-test.yml
- tests/integration/__tests__/doc-mark-as-root.js
> chore: fix some comments

- src/index.d.ts
> Update resolveConfig doc comment

- scripts/build/shims/array-find-last-index.js
- scripts/build/transform/transforms/index.js
- scripts/build/transform/transforms/transform-array-find-last-index.js
- src/main/range-util.js
- tests/unit/syntax-transform.js
> Use `Array#findLastIndex`

- src/index.js
- src/main/core.js
> Import `diff` directly

- scripts/build/transform/transforms/index.js
> Add comments for transforms

- src/common/ast-path.js
- src/language-html/embed/attribute.js
- src/language-html/embed/vue-attributes.js
- src/language-js/needs-parens.js
- src/language-js/print/call-expression.js
- src/language-js/print/type-parameters.js
- src/language-js/utils/index.js
- Move related code to `isCommonsJsOrAmdModuleDefinition`
- Add `printCallee`
> Minor refactor to `printCallExpression`

- src/language-markdown/print-preprocess.js
- src/language-markdown/utils.js
> Simplify `hasGitDiffFriendlyOrderedList`

- .github/workflows/dev-test.yml
- .github/workflows/prod-test.yml
https://github.com/nodejs/node/issues/53902
> Pin Node.js v22 version

- changelog_unreleased/javascript/13315-2.md
> Fix changelog for #13315

- changelog_unreleased/markdown/16546.md
- src/language-markdown/printer-markdown.js
- tests/format/markdown/linkReference/__snapshots__/format.test.js.snap
- tests/format/markdown/linkReference/wrap.md
Fix https://github.com/prettier/prettier/issues/16351
> Fix incorrect wrap in sentence with linkReference

- changelog_unreleased/api/16567.md
- docs/plugins.md
- src/index.d.ts
- src/utils/get-preferred-quote.js
- src/utils/public.js
- tests/integration/__tests__/util-shared.js
> Make `getPreferredQuote` public

- changelog_unreleased/css/16572.md
- src/language-css/printer-postcss.js
- tests/format/css/pseudo-call/__snapshots__/format.test.js.snap
- tests/format/css/pseudo-call/indent.css
> Remove extra indentation in pseudo class function

- changelog_unreleased/typescript/16574.md
- src/language-js/comments/handle-comments.js
- tests/format/typescript/comments/16065.ts
- tests/format/typescript/comments/__snapshots__/format.test.js.snap
> Preserve a comment on between decorator and modified parameter property

- .github/workflows/dev-test.yml
- .github/workflows/prod-test.yml
> Pin Node.js to v22.6.0

- changelog_unreleased/javascript/16593.md
- src/language-js/comments/handle-comments.js
- tests/format/js/comments/15661.js
- tests/format/js/comments/__snapshots__/format.test.js.snap
> Improve comment formatting for logical expression in unary expression

- docs/index.md
> Docs: HTTPS link to Less site

- package.json
- yarn.lock
**This PR will be merged into `next` branch.**
- Updates `@prettier/cli` to [0.6.0](https://github.com/prettier/prettier-cli/releases/tag/v0.6.0)
> Update `@prettier/cli` to 0.6.0

- scripts/build/esbuild-plugins/throw-warnings.js
- src/language-js/parse/postprocess/index.js
- tests/config/run-format-test.js
> Cleanup for meriyah parser

- .github/workflows/dev-test.yml
- .github/workflows/prod-test.yml
- cspell.json
- tests/integration/__tests__/config-resolution.js
Reverts prettier/prettier#16601
> Revert "Pin Node.js to v22.6.0"

- src/language-js/parse/babel.js
https://github.com/babel/babel/pull/16801
> Remove support for "minimal" Pipeline Operator

- .github/workflows/dev-package-test.yml
- .github/workflows/dev-test.yml
- .github/workflows/release-script-test.yml
> Drop Node.js 18 for development build

- src/config/prettier-config/loaders.js
It's added accidentally from #16450
> Remove useless import

- changelog_unreleased/typescript/16730.md
- src/language-js/print/class.js
- tests/format/typescript/class/__snapshots__/format.test.js.snap
- tests/format/typescript/class/issue-16723.ts
> Fix space between class heritage and class body

- changelog_unreleased/typescript/16731.md
- src/language-js/print/class.js
- tests/format/typescript/class/__snapshots__/format.test.js.snap
- tests/format/typescript/class/declare-field.ts
> Print `declare` before accessibility in class properties

- changelog_unreleased/vue/16733.md
- src/language-html/embed/vue-attributes.js
- src/language-html/embed/vue-bindings.js
- src/language-js/print/expression-statement.js
- src/language-js/print/semicolon.js
- src/language-js/utils/vue-event-binding.js
- src/main/multiparser.js
- tests/format/vue/event-binding/__snapshots__/format.test.js.snap
- tests/format/vue/event-binding/non-ascii-expression-ts.vue
- tests/format/vue/event-binding/non-ascii-expression.vue
- tests/format/vue/vue/__snapshots__/format.test.js.snap
> Fix `v-on` print

- docs/plugins.md
- website/versioned_docs/version-stable/plugins.md
This sentence in the docs seems incomplete. This PR makes the comment for `astFormat` clearer.
> fix(docs): complete sentence for astFormat

- src/language-js/print/typescript.js
Part of #16801
[#babel-​16732](https://redirect.github.com/babel/babel/pull/16732) Add kind to TSModuleDeclaration
> Simplify `TSModuleDeclaration` print

- scripts/build/transform/index.js
- tests/unit/syntax-transform.js
> Build: Add `experimental_preserveFormat` to `@babel/generator`

- src/language-js/parse/babel.js
Ref https://github.com/prettier/prettier/issues/16801#issuecomment-2445990023
> Update babel parse options for `import assertions` support

- src/language-js/comments/printer-methods.js
- src/language-js/print/call-arguments.js
- src/language-js/print/estree.js
- src/language-js/traverse/visitor-keys.evaluate.js
- src/language-js/utils/index.js
- tests/unit/__snapshots__/visitor-keys.js.snap
> Remove outdated node type "Import"

- changelog_unreleased/angular/16862.md
- package.json
- tests/format/angular/typeof-expression/__snapshots__/format.test.js.snap
- tests/format/angular/typeof-expression/format.test.js
- tests/format/angular/typeof-expression/typeof-expression.html
- yarn.lock
> Angular: Support `typeof` expression

- scripts/build/config.js
- scripts/release/yarn.lock
- scripts/tools/bundle-test/yarn.lock
- website/yarn.lock
- yarn.lock
Hope this can fix some security issues
> Regenerate lock files

- website/blog/2024-11-26-3.4.0.md
* Minor wording improvements
* Change `Output (stable)` / `Output (main)` to `Prettier 3.3` / `Prettier 3.4` for consistency
* Fix code block languages
> Minor improvements in v3.4.0 blog post

- tests/format/typescript/comments/16207.ts
- tests/format/typescript/comments/__snapshots__/format.test.js.snap
> Add test for #16207

- changelog_unreleased/typescript/16891.md
- src/language-js/comments/handle-comments.js
- tests/format/typescript/comments/16889.ts
- tests/format/typescript/comments/__snapshots__/format.test.js.snap
> Fix comments on class methods with decorators

- scripts/release/steps/wait-for-bot-release.js
NPM updated their UI https://www.npmjs.com/package/prettier/access
> Update release instruction

- .github/workflows/prod-test.yml
See https://blog.stackblitz.com/posts/pkg-pr-new/
> Add action to publish preview release for PR

- .github/workflows/dev-test.yml
- .github/workflows/prod-test.yml
- tests/config/install-prettier.js
- tests/config/run-format-test.js
- tests/format/js/babel-plugins/__snapshots__/format.test.js.snap
- tests/format/js/regex/__snapshots__/format.test.js.snap
- tests/integration/run-cli.js
> Remove TLA from jest.config.js

- src/config/prettier-config/load-external-config.js
- tests/integration/__tests__/__snapshots__/config-resolution.js.snap
- tests/integration/__tests__/config-resolution.js
- tests/integration/cli/config/external-config/esm-package-with-tla/index.js
- tests/integration/cli/config/external-config/esm-package-with-tla/node_modules/@company/prettier-config/index.js
- tests/integration/cli/config/external-config/esm-package-with-tla/node_modules/@company/prettier-config/package.json
- tests/integration/cli/config/external-config/esm-package-with-tla/package.json
> Add tests for #16857

- changelog_unreleased/angular/16922-2.md
- changelog_unreleased/angular/16922.md
- src/language-html/ast.js
- src/language-html/print-preprocess.js
- src/language-html/print/angular-icu-expression.js
- src/language-html/printer-html.js
- tests/format/angular/icu-expression/__snapshots__/format.test.js.snap
- tests/format/angular/icu-expression/issue-16914.html
> Improve angular ICU expression print

- src/cli/format-results-cache.js
> Improve `FormatResultsCache`

- src/utils/ignore.js
[`node-ignore` v7 introduced new `checkIgnore` method](https://github.com/kaelzhang/node-ignore/releases/tag/7.0.0), not sure what's the difference.
Looking at https://github.com/kaelzhang/node-ignore/issues/77, seems it fixes compatibility with `git check-ignore`
> Replace "node-ignore"'s `.ignores()` with `.checkIgnore()` method

- changelog_unreleased/api/16828.md
- changelog_unreleased/javascript/16163.md
- changelog_unreleased/javascript/7111.md
> Update changelog_unreleased for 3.5

- website/playground/Playground.js
\
Fixes https://github.com/prettier/prettier/issues/17021
> Comment out `objectWrap` for playground

- package.json
- scripts/build/build.js
- scripts/check-deps.js
- yarn.lock
> Use `node-text-style` in script files

- changelog_unreleased/BLOG_POST_INTRO_TEMPLATE.md
For https://github.com/prettier/prettier/pull/17043
> Update author notation in `BLOG_POST_INTRO_TEMPLATE`

- README.md
> Update links to website in README.md

- CONTRIBUTING.md
> Update debug script

- .github/workflows/dev-test.yml
Found this when checking https://github.com/codecov/codecov-action/blob/5efa07bc177542802086d6a447e0ba274759c103/action.yml#L26, ~hope~ it works
Before:
[info - 2025-02-08 09:35:47,841 -- Found 416 coverage files to report](https://github.com/prettier/prettier/actions/runs/13214375983/job/36891873059#step:7:236)
After:
[info - 2025-02-08 10:19:04,663 -- Found 1 coverage files to report](https://github.com/prettier/prettier/actions/runs/13214660802/job/36892500754?pr=17082#step:7:235)
> Add `disable_search` to `codecov/codecov-action`

- scripts/build/build-dependencies-license.js
- scripts/build/build-license.js
- scripts/build/config.js
> Separate license and third-party licenses

- changelog_unreleased/handlebars/15087.md
> Fix tag notation in changelog

- changelog_unreleased/javascript/16163.md
- website/blog/2025-02-09-3.5.0.md
> Fix a link in changelog

- commands.md
Updated commands.md to fix incorrect links called out in the issue https://github.com/prettier/prettier/issues/14541
Fixes #14541
> docs: updated commands.md to fix links

- package.json
What do you think? @sosukesuzuki 
> Add `debug:watch` script

- docs/browser.md
- website/versioned_docs/version-stable/browser.md
Before:
After:
[Rendered](https://deploy-preview-17126--prettier.netlify.app/docs/browser#worker)
> Docs: Add example for module worker

- scripts/build/build-javascript-module.js
> Clean bundle script

- scripts/lint-changelog.js
> Use `URL`s in `lint-changelog.js`

- scripts/lint-changelog.js
> Fix `lint-changelog` script

- package.json
Similar to #17086, add another script
> Add `debug:inspect` script

- scripts/build/build-package-json.js
> Add note on re-enabling module-sync

- scripts/release/package.json
- scripts/release/steps/install-dependencies.js
- scripts/release/steps/publish-to-npm.js
- scripts/release/steps/update-changelog.js
- scripts/release/utils.js
- scripts/release/yarn.lock
Similar to #17128, but for release script
> Replace `execa` with `nano-spawn` in release script

- scripts/build-website.js
- website/static/service-worker.js
- website/static/worker.js
> Lazy load plugins in playground

- changelog_unreleased/api/17166.md
- docs/api.md
- src/index.d.ts
- src/main/plugins/load-plugin.js
- tests/integration/__tests__/plugins.js
> Support `URL` in `plugins` options

- changelog_unreleased/api/17167.md
- src/config/resolve-config.js
- src/index.d.ts
- tests/integration/__tests__/config-resolution.js
- tests/integration/cli/config/custom-config-file-location/my-prettier-config.mjs
> Accept `URL` as custom config file in `resolveConfig`

- src/language-js/comments/handle-comments.js
@sosukesuzuki We can't use `.loc` since not all parsers has this property.
> Fix line compare

- src/language-html/print/tag.js
- src/language-js/comments/handle-comments.js
- src/language-js/loc.js
- src/language-js/parse/postprocess/index.js
- src/language-js/print/comment.js
- src/language-js/print/flow.js
- src/language-js/print/jsx.js
- src/language-js/print/module.js
- src/language-js/print/property.js
- src/language-js/utils/get-raw.js
- src/language-js/utils/index.js
- src/language-js/utils/is-line-comment.js
- tests/integration/__tests__/format-ast.js
> Add assertions to location sensitive nodes

- scripts/changelog-for-patch.js
- scripts/draft-blog-post.js
- scripts/utils/changelog.js
For the blog post, we have categories above the entries, but for patch release, we don't. Add category name to the title to be more clear.
> Add title to patch release changelog

- scripts/build-website.js
- scripts/build/esbuild-plugins/evaluate.js
> Fix build script for Node.js v23

- .github/renovate.json5
> Group regexp related dependencies in renovate.json5

- docs/precommit.md
- website/versioned_docs/version-stable/precommit.md
> docs: add pretty-quick section back

- .github/workflows/autofix.yml
- docs/ci.md
- website/sidebars.json
- website/versioned_docs/version-stable/api.md
- website/versioned_docs/version-stable/ci.md
- website/versioned_sidebars/version-stable-sidebars.json
Fixes #16385
Rendered https://deploy-preview-17215--prettier.netlify.app/docs/ci
> Docs: document how to use `autofix.ci`

- website/package.json
- website/yarn.lock
Regenerate lock file to update babel
https://github.com/prettier/prettier/pull/17241
https://github.com/prettier/prettier/pull/17242
https://github.com/prettier/prettier/pull/17243
will be closed
> Update website dependencies

- .github/codeql/codeql-config.yml
Fix errors  https://github.com/prettier/prettier/actions/runs/13807682536/job/38621874713#step:4:2572 by ignore the test fixtures.
> Fix CodeQL Analysis

- .github/workflows/lint.yml
- https://github.com/actions/dependency-review-action
- https://github.com/prettier/prettier/issues/17072
> Add `dependency-review-action`

- src/document/debug.js
> Support `cursor` in `printDocToDebug()`

- package.json
- src/language-markdown/constants.evaluate.js
- yarn.lock
> Update `cjk-regex` to v3.3

- website/docusaurus.config.js
- website/package.json
- website/yarn.lock
> Enable Docusaurus Faster

- src/language-js/parse/espree.js
- src/language-js/parse/flow.js
- src/language-js/parse/postprocess/index.js
- src/language-js/parse/typescript.js
Prevent bugs found when working in https://github.com/prettier/prettier/pull/17238
> Assert `TemplateElement` location

- src/language-handlebars/parser-glimmer.js
Turns out we don't need `lines-and-columns` to get `offset`.
> Simplify glimmer parse

- cspell.json
- website/docusaurus.config.js
Fixes https://github.com/prettier/prettier/issues/17294.
When the upstream Docusaurus issue is addressed either with a fix or a workaround, then we can turn on the other experimental features.
> Docs: fix emoji rendering on "Rationale" page

- website/data/editors.yml
Add Prettier+ to the Nova Extension list
First off, I’m the author of Prettier+. Just to get that out of the way.
The reason I’m adding my fork is that the original extension hasn’t been updated in nearly two years. Over the past four months, I’ve tried to upstream several of my changes, but I haven’t been able to get them in—likely because the original author has limited time to maintain the project.
Eventually, I got tired of waiting and decided to release my own extension with the changes. I'm still trying to upstream my changes, since the original extension has way more users, but this might take some time.
> Add `Prettier+` to the Nova extension list

- scripts/build/esbuild-plugins/add-default-export.js
> Minor tweak to ESBuild `addDefaultExport` plugin

- scripts/build/parse-arguments.js
- scripts/changelog-for-patch.js
> Use `util.parseArgs` in `changelog-for-patch.js` script

- src/cli/file-info.js
- src/cli/print-support-info.js
- tests/integration/__tests__/__snapshots__/file-info.js.snap
- tests/integration/__tests__/__snapshots__/infer-parser.js.snap
- tests/integration/__tests__/__snapshots__/support-info.js.snap
> Remove extra lines in `--file-info` and `--support-info`

- src/language-graphql/pragma.js
- src/language-html/pragma.js
- src/language-js/pragma.js
- src/language-yaml/pragma.js
- src/utils/pragma/pragma.evaluate.js
> Put pragma related code together

- changelog_unreleased/api/17339.md
- docs/options.md
- scripts/generate-changelog.js
- scripts/utils/changelog-categories.js
- scripts/utils/changelog.js
- src/index.d.ts
- src/language-html/languages.evaluate.js
- src/language-html/parser-html.js
- src/main/core-options.evaluate.js
- src/plugins/builtin-plugins-proxy.js
- tests/config/utils/check-parsers.js
- tests/dts/unit/cases/parsers.ts
- tests/format/mjml/mjml/__snapshots__/format.test.js.snap
- tests/format/mjml/mjml/format.test.js
- tests/integration/__tests__/__snapshots__/early-exit.js.snap
- tests/integration/__tests__/__snapshots__/help-options.js.snap
- tests/integration/__tests__/__snapshots__/plugin-options-string.js.snap
- tests/integration/__tests__/__snapshots__/plugin-options.js.snap
- tests/integration/__tests__/__snapshots__/schema.js.snap
- tests/integration/__tests__/__snapshots__/support-info.js.snap
- tests/unit/builtin-plugins.js
- website/playground/codeSamples.mjs
- website/playground/markdown.js
- website/playground/util.js
Ref: https://github.com/prettier/prettier/pull/17338#discussion_r2037607473
> Add `mjml` parser

- src/utils/infer-parser.js
Skip reading files if there are no `interpreters`, currently builtin plugins always loaded so there are `interpreters`, but we may remove them in the future, and this function is exposed for new CLI.
> Minor improvement to `inferParser`

- src/cli/directory-ignorer.js
- src/cli/expand-patterns.js
No logic change, just refactoring.
> Minor improvement to `expandPatterns`

- src/config/prettier-config/load-external-config.js
- yarn.lock
Noticed a size change in https://github.com/prettier/prettier/pull/17040, trying to find what's changed.
> Regenerate lock file

- changelog_unreleased/css/17362.md
- src/language-css/print/comma-separated-value-group.js
- tests/format/css/tailwind/__snapshots__/format.test.js.snap
- tests/format/css/tailwind/format.test.js
- tests/format/css/tailwind/utility-directive.css
> Support `@utility` directive for Tailwind

- .vscode/settings.example.json
> Update VSCode settings

- jest.config.js
- scripts/build/esbuild-plugins/evaluate.js
- src/index.cjs
- src/index.js
- src/main/version.evaluate.cjs
- src/main/version.evaluate.js
- src/standalone.js
The last/only CommonJS module (except cjs entry and cli entry) in source.
> Migrated version.evaluate.cjs to ES Module

- package.json
- tests/integration/run-cli.js
- yarn.lock
> [V4] Update `jest-light-runner` to v0.7.1

- .github/workflows/dev-test.yml
- package.json
- yarn.lock
> [V4] Test: Fix coverage collect

- eslint.config.js
- tests/config/get-prettier.js
- tests/config/run-format-test.js
- tests/config/utils/consistent-end-of-line.js
- tests/config/utils/visualize-end-of-line.js
- tests/integration/cli-worker.js
- tests/integration/run-cli.js
> [V4] Update ESLint config

- .github/workflows/dev-test.yml
- package.json
- yarn.lock
> [V4] Update jest-light-runner to v0.7.4

- .github/workflows/prod-test.yml
- jest.config.js
- package.json
- scripts/jest-light-process-runner.js
- yarn.lock
Another shot for the main branch https://github.com/prettier/prettier/pull/17131
Fixes #16964
> Test: Remove `--runInBand`

- tests/integration/cli-worker.js
> Remove outdated mock

- src/language-html/print/tag.js
Don't know why I slice the string twice in #16765
> Minor improvement to `doctype` print

- cspell.json
- website/docusaurus.config.js
- website/plugins/llms-txt-plugin.mjs
https://llmstxt.org/
https://deploy-preview-17388--prettier.netlify.app/llms.txt
https://deploy-preview-17388--prettier.netlify.app/llms-full.txt
> Website: generate `llms-full.txt` and `llms.txt` files

- changelog_unreleased/javascript/17398.md
- src/language-css/loc.js
- src/language-css/print/comma-separated-value-group.js
- tests/format/js/multiparser-css/__snapshots__/format.test.js.snap
- tests/format/js/multiparser-css/issue-16692.js
> Preserve spaces between CSS words and embedded expression

- src/language-js/parse/babel.js
- src/language-json/parser-json.js
- src/plugins/babel.js
> Internally use named export in babel parser

- changelog_unreleased/javascript/17470.md
- src/language-js/print/member-chain.js
- tests/format/js/method-chain/__snapshots__/format.test.js.snap
- tests/format/js/method-chain/issue-17457.js
> Fix inconsistent member chain format

- changelog_unreleased/javascript/17469.md
- src/language-js/print/assignment.js
- src/language-js/utils/index.js
- tests/format/js/assignment/__snapshots__/format.test.js.snap
- tests/format/js/assignment/issue-17437.js
> Fix inconsistent assignment format

- tests/format/angular/interpolation/html/17428.html
- tests/format/angular/interpolation/html/__snapshots__/format.test.js.snap
- tests/format/angular/interpolation/html/format.test.js
> Add a test for angular interpolation

- src/language-js/parse/oxc.js
- tests/config/run-format-test.js
@ArnaudBarre Thanks for your great work in #17491, all tests passed on `oxc` parser!
> Support type cast comments for `oxc` parser

- src/language-js/clean.js
- src/language-js/parse/postprocess/index.js
- src/language-js/print/enum.js
- src/language-js/print/flow.js
- src/language-js/print/object.js
- src/language-js/print/typescript.js
- src/language-js/traverse/visitor-keys.evaluate.js
- tests/unit/__snapshots__/visitor-keys.js.snap
Extracted from #15157, use the new AST, it's also needed for `oxc-ts` parser https://github.com/prettier/prettier/pull/17483
> Refactor Enum print

- tests/integration/__tests__/__snapshots__/experimental-cli.js.snap
- tests/integration/__tests__/experimental-cli.js
> Fix experimental-cli test

- scripts/build-website.js
- website/README.md
- website/playground/install-service-worker.js
- website/static/service-worker.mjs
- website/static/worker.mjs
> Update website build script

- scripts/generate-changelog.js
Use `URL` instead of path where possible.
> Remove `esm-utils` from "generate-changelog" script

- changelog_unreleased/javascript/17491.md
- src/language-js/parse/espree.js
- tests/config/run-format-test.js
> Support type cast comments for `espree` parser

- changelog_unreleased/angular/17534.md
- changelog_unreleased/api/17166.md
- changelog_unreleased/api/17167.md
- changelog_unreleased/api/17178.md
- changelog_unreleased/api/17331.md
- changelog_unreleased/api/17548.md
- changelog_unreleased/cli/17151.md
- changelog_unreleased/cli/17438.md
- changelog_unreleased/cli/17505.md
- changelog_unreleased/css/17362.md
- changelog_unreleased/flow/17520.md
- changelog_unreleased/javascript/17145.md
- changelog_unreleased/javascript/17190.md
- changelog_unreleased/javascript/17363.md
- changelog_unreleased/javascript/17472.md
> Fix English grammer in changelog_unreleased

- tests/format/flow/comments/__snapshots__/format.test.js.snap
- tests/format/flow/comments/normal-comments/11526.js
- tests/format/flow/comments/normal-comments/__snapshots__/format.test.js.snap
- tests/format/flow/comments/normal-comments/format.test.js
> Add test for #11526

- website/blog/2025-06-23-3.6.0.md
> Move CLI changelog upper

- website/src/pages/index.jsx
It failed to update during release due to network issue.
> Update dependents count

- .github/ISSUE_TEMPLATE/config.yml
> Add issue link for the experimental CLI

- src/language-js/parse/oxc.js
OXC added a new lang `dts`, so we don't need use fake `.d.ts` filename (from https://github.com/prettier/prettier/pull/17654 ).
> Use `lang` instead of fake file name in oxc parser

- packages/plugin-hermes/package.json
- packages/plugin-oxc/package.json
> chore: fix homepage link

- changelog_unreleased/scss/17836.md
- src/language-css/parser-postcss.js
- tests/format/scss/include/__snapshots__/format.test.js.snap
- tests/format/scss/include/format.test.js
- tests/format/scss/include/include.scss
> Fix parentheses space problem in mixin argument

- tests/format/css/comments/__snapshots__/format.test.js.snap
- tests/format/css/comments/block.css
- tests/format/css/comments/nestled.css
ref: https://github.com/prettier/prettier/pull/17848#issuecomment-3268133370
fix: #11564
> Add test case for comments

- changelog_unreleased/css/17841.md
- src/language-css/clean.js
- src/language-css/print/misc.js
- tests/format/css/attribute/__snapshots__/format.test.js.snap
- tests/format/css/attribute/insensitive.css
Ref https://github.com/prettier/prettier/pull/17841#issuecomment-3269615781
> Handle CSS attribute selector value ending with `I` flag

- changelog_unreleased/scss/17903.md
- src/language-css/parser-postcss.js
- tests/format/scss/mixin/5636.scss
- tests/format/scss/mixin/__snapshots__/format.test.js.snap
> Prevent matching mixin calls inside arguments

- yarn.lock
> Reinstall `@prettier/cli`

- packages/plugin-hermes/package.json
- packages/plugin-oxc/package.json
> Fix `types` entry for `@prettier/plugin-{hermes,oxc}`

- src/language-css/clean.js
- src/language-css/embed.js
- src/language-css/parser-postcss.js
- src/language-css/pragma.js
- src/language-css/print/sequence.js
- src/language-html/clean.js
- src/language-html/embed.js
- src/language-html/parser-html.js
- src/language-html/utils/index.js
- src/language-markdown/clean.js
- src/language-markdown/embed.js
- src/language-markdown/pragma.js
- src/language-markdown/unified-plugins/front-matter.js
- src/utils/front-matter/index.js
> Add `front-matter/index.js`

- tests/format/misc/errors/js/reserved-word/__snapshots__/format.test.js.snap
- tests/format/misc/errors/js/reserved-word/format.test.js
- tests/format/misc/errors/typescript/__snapshots__/format.test.js.snap
- tests/format/misc/errors/typescript/default-escaped.ts
- tests/format/misc/errors/typescript/format.test.js
> More parsers on reserved word tests

- src/language-html/embed/angular-attributes.js
- src/language-html/embed/angular-interpolation.js
- src/language-html/embed/print-vue-script-generic-attribute-value.js
- src/language-html/embed/vue-attributes.js
- src/language-html/embed/vue-bindings.js
Remove unnecessary arrow functions, move logic into the print function directly.
> Refactor embed format in HTML

- src/language-html/embed/attribute.js
> Simplify embed html detection

- src/language-html/embed/angular-attributes.js
- src/language-html/embed/angular-interpolation.js
- src/language-html/embed/attribute.js
- src/language-html/embed/class-names.js
- src/language-html/embed/event-handler.js
- src/language-html/embed/srcset.js
- src/language-html/embed/style.js
- src/language-html/embed/vue-attributes.js
> Split HTML attribute printers into test/print

- src/language-markdown/print-preprocess.js
> Replace an `array.reduce()`

- src/language-yaml/utils.js
> Rewrite `Array#reduce` in `getFlowScalarLineContents`

- src/language-yaml/utils.js
> Simplify `splitWithSingleSpace`

- src/utils/front-matter/embed.js
- tests/config/prettier-plugins/prettier-plugin-dummy-toml/index.js
- tests/config/utils/create-plugin.cjs
- tests/format/misc/front-matter/with-plugins/__snapshots__/format.test.js.snap
> Allow TOML front matter formatted by other plugins
