index.js
src/cli/util.js
src/main/multiparser.js
src/main/parser.js
tests_config/run_spec.js
tests_integration/__tests__/plugin-preprocess.js
tests_integration/plugins/preprocess/file.foo
tests_integration/plugins/preprocess/plugin.js
website/static/worker.js

As noted in prettier/prettier-swift#1
This allows plugins to preprocess the text that get's passed in and have Prettier update its `text` variable that is passed to `parse` and `attachComments` later.

Allow Plugins to preprocess text

---

docs/ignore.md

Makes https://prettier.io/docs/en/ignore.html#ignoring-files link directly to https://prettier.io/docs/en/cli.html#ignore-path

Make `--ignore-path` link more specific in docs

---

scripts/build/build-docs.js

fix(playground): avoid `assign to readonly` error on Safari

---

src/language-vue/printer-vue.js
tests/multiparser_vue/__snapshots__/jsfmt.spec.js.snap
tests/vue_examples/__snapshots__/jsfmt.spec.js.snap
tests/vue_examples/board_card.vue
tests/vue_examples/jsfmt.spec.js
tests/vue_examples/test.vue
website/pages/playground/index.html

Looks like the way the parsing works doesn't add `end` properties to self-closing tags and their parents (all the way up?). Couldn't figure out a nice way to fix it in the parser so just did it in the printer for now.
Copied in an example component from GitLabHQ.
Fixes #3692

Fix vue self-closing tags

---

src/language-markdown/printer-markdown.js
tests/markdown_list/__snapshots__/jsfmt.spec.js.snap
tests/markdown_list/indent.md
tests/markdown_list/jsfmt.spec.js

Fixes #3679
---
**Prettier pr-3694**
[Playground link](https://deploy-preview-3694--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEBiABAWQIYCcDWAJhAO5ToAqcAzjADpQMBU6AgugDYCWM6PcAWwboR6FgCEeAIwCuYfHF4C8RUuVxwAjjK4bq6ACzpqAB2xga6AGYRc6KDXiFOXWn3gD9ACgAWMGCbUSAD0wbTm+BAAbnC4VhykAHSQAsHYwQDMAOwArACcBtkATACUzOgAChr+sXxQhAgw+jAQ6EXGZhbeMNhS6CRchDA+6MQ0UADkvNRwgugt6NhWVnBgvDwlIAA0IBAmMFzQ1MigeLikFXgIxyjYURCD2yDYtMhW2BwzO1K4EYoAyp0uFAAObIGC4GRwHbEMBvD5fEDAma4GBVbAg5Twz7QkAAK2oAA9xL95ADsAI4AAZYFwbGIiAyAJMorgyG4sy4FHIEDKAjEMhPEy4YEwADqg2GyAAHAAGHbCiAzMW-Ew84U0WIxJ4abS6ODozHYem4mYCLhsqE7ajAkEcOAARRkEHgJp2PSkEqGPmQBndvy43FBAGEIAIsSgoNA6TsZDMKL0bu8cQBfFNAA)
```sh
--parser markdown
--tab-width 4
```
**Input:**
```markdown
* A lit item
* Bitbucket markdown requires 4 spaces for nested list items …
```

feat(markdown): respect `tabWidth` for list indentation

---

src/language-css/parser-postcss.js
src/language-css/printer-postcss.js
tests/css_scss/__snapshots__/jsfmt.spec.js.snap
tests/css_scss/scss.css

`postcss` add `node.important` when you use `!important`, but don't handle `!default`. 
Just remove `!default` from `value` and add `node.default` to detect when you use `!default`.
Issue: https://github.com/prettier/prettier/issues/2799

fix(scss): `!default` directive

---

.travis.yml
package.json
scripts/test-dist.js
tests_config/require_prettier.js
tests_integration/runPrettier.js
yarn.lock

Runs the production tests agains the result of actually installing the package, rather than from the `dist` directory. 
Extracted from #3712
Fixes #3698

Run production tests on npm package

---

src/language-js/printer-estree.js
tests/ternaries/__snapshots__/jsfmt.spec.js.snap
tests/ternaries/indent.js
tests/ternaries/jsfmt.spec.js

Fixes #3384 
Only affects `tabWidth > 2`.
---
**Prettier pr-3747**
[Playground link](https://deploy-preview-3747--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuc0DOMAEAxCFMC8mAFAJSEB8JAOlJvZgDwAmAlgG4W0M+bABmeQgSJQArgBsJ3XrID8maiCUzZPJJkH4RRGACcxcVWp4KlATThoVdE7w1KAchCUBfY4wD0bTrVIBuEAAaEAgABxhWdGRQML1WWAB1VmYYAAtkABYABhCYAEMAI2TUjKRMkLQEgHMJOABFMQh4ZH58iTQ4PL181gkagGEIAFth-OQQKGg4YJBCnrAAazgYAGUw-LAa5H1DEIArNAAPACEF5bX84bgAGQSZpDaOrpANvU69CcKigE8JaFmnWGrB2BheYk6ABUimhWu1OiEEh8YAAFHrVMZw54hPRwACOYlYuLR+Qx40e8JecQgnUSPTCEziVjgenYMxC+T0eggAHcUZyELCUPl2BAUrNmBAwFiESB8hgZS8IGIYGEVQAmRWuVxAA)
```sh
--print-width 40
--tab-width 4
```
**Input:**
```jsx
const Foo = () => (
<div>
{foo === null
? ""
: foo === true
? "Yes"
: "No"}
</div>
);
```
**Output:**
```jsx
const Foo = () => (
<div>
{foo …
```

fix(javascript): indentation for sub-ternaries

---

src/language-vue/embed.js
tests/multiparser_vue/__snapshots__/jsfmt.spec.js.snap
tests/multiparser_vue/lang-ts.vue
tests/multiparser_vue/lang-tsx.vue

vue-language-server requires that lang must be "tsx" when <script> contains TSX syntax, like below:
```jsx
<script lang="tsx">
import { VNode } from "vue";
export default {
render(): VNode { return <div>foo</div>; }
}
</script>
```
But prettier does not treat this code as TypeScript. This PR will fix this problem.

[vue] fix: *.vue with `lang='tsx'` is not formatted

---

package.json
tests/markdown_link/__snapshots__/jsfmt.spec.js.snap
tests/markdown_link/entity.md
tests/markdown_list/__snapshots__/jsfmt.spec.js.snap
tests/markdown_list/interrupt.md
yarn.lock

fix(markdown): update remark-parse to v5.0.0

---

website/core/Footer.js

I get this message in the console when visiting the website:
> GitHub Buttons deprecated `data-count-api`: use `data-show-count="true"` instead. Please refer to https://github.com/ntkme/github-buttons#readme for more info.
I updated the code for the star button in the footer to use the latest syntax.

Fix deprecation warning from Github Buttons on website

---

src/language-css/parser-postcss.js
tests/css_scss/__snapshots__/jsfmt.spec.js.snap
tests/css_scss/scss.css

Fixes #3719 
Right now media parser is very buggy for scss, i think better print media params with interpolation as is (it is don't break code).

fix(css): ignore `media` params with scss interpolation

---

src/language-css/clean.js
src/language-css/printer-postcss.js
tests/css_attribute/__snapshots__/jsfmt.spec.js.snap
tests/css_attribute/insensitive.css
tests/css_attribute/namespaces.css
tests/css_attribute/quotes.css
tests/css_attribute/spaces.css

Also add tests.
`[foo|att=val] {}` - namespace attribute selector - https://drafts.csswg.org/css-namespaces-3/#css-qnames

fix(css): handle namespace in attribute selector

---

src/language-js/printer-estree.js
tests/require-amd/__snapshots__/jsfmt.spec.js.snap
tests/require-amd/jsfmt.spec.js
tests/require-amd/require.js

See issue #3829. This commit keeps define calls as a unit when possible,
to prevent an extra indent in the body of an AMD-style define.
Rather than adding the "define" check in the same case as the existing
"require" check, I added a separate condition to explicitly call out the
fact that this checks for both AMD and CommonJS modules.
`yarn test -u` yields no changes, and `yarn lint` passes successfully.

Treat define calls like require

---

src/language-js/printer-estree.js
tests/return/__snapshots__/jsfmt.spec.js.snap
tests/return/comment.js

This one was kind of tricky, I'm still not sure why it was breaking in `(function () { /* code */ })` but not `fn(function() { /* code */ });`. Either way, if there's a comment in a return argument it probably requires a hardline, instead of a softline/line. Apparently, there weren't any specific tests relying on the softline/line so I guess this should be ok?
Fixes #3648

Force break if comment in return argument

---

src/language-css/parser-postcss.js
src/language-css/printer-postcss.js
tests/css_inline_url/__snapshots__/jsfmt.spec.js.snap
tests/css_inline_url/inline_url.css

Partial fix https://github.com/prettier/prettier/issues/2835, stringify nodes inside unquoted urls.
Need fix in future:
```css
a {
background-image: url(/data/data/+0ThisIsLowerCased);
}
```

fix(css): stringify unquoted data urls

---

package.json
scripts/build/rollup.parser.config.js
tests/flow/constructor_annots/__snapshots__/jsfmt.spec.js.snap
tests/flow/constructor_annots/constructors.js
tests/jsx_spread/jsfmt.spec.js
yarn.lock

This also enables spread operator on jsx on the flow parser:
```js
<div>{...list}</div>
```
I had no idea it was even a thing.
I had to comment out a flow test that no longer parses, but it's no longer in the flow repo and the comment said that it shouldn't be working anyway so I don't think it's going to be a problem.
Fixes #3898

Upgrade flow to 0.64

---

index.js
src/common/fast-path.js
src/common/util-shared.js
src/common/util.js
src/language-css/index.js
src/language-css/printer-postcss.js
src/language-graphql/index.js
src/language-graphql/printer-graphql.js
src/language-handlebars/index.js
src/language-html/embed.js
src/language-html/index.js
src/language-html/printer-htmlparser2.js
src/language-js/index.js
src/language-js/printer-estree.js
src/language-markdown/printer-markdown.js
src/main/ast-to-doc.js
src/main/comments.js
src/main/options.js
src/main/parser.js
tests_integration/__tests__/util-shared.js

This is a first attempt to extract the parser-specific location extraction code (`locStart` and `locEnd` in `/common/util.js`) so that it can be configured by plugins - see https://github.com/prettier/prettier-php/pull/14 for more background.
This PR splits `util.js` in a "private" and a "public" part; the public one is configurable by passing `options` to it. It also shows how an example of it's usage for the HTML printer. In order to get this merged, all printers would have to be adapted to use new argument `util` in 
```javascript
genericPrint(path, options, print, args, util)
```
instead of importing it directly.
I thought I'd open this PR already to ask if this is going in the right direction. Thanks!

Split out location extraction into plugin config

---

package.json
tests/css_color/__snapshots__/jsfmt.spec.js.snap
yarn.lock

Hex `#f09f` now parse correctly

chore(css): update `postcss-values-parser` to latest version

---

src/language-css/printer-postcss.js
tests/css_atrule/__snapshots__/jsfmt.spec.js.snap
tests/css_atrule/return.css
tests/css_parens/__snapshots__/jsfmt.spec.js.snap
tests/css_parens/parens.css
tests/css_scss/__snapshots__/jsfmt.spec.js.snap

Feel free to feedback.
In short:
1. Always space before and after `*`.
2. Always space before and after `*` and `/` in calc function.
3. Don't touch `+` and `-` inside in `calc`, spec require always use space, but we don't prettify invalid syntax.
4. Always space before and after `/` if before or after `func`, `word`.
5. Refactor.
6. A lot of tests.
7. Ignore all in `url`.

feat(css): improve math output

---

src/language-js/printer-estree.js
tests/typescript_non_null/__snapshots__/jsfmt.spec.js.snap
tests/typescript_non_null/member-chain.js

Fixes #3999
When encountering a `TSNonNullExpression`, don't abort the chain. Just include it with the current group.

fix(typescript): properly chain when there is a TSNonNullExpression

---

.pre-commit-hooks.yaml

Prettier now runs on markdown files! Let's let pre-commit run on those files!
(There may be additional file extensions that we should also add?)
cc @asottile

Add support for markdown with pre-commit

---

src/language-css/parser-postcss.js
src/language-css/printer-postcss.js
tests/css_quotes/__snapshots__/jsfmt.spec.js.snap

Note:
1. Use `postcss-media-query-parser` only for standard css at rules with params, because we can break other code (example postcss plugin which add own at rules or less).
2. Don't parse unknown at rules, it is also can break code (including change quotes, numbers and etc).
3. Refactor code to improve readability

refactor: at rules parse

---

src/common/support.js
src/language-handlebars/index.js
src/language-html/index.js
src/main/options.js
tests_integration/plugins/extensions/plugin.js

Fixes the issue raised in https://github.com/prettier/plugin-php/issues/55

Do not require plugins to set 'since' field

---

src/config/resolve-config-editorconfig.js
tests_integration/__tests__/__snapshots__/config-resolution.js.snap
tests_integration/__tests__/__snapshots__/with-config-precedence.js.snap
tests_integration/cli/config/js/file.js

Fixes https://github.com/prettier/prettier/issues/3963#issuecomment-366420997
The test changes look a little strange, but see here for context:
https://github.com/prettier/prettier/pull/3255#issuecomment-348420546

Respect EditorConfig when `--config` is passed

---

src/language-markdown/printer-markdown.js
tests/markdown/__snapshots__/jsfmt.spec.js.snap
tests/markdown_code/__snapshots__/jsfmt.spec.js.snap
tests/markdown_code/indent.md
tests/markdown_list/__snapshots__/jsfmt.spec.js.snap
tests/markdown_spec/__snapshots__/jsfmt.spec.js.snap

Context: https://github.com/prettier/prettier/issues/3459#issuecomment-366382620
This PR improves the indenting experience in VSCode (probably other editors as well) and also fixes #3459, I'm not sure if this is the proper fix but at least we can see the result and decide if it should be closed/merged.
- align list prefix with `tabWidth`
- it only affect ordered lists if `tabWidth: 2`, otherwise all lists.
cc @kachkaev
---
**Prettier pr-3990**
[Playground link](https://deploy-preview-3990--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEBGAdAAgMIAsCGUA5nJjBJgJ4QCuATprhALakAmAlnXGOXZUgA6UYZjHixYNsOEAmLABkOAZxhlcpSLAQxlQkVAkSANsswBaYyAA0ICAAcYHaMuSh8dOhADuABQ8Irij4AG4QHGw2IPiqyABm+KZwtgBGdPhgANZwMADK9hkcxMgwdDTJIGwQYPGJyhVF9XQwvulEzPi1SbYAVsoAHgBC6Vk5ufisSlBwXfW2tDD2NDCyJWUVBXRNyCAddJlV3l …

feat(markdown): respect tabWidth for list items

---

website/data/users.yml

[`webpack/webpack-cli`](https://github.com/webpack/webpack-cli) has used Prettier for a while, but now [`webpack/webpack`](https://github.com/webpack/webpack) does, too!
https://github.com/webpack/webpack/pull/6081

webpack/webpack now uses Prettier

---

src/language-css/parser-postcss.js
src/language-css/printer-postcss.js
tests/css_parens/__snapshots__/jsfmt.spec.js.snap
tests/css_parens/parens.css
tests/css_scss/__snapshots__/jsfmt.spec.js.snap

Why?
1. It is non standard.
2. It is break standard css specification.
3. Rare usage.
4. Many logic around this = decrease perf
5. I don't found right syntax. 
In 7-8 IE (with newlines) don't work, in IE 9 work :confused: 
```
progid:DXImageTransform.Microsoft.gradient(
enabled='false', 
startColorstr='#fff', 
endColorstr='#000'
);
```
6. Very buggy property :smile: 
Let's output this property as is

feat: ignore non standard IE filter values

---

src/language-js/printer-estree.js
tests/typescript_non_null/__snapshots__/jsfmt.spec.js.snap
tests/typescript_non_null/member-chain.js

Fixes #4051
Tests are failing but its the same tests that are failing on master (see #4053), in typescript conditional code; unrelated to chaining.

Fix TypeScript regression by moving non-null assertion to the end of the line instead of the beginning

---

website/blog/2018-02-26-1.11.0.md

The link wasn't a link in the truncated preview: https://prettier.io/blog/

Fix @orta's link

---

src/language-js/printer-estree.js
tests/class_comment/__snapshots__/jsfmt.spec.js.snap
tests/classes/__snapshots__/jsfmt.spec.js.snap
tests/classes/property.js
tests/classes_private_fields/__snapshots__/jsfmt.spec.js.snap
tests/classes_private_fields/with_comments.js
tests/typescript/custom/abstract/__snapshots__/jsfmt.spec.js.snap
tests/typescript/custom/abstract/abstractPropertiesWithBreaks.ts

When printing a `BinaryExpression` we have a few checks to determine if we should indent when breaking it. One of the checks is if the parent already adds indentation or not (which is the case for assignment expressions) and class properties were not included in this check.
Closes #4079

Prevent "over-indenting" class properties values

---

docs/precommit.md

Since pretty-quick replaced the _other_ pre-commit: https://github.com/prettier/prettier/pull/3675

No longer need to clarify that `pre-commit` is "Python version"

---

src/language-vue/embed.js
tests/vue_examples/__snapshots__/jsfmt.spec.js.snap
tests/vue_examples/self_closing_style.vue

With Vue we special case printing of `style` and `script` tags to format their content, but we shouldn't do that if they're an unary (self-closing) tag.
Closes #4106

Fix self-closing style tags in vue

---

src/language-markdown/embed.js
tests/multiparser_markdown_js/__snapshots__/jsfmt.spec.js.snap
tests/multiparser_markdown_js/markdown-preview-enhanced.md

Fixes #4150
- support ` ```js {something=something} `
- **does not** support ` ```js{something=something} `

feat(markdown): support fenced codeblock lang followed by attributes

---

package.json
src/language-js/printer-estree.js
tests/typescript/custom/modifiers/__snapshots__/jsfmt.spec.js.snap
tests/typescript/custom/modifiers/minustoken.ts
yarn.lock

Fixes #4158
TypeScript 2.8 has granular control on mapped type modifiers. Meaning you can also remove modifiers like `readonly` and `?` in mapped types.
This PR adds support for `TSMinusToken` and `TSPlusToken`, so following code could be formatted correctly.
```ts
type MutableRequired<T> = { 
-readonly [P in keyof T]-?:T[P] 
};  // Remove readonly and ?
type ReadonlyPartial<T> = {
+readonly [P in keyof T]+?:T[P] 
};  // Add readonly and ?
```

feat(typescript): support TSMinusToken and TSPlusToken

---

src/common/fast-path.js
tests/typescript_as/__snapshots__/jsfmt.spec.js.snap
tests/typescript_as/as.js

Add "UpdateExpression" to the list of parent node types that cause a "TSAsExpression" (and similar expressions) to require parenthesis.
Fixes #4167
NOTE: The tests_integration/debug-check unit test is failing. This failure existed before I made any changes, so I did not touch it. I only updated tests related to my change.

Require parenthesis around "TSAsExpression" inside an "UpdateExpression"

---

scripts/build/build.js

Fixes https://github.com/prettier/prettier/issues/4179
I tried the `.gitignore` idea, but it didn't work, presumably because we
publish from `dist/` instead of the repo root. See here for more details
on how/why this solution works:
https://docs.npmjs.com/files/package.json#files

Don't publish nested tarballs

---

src/language-js/embed.js
tests/multiparser_js_css/__snapshots__/jsfmt.spec.js.snap
tests/multiparser_js_css/styled-components.js

fixes #4218
Very critical bug, it is affect on multi parser anywhere you use `prettier-ignore` comment(s), including `js` in `markdown`, `css` in `js` and etc. I recommend patch release.

fix: mangles template literal when you use `prettier-ignore`

---

src/language-js/printer-estree.js
tests/ternaries/__snapshots__/jsfmt.spec.js.snap

We'll reuse the same logic from JSX mode to only group at the outermost ternary, forcing all ternaries in a chain to break if any of them break.
Closes #3018

Break nested ternaries

---

src/language-js/comments.js
src/language-js/printer-estree.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/flow/refinements/__snapshots__/jsfmt.spec.js.snap
tests/if/__snapshots__/jsfmt.spec.js.snap
tests/if/comment_before_else.js

I chose to treat comments as:
- trailing comments of the consequent, if it's a `BlockStatement`
- dangling comments of the `IfStatement` otherwise. (I'm not quite sure this is conceptually correct. Thoughts?)
In this PR I'm always printing as:
```js
if (cond) {
}
// comment
else {
}
if (cond) {
} /* comment */ else {
}
```
Should `// comment`s always be printed in their own line or should we detect if they're on the same line? Same for `/* comment */`s should always be printed in the same line?
Closes #2573

Handle comments before `else`

---

src/language-js/embed.js
tests/multiparser_js_graphql/__snapshots__/jsfmt.spec.js.snap
tests/multiparser_js_graphql/backticks.js

This one was hard to write the title :sweat_smile:
When we parse embedded GraphQL, we use the `raw` value from the template literal, which includes escape characters, e.g.:
```gql
"\`foo\` mutation payload."
type FooPayload {
bar: String
}
```
We should probably pass the `cooked` value instead, because they're only meaningful in the JS context, and escape the result of the "foreign" language printer (which is what the markdown embed does).
Closes #4258

Fix embedded GraphQL in JS with backticks

---

src/language-js/printer-estree.js
tests/destructuring/__snapshots__/jsfmt.spec.js.snap
tests/destructuring/destructuring.js

Context: #2550
After significant demand, this PR introduces an heuristic to always break `ObjectPattern`s if there are any nested `ObjectPattern` (or `ArrayPattern` in that case) properties.
I chose not to use the "always break if any property has a value" for now and not to break the outermost `ObjectPattern` if it's a function argument.
I personally think it's a good compromise, but I didn't mark to close the issue yet.
Let me know what you think!

Break `ObjectPattern`s with nested `ObjectPattern`s

---

src/language-markdown/index.js
src/language-markdown/printer-markdown.js

Also fixes the `TypeError: options.locStart is not a function` issue in playground, e.g. #4272.

refactor(markdown): use built-in ignore

---

src/language-js/embed.js
tests/multiparser_js_graphql/__snapshots__/jsfmt.spec.js.snap
tests/multiparser_js_graphql/invalid.js

Follow-up to https://github.com/prettier/prettier/pull/4265#issuecomment-379236243
If any of the quasis inside the ``` gql`` ``` template have an invalid escape sequence, its `cooked` value will be `null` and will break formatting. We'll bail out formatting the embedded and print the template as is.

Prevent formatting GraphQL embedded in JS if it contains invalid escape sequences

---

src/language-js/comments.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/break-continue-statements.js
tests/comments/continue-statement.js

A comment between `continue` and `;` was treated as a dangling comment of a `ContinueStatement`. I'm not sure there's that much value in keeping it like this so I chose treat as a trailing comment instead, which will move it to after the `;` (and will be stable afterwards).
Same for `break`
Closes #4276

Handle ContinueStatement and BreakStatement comments

---

src/language-markdown/index.js
src/language-markdown/pragma.js
src/language-markdown/printer-markdown.js
tests/insert-pragma/markdown/__snapshots__/jsfmt.spec.js.snap
tests/insert-pragma/markdown/front-matter.md
tests/insert-pragma/markdown/jsfmt.spec.js
tests/insert-pragma/markdown/simple.md
tests/insert-pragma/markdown/start-with-comment.md
tests/require-pragma/markdown/__snapshots__/jsfmt.spec.js.snap
tests/require-pragma/markdown/empty-front-matter-with-pragma.md
tests/require-pragma/markdown/empty-front-matter-without-pragma.md
tests/require-pragma/markdown/front-matter-with-pragma.md
tests/require-pragma/markdown/front-matter-without-pragma.md
tests/require-pragma/markdown/jsfmt.spec.js
tests/require-pragma/markdown/with-pragma-in-multiline.md
tests/require-pragma/markdown/with-pragma.md
tests/require-pragma/markdown/without-pragma.md

_hasPragma_
**support**
```md
```
```md
---
something
---
```
```md
```
---
_insertPragma_
**support**
```diff
+ 
+
something something
```
```diff
---
seomthing
---
+ 
+
something something
```
**does not support**
```diff
```

feat(markdown): support hasPragma/insertPragma

---

src/language-js/comments.js
src/language-js/printer-estree.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/export.js

The underlying bug in #4291 is actually because we were attaching every comment inside a named export as leading comments of that export. Leading and trailing comments are not ignored with `// prettier-ignore` so they are printed twice.
This PR removes the special handling of comments inside named exports and simply print them correctly in the printer.
Closes #4291

Stop marking all comments in named exports as leading comments

---

src/language-js/printer-estree.js
tests/typescript_export/__snapshots__/jsfmt.spec.js.snap
tests/typescript_export/default.js

Never print a semicolon after `export default interface Foo {}`

---

src/doc/doc-utils.js
src/language-js/printer-estree.js

I couldn't think of a reason why `rawText` should live in `doc-utils`, it's probably misplaced.

refactor(doc-utils): move `rawText` to printer-estree

---

src/common/util-shared.js
src/common/util.js
src/doc/doc-utils.js
src/language-js/embed.js
src/language-markdown/embed.js
src/language-markdown/printer-markdown.js

Just noticed we have two `mapDoc`.

refactor(util): remove duplicate mapDoc

---

src/language-js/needs-parens.js
tests/async/__snapshots__/jsfmt.spec.js.snap
tests/async/await_parse.js
tests/typescript/compiler/__snapshots__/jsfmt.spec.js.snap

Fixes #4138 by wrapping await expressions inside of unary expressions.  ([list of unary operators](https://scotch.io/tutorials/javascript-unary-operators-simple-and-useful#toc-summary-of-all-unary-operators))
Sample input (currently prettier would leave this unchanged):
```javascript
const w = !await resolveIdentity(false);
const x = -await resolveIdentity(3);
const y = +await resolveIdentity('3');
const z = typeof await resolveIdentity(false);
```
Output:
```javascript
const w = !(await resolveIdentity(false));
const x = -(await resolveIdentity(3));
const y = +(await resolveIdentity('3'));
const z = typeof (await resolveIdentity(false));
```

Wrap awaits in unary expressions with parens

---

src/language-js/printer-estree.js
tests/union_intersection/__snapshots__/jsfmt.spec.js.snap
tests/union_intersection/test.js

Fixes #4323
See #4323 for all the context.
I'd love to get it merged and ship a dot release if possible with it. It's affecting a bunch of code and prevents upgrading to the latest version of prettier at Facebook. I know it's been there for a while (since 1.9.3...)

[flow] Fix union indent inside of function param with a name

---

docs/webstorm.md

#4320: add paths for the global installation to the WebStorm docs

---

src/language-css/parser-postcss.js
src/language-css/printer-postcss.js
src/language-css/utils.js
tests/css_trailing_comma/__snapshots__/jsfmt.spec.js.snap
tests/css_trailing_comma/jsfmt.spec.js
tests/css_trailing_comma/list.css
tests/css_trailing_comma/map.css

Allow trailing comma in scss list and maps

---

package.json
scripts/build/rollup.parser.config.js
src/language-js/printer-estree.js
tests/flow/traits/__snapshots__/jsfmt.spec.js.snap
tests/flow_implements/__snapshots__/jsfmt.spec.js.snap
tests/flow_implements/implements.js
tests/flow_implements/jsfmt.spec.js
tests/flow_mixins/jsfmt.spec.js
yarn.lock

Fixes #4240.
Followup to https://github.com/prettier/prettier/pull/4244, now that @duailibe's fix is published.
EDIT: Just for reference, PR for support of implements in Babylon/Babel is https://github.com/babel/babel/pull/7741, will update tests when it lands.

Bump flow to 0.70

---

src/language-js/printer-estree.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/return-statement.js
tests/method-chain/__snapshots__/jsfmt.spec.js.snap
tests/method-chain/d3.js

#1283 
```
d3.select('body')
.append('circle')
.at({width: 30, fill: '#f0f'})
.st({fontWeight: 600})
```
instead of 
```
d3
.select('body')
.append('circle')
.at({ width: 30, fill: '#f0f' })
.st({ fontWeight: 600 })
```
I'm not familiar with `jsfmt` and I'm not sure how to add a test for this; please let me know what changes are needed.

Nicer line wrapping for d3

---

src/language-js/index.js
tests/insert-pragma/json/__snapshots__/jsfmt.spec.js.snap
tests/insert-pragma/json/does-nothing.json
tests/insert-pragma/json/jsfmt.spec.js
tests/require-pragma/json/__snapshots__/jsfmt.spec.js.snap
tests/require-pragma/json/format-anyway.json
tests/require-pragma/json/jsfmt.spec.js

Following https://github.com/prettier/prettier/issues/3557#issuecomment-356280409 we should always format JSON even with `--require-pragma` and never add a comment even with `--insert-pragma`.
Making `hasPragma` for JSON always return true makes Prettier always format the JSON file, and stop trying to insert pragma because it thinks the code already has a pragma.

Fix pragma detection/insertion for JSON

---

package.json
src/language-js/printer-estree.js
tests/typescript_typeparams/__snapshots__/jsfmt.spec.js.snap
tests/typescript_typeparams/tagged-template-expression.ts
website/static/worker.js
yarn.lock

Fixes #4352
---
**Prettier pr-4353**
[Playground link](https://deploy-preview-4353--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wCU4ATAIQjTwF48SBPAG0oDoKBLANwB5gAMwgQkTGNm5QA5gF8AfAAMAOlDx4ARgEMwAaxnYIAVygVx2SgG41GgCTAMRjEQYK8TiC44iIctUpWIAA0IF4w3NBEyKDa2EYA7gAKcQjRKNq8ENwUISCa2Lp6cDAAyhi60jLIksZwodJEcLhJhTIAttrIQtqsTaEAVkRoVIX6JaXa7XAAMtJw3b39IBXYTdjIIDDMGHBEYFIYMHlO0jAA6jkwABbIABwADKGeTeeFGJtOe828C6GWAEdjNxLK1tB0ukgen16iAmu1uDVsHVQkQquwAIrGCDwRYw0IwbSaS4UG7IABMBMK3FYVQAwhB2p1NlBoH8QMYmgAVInpaFNORyIA)
```sh
```
**Input:**
```tsx
export const RedBox = styled.div<{foo: string}>`
background: red;
${props => props.foo}
`;
```
**Output:**
```tsx
export const RedBox = styled.div<{ foo: string }>`
background: red;
${props => props.foo};
`;
```

feat(typescript): support TaggedTemplateExpression typeParameters

---

package.json
src/language-js/printer-estree.js
tests/typescript_tsx/__snapshots__/jsfmt.spec.js.snap
tests/typescript_tsx/generic-component.tsx
website/static/worker.js
yarn.lock

Fixes #4259
---
**Prettier pr-4268**
[Playground link](https://deploy-preview-4268--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAeAsgTwMIQLYAO0CMqUArngEZwBOAfAAQAmAhjKwLzACMATAF9GAenogANCAgEYAS2gBnZKAK1ZsAOqzmMABbIAHAAZJHKlp36kfSQvUBzADZwAiuQjxkAM1aOFcU1pWWUcHXDw8VmQQKGIJECogsABrOBgAZQJWMAdkGFpyAJAAKwUADwAhJNSM1jw4ABl1OG9ff0ks2n9aaJhMAjgFMDUZeP88WTyCovJ-ABVWKiUkHz8i9W6YAAUg+0jWtclaOABHclljndY9qJW2otUIfw0ggmjVQboANxbJVlpaBAAO5bf4IZYgVhfCDaeJBKD2ODpDi0GDIEwgeGIgCiUGY6MkzAgYAO7UhCjRd0OUnIMAItL4pLgAgEQA)
```sh
```
**Input:**
```tsx
<MyComponent<number> data={12} />
```
**Output:**
```tsx
<MyComponent<number> data={12} />;
```

feat(typescript): support generic JSX element

---

src/language-css/parser-postcss.js
src/language-css/printer-postcss.js

Part of https://github.com/prettier/prettier/pull/4181. `postcss-value-parser` is abadoned and bad parser many bleeding edge in `at-rules`

feat: use `postcss-values-parser` for `@namespace` at rule

---

website/playground/Playground.js

Fixes the following case:
> **Prettier 1.12.1**
> [Playground link](https://prettier.io/playground/)
> 
> **Input:**
> ```jsx
> 
> ```
> 
> **Output:**
> ```jsx
> function HelloWorld({
>   greeting = "hello",
>   greeted = '"World"',
>   silent = false,
>   onMouseOver
> }) {
>   if (!greeting) {
>     return null;
>   }
> 
>   // TODO: Don't use random in render
>   let num = Math.floor(Math.random() * 1e7)
>     .toString()
>     .replace(/\.\d+/gi, "");
> 
>   return (
>     <div
>       className="HelloWorld"
>       title={`You are visitor number ${num}`}
>       onMouseOver={onMouseOver}
>     >
>       <strong>
>         {greeting.slice(0, 1).toUpperCase() + greeting.slice(1).toLowerCase()}
>       </strong>
>       {greeting.endsWith(",") ? (
>         " "
>       ) : (
> …
```

fix(playground): add missing `input` code sample for `copy markdown`

---

src/language-js/index.js
tests_integration/__tests__/__snapshots__/support-info.js.snap

Just noticed that jsonc (JSON with Comments) in VSCode is indeed just JSON + comments...

fix(json): jsonc is considered JSON instead of JSON5

---

website/static/separate-css/playground.css

fixes #4350
playground-container
overflow hidden forces the container to don't outgrow its space
sub-options
fixes Problem in Edge

avoid overflow in playground-container

---

src/language-js/printer-estree.js
tests/destructuring/__snapshots__/jsfmt.spec.js.snap
tests/destructuring/destructuring.js

In #4267 we started to break destructuring with "nested destructurings", except for function arguments which ignored the "first level". This PR applies the same exception to catch clauses parameters.
Context: #4384
---
**Prettier pr-4385**
[Playground link](https://5ae1d2908df8940c97484a26--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEMBOBPABMAvlsAQxjAAssAKYAE2MKRwFs4BnFwgczl1wEodcAHSjD02PAWJlKNOg2DM2nOPLho0ENCx58BIADQgIABxgBLaC2ShC6iAHcACrYRWUhAG4Qz1AyABGaIRgANZwMADKxsFmUBzI6ACucIaxLGowjkEcjITIAGaEADbphgBWLAAeAEJBoeERhMwAMrFwBcWlINFaasgBhP4YRdB+xmixMADqPjCkyAAcAAyG4xDpU0HG-eOsah7thmhwAI6JZsdZnLkdJSkg6YxmCWjJhiyxHEVwAIqJEPBbl0YIMZtQ5sgAEyGdCEMxFT4AYQgjBuKCg0EOIES6QAKoM3IU7jwgA)
**Input:**
```jsx
try {} catch ({data: {message}}) {}
try {} catch ({data: {message: {errors}}}) {}
``` …

Apply destructuring rules in functions to catch param

---

src/language-js/printer-estree.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/trailing-jsdocs.js

Closes #4412
We print trailing comments in their own line with a `lineSuffix` which buffers the comment until it finds a `hardline`. When we have a following JSDoc comment, we print each line with a `hardline` at the end. So what happens is:
- prints the node;
- buffers the trailing comment;
- prints the 1st line of the JSDoc `/**`;
- print the trailing comment;
- print the rest of the JSDoc
This PR changes the behavior for JSDoc as trailing comments (uncommon I guess) to print a hardline before it.

Fix trailing JSDoc comments with trailing regular comments

---

website/static/separate-css/playground.css

As discussed in https://github.com/prettier/prettier/pull/4406 the changes to the code mirror gutter styles cause problems during vertical scrolling. So this change reverts that changes.

revert changes to code mirror gutter styles

---

src/language-js/printer-estree.js
tests/typescript_import_type/__snapshots__/jsfmt.spec.js.snap
tests/typescript_import_type/import-type.ts
tests/typescript_import_type/jsfmt.spec.js

Ref: Microsoft/TypeScript#22592
---
**Prettier pr-4429**
[Playground link](https://deploy-preview-4429--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3zSQEsBbLXACjwYB0QA6AegDMIJmG8BKALzAyABgA0ATySiAvgG5GUJehr4ANnHzSqa2s3ZcIAJl4N+LAEIBDbCwCSw60mbNxAIxkKlKzDg1aeEQAFlRIMJIYcBAceLr+9EysnNymIELANthIeFnG3lAg4iAQGDDk0ETIoLbYEADuAAq2CFUo1gBuEOQAJkUg7tjWYADWWgDKGMPkUADmyDDYAK5wxTNEcLiNQ7OU1sgc1uobxQBWRGiWQ6MT1pRwADIzcAdHJyBT2BvYyCARUUQwNhyGV+hhgbAAOq9GDBZAADgkHzqG0hQwwv3BcG+HRexWwcAAjktyATttZdvskIdjqsQBtKOQFss6UQZrNNABFJYQeCvWnFGDWdzQnqw5DGQVDcjqdkAYQglD2vyg0DxICWGwAKsK2jSNrJZEA)
```sh
```
**Input:**
```tsx
export const x:import(   "./foo"   )={x:0,y:0};
export let y:import("./foo2"   ).Bar.I={a:"",b:0};
export let shim:typeof import(   "./foo2")={Bar: …
```

feat(typescript): support TSImportType

---

.eslintignore

I generated coverage reports and then ran `yarn lint`. The script took ages to run and printed lots of useless errors.
Adding `/coverage/` to `.eslintignore` fixes `yarn lint`'s performance.

Add /coverage/ to .eslintignore

---

src/language-css/clean.js
src/language-js/clean.js
src/language-markdown/printer-markdown.js
src/language-vue/printer-vue.js
src/main/massage-ast.js

I'm not sure why but it seems some of them are unnecessary.
```js
[
"loc",
"range",
"raw",
"comments",
"leadingComments",   // js
"trailingComments",  // js
"extra",             // js
"start",             // js, vue
"end",               // js, vue
"tokens",
"flags",             // js
"raws",              // css
"sourceIndex",       // css
"id",
"source",            // css
"before",            // css
"after",             // css
"trailingComma",     // css
"parent",
"prev",
"position"           // md
].forEach(name => {
delete newObj[name];
});
```

refactor(massageAst): move target props to corresponding plugins

---

src/language-js/printer-estree.js
tests/typescript_cast/__snapshots__/jsfmt.spec.js.snap
tests/typescript_cast/generic-cast.ts

fixes #4171
fixes #4168
Implemented by adding a soft break between the cast and the expression. Also includes wrapping parentheses for clarity as suggested in #4171.
Avoids changing behavior at all though if casting an array or object literal because those already have good behavior where the array or object literal breaks before the cast does so including them would just result in a pointless extra layer of parentheses that would add no clarity because the `{ }` or `[ ]` wrapping the literal serves same purpose as the parentheses would.

 Improve formatting of TS casts with generics and unions

---

src/language-js/printer-estree.js
tests/typescript_import_type/__snapshots__/jsfmt.spec.js.snap

Just noticed that we forgot to add `qualifier` and `typeof` in #4429 but no error occurred until #4430.
My eyes... 🙈

fix(typescript): add missing `qualifier` and `typeof` in TSImportType

---

src/language-js/printer-estree.js
tests/classes/__snapshots__/jsfmt.spec.js.snap
tests/classes/property.js

This PR moves the `canBreak` check from `printAssignment` to `printAssignmentRight`, so that it can be used in class properties.
Fixes https://github.com/prettier/prettier/issues/4437

Fix: Correctly break class property initializers

---

src/language-js/printer-estree.js
tests/bind_expressions/__snapshots__/jsfmt.spec.js.snap
tests/bind_expressions/long_name_method.js
tests/bind_expressions/short_name_method.js

This PR inlines and adds a newline to long method in bind expressions.
Fixes #4417

Fix: Group long name method in bind expressions

---

docs/api.md
index.js
src/cli/constant.js
src/cli/index.js
src/cli/util.js
src/common/create-ignorer.js
src/common/get-file-info.js
src/main/options.js
tests_integration/__tests__/__snapshots__/early-exit.js.snap
tests_integration/__tests__/__snapshots__/file-info.js.snap
tests_integration/__tests__/early-exit.js
tests_integration/__tests__/file-info.js
tests_integration/plugins/automatic/node_modules/@prettier/plugin-foo/index.js

Closes #4253
---
This PR adds the following prettier method:
```js
const info = prettier.getFileInfo(filepath, opts);
// opts = {
//   ignorePath?: string,
//   withNodeModules?: boolean,
//   plugins: string[]
// }
```
and a corresponding CLI option:
```
prettier.js --help file-info
--file-info <path>
Extract the following info (as JSON) for a given file path. Reported fields:
* ignored (boolean) - true if file path is filtered by --ignore-path
* inferredParser (string | null) - name of parser inferred from file path
```
The new API method is designed to help text editors decide whether a file needs to be formatted on save. A call to it is vital given the introduction of plugins and thus no fixed mapping between file extensions and parsers. A file with the given path does not have to …

Implement prettier.getFileInfo() method and --file-info CLI option

---

website/static/worker.js

After #4341, because of `find-parent-dir`, the playground from master was broken
This is the kind of thing that makes me wish for #4449

Fix playground

---

scripts/build/build-docs.js
website/package.json
website/siteConfig.js
website/static/service-worker.js
website/yarn.lock

Leverage use of unpkg.com instead of manually copying stuff to `static/`
This is motivated by #4449 to simplify build processes

Simplify `build-docs.js`

---

docs/options.md

update the docs to give example for JSX brackets rule. All the options have examples and it makes sense to have one this use case as well.

update doc with example for JSX Brackets config

---

src/language-graphql/printer-graphql.js
src/language-handlebars/printer-glimmer.js
src/language-html/clean.js
src/language-js/clean.js
src/language-js/printer-estree-json.js
tests_config/run_spec.js

`stripLocation` should not exist since we do have `massageAst`, and also there's a bug in `stripLocation` that `null` will be transformed into `{}`.

refactor(massageAst): move stripLocation to corresponding plugins

---

src/common/common-options.js
src/language-css/options.js
src/language-graphql/options.js
src/language-js/options.js
src/language-markdown/options.js
tests_integration/__tests__/__snapshots__/support-info.js.snap
website/playground/Playground.js

While seeing where we were at with web, I tried to make a build containing only the markdown plugin, and was surprised to see files from the JS plugin get pulled in. This refactor just makes it a bit more obvious that these settings are shared across plugins.

(refactor): Move common options out of JS plugin

---

src/language-js/printer-estree.js
tests/test_declarations/__snapshots__/jsfmt.spec.js.snap
tests/test_declarations/angularjs_inject.js

Like #4241, but for the older Angular.
A code example (from [here](https://docs.angularjs.org/guide/unit-testing#using-beforeall-)):
```js
it("has calculated the answer correctly", inject(function(DeepThought) {
expect(DeepThought.answer).toBe(42);
}));
```

Inline AngularJS tests that use `inject`

---

src/main/core.js
tests/require-pragma/js/__snapshots__/jsfmt.spec.js.snap
tests/require-pragma/js/range-with-pragma.js
tests/require-pragma/js/range-without-pragma.js

Fixes https://github.com/prettier/prettier/issues/3985
`formatRange()` is only called from `formatWithCursor()`,
which already checks for the pragma.
EDIT: @JamesHenry, could you try this out and verify that it's working for you?

Don't format range if required pragma is missing outside range

---

.circleci/config.yml
.travis.yml

Context: #3919
With CircleCI we can make a "pipeline" that first builds the production bundle in a modern Node environment, then uses the built artifact to run test suites in other node versions (in parallel).
This opens up some new interesting possibilities that I'm really excited to explore in the near future

Set up CircleCI

---

src/language-js/embed.js

Minor refactor, removes unnecessary check `if (process.env.PRETTIER_DEBUG) throw error;` since the multiparser will already catch any error thrown in `embed`.

Remove unnecessary check for PRETTIER_DEBUG

---

src/language-css/parser-postcss.js
src/language-css/printer-postcss.js
src/language-markdown/parser-markdown.js
src/language-markdown/pragma.js
src/language-markdown/printer-markdown.js
src/utils/front-matter.js

A quick web [search](https://duckduckgo.com/?q=frontmatter) shows many matches for “front matter,” but few for “frontmatter.” Also, [Grammarly](https://www.grammarly.com) suggests that I use “front matter:”

Rename all uses of frontmatter to frontMatter or front-matter

---

src/language-css/printer-postcss.js
tests/css_scss/__snapshots__/jsfmt.spec.js.snap
tests/css_scss/scss.css

fixes #4294
We ignore all inside in string (no pretty output, print as is) with interpolation. 
Why?
1. It it feature and will be done in other PR
2. It is dangerous in some case:
Input:
```scss
a {
content: "#{my-fn("_")}";
}
```
If `my-fn` function found, output:
```scss
a {
content: "result-of-function";
}
```
If `my-fn` not found, output:
```scss
a {
content: "my-fn("_")";
}
```
IMHO, better don't touch right now this.

fix: scss interpolation in string

---

src/language-js/clean.js
src/language-js/embed.js
tests/angular_component_examples/__snapshots__/jsfmt.spec.js.snap
tests/angular_component_examples/jsfmt.spec.js
tests/angular_component_examples/test.component.ts

I had a free couple of hours on the flight back from ng-conf and so put together a POC for Angular Component inline template and style formatting. Would love feedback! More than a couple of folks at the conference asked me if this was something we could add to Prettier.
I can see from recent comments on issues that HTML support is not classed as stable yet? If this has to go in in two stages (first inline styles, then inline template once HTML is no longer experimental) then that would still be great.
The implementation is a little bit hacky as I did not have a WIFI connection and just did my best to emulate existing patterns from Vue formatting etc. so happy to make any updates you want me to. 
Example test case:
**UPDATED TO REMOVE HTML SUPPORT**
**Before:**
```ts
@Component({
selector: …
```

New: Format Angular Component styles

---

src/language-js/index.js

Many `PHP` projects use `composer` https://getcomposer.org/ (package manager for `PHP`) and many of this projects use `prettier` (I hope :smile:), also we have official `plugin-php`. Let's use same logic for `composer.json` as for `package.json`.

feat: handle `composer.json` as `package.json`

---

.travis.yml
package.json
scripts/build/build.js

Let's skip testing node 4 for the dev build. CircleCI tests the prod build

Drop node 4 support for development "build"

---

package.json
src/language-js/clean.js
src/language-js/parser-babylon.js
src/language-js/parser-flow.js
src/language-js/printer-estree.js
tests/literal-numeric-separator/jsfmt.spec.js
tests/nullish_coalescing/__snapshots__/jsfmt.spec.js.snap
tests/nullish_coalescing/jsfmt.spec.js
tests/nullish_coalescing/nullish_coalesing_operator.js
tests/pipeline_operator/__snapshots__/jsfmt.spec.js.snap
tests/pipeline_operator/pipeline_operator.js
yarn.lock

This updates babylon and flow. The motivation is that we want to start using `?.` and `??` at Facebook :)
The two big changes are:
- Babylon shipped the new decorator spec in master and you need to use the legacy one which has a slightly different API.
- The new `?.` spec adds "OptionalXXX" nodes, so we need to update all the call sites to support it. Thankfully @xixixao did most of the hard work in #4463

Update babylon & flow

---

src/language-js/printer-estree.js
tests/flow_typeapp_call/__snapshots__/jsfmt.spec.js.snap
tests/flow_typeapp_call/jsfmt.spec.js
tests/flow_typeapp_call/typeapp_call.js

Fixes #4489.
Babylon support landed in `beta.48` just now but requires a few other fixture changes, so I'm going to follow this up with another PR.

Add support for flow explicit type arguments

---

package.json
src/language-js/printer-estree.js
tests/flow_interface_types/__snapshots__/jsfmt.spec.js.snap
tests/flow_interface_types/interface_types.js
tests/flow_interface_types/jsfmt.spec.js
yarn.lock

Flow commit: https://github.com/facebook/flow/commit/4f93f3adb7a5fedd3d572d62d718cf48c15a08ce
Babel commit: https://github.com/babel/babel/pull/7973
Will follow up w/ flow team on making `InterfaceType` -> `InterfaceTypeAnnotation`, since it seems a bit inconsistent.

Add support for flow inline interfaces

---

package.json
src/language-js/parser-babylon.js
src/language-js/printer-estree.js
tests/flow_interface_types/jsfmt.spec.js
tests/flow_typeapp_call/jsfmt.spec.js
yarn.lock

We landed a change that added a new `InterpreterDirective` AST node type for hashbangs, and no longer add it as a comment/leadingComment.
Ref: https://github.com/babel/babel/pull/7928
I mimicked what we do in `@babel/generator` here, since I found it better than trying to add comments to the ast in `parser-include-shebang.js`). Definitely open to a better/cleaner option though!
Note: I'll follow this up with enabling tests for https://github.com/prettier/prettier/pull/4543 and https://github.com/prettier/prettier/pull/4540 once they land too.

Switch to @babel/parser

---

docs/options.md

Context: #4528
I don't know how to communicate the change between versions.
Related: do you think we should start versioning docs (supported by docusaurus)? Would this be enough to communicate changed values?
(versioning docs are also useful for "hiding" unreleased features anyway. so we should keep the `since v1.XX.X` we use and use docs versioning)

Update docs for default parser

---

src/language-js/printer-estree.js
tests/typescript_typeparams/__snapshots__/jsfmt.spec.js.snap
tests/typescript_typeparams/class-method.ts

fixes #4070; fixes #2581
Probably should not be merged until after #4219 is merged and I have a chance to rebase since I added some test cases here that might be affected by the changes there.

Improve format when passing ts arrow function with return type as an argument

---

website/static/overrides.css

`overflow-x: scroll` shows scrollbars under every code block even if they aren't scrollable:

website: Change pre overflow-x to auto

---

docs/related-projects.md

I really like prettier. I have recently continued to pay attention to prettier updates, waiting for prettier support to run in the browser. Today finally released version 1.3, so I wrote a chrome extension based on this version, thanks prettier!
🎨 An extension that can be formatted using Prettier in Chrome: 
https://github.com/u3u/prettier-chrome

docs(misc): add `prettier-chrome` project

---

src/language-js/printer-estree.js
tests/functional_composition/__snapshots__/jsfmt.spec.js.snap
tests/functional_composition/functional_compose.js

fix(javascript): regression for `hasOwnProperty`

---

src/cli/util.js
tests_integration/__tests__/__snapshots__/debug-check.js.snap
tests_integration/__tests__/debug-check.js
tests_integration/cli/debug-check/issue-4599.js

Fixes #4599
The regression was introduced in #4528, `output` is actually not prettified code under `--debug-check`, e.g. the check `output !== input` is actually `"index.js" !== "console.log("…");"` in #4599.
The returned value from `format()` is really confusing, we should refactor it.

fix(cli): regression for --debug-check + --list-different

---

src/language-markdown/printer-markdown.js
tests/markdown_html/__snapshots__/jsfmt.spec.js.snap
tests/markdown_html/blank-line-between-htmls.md
tests/markdown_ignore/__snapshots__/jsfmt.spec.js.snap

Fixes #4605 
The AST here is actually two `html`s and it did follow the [CommonMark spec](https://spec.commonmark.org/0.28/#html-blocks), so I ended up with respecting the blank line between block `html`s.

fix(markdown): respect blank line between block htmls

---

src/language-graphql/printer-graphql.js
tests/multiparser_js_graphql/__snapshots__/jsfmt.spec.js.snap
tests/multiparser_js_graphql/definitions.js

Fixes #4615
The root cause is the output doc from graphql printer does not match the desired input from `stripTrailingHardline`.
https://github.com/prettier/prettier/blob/a9b21a01e2d352aab06332e8e545e33efacc4f97/src/doc/doc-utils.js#L167-L180
---
**Prettier pr-4616**
[Playground link](https://deploy-preview-4616--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEBzATgQwA4AsCOANgAYA6UABBQGZaoC2CMFAHhdBQJ4XDlVUAvPhQC+5YbUwMmFTO0oAjHsKphhYqMQDcIADQgI2GAEtoAZ2ShM6dBADuABWsILKTADcIxgCZ6QCrDAAazgYAGVsTDBjKFRkGHQAVzh9GLM4dBgHOnpMZGpMQnT9ACszFgAhQJDwzEYAGRi4fMLikEj0dPRkf0wFTkJoP2x0GJgAdR8YXGQADgAGfRGIdPGsbB6RuC73Zv10OHxE4wPsqVyWopSQdPpjeKTrsxjUQjgARUSIeEu2mD7Jt5psgAEz6BKYYyEF4AYQg9AuKCg0D2IES6QAKn1XAUriIREA)
```sh
--parser babylon
```
**Input:**
```jsx
graphql`
fragment x on y {
z
}
fragment a …
```

fix(multiparser): no additional trailing newline for graphql in js

---

src/language-js/printer-estree.js
tests/typescript_import_type/__snapshots__/jsfmt.spec.js.snap
tests/typescript_import_type/import-type.ts

fix(typescript): preserve type parameters of import-types (#4656)

---

src/language-js/needs-parens.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/closure-compiler-type-cast.js

fix(javascript): preserve parens for type casting for sub-item

---

src/main/core.js

Removes redundant call to `normalizeOptions` (already done in preceding line)
https://github.com/prettier/prettier/blob/8ec543276838f66f0a84824a39c215a3039e9071/src/main/core.js#L260-L263

refactor: remove redundant call to normalizeOptions

---

.circleci/config.yml
jest.config.js
scripts/build/shims/assert.js
scripts/build/shims/os.js
scripts/test-dist.js
tests_config/require_standalone.js
tests_config/run_spec.js

This uses the [`vm.Script`](https://nodejs.org/api/vm.html) API to run the standalone build in an empty context. This is mostly to validate that our build is stripping all the "native" dependencies (native modules and env vars).
It might not be necessary to run *all* `run_spec` tests, but I figured why not?

Run tests using the standalone build in an empty context

---

src/main/ast-to-doc.js
src/main/options.js

This allows `prettier.__debug.formatAST` to not crash when given the AST
for the below code (taken from https://astexplorer.net/), which is
useful when trying to use Prettier as a code generator for an AST
without corresponding source code (https://github.com/prettier/prettier/issues/4675)
```js
let tips = [
"Click on any AST node with a '+' to expand it",
"Hovering over a node highlights the \
corresponding part in the source code",
"Shift click on an AST node expands the whole substree"
];
function printTips() {
tips.forEach((tip, i) => console.log(`Tip ${i}:` + tip));
}
```

Allow `originalText` to be passed to `formatAST()`

---

src/common/load-plugins.js

Resolves #4637 
Verified via:
```bash
git clone git@github.com:prettier/prettier /tmp/wat
cd /tmp/wat
nodeenv nenv
. nenv/bin/activate
npm install -g .
prettier --help
```

Fix `prettier` installed in a directory not named prettier

---

.circleci/config.yml
.gitignore
package.json
scripts/build/build.js
scripts/build/bundler.js
scripts/build/cache.js
scripts/build/util.js
scripts/release/steps/generate-bundles.js
scripts/release/utils.js
yarn.lock

I over-engineered the build script again. I'm saving the checksums of all the files included in each bundle, and in subsequent builds, I'll skip the build entirely if nothing changes.
In practice, this will be most relevant to skip bundling `parser-*.js` files since we most frequently change stuff in printer (i.e. only rebuild `index.js` and `standalone.js`), or we only make changes to a single parser at a time and can skip rebuilding all the others.
To be safe, we'll bundle everything if `yarn.lock` changes.
It works, but there's no pressure to merge this. To put things in perspective, the build in CircleCi currently takes around 4min.

[build] Cache build result

---

package.json
tests/optional_catch_binding/jsfmt.spec.js
yarn.lock

The main change in the parser is the support for optional catch bindings (which were a syntax error previously).

Upgrade flow-parser to 0.75.0

---

package.json
src/main/options.js
yarn.lock

Context: https://github.com/prettier/prettier/issues/4720#issuecomment-398757044
I think it'd be better to keep consistent in node/browser if possible.

fix(inferParser): filepath in standalone

---

src/language-js/printer-estree.js
tests/jsx/__snapshots__/jsfmt.spec.js.snap
tests/jsx/conditional-expression.js

This pull request aims to fix the issue of excessive nesting brought up in the following comment: https://github.com/prettier/prettier/issues/737#issuecomment-392541493
This "fix" is very simple. It adds a new possible way to activate JSX mode for ternary operators. If the first non-conditional parent of the expression is a JSX expression container, then JSX mode gets activated.
This branch also contains a test case for said scenario.

Ternary Operators in JSX Expression Containers

---

src/language-js/printer-estree.js
tests/jsx-fbt/__snapshots__/jsfmt.spec.js.snap
tests/jsx-fbt/jsfmt.spec.js
tests/jsx-fbt/test.js
tests/jsx-newlines/__snapshots__/jsfmt.spec.js.snap
tests/jsx-significant-space/__snapshots__/jsfmt.spec.js.snap
tests/jsx-split-attrs/__snapshots__/jsfmt.spec.js.snap
tests/jsx-stateless-arrow-fn/__snapshots__/jsfmt.spec.js.snap
tests/jsx-text-wrap/__snapshots__/jsfmt.spec.js.snap
tests/jsx-text-wrap/test.js

This is partial progress towards https://github.com/prettier/prettier/issues/2279
With this PR we now detect Facebook `fbt` tags and handle whitespace for them differently from other JSX tags.
This lets us tweak how we format whitespace in JSX tags without breaking the Facebook translation pipeline. This means we can now fix up some small JSX formatting edge cases that have always bugged me 😀
The main benefit here is improved consistency across different but equivalent inputs.
For example the current version of Prettier leaves these unchanged ([Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzAlgJwM4wAQC8eAFADpR54A8AJugG4B85llAKnAB4xUBGmeAPTMKrALIRMcPPG58BwlqwCCUGngC2kuPKEjKVQXSbkAlAG5y5bHEhrCJJbQb7WHOfz0SpMrj0-CqupaUrqKoobGIhZWsAAWWOpEZBFRSux+6dQBrpTe0rIwWWG5eEGa2sU5Tk …

Handle JSX whitespace separately from fbt whitespace

---

docs/plugins.md
src/common/util-shared.js
tests_integration/__tests__/util-shared.js

Expose `isPreviousLineEmpty` to plugins (#4747)

---

src/language-markdown/printer-markdown.js
tests/markdown_link/__snapshots__/jsfmt.spec.js.snap
tests/markdown_link/autolink.md
tests/markdown_spec/__snapshots__/jsfmt.spec.js.snap

```diff
<hello@example.com>
<mailto:hello@example.com>
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-<mailto:hello@example.com>
+<hello@example.com>
<mailto:hello@example.com>
```

fix(markdown): preserve email autolink

---

website/data/users.yml

Jest got a new domain! Let's point to it.
See facebook/jest#6549.

Update Jest URL to jestjs.io

---

scripts/build/babel-plugins/transform-custom-require.js
src/common/internal-plugins.js

Regression in the build script left some `eval("require")` in the codebase.
I decided to remove the `$$$r` thing

Fix custom require's

---

yarn.lock

I had this lying in my tree when I looked at maybe upgrading Jest. So why not open up a PR with it 🙂 
This is `yarn-tools fix-duplicates` followed by `yarn`.
https://www.npmjs.com/package/yarn-tools

chore: dedupe dependencies in lockfile

---

website/data/languages.yml
website/package.json
website/pages/en/index.js
website/siteConfig.js
website/static/overrides.css
website/yarn.lock

Docusaurus 1.3.1 brings about some [backwards-incompatible CSS changes](https://github.com/facebook/Docusaurus/blob/master/CHANGELOG.md#breaking-changes). So the team is helping the major users update 😄 
The header font weights in Docusuaurs have been changed. I left them alone in this PR but will be glad to help Prettier change it such that it looks better (according to my limited artistic skills). Let me know if you want that!
cc @JoelMarcey @endiliey
Ran the site locally and visited every page. The playground doesn't seem to be working locally though.

Upgrade Docusaurus to 1.3.1

---

src/common/util.js
src/doc/doc-printer.js

Total run time for 1000 repetitions for `LspLanguageService.js` is **182276ms**, average run is **181.80ms**.
```
$ cat LspLanguageService.js | NODE_ENV=production node --inspect-brk ./bin/prettier.js --stdin-filepath LspLanguageService.js --loglevel debug --debug-repeat 1000 > /dev/null
Debugger listening on ws://127.0.0.1:9229/d085f49d-a12c-432e-ad7e-acf322152bd3
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
[debug] normalized argv: {"color":true,"editorconfig":true,"stdin-filepath":"LspLanguageService.js","loglevel":"debug","debug-repeat":"1000","plugin-search-dir":[],"plugin":[],"ignore-path":".prettierignore","config-precedence":"cli-override","_":[]}
[debug] resolve config from '/Users/ivanbabak/_sompylasar/_github/prettier/LspLanguageService.js'
[debug] …
```

fix(perf): shortcut getStringWidth for ASCII-only strings (#4776)

---

package.json
src/cli/constant.js
src/cli/util.js
yarn.lock

- `--debug-benchmark` uses `benchmark` module to produce statistically significant time measurements.
- `--debug-repeat` uses a naive loop and measures just the average run time, but useful for profiling to highlight hot functions.
Refs https://github.com/prettier/prettier/issues/4776

feat(benchmark): add options to measure performance (#4776)

---

src/cli/util.js

`benchmark` would either get bundled in the production build or unable to be required, this PR prevents both from happening.
cc @sompylasar

Fix benchmark require

---

docs/precommit.md

The current docs are not compatible with the latest husky API, which changed with the version bump from 0.1.x to 1.x.x.
This updates the docs to provide valid examples with husky version 1.x.x.

Update precommit docs to be compatible with latest husky version

---

.github/lock.yml

Mostly to avoid random notifications from people "me too"ing on stuff that no one has touched in ages.

Lock closed issues and PRs after 3 months of inactivity

---

docs/precommit.md

Tried to install prettier with current installation description here: https://prettier.io/docs/en/precommit.html
Unfortunately `husky` was not updated on npm yet, so you need to install the pre-release version which is more or less fine I guess. Still should be added to the instructions there.

Fix example of husky pre-commit hook to include next version tag

---

src/language-js/printer-estree.js
tests/functional_composition/__snapshots__/jsfmt.spec.js.snap
tests/functional_composition/functional_compose.js

As filtering out `this` and `super` cases in #4758 didn't seem to get any objections, here's that part as a separate PR:
Do not react when `MemberExpression` object type is `ThisExpression` or `Super`
Filters out cases like 
```js
this.compose(a(), b);
super.compose(a(), b);
```
cc @suchipi

Blacklist this in functional composition heuristics

---

docs/related-projects.md

Tweak order of stylelint integrations to match ordering of eslint/tslint and update url of stylelint-config-prettier

Add stylelint-prettier to related projects

---

src/language-yaml/parser-yaml.js
tests_integration/__tests__/__snapshots__/format.js.snap
tests_integration/__tests__/format.js

Context: https://github.com/prettier/prettier/issues/4856#issuecomment-405982539
Workaround for eemeli/yaml#20

fix(yaml): no wrong loc info for CRLF

---

src/language-handlebars/printer-glimmer.js
tests/html_glimmer/__snapshots__/jsfmt.spec.js.snap
tests/html_glimmer/block-statement.hbs

fix(glimmer): do not strip block params on <Component>

---

src/language-handlebars/printer-glimmer.js
tests/html_glimmer/__snapshots__/jsfmt.spec.js.snap
tests/html_glimmer/sub-expressions.hbs

*before*
```handlebars
{{foo (bar )}}
```
*after*
```handlebars
{{foo (bar)}}
```

fix(glimmer): remove extra space from sub-expressions without params

---

src/language-handlebars/printer-glimmer.js
tests/html_glimmer/__snapshots__/jsfmt.spec.js.snap
tests/html_glimmer/block-statement.hbs

*input*
```handlebars
{{#block}}
{{#block param}}
hello
{{/block}}
{{/block}}
```
*before*
```handlebars
{{#block}}
{{#block param}}
hello
{{/block}}{{/block}}
```
*after*
```handlebars
{{#block}}
{{#block param}}
hello
{{/block}}
{{/block}}
```

fix(glimmer): add softline in nested block statements

---

src/language-handlebars/printer-glimmer.js
tests/html_glimmer/__snapshots__/jsfmt.spec.js.snap
tests/html_glimmer/component.hbs

I hope this is not controversial...
*input*
```handlebars
<button disabled>Click</button>
<button disabled=disabled>Click</button>
<button ...attributes>Click</button>
```
*before*
```handlebars
<button disabled="">Click</button>
<button disabled="disabled">Click</button>
<button ...attributes="">Click</button>
```
*after*
```handlebars
<button disabled>Click</button>
<button disabled="disabled">Click</button>
<button ...attributes>Click</button>
```

fix(glimmer): better formatting of boolean attributes

---

package.json
tests/jsx_spread/jsfmt.spec.js
yarn.lock

fix(typescript): support jsx spread child

---

src/language-handlebars/printer-glimmer.js
tests/html_glimmer/__snapshots__/jsfmt.spec.js.snap
tests/html_glimmer/component.hbs

This alignes with [Angle Bracket Invocation RFC](https://github.com/emberjs/rfcs/blob/master/text/0311-angle-bracket-invocation.md)
*input*
```handlebars
<Button @title="hello" />
<Label>hello</Label>
<this.button @title="hello" />
```
*before*
```handlebars
<Button @title="hello"></Button>
<Label>hello</Label>
<this.button @title="hello"></this.button>
```
*after*
```handlebars
<Button @title="hello" />
<Label>hello</Label>
<this.button @title="hello" />
```

fix(glimmer): treat glimmer components as self closing tags

---

src/cli/util.js
tests_integration/__tests__/__snapshots__/ignore-vcs-files.js.snap
tests_integration/__tests__/__snapshots__/multiple-patterns.js.snap
tests_integration/__tests__/ignore-vcs-files.js
tests_integration/cli/ignore-vcs-files/.hg/file.js
tests_integration/cli/ignore-vcs-files/.svn/file.js
tests_integration/cli/ignore-vcs-files/file.js

Don't really see a compelling case for a CLI argument for this.
Fixes #4895
> Note: Can't actually add a `.git` test because git ignores the files 😉

Ignore .git, .svn and .hg directories

---

src/language-yaml/printer-yaml.js
tests/yaml_flow_mapping/__snapshots__/jsfmt.spec.js.snap
tests/yaml_flow_sequence/__snapshots__/jsfmt.spec.js.snap
tests/yaml_mapping/__snapshots__/jsfmt.spec.js.snap
tests/yaml_plain/__snapshots__/jsfmt.spec.js.snap
tests/yaml_plain/force-singleline-in-mapping-value.yml

Fixes #4913
Only apply to `alias` and `plain`/`quoteSingle`/`quoteDouble` with
- no backslash newline
- or no literal newline and `proseWrap: preserve`
- or no newline and `proseWrap: never`
- or no whitespace and `proseWrap: always`
in mapping items with implicit key, otherwise it's impossible to do prose wrapping.

feat(yaml): do not put singleline values on a separate line from the key

---

src/language-js/printer-estree.js
tests/assignment/__snapshots__/jsfmt.spec.js.snap
tests/assignment/destructuring.js
tests/assignment_comments/__snapshots__/jsfmt.spec.js.snap

If you have
```js
a = b
```
we used to do
```js
group[a = b]
```
which works most of the time but has the unfortunate side effect that if the left part breaks, we're going to break the `=` as well. So you get
```js
{
a
} = \n
b
```
What this PR does it to add a group
```js
group[a group[= b]]
```
so that if the right hand side fits in one line, it should stay that way.
Note that there's a change with a comment being move but I think that it's fine. If I remember correctly, this test was to make sure that we didn't print invalid code, not that it had to be respected (that comment position is not something we really want to support in the first place).
Fixes #4645

[assignment] proper group

---

src/language-js/printer-estree.js
tests/functional_composition/__snapshots__/jsfmt.spec.js.snap
tests/functional_composition/functional_compose.js

Revert this/super blacklist for function composition heuristic

---

scripts/release/README.md
scripts/release/release.js
scripts/release/steps/bump-prettier.js
scripts/release/steps/publish-to-npm.js
scripts/release/steps/update-changelog.js
scripts/release/steps/update-version.js
scripts/test-dist.js

Fixes #4905 
- use the latest git tag as the previous version
- restore/bump the version on master in `bump-prettier.js`
- use `stdio: "inherit"` for `npm publish` so that we could input the OTP
- do not use `--runInBand` for local `test:dist`
- remove `Updating integration snapshots`
- remove `Attach all files in dist/ folder`

chore: improve release scripts

---

src/main/core.js
tests_integration/__tests__/__snapshots__/format.js.snap
tests_integration/__tests__/format.js

Fixes #4956 
I originally thought it worked this way, but apparently not.
cc @kachkaev

fix: guess line ending before preprocess

---

src/language-js/printer-estree.js
tests/bind_expressions/__snapshots__/jsfmt.spec.js.snap

remove redundant ASI protection for BindExpression

---

.github/lock.yml

This allows us to track 👍s on closed issues so we can perhaps reopen them if there’s strong enough support. (inspired by & closes #4986)

Add a label that exempts issues from auto-locking

---

docs/configuration.md

So in the list, it says to use `prettier.config.js` as your file name for configuring prettier in js. But in the example it has `//.prettierrc.js`. This confused me so I tried both file names. Both these file names work to configure prettier so I updated the docs to reflect that.

Update configuration to be clearer about js config

---

src/language-js/comments.js
tests/import/__snapshots__/jsfmt.spec.js.snap
tests/import/comments.js

Fixes #4847 by making sure that the `precedingNode` is of type `ImportSpecifier`. 
In the example mentioned in the original issue, where the comment should not be moved outside the block, `precedingNode.type` is `ImportDefaultSpecifier`.

verify the precedingNode type when handling import declaration comments

---

src/language-js/printer-estree.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/binary-expressions.js
tests/comments_pipeline_own_line/__snapshots__/jsfmt.spec.js.snap
tests/comments_pipeline_own_line/jsfmt.spec.js
tests/comments_pipeline_own_line/pipeline_own_line.js

Resolves #5009 .
The pipeline operator now doesn't get inlined with an leading ownLineComment, but is instead treated as any other binary expression. Thus, the pipeline operator gets moven above the ownLineComment.
I also added tests for all other binary expressions as well as a separate test for the pipeline operator binary expression as this can only be run with babylon.

Bugfix/ Don't inline pipeline operator with leading ownline comment

---

src/language-js/printer-estree.js
tests/jsx-significant-space/__snapshots__/jsfmt.spec.js.snap
tests/jsx-text-wrap/__snapshots__/jsfmt.spec.js.snap
tests/jsx-text-wrap/test.js

fix: splitting jsx text correctly

---

src/language-js/printer-estree.js
tests/test_declarations/__snapshots__/jsfmt.spec.js.snap
tests/test_declarations/angular_async.js

Format {before,after}{Each,All} calls like regular function calls

---

src/cli/constant.js
src/cli/util.js
src/main/options-normalizer.js
tests_integration/__tests__/__snapshots__/early-exit.js.snap
tests_integration/__tests__/early-exit.js

Option-related processing should be done in `options-normalizer`.
- unknown flag suggestions are colored
- unknown flags with no suggestion are now errors:
```
$ bin/prettier.js --help noseminosemi
[error] Invalid `--help` value. Expected `a flag`, but received `"noseminosemi"`.
```
---

refactor: move cli leven suggestion to options-normalizer

---

src/language-js/printer-estree.js
tests/jsx/__snapshots__/jsfmt.spec.js.snap
tests/jsx/open-break.js

Closes #5075
The bug happens because single line template literals don't break and we inline template literals if they're the only children of a JSX tag because of #1090. The simplest fix is to prevent simple `<Tag>` from breaking.

Keep simple JSXOpeningTag's unbroken

---

src/language-js/printer-estree.js
tests/no-semi-typescript/__snapshots__/jsfmt.spec.js.snap
tests/no-semi-typescript/jsfmt.spec.js
tests/no-semi-typescript/no-semi.ts

Fixes #5082
---
**Prettier pr-5083**
[Playground link](https://deploy-preview-5083--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuc0DOMAEBrAQgVwDNC4AnTAXkwGUBPAWwCMIAbACgHJGiTSOBKADpRIUDDgDyxNHCxU6TVpwjTZA4cLAsAhmjSYASnG0ATMpmDDMmAA6kAlgDdt8TAG08PMgF0kmAsTmAPRBmAA8ALQRmAAWZHBWtg7Orh5ShDIwvphQ+ExkwgC+IAA0IBA2MPboyKDapKQQAO4ACvUIaMgg2o4Q9ialIIyk2mDYstQ2o-ZQAObIMKT4cGUzMqQwLSOz9NrIhNosMmUAVmgAHrgjYxPa9HAAMjNw+4fHIFOk610wtDZwaDADkqgzsMxgAHV+jAYsgABwABjKdggMghIxsXTsALIjheZVIcAAjvh7ISttodnskAcjisQDJ6PZXnSymgZrMWHAAIr4CDwFnvGDaRhQkww5AAJjKi209hYHIAwhB6LsulBoPiQPgZAAVEWdGlvOCFQpAA)
```sh
--no-semi
```
**Input:**
```tsx
const kBuffer = Symbol('buffer')
const kOffset = Symbol('offset')
class Reader {
private [kBuffer]: Buffer // <-- here
private [kOffset]: number
}
``` …

fix(typescript): no-semi for class props with modifiers

---

src/language-js/printer-estree.js
tests/test_declarations/__snapshots__/jsfmt.spec.js.snap
tests/test_declarations/test_declarations.js

Add support for timeouts passed as integers to test functions

---

src/language-js/needs-parens.js
tests/assignment/__snapshots__/jsfmt.spec.js.snap
tests/assignment/destructuring.js

Fixes #4813
---
**Prettier pr-5096**
[Playground link](https://deploy-preview-5096--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAbOMAEMIEEDO+AlgOZRKb4wBORUJA3ADpQAUwmADtRJxTgWJlMAXkxMQAEzgAzAIYBXVDAmYAvqMwduvChJ2cAbnNSq1ASgYgANCF4wi0fMlBzqPAO4AFNwmco5QwgiSRsQACNqOTAAawwAZU5ouhJkGgU4Wzp8OGoYLyiSAFs5ZHlUHNsAK3wADwAhKNiEuSK4ABk6ODKTSpAk6hzqZBAYAE9OOHwwWk4YMO46GAB1EJgAC2QADgAGWx0c5ajOEe4p3MNu22o4AEcFIhuCuWLSpHK+nKKiNOoM22I9HQAEUFBB4D0KplRnJwqtJBtkAAmWw0OREVApADCECKJRGUGgVxAChyABVYf4PnA1GogA)
```sh
```
**Input:**
```tsx
let toAssign: string;
({ prop: toAssign = "default" } = { prop: "propval" });
```
**Output:**
```tsx
let toAssign: string;
({ prop: toAssign = "default" } = { prop: "propval" });
```
---
- (If changing the API or CLI) I’ve documented the changes I’ve …

fix(typescript): no invalid parens for destructuring with default value

---

src/language-html/parser-parse5.js
tests/html_basics/__snapshots__/jsfmt.spec.js.snap
tests/html_basics/comment.html

Context: https://github.com/prettier/prettier/pull/4753#discussion_r200848784

fix(html): exclude comments from fragment detection

---

src/utils/front-matter.js
tests/css_yaml/__snapshots__/jsfmt.spec.js.snap
tests/css_yaml/ignore.css
tests/insert-pragma/css/__snapshots__/jsfmt.spec.js.snap
tests/require-pragma/css/__snapshots__/jsfmt.spec.js.snap

Replace front matter with whitespaces to maintain the loc info.

fix(css): no wrong loc info caused by front matter

---

src/language-html/parser-parse5.js
src/language-html/printer-htmlparser2.js
tests/html_tags/__snapshots__/jsfmt.spec.js.snap
tests/html_tags/case-sensitive.html

Attributes in non-HTML tags are considered case-sensitive.
---
**Prettier pr-5109**
[Playground link](https://deploy-preview-5109--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAeAwgQwM5wMoLYCWMRAbnAARa4FTGkUB8AFnADbsSUDuEATuwAmqAPQ18hEuThMAOlFQARctRxwAkvSmNZbTtz6CRolWSYgANCAgAHUtGzJQmfvwg8ACq8LIQmMggiISsQACN+TDAAazgYPFsooigAc2QYfgBXOGtk3H4YT0iUgFtMZAAzTHZcawArbAAPACFImLi8TBK4ABlkuErq2pBE-ny-UdwAVlDbfmSYAHVgmBZkAA4ABms5iFxFyNsJ-jh8ilCTgEdMohOizFLypCqanJBcEqJ0rLfiVPY4ABFTIQeCDV7WGCYMLLISrZAAJkhkSI7GSKXQEBKZT8UGgA2smVwABVoU5nkM4ABfKlAA)
```sh
--parser parse5
```
**Input:**
```html
<CaseSensitive CaseSensitive>hello world</CaseSensitive>
<Div CaseInsensitive>hello world</Div>
```
**Output:**
```html
<CaseSensitive CaseSensitive>hello world</CaseSensitive>
<div caseinsensitive>hello …
```

fix(html): preserve case-sensitive attributes

---

src/language-html/clean.js
src/language-html/embed.js
src/language-html/parser-parse5.js
src/language-html/printer-htmlparser2.js
tests/html_yaml/__snapshots__/jsfmt.spec.js.snap
tests/html_yaml/invalid.html
tests/html_yaml/jsfmt.spec.js
tests/html_yaml/yaml.html

- format yaml front matter
- preserve toml front matter
---
**Prettier pr-5110**
[Playground link](https://deploy-preview-5110--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEBadAdKALOAbPCJAAlLIHcIAnPAEy3VS1KwB5sYBbPAPnbgCGtPgHpcQvgCMItAJ6jpc0R248sIADQgIABxgBLaAGdkoAVSoRyABXMITKAQDcI+2ppCSqAsAGs4MADKOj76UADmyDBUAK5wWmFGcFQw1t7hnALIAGYCeElaAFZGAB4AQt5+AYECnHAAMmFwOXkFICFUSVTI7eZJAKweOlRhMADqbjDYyAAcAAxawxBJY946PcNwXU7NWlRwAI4x+vtpAhlZSLn58SBJnPpRsbdGYeF4cACKMRDwLTdaGACSQTWhTZAAJkB3n0eDeAGEIJxMj0oNBdiAYkkACrAhzXJIAX0JQA)
```sh
--parser parse5
```
**Input:**
```html
---
hello:      world
---
<html><head></head><body></body></html>
```
**Output:**
```html
---
hello: world
---
<html>
<head></head>
<body></body>
</html>
```
---
- (If changing the API or CLI) I’ve documented the changes I’ve …

feat(html): support front matter

---

src/language-html/embed.js
src/language-html/printer-htmlparser2.js
src/language-html/utils.js

- extract utilities
- use built-in hasPrettierIgnore
- simplify some functions
- remove dead code
---

refactor(html): simplify/extract code

---

src/doc/doc-utils.js
src/language-html/embed.js
tests/html_css/__snapshots__/jsfmt.spec.js.snap
tests/multiparser_html_css/__snapshots__/jsfmt.spec.js.snap

The issue here is that the `stripTrailingHardline` does not work for js/ts, I fixed it and then I realized that we always print trailing newline in every language, so there's no need to strip newline for text in script-like tag.
---
**Prettier pr-5111**
[Playground link](https://deploy-preview-5111--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAeAzjAngGzgPgB0oACEgOgDMIITgBfY1Aek1wJABoQIAHGAJbR0yUAEMAThIgB3AAqSEIlGIBuEAQBMuIAEYSxYANZwYAZV6GBUAObIYEgK5xu19HAkw5BmwFsxyJRiOO7cAFboAB4AQgbGpmZivnAAMtZwgcGhIJYS7hLIOZLuAKw6vBLWMADqWjAAFsgAHAAM3BUQ7tUGvIUVcPmqGdwScACOjgKj3mJ+AUhBIS4g7r4C9k7L6NY2eACKjhDwmUvcMGK6tZoNyABMZwYCODsAwhC+-oVQ0MMgju4AFQuykW7no9CAA)
```sh
--parser parse5
```
**Input:**
```html
<style>
.foo {}
</style>
```
**Output:**
```html
<style>
.foo {
}
</style>
```
---
- I’ve …

fix(html): no need to strip newline for text in script-like tag

---

docs/precommit.md

Husky 1.0 was released and isn't behind a `@next` tag anymore :)

docs: remove next tag for husky

---

package.json
src/language-html/parser-html.js
src/language-html/utils.js
tests/html_attributes/__snapshots__/jsfmt.spec.js.snap
tests/html_attributes/case-sensitive.html
yarn.lock

fix(html): non-HTML attributes are considered case-sensitive

---

src/language-js/printer-estree.js
tests/first_argument_expansion/__snapshots__/jsfmt.spec.js.snap
tests/first_argument_expansion/test.js

Fixes: #5046 
To prevent ugly output when the first argument is a `[Function|ArrowFunction]Expression` and the second is a `ConditionalExpression`, arguments are broken.

fix(js) Break args when second arg is a ternary (#5046)

---

src/language-js/printer-estree.js
tests/quotes/__snapshots__/jsfmt.spec.js.snap
tests/quotes/objects.js

Currently, Prettier quotes property names if the name isn't es6 compatible.
It means that Prettier might strip the quote for a property name that is es6 compatible but is not es5 compatible.
So this might break scripts on ES5 environments.
For example, the following example doesn't work on some ES5 environments.
You can try the script on Node v0.12.
**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA3AhgJwAQQEYBW2AvNsADpTbkiAAG4OV7NS2A5BANYuUC+A3JZUhQAzhAA2cAHRiIAcwAU+AgEp+UEABoQEAA4wAltGHJQWTBADuABSwJjKdKgj6AJppB5M6MOzgwAyjre+lCyyDCYAK5wWiHCcJgwVl6yALboyABm6GLxWgTCAB4AQl4+fv7oqXAAMiFwWTl5IEGY8ZjIHuh4AJ4y6lo6mCEwAOquMAAWyAAcAAyD5vGjXjqdQ3DtqA1amHAAjpH6e8noaRlI2bkxIPGp+uFRN8IhshIAipEQ8I3XWjDdcYuKbIABM-y8+jErwAwhBUulOlBoDsQJF4gAVbr2K7xbjcIA)
```sh …
```

fix(js): quote property name as es5 compatible

---

docs/editors.md
docs/vim.md

Update "Running Prettier manually in Vim" docs
- Add `--stdin-filepath` for parser inference.
- Reword "if you need a little more control" since it can be argued that
this approach gives you _less_ control than the plugins.
- Add note about error messages.
- Add note about cursor position.
Clean up vim.md
- Replace the out-of-date vim-prettier information with a link to its
readme. Move vim-prettier to the top as compensation for its reduced
part of the page.
- Remove out-of-date instructions.
- Try to provide roughly the same information about Neoformat and ALE.
- Simplify language and formatting.

Update vim docs

---

src/language-js/printer-estree.js
tests/typescript_interface/__snapshots__/jsfmt.spec.js.snap
tests/typescript_interface/ignore.js

Fixes: #5140 
Separator paths are shifted for `TSMethodSignature`s when `prettier-ignore` is used, just as `TSPropertySignature`s.

fix(typescript) Do not add extra semicolon to `TSMethodSignature` when `prettier-ignore` is used (#5140)

---

src/language-html/embed.js
tests/html_js/__snapshots__/jsfmt.spec.js.snap
tests/html_js/js.html

support script type of text/babel in language-html

---

commands.md
src/doc/doc-builders.js
src/doc/doc-debug.js
src/doc/doc-printer.js
tests_integration/__tests__/doc-mark-as-root.js
tests_integration/__tests__/doc-trim.js

I reused and factorized the pre-existing code to trim trailing spaces.
Note that this adds no test, and I'm not really confident about that. How would you test this change? I couldn't find any test that explicitly used `hardline` for instance.
Fixes #4771

Add a new `trim` command to trim whitespaces in the current line (#4771).

---

src/language-js/printer-estree.js
tests/decorators-ts/__snapshots__/jsfmt.spec.js.snap
tests/decorators-ts/angular.ts
tests/decorators/__snapshots__/jsfmt.spec.js.snap
tests/decorators/classes.js
tests/decorators/methods.js
tests/decorators/multiline.js
tests/decorators/multiple.js
tests/typescript_decorators/__snapshots__/jsfmt.spec.js.snap

Implements @lydell's suggestions: https://github.com/prettier/prettier/issues/4924#issuecomment-425659254
Closes #4924
Closes #5088
What this PR does is select the separator for each decorator by checking:
- is there a new line between the start of the first decorator and the start of the last decorator
- is there a new line right after the end of the last decorator
If either of those are true, we should use a `hardline` separator, otherwise it's a `line`. If they are separated with `line` they will be the in the same line, unless they don't fit, then they'll break; `hardline` will force a break.
"Breaking", in this case, means each decorator is printed in a separate line and the thing they decorate too.
I'll navigate to the threads now to see if I can't find any case not covered in our …

Keep decorators inline if they were written inline

---

src/language-js/printer-estree.js
tests/arrow-call/__snapshots__/jsfmt.spec.js.snap
tests/arrow-call/arrow_call.js
tests/arrow-call/jsfmt.spec.js
tests/ternaries/__snapshots__/jsfmt.spec.js.snap

Inline the arguments of an arrow function in the body is conditional expression

---

src/language-markdown/printer-markdown.js
tests/markdown_math/__snapshots__/jsfmt.spec.js.snap

fix(markdown): preserve inline math style

---

src/language-js/comments.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/try.js

Fixes #5192 - comment ordering within try / catch / finally blocks

Fix comment issue with try finally

---

src/language-js/printer-estree.js
tests/typescript_conditional_types/__snapshots__/jsfmt.spec.js.snap

Break nested TSConditionalType

---

.pre-commit-hooks.yaml

The pre-commit hook registers for HTML files but that will always fail until #5098 is completed. This means that anyone following [the instructions](https://prettier.io/docs/en/precommit.html#option-3-pre-commit-https-githubcom-pre-commit-pre-commit) will have the hook fail any time they attempt to commit an HTML file.

Remove HTML from pre-commit hooks until available

---

src/language-js/loc.js
src/language-js/parser-babylon.js
src/language-js/printer-estree.js
tests/decorators_export/__snapshots__/jsfmt.spec.js.snap
tests/decorators_export/after_export.js
tests/decorators_export/before_export.js
tests/decorators_export/jsfmt.spec.js

Closes #5045
Closes #4795
Supersedes #2630
Hopefully this will enable to continue using Prettier without too much problems until the spec is standardized

Respect original text decorator order

---

website/pages/en/index.js

Latest husky (version 1.0.0) moved its hooks config from the `scripts` field to a new `husky` field in `package.json` ([ChangeLog](https://github.com/typicode/husky/blob/master/CHANGELOG.md)).
The `scripts` syntax described here, although shorter, will be deprecated soon. This change replaces it with the new husky syntax.
The new syntax is already used in [precommit.md](https://github.com/prettier/prettier/blob/master/docs/precommit.md).

Update husky integration code for husky v1.0.0

---

src/language-js/flow-comments.js
src/language-js/needs-parens.js
src/language-js/printer-estree.js
src/language-js/utils.js
tests/flow_comments/__snapshots__/jsfmt.spec.js.snap
tests/flow_comments/type_annotations.js

This attempts to fix the bug described in #719. Previously, Prettier was removing parentheses in expressions like: 
```
new (window.Request /*: Class<Request> */)("")
```
turning them into:
```
new window.Request /*: Class<Request> */("")
```
which no longer satisfies Flow's syntax. With this change, we detect these typecast expressions and attempt to keep the parentheses intact in such cases.
This is my first time contributing to Prettier, so I'm probably making some egregious mistakes!

Add support for flow typecast comments

---

src/language-js/printer-estree.js
src/language-js/utils.js
tests/flow_comments/__snapshots__/jsfmt.spec.js.snap
tests/flow_comments/babylon_only/__snapshots__/jsfmt.spec.js.snap
tests/flow_comments/babylon_only/class_with_generics.js
tests/flow_comments/babylon_only/jsfmt.spec.js
tests/flow_comments/generics.js

This fixes a bug in Prettier where Flow generic comments get repositioned, breaking Flow's syntax. An example:
```
foo /*:: <bar> */ (baz);
```
Currently, Prettier will rewrite this ([source](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzCEAEB6AVEpTAHgCMBDAJwD5NdtMAKcgLwEoBuEAGhAgAcYAS2gBnZKEoUIAdwAKlBGJRkAbhEEATbiBIUyYANZwYAZT77BUAObIYFAK5welkXAoxZeqwFsyyVGQANq48AFYiAB4AQnqGxiZk3nAAMpZw-kEhIOYUrhTIOmQkAJ6B0Np8FJYwAOqaMAAWyAAcAAw8lRCuNXp8BZVweSrpPBRwAI72gmOeZD5+SAHBTiCu3oK2DisillaBcACK9hDwGcs8MEV1Go3IAEwXeoKBuwDCEN6+BVDQIyD2rgAKkUlEtXABfcFAA)) as:
```
foo(/*:: <bar> */ baz);
```
This PR attempts to fix this behavior. One issue that I ran into was dealing with the Flow parser's AST that it generates from the comment syntax. Code like this:
```
/*:: type Props = {
foo?: ?string,
bar: …
```

Fix Flow generic comment positioning

---

website/playground/Playground.js

After using the playground, it would be nice to have a single click action to copy the JSON config to place into the `.prettierrc` file.
Clicking `Copy JSON` will copy the current options to the clipboard. Here's an example:
```json
{
"arrowParens": "avoid",
"bracketSpacing": false,
"insertPragma": false,
"jsxBracketSameLine": false,
"parser": "babylon",
"printWidth": 80,
"proseWrap": "preserve",
"requirePragma": false,
"semi": false,
"singleQuote": true,
"tabWidth": 2,
"trailingComma": "es5",
"useTabs": false
}
```
Here's a video showing how it works:

User can copy JSON config from Playground

---

package.json
tests/es6modules/__snapshots__/jsfmt.spec.js.snap
yarn.lock

Fixes #5084
Update the flow parser to 0.84.0, which includes parser support for explicit inexact objects using `...`. See https://medium.com/flow-type/on-the-roadmap-exact-objects-by-default-16b72933c5cf for more info.
One test had to be re-recorded

Update flow parser to 0.84.0

---

package.json
yarn.lock

This resolves a deprecated warning when installing prettier.

build: update editorconfig to resolve a deprecated warning

---

docs/precommit.md

Since partially staged files are [now officially supported](https://medium.com/@okonetchnikov/announcing-lint-staged-with-support-for-partially-staged-files-abc24a40d3ff), this isn't up to date anymore.

docs: Remove the warning about partially staged files

---

website/README.md

Update readme with steps to setup and run locally. 
Removed note about the need to run two separate processes because `yarn start` was [updated to concurrently runs both processes](https://github.com/prettier/prettier/commit/ef932741ad263f50c0bb3b08a680f8d65ab7ee7e#diff-07f3a4647460e74f9514d8def137963a).
Fixes #5302

Website and Playground Setup and Run Instructions

---

.pre-commit-hooks.yaml

- Prettier support YAML but pre-commit hook was not checking those
files so added file extensions to hooks config.
- Used double-quoted flow scalar style to make the list of file
extensions easier to read. Backslash for regex needed escaping and
backslash each line to prevent YAML including spaces.
- Added alternative markdown file extensions.
- Formatted with prettier.

Add YAML file extensions to pre-commit hooks config

---

src/language-js/comments.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/function-declaration.js

Fixes #5241
Fixed the Issues with unstable comments between function declaration and block statements described in #5241 by adding a clause that checks if a comment is enclosed by a function declaration and followed by a block statement it will move the comment inside the block statement as the first line.
This is the same way comments are handled in if statements before a block statement.

Fixed unstable comment between function declaration and block statement

---

src/language-css/printer-postcss.js
src/language-css/utils.js
tests/multiparser_js_css/__snapshots__/jsfmt.spec.js.snap
tests/multiparser_js_css/styled-components.js
tests/template_literals/__snapshots__/jsfmt.spec.js.snap
tests/typescript_typeparams/__snapshots__/jsfmt.spec.js.snap

Fixes: #5147 
Keep newlines after CSS-in-JS quasi-literal substitutes.

fix(css-in-js) Keep newlines in CSS-in-JS Templates (Fixes: #5147)

---

src/language-js/printer-estree.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/single-star-jsdoc.js

Fixes #5323. Previously we added space after `/*` _on the first line
only,_ but the intent is to only fix the indentation of comments, not
changing their "contents". Besides, this was inconsistent with the
handling of every following line. Finally, it broke `/*!` comments which
some minifiers look for to know which (license) comments to keep.
People can use https://eslint.org/docs/rules/spaced-comment to enforce
when to start comments with spaces.
@j-f1 Does this feel like the right approach to you?

Never put spaces to the right of stars in indentable block comments

---

src/language-css/printer-postcss.js

Fixes #5315
The issue is that less parser somehow included CRs in `comment.raws.content`, but it was hidden by the wrong trailing space elimination previously, which was fixed by #5165.
We already have such tests but it's not reproducible in AppVeyor since they use LF ([`core.autocrlf=input`](https://stackoverflow.com/a/20653073)).

fix(less): remove CRs from inline comments

---

.github/PULL_REQUEST_TEMPLATE.md
website/pages/playground-redirect.html

This should allow the PR template to link to https://prettier.io/playground-redirect and have it redirect to the appropriate preview playground.

Add a preview playground redirect page

---

src/main/ast-to-doc.js

Rename genericPrint function to callPluginPrintFunction to avoid similar name to printGenerically
Add comments that explain the descent/recursion
Rename "addAlignmentSize" parameter to "alignmentSize" to make it sound less like a function
No functionality has been changed. Test still run. No changes to API or CLI.

Make ast-to-doc.js a little easier to understand

---

src/language-js/printer-estree.js
tests/jsx/__snapshots__/jsfmt.spec.js.snap
tests/jsx/expression.js

fix(javascript): no regression for jsx in arrow function in jsx

---

src/language-js/printer-estree.js
tests/jsx/__snapshots__/jsfmt.spec.js.snap
tests/jsx/quotes.js
website/playground/Playground.js

fix(jsx): consistent quotes in JSX expression

---

src/language-css/parser-postcss.js
src/language-css/printer-postcss.js
tests/multiparser_js_css/__snapshots__/jsfmt.spec.js.snap
tests/multiparser_js_css/styled-components.js

Fixes #5344
Not sure if this is the correct fix but at least it works.

fix(css-in-js): do not remove semicolon

---

src/language-js/printer-estree.js
tests/jsx-text-wrap/__snapshots__/jsfmt.spec.js.snap
tests/jsx-text-wrap/test.js

Fixes #5336
Though I'm not sure why we should special-case self-closing tags, the changes look OK to me.

fix(jsx): do not move trailing char to the next line as leading char

---

src/language-js/embed.js
tests/multiparser_js_html/__snapshots__/jsfmt.spec.js.snap
tests/multiparser_js_html/lit-html.js

This one should be the final fix in 1.15.

fix(html-in-js): do not break empty content

---

docs/option-philosophy.md
docs/rationale.md

To be merged when 1.15 has been released and we've updated our own Prettier version.

Update rationale for the 1.15 changes

---

src/language-js/printer-estree.js
tests/decorators/__snapshots__/jsfmt.spec.js.snap
tests/decorators/mobx.js

Fixes the `@action` part in #5360

fix(javascript): inline property decorator should stay inline

---

src/language-js/printer-estree.js
tests/test_declarations/__snapshots__/jsfmt.spec.js.snap
tests/test_declarations/angular_fakeAsync.js
tests/test_declarations/test_declarations.js

fix(javascript): do not apply test call formatting to arrow without body

---

package.json
tests/html_angular/__snapshots__/jsfmt.spec.js.snap
tests/html_angular/attributes.component.html
yarn.lock

Fixes #5367
See ikatyang/angular-estree-parser#22.

fix(angular): handle parens in ng expression correctly

---

src/language-css/printer-postcss.js
tests/css_scss/__snapshots__/jsfmt.spec.js.snap
tests/css_scss/scss.scss

fix(scss): do not throw if node.source undefined

---

src/language-html/utils.js
tests/html_attributes/__snapshots__/jsfmt.spec.js.snap
tests/html_vue/__snapshots__/jsfmt.spec.js.snap
tests/html_vue/self_closing.vue

Fixes #5385
Custom element: keep it on its own line if both leading/trailing line breaks exist

feat(html): treat capital element as custom element

---

src/language-js/needs-parens.js
tests/angular_interpolation/__snapshots__/jsfmt.spec.js.snap
tests/angular_interpolation/pipe-expression.ng

fix(angular): add missing parens for pipe in ternary

---

src/language-html/parser-html.js
src/language-html/printer-html.js
tests_integration/__tests__/__snapshots__/format.js.snap
tests_integration/__tests__/format.js

fix(html): treat CRLF as LF

---

src/language-html/printer-html.js
src/language-html/utils.js
tests/html_vue/__snapshots__/jsfmt.spec.js.snap
tests/html_vue/template-lang.vue

fix(html): preserve content for `<template>` with unknown lang

---

src/main/options-normalizer.js
tests_integration/__tests__/__snapshots__/arg-parsing.js.snap
tests_integration/__tests__/arg-parsing.js

feat(cli): allow overriding

---

package.json
tests/html_angular/__snapshots__/jsfmt.spec.js.snap
tests/html_angular/attributes.component.html
yarn.lock

Fixes #5404
Ref: ikatyang/angular-estree-parser#23

fix(angular): correctly print unary expression with `+`

---

src/language-js/printer-estree.js
tests/functional_composition/__snapshots__/jsfmt.spec.js.snap
tests/functional_composition/reselect_createselector.js

This fixes #5285; initially I thought this was a feature but after seeing that #4431 already added special handling for similar function composition functions, including one from redux, I think adding support for [reselect's `createSelector`](https://github.com/reduxjs/reselect) could be considered a fix (especially since it's an official library in the same github org as redux)

Handle reselect's createSelector as function composition

---

src/language-css/printer-postcss.js
tests/multiparser_js_css/__snapshots__/jsfmt.spec.js.snap
tests/multiparser_js_css/styled-components.js

Fixes #5381
The original behavior was introduced by #5240. Since the original intent is to keep line breaks so I guess we can simply preserve at most 2 line breaks (next empty line)?

fix(css-in-js): do not duplicate comments

---

src/language-html/parser-html.js
src/language-html/utils.js
tests/html_comments/__snapshots__/jsfmt.spec.js.snap
tests/html_comments/conditional.html

fix(html): preserve incomplete ie conditional comment

---

src/common/util.js
src/language-js/comments.js
tests/flow_comments/babylon_only/__snapshots__/jsfmt.spec.js.snap
tests/flow_comments/babylon_only/functions.js

fix(javascript): do not attach to block if it's not behind right func paren

---

src/language-js/printer-estree.js
tests/flow/declare_export/__snapshots__/jsfmt.spec.js.snap
tests/flow/export_type/__snapshots__/jsfmt.spec.js.snap
tests/flow/implements/__snapshots__/jsfmt.spec.js.snap
tests/flow/interface/__snapshots__/jsfmt.spec.js.snap
tests/flow/new_spread/__snapshots__/jsfmt.spec.js.snap
tests/flow/poly_overload/decls/__snapshots__/jsfmt.spec.js.snap
tests/flow/this_type/__snapshots__/jsfmt.spec.js.snap
tests/flow_function_parentheses/__snapshots__/jsfmt.spec.js.snap
tests/flow_generic/__snapshots__/jsfmt.spec.js.snap
tests/flow_internal_slot/__snapshots__/jsfmt.spec.js.snap
tests/flow_method/__snapshots__/jsfmt.spec.js.snap
tests/flow_proto_props/__snapshots__/jsfmt.spec.js.snap
tests/interface/__snapshots__/jsfmt.spec.js.snap
tests/interface/break.js
tests/interface/jsfmt.spec.js
tests/typescript_keywords/__snapshots__/jsfmt.spec.js.snap

Fixes #5431
+ force-break Flow interfaces to be consistent with TS interfaces
+ do not indent interface `extends` if there's only one extend member
+ correctly distinguish `module` and `namespace` for `TSModuleDeclaration`
(`module X {}` was printed as `namespace X {}`)

fix(flow,ts): consistent interface and remove unnecessary indent for extends

---

docs/vim.md

Docs on how to configure Prettier with ALE didn't work out of the box for me, since multiple linters with conflicting configurations were run. This PR invite users to explicitly disable default linters.
Fix #5447

Add more information on how to configure ALE

---

src/language-js/printer-estree.js
tests/decorators-ts/__snapshots__/jsfmt.spec.js.snap
tests/decorators-ts/mobx.ts

fix(typescript): inline method decorators should stay inlined

---

src/language-js/printer-estree.js
tests/typescript_interface/__snapshots__/jsfmt.spec.js.snap
tests/typescript_interface/ignore.js

fix(typescript): do not add invalid semi for construct in interface with prettier-ignore

---

src/language-html/preprocess.js
src/language-html/printer-html.js
src/language-html/utils.js
tests/html_angular/__snapshots__/jsfmt.spec.js.snap
tests/html_angular/first-lf.component.html
tests/html_tags/__snapshots__/jsfmt.spec.js.snap

fix(html): leading space for leading interpolation in textarea is sensitive

---

src/language-html/parser-html.js
tests/html_angular/__snapshots__/jsfmt.spec.js.snap
tests/html_angular/tag-name.component.html
tests/html_vue/__snapshots__/jsfmt.spec.js.snap
tests/html_vue/tag-name.vue

fix(vue,ng): do not normalize tag names

---

src/language-html/printer-html.js
tests/html_js/__snapshots__/jsfmt.spec.js.snap
tests/html_js/template-literal.html

fix(html): do not add extra indent for js template in script

---

src/cli/util.js
tests_integration/__tests__/infer-parser.js
tests_integration/__tests__/piped-output.js

closes #4144 
let me know if i missed anything! 💖 

ensure --list-different + --write reports status code 0

---

package.json
tests/template/__snapshots__/jsfmt.spec.js.snap
tests/template/inline.js
tests/template/jsfmt.spec.js
yarn.lock

fix(javascript): upgrade @babel/parser to 7.1.6

---

src/language-js/needs-parens.js
tests/optional_chaining/__snapshots__/jsfmt.spec.js.snap
tests/optional_chaining/chaining.js

fix(javascript): add missing parens for binary in optionalMember

---

src/language-html/printer-html.js
src/language-js/embed.js
tests/multiparser_js_html/__snapshots__/jsfmt.spec.js.snap
tests/multiparser_js_html/lit-html.js

fix(html-in-js): do not add quotes for interpolation-only attributes

---

src/language-js/printer-estree.js
tests/html_angular/__snapshots__/jsfmt.spec.js.snap
tests/html_angular/attributes.component.html

feat(angular): do not print colon for ngIf

---

src/language-html/parser-html.js
tests/html_angular/__snapshots__/jsfmt.spec.js.snap
tests/html_angular/attr-name.component.html

Fixes #5547 
I don't know if this happens to vue as well but I also disabled it for vue since it does not look like a good idea to apply normalization for these template languages.

fix(ng,vue): do not normalize attribute names

---

package.json
tests_integration/__tests__/config-resolution.js
tests_integration/cli/config/editorconfig/.editorconfig
yarn.lock

fix: update editorconfig-to-prettier

---

src/language-html/parser-html.js

Found in #5552
- before
```html
[error] test.html: SyntaxError: Unexpected character "/" (1:26)
[error] > 1 | <div>footer content here<//>
[error]     |                          ^
```
- after
```html
[error] test.html: SyntaxError: Unexpected character "/" (1:27)
[error] > 1 | <div>footer content here<//>
[error]     |                           ^
```
---

fix(html): correct column for error code frame

---

.azure-pipelines/lint-dist.yml
azure-pipelines.yml
package.json
scripts/build/build.js
scripts/build/rollup-plugins/evaluate.js

chore(build): es5 compatibility for browser

---

src/language-js/printer-estree.js
tests/flow_union/__snapshots__/jsfmt.spec.js.snap
tests/flow_union/comment.js

We're running into this issue at Facebook because `// flowfixme` ignores the very next line, but in this case an empty line is added in-between which breaks the fixme.
Ideally the solution is to avoid adding a newline and we'd call it a day. Unfortunately it is tricky to implement in this particular case. The comment is already printed, including its \n. Yet, we want to indent the block and the only way to convince the doc printer to do so is to add an indent group --before-- the \n is printed, otherwise it's just going to indent on the next \n.
So this PR changes the output from one bad way to another, but the new way has the benefit of not breaking flow for Facebook, which makes our internal teams happier.
Note that the way we print the same construct with `&` is broken in the same way …

Improve union types with leading comments

---

src/common/get-file-info.js
tests_integration/__tests__/file-info.js

fix(api): normalize file path for `getFileInfo`

---

.travis.yml

They’re currently segfaulting so we ignore them. Therefore there’s no point in even running this job until #3457 is fixed since there isn’t a way for it to signal that something has gone wrong on Node 6 other than the segfault.

Don’t run tests on Node 6

---

docs/rationale.md

A sentence that did not read well. Fixed it with the smallest amount of new words I could think of.

Fix incorrect grammar

---

src/main/ast-to-doc.js
tests/range/__snapshots__/jsfmt.spec.js.snap
tests/range/large-dict.js

This change avoids collapsing an already-formatted range into a single
overlong line when --range-start is provided and the range starts on a
line that has a non-zero amount of leading whitespace.
Fixes: #4923

Fix formatting with --range-start

---

src/language-js/comments.js
src/language-js/embed.js
tests/multiparser_js_html/__snapshots__/jsfmt.spec.js.snap
tests/multiparser_js_html/jsfmt.spec.js

fix(flow,ts): format `/* HTML */` templates

---

website/static/worker.js

fix(playground): backward compatibility for --parser babylon

---

website/versioned_docs/version-stable/webstorm.md

This is where I found File Watchers (File -> Settings). Couldn't find Preferences anywhere. Working with Windows 10. WS 2018.3
- [] I’ve added tests to confirm my change works.

Update Webstorm integration docs

---

website/package.json
website/yarn.lock

Context: https://nvd.nist.gov/vuln/detail/CVE-2018-6341 (Though we're not affected.)

chore(website): upgrade react-dom to 16.3.3

---

src/language-js/needs-parens.js
tests/typescript/conformance/types/functions/TSFunctionTypeNoUnnecessaryParentheses.ts
tests/typescript/conformance/types/functions/__snapshots__/jsfmt.spec.js.snap

Fixes  #5247. I added a test, not sure I put it in the right folder though.

typescript: remove unneeded parentheses around type annotation

---

docs/precommit.md

I played around with the pre-commit hook script a bit and found out that it doesn't work correctly with files with unusual characters in the file name like spaces or line breaks.
I created the following files and added them to the index via `git add`.
```bash
$ touch 'file
with
newlines.js'
$ touch 'file with spaces.js'
$ touch 'just_a_file.js'
```
Then I executed these commands from the script manually. Instead of `prettier` `ls` was used.
```bash
$ jsfiles=$(git diff --cached --name-only --diff-filter=ACM "*.js" "*.jsx" | tr '\n' ' ')
$ echo "$jsfiles" | xargs ls
ls: cannot access 'file': No such file or directory
ls: cannot access 'with': No such file or directory
ls: cannot access 'spaces.js': No such file or directory
ls: cannot access 'file\357\200\212with\357\200\212newlines.js': …
```

Fix pre-commit hook script

---

docs/api.md
docs/cli.md
docs/options.md
docs/plugins.md
website/versioned_docs/version-stable/api.md
website/versioned_docs/version-stable/cli.md
website/versioned_docs/version-stable/options.md
website/versioned_docs/version-stable/plugins.md

Removed the redundant relative paths to fix broken links on build. This was done with the following command:
```sh
sed -i "s#(\./#(#" docs/*.md website/versioned_docs/version-stable/*.md
```
This commit also removed the following warnings thrown by the `yarn run build-docs` script:
```
[WARN] unresolved links in file 'version-stable/cli.md' > [ './api.md' ]
[WARN] unresolved links in file 'version-stable/options.md' > [ './precommit.md' ]
[WARN] unresolved links in file 'version-stable/api.md' > [ './plugins.md' ]
[WARN] unresolved links in file 'version-stable/cli.md' > [ './api.md' ]
```
Maybe a `build-docs` job should be added to the CI to catch these warnings in the future?
~~**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**~~

docs: remove redundant "./" from relative links (#5740)

---

src/language-js/printer-estree.js
tests/functional_composition/__snapshots__/jsfmt.spec.js.snap
tests/functional_composition/gobject_connect.js
tests/functional_composition/mongo_connect.js

Fixes #4935. Checks a member expression property against an ordinary method name blacklist, after the property has found a match in the existing set of function composer names.

fix(javascript): skip .connect() method when composing fun

---

scripts/build-docs.js

Fixes #5742. Instead of relying on the Linux style `cp` command, this commits takes advantage of the multi-platform [`shelljs.cp`](http://documentup.com/shelljs/shelljs#cpoptions-source--source--dest) command. 
This also fixes building from a path containing spaces, as `__dirname` was not previously escaped.
~~**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**~~

docs: fix Windows build (#5742)

---

src/language-js/embed.js
tests/multiparser_js_html/__snapshots__/jsfmt.spec.js.snap
tests/multiparser_js_html/lit-html.js

fix(javascript): remove unnecessary linebreaks from html templates

---

src/main/options-normalizer.js
tests_integration/__tests__/__snapshots__/deprecated-parser.js.snap
tests_integration/__tests__/deprecated-parser.js

A quick fix for suppressing duplicate deprecation warnings.

fix(api): do not report the same deprecation warning more than once

---

CHANGELOG.unreleased.md
src/language-js/needs-parens.js
tests/typescript_function_type/__snapshots__/jsfmt.spec.js.snap
tests/typescript_function_type/jsfmt.spec.js
tests/typescript_function_type/type-annotation.ts

fix(typescript): stable parens for function type in arrow return type

---

CHANGELOG.unreleased.md
package.json
src/cli/util.js
src/common/third-party.js
src/utils/is-tty.js
tests_integration/__tests__/__snapshots__/check.js.snap
tests_integration/__tests__/__snapshots__/list-different.js.snap
tests_integration/__tests__/check.js
tests_integration/__tests__/list-different.js
tests_integration/runPrettier.js
yarn.lock

Fix CI detection to avoid unwanted TTY behavior

---

docs/plugins.md

Hi, I wrote a tutorial on how to build a plugin for Prettier and @j-f1 (who kindly proofread it) suggested that I add it to the docs. I don't know if the way I did it is the best one though, let me know if you'd prefer it in some other part.

Add tutorials section to plugins doc

---

CHANGELOG.unreleased.md
src/main/support.js
tests_integration/__tests__/__snapshots__/support-info.js.snap
tests_integration/__tests__/support-info.js

This undoes an accidental breaking change where `prettier.getSupportInfo('1.0.0')` would report supporting the `babel` parser instead of `babylon`.
Fixes #5822

Fixup getSupportInfo for babylon parser prior to 1.16.0

---

src/common/load-plugins.js
tests_integration/__tests__/plugin-virtual-directory.js
tests_integration/runPrettier.js

Basically with Yarn v2 we'll make it possible to load files directly from within the zip archive. For now this will be implemented by patching the fs module so that Node is able to see the files within the archive. The problem is that in order to work well with rimraf and similar crawlers, the archive itself mustn't be stat'd as a directory. This is problematic in Prettier because you actually check it by default.
With this change the node_modules isDirectory check will succeed, and will shortcut the one to check whether its parent directory is a directory.

Tweaks the plugin directory search

---

CHANGELOG.unreleased.md
src/language-js/printer-estree.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/closure-compiler-type-cast.js
tests/optional_chaining/__snapshots__/jsfmt.spec.js.snap
tests/optional_chaining/chaining.js

Logic introduced in https://github.com/prettier/prettier/pull/4542 will print parens in the wrong places and produce invalid code with optional chained expressions (with more than 2 nodes) or closure type casts that end in function calls 

JavaScript: Fix parens logic for optional chaining expressions and closure type casts

---

docs/rationale.md

Corrected a sentence in the docs which contained a couple of spelling/grammar mistakes.

Fix spelling/grammar in Rationale docs

---

CHANGELOG.unreleased.md
src/cli/util.js
tests_integration/__tests__/__snapshots__/stdin-filepath.js.snap

Honor stdin-filepath when outputting error messages.

Honor stdin-filepath when outputting error messages.

---

docs/plugins.md
website/versioned_docs/version-stable/plugins.md

https://github.com/iamsolankiamit/prettier-ruby has now been archived and deprecated in favour of https://github.com/prettier/plugin-ruby
Original PR: https://github.com/prettier/prettier/pull/5841

Remove archived prettier for ruby

---

src/main/comments.js

When a printer exposes its own `printComment` function and returns a doc (eg. `concat([])`) instead of a string, and a comments turns out to be trailing, Prettier printed `[Object object]`.
I spent a considerable amount of time trying to add a test for this bug fix, but it requires a test case with a custom parser supporting comments. I see that there are some test plugin in `tests_integration/plugins`, but nothing as fancy. Please tell me if you require new tests for this bug fix, and I'll try to come up with something.

Fix trailing comment output when the printer returns a doc instead of a string

---

docs/precommit.md

Currently, to install and configure lint-staged you'd need to manually install all packaged and modify the `package.json`.  With [mrm](https://github.com/sapegin/mrm) it's done automatically depending on what version of Prettier is installed and specified in project's dependencies.

docs: Add simplified installation instructions for lint-staged

---

CHANGELOG.unreleased.md
docs/configuration.md
src/config/resolve-config.js
tests_integration/__tests__/__snapshots__/config-invalid.js.snap
tests_integration/__tests__/__snapshots__/config-resolution.js.snap
tests_integration/__tests__/__snapshots__/with-config-precedence.js.snap
tests_integration/__tests__/config-resolution.js
tests_integration/cli/config/external-config/index.js
tests_integration/cli/config/external-config/node_modules/@company/prettier-config/index.json
tests_integration/cli/config/external-config/node_modules/@company/prettier-config/package.json
tests_integration/cli/config/external-config/package.json

This PR introduces support for external/shared configurations for Prettier.
Sharing a Prettier configuration is simple, just publish a module that exports a configuration object, say `@azz/prettier-config`, and reference it in your `package.json`:
```json
{
"name": "my-cool-library",
"version": "9000.0.1",
"prettier": "@azz/prettier-config"
}
```
If you don't want to use `package.json`, you can use any of the supported extensions, e.g. `.prettierrc.json`:
```json
"@azz/prettier-config"
```
This PR does **not** offer a way to _extend_ the configuration to overwrite some properties from the shared configuration. If you need to do that, import the file in a `.prettierrc.js` file and export the modifications, e.g:
```js
module.exports = {
...require('@azz/prettier-config'),
semi: false,
}; …
```

Support shared Prettier configuration

---

scripts/build/config.js

Fixes https://github.com/prettier/prettier/issues/6008
I ran `yarn build` locally, and was then able to do this: 
```
> const {builders: b, printer: p} = require('./dist/doc.js')
undefined
> p.printDocToString(b.concat(['hello', 'world']), {})
{ formatted: 'helloworld' }
```
The file is 58kb 🎉
I wasn't sure if this warranted docs or tests; please advise.

Add doc build

---

package.json
yarn.lock

- remove old resolutions field from `package.json`
- stable `@babel/code-frame` version `7.0.0` update in dependencies
These changes resolve an ugly warning message from Yarn.
Splitting this change out of PR #5982.
I have already verified that this update gives me a green build on Azure Pipelines.
- ~~(If the change is user-facing) I’ve added my changes to the `CHANGELOG.unreleased.md` file following the template.~~

@babel/code-frame 7.0.0 update

---

docs/cli.md

Closes #5896 
> Add CLI existing status information the the docs.

Add exit code information to cli docs

---

CHANGELOG.unreleased.md
src/language-js/needs-parens.js
tests/optional_chaining/__snapshots__/jsfmt.spec.js.snap
tests/optional_chaining/chaining.js

fix(javascript): correctly handle parentheses between await and optional chaining

---

CHANGELOG.unreleased.md
src/main/core.js
tests/range/__snapshots__/jsfmt.spec.js.snap
tests/range/nested-print-width.js

Fixes an issue were a file would end up formatted differently with ranged formatting (--range-start & --range-end) versus normal whole file formatting.
Fixes #6046 

Use same print width for range formatting as normal formatting.

---

CHANGELOG.unreleased.md
src/language-js/needs-parens.js
tests/comments_closure_typecast/__snapshots__/jsfmt.spec.js.snap
tests/comments_closure_typecast/closure-compiler-type-cast.js

Fixes https://github.com/prettier/prettier/issues/6067

Improved multiline closure comment detection

---

CHANGELOG.unreleased.md
src/language-js/printer-estree.js
tests/typescript_tsx/__snapshots__/jsfmt.spec.js.snap
tests/typescript_tsx/type-parameters.tsx

Previously, a trailing comma after single type parameter in arrow function was cleaned up. The formatted result is valid as ts, but is invalid as tsx. This pr is fix to keep a trailing comma for formatting to valid tsx.
Fixes #6114 

Keep a trailing comma in tsx type parameter

---

CHANGELOG.unreleased.md
src/language-js/needs-parens.js
tests/comments_closure_typecast/__snapshots__/jsfmt.spec.js.snap
tests/comments_closure_typecast/closure-compiler-type-cast.js

Closure typecasts don't require a space between the `@type` and opening `{`.

Fix closure type cast without spaces

---

scripts/build/build.js
scripts/build/bundler.js

For some reason, in Vue testing Prettier runs in an environment that polyfills `window` (#5018). A better description of the situation is in #5662
In `index.js` bundle, the TOML parser we use for config uses `global.Date` and Rollup replaces all uses of `global` for something that evaluates to the equivalent of `window || global || self || {}`. In the cases listed above, `global` will evaluate to the `window` polyfill and `global.Date` evaluates to `undefined`.
This PR will remove the `global` replacement since `index.js` is only intended to be used in a Node environment, not in the browser; this will break all uses of `index.js` in the browser, which is not supported already.
Fixes #5018
Fixes #5662

Stop handling 'global' in the Node-specific bundles

---

CHANGELOG.unreleased.md
src/language-js/needs-parens.js
tests/typescript_keyof/__snapshots__/jsfmt.spec.js.snap
tests/typescript_keyof/keyof.ts

Fix #6111
Previously, Prettier removes the necessary parentheses when trying to remove unnecessary parentheses, in TypeScript. So, I fixed to keep a pair of parentheses.

[TS] keep a pair of parentheses where there extra pairs.

---

CHANGELOG.unreleased.md
src/language-js/embed.js
tests/template_literals/__snapshots__/jsfmt.spec.js.snap
tests/template_literals/styled-jsx.js

Supports all 3 tags in `styled-jsx/css`: `css`, `css.global`, and `css.resolve`.
https://github.com/zeit/styled-jsx/#external-css-and-styles-outside-of-the-component
Fixes https://github.com/zeit/styled-jsx/issues/548
Formatting template literal with `css` was already working because it
happens to be the same as what styled-components was using.
https://www.styled-components.com/docs/api#css
So this change just adds support for `css.global` and `css.resolve`.

Add support for styled-jsx external styles

---

website/playground/panels.js

I followed the suggested best practice from the CodeMirror docs of changing the value of the CodeMirror.keyMap['keymap_name'] property to false for the Sublime shortcut that was overriding Ctrl + L to select a line rather than the browser default of selectitng the URL bar.
Unsure if this issue is considered "user-facing" or not; if it is, please let me know and I will update the CHANGELOG file along with any other requested adjustments. 
Fixes #6105

Disable Ctrl + L shortcut in CodeMirror

---

CHANGELOG.unreleased.md
src/language-js/needs-parens.js
tests/typescript_non_null/__snapshots__/jsfmt.spec.js.snap
tests/typescript_non_null/parens.ts

Keep parens around non-null assertions for new-expressions only

---

CHANGELOG.unreleased.md
src/language-js/needs-parens.js
tests/new_expression/__snapshots__/jsfmt.spec.js.snap
tests/new_expression/new_expression.js
tests/typescript_non_null/__snapshots__/jsfmt.spec.js.snap
tests/typescript_non_null/parens.ts

Fixes the bugs in #6147. Doesn't try to address the readability issues raised in that issue.
Kind of a followup to #6140. cc @thorn0.
From the changelog:
```ts
// Input
new (x()``.y)();
new (x()!.y)();
new e[f().x].y()
// Output (Prettier stable)
new x()``.y();
new x()!.y();
new e[(f()).x].y();
// Output (Prettier master)
new (x())``.y();
new (x())!.y();
new e[f().x].y();
```

Address parentheses bugs for edge cases with call and new

---

CHANGELOG.unreleased.md
src/language-js/printer-estree.js
tests/multiparser_html_ts/__snapshots__/jsfmt.spec.js.snap
tests/typescript/compiler/__snapshots__/jsfmt.spec.js.snap
tests/typescript/custom/modifiers/__snapshots__/jsfmt.spec.js.snap
tests/typescript_comments/__snapshots__/jsfmt.spec.js.snap
tests/typescript_comments/mapped_types.ts
tests/typescript_conditional_types/__snapshots__/jsfmt.spec.js.snap

Fix #5725
Previously, Prettier has removed line breaks within mapped types.This change keeps it, similar to how it treats other object types.
And, this change modify to add trailing semicolon to mapped types that include line breaks like below:
(I don't know if it is the best)
```ts
// Input
type A<T> = {
readonly [P in keyof T]: T[P]
};
// Output
type A<T> = {
readonly [P in keyof T]: T[P];
};
```

TypeScript: Keep line breaks within mapped types.

---

website/playground/Playground.js

Playground: Remove `parser` from Copy config JSON

---

CHANGELOG.unreleased.md
src/common/util.js
src/language-html/printer-html.js
src/language-js/embed.js
src/language-js/needs-parens.js
src/main/multiparser.js
tests/multiparser_html_js/__snapshots__/jsfmt.spec.js.snap
tests/multiparser_html_js/script-tag-escaping.html
tests/multiparser_js_html/__snapshots__/jsfmt.spec.js.snap
tests/multiparser_js_html/lit-html.js

Currently, if JS code embedded in HTML (via `<script>`) embedded in JS (via a template literal) contains template literals, the inner JS isn't formatted.
```js
const html = /* HTML */ `<script>var a=\`\`</script>`;
```
([playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEALGBbAG0wF5MB6AKkwAkAVAWQBlMKzMADAHjTACcBLAA4wAfADcAhr0wTiAHTnsFXMjwHCR7ANwgANCAjD+6ZKCm8IAdwAKUhGmQgJYiPwAmekACNeEsAGs4GABlQT9+KABzZBheAFc4fVxCAHVsfng0MLA4YPsM-jEMgE9HMDQHfQi0OF4Ya19IvAlkADMJAhr9ACs0AA8AIV8AoOCJPDhGCLg2jq6QXr7giMiCOABFOIh4Wc7EkDDeGt5HLwkvOAJPQQFYFPcYbGQADgAGfRuIGpTfQUcbuDHMQzfS8OAARzi-DBDQkTRaSHae30NTw-Bi8X2aBWa022xmiLm+xg53ubkeyAATPpYhJ+AQVgBhCB4ZqOKDQEEgOI1WjnByEvYAXyFQA))
This fix has been extracted from #5993. …

fix: nested embeds (JS in HTML in JS)

---

docs/ignore.md

I recently spent some time debugging a `.prettierignore` file. There's a
bit of docs about the existence of `.prettierignore`, but what's the
syntax? Is each line a regex?
Prettier uses the `ignore` package, which implements gitignore syntax.
So add a link to gitignore syntax.
----

ignore.md: add link to gitignore docs

---

CHANGELOG.unreleased.md
src/language-js/printer-estree.js
tests/typescript_tuple/__snapshots__/jsfmt.spec.js.snap
tests/typescript_tuple/jsfmt.spec.js

Fix #5846.
TypeScript trailing comma on tuple types is allowed from https://github.com/microsoft/TypeScript/pull/28919.
Keep a trailing comma on tuple types when `trailing-comma` option is `all`.
```ts
// Input
export type Foo = [
number,
number, // comment
];
// Output (Before)
export type Foo = [
number,
number // comment
];
// Output (After);
export type Foo = [
number,
number, // comment
];
```

[TypeScript]Keep a trailing comma on tuple types

---

src/doc/doc-utils.js

Fixes https://github.com/prettier/prettier/issues/6095
- Unnecessary I think
- `prettier.doc` does not have `docs`
- Not user facing

Export doc.utils.findInDoc

---

src/language-js/printer-estree.js
src/main/ast-to-doc.js

In the [Coffeescript plugin](https://github.com/helixbass/prettier-plugin-coffeescript), I've found the need to have `options` passed to `willPrintOwnComments()` (specifically, I'd want access to `options.originalText`/`options.locStart()`/`options.locEnd()`)
So this PR adds `options` as a second argument passed to `willPrintOwnComments()`

Pass options to willPrintOwnComments()

---

CHANGELOG.unreleased.md
src/language-handlebars/printer-glimmer.js
tests/glimmer/__snapshots__/jsfmt.spec.js.snap
tests/glimmer/component.hbs

This fixes an issue where unwanted white space was being added to components.
With the following input:
```hbs
<div>
<UserGreeting
@aVeryLongArgumentNameThatIsStillGoing={{@alsoAVeryLongArgument}}
/>
</div>
```
**before this PR**: (note the extra ` ` before the `/>` and the extra line break)
```hbs
<div>
<UserGreeting
@aVeryLongArgumentNameThatIsStillGoing={{@alsoAVeryLongArgument}}
/>
</div>
```
**after this PR**:
```hbs
<div>
<UserGreeting
@aVeryLongArgumentNameThatIsStillGoing={{@alsoAVeryLongArgument}}
/>
</div>
```

Fix (Glimmer): avoid unwanted whitespace in components

---

package.json
yarn.lock

This updated `@glimmer/syntax` to the latest version that still passes the existing tests, `0.38.4`. There appears to be a breaking change in `0.39` which will require some work.

[Glimmer] update @glimmer/syntax to "0.38.4"

---

CHANGELOG.unreleased.md
src/language-js/printer-estree.js
tests/typescript_tsx/__snapshots__/jsfmt.spec.js.snap
tests/typescript_tsx/type-parameters.tsx

Fix #6189 .
Prettier inserts a trailing comma to single type parameter for arrow functions in tsx, since v 1.18 (#6115 ). But, this feature inserts a trailing comma to type parameter for besides arrow functions too (e.g, function , interface ).

[TypeScript] Add trailing comma for only arrow functions in tsx.

---

CHANGELOG.unreleased.md
src/config/resolve-config.js
tests_integration/__tests__/config-resolution.js
tests_integration/cli/config/dot-overrides/.prettierrc

Support overrides for dotfiles

---

website/blog/2019-06-06-1.18.0.md

[preview](https://deploy-preview-6191--prettier.netlify.com/blog/2019/06/06/1.18.0.html)

docs: fix typos and stuff in the 1.18 release blog post

---

src/language-js/embed.js

Fix the `styled-components` method name and missing curly brace in the comments.

Fix method name in comment

---

src/language-js/printer-estree.js
tests/typescript_tuple/__snapshots__/jsfmt.spec.js.snap
tests/typescript_tuple/jsfmt.spec.js

Fix adding trailing comma in TS tuples

---

src/language-js/printer-estree.js

So when investigating #4784, I've managed to verify the issue was in `printArgumentsList()`, more specifically the part where we check if it should hug the first of the last argument, and later, verified the issue was in the `conditionalGroup`, and more specifically, the first possible group, with a combination of `ifBreak()` and `softline`.
The previous code had the following meaning: if the group breaks, print all arguments broken down; else, just concat the arguments with the wrapping parenthesis (note that there are some cases where we print a new line but the group doesn't break!). 
So the first thing I changed was: if none of the arguments break beforehand (this is before printing, so this means the argument "doc" already includes something that makes it break. It can break later …

Printing arguments: short circuiting some cases

---

website/playground/markdown.js

Previously, the "Copy markdown" button in the playground generated
markdown containing this when having selected "babel-flow" as parser:
```babel-flow
This commit changes it to:
```jsx
So that the code blocks get syntax highlighting on GitHub.

Fix markdown syntax highlighting for babel-flow

---

src/cli/util.js
tests_integration/cli/ignore-absolute-path/ignored/.prettierrc.js
tests_integration/cli/ignore-relative-path/level1/level2/.prettierrc.js

Fix #5955.
Prior to this change, the CLI would resolve the config for a file before checking it against the ignored list. If the config was invalid, the CLI would report a failure.
This change relocates the config-resolution phase until after the file is confirmed to not be ignored.

Config should not be evaluated for ignored files

---

docs/plugins.md

I tried to run `yarn build-docs` but I get some errors :(
I'm on Mac 10.14.5 and using node v12.5.0 and yarn v1.17.0
Can you try to generate the documents? Or better: Is an automation integrated somewhere?

Remove not publish from plugin pug

---

docs/browser.md

Make it easy for JS developers to know how to use the prettier standalone version in ES6 + applications.

Add ES6 instructions in browser docs

---

CHANGELOG.unreleased.md
package.json
tests/typescript_tsx/__snapshots__/jsfmt.spec.js.snap
tests/typescript_tsx/url.tsx
yarn.lock

Closes #6084
**Prettier pr-6289**
[Playground link](https://deploy-preview-6289--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEA3AhgJwATuwXmwB4ATAS1QD5sAdKbYgIxwHpK6GAFTCAKzjAxsACQgBbOEmwAKABYwYABwDOSFiwDmZGLICujAHSQxLMOihg4mRlYgBlDQA8W6MGF2ZlcEiwCUTVmoGYLoiFnIqEAAaEAhFGDJoZWRQLB4Ad04sBGSUdFQIMhJokGZXAGs4GDtFVzIoDWQYTF04GPkxABsAdVltOGVayzsc7QptAE9kcGVkmPqvTBhudA0xdGQAM3ROrxjeZUcAIUwKqrt0CQAZergtnb2QA8c7eo1OuABFXQh4e922iBap4rNMYBNFAMwJgyPESooYbBukUdMgABwABhiCIgXm6p0U0wRAysqDuMQAjj94Nw4rkQOhlABaKBwbzeEqYOBUshclZrDZIbYAmJeMRkJotQHKN4fb6-O5Ch6AmDoRjIkiopAAJhizXQZE6bwAwuJ1tMoNBySBdF4ACpq3LCrwAXxdQA)
```sh
```
**Input:**
```tsx
var a = <div> 
<br />
Project Home: (https://github.com/cancerberoSgx/accursed/) <br />      
</div>
```
**Output:**
```tsx
var a = (
<div>
<br …
```

Fix more bugs with double slash in TSX

---

docs/plugins.md
website/versioned_docs/version-stable/plugins.md

I discovered [`prettier-plugin-packagejson`](https://github.com/matzkoh/prettier-plugin-packagejson) a couple of weeks ago and am using it in all projects now. Thanks to [`sort-package-json`](https://www.npmjs.com/package/sort-package-json) internally called by the plugin, the order of `package.json` fields is consistent at all times. The team no longer needs to argue whether to sort them alphabetically / put name and version first / move dependences to the very end and so on. This is especially valuable when collaborating on a monorepo.
cc @matzkoh (the author of the plugin) and @simonepri (the author of #4040)

Add prettier-plugin-packagejson to docs

---

src/language-handlebars/printer-glimmer.js
tests/handlebars/__snapshots__/jsfmt.spec.js.snap
tests/handlebars/component.hbs

Hi,
Before:
```
{{my-component  foo="bar"  bar="baz" action=(action "almostTheMaximumLengthxxxx")
}}
```
After:
```
{{my-component
foo="bar"
bar="baz"
action=(action "almostTheMaximumLengthxxxx")
}}
```

[Glimmer/Handlebars] Forces multilines print when almost at max length

---

src/language-html/utils.js
tests/html_script/__snapshots__/jsfmt.spec.js.snap
tests/html_script/script.html

Prettier currently recognises `<script type="application/ld+json">` as JSON. This PR adds support for other `application/foo+json` types, as well as plain `application/json`. It also adds support for [import maps](https://github.com/WICG/import-maps).

Add JSON script types

---

src/cli/util.js

Small patch to check that the cache directory was found before initializing the `changedCache`.
https://github.com/prettier/prettier/pull/5910#discussion_r305870825

Handle missing cache directory for changedCache

---

docs/cli.md

While debugging a glob-related issue (caused by me not quoting the glob string as recommended in the docs) I noticed a small mistake on [the **CLI** page in the docs](https://prettier.io/docs/en/cli.html) which states that:
> The [glob syntax from the glob module](https://github.com/isaacs/node-glob/blob/master/README.md#glob-primer) is used.
After taking a look at the source code I found out that's not actually true and [the `globby` module](https://github.com/sindresorhus/globby) is used instead. As a result, [the syntax from the `fast-glob` module](https://github.com/mrmlnc/fast-glob/blob/master/README.md#pattern-syntax) (on which `globby` depends) is used.

Link to `fast-glob` instead of `glob` in docs

---

CHANGELOG.unreleased.md
src/language-html/utils.js
tests/html_whitespace/__snapshots__/jsfmt.spec.js.snap
tests/html_whitespace/template.html

Fix #6263
Previously, even if the line length is shorter than print-width is Prettier breaks the line with a template element.

HTML, Vue: Don't break the template element included in a line shorter than print-width

---

CHANGELOG.unreleased.md
src/language-js/printer-estree.js
tests/typescript_union/__snapshots__/jsfmt.spec.js.snap
tests/typescript_union/union-parens.ts

Fix #6303
Union types put with `[]`(array), `as`, `keyof`, `|`, `&` breaks after opening parenthesis, but not before closing.
```ts
// Stable
const foo = [abc, def, ghi, jkl, mno, pqr, stu, vwx, yz] as (
| string
| undefined)[];
const foo: (
| AAAAAAAAAAAAAAAAAAAAAA
| BBBBBBBBBBBBBBBBBBBBBB
| CCCCCCCCCCCCCCCCCCCCCC
| DDDDDDDDDDDDDDDDDDDDDD)[] = [];
const foo: keyof (
| AAAAAAAAAAAAAAAAAAAAAA
| BBBBBBBBBBBBBBBBBBBBBB
| CCCCCCCCCCCCCCCCCCCCCC
| DDDDDDDDDDDDDDDDDDDDDD) = bar;
const foo:
| foo
| (
| AAAAAAAAAAAAAAAAAAAAAA
| BBBBBBBBBBBBBBBBBBBBBB
| CCCCCCCCCCCCCCCCCCCCCC
| DDDDDDDDDDDDDDDDDDDDDD) = bar;
const foo: foo &
(
| AAAAAAAAAAAAAAAAAAAAAA
| BBBBBBBBBBBBBBBBBBBBBB
| CCCCCCCCCCCCCCCCCCCCCC
| DDDDDDDDDDDDDDDDDDDDDD) = bar;
// This pr
const foo = [abc, def, ghi, jkl, mno, pqr, stu, vwx, …
```

TypeScript: Fix specific union type breaks after opening parenthesis, but not before closing

---

package.json
yarn.lock

See title: update `get-stream` version to `4.1.0` in `package.json`
I verified that the Azure Pipeline build is green and that `yarn test-integration` & `yarn test` succeeds on Node.js 6. This means that installing from GitHub should continue to work on Node.js version 6.
Note that using get-stream@5 would break installation from GitHub on Node.js version 6 (see <https://github.com/prettier/prettier/pull/6224#issuecomment-519527492>).
- ~~(If the change is user-facing) I’ve added my changes to the `CHANGELOG.unreleased.md` file following the template.~~

get-stream@4.1.0 update in package dependencies

---

docs/webstorm.md

Since file watchers ignore partials like `_component.scss` (underscore!) when imported in some `main.scss`, they won’t be prettified. Use the `COMPILE_PARTIAL=true` environment variable to also watch and prettify partials.

docs: webstorm info on how to watch partials

---

docs/related-projects.md

A while ago I created a [Jest runner](https://jestjs.io/docs/en/configuration#runner-string) that runs Prettier. I've been using it in several of my projects, have it well tested, and use dependabot to keep it up to date. Since I've found using Jest to run my projects' unit tests and ensure code style to be very convenient, I'd love to have [`jest-runner-prettier`](https://github.com/keplersj/jest-runner-prettier) listed in the documentation to better share this with other Prettier users.

Add jest-runner-prettier to Related Projects Documention

---

CHANGELOG.unreleased.md
src/language-markdown/parser-markdown.js
src/language-markdown/printer-markdown.js
tests/mdx/__snapshots__/jsfmt.spec.js.snap
tests/mdx/jsx.mdx

fix: text with whitespace after JSX trim incorrectly

---

src/common/util.js
tests/nullish_coalescing/__snapshots__/jsfmt.spec.js.snap
tests/nullish_coalescing/nullish_coalesing_operator.js

@mroch told me that the spec was updated ( https://tc39.es/proposal-nullish-coalescing/ ) with the following two changes:
- ?? has lower precedence than ||. (previously equal)
- ?? cannot immediately contain, or be contained within, an && or || operation. (parens are now required)
The safe way to upgrade is to run prettier with just this change so that parenthesis are properly added. Then to upgrade the parser (only flow supports the new precedence in the next release, babel hasn't been updated yet) in prettier so that the new precedence is being used. Failure to do so will result in parse errors because of missing parenthesis so we will not have silent errors.
There was only 44 callsites mixing || and ?? in a confusing way in the Facebook codebase so it shouldn't be a huge deal in …

Update ?? precedence to match stage 3 proposal

---

docs/plugins.md
website/versioned_docs/version-stable/plugins.md

Remove alpha from plugin pug in docs
I released 1.0.0

Remove alpha from plugin pug

---

CHANGELOG.unreleased.md
src/language-js/needs-parens.js
tests/new_expression/__snapshots__/jsfmt.spec.js.snap
tests/new_expression/new_expression.js
tests/typescript_non_null/__snapshots__/jsfmt.spec.js.snap
tests/typescript_non_null/parens.ts

Fixes #6147: leave `new (a().b)()` as-is, rather than changing to `new (a()).b();`.

More readable parentheses for new-call

---

CHANGELOG.unreleased.md
src/language-js/printer-estree.js
tests/typescript_conditional_types/__snapshots__/jsfmt.spec.js.snap

TypeScript: Fixed to break line and add a semi in one execution on one line long mapped types

---

CHANGELOG.unreleased.md
src/language-js/printer-estree.js
tests/flow_parameter_with_type/__snapshots__/jsfmt.spec.js.snap
tests/flow_parameter_with_type/jsfmt.spec.js
tests/flow_parameter_with_type/param.js

Fixes #6435: don't print a trailing comma or extra space when printing an object pattern which is empty but has a type annotation.
This doesn't precisely give the output the OP of that issue asked for, because it doesn't wrap at all - when the parameter is a single array or object pattern, it doesn't allow the parameters to break. But it seems fine, and at least fixes the correctness issue.

handle empty object patterns with type annotations in function parameters

---

CHANGELOG.unreleased.md
src/language-js/comments.js
tests/optional_chaining/__snapshots__/jsfmt.spec.js.snap
tests/optional_chaining/comments.js

Fix #6500
```js
// Input
return a
.b()
.c()
// Comment
?.d()
// Prettier (stable)
return a
.b()
.c()
?.// Comment
d();
// Prettier (master)
return (
a
.b()
.c()
// Comment
?.d()
);
```

JavaScript: Fix Bad format for multi-line optional chaining with comment

---

CHANGELOG.unreleased.md
src/language-js/printer-estree.js
tests/typescript/custom/typeParameters/__snapshots__/jsfmt.spec.js.snap
tests/typescript/custom/typeParameters/variables.ts

Fix #5684 
I understand that this fix doesn't make much sense in practice. But, since its behavior is a bug, I created pr.
```ts
// Input
const fooooooooooooooo: SomeThing<boolean> = looooooooooooooooooooooooooooooongNameFunc();
// Prettier (stable)
const fooooooooooooooo: SomeThing<
boolean
> = looooooooooooooooooooooooooooooongNameFunc();
// Prettier (master)
const fooooooooooooooo: SomeThing<boolean> = looooooooooooooooooooooooooooooongNameFunc();
```

TypeScript: Keep type parameters inline for a variable declaration

---

docs/plugins.md

This is a Documentation PR which proposes to add [`prettier-plugin-package`](https://github.com/shellscape/prettier-plugin-package) to the list of Community Plugins.
Acknowledging that `prettier-plugin-packagejson` already exists, the plugin I am proposing to add is functionally different:
- leverages `parser` rather than `preprocess`. This means that Prettier's parsing and error handling is run before modification, and results in a good user experience. Especially important for `package.json` files containing errors. 
- no extraneous `JSON.stringify` or `JSON.parse` calls
- root sorting based on well-known and prolific package author's preferences
I'm not sure if there is a standard or bar that must be met to have a plugin included in this list, but if it's compelling, the Rollup project …

docs: add prettier-plugin-package to community plugins

---

package.json
yarn.lock

Since #6541 requires changes, update `remark-math` to latest compatible version first

Update `remark-math` to v1.0.6

---

package.json
yarn.lock

this is latest version support node v6, replace #6550 , please close #6550 when merge this one

Update `jest-watch-typeahead` to v0.3.1

---

CHANGELOG.unreleased.md
src/language-js/printer-estree.js
tests/arrows/__snapshots__/jsfmt.spec.js.snap
tests/decorators-ts/__snapshots__/jsfmt.spec.js.snap
tests/decorators/__snapshots__/jsfmt.spec.js.snap
tests/functional_composition/__snapshots__/jsfmt.spec.js.snap
tests/functional_composition/ramda_compose.js
tests/typescript_arrow/__snapshots__/jsfmt.spec.js.snap

This PR removes the hard-coded strings used to detect function composition in favor of a heuristic which counts the number of function literals passed as arguments.
In my opinion, the counter-examples are all places where it would be unreasonable to expect line-breaks (e.g. redux connect functions) or where line-breaks should occur anyways (the most common example is calling `Promise.prototype.then` with two short functions).
Related issues:
- Long curried function calls #1420
- RxJS pipe chaining get formatted on a single line #4172
- Add heuristic to format functional composition more nicely #4431
- Functional composition heuristics false positives #4751
- Improve functional composition heuristics #4758
- Codes format unexpected with function "pipe" #4858
- Composed functions not put on …

Javascript: Use function literals in arguments to detect function composition

---

package.json
yarn.lock

I think #6621 contains other deps updates, only update `eslint` to see the CI result

Update `eslint` to v6.5.1

---

CHANGELOG.unreleased.md
src/language-js/parser-babylon.js
src/language-js/printer-estree.js
tests/v8_intrinsic/__snapshots__/jsfmt.spec.js.snap
tests/v8_intrinsic/intrinsic_call.js
tests/v8_intrinsic/jsfmt.spec.js

Add support for V8 intrinsics via Babel

---

package.json
yarn.lock

This dependency is not using currently

Remove useless `rollup-plugin-node-builtins`

---

docs/configuration.md

This updates the docs to show the search order of the config files.
Order comes from: https://github.com/prettier/prettier/blob/3805034bdfe45722e31a1abf019d4368dfb8ae11/src/config/resolve-config.js#L35-L44

docs/configuration: specify order of precedence

---

scripts/build/config.js

use `includes-with-indexof` instead of hard code replacement

Use `babel` plugin replace `includes`

---

src/language-js/parser-babylon.js
tests/exports/__snapshots__/jsfmt.spec.js.snap
tests/exports/test.js

Babel 7.4.0 introduced a [check for undefined exported bindings](https://github.com/babel/babel/pull/9589). It could break Prettier's range formatting, but luckily, they also added a [way to disable it](https://github.com/babel/babel/pull/9864) in 7.5.0.
No changes in the API or CLI. Not a user-facing change.

enable the allowUndeclaredExports Babel option

---

scripts/build/build.js
scripts/build/config.js

fixes: https://github.com/prettier/prettier/issues/6656

Remove usage of `require.extensions` in `parser-glimmer.js`

---

CHANGELOG.unreleased.md
src/language-js/printer-estree.js
tests/classes_private_fields/__snapshots__/jsfmt.spec.js.snap
tests/classes_private_fields/private_fields.js
tests/destructuring/__snapshots__/jsfmt.spec.js.snap
tests/destructuring/destructuring.js

Adds `ObjectMethod` `ClassMethod`, and `ClassPrivateMethod` to the list of types that should/shouldn't cause line breaks. Now they behave like `ArrowFunctionExpression`.
fixes #6515

fix(js): Object destructuring in method shorthand #6515

---

CHANGELOG.unreleased.md

I removed the description in some entries where the title was descriptive enough.

fix spelling, wording, markup issues in CHANGELOG.unreleased.md

---

CHANGELOG.unreleased.md
src/language-js/parser-babylon.js
src/language-js/printer-estree.js
tests/partial_application/__snapshots__/jsfmt.spec.js.snap
tests/partial_application/jsfmt.spec.js
tests/partial_application/test.js

feat: add support for PartialApplication

---

website/playground/util.js

The select shows "flow" while in fact "babel" is used.

fix playground: wrong parser shown in options on first open

---

CHANGELOG.unreleased.md
website/static/separate-css/playground.css

Fixes https://github.com/prettier/prettier/issues/6297
Adds a `z-index` to the button tooltips in the footer in the playground to bring the tooltip above the browser scrollbar.

Fix tooltip being hidden behind browser scrollbars

---

CONTRIBUTING.md

Fixes #5887.
Just adds a tiny bit of extra guidance around how to invoke the tool to debug locally, for those new to the codebase.

Add basic instructions on how to run Prettier locally for debugging.

---

package.json
yarn.lock

see title
Most recent release of TypeScript is *highly desired* to support JavaScript type linting (type checking using JSDoc comments) as we have been working on in multiple PRs such as  #6313 & #6702.
A timely review would be much appreciated.
Unfortunately I don't think we should include TypeScript 3.7 in the RC stage.
- ~~(If the change is user-facing) I’ve added my changes to the `CHANGELOG.unreleased.md` file following the template.~~
/cc @Shinigami92 @lydell

typescript@3.6.4 update

---

src/main/core-options.js

with unused `oppositeDescription` parameter removed
and reordering of some other members
to resolve checkJs issues in `src/main/core-options.js`,
as verified by the following command:
```
npx tsc --allowJs --checkJs --noEmit --target es5 src/main/core-options.js
```
I can also enable Check JS in VSCode and see that the type errors go away in `src/main/core-options.js`.
In the future, it should be possible to typecheck the whole project by either:
- using a command like this (99% solution): `npx tsc --allowJs --checkJs --noEmit --resolveJsonModule --target es5 src/index.js`
- add tsconfig.json and just do `npx tsc` or use a script that calls `tsc` to check all sources
for reference:
- https://medium.com/@trukrs/javascript-type-linting-5903e9e3625f
- …

JSDoc type fixes in `src/main/core-options.js`

---

package.json
yarn.lock

original PR https://github.com/prettier/prettier/pull/6550

Update `jest-watch-typeahead` to v0.4.0

---

src/language-css/index.js
src/language-graphql/index.js
src/language-handlebars/index.js
src/language-html/index.js
src/language-js/index.js
src/language-markdown/index.js
src/language-yaml/index.js
src/utils/create-language.js

Refactor internal api `createLanguage` to use function transform, this makes it more powerful and easier to use, no need check how `extend` `exclude` `override` works
It will be even easier to use when we support `Spread syntax`

Refactor createLanguage to use function transform

---

.azure-pipelines/jobs/prod-build.yml
scripts/build/build.js
scripts/build/bundler.js
scripts/build/config.js

the new version of `terser-webpack-plugin` v2.1.3 https://github.com/prettier/prettier/pull/6654 generate extra `parser-postcss.js.LICENSE` file, when minify
see this file first line: https://deploy-preview-6654--prettier.netlify.com/lib/parser-postcss.js

Prevent webpack generate `.LICENSE` file when minify

---

package.json

I made a mistake in #6751 `-p` should be a `npx` argument, not `cspell` command argument
to see difference
```bash
$ npx -p cspell@1 cspell --version
npx: installed 117 in 20.66s
1.10.6
$ npx cspell -p cspell@1 --version
4.0.30
```

Fix spellcheck script

---

website/data/editors.yml

The `prettier-emacs` repository actually contains the `prettier-js` package.

prettier-emacs is actually prettier-js-mode

---

docs/cli.md

Revert "Link to `fast-glob` instead of `glob` in docs (#6333)"

---

src/main/options-normalizer.js
tests_integration/__tests__/__snapshots__/plugin-options-string.js.snap
tests_integration/__tests__/plugin-options-string.js
tests_integration/plugins/options-string/config.json
tests_integration/plugins/options-string/plugin.js

This PR allows plugins to specify option with type `string`. Currently (as can be seen in #6151), Prettier only accepts option types `int`, `choice`, `boolean`, `flag`, `path`, and rejects type `string`.
Fixes #6151.

#6151 -- Allow plugin to specify option with type `string`

---

src/language-js/printer-estree.js
tests/break-calls/__snapshots__/jsfmt.spec.js.snap
tests/break-calls/type_args.js

fix for https://github.com/prettier/prettier/issues/6469#issuecomment-549093687
**✨[Try the playground for this PR](https://deploy-preview-6791--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuc0DOMAEAnOaAO6cmAvJmhALZwwAWAllAOYB0AJLTDPi0zQDwAVBswCGlUQCMIkgMpxsAN3pg4LACI1R9ADZp1omKIB8ACgA6UTJgAGo-PQD0AMwgQWotLQAeLtwFoAEy1dNEc2YEoATwBJQIBfGwAaS2tgTDBRMFo4JEwARwBXQu8WTm4AYSycpMwYemoIQqx4ywBKAG5LECSQCHx69GRQUWxsCAB3AAVRhDRkEFFFCHpAnpBJbCyAaxpZfCzGJmQYbEK4Xs5KHQB1BngCLLh5KDR6euUYKIWwNHnexhoBQwKZbJgSZDOUR6C4gABWaG8ACEtmBdjBZOI4AAZRhwSHQoG9BHeWRHHRwACKhQg8AJMN6B2wQOwCy++DwYGw9AG63w3NgN1WdGQAA4AAyM8ZAm5bfALfl4BSKfG9Iq0uCg-rzFCefxQOBwYJrXq4Ir0XCg0Tg0T0okgIGUegnM6wt7MCnUjV22FGSRCwIipAAJl6p20OiOFSoEJQUGgqpAhSBgikOqhDJAinOMSgwVgsi5PJgAEE87IvhSffF4kA)✨**

disable optimization from #6229 for calls with type arguments

---

website/versioned_docs/version-stable/index.md

I noticed that links on the website isn't https after #6811 was merged, so I fixed it.
(the link to JSON was also changed to https)

Fix links to http in website for following #6811

---

CHANGELOG.unreleased.md
src/language-js/index.js
tests_integration/__tests__/__snapshots__/support-info.js.snap

Closes https://github.com/prettier/prettier/issues/6769
This PR adds support for the VS Code mongo language (alias of javascript)
- ~(If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)~

Add mongo as a VS Code supported language

---

package.json
yarn.lock

resolves critical `yarn audit` issue due to: https://www.npmjs.com/advisories/755
without causing any regressions (failures) in the existing test suite
I hope this update can be part of the release 1.19 checklist (#6469).

audit(critical): handlebars@4.4.5 in package resolutions

---

yarn.lock

https://github.com/prettier/prettier/pull/6853#issuecomment-550778779 handlebars still lock to `4.4.5`

Remove extra requirement in yarn.lock

---

CHANGELOG.unreleased.md
src/language-js/needs-parens.js
tests/nullish_coalescing/__snapshots__/jsfmt.spec.js.snap
tests/nullish_coalescing/nullish_coalesing_operator.js

Mixing nullish coalescing (`??`) with the other logical operators (`&&` and `||`) requires parenthesis to disambiguate the inteded short circuiting. Without it, it's a `SyntaxError`. Earlier drafts of the spec allowed mixing, but it was disallowed when we reached Stage 3.
See https://v8.dev/features/nullish-coalescing#mixing-and-matching-operators

Fix nullish coalescing parenthesis with mixed logical operators

---

package.json
src/language-js/parser-babylon.js
tests_integration/__tests__/__snapshots__/format.js.snap
tests_integration/__tests__/format.js
yarn.lock

Otherwise Prettier formats `<a/><b/>` to `<a/ >;`.

Fix lost adjacent JSX when using Babel

---

src/language-js/printer-estree.js
tests/big-int/__snapshots__/jsfmt.spec.js.snap
tests/big-int/jsfmt.spec.js

fix printing bigint literals parsed by Flow

---

yarn.lock

Unfortunately, yarn.lock merged in #6882 is unstable. Yarn rewrites it on `yarn install`. This PR fixes this issue.

deduplicate entries in yarn.lock - part 2

---

changelog_unreleased/typescript/pr-6896.md
src/language-js/printer-estree.js
tests/typescript_generic/__snapshots__/jsfmt.spec.js.snap
tests/typescript_generic/arrow-return-type.ts

fix formatting of union type as arrow function return type

---

src/language-html/options.js
tests_integration/__tests__/__snapshots__/support-info.js.snap

Fix `since` version for `vueIndentScriptAndStyle`

---

changelog_unreleased/cli/pr-6894.md
package.json
yarn.lock

Closes #6891.
This downgrades the get-stream package from 5.x to 4.x, which does not
use `async` functions which works around the problem of
`regeneratorRuntime` not being defined (it shouldn’t be needed).
This is an alternative solution to #6893 because I don’t know yet if we
want to enable `corejs` given that we will most likely drop support for
Node.js 8 and older in the next version.
Just like #6893 this PR comes without tests, but I verified locally that
`--stdin` works after this change.
/cc @fisker @evilebottnawi

Quick-fix for stdin being broken in 1.19.0

---

.azure-pipelines/jobs/prod-test.yml
.azure-pipelines/steps/install-dependencies.yml
.azure-pipelines/steps/install-nodejs.yml
azure-pipelines.yml

As required in https://github.com/prettier/prettier/issues/6888 , drop CI test running on node 4.
It's only two month schedule, the clock is ticking, let's get started

Drop Node.js 4 test on CI

---

src/language-js/parser-babylon.js
tests/decorators/__snapshots__/jsfmt.spec.js.snap
tests/decorators/mixed.js

see also https://github.com/prettier/prettier/issues/6889#issuecomment-552075267

refactoring: Babel's error recovery superseded option combinations

---

scripts/generate-schema.js
tests_integration/__tests__/__snapshots__/schema.js.snap

Prettier supports having just a string in the config file to use a
shared config from a package. Example:
"@company/prettier-config"
But the JSON schema generated by running `node
scripts/generate-schema.js` did not include that possibility.
See https://github.com/SchemaStore/schemastore/pull/855 for more
information.

Support string-to-package config in JSON schema:

---

src/language-js/printer-estree.js
tests/angular_interpolation/__snapshots__/jsfmt.spec.js.snap
tests/angular_interpolation/jsfmt.spec.js

extra comma, cause parse error, fond in #6910

Disable trailingComma for Angular internal parser

---

changelog_unreleased/mdx/pr-6949.md
src/language-js/preprocess.js
src/language-js/printer-estree.js
src/language-markdown/embed.js
src/language-markdown/parser-markdown.js
src/language-markdown/printer-markdown.js
src/language-markdown/utils.js
tests/mdx/__snapshots__/jsfmt.spec.js.snap
tests/mdx/levels.mdx

For MDX wrap JSX parsing in a fragment before sending it of to babel for parsing and formatting. In MDX adjacent JSX tags are permitted in the root.
An option sent to the babel parser omits printing the root fragment and instead just prints its children.
Fixes #6943
**✨[Try the playground for this PR](https://deploy-preview-6949--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAeAKgQwOYAIBumANgK5wC8wwumSuAOiAEaO4C+bAfPAM4yoB6LNk64AjACYAzPSioAYhAi4m2SowBOcACaMus3LlTaAlvlx8AnkQpVcpngAcimS3UZMiEMAGtWHTgNDIwAhTA1OAAsTIwEwiKDDYEi4Ii82RNxgAQAqGigIGBSNXEgAWzKEGFwcgQyoQ0FTfEC5AUUIUQAWAFYANhAAGhAIRxgTaB5kUHCNCAB3AAVwhCmUTHwIE20h5g1MXzgYAGVHA5MobGQYDTJhyJgyogB1aN4zsDhj1ZNx-F-LMhwDwpsMLjw4BoYIt9tgyphkAAzYgQ4YAKx4AA8QvtDidMJUADIXOBIlFwdFY44XbA2ACKJEKpKQyKIqJAZw0EI0QLK2kxu0cGguMGe2yKyAAHAAGYZCiAQ577 …

Fix MDX html parsing errors

---

scripts/build/bundler.js
scripts/build/config.js

It's really annoying, and hard to locate code, let's enable it for all bundles.
maybe we can also merge #6967 to `master` instead of `next`

Enable `replace-array-includes-with-indexof` for all bundles

---

changelog_unreleased/javascript/pr-6984.md
src/language-js/comments.js
tests/label/__snapshots__/jsfmt.spec.js.snap
tests/label/comment.js

Fix #6983 
I added the handleLabeledStatementComments in handleOwnLineComment to deal with comments like:
```js
loop:
// comment
const t = 1;
```
As it is my first PR here, please let me know if I have to do something more (add some tests somewhere, for instance) 😄 

Fix handling comments in labeled statements

---

changelog_unreleased/mdx/pr-6398.md
src/language-markdown/mdx.js
tests/mdx/__snapshots__/jsfmt.spec.js.snap
tests/mdx/jsx.mdx

fix: format JSX Fragment correctly, consider Fragment as block

---

changelog_unreleased/typescript/pr-7020.md
cspell.json
src/language-js/needs-parens.js
src/language-js/printer-estree.js
tests/typescript_error_recovery/__snapshots__/jsfmt.spec.js.snap
tests/typescript_error_recovery/jsdoc_only_types.ts

fixes #5840 
It would be really easy to replace these types with valid TS, but so far we (with @evilebottnawi) [decided](https://github.com/prettier/prettier/issues/5840#issuecomment-555942944) to print them as is.

TypeScript: print JSDoc-only types

---

changelog_unreleased/javascript/pr-7026.md
src/language-js/clean.js
src/language-js/loc.js
src/language-js/postprocess.js
tests/logical_expressions/__snapshots__/jsfmt.spec.js.snap
tests/logical_expressions/issue-7024.js

fix unstable formatting of logical expressions

---

changelog_unreleased/javascript/pr-7070.md
src/language-js/needs-parens.js
src/language-js/printer-estree.js
tests/throw_statement/__snapshots__/jsfmt.spec.js.snap
tests/throw_statement/binaryish.js
tests/throw_statement/comment.js
tests/throw_statement/jsfmt.spec.js
tests/throw_statement/jsx.js

https://github.com/prettier/prettier/pull/7042#discussion_r349902896
```js
// Input
function foo() {
throw this.hasPlugin("dynamicImports") && this.lookahead().type === tt.parenLeft.right;
}
function foo() {
return this.hasPlugin("dynamicImports") && this.lookahead().type === tt.parenLeft.right;
}
// Prettier stable
function foo() {
throw this.hasPlugin("dynamicImports") &&
this.lookahead().type === tt.parenLeft.right;
}
function foo() {
return (
this.hasPlugin("dynamicImports") &&
this.lookahead().type === tt.parenLeft.right
);
}
// Prettier master
function foo() {
throw (
this.hasPlugin("dynamicImports") &&
this.lookahead().type === tt.parenLeft.right
);
}
function foo() {
return (
this.hasPlugin("dynamicImports") &&
this.lookahead().type === tt.parenLeft.right
);
}
``` 
@prettier/core …

JavaScript: Format ThrowStatement like ReturnStatement

---

changelog_unreleased/typescript/pr-7075.md
src/language-js/printer-estree.js
tests/typescript_tuple/__snapshots__/jsfmt.spec.js.snap
tests/typescript_tuple/no-trailing-comma-after-rest.ts

* A rest element is always the last element of a tuple type. Nothing can be added after it.
* While TS is okay with this comma, Babel doesn't parse it. https://github.com/babel/babel/issues/10769
* In function parameters and array destructuring, such a comma is a syntax error. Keeping it in tuples is inconsistent.

Don't print trailing commas after rest elements in tuples

---

src/common/fast-path.js
src/common/util.js
src/language-js/embed.js
src/language-js/printer-estree.js

Those `parentParentParent` deep condition checks are getting too awkward. We need a convenient and unified way to perform them.

refactoring: introduce path.match

---

tests_config/run_spec.js

E.g. a test called "flow-verify" verifies that the output with `--parser flow` is identical to the the reference output. However, when such a test fails, the reference output is called "Received" and the output of the current parser "Expected", which is really confusing and misleading.

tests: "Expected" and "Received" are mixed up in parser verification tests

---

changelog_unreleased/javascript/pr-7138.md
src/language-js/printer-estree.js
tests/decorators-ts/__snapshots__/jsfmt.spec.js.snap

fixes #6953
Decorators are most readable when they’re on a single line, because they modify the declaration/parameter which follows them. Therefore, we revert the new function literal behavior introduced in https://github.com/prettier/prettier/pull/6033 for decorator calls.

revert function composition logic for decorators

---

changelog_unreleased/javascript/pr-7140.md
src/language-js/printer-estree.js
tests/return/__snapshots__/jsfmt.spec.js.snap
tests/return/comment.js

JavaScript: Fix moving semi for `return` to end of line-comment

---

src/language-handlebars/printer-glimmer.js

This PR is an extraction of some experiments I made for resolving this comment https://github.com/prettier/prettier/pull/7051#discussion_r351877770.
It doesn't bring in any new feature or bug fix but aims at slightly simplifying / cleaning up / bringing consistence in glimmer printer.
It might be reviewed commit per commit (changes are split in 4 commits).

Refactor a few functions in glimmer printer

---

src/language-handlebars/printer-glimmer.js

Let's simplify how `ElementModifierStatement` nodes are printed.
This has another benefit: it will allow me to iterate on `MustacheStatement` nodes without impacting `ElementModifierStatement`s.
This should be merged after https://github.com/prettier/prettier/pull/7072 on which it is based.

glimmer: Split ElementModifierStatement and MustacheStatement

---

docs/vim.md

Since the author of the Vim plugin ALE moved the repository to an organization account, the command used to download the plugin has changed from `Plug 'w0rp/ale'` to `Plug 'dense-analysis/ale'`

Fixed ALE installation instruction

---

changelog_unreleased/markdown/pr-7181.md
src/language-markdown/printer-markdown.js
tests/markdown_html/__snapshots__/jsfmt.spec.js.snap
tests/markdown_html/beginning-tag-after-a-list-item.md

fix #5907
I apologize for making mistakes creating a lot of troublesome PRs (#7182 - #7201) and sending unnecessary notifications to repository watchers and maintainers :bowing_man:

Markdown: fix HTML formatting broken if the beginning tag starts after a list item

---

changelog_unreleased/handlebars/pr-7157.md
src/language-handlebars/printer-glimmer.js
tests/handlebars-mustache-statement/__snapshots__/jsfmt.spec.js.snap
tests/handlebars-mustache-statement/basics.hbs
tests/handlebars-text-wrap/__snapshots__/jsfmt.spec.js.snap
tests/handlebars-whitespace/__snapshots__/jsfmt.spec.js.snap

Here is the issue addressed by this PR:
```
{{!-- input --}}
<p>Hi here is your name, as it will be displayed  {{firstName}}  {{lastName}}   , welcome!</p>
{{!-- stable --}}
<p>
Hi here is your name, as it will be displayed {{firstName}} {{lastName
}} , welcome!
</p>
{{!-- master --}}
<p>
Hi here is your name, as it will be displayed {{firstName}} {{
lastName
}} , welcome!
</p>
```
As a result, it will implement https://github.com/prettier/prettier/pull/7051#discussion_r351894842 and https://github.com/prettier/prettier/pull/7051#discussion_r351877770
It depends on [this first](https://github.com/prettier/prettier/pull/7072) and [second](https://github.com/prettier/prettier/pull/7072) PRs (they should be settled first). …

handlebars: Improve MustacheStatement printing

---

docs/cli.md

I noticed that two links on https://prettier.io/docs/en/cli.html are broken. They are both missing the `--`.

docs: Fix broken links

---

changelog_unreleased/typescript/pr-7144.md
src/language-js/comments.js
tests/typescript_comments/__snapshots__/jsfmt.spec.js.snap
tests/typescript_comments/declare_function.ts
tests/typescript_comments/method_types.ts
tests/typescript_comments/methods.ts

This PR fixes some of position issues with comment and fixes  #4078
Affected comments are only one from within function like nodes when there is no params provided.
Tests shows other issues that was not affected by this change.

fix: comments for typescript function like nodes

---

src/language-graphql/printer-graphql.js
tests/graphql_directive_decl/__snapshots__/jsfmt.spec.js.snap
tests/graphql_directive_decl/directive_decl.graphql

This PR fixes a bug where (or really adds a feature) `repeatable` (new in `graphql@14.4.0`) GraphQL `DirectiveDefinitionNode`'s were not being printed correctly.

GraphQL: Support repeatable directive definition printing (closes #7226)

---

changelog_unreleased/cli/pr-7210.md
package.json
tests_integration/__tests__/__snapshots__/support-info.js.snap
yarn.lock

Update [linguist-languages](https://github.com/ikatyang/linguist-languages) to 7.7 for `.cjs` and `.yaml.sed`
```sh
$ prettier test.cjs
test.cjs[error] No parser could be inferred for file: test.cjs
$ prettier test.cjs
"use strict";
console.log("Hello, World!");
```

Update linguist-languages to support file extensions `.cjs` and `.yaml.sed`

---

package.json
src/common/load-plugins.js
website/package.json
website/playground/sidebar/SidebarOptions.js
website/yarn.lock
yarn.lock

The `lodash.*` packages are deprecated and abandoned. The recommended thing is to use `lodash/*` instead. See https://github.com/lodash/lodash/issues/3838

use lodash/* instead of lodash.*

---

changelog_unreleased/scss/pr-7211.md
src/language-css/printer-postcss.js
tests/css_scss/__snapshots__/jsfmt.spec.js.snap
tests/css_scss/string-concatanation.scss

Scss: fix scss variable string concatenation removing spaces

---

package.json
tests_integration/runPrettier.js

> If you have a single executable, and its name should be the name of the package, then you can just supply it as a string. 
Ref: https://docs.npmjs.com/files/package.json#bin

Use shorthand `bin` in package.json

---

changelog_unreleased/html/pr-7293.md
src/language-html/utils.js
tests/html_basics/__snapshots__/jsfmt.spec.js.snap
tests/html_basics/broken-html.html

fixes: #7241
- [stable playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4D5UDOADgIZS4A6UqABFSADQgREybQHKgkBOPEAdwAKvBJxQlsETOkYgARjxJgA1nBgBlUmExQA5shg8ArnCYALGAFsANgHVzmeMWVwNYpzicBPZOAKcTLoEcDwwQkp6ViTIAGYkNiFMAFYEAB4AQkqq6hokVnAAMrpwcQlJIKlpGrp6NnAAisYQ8GWJZiCkPCE8fpa2ckQ8ujB2MjDmyAAcAAxMQxAhdkpEfkNwPdilTACOzfARLOIgJAQAtFBwcOjXcjxwe5j3ESRRMUjx7UwhVpiGJh0CLV6k0WqUPuUOjASPIxugJsgAExMIwkTA2WoAYQgVmifig0G2IGMIQAKjDxJ8KthTABJKA3WAaMDDVgAQQZGhg3nqbRCAF9+UA)
- [PR playground](https://deploy-preview-7293--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4D5UDOADgIZS4A6UqABFSADQgREybQHKgkBOPEAdwAKvBJxQlsETOkYgARjxJgA1nBgBlUmExQA5shg8ArnCYALGAFsANgHVzmeMWVwNYpzicBPZOAKcTLoEcDwwQkp6ViTIAGYkNiFMAFYEAB4AQkqq6hokVnAAMrpwcQlJIKlpGrp6NnAAisYQ8GWJZiCkPCE8fpa2ckQ8ujB2MjDmyA …

Fix: don't throw on broken html

---

.eslintrc.yml
scripts/build/bundler.js

I think it's time to start using it. It's still transpiled by Babel because that's how `@babel/preset-env` is configured (`targets.browsers = [">0.25%", "not ie 11", "not op_mini all"]`), but I switched this transpilation to the [loose mode](https://babeljs.io/docs/en/babel-plugin-proposal-object-rest-spread#loose) to minimize the overhead.

Let's start using the object spread syntax in the code base

---

.eslintrc.yml
src/cli/util.js
src/index.js
src/language-html/syntax-attribute.js
src/language-js/needs-parens.js
src/language-js/printer-estree.js
src/language-markdown/printer-markdown.js
src/standalone.js

Use `fn(...args)` insteadof `fn.apply(this, args)`, enable [`prefer-spread`](https://eslint.org/docs/rules/prefer-spread)

Style: enable `prefer-spread`

---

.eslintrc.yml
website/playground/EditorState.js
website/playground/Playground.js
website/playground/buttons.js
website/playground/panels.js

Fix `prefer-object-spread` in `/website`

---

changelog_unreleased/handlebars/pr-7275.md
docs/ignore.md
src/language-handlebars/parser-glimmer.js
src/language-handlebars/printer-glimmer.js
tests/handlebars-prettier-ignore/__snapshots__/jsfmt.spec.js.snap
tests/handlebars-prettier-ignore/jsfmt.spec.js
tests/handlebars-prettier-ignore/prettier-ignore.hbs

This pull request adds the ability to use `{{! prettier-ignore }}` in  glimmer/handlebars

handlebars: Add prettier-ignore

---

.eslintrc.yml
website/.eslintrc.yml

Local tested, root rules works as expected in `/website`.

Move React ESLint rules to `/website`

---

package.json
scripts/sync-flow-tests.js
tests_config/run_spec.js
yarn.lock

Node.js v8 moved to End-of-Life on Dec 31, 2019. ( Please see https://github.com/nodejs/Release)
Node.js v10.13.0 is minimum LTS version now.
Moreover, new API's options in Node.js Core are added in Node.js v10.13.0. 
- [withFileTypes](https://nodejs.org/api/fs.html#fs_fs_readdirsync_path_options) option for `fs.readdirSync` can make code faster than using `fs.stat`.
- [recursive](https://nodejs.org/api/fs.html#fs_fs_mkdirsync_path_options) option for `fs.mkdirSync` can recursively make directories so that `mkdirp` package is no longer need.

Upgrade Node.js version and drop mkdirp

---

tests_integration/path-serializer.js

The drive letter case returned by `process.cwd()` and other functions can be inconsistent.

fix tests on Windows: drive letter case issue

---

.eslintrc.yml
src/common/fast-path.js
src/language-css/parser-postcss.js

Notice: Similar changes inside `fast-path.js` was merged and reverted.  ( #6225 and #6226 )
But I see no reason not use rest params (node 10 supports this), we already used it a lot.

Enable ESLint `prefer-rest-params` rule

---

src/main/core.js

Use BOM string, so we don't have to use `String.fromCharCode` after format.
And renamed it, I believe it's called `unicode BOM` or [`BOM`](https://en.wikipedia.org/wiki/Byte_order_mark)

Use BOM string instead of BOM charCode

---

docs/api.md

It is not immediately obvious how to set the language (`options.parser`), hopefully this will save others time.

Clarify API docs

---

src/common/util.js
src/language-js/printer-estree.js
src/language-js/utils.js

- Move `isExportDeclaration` and `getParentExportDeclaration` into `src/language-js/util.js`
- Simplify `isExportDeclaration`

Minor tweak

---

src/config/resolve-config-editorconfig.js

Remove useless argument in `editorconfig` load function

---

src/common/fast-path.js

After https://github.com/prettier/prettier/pull/7418 get merged, we will no longer tansfrom classes into functions, there is no reason not to use `class`

Rewrite FastPath class

---

src/common/parser-include-shebang.js
src/language-js/clean.js
tests/flow/sketchy_null_default/__snapshots__/jsfmt.spec.js.snap
tests/flow/sketchy_null_default/jsfmt.spec.js
tests/flow/sketchy_null_default/test.js

I found a failed test
```js
const foo: ?boolean = true;
const bar = true || (foo || false);
```
This will format to 
```js
const foo: ?boolean = true;
const bar = true || foo || false;
```
AST_COMPARE shows diff
```diff
@@ -67,13 +67,11 @@
"source": null,
},
"type": "Literal",
"value": true,
},
-               "loc": Object {
-                 "source": null,
-               },
+               "loc": Object {},
"operator": "||",
"right": Object {
"loc": Object {
"source": null,
},
@@ -81,14 +79,12 @@
"optional": false,
"type": "Identifier",
"typeAnnotation": null,
},
"type": "LogicalExpression",
-             },
-             "loc": Object {
-               "source": null,
},
+             "loc": Object {},
"operator": "||",
"right": Object {
"loc": Object {
"source": null,
},
```
I'm not …

Fix a failed test on `flow` parser

---

src/language-handlebars/printer-glimmer.js
src/language-handlebars/utils.js

Extract a few glimmer printer utils into a file, similar to what is done for others languages.

refactoring(glimmer): Extract utils from printer

---

tests_integration/__tests__/format.js

[Before:](https://dev.azure.com/prettier/prettier/_build/results?buildId=5096&view=logs&j=feaed275-2517-5ad3-d429-3dc96013ea33&t=e2f326fe-3fae-5235-1e33-c604ad7f1ff7&l=32)
```text
PASS tests_integration/__tests__/format.js
● Console
console.warn src/main/options.js:42
No parser and no filepath given, using 'babel' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be inferred.
```
[After:](https://dev.azure.com/prettier/prettier/_build/results?buildId=5126&view=logs&j=feaed275-2517-5ad3-d429-3dc96013ea33&t=e2f326fe-3fae-5235-1e33-c604ad7f1ff7&l=31)
```text
PASS tests_integration/__tests__/format.js
```

Fix a warning on test

---

src/language-js/printer-estree.js

Found this can DRY a little bit here, when I was trying to do something else.
Those codes are from #5280 , but `printTypeAnnotation` function already exists #3449 , I guess `printTypeAnnotation` hasn't cover this case yet back then, or just missed that function.
Wow, `utils.js` was first introduced in that PR  :).

A little DRY on `TypeCastExpression` print

---

website/data/languages.yml

Simple addition to Prettier home page for Apex as a supported language.

Add Apex to list of supported languages on home page

---

changelog_unreleased/vue/pr-7479.md
src/language-html/printer-html.js
src/language-js/html-binding.js
tests/html_vue/__snapshots__/jsfmt.spec.js.snap
tests/html_vue/expression-binding.vue

Fixes https://github.com/prettier/prettier/issues/7396

Vue: don't print long single expression of `TemplateLiteral` and `StringLiteral` on new line

---

changelog_unreleased/markdown/pr-7203.md
src/language-markdown/printer-markdown.js
tests/markdown_footnoteDefinition/__snapshots__/jsfmt.spec.js.snap

Markdown: fix incorrect prettification of multi-line markdown footnote

---

changelog_unreleased/handlebars/pr-7552.md
src/language-handlebars/printer-glimmer.js
tests/handlebars-basics/__snapshots__/jsfmt.spec.js.snap
tests/handlebars-basics/component.hbs

Fixes #7550. The code in `printer-glimmer.js` that checks if an `AttrNode` has blank text appears to have a logical error; it checks if the node value's location's start and end columns are the same as a heuristic to determine if there should be no value in the output. But this will be incorrect when the start/end columns are the same but the start/end *lines* are not.
The code was added in #4897 to ensure that empty-value attributes, like the `alt` in `<img alt=""` are preserved (i.e., it prints `<img alt=""` rather than `<img alt`).
But the logical error mentioned above makes it so that if the attribute value has a linebreak and the start/end columns line up, it is stripped, like so:
```hbs
<ul class="abc
def"></ul> 
```
In that ^ example, the AttrNode's value's location has a start …

fix(glimmer): Do not strip AttrNode value when it is not blank

---

changelog_unreleased/angular/pr-6869.md
src/language-html/printer-html.js
tests/html_angular/__snapshots__/jsfmt.spec.js.snap
tests/html_angular/angularjs.html

While there are two syntax incompatibilities ([one-time bindings](https://github.com/prettier/prettier/issues/5466) and [the precedence of `|`](https://github.com/prettier/prettier/issues/5586)) between the expression languages of the old AngularJS and the new Angular, overall the two languages are compatible enough for legacy and hybrid AngularJS-based projects to be able to benefit from using Prettier, which I know from my own experience. An ideal solution would be to add a separate parser for AngularJS, but given the [LTS status](https://docs.angularjs.org/misc/version-support-status) of the framework, such an effort would hardly make sense. On the other hand, unofficially impoving the partial support like I'm doing with this PR is very cheap in terms of effort and code complexity, but …

Rudimentary support for the most used directives of AngularJS 1.x

---

changelog_unreleased/cli/pr-7588.md
src/cli/util.js
tests_integration/__tests__/__snapshots__/ignore-in-subdirectories.js.snap
tests_integration/__tests__/ignore-in-subdirectories.js
tests_integration/cli/ignore-in-subdirectories/.prettierignore
tests_integration/cli/ignore-in-subdirectories/web1/ignore-me/should-ignore.js
tests_integration/cli/ignore-in-subdirectories/web1/ignore-me/subdirectory/should-ignore.js
tests_integration/cli/ignore-in-subdirectories/web1/should-not-ignore.js
tests_integration/cli/ignore-in-subdirectories/web2/should-not-ignore.js

This fixes https://github.com/prettier/prettier/issues/7586. It changes the filename we use in `ignore.filter` to be relative to the location of the `ignore-path` and not the current working directory. 
This is my first exposure to the prettier source code, so please school me! This fixes the issue I have locally, but I have no idea if other changes might be needed or if there are other scenarios I'm not considering here. Thanks!

Respect prettierignore when executed in subdirectories

---

src/language-css/printer-postcss.js

Since wordPart is checked for falsiness on the previous line, it will always evaluate to an empty string. The expression in the parentheses will then evaluate to `"" || ""`, which I assume is not desired.
Ref: https://lgtm.com/projects/g/prettier/prettier/snapshot/ecfc5e9b8320d79ed8a801d811e0a63892b040d0/files/src/printer-postcss.js?sort=name&dir=ASC&mode=heatmap#L468
cc @lydell 

Remove unnecessary expression

---

changelog_unreleased/api/pr-7620.md
docs/api.md
docs/plugins.md
src/cli/util.js
src/index.js
src/language-markdown/embed.js
src/language-markdown/index.js
src/main/options.js
src/main/support.js
src/standalone.js
tests_integration/__tests__/__snapshots__/support-info.js.snap
tests_integration/__tests__/help-options.js
tests_integration/__tests__/support-info.js
website/static/worker.js

closes https://github.com/prettier/prettier/issues/7615

api: remove the version parameter of getSupportInfo

---

package.json
src/common/load-plugins.js
src/config/resolve-config.js
tests_integration/__tests__/__snapshots__/config-invalid.js.snap
yarn.lock

I think `require.resolve` can do the job.
Tests from separate PR https://github.com/prettier/prettier/pull/7517

Remove `resolve` package

---

cspell.json
docs/precommit.md

I am the author of [git-format-staged](https://github.com/hallettj/git-format-staged) which provides another option for running prettier in a pre-commit hook. I believe that git-format-staged is valuable because it operates fundamentally differently compared to other tools that format partially-staged files, and therefore provides a different set of guarantees. This PR documents usage of git-format-staged with prettier in a pre-commit hook, and provides a brief description of its merits.
Should I add an entry to `changelog_unreleased/` for a documentation change?

Add docs on using prettier with git-format-staged in a pre-commit hook

---

azure-pipelines.yml

see https://devblogs.microsoft.com/devops/removing-older-images-in-azure-pipelines-hosted-pools/

azure pipelines: switch to macOS 10.14

---

changelog_unreleased/typescript/pr-7729.md
src/language-js/printer-estree.js
tests/typescript_comments/__snapshots__/jsfmt.spec.js.snap
tests/typescript_comments/type-parameters.ts

Fixes #7574
```ts
// Input
const a: T</* comment */> = 1;
// Prettier stable
Error: Comment "comment" was not printed. Please report this error!
at https://prettier.io/lib/standalone.js:15543:15
at Array.forEach (<anonymous>)
at ensureAllCommentsPrinted (https://prettier.io/lib/standalone.js:15541:17)
at coreFormat (https://prettier.io/lib/standalone.js:15592:5)
at format (https://prettier.io/lib/standalone.js:15832:75)
at formatWithCursor (https://prettier.io/lib/standalone.js:15848:14)
at https://prettier.io/lib/standalone.js:31794:17
at Object.format (https://prettier.io/lib/standalone.js:31802:14)
at formatCode (https://prettier.io/worker.js:234:21)
at handleMessage (https://prettier.io/worker.js:185:18)
// Prettier master
const a: T</* comment */> = 1;
```
**✨[Try the playground for …

TypeScript: Print dangling comment in empty type parameters

---

package.json
yarn.lock

Release log https://github.com/rollup/rollup/releases/tag/v2.0.0
I've checked our [plugins](https://github.com/prettier/prettier/tree/next/scripts/build/rollup-plugins), we are not using those removed hooks.

Update `rollup` to v2

---

changelog_unreleased/typescript/pr-7631.md
src/language-js/postprocess.js
src/language-js/printer-estree.js
tests/typescript_class/__snapshots__/jsfmt.spec.js.snap
tests/typescript_class/standard_private_fields.ts
tests/typescript_export/__snapshots__/jsfmt.spec.js.snap
tests/typescript_export/export-as-ns.ts
tests/typescript_import_export/__snapshots__/jsfmt.spec.js.snap
tests/typescript_import_export/jsfmt.spec.js
tests/typescript_import_export/type-modifier.ts

issue: https://github.com/prettier/prettier/issues/7263
typescript-estree issue: https://github.com/typescript-eslint/typescript-eslint/issues/1436
**✨[Try the playground for this PR](https://deploy-preview-7631--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgMoCOArugE5w7AA6UOdOAxJgJYAmcAMggOYwAWSHFCIBbAEZxSAbho16OSFEwxSRMDAikAFC3ZcovAUNETSASkpz59fs0wA6Jm049+OALw5dLg-xm16AF9ZALo4YnRUTC0IfklBdCgATwtqUOtyGCJSWlsHJz1XPg93T1i+SUdvfUN-eWCoQJAAGhAIAAcYZmhMZFAyUggAdwAFMgRelEih9CTe1rFSdDAAazgYPHbl5gNkFSI4Vr4YEVQAdT5meEwtsDg8CavmADcrpORwbBaQHcxJGBGS24InQyAAZpE-q0AFaYAAeACElqt1nh0CJODs4ODIYcQLC4XgdtxUHAAIpEWLYpAQqJ4rakP6kD4wJLtOCYMCkZidb7tbmwM5sfjIAAcAAZWvyIH8zkt2h9+RzJM9sa1iFTAR1JiAsABaKBwODsVjfcjEZjkQHoYGgmm41p-ETMPaqPEsAykilUnF01owdBiIWsEVIABM-qWzFQxIAwhARCCPhyAKzfIh-AAqgcmtKhIGeBwA …

Partial support for TypeScript 3.8 (private fields, import/export type modifier)

---

yarn.lock

`yaml` is in `dependencies` of `yaml-unist-parser`, how do we keep it up to date?

Update `yaml` to v1.8.2

---

docs/rationale.md
website/versioned_docs/version-stable/rationale.md

The italic Markdown formatting is included in the [automatically generated ID](https://prettier.io/docs/en/rationale.html#what-prettier-is-_not_-concerned-about), so it must be present in the references as well.

Fix broken HTML anchor in the Rationale documentation

---

tests/typescript/custom/abstract/jsfmt.spec.js
tests_config/run_spec.js

~Refactor disabled `babel-ts` tests to a better way to manage.~
~Seems there is already a fixture fixed see https://github.com/prettier/prettier/commit/95edf2ee7b7b7d8193070a9fce8d845d20858a0d~
Run verify test on disabled `babel-ts` tests, make sure they throws `SyntaxError`

Run verify test on  disabled `babel-ts` tests

---

changelog_unreleased/typescript/pr-7631.md
package.json
tests/typescript_import_export/__snapshots__/jsfmt.spec.js.snap
tests/typescript_import_export/jsfmt.spec.js
tests/typescript_import_export/type-modifier.ts
yarn.lock

[Babel 7.9.0](https://babeljs.io/blog/2020/03/16/7.9.0) has been released! It supports TypeScript 3.8 type only import/export.
~~But, we cannot update snapshots now, because there is https://github.com/babel/babel/issues/11291. We need to wait the issue is fixed.~~

Support type only import/export via `babel-ts`

---

scripts/build/config.js

Tweak build script to not corrupt import-fresh module

---

website/package.json
website/yarn.lock

Remove codemirror from website/package.json as Playground loads it from CDN

---

changelog_unreleased/typescript/pr-7798.md
cspell.json
src/common/util.js
src/language-js/comments.js
src/language-js/postprocess.js
src/language-js/printer-estree.js
src/main/comments.js
src/main/core.js
tests/typescript_union/__snapshots__/jsfmt.spec.js.snap
tests/typescript_union/prettier-ignore-nested-unions.ts
tests/typescript_union/prettier-ignore.ts

fix prettier-ignore in union types

---

changelog_unreleased/typescript/pr-7836.md
src/language-js/printer-estree.js
tests/typescript_error_recovery/__snapshots__/jsfmt.spec.js.snap
tests/typescript_error_recovery/index-signature.ts

Fixes https://github.com/prettier/prettier/issues/7834. Specifically, it now outputs the trailing comma only when there's multiple parameters. In the usual (non-error) case, it treats it like a computed property name and therefore omits the trailing comma.
See https://github.com/prettier/prettier/issues/7224 and https://github.com/prettier/prettier/pull/7228 for some context.

TypeScript: avoid trailing commas on index signatures with only one parameter

---

src/main/options.js

Just microrefactoring.
- (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.

Refactor inferParser to extract interpreter only once

---

changelog_unreleased/javascript/pr-7842.md
src/language-js/embed.js
tests/multiparser_js_css/__snapshots__/jsfmt.spec.js.snap
tests/multiparser_js_css/colons-after-substitutions.js

fixes https://github.com/prettier/prettier/issues/7826
The solution is pretty dirty, but hopefully it will do for now.

fix formatting of pseudo-elements and pseudo-classes in styled-component

---

changelog_unreleased/html/pr-7867.md
src/language-html/printer-html.js
tests/html_prettier_ignore/__snapshots__/jsfmt.spec.js.snap
tests_config/run_spec.js

Fix ignored element print

---

.github/workflows/dev-test.yml
.github/workflows/prod-test.yml
jest.config.js

- Set `jest` verbose to false by default
- Correct `doc-debug.js` path
- Remove outdated ignore patterns
- Exclude Node.js 13 on macos

Tweak test and CI configs

---

changelog_unreleased/javascript/pr-7877.md
src/language-js/printer-estree.js
tests/jsx_ignore/__snapshots__/jsfmt.spec.js.snap
tests/line_suffix_boundary/__snapshots__/jsfmt.spec.js.snap
tests_config/run_spec.js

Fix prettier-ignore inside JSX

---

cspell.json
docs/plugins.md

Just adding a plugin I wrote to organize tyepscript imports to the list of community plugins cause I find it quite handy and want other people to be able to discover it and benefit from it as well. Not sure whether this list is open to additions but I hope so!

docs: add prettier-plugin-organize-imports to list of community plugins

---

changelog_unreleased/flow/pr-7892.md
src/language-js/printer-estree.js
tests/flow_object_inexact/__snapshots__/jsfmt.spec.js.snap
tests/flow_object_inexact/comments.js

Fixes #7718
The following comments cannot be formatted in this PR:
**Input:**
```js
type Foo = {
// comment0
...,
// comment1
};
```
**Output:**
```js
type Foo = {
// comment0
// comment1
...,
};
```
**Expected:**
```js
type Foo = {
// comment0
...,
// comment1
};
```
It is hard to format this because there was not much information about inexact in the AST. But, since this is an edge case, I don't think this is a problem.

Flow: Print dangling comments for empty inexact object type

---

changelog_unreleased/javascript/pr-7883.md
src/language-css/printer-postcss.js
src/language-js/embed.js
tests/multiparser_js_css/__snapshots__/jsfmt.spec.js.snap
tests/multiparser_js_css/colons-after-substitutions2.js
tests/multiparser_js_css/var.js

use scss parser for css-in-js

---

docs/browser.md
docs/ignore.md
docs/options.md
website/versioned_docs/version-stable/browser.md
website/versioned_docs/version-stable/ignore.md
website/versioned_docs/version-stable/options.md

After noticing a broken link while browsing the docs I checked out the code and found a couple more, so I decided to open a PR 😉.
___

Fix broken documentation links

---

changelog_unreleased/flow/pr-7923.md
src/language-js/printer-estree.js
tests/flow_object_inexact/__snapshots__/jsfmt.spec.js.snap
tests/flow_object_inexact/comments.js
tests/flow_object_inexact/jsfmt.spec.js
tests/flow_object_inexact/test.js

Fixes #7920  - do not add comma for explicit inexact object with indexer property - for all cases. Previously it was removed only when type had some simple "properties" field defined.
In tests, the main factor that it works is that comma being shown or hidden behaves the same for both the simple/main case
```
type T = {
a: number,
...,
}
```
and for object with indexer property or without properties.

Fix #7920 - do not add comma for explicit inexact object with indexer property

---

changelog_unreleased/html/pr-7916.md
src/language-html/utils.js
tests/html_basics/__snapshots__/jsfmt.spec.js.snap
tests/html_basics/with-colon.html

Format script content inside HTML tag with colon

---

src/language-css/utils.js
tests_config/run_spec.js

Fix `css_atrule/include.css` second format.
I don't really understand this regex, but space after `:` should be optional.
It's added in https://github.com/prettier/prettier/pull/4317/files#diff-29bcb0b461c4ae51930e975e53edfdd9L481

Update `isSCSS` test regex

---

src/common/load-plugins.js
src/common/resolve.js
src/config/resolve-config.js

workaround for require.resolve in prettier-vscode

---

website/pages/playground-redirect.html

https://community.netlify.com/t/changes-coming-to-netlify-site-urls/8918
> Starting April 14, 2020, sites without a custom domain are being moved from site-name.netlify.com to site-name.netlify.app . New websites will also have URLs ending with netlify.app by default. Custom domains set on old, or new, sites will behave in the same way as before!

change playground redirect to use *.netlify.app domains

---

tests_integration/__tests__/check.js
tests_integration/__tests__/list-different.js
tests_integration/runPrettier.js

Seems like GitHub Actions have the `CI` environment variable set now whereas some tests (added in #5804) depended on this variable.

An attempt to fix unexpected GitHub Actions failures

---

changelog_unreleased/less/pr-7984.md
src/language-css/parser-postcss.js
tests/css_less/__snapshots__/jsfmt.spec.js.snap
tests/css_less/less.less

Fix less `:extend` format

---

.github/workflows/dev-test.yml
scripts/test-dist.js

I ran several tests (only the slowest job and a normal windows job) with different `maxWorkers` on my fork
job | duration
:--|--:
[max-workers-1](https://github.com/fisker/prettier/actions/runs/73379503) | 22m 50s 
[max-workers-2](https://github.com/fisker/prettier/actions/runs/73381299) | 14m 10s
[max-workers-3](https://github.com/fisker/prettier/actions/runs/73379954) | 16m 4s
[max-workers-4(current)](https://github.com/fisker/prettier/actions/runs/73388980) | 17m 30s
[max-workers-5](https://github.com/fisker/prettier/actions/runs/73380194) |  22m 56s
[max-workers-6](https://github.com/fisker/prettier/actions/runs/73380357) | 17m 0s
[max-workers-7](https://github.com/fisker/prettier/actions/runs/73393607) | 17m 5s
I also tried increase memory, seems not helping
job | duration
:--|--: …

Adjust `maxWorkers` for `jest`

---

changelog_unreleased/graphql/pr-8007.md
src/language-graphql/printer-graphql.js
tests/graphql_interface/__snapshots__/jsfmt.spec.js.snap
tests/graphql_interface/interface.graphql

`graphql`: Allow interfaces to implement other interfaces

---

.github/workflows/dev-test.yml
.github/workflows/lint.yml
.github/workflows/prod-test.yml

This weekend I want to release 2.0.5 from a branch. It will be based on 2.0.4 and include only https://github.com/prettier/prettier/pull/7984 (a 2.0 regression).

Enable GitHub Actions for a patch-release branch

---

cspell.json
src/language-yaml/index.js
tests/yaml_ansible/__snapshots__/jsfmt.spec.js.snap
tests/yaml_ansible/jsfmt.spec.js
tests/yaml_ansible/playbook.yml
tests_integration/__tests__/__snapshots__/support-info.js.snap

The Ansible[1] extension define a new language for yaml files that describe
ansible playbooks and because of that is not possible use the prettier
extension with ansible files.
1 - https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible

Use yaml formatter to format ansible files

---

.github/workflows/dev-test.yml

Possible regression  https://github.com/facebook/jest/issues/9457#issuecomment-612497425
Switch `jest` back to `v24` for coverage collect job, ~8 mins vs ~15 mins.
Finally get everything back normal.

Use `jest@24` to collect coverage

---

.github/workflows/prod-test.yml
cspell.json

The build cache system seems [designed to speed up CI build](https://github.com/prettier/prettier/pull/4693), but lost in last CI setup.
With cache, ~12s https://github.com/prettier/prettier/pull/8027/checks?check_run_id=580817579#step:7:22
For reference: this caching was implemented in https://github.com/prettier/prettier/pull/4693

Cache CI build result

---

.github/workflows/prod-test.yml

Merge `standalone-test` and `production-test`

Simplify production tests

---

package.json

refs:
- [old azure pipeline settings](https://github.com/prettier/prettier/commit/34115cbd3c7101a6be733e8d3288fe46d0eb10f5#diff-fec826feae04e51c0d94076385408bdcL90)
- [mistake](https://github.com/prettier/prettier/pull/7431/files#diff-2d1d1197987e7769ed317c9ef37ea11dR110)

Correct `standalone test` environment variable

---

website/playground/panels.js

[An example of the current wrong rendering](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBGAOlATCANCCABxgEtoBnZUAQwCdaIB3ABToUpWoBtHqBPSvgBGtamADWcGAGVCYklADmyGLQCucfAAsYAWy4B1LSXjk5YONPYmSANxN9k4coJALycWjGajFu6sgAZtwe+ABW5AAeAEKiElLS1LpwADIKcEEhmiARkdIKilxwAIpqEPCZXKEgcrQetE5C1EJwXHg1tAowBiQAJjBayAAcAAz4hAweBqKEThNw9bYZ+ACOZfA+RBwg1OQAtFBwcL3H7bRwayTnPtR+AUjBVdkeuiQq6s8FRaXlGQ9Z+BgzR6-UGSCwgNEJC4BQAwhBdP4nAsAKztNQeAAqzQ4j2qtg0AEkoCdYNIwJ1iABBEnSGB8IqVaqiJSWIFeZBjEAsxRwACiJOQWAAvsKgA).

playground: fix how ranges are rendered

---

changelog_unreleased/cli/pr-8098.md
src/cli/expand-patterns.js
src/cli/util.js
tests_integration/__tests__/__snapshots__/ignore-emoji.js.snap
tests_integration/__tests__/ignore-emoji.js
tests_integration/cli/ignore-emoji/.prettierignore
tests_integration/cli/ignore-emoji/ignored/1.js
tests_integration/cli/ignore-emoji/ignored/中文.js
tests_integration/cli/ignore-emoji/ignored/😁.js
tests_integration/cli/ignore-emoji/not-ignored.js

Fixes #7899
Not only filename contains emoji, but also CJK characters are not ignored.
We are passing `a\中文.js` to ignore, and here 
https://github.com/kaelzhang/node-ignore/blob/56976cef6d5ec0e5651910801669f9aa3daa8120/index.js#L452-L453
passed, so `\` won't replace to `a/中文.js`, this file will not ignored.

Fix ignore bug on windows

---

.github/workflows/prod-test.yml
scripts/build/build.js

Finally found the reason, 
We write `.cache/manifest.json` first, then copy files to `.cache/files/`
If `.cache` is missing, we try to write `.cache/manifest.json`, it will fail and continue, then we copy js files to `.cache/files/`, this will success, so we missed the `manifest.json` in cache.
With new logic, we copy js files to `.cache/files/` first, in this step, the `.cache` dir will be created, then write `.cache/manifest.json` won't fail.
Test steps:
Test result: 
As expected.
---- 

Build: Fix cache logic

---

.eslintrc.yml
package.json
yarn.lock

`unicorn/prefer-set-has` seems a little bit annoying , disabling for now.
Issue https://github.com/sindresorhus/eslint-plugin-unicorn/issues/696

Bump `eslint-plugin-unicorn` to v19

---

docs/plugins.md

`prettier-plugin-pkg` for `package.json`
`prettier-plugin-sh` for shell scripts

docs: add two plugins `pkg` and `sh`

---

.github/workflows/prod-test.yml
scripts/build/build.js

I  updated  [cache version](https://github.com/prettier/prettier/blob/736db9b0db4d5698f8ad8260a35f115aac2045ae/scripts/build/build.js#L24) in https://github.com/prettier/prettier/pull/8119 , like  I  said https://github.com/prettier/prettier/pull/8027#discussion_r407215287 , we  are  not able to  update cache  unless `yarn.lock` changes, now  `scripts/build/` changes updates the cache too.

Update CI  cache  key

---

changelog_unreleased/javascript/pr-8255.md
src/language-css/printer-postcss.js
tests/js/multiparser-css/__snapshots__/jsfmt.spec.js.snap
tests/js/multiparser-css/var.js

fixes #5465 
fixes #8250
I feel like this fix might break some other cases where whitespace is actually needed. Please help me find them.

Fix extra space after minus in CSS-in-JS

---

changelog_unreleased/html/pr-8275.md
src/language-html/constants.evaluate.js
tests/html/tags/__snapshots__/jsfmt.spec.js.snap
tests/html/tags/option.html

Treat <select> and <optgroup> as inline-block for whitespace sensitivity

---

package.json

I remember I did move it from `devDependencies` to `dependencies`, somehow added back when rebasing.

Remove duplicated `outdent` in package.json

---

tests_config/run_spec.js

Test: "Expected" and "Received" are mixed up in ast compare tests

---

src/language-css/clean.js
src/language-css/loc.js
src/language-css/parser-postcss.js
src/language-css/printer-postcss.js

Once all the nodes have the correct location data (`selector-*` and `media-*` are TBD), it'll be possible to use Prettier's comment attachment logic for CSS like discussed in #3905. Here's the plan:
- Have correct location data in the AST.
- Preparse the input with a simple parser (similar to what we already have in `language-css/loc.js`, see `replaceQuotesInInlineComments` there) and collect comments.
- Remove the comments from the input, so that the `postcss-*` parsers don't have to deal with them.
- Use the comment attachment logic like it's done for JS.
A big problem here is that it's not always possible to remove a comment safely (e.g. [`div/**/span`](https://mobile.twitter.com/thorn0/status/1257251001448398854)), so some of them will have to stay and be handled the way they're …

refactor(css): calculate correct location data for value-* nodes

---

website/playground/VersionLink.js

This way it should be a bit easier not to get lost comparing the output of pull requests with the release.

Playground: add Prettier version to document title

---

website/static/worker.js

https://prettier.io/playground doesn't let select `glimmer` parser (for handlebars) because it is still experimental. With this PR, I propose to enable glimmer parser on the playground. It would simplify the bug reporting on that parser.
AFAICT glimmer is the only parser to be experimental.

Enable glimmer printer in the playground

---

website/playground/Playground.js

Old issues has `parser=babylon` in url, every time people click it, has to change the parser to `babel` manually.
https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACVkoGcaoB6oC8qADANwA6U6V6A9AFSoCWOAhlAEYCuANiwHMoEAE5wWAM1QM6qOrIAmcHgIxss4sNxFjYvAJ6phuGCOYCBcMQtqTUAClPc4ASlTBb6PJWqoAviAANCAQAA4wzNBYyKDqMMgSbLwawZwibGAA1nAwAMqhGcxQAshOcMEKEGAJSSkgAFZYeABC6Vk5uWwAtnAAMkVwNcnlIdwwoWMATEN1BSIaIsggnGyc+rzQQSChZrAA6swKMAAWyAAcJMEaXcylIs5XRQK8cACK3BDwMyMwqwdHpyQk2CpjYzF4TwAwhAul02EthFBBsFuBoACqraJIRLDPx+IA
https://deploy-preview-8382--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEACVkoGcaoB6oC8qADANwA6U6V6A9AFSoCWOAhlAEYCuANiwHMoEAE5wWAM1QM6qOrIAmcHgIxss4sNxFjYvAJ6phuGCOYCBcMQtqTUAClPc4ASlTBb6PJWqoAviAANCAQAA4wzNBYyKDqMMgSbLwawZwibGAA1nAwAMqhGcxQAshOcMEKEGAJSSkgAFZYeABC6Vk5uWwAtnAAMkVwNcnlI …

Playground: Redirect `babylon` parser to `babel`

---

docs/plugins.md

The current documentation doesn't give good guidance about how to use the `embed` function or what the call chain is. This PR explains in more detail.

Clarified usage of `embed`

---

docs/browser.md
package.json

Closes #7557
When this [field](https://docs.npmjs.com/files/package.json#browser) is specified, `import prettier from "prettier";` and `require("prettier")` ["just works" with webpack](https://webpack.js.org/configuration/resolve/#resolvealiasfields), [Parcel](https://parceljs.org/module_resolution.html#package.json-%60browser%60-field) and probably with other bundlers. It's important for plugins because otherwise it's not clear what they should import to access Prettier's API. E.g. this simple change would make `prettier-plugin-csharp` web-compatible.
Theoretically, this might break someone's setup if they use webpack to bundle Prettier as part of non-web code, but as it's described in #7557 and https://github.com/warrenseine/prettier-plugin-csharp/issues/39, Prettier's Node bundle is …

Add the browser and unpkg field to package.json

---

changelog_unreleased/html/pr-8173.md
src/language-html/printer-html.js
tests/html/script/__snapshots__/jsfmt.spec.js.snap
tests/html/script/babel.html

Ref: https://github.com/babel/babel/pull/11466

Support babel `data-type="module"`

---

changelog_unreleased/api/pr-8390.md
src/main/support.js
tests_integration/__tests__/__snapshots__/plugin-options-string.js.snap
tests_integration/__tests__/__snapshots__/plugin-options.js.snap
tests_integration/__tests__/plugin-options.js

Add plugins' parsers to the `parser` option

---

scripts/build/config.js

Ref: https://github.com/prettier/prettier/pull/8367#issuecomment-633497645
Local build and compared, nothing changes.

Build: Fix `@rollup/plugin-commonjs` warning

---

changelog_unreleased/typescript/pr-8422.md
src/language-js/needs-parens.js
src/language-js/printer-estree.js
tests/js/directives/__snapshots__/jsfmt.spec.js.snap
tests/js/directives/issue-7346.js

Removes the workaround added in #2107.
Closes #7346 as it works as intended.
Thanks to @bakkot for the [comment](https://github.com/prettier/prettier/issues/7346#issuecomment-574823604) that I used for the changelog entry.

fix(typescript): remove now-unneeded workaround for directives

---

changelog_unreleased/javascript/pr-8431.md
src/language-js/parser-babel.js
tests/js/private-in/__snapshots__/jsfmt.spec.js.snap
tests/js/private-in/jsfmt.spec.js
tests/js/private-in/private-in.js

- https://babeljs.io/blog/2020/05/25/7.10.0#private-fields-in-in-11372-https-githubcom-babel-babel-pull-11372
- https://github.com/tc39/proposal-private-fields-in-in/blob/master/README.md

JavaScript: Support Babel 7.10 private field in `in`

---

tests_config/run_spec.js
tests_config/utils/compose-options-for-snapshot.js
tests_config/utils/consistent-end-of-line.js
tests_config/utils/create-snapshot.js
tests_config/utils/stringify-options-for-title.js
tests_config/utils/visualize-end-of-line.js

~`composeOptionsForSnapshot` function is from #8408~ Didn't notice it keeps ranges.

Test: extract code to utils

---

src/language-js/print/misc.js
src/language-js/print/module.js
src/language-js/printer-estree.js

Add `printModuleSpecifiers` to print import/export 'specifiers'
Add `printModuleSource` to print import/export 'source'
There still some differences between import and export 'specifiers'
- `printModuleSpecifiers` handles empty `specifiers` for `export`, but not for `import`, a little difference between current implementation.
- leading space handled differently, this effect comment print.

Refactor: simplify import/export print

---

docs/webstorm.md

The `Alt` key on Mac keyboards is `Option`

Change Alt to Opt in MacOS shortcut

---

changelog_unreleased/javascript/pr-8431.md

This is a tiny fix for a changelog. `proposal-private-fields-in-in` is Stage-2 in now. See https://github.com/tc39/proposal-private-fields-in-in/commit/4d9da6aa3c5ee617d0d7f6d16a4a4965b8048c28

Changelog: Fix Stage-1 => Stage-2

---

changelog_unreleased/javascript/pr-8476.md
src/document/doc-utils.js
src/language-html/printer-html.js
src/language-html/utils.js
src/language-js/printer-estree.js
src/main/comments.js
tests/js/babel-plugins/__snapshots__/jsfmt.spec.js.snap
tests/js/binary-expressions/__snapshots__/jsfmt.spec.js.snap
tests/js/binary-expressions/comment.js
tests/js/comments-pipeline-own-line/__snapshots__/jsfmt.spec.js.snap
tests/js/comments-pipeline-own-line/pipeline_own_line.js
tests/js/comments/__snapshots__/jsfmt.spec.js.snap

Fixes #8451
This PR seems to work fine but the doc is transformed so it maybe a dirty way...

JavaScript: Fix indentation for binary expressions with trailing comments

---

src/document/doc-utils.js
src/language-markdown/printer-markdown.js
tests_integration/__tests__/normalize-doc.js

Using `normalizeParts` from utils in `printer-markdown` seems to work fine.

Refactor: Use `normalizeParts` from `document/utils` in `printer-markdown`

---

changelog_unreleased/css/pr-8535.md
src/language-css/printer-postcss.js
tests/css/character-escaping/__snapshots__/jsfmt.spec.js.snap
tests/css/character-escaping/character_escaping.css

Potentially fixes https://github.com/prettier/prettier/issues/8512. I'm guessing however that this is at its core an issue in the ast parser, see https://github.com/prettier/prettier/issues/8512#issuecomment-641322576
**Prettier pr-8535**
[Playground link](https://deploy-preview-8535--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEA6A5gJwJYBMAEwAOlPvlngLTwC2ADgDYCG8lmEA7gM5IllkBtdh0oBGSgAYJRIkikBdfEwCuMCAG4SAXxAAaEBDoxs0LslBNMwgAqWEZlEwYcmATzP6ARpiZgA1nAwAMp0vthQ6MgwmMpw+nA0nnC4uMkAMkwRykzocABiEJg0LMYRyCAqanogABYwNAwA6jXY8FyhYHBB9q3YAG6truVgXB4g4VxwmDDWPujFyABmTpP6AFZcAB4AQj7+gUFMNHBp4XBLK3EgG5tB4egMcACKyhDwFwyrIKGYk5jDo2qdBwsEaeBgNWQAA4JPpgRBJo0fHRysC4H8+ud9ABHV7wWaGBwVLiUKBwZLJaqYOC47DU2Y5BZIZafK6TGjYKIxN …

Fix: Incorrect whitespace added after escaped colon in css line name

---

scripts/build/build.js
scripts/build/config.js

Fix encoding in postcss-parser build
The encoding in parser-postcss build makes it not possible to load it inside a chrome extension. 
Related issues:
- Fixes: https://github.com/prettier/prettier-chrome-extension/issues/203
- https://github.com/webpack-contrib/terser-webpack-plugin/issues/107

Fix encoding in postcss-parser build

---

changelog_unreleased/javascript/pr-8354.md
src/language-js/printer-estree.js
tests/js/test-declarations/__snapshots__/jsfmt.spec.js.snap
tests/js/test-declarations/jest-each-template-string.js
tests/js/test-declarations/jest-each.js

Fixes #7653
This adds a verification in the "ArrayPattern" in `printer-estree.js` and updates `shouldBreak` variable if a Jest Each Template Literal is identified.
-----------

Fix: don't wrap arrays in `test.each` template strings

---

changelog_unreleased/css/pr-8567.md
src/language-css/printer-postcss.js
tests/scss/scss/__snapshots__/jsfmt.spec.js.snap
tests/scss/scss/arbitrary-arguments.scss

Fixes https://github.com/prettier/prettier/issues/7997

Fix: [Sass] Unexpectedly add extra space after function when passing arbitrary arguments 

---

src/common/get-file-info.js
tests_integration/__tests__/__snapshots__/file-info.js.snap
tests_integration/__tests__/file-info.js
tests_integration/cli/with-resolve-config/.prettierrc

`inferredParser` is useless for ignored files.

Do not inferParser for ignored files

---

package.json
yarn.lock

We should not need this anymore.
Anybody send coverage from local?

Remove `codecov` from `package.json`

---

changelog_unreleased/css/pr-8567.md
src/language-css/parser-postcss.js
tests/scss/scss/__snapshots__/jsfmt.spec.js.snap
tests/scss/scss/arbitrary-arguments.scss
tests/scss/scss/inline_arbitrary_arguments.scss

Fixes: https://github.com/prettier/prettier/issues/8565
Not sure if this warrants a changelog ? Might just clutter it ?

Fix: Prettier breaks code when inline number lists are used as arbitrary arguments [SCSS]

---

changelog_unreleased/api/pr-8551.md
src/common/get-file-info.js
tests_integration/__tests__/file-info.js
tests_integration/cli/ignore-and-config/config-dir/.prettierrc

Ref https://github.com/prettier/prettier/pull/8546#discussion_r439279587

Fix: resolving to incorrect config in `getFileInfo()`

---

changelog_unreleased/javascript/pr-8592.md
src/language-js/printer-estree.js
tests/js/conditional/__snapshots__/jsfmt.spec.js.snap
tests/js/conditional/comments.js
tests/typescript/conditional-types/__snapshots__/jsfmt.spec.js.snap
tests/typescript/conditional-types/comments.ts

JavaScript: Break ternary expressions containing a multi-line block comment

---

package.json
src/language-handlebars/utils.js
yarn.lock

Missing elements `basefont`, `bgsound`, `command`, `frame`, `image`, `isindex`, `keygen`, `menuitem`, `nextid`

Use `html-void-elements` for more completed list

---

changelog_unreleased/html/pr-8275.md
src/language-html/constants.evaluate.js
tests/html/tags/__snapshots__/jsfmt.spec.js.snap

Related: [`Treat <select> and <optgroup> as inline-block for whitespace sensitivity`](https://github.com/prettier/prettier/pull/8275)
I think it's safe to treat `option` and `optgroup` as `block`.
This is how `chrome` do https://chromium.googlesource.com/chromium/blink/+/refs/heads/master/Source/core/css/html.css

Treat <option> and <optgroup> as block

---

.pre-commit-hooks.yaml

Currently, the pre-commit hook will output all files that prettier analyzes.
The changed lines are highlighted in the terminal, but this highlighting is not always successful (e.g. we have seen the highlighting disappear when running inside Jenkins)
This sets prettier (when running within pre-commit) to only output changed files

fix: configure pre-commit hook to only output changed files

---

changelog_unreleased/handlebars/pr-8634.md
src/language-handlebars/preprocess.js
src/language-handlebars/printer-glimmer.js
tests/handlebars/mustache-statement/__snapshots__/jsfmt.spec.js.snap
tests/handlebars/mustache-statement/escaped.hbs

In handlebars, it is possible to escape a mustache with a backslash. [See handelbars documentation here.](https://handlebarsjs.com/guide/expressions.html#escaping-handlebars-expressions)
This PR propose to add the support for this feature.
This would close https://github.com/prettier/prettier/issues/8633
Initial report: https://github.com/jgwhite/prettier/issues/1#issuecomment-646227623
This PR would introduce a new file: `src/language-handlebars/preprocess.js`. It is present to make an adjustement to the AST produced by Glimmer parser.
Indeed, given that template:
```hbs
a non-escaped mustache: \\\{{helper}}
```
Glimmer parser will produce two nodes for the template body:
- a TextNode where `node.chars === "a non-escaped mustache: \\\\"` (note the backslash escaping here, so it is …

handlebars: Support escaping a mustache with a backslash

---

changelog_unreleased/handlebars/pr-8593.md
src/language-handlebars/printer-glimmer.js
tests/handlebars/mustache-statement/__snapshots__/jsfmt.spec.js.snap
tests/handlebars/mustache-statement/basics.hbs

Resolves:
#8584 
https://github.com/jgwhite/prettier/issues/1#issuecomment-607273019
https://github.com/jgwhite/prettier/issues/1#issuecomment-630412651

Handlebars: Fix incorrect classic component syntax formatting

---

changelog_unreleased/api/pr-8591.md
package.json
src/config/find-project-root.js
src/config/resolve-config-editorconfig.js
yarn.lock

Fixes #5705
`find-project-root` package can't use `Infinity` as `maxDepth`, so I wrote a simple one.

Fix resolve EditorConfig for files in deep directory

---

src/language-js/print/ternary.js
src/language-js/printer-estree.js
src/language-js/utils.js

Refactor: Extract long function `printTernaryOperator` and related utils to the other file

---

website/static/overrides.css

https://github.com/prettier/prettier/issues/8509
Using different font stack for website. `Apple SD Gothic Neo` and `AppleSDGothicNeo` are for the Korean language. It's often a bad idea to use such fonts for English.

feat: use different font stack for website

---

src/language-js/print/ternary.js

Fix broken JSDoc type comments for `printTernaryOperator`

---

changelog_unreleased/css/pr-8545.md
src/language-css/parser-postcss.js
tests/css/atrule/__snapshots__/jsfmt.spec.js.snap
tests/css/atrule/supports.css

Fixes https://github.com/prettier/prettier/issues/8409.
Parses `<complex-selector>` in `@supports selector(<complex-selector>)` as a selector.

Fix: at rule supports selector

---

docs/precommit.md

Unfortunately, the precise-commits repo does not seem to have been maintained for the past two years:
- [most recent commit](https://github.com/nrwl/precise-commits/commit/803871289f59e2c326b4d20c08e6b1b862c0408e) to master was on Mar 27, 2018
- [most recent release](https://github.com/nrwl/precise-commits/releases/tag/v1.0.2) was on Feb 16, 2018
- [most recently closed issue](https://github.com/nrwl/precise-commits/issues/19) was closed on Jul 29, 2018
I have [requested](https://github.com/nrwl/precise-commits/issues/58) archiving.
This is sad. I could think of several use-cases where a tool like `precise-commits` could be very useful, especially for already matured projects that are trying to onboard linting and prettifying. …

Remove the precise-commits section

---

src/common/util.js

[`isWithinParentArrayProperty` function](https://github.com/prettier/prettier/blob/b0fbd726888de44c9e5e2157a4032ea5bd1272e2/src/common/util.js#L636) is also not used, not sure if we want remove it.

Remove dead code

---

src/language-js/embed.js

Use `.map` instead of `.forEach + .push`

Simplify `escapeTemplateCharacters`

---

src/language-yaml/index.js
tests/yaml/home-assistant/__snapshots__/jsfmt.spec.js.snap
tests/yaml/home-assistant/configuration.yml
tests/yaml/home-assistant/jsfmt.spec.js
tests_integration/__tests__/__snapshots__/support-info.js.snap

This PR adds a custom language identifier for the Home Assistant language/vscode extension, as documented in:
<https://github.com/prettier/prettier-vscode/wiki/Custom-File-Extension-Configuration#custom-language-identifier>
The Home Assistant extension can be found here: https://marketplace.visualstudio.com/items?itemName=keesschollaart.vscode-home-assistant
Registers `home-assistant` in its language ID, however, it is YAML.

Add Home Assistant vscode language ID as YAML

---

src/language-js/parser-angular.js
src/language-js/parser-babel.js
src/language-js/parser-flow.js
src/language-js/parser-typescript.js

`loc.js` has extra function `composeLoc`, this not public api, should not add to parser.

Do not expose `composeLoc`

---

docs/cli.md
src/cli/util.js
tests_integration/__tests__/__snapshots__/check.js.snap
tests_integration/__tests__/__snapshots__/infer-parser.js.snap
tests_integration/__tests__/__snapshots__/piped-output.js.snap

When `prettier --check` is run by a script that combines the output from dozens of separate linters, any progress output like “Checking formatting...” and “All matched files use Prettier code style!” is just noise that makes it harder to see whether there are real errors.  Bump the loglevel of issues reported by `--check` from `log` to `warn` so that the noise can be selectively silenced with `--loglevel=warn`.
Alternative to #8694 suggested by @thorn0.

Bump loglevel of issues reported by --check to warn

---

changelog_unreleased/flow/pr-8768.md
src/language-js/printer-estree.js
tests/flow/enums/__snapshots__/jsfmt.spec.js.snap

This is a bug fix (missed this during initial support). Like function declarations and class declarations, Flow Enum declarations should not be trailed by a semicolon.

When default exporting a Flow Enum, do not append semicolon

---

jest.config.js
package.json

Make `test:dist-standalone` easier to test subset of tests.
Before, if I want run test only on vue files `yarn test:dist-standalone tests/vue/` won't work, it will be `cross-env NODE_ENV=production TEST_STANDALONE=1 jest tests/ tests/vue/`

Update `test:dist-standalone` script

---

cspell.json
docs/editors.md
website/data/editors.yml

I am the maintainer of the Emacs package [Apheleia](https://github.com/raxod502/apheleia) which allows users to apply code formatters asychronously on save without (for the most part) moving the cursor when code is reformatted. Prettier is supported out of the box. This pull request adds Apheleia to the list of suggested Emacs plugins that have support for Prettier.

Mention Apheleia in list of Emacs plugins

---

scripts/build/build.js
scripts/build/bundler.js

There is a warning info during build, introduced in #8797
https://github.com/prettier/prettier/runs/888536756#step:6:7

Build: Avoid `PREFER_NAMED_EXPORTS` warning

---

changelog_unreleased/cli/pr-8586.md
src/cli/util.js
tests_integration/__tests__/__snapshots__/file-info.js.snap
tests_integration/__tests__/file-info.js

Fix for #8586, I don't know we have `--no-config`

Fix cli `--file-info` bug (part 2)

---

changelog_unreleased/cli/pr-8833.md
docs/cli.md
src/cli/constant.js
tests_integration/__tests__/__snapshots__/early-exit.js.snap
tests_integration/__tests__/__snapshots__/help-options.js.snap
tests_integration/__tests__/__snapshots__/write.js.snap
tests_integration/__tests__/write.js

CLI: Add `-w` alias for `--write` option

---

changelog_unreleased/vue/pr-8839.md
src/language-html/printer-html.js
tests/vue/vue/__snapshots__/jsfmt.spec.js.snap
tests/vue/vue/attributes.vue

fix(vue): named slots shorthand value is not formatted

---

src/language-html/printer-html.js

These ternary are nested too deep, hard to read. 

Style: improve html printer readability

---

changelog_unreleased/typescript/pr-8885.md
src/language-js/printer-estree.js
tests/misc/typescript-babel-only/__snapshots__/jsfmt.spec.js.snap
tests/misc/typescript-babel-only/jsfmt.spec.js
tests/misc/typescript-babel-only/tuple-labeled.ts

Fixes #8883
Include changes from #8869, should merge it first.

Support `babel-ts` AST type `TSNamedTupleMember`

---

changelog_unreleased/javascript/pr-8901.md
src/language-js/clean.js
src/language-js/parser-babel.js
src/language-js/printer-estree.js
src/language-js/utils.js
tests/js/babel-plugins/__snapshots__/jsfmt.spec.js.snap
tests/js/babel-plugins/decimal.js
tests/misc/errors/js/__snapshots__/jsfmt.spec.js.snap
tests/misc/errors/js/jsfmt.spec.js

[`Decimal Proposal`](https://github.com/tc39/proposal-decimal)
Fixes #8884

Support `Decimal Proposal`

---

.eslintrc.yml
cspell.json
package.json
scripts/tools/eslint-plugin-prettier-internal-rules/index.js
scripts/tools/eslint-plugin-prettier-internal-rules/package.json
scripts/tools/eslint-plugin-prettier-internal-rules/require-json-extensions.js
src/language-css/index.js
src/language-graphql/index.js
src/language-handlebars/index.js
src/language-html/index.js
src/language-js/index.js
src/language-markdown/index.js
src/language-yaml/index.js
website/siteConfig.js
yarn.lock

The JSDoc throws when require JSON files without `.json` extension. 
ESLint rule `import/extensions` don't work with `require`, so I made a eslint plugin for it.
Context https://github.com/prettier/prettier/pull/8759#discussion_r465129685

Enforce `.json` extensions

---

package.json

These files can't add to `.prettierignore`, otherwise `node bin/prettier test.js` for debug won't work.
But `yarn lint:prettier` won't pass (and `yarn format:pretter` #8909 will format them) , if we have some `test*` file not formatted.

Ignore `test*` file in `lint:prettier` script

---

package.json
src/common/parser-create-error.js
src/language-handlebars/postprocess.js
tsconfig.json
yarn.lock

- add `@glimmer/reference` to devDependencies, as needed to avoid some "cannot find module" typecheck errors
- quick JSDoc type workaround in `src/language-handlebars/postprocess.js`
- `@ts-ignore` comments, including a comment in `src/common/parser-create-error.js` which is duplicated from PR #8759
- remove `src/language-handlebars` from `exclude` list in `tsconfig.json`
TODO items:
- ~~I think PR #8759 should be merged first, if accepted, and remove `src/common/parser-create-error.js` update from this PR~~
I am also not so happy that I had to add an extra Glimmer dependency to resolve some "cannot find module" typecheck errors, hope they can improve the situation between `@glimmer/syntax` and `tsc` (TypeScript compiler).
~~I am raising this PR as a draft PR now to give Glimmer some more …

typecheck fixes in src/language-handlebars

---

scripts/build/build.js
scripts/build/config.js
tests_config/require_standalone.js

The bundled `parser-typescript.js` exposes global objects `TypeScript`, `toolsVersion`, and `globalThis`.

Build: remove extra global objects exposed by UMD bundles

---

src/main/core.js
tests/js/cursor/jsfmt.spec.js

Similar to #9012, this one is more tricky.

Improve internal `cursorOffset` calculate

---

changelog_unreleased/javascript/pr-9011.md
src/language-js/needs-parens.js
tests/js/yield/__snapshots__/jsfmt.spec.js.snap

Without parens, eslint default parser `espree` can't parse it
Fixes #8999

Revert #7367 "Fix: remove unnecessary parens when yielding jsx"

---

scripts/build/build.js
scripts/build/bundler.js

Local checked, seems working
> Regression on build script cause by #8639
>
> Before, require('parse-*') is "Dynamic Require", now it's not, this will slow down prettier, I'll try to find a way or revert that PR.
posted in https://github.com/prettier/prettier/issues/8882#issuecomment-678979437
---

Build: Quick fix for #8639

---

website/blog/2020-08-24-2.1.0.md

In the [release notes for v2.1.0](https://prettier.io/blog/2020/08/24/2.1.0.html), [ES Module Attributes and JSON modules](https://github.com/tc39/proposal-import-assertions) and [Records & Tuples Proposal](https://github.com/tc39/proposal-record-tuple) are described as Stage-1, when in fact they appear to be Stage-2.

[blog] fix proposal stages

---

changelog_unreleased/typescript/pr-9044.md
src/language-js/needs-parens.js
tests/typescript/rest-type/__snapshots__/jsfmt.spec.js.snap
tests/typescript/rest-type/infer-type.ts

Typescript: Fix broken format for `...infer T`

---

src/language-js/parser-typescript.js

Jest `inline snapshot` rely on AST `loc` property, add it back to avoid breaking jest.
I also checked other parsers, we have `loc` in `babel`, because `comment`s in `babel` don't have range info. `flow` parser seems don't have an option for it.
Context https://github.com/facebook/jest/issues/10444
/cc @SimenB @evilebottnawi @thorn0

Add `loc` back for `typescript` parser

---

changelog_unreleased/vue/pr-9052.md
src/language-html/utils.js
tests/vue/with-plugins/__snapshots__/jsfmt.spec.js.snap
tests/vue/with-plugins/with-src.vue

Vue: fix format on blocks with `src` attribute

---

tests/typescript/rest-type/__snapshots__/jsfmt.spec.js.snap
tests/typescript/rest-type/infer-type.ts

In followup to PR #9044, I was thinking it may be good to test that these cases continue to be handled correctly:
```ts
// should remove parens from this, to avoid a type issue with TypeScript 4.0:
type Tail2<T extends any[]> = T extends [infer U, ...(infer R)] ? R : never;
// but not remove parens from this:
type Tail3<T extends any[]> = T extends [infer U, ...(infer R)[]] ? R : never;
```

test(TypeScript): test ...infer type with parens

---

scripts/draft-blog-post.js
scripts/release/steps/update-changelog.js

https://github.com/prettier/prettier/pull/8932#issuecomment-678998888

Replace changelog versions in ./scripts/draft-blog-post.js

---

.github/workflows/dev-package-test.yml
.github/workflows/dev-test.yml
.github/workflows/lint.yml
.github/workflows/prod-test.yml

Remove `fetch-depth:1` for checkout action, it default to `1`

CI: remove `fetch-depth`

---

src/language-css/printer-postcss.js

We've `stripTrailingHardline` in html (#8595), this check is not needed anymore.

Remove a unnecessary check in css printer

---

src/language-css/parser-postcss.js
src/language-css/printer-postcss.js
src/language-css/utils.js

Followup #7933, these parts should only work for less now.

Remove `css` parser from `isLessParser` check

---

src/language-js/parser-babel.js

We can access the babel error messages now. 
~I'm thinking instead of listing the errors need rethrow, we may want list the errors we want ignore.
@thorn0~ Sorry, not a good idea

Refactor `RecoveredErrors` rethrow

---

changelog_unreleased/graphql/pr-9116.md
src/language-graphql/printer-graphql.js
tests/graphql/directives/__snapshots__/jsfmt.spec.js.snap
tests/graphql/newline/__snapshots__/jsfmt.spec.js.snap

GraphQL: Fix formatting for directives in fields

---

changelog_unreleased/javascript/pr-9136.md
src/document/doc-utils.js
src/language-js/embed.js
src/language-markdown/embed.js
tests/js/multiparser-css/__snapshots__/jsfmt.spec.js.snap
tests/js/multiparser-css/styled-components.js

Fix line breaks for CSS in JS

---

docs/plugins.md

I added the `prettier-plugin-go-template` plugins to the community section of the plugin page.
---
Only changes to docs were made:

Docs: community plugins – add prettier-plugin-go-template

---

tests/typescript/template-literals/__snapshots__/jsfmt.spec.js.snap
tests/typescript/template-literals/expressions.ts

I've added a new test that demonstrates how prettier behaves with typed literals in Typescript that have generic parameters.
**✨[Try the playground for this PR](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAjAhgJ0wF5MZcBzAHigFcBbbOfAPgANsasB3ACybkxcAlgBsRmAA744MGEKaD8uCZjQ0wPTLkwjo5UhXJwAJqTh0JI3PB1D4SkQH5MAEmAAzCBAB0efL9wALwBfHT0wqH1dSIio8Oi4mITYlOS0+L1WAG4QABoQCAk5dGRQAnwILgAFAgQ0ZBBcES5cAE96-OwlMABrGQBlCVwwIUjkGHwaOHzzRmNjEwAZXEiaCjgAMQh8Oms5MZRcTgg8kB4YOhEAdR47ODQhsDh+urshADc7VoawNA6QUZoJgwKpKci7ZDuJpA-IAKzQAA8AELdPowfq4OhwRajOCQ6HTEDwhH9UbkERwACKNAg8HxIhhICG+CB+AaMFaEnuYHwQiKpykoxgVyExhgPGQAA4AAz5KQQIFXJQSBpSe5Md54-IARxp8FBhXqhzQAFooHATCZTtJdUJpKCKBCkFCGYSgXQhONJm6yRTqbS8c6CfkyNgRWKJUgAEwhpSiMkAYQgdCdIHuAFZTjQgQAVXDYI0uxnvKYASSgC1g-R5fJgAEEK-0ORT6UDgsEgA)✨**

Typescript tagged template literal test

---

package.json
src/cli/util.js
src/common/third-party.js
tests_integration/runPrettier.js
yarn.lock

`get-stdin` is simpler
- <https://unpkg.com/browse/get-stdin@8.0.0/>
- <https://unpkg.com/browse/get-stream@6.0.0/>

Switch `get-stream` to `get-stdin`

---

jest.config.js
src/main/core.js
tests_config/run_spec.js

As we can see on first commit, there are several tests failed.
1. [1](https://github.com/prettier/prettier/runs/1072793119?check_suite_focus=true#step:7:53943), [2](https://github.com/prettier/prettier/runs/1072793119?check_suite_focus=true#step:7:53974), [3](https://github.com/prettier/prettier/runs/1072793119?check_suite_focus=true#step:7:54005), [4](https://github.com/prettier/prettier/runs/1072793119?check_suite_focus=true#step:7:54036), [5](https://github.com/prettier/prettier/runs/1072793119?check_suite_focus=true#step:7:54067), [6](https://github.com/prettier/prettier/runs/1072793119?check_suite_focus=true#step:7:54096), [7](https://github.com/prettier/prettier/runs/1072793119?check_suite_focus=true#step:7:54125), [8](https://github.com/prettier/prettier/runs/1072793119?check_suite_ …

Enable `CR` test

---

website/static/separate-css/playground.css

I've always found fonts used in Playground's CodeMirror hard to read. If you know any other good fonts, please let me know.
What do you think?
***
Screen shots were taken on Google Chrome on MacOS.
**Before(current):**
**After:**

Use better fonts in Playground

---

.flowconfig

`.flowconfig` file is added in #1711, for [Nuclide](https://github.com/facebookarchive/nuclide), and [Nuclide is retired](https://github.com/facebookarchive/nuclide/blob/master/docs/index.md#retiring-the-nuclide-open-source-project)

Remove `.flowconfig`

---

changelog_unreleased/javascript/pr-9345.md
src/language-js/comments.js
tests/js/comments/__snapshots__/jsfmt.spec.js.snap
tests/js/comments/while.js

Fix placing leading comments for a body of while statement

---

changelog_unreleased/javascript/pr-9341.md
src/language-js/printer-estree.js
tests/js/classes/__snapshots__/jsfmt.spec.js.snap
tests/js/classes/assignment.js

Context: https://github.com/prettier/prettier/issues/9310#issuecomment-703321509

Improve formatting for AssignmentExpression with ClassExpression that has long superClass

---

changelog_unreleased/cli/pr-9298.md
src/cli/util.js
tests_integration/__tests__/__snapshots__/arg-parsing.js.snap
tests_integration/__tests__/arg-parsing.js
tests_integration/cli/arg-parsing/number/1/file-in-dir-named-1.js
tests_integration/cli/arg-parsing/number/2.2/file-in-dir-named-2.2.js
tests_integration/cli/arg-parsing/number/3
tests_integration/cli/arg-parsing/number/4.44

Prettier can't work if a dir/file named `1` passed to CLI

CLI: Fix error on dir or file that name is a number

---

website/pages/playground/index.html

Removed "user-scalable=no" from viewport. Consider avoiding viewport values that prevent users from resizing documents.

Playground: Removed "user-scalable=no"

---

docs/plugins.md

Added [prettier-plugin-tailwind](https://github.com/Acidic9/prettier-plugin-tailwind) to the list of community plugins in the documentation.

community plugins: add prettier-plugin-tailwind

---

docs/plugins.md

I developed a prettier plugin for formatting Jsdoc comments, I hope this plugin will be helpful for JavaScript or typescript project which uses documentation on project, for choosing all the configurations we discussed, and they are more standard.
https://github.com/hosseinmd/prettier-plugin-jsdoc

Add `prettier-plugin-jsdoc` to plugins list

---

changelog_unreleased/javascript/pr-9431.md
src/language-js/embed.js
tests/js/multiparser-invalid/__snapshots__/jsfmt.spec.js.snap
tests/js/multiparser-invalid/jsfmt.spec.js
tests/js/multiparser-invalid/text.js

Fixes #9429
---
I'll do more improvements on js embed after this merge.

Consistent format on invalid template literals

---

changelog_unreleased/javascript/pr-9435.md
src/language-js/printer-estree.js
src/language-js/utils.js
tests/js/export/__snapshots__/jsfmt.spec.js.snap
tests/js/export/same-local-and-exported.js
tests/js/import/__snapshots__/jsfmt.spec.js.snap
tests/js/import/same-local-and-imported.js

JS: Fix `import {a as a}` and `export {a as a}` format

---

src/language-js/embed.js

- Move `markdown` format logic from `TemplateElement` to `TemplateLiteral`, consistent with other languages
- DRY/Simplify

Refactor JS embed

---

changelog_unreleased/typescript/pr-9473.md
cspell.json
src/language-js/printer-estree.js
tests/typescript/key-remapping-in-mapped-types/__snapshots__/jsfmt.spec.js.snap
tests/typescript/key-remapping-in-mapped-types/jsfmt.spec.js
tests/typescript/key-remapping-in-mapped-types/key-remapping.ts
tests/typescript/template-literal-types/__snapshots__/jsfmt.spec.js.snap
tests/typescript/template-literal-types/jsfmt.spec.js
tests/typescript/template-literal-types/template-literal-types.ts

Support TypeScript 4.1 via Babel

---

changelog_unreleased/javascript/pr-9408.md
src/language-js/parser-babel.js
src/language-js/printer-estree.js
tests/js/babel-plugins/__snapshots__/jsfmt.spec.js.snap
tests/js/babel-plugins/class-static-block.js
tests/js/babel-plugins/jsfmt.spec.js
tests/js/class-static-block/__snapshots__/jsfmt.spec.js.snap
tests/js/class-static-block/class-static-block.js
tests/js/class-static-block/jsfmt.spec.js

Support class-static-block proposal that is supported on Babel 7.12 https://babeljs.io/blog/2020/10/15/7.12.0#class-static-blocks-12079httpsgithubcombabelbabelpull12079-12143httpsgithubcombabelbabelpull12143

Support class-static-block proposal

---

changelog_unreleased/flow/pr-9457.md
src/language-js/comments.js
src/language-js/printer-estree.js
tests/flow/this-annotation/__snapshots__/jsfmt.spec.js.snap
tests/flow/this-annotation/declare_function.js
tests/flow/this-annotation/function_declaration.js
tests/flow/this-annotation/function_type.js
tests/flow/this-annotation/jsfmt.spec.js
tests/flow/this-annotation/line_break.js
tests/flow/this-annotation/method.js
tests/flow/this-annotation/union_type.js

This PR adds support for Flow `this` parameter annotations. 
E.g.
```
function foo (this : number) {}
``` 

Support Flow this parameter annotations

---

tests/js/dynamic-import/__snapshots__/jsfmt.spec.js.snap
tests/js/dynamic-import/assertions.js
tests/js/dynamic-import/jsfmt.spec.js

The second argument in `import()` is not handled, https://github.com/prettier/prettier/blob/56e9602a28d10b05a7205692786356f5d1e8308d/src/language-js/print/call-arguments.js#L121, when parser support this syntax, the test should fail.

Test "import assertions" on other parsers

---

scripts/build/build.js

The new esm files not listed in package.json.

Fix missing `esm` files in `dist/package.json`

---

src/language-js/clean.js
src/main/massage-ast.js

We deleted `ast.tokens` in clean, but the `massageAST` will still run `clean` over objects inside `tokens` and `comments`, because `Object.keys()` is called before `clean()`.
Found this during https://github.com/prettier/prettier/pull/9514, [there is a token `{type: 'TemplateLiteral'}`](https://github.com/prettier/prettier/pull/9514/files#diff-6bb1daf26b0ff781b5a96f32e9b3faf9bf0375deac42f3e7235430bf9ad92eeaR207)
Current implementation not looks good, but I can figure a better way. Any better idea?

Improve `massageAST`

---

website/static/worker.js

[`serialize-javascript` serialize BigInt like 'BigInt("9999")'](https://github.com/yahoo/serialize-javascript/blob/ac79a5aa9578131cd199f45c5e449eca84f9e35e/test/unit/serialize.js#L439-L440), I replaced `"` with `'` to avoid escape in JSON values.
Fixes #9524

Playground: serialize ast contains BigInt

---

changelog_unreleased/flow/pr-9553.md
src/language-js/postprocess.js
tests/flow/ignore/__snapshots__/jsfmt.spec.js.snap
tests/flow/ignore/type-cast-expression.js

Flow: Fix missing parentheses around prettier-ignored arguments

---

.eslintrc.yml
scripts/tools/eslint-plugin-prettier-internal-rules/directly-loc-start-end.js
scripts/tools/eslint-plugin-prettier-internal-rules/index.js
scripts/tools/eslint-plugin-prettier-internal-rules/package.json
src/language-js/comments.js
src/language-js/print/call-arguments.js
src/language-js/print/member-chain.js
src/language-js/print/ternary.js
src/language-js/printer-estree.js
src/language-js/utils.js

Refactor: Use `locStart` and `locEnd` directly from `language-js/loc.js`

---

src/language-js/printer-estree.js
tests/misc/errors/invalid/__snapshots__/jsfmt.spec.js.snap
tests/misc/errors/invalid/jsfmt.spec.js

This was [added long time ago](https://github.com/josephfrazier/prettier/commit/9b4535e9f8a7040f2fbc65b22c9713632f3731be#diff-2d346b55d05d4171a948f6cb1573717ecd3adfb47cd9647448728c024cfec86bR891), maybe some parser support this syntax back then, but as I checked, no parser support it now.

Remove `for-each-in` syntax

---

src/language-js/loc.js
src/language-js/printer-estree.js
src/language-js/utils.js

Fix more `locStart`/`locEnd` from `options`

---

src/language-handlebars/utils.js

I guess this mean to test `.children.length`, but it's unnecessary too, `Array#every()` always returns `true` on empty array.

Fix a condition

---

changelog_unreleased/javascript/pr-9650.md
src/language-js/needs-parens.js
tests/js/yield/__snapshots__/jsfmt.spec.js.snap

Revert #9011, don’t add parens when yielding simple JSX expressions

---

changelog_unreleased/javascript/pr-9662.md
src/language-js/printer-estree.js
tests/js/last-argument-expansion/__snapshots__/jsfmt.spec.js.snap
tests/js/last-argument-expansion/function-expression.js

Fixes #3376
This was done for arrow functions in #1305 ("Avoid breaking arguments for last arg expansion").
This PR enables the same for function expressions unless the function expression is the only argument.
**Before:**
```js
function* mySagas() {
yield effects.takeEvery(rexpress.actionTypes.REQUEST_START, function*({
id
}) {
console.log(id);
yield rexpress.actions(store).writeHead(id, 400);
yield rexpress.actions(store).end(id, "pong");
console.log("pong");
});
}
```
**After:**
```js
function* mySagas() {
yield effects.takeEvery(
rexpress.actionTypes.REQUEST_START,
function* ({ id }) {
console.log(id);
yield rexpress.actions(store).writeHead(id, 400);
yield rexpress.actions(store).end(id, "pong");
console.log("pong");
}
);
}
```
Where did "unless the function expression is the only …

Flatten function expression parameters in hugged last argument

---

src/document/doc-printer.js
tests_integration/__tests__/plugin-flush-line-suffix.js
tests_integration/plugins/flushLineSuffix/file.foo
tests_integration/plugins/flushLineSuffix/plugin.js

As noted in #9702, currently Prettier core does not flush line-suffix contents at the end of the document if there is no trailing newline. This fix forces all of those contents to be flushed even without trailing newlines.

Fix #9702 - Flush line suffix contents at the end of document

---

src/language-js/print/class.js
src/language-js/print/function.js
src/language-js/print/misc.js
src/language-js/print/property.js
src/language-js/printer-estree.js

Extract function related functions

---

src/language-js/print/call-expression.js
src/language-js/print/interface.js
src/language-js/print/misc.js
src/language-js/printer-estree.js

Extract printInterface and printCallExpression

---

src/common/util.js
src/language-js/comments.js
src/language-js/printer-estree.js
src/main/comments.js

One step to address #8122, stop mutating comments during `decorateComment`, to achieve this, we have to pass decorate info seperately to `handleXXXComment`, I added a flag on printer, but we'll remove it when all done.

Refactor: Stop mutating comments during `decorateComment`

---

changelog_unreleased/javascript/9741.md
src/language-js/print/class.js
tests/js/classes/__snapshots__/jsfmt.spec.js.snap
tests/js/classes/assignment.js
tests/js/classes/long-superclass.js

Fix formatting for AssignmentExpression with ClassExpression

---

scripts/build/bundler.js

Fix rollup warnings by replacing `@glimmer/syntax` with another entry
Master branch build log https://github.com/prettier/prettier/runs/1478488011#step:6:22
New log https://github.com/prettier/prettier/runs/1478653306?check_suite_focus=true#step:6:1

Build: Fix rollup warning

---

scripts/build/cache.js

Is there a reason that `Cache` is built with constructor function?
This PR has only two changes:
1. constructor function -> class statement
2. `assert.equal` -> `assert.strictEqual`
This PR doesn't touch logics of Cache.

Refactor: Make Cache modern in build scripts
