prettier/prettier

src/comments.js, src/printer.js, tests/node_tests/stream/__snapshots__/jsfmt.spec.js.snap, tests/promises/__snapshots__/jsfmt.spec.js.snap, tests/union/__snapshots__/jsfmt.spec.js.snap
This seems to work pretty well, however this forces simple expressions that have a CallExpression on the left-hand to break on a newline:
```js
foo()
.callMethod()
```
The question is how can we differentiate between that and places we want to chain?
=> Initial attempt at chaining call expressions

package.json
Installed via npm (not yarn). Also stuck on npm 2 at work.  In ran `npm install -g prettier`. Install worked fine.
Then I went to run:
```
prettier -h
```
And found that 2 packages were missing until I installed them: `source-map` and `private`
=> Adding missing `source-map` and `private` to deps

src/printer.js, tests/prettier/__snapshots__/jsfmt.spec.js.snap, tests/prettier/jsfmt.spec.js, tests/prettier/optional-type-name.js
Fixes #38.
The `name` on `FunctionTypeParam`, and the `id` on `ObjectTypeIndexer`, can be skipped as of Flow 34.
I wasn't exactly sure where to put the tests, I added them into `abnormal`? Let me know if there's a better place for them.
=> Print Flow types with no name (fixes #38)

README.md
I got an error the first time I tried to use the API, because I copied-and-pasted the example, and there is a missing comma in the API example.
This PR could help save some time for the users. 😄
=> Add missing comma in API example

bin/prettier.js
When you are formatting an entire codebase and a single file throw, it shouldn't stop the entire process.
Example with #84 added:
=> Do not fatal when formatting throws

src/printer.js, tests/predicates-parsing/__snapshots__/jsfmt.spec.js.snap
=> Remove trailing whitespace in broken arrow function expressions.

README.md, bin/prettier.js
Although prettier lacks options to filter project files to format by itself, most shells allow to submit multiple files with a filename expansion. Add an example using bash.
=> docs: add globbing example

package.json
Add repository field to package.json, allowing the [package page](https://www.npmjs.com/package/prettier) at npm to link to [jlongster/prettier](https://github.com/jlongster/prettier).
=> chore: link prettier package to its github project

package.json, src/printer.js
This omits quotes for property names which don't need them, fixing #79. It doesn't touch property names in flow type annotations, since I'm not sure which quotes are semantic there.
There's currently no tests, and no effect on the snapshots. As an example of its effect, currently the below passes through prettier without change:
```js
function f({ "a": b = c }) {}
({ "0": null });
class A {
["d"];
"e";
"f"() {}
get "g"() {}
+"0";
}
```
~~With this PR, it becomes~~
```js
function f({ a: b = c }) {}
({ 0: null });
class A {
["d"];
e;
f() {}
get g() {}
+0;
}
```
Please take an especially careful look `printPropertyKey`, since I'm not entirely sure how it ought to be implemented.
Edit: per review, updated to not apply to numbers. Now it outputs
```js
function f({ a: b = c }) {}
({ "0": null …
```
=> Fix #79: omit unnecessary quotes in property names

editors/emacs/prettier-js.el
It's more prolific!
The discussion in #110 was helpful, it looks like @brocmdean basically had it right.
=> Emacs library fix: use `setq' instead of `infc' and `decf'

src/printer.js
This is working on the flow parser but not babylon
```js
echo 'function f(...flags: Array<boolean>) {}' | ./bin/prettier.js --stdin
function f(...flags: Array<boolean>) {}
```
=> Support type annotation for rest argument on babylon parser

src/printer.js, src/util.js, tests/jsx/__snapshots__/jsfmt.spec.js.snap, tests/jsx/jsfmt.spec.js, tests/jsx/quotes.js
JSX quotes are unfortunately using html escaping. Also, we should disregard the single-quote option for JSX quotes as we always want double quotes.
=> Always use double quotes for JSX and properly escape

src/printer.js
This is working on the flow parser but not babylon
```js
echo 'class C<T> { submit<T>() { } }' | ./bin/prettier.js --stdin
class C<T> {
submit<T>() {}
}
```
=> Support method generics on babylon parser

src/printer.js, tests/prettier/__snapshots__/jsfmt.spec.js.snap, tests/prettier/method-chain.js
Supersedes https://github.com/jlongster/prettier/pull/108 with fixes to get it in.
=> Fix misprinting of computed properties in method chains.

bin/prettier.js
Attempt to fix #44 
Shebangs are treated as comments in the AST, this PR handles them outside of the parser by removing before and adding after.
=> treat shebang outside of parsing

src/printer.js, tests/config_module_name_mapper_filetype/__snapshots__/jsfmt.spec.js.snap, tests/declare_export/__snapshots__/jsfmt.spec.js.snap, tests/es6modules/__snapshots__/jsfmt.spec.js.snap, tests/export_type/__snapshots__/jsfmt.spec.js.snap
Follows the same pattern as https://github.com/jlongster/prettier/pull/156/files
```js
echo "import { aaaaaaaa, bbbbbb, cccccc, dddddddd, eeeeeee, fffffffff, ggggggggg } from 'vjeux';" | ./bin/prettier.js --stdin
import {
aaaaaaaa,
bbbbbb,
cccccc,
dddddddd,
eeeeeee,
fffffffff,
ggggggggg
} from "vjeux";
```
=> Break multiline imports

src/printer.js
```js
echo "export { aaaaaaaa, bbbbbb, cccccc, dddddddd, eeeeeee, fffffffff, ggggggggg } from 'vjeux';" | ./bin/prettier.js --stdin --trailing-comma
export {
aaaaaaaa,
bbbbbb,
cccccc,
dddddddd,
eeeeeee,
fffffffff,
ggggggggg,
} from "vjeux";
```
=> Add trailing comma support for multiline exports

src/fast-path.js, tests/literal/__snapshots__/jsfmt.spec.js.snap, tests/literal/number.js
Here's a shot at fixing #96. It's pretty much a shot in the dark, but it was fun rooting around and getting to know the codebase a little.
=> Numeric literal callees should keep parens

src/printer.js
This option was leftover from recast's printer. There's no need for an option for such a tiny syntax tweak.
=> Remove leftover `arrowParensAlways` option

src/printer.js, tests/jsx_intrinsics.builtin/__snapshots__/jsfmt.spec.js.snap, tests/jsx_intrinsics.custom/__snapshots__/jsfmt.spec.js.snap, tests/prettier/__snapshots__/jsfmt.spec.js.snap, tests/prettier/jsx-multiline-assign.js, tests/prettier/jsx-significant-space.js, tests/prettier/jsx-split-attrs.js, tests/prettier/jsx-stateless-arrow-fn.js
I wasn't sure where to add the new test cases, so I just threw them as separate files in the `prettier` dir. Happy to move/rename etc as desired.
=> Several JSX fixes (addresses #73)

package.json
This PR will include `index.js` in the npm script `format:all`.
=> Include index.js in format:all script

docs/index.html
Hi! Cool project and concept. Love auto formatting in languages like OCaml, so I'm excited for this.
I did some various changes (subjectively improvements) to prettier-browser that I think would make for more comfortable usage.
- Added link to project repo on header for easier navigation to code.
- Added Sublime key-mapping, which I think is one of the more popular/widely used mappings. Helps for better tabbing, duplicate lines, multi cursors etc.
- Added line numbers.
- Changed theme to be more soothing I think (highly subjective of course). See image below
I get that this is subjective and might not be what all want, but let me know if there is anything I should remove or of course close the PR if not interested.
Thanks again.
=> Adds various prettier-browser changes

src/fast-path.js
Another issue where babylon and flow ast are different. In babylon, it is NumericLiteral but flow is Literal. All the tests are running on flow so were working correctly, but the default in the command line is to use babylon, so people report bugs with it.
=> Fix `[(0)]`

src/util.js
For backward, we should go one step back, but for forward we are already in the correct place. It doesn't change any tests.
=> Do not advance for forward skipSpaces

src/util.js, tests/line-endings/__snapshots__/jsfmt.spec.js.snap, tests/line-endings/jsfmt.spec.js, tests/line-endings/windows.js
The search for an empty line incorrectly does +1 which happens to be skipping a `\n`, but in case of windows line endings it skips the `\r` but sees a `\n` afterwards and incorrectly assumes that it is a empty line.
This doesn't change the behavior of doing +1 when there's not a line ending. Making it correct actually triggers a bunch of changes, where half of them are better and half of them regressions. So I'm going to send another pull request to fix that case.
Fixes #151
=> Fix windows line-endings

src/printer.js
Flow doesn't have a different ast node for `type` and `declare type`. Let's always use the heuristic to be inside of a `declare module` for both ast. This way more snapshot tests are passing between the two parsers.
```js
echo 'declare type Dinosaur = "T-Rex" | "Apatosaurus";' | ./bin/prettier.js --stdin
type Dinosaur = "T-Rex" | "Apatosaurus";
```
```js
echo 'declare type Dinosaur = "T-Rex" | "Apatosaurus";' | ./bin/prettier.js --stdin --flow-parser
type Dinosaur = "T-Rex" | "Apatosaurus";
```
```js
echo 'declare module X {declare type Dinosaur = "T-Rex" | "Apatosaurus";}' | ./bin/prettier.js --stdin
declare module X {
declare type Dinosaur = "T-Rex" | "Apatosaurus";
}
```
```js
echo 'declare module X {declare type Dinosaur = "T-Rex" | "Apatosaurus";}' | ./bin/prettier.js --stdin …
```
=> Make `declare type` consistent between babylon and flow

src/printer.js, tests/async_iteration/__snapshots__/jsfmt.spec.js.snap, tests/callable/__snapshots__/jsfmt.spec.js.snap, tests/constructor_annots/__snapshots__/jsfmt.spec.js.snap, tests/export_type/__snapshots__/jsfmt.spec.js.snap, tests/interface/__snapshots__/jsfmt.spec.js.snap, tests/interface/interface.js, tests/lib_interfaces/declarations/__snapshots__/jsfmt.spec.js.snap, tests/object-method/__snapshots__/jsfmt.spec.js.snap, tests/poly_overload/decls/__snapshots__/jsfmt.spec.js.snap, tests/structural_subtyping/__snapshots__/jsfmt.spec.js.snap, tests/tagged-unions/__snapshots__/jsfmt.spec.js.snap, tests/this_type/__snapshots__/jsfmt.spec.js.snap, tests/traits/__snapshots__/jsfmt.spec.js.snap, tests/type_args_nonstrict/__snapshots__/jsfmt.spec.js.snap, tests/type_args_strict/__snapshots__/jsfmt.spec.js.snap, tests/type_param_scope/__snapshots__/jsfmt.spec.js.snap, tests/union_new/__snapshots__/jsfmt.spec.js.snap
DeclareInterface (flow) and InterfaceDeclaration (babylon) are the same type so should behave the same way. I am using the same `declare` trick where I only add it if you are inside of a `declare module` block.
=> Fix DeclareInterface

index.js, package.json, src/printer.js, src/util.js
Source maps are no longer really relevant to this project, so I completely removed code dealing with them, as Prettier reprints everything anyway and it would be nearly impossible to remap from the old source to the new one. This also allows us to remove some legacy Recast options and API.
=> Remove legacy Recast code and simplify API.

src/printer.js
We were not printing the directives if the body of the function was empty in babylon. Also, we were printing way too many \n
```js
echo "function fn() { 'use strict'; }" | ./bin/prettier.js --stdin
function fn() {
"use strict";
}
```
```js
echo "function fn() { 'use strict'; }" | ./bin/prettier.js --stdin --flow-parser
function fn() {
"use strict";
}
```
=> Fix directives printing for empty functions

src/printer.js, tests/destructuring/__snapshots__/jsfmt.spec.js.snap, tests/typeof/__snapshots__/jsfmt.spec.js.snap
#90 fixed it using the Babylon AST nodes, this makes it work for Flow ones as well.
```js
echo 'var { "key": val } = 1;' | ./bin/prettier.js --stdin --flow-parser
var { key: val } = 1;
```
=> Fix key quotes omission for flow parser

src/printer.js, tests/last_argument_expansion/__snapshots__/jsfmt.spec.js.snap, tests/last_argument_expansion/jsfmt.spec.js, tests/last_argument_expansion/jsx.js, tests/last_argument_expansion/object.js
=> Last argument expansion works for arrow functions that return JSX

src/util.js, tests/template/__snapshots__/jsfmt.spec.js.snap, tests/template/faulty-locations.js
There's a handful of files inside of Nuclide that throw exceptions because an assertion is raised.
```
{ AssertionError: ']' === '`'
at fixTemplateLiteral (/Users/vjeux/random/prettier/src/util.js:105:10)
at Object.util.fixFaultyLocations (/Users/vjeux/random/prettier/src/util.js:45:5)
at getSortedChildNodes (/Users/vjeux/random/prettier/src/comments.js:25:8)
at getSortedChildNodes (/Users/vjeux/random/prettier/src/comments.js:61:5)
at decorateComment (/Users/vjeux/random/prettier/src/comments.js:71:20)
at decorateComment (/Users/vjeux/random/prettier/src/comments.js:85:7)
at decorateComment (/Users/vjeux/random/prettier/src/comments.js:85:7)
at decorateComment (/Users/vjeux/random/prettier/src/comments.js:85:7)
at decorateComment (/Users/vjeux/random/prettier/src/comments.js:85:7)
at …
```
=> Remove faulty location check on template literals that throws in Nuclide

index.js, tests_config/run_spec.js
The Nuclide codebase uses features that are still proposals which require a flag to be enabled. Babylon parses them fine without any flags.
Let's enable them by default as it doesn't cost much, you either are using those features and you don't want the parser to break, or you are not and you don't care.
After this and #218, none of the nuclide files are throwing exceptions anymore! (yay!)
=> Add flow parser experimental options

src/printer.js, tests/empty_statement/__snapshots__/jsfmt.spec.js.snap, tests/empty_statement/body.js, tests/empty_statement/jsfmt.spec.js
```js
for (;;);
function f() {}
```
The `;` was dropped meaning that the line right after was executed within the for loop which is not correct.
I tried to return `;` but it looks like
```js
for (;;)
;
```
which looks super weird so I ended up printing `{}` which looks like
```js
for (;;) {}
```
This fixes and issue found by #223
=> Make sure empty for loops generate valid code

editors/emacs/prettier-js.el
This adds a `prettier-target-mode` variable to `prettier-js.el` to allow customizing what major mode to run `prettier-before-save` in, as mentioned in #273.
=> Allow specifying the major mode that `defun-before-save` will use.

src/printer.js, tests/export/__snapshots__/jsfmt.spec.js.snap, tests/export/bracket.js, tests/export/jsfmt.spec.js
I copy and pasted the code for arrays which doesn't have this problem. Would be nice to come up with an abstraction for a list of stuff separated by commas. It happens a lot of time and right now it's duplicated everywhere.
Fixes #255
=> Fix space missing before `,` on export with bracket spacing off

src/printer.js, tests/import/__snapshots__/jsfmt.spec.js.snap, tests/import/brackets.js, tests/import/jsfmt.spec.js
Same fix as #278. We use the same (wrong) pattern in both places
=> Fix space missing before `,` on import with bracket spacing off

editors/emacs/prettier-js.el
We require single quotes in our eslint config, which conflicts with prettier's default rules. Now the `prettier-args` custom variable allows anyone to set the arguments passed to the prettier command when it runs.
Might be nice to eventually build this up out of individual customization options (ie. `(setq prettier-single-quote t)`), but this is a pretty simple approach that works for now.
=> Allow customizing args sent to prettier-command

src/printer.js, tests/rest/__snapshots__/jsfmt.spec.js.snap, tests/rest/jsfmt.spec.js, tests/rest/trailing-commas.js
It turns out that this is not valid by the spec!
=> Do not output trailing commas with rest arguments

tests/export/__snapshots__/jsfmt.spec.js.snap, tests/export/jsfmt.spec.js, tests/import/__snapshots__/jsfmt.spec.js.snap, tests/import/jsfmt.spec.js
Basically `bracketsSpacing` -> `bracketSpacing`.
Do you think it's worth to validate config options, so such typos could be easily caught?
I actually was testing [`jest-validate`](https://github.com/facebook/jest/tree/master/packages/jest-validate) here because I thought it may come in handy and this showed up:
From some very rough (measured Jest total time) tests the impact on performance is ~1-2%
=> Fix bracketSpacing typo in tests

src/pp.js, tests/disjoint-union-perf/__snapshots__/jsfmt.spec.js.snap, tests/dom/__snapshots__/jsfmt.spec.js.snap, tests/intersection/__snapshots__/jsfmt.spec.js.snap, tests/trailing_whitespace/__snapshots__/jsfmt.spec.js.snap, tests/trailing_whitespace/jsfmt.spec.js, tests/trailing_whitespace/trailing.js, tests/type-printer/__snapshots__/jsfmt.spec.js.snap, tests/typeapp_perf/__snapshots__/jsfmt.spec.js.snap, tests/union-intersection/__snapshots__/jsfmt.spec.js.snap, tests/union/__snapshots__/jsfmt.spec.js.snap, tests/union_new/__snapshots__/jsfmt.spec.js.snap
In the printer, remove trailing whitespace except for template literals
Fixes #222
=> Fix trailing whitespace

src/fast-path.js, src/printer.js, src/util.js, tests/intersection/__snapshots__/jsfmt.spec.js.snap, tests/logical/__snapshots__/jsfmt.spec.js.snap, tests/prettier/__snapshots__/jsfmt.spec.js.snap, tests/prettier/binary-expressions.js
This is a complete rewrite of binary and logical expressions that, if anything, is at least a whole lot more consistent. There may be tweaks to actual output for certain patterns, but before it was somewhat arbitrary what was broken across lines.
Now, if an expression is broken up, it's all or nothing:
```js
var x = reallyLongArg() + reallyLongArg() * reallyLongArg() % reallyLongArg() + reallyLongArg() + reallyLongArg() + reallyLongArg();
```
Turns into:
```js
var x = reallyLongArg() +
reallyLongArg() *
reallyLongArg() %
reallyLongArg() +
reallyLongArg() +
reallyLongArg() +
reallyLongArg();
```
The idea is that we shouldn't touch anything that you could write out by hand without adding parens. The AST makes this a little difficult, but I think the solution ended up elegant. I spent a lot …
=> Print binary and logical expressions in a nicer format

docs/index.html, docs/rollup.config.js, package.json, yarn.lock
It doesn't compile cleanly anymore:
- esutils checks for Buffer.isBuffer without ensuring that Buffer exists.
- for version, we require a json file, need a rollup extension for that.
I no longer hardcode the version number.
Note: we need to merge this pull request after we have done the release so that the version number is correct and need to rebuild the minified version in a subsequent commit.
=> Fix docs generation process

src/printer.js, tests/rest/__snapshots__/jsfmt.spec.js.snap, tests/rest/trailing-commas.js
I thought I didn't need to check the length but forgot that the rest argument is not in the list for class declaration. Now it doesn't crash anymore and there's a test...
=> Fix crash for single rest on class declaration

README.md
Hey guys... this would be the [canonical link](https://packagecontrol.io/packages/JsPrettier) ([discussion here](https://github.com/jlongster/prettier/pull/190#issuecomment-272619266)) for Sublime Text Prettier support, approved by [Package Control](https://packagecontrol.io).
=> Add Canonical Sublime Text Link

src/printer.js, tests/jsx/__snapshots__/jsfmt.spec.js.snap, tests/jsx/expression.js, tests/react/__snapshots__/jsfmt.spec.js.snap
=> Hug elements inside of JSXExpressionContainer

src/doc-builders.js, src/doc-utils.js
It complained that it couldn't recognize const outside of `"use strict";`. It's a good idea to add this anyway.
=> Fix node 4

index.js, src/parser.js, tests_config/run_spec.js
Before, we would parse things inline in both index.js and run_spec.js. Extracting it should make it easier to manage and understand what is going on.
I ran `AST_COMPARE=1 npm test` and it still works.
=> Extract parser.js

index.js
Extracted out `parse` and `attachComments`. Moved the options normalization in the exported function.
This way, we have a super clean `format` function :)
```js
function format(text, opts) {
const ast = parse(text, opts);
attachComments(text, ast, opts)
const doc = printAstToDoc(ast, opts)
const str = printDocToString(doc, opts.printWidth)
return str;
}
```
=> Refactor index.js

README.md, bin/prettier.js, index.js, src/options.js, src/printer.js, tests/array_spread/jsfmt.spec.js, tests/comments/jsfmt.spec.js, tests/jsx_escape/jsfmt.spec.js, tests_config/run_spec.js
The previous API was inconsistent. The new one is
```js
--parser flow
--parser babylon
{parser: 'flow'}
{parser: 'babylon'}
```
if we ever want to add new parsers in the future it'll allow that more easily.
I put a console.log in parser.js in both functions and tested that the test suite worked both with and without the change in run_spec. I also tested that both the previous and new command line options are working.
At some point in the future we'll likely want to get rid of the old api but might as well keep supporting it so we don't break anyone for now.
=> Introduce --parser/parser option and deprecate --flow-parser/useFlowParser

bin/prettier.js, docs/index.html, index.js, src/doc-debug.js
This PR adds two things:
`--debug-print-doc` command that prints the formatted doc
```js
echo "<div>&lt;</div>" | ./bin/prettier.js --stdin --debug-print-doc
[
groupConditional(
group([
group([ "<", "div", group([ indent(2, []), softline() ]), ">" ]),
"&lt;",
"</",
"div",
">"
]),
[
group([
group([ "<", "div", group([ indent(2, []), softline() ]), ">" ]),
"&lt;",
"</",
"div",
">"
]),
group([
group([ "<", "div", group([ indent(2, []), softline() ]), ">" ]),
indent(2, groupBreak([ hardline(), "&lt;" ])),
hardline(),
"</",
"div",
">"
])
]
),
";",
hardline()
];
```
The ability to view the IR in real time on the browser display:
The way it works is pretty cool, we take the doc IR and print a valid JavaScript string out of it, that we then send to prettier in order to make it look good :)
=> Add debugging support for doc IR

package.json, src/doc-debug.js
Even though JSON.stringify is not 100% correct, this is only used for debugging and doesn't warrant adding a dependency for it.
Note: this needs to land after #355
=> Drop jsesc

bin/prettier.js
- Add missing options to minimist. This removes "Ignored unknown
option:" warnings for options that actually exists.
- Put more interesting options closer to the top.
- Consistenly use full sentences.
=> Fix CLI options

src/printer.js, tests/import/__snapshots__/jsfmt.spec.js.snap, tests/import/multiple_standalones.js
There was an assertion that there would be only one, it turned out not to be the case.
Fixes #386
=> Support multiple standalones in import

src/printer.js, tests/rest/__snapshots__/jsfmt.spec.js.snap, tests/rest/trailing-commas.js
We shouldn't output trailing commas when there is a forced one when we break.
Fixes #380
=> Fix forced trailing comma

index.js
This makes it easier to use prettier to format an existing AST, avoiding the need to generate code then parse again.
=> Add formatAST() for formatting ASTs directly

src/fast-path.js, tests/function/__snapshots__/jsfmt.spec.js.snap, tests/function/function_expression.js
=> Remove unneeded parens for FunctionExpression inside LogicalExpression

src/fast-path.js, tests/yield/__snapshots__/jsfmt.spec.js.snap, tests/yield/conditional.js
Turns out, we need to always parenthesis when it's the first part of a conditional for both yield and await.
Fixes #433
=> Proper parenthesis for yield and await in conditional

bin/prettier.js
If you use the `--write` option, the files will end with a single
newline as expected. But if you let prettier print to stdout instead and
redirect that into a file, it will contain _two_ newlines at the end.
Demonstration of the correct `--write` behavior:
```js
$ cat tmp.js
function test() {
return "hello";
}
$ wc -l tmp.js
3 tmp.js
$ ./bin/prettier.js tmp.js --write
tmp.js
$ cat tmp.js
function test() {
return "hello";
}
$ wc -l tmp.js
3 tmp.js
```
Notice how an extra line is added when redirecting stdout:
```js
$ ./bin/prettier.js tmp.js > tmp2.js
$ cat tmp2.js
function test() {
return "hello";
}
$ wc -l tmp2.js
4 tmp2.js
```
With this commit things work as expected:
```js
$ ./bin/prettier.js tmp.js > tmp2.js
$ cat tmp2.js
function test() {
return "hello";
}
$ wc -l tmp2.js
3 tmp2.js …
```
=> Don't print double newlines at EOF to stdout

package.json, src/deprecated.js, src/options.js, yarn.lock
Example usage of `jest-validate` for pretty errors and warnings
=> Validate user-provided config with jest-validate

src/deprecated.js
Fixes a typo
btw, this warning looks like this:
=> Fix typo in config.useFlowParser variable name

src/doc-builders.js
Right now it says that the boolean expression fails which is not super useful. Instead, now it prints the actual value.
=> Better error message for assertDoc

commands.md, src/doc-builders.js, src/doc-debug.js, src/printer.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/trailing_whitespace/__snapshots__/jsfmt.spec.js.snap
Starting to convert all `multilineGroup`s into normal `group`s. This inverts the logic in some places and we need to be sure that the right nodes break the parents correctly. This is making code a bit more consistent already.
=> Remove `multilineGroup`

package.json
Add Flow's DeclareExportAllDeclaration type has been merged into benjamn/ast-types so the forks are now in sync.
=> Update package.json, use ast-types 0.9.4

src/printer.js, tests/dynamic_import/__snapshots__/jsfmt.spec.js.snap, tests/dynamic_import/jsfmt.spec.js, tests/dynamic_import/test.js
Fixes https://github.com/jlongster/prettier/issues/457
Did the same as babel-generator (https://github.com/babel/babel/pull/4945)
=> Support printing import("a")

src/printer.js, tests/flow/logical/__snapshots__/jsfmt.spec.js.snap, tests/trailing_comma/__snapshots__/jsfmt.spec.js.snap, tests/trailing_comma/object.js
This was introduced by #314 where `line` should have been `softline`. By the way, I was going to propose renaming `line` to `line_or_space` and `softline` to `line_or_nothing` which should make it more explicit what is going on.
Fixes #461
=> Fix spurious whitespace

src/printer.js, tests/directives/__snapshots__/jsfmt.spec.js.snap, tests/directives/jsfmt.spec.js, tests/directives/newline.js
It's annoying that the line after `"use strict";` gets eaten away on babylon. This fixes it :)
Fixes #216
=> Preserve new lines after directives in babylon

src/printer.js, tests/decorators/__snapshots__/jsfmt.spec.js.snap, tests/decorators/jsfmt.spec.js, tests/decorators/mobx.js, tests/decorators/multiple.js, tests/decorators/redux.js
Mobx is the only popular JavaScript library that I know about which uses decorators. They put things on the same line so we should follow their conventions.
The logic implemented here is the following: if there is one decorator, it's on the same line. If there is more than one, they are each on their own line.
Fixes #325
=> Put decorators on the same line

README.md
I think it may help adoption of `prettier` if people don't have to change their entire coding style all at once. These projects enable that.
Figured it'd be just as easy to create a PR as it would be to ask first :)
=> docs: add related projects

src/printer.js, tests/classes/__snapshots__/jsfmt.spec.js.snap, tests/classes/break.js
```js
class A extends B implements C {
method() {}
}
```
now outputs
```js
class A
extends B
implements C {
method() {}
}
```
Fixes #147
=> Add break points for class declaration

src/printer.js, tests/jsx-stateless-arrow-fn/__snapshots__/jsfmt.spec.js.snap, tests/jsx/__snapshots__/jsfmt.spec.js.snap, tests/jsx/hug.js
Conditionals are very common in JSX and it is unfortunate that they take up so much vertical space in the current prettier.
This pull request does a few tweaks:
- It hugs ConditionalExpression (ternary) and LogicalExpression (&&) inside of `{}` in a jsx child, not an attribute
- It doesn't output parenthesis if your parent is a LogicalExpression (&&)
Fixes #317
=> [RFC] Hug Conditionals in JSX

index.js, src/doc-printer.js, tests/windows/__snapshots__/jsfmt.spec.js.snap, tests/windows/jsfmt.spec.js, tests/windows/line-ending.js
It's nice that we print line endings in a single place, it was super easy to preserve them :)
Fixes #92 
```js
cat tests/windows/line-ending.js | cat -e
this;^M$
has;^M$
windows;^M$
line;^M$
endings;^M$
./bin/prettier.js tests/windows/line-ending.js | cat -e
this;^M$
has;^M$
windows;^M$
line;^M$
endings;^M$
```
=> Maintain windows line ending

src/printer.js, tests/jsx-split-attrs/__snapshots__/jsfmt.spec.js.snap, tests/jsx-split-attrs/test.js
Addresses a pain point mentioned in https://github.com/jlongster/prettier/issues/467 according to an algorithm proposed by @vjeux in https://github.com/jlongster/prettier/issues/467#issuecomment-275230393
specifically, don't break opening elements such as 
```jsx
<div className="i use bootstrap and just put loooaads of classnames in here all the time">
hello world
</div>
```
=> Don't break up JSXOpeningElement if it only has a single text attribute

src/printer.js, tests/comments/__snapshots__/jsfmt.spec.js.snap
It's actually not needed to use conditionalGroup as we can use `ifBreak` and `join` for it. I was going to do it just for cleanup and found out that it also fixed two of the bugs we have with comments. That's great :p
Fixes #485
Fixes #486
=> Stop using conditionalGroup inside of UnionTypeAnnotation

src/printer.js, tests/arrows/__snapshots__/jsfmt.spec.js.snap, tests/arrows/long-contents.js
Alright, I had pushed a different branch and written up a long PR comment about tweaking the low-level printer's remeasuring logic. However, it made the low-level printer even more complicated, and I'm not willing to do that after I found this really simple fix.
The gist of it is that the printer has problems with a specific combination of groups. It needs to "remeasure" the code when it hits a hard line in flat mode; the printer thinks the whole expression fits because it hit a newline, but since it was a hard line, only the first line is sure to fit. The rest of the contents need to be "remeasured", so when a line is outputted we toggle a flag to force the printer to do that.
Unfortunately, there seems to be an edge case where a global flag doesn't work. If there are multiple groups …
=> Simplify arrow functions that use blocks

src/printer.js, tests/comments/__snapshots__/jsfmt.spec.js.snap
We don't call the generic print on the BinaryExpression itself, so we need to manually print those comments. It's going to be useful for my work on the MemberExpression :)
=> Properly print comments for BinaryExpression

src/comments.js, src/printer.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/dangling.js, tests/flow/this_type/lib/__snapshots__/jsfmt.spec.js.snap, tests/flow/traits/__snapshots__/jsfmt.spec.js.snap
In one code path, the dangling comment case is not properly handled. So I added the dangling comment, but it turns out that we only print manually in two node types: Program and BlockStatement. I made the generic printComment function print it everywhere but those two nodes. I tried to get rid of those special cases but unfortunately we need them there otherwise they are not printed at the right place.
Fixes #20
=> Proper support for dangling comments

README.md
When reading the Readme file I noticed that the first `foo` method has only 3 args but every other `foo` method has 4. Therefore, I am adding a 4th arg to the first `foo` method for consistency.
=> Adding a 4th arg to foo function for consistency

src/printer.js, tests/object_colon_bug/__snapshots__/jsfmt.spec.js.snap, tests/object_colon_bug/bug.js, tests/object_colon_bug/jsfmt.spec.js
It turns out that in an unlikely turn of event, the inner group can be inline and not print the opening paren but the outer group breaks and outputs the closing paren which generates invalid JavaScript.
I tried removing the group altogether and no tests failed, so I'm assuming the group wasn't needed in the first place. If it was, we should add tests to cover this.
Fixes #501
=> Remove extra group when printing object values

src/printer.js, tests/rest/__snapshots__/jsfmt.spec.js.snap, tests/rest/trailing-commas.js
=> Don't print trailing commas for object destructuring and rest

src/printer.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/issues.js
```js
foo({}
// Hi
);
```
prints
```js
foo({}
// Hi);
```
Edit: change from a test failure PR to a fix PR
=> Fix closing call expression commented out

README.md
Before e13bb7dbba5b9b725338f19cc196f75201b9fc82 `bracketSpacing` used to be about both `[]` and `{}` but now it's only about `{}`.
=> Update `bracketSpacing` comment to say it's about {}

CHANGELOG.md
Also, the tag for 0.14.1 hasn't been pushed to the repository, so the "changes" link is invalid – currently, you'd need https://github.com/jlongster/prettier/compare/0.14.0...efc3ee0488f72ddecda6c3605061327b737f1c22.
=> Add 0.14.1 to CHANGELOG

src/printer.js, tests/literal/__snapshots__/jsfmt.spec.js.snap, tests/literal/regex.js, tests/strings/__snapshots__/jsfmt.spec.js.snap, tests/strings/strings.js
I went with lowercase since with did so for hex numbers in #498. Tell me if you'd rather want uppercase.
Feel free to close this if prettier shouldn't care. :)
=> Print \x and \u escapes in strings and regexes lowercase

src/printer.js, test.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/flow/array-filter/__snapshots__/jsfmt.spec.js.snap, tests/flow/promises/__snapshots__/jsfmt.spec.js.snap, tests/last_argument_expansion/__snapshots__/jsfmt.spec.js.snap, tests/method-chain/__snapshots__/jsfmt.spec.js.snap, tests/method-chain/break-last-call.js, tests/method-chain/multiple-members.js
There are currently three issues related to suboptimal rendering of MemberExpression chains. The previous implementation was trying to flatten only a single group at the same time, but it didn't work well because we didn't have the full context to be able to make decisions.
In this implementation, I'm going through the entire chain at the same time and group it into logical units and make decisions based on this. It solves all the problems I can think of and if we need to tweak it in the future, it should be easy.
Fixes #268
Fixes #212
Fixes #21
=> [RFC] Reimplement MemberExpression printing

src/printer.js, tests/unary/__snapshots__/jsfmt.spec.js.snap, tests/unary/object.js
It seems like unary are unlikely to need parenthesis
Fixes #542
=> Whitelist UnaryExpression for parentless objects

.gitignore, src/printer.js, tests/ternaries/__snapshots__/jsfmt.spec.js.snap, tests/ternaries/jsfmt.spec.js
addresses #564
Also adds `test.js` back to source control
=> Fix ternary indent bug 

src/comments.js, src/printer.js, test.js, tests/classes/__snapshots__/jsfmt.spec.js.snap, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/jsx.js, tests/flow/async/__snapshots__/jsfmt.spec.js.snap, tests/flow/classes/__snapshots__/jsfmt.spec.js.snap, tests/flow/conditional/__snapshots__/jsfmt.spec.js.snap, tests/flow/destructuring/__snapshots__/jsfmt.spec.js.snap, tests/flow/dictionary/__snapshots__/jsfmt.spec.js.snap, tests/flow/iterable/__snapshots__/jsfmt.spec.js.snap, tests/flow/logical/__snapshots__/jsfmt.spec.js.snap, tests/flow/missing_annotation/__snapshots__/jsfmt.spec.js.snap, tests/flow/more_path/__snapshots__/jsfmt.spec.js.snap, tests/flow/new_react/__snapshots__/jsfmt.spec.js.snap, tests/flow/poly/__snapshots__/jsfmt.spec.js.snap, tests/flow/predicates-declared/__snapshots__/jsfmt.spec.js.snap, tests/flow/predicates-parsing/__snapshots__/jsfmt.spec.js.snap, tests/flow/refinements/__snapshots__/jsfmt.spec.js.snap, tests/flow/this/__snapshots__/jsfmt.spec.js.snap, tests/flow/this_type/__snapshots__/jsfmt.spec.js.snap, tests/flow/try/__snapshots__/jsfmt.spec.js.snap, tests/flow/type_args_nonstrict/__snapshots__/jsfmt.spec.js.snap, tests/flow/type_args_strict/__snapshots__/jsfmt.spec.js.snap
The original motivation for this change is trying to fix #560 where the comment was attached to the JSXText node instead of the JSXExpressionContainer because it used the globalPrecedingNode. In general, I don't think that it is very safe to attach a comment to a random node just because it happened to be before.
I tried to delete the globalPrecedingNode codepath and I think that it actually improves the results. I'll add inline comments in the pull request to explain the various changes.
Fixes #560
=> Remove the concept of globalPrecedingNode

src/printer.js, tests/last_argument_expansion/__snapshots__/jsfmt.spec.js.snap
I made sure that MemberExpressions where printed correctly but didn't do the same for CallExpression. Now it is! It is a bit less straightforward because the comments for the root CallExpression have already been printed, so we need to extract the first call out.
(This is the last place where we drop comments on the test suite, we can start enabling throwing when comments are dropped!)
=> Print CallExpression comments inside of memberChain

src/comments.js, tests/flow/binding/__snapshots__/jsfmt.spec.js.snap
Since we don't print EmptyStatement, we don't want to attach comments to them. I've tried actually printing the EmptyStatement but it messes up a ton of other things.
=> Do not attach comments to EmptyStatement

src/comments.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/first-line.js, tests/flow/annot/__snapshots__/jsfmt.spec.js.snap, tests/flow/get-def2/lib/__snapshots__/jsfmt.spec.js.snap, tests/flow/jsx_intrinsics.custom/lib/__snapshots__/jsfmt.spec.js.snap, tests/flow/new_react/fakelib/__snapshots__/jsfmt.spec.js.snap, tests/flow/node_tests/basic_file/__snapshots__/jsfmt.spec.js.snap, tests/flow/node_tests/basic_package/__snapshots__/jsfmt.spec.js.snap, tests/flow/node_tests/package_file/__snapshots__/jsfmt.spec.js.snap, tests/flow/node_tests/package_file_node_modules/foo/__snapshots__/jsfmt.spec.js.snap, tests/flow/rec/__snapshots__/jsfmt.spec.js.snap, tests/flow/record/__snapshots__/jsfmt.spec.js.snap, tests/flow/type-destructors/__snapshots__/jsfmt.spec.js.snap
If you removed it before #561, it would trigger an exception in the globalPreceding branch. But now that we don't have this hack anymore, it works fine.
Fixes #523
=> Remove first line special case

bin/prettier.js, package.json
This let's you run `pp(x) === pp(pp(x))` across an entire codebase quickly. I think it's small enough that we can merge it in to master while we are nailing down all the issues.
You can see the output in #610
=> Add --debug-check cli option

src/comments.js, src/util.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/preserve-new-line-last.js, tests/flow/more_generics/__snapshots__/jsfmt.spec.js.snap, tests/flow/while/__snapshots__/jsfmt.spec.js.snap
We want to preserve an empty line before the last comment. It is added as a trailing comment of the node and adding the same logic to detect if the next line is empty is working.
Fixes #566
=> Preserve empty line before last comment

.travis.yml
Add the "stable" alias to the list of node.js versions to test against. This will hit 7.x today, and 8.x pretty soon.
=> test on current release of node.js

src/printer.js, tests/while/__snapshots__/jsfmt.spec.js.snap
The reason why the indent has been added is to support the
```js
var x = a ||
b;
```
use case where we need a level of indentation. But inside of a `if` it just looks strange
```js
if (
a ||
b
) {
```
because the parent already indented the first line.
Fixes #567
=> Do not indent binary expressions inside of if

src/printer.js, tests/binary-expressions/__snapshots__/jsfmt.spec.js.snap, tests/binary-expressions/short-right.js
I've been trying to come up with a heuristic to stop putting small elements on a new line and I just realized that all the cases I found out only involved a single binary expression. If there's only a single operation, we can just put them on the same line (if it fits) and it's not going to look weird.
We do the same thing for MemberExpression where we only break if there are more than one ".".
Fixes #583
Fixes #503
=> Put short elements at right of single binary expression on same line

src/printer.js, src/util.js, tests/flow/get-def/__snapshots__/jsfmt.spec.js.snap, tests/flow/getters_and_setters_enabled/__snapshots__/jsfmt.spec.js.snap, tests/flow/missing_annotation/__snapshots__/jsfmt.spec.js.snap, tests/flow/more_react/__snapshots__/jsfmt.spec.js.snap, tests/flow/new_react/__snapshots__/jsfmt.spec.js.snap, tests/flow/overload/__snapshots__/jsfmt.spec.js.snap, tests/flow/react/__snapshots__/jsfmt.spec.js.snap, tests/flow/react_modules/__snapshots__/jsfmt.spec.js.snap, tests/flow/type-at-pos/__snapshots__/jsfmt.spec.js.snap, tests/flow/type_param_variance2/libs/__snapshots__/jsfmt.spec.js.snap
We already preserve blank lines inside of classes but not objects. It's still very common to have objects that represent classes (React.createClass) and having the same behavior there seems like a good idea. It does make the snapshot tests look better!
Fixes #554
=> Preserve blank lines inside of objects

src/printer.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/dangling_array.js
It was missing a softline. I copy and pasted the dangling handling for objects.
Fixes #624
=> Fix dangling comments for arrays

src/doc-debug.js
I was trying to debug #620 and got confused that it didn't show `//comment1`. Turns out we just fail silently if we can't print a node type. I added support for `line-suffix` and throw if we encounter a node type that we can't print.
=> Print line-suffix in --debug-print-doc

src/printer.js, tests/object-prop-break-in/__snapshots__/jsfmt.spec.js.snap, tests/object-prop-break-in/comment.js
Because the group was too high up, the comment would be taken into consideration to determine the size and it would break and add parenthesis. Adding a group where we actually want the ifBreak seems to be passing all the existing tests and fixes this edge case.
Fixes #655
=> Avoid unneeded parenthesis for colon with comments

src/printer.js, tests/method-chain/__snapshots__/jsfmt.spec.js.snap, tests/method-chain/first_long.js
Before, we would always concatenate the first `.call()` if the identifier started with a capital letter, but we do want to break if the content of the call doesn't fit in one line.
Fixes #639
=> Soft break the first member of a chain

src/comments.js, tests/conditional/__snapshots__/jsfmt.spec.js.snap, tests/conditional/comments.js, tests/conditional/jsfmt.spec.js
Now, all the variations of comments in ternaries are printed the same way.
Fixes #617
=> Stabilize comments inside of ternaries

src/comments.js, src/doc-builders.js, src/doc-printer.js, tests/trailing_comma/__snapshots__/jsfmt.spec.js.snap, tests/trailing_comma/trailing_whitespace.js
The reason why trailing comments on a line work with commas is because of a special `lineSuffix` document that delays printing the content until a \n is printed. But `lineSuffix` only worked for pure string. By making it work with arbitrary documents we can fix trailing commas with trailing comments.
Fixes #538
=> Fix trailing commas with a trailing comment

index.js, src/comments.js
This currently fails for 20 tests. I'm putting this up as a pull request so we can merge it once all the comments are properly printed :)
=> Ensure that all comments are printed

src/printer.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/method-chain/__snapshots__/jsfmt.spec.js.snap, tests/method-chain/comment.js
When there is a comment right before the first `.`, we want to force break such that the comment is printed on its own line.
Note: this needs to be based on-top of #667 as it always indent the first `.`
Fixes #613
=> Member chain comments

src/comments.js, src/printer.js, tests/classes/__snapshots__/jsfmt.spec.js.snap, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/flow/more_path/__snapshots__/jsfmt.spec.js.snap, tests/flow/new_react/__snapshots__/jsfmt.spec.js.snap, tests/flow/refinements/__snapshots__/jsfmt.spec.js.snap, tests/flow/try/__snapshots__/jsfmt.spec.js.snap
In #563 it looked odd that there was no space before `//`, it turns out that we don't automatically go to the new line for dangling comments. I think that we just should no matter what, so this is what this diff does.
Fixes #563
=> Always put a hardline before dangling comment

src/printer.js, tests/jsx-newlines/__snapshots__/jsfmt.spec.js.snap, tests/jsx-newlines/test.js
Fixes https://github.com/jlongster/prettier/issues/686
Was adding a `softline` for this case: `some text<span />` but shouldn't have been in this case: `some text\n<span />`. Now only adds the softline when necessary.
=> [JSX] Don't add newline following newline

bin/prettier.js
Current implementation with `process.stdout.clearLine` and `process.stdout.cursorTo` throws `TypeError: process.stdout.clearLine is not a function` and `TypeError: process.stdout.cursorTo is not a function` when `process.stdout` is not a tty.
=> Use `readline` api to manipulate `process.stdout` output.

docs/index.html
In the current demo, every time the code in the left panel is changed, the new code is stored in the URL hash, which pushes a new history entry. This effectively "breaks" the back button - after making some changes to the demo code, clicking the back button once has no effect, and refreshing the page shows the previous code change. This change calls `history.replaceState` instead, so a single click of the back button will return the browser to whatever page was open before navigating to the demo.
=> [Docs] Use replaceState API when demo code changes

src/printer.js, tests/flow/promises/__snapshots__/jsfmt.spec.js.snap
We inline function definitions but we shouldn't inline new expressions,
https://github.com/jlongster/prettier/commit/835befebf53da9f4a8a1e447cb33f1087e862ea3 introduced both call expressions and new expressions. Call expressions have been removed but looks like new haven't.
=> Do not inline new as last argument

src/printer.js, tests/object-prop-break-in/__snapshots__/jsfmt.spec.js.snap, tests/object_colon_bug/__snapshots__/jsfmt.spec.js.snap
I've started the discussion around it but I think that it was a mistake. It feels weird to add parenthesis on object values sometimes but not others. I think that it's best to let prettier do its work on staying under 80 columns based on the rules we added.
=> [RFC] Remove parenthesis object special case

README.md
As discussed on twitter: https://twitter.com/dan_abramov/status/831616492068290561
=> docs: Add pre-commit hook with 🚫💩 lint-staged section to the README

src/util.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/preserve-new-line-last.js, tests/flow/covariance/__snapshots__/jsfmt.spec.js.snap, tests/flow/coverage/__snapshots__/jsfmt.spec.js.snap, tests/flow/declare_module_exports/flow-typed/__snapshots__/jsfmt.spec.js.snap, tests/flow/destructuring/__snapshots__/jsfmt.spec.js.snap, tests/flow/more_generics/__snapshots__/jsfmt.spec.js.snap, tests/flow/overload/__snapshots__/jsfmt.spec.js.snap, tests/flow/reflection/__snapshots__/jsfmt.spec.js.snap, tests/flow/return/__snapshots__/jsfmt.spec.js.snap, tests/flow/while/__snapshots__/jsfmt.spec.js.snap, tests/trailing_comma/__snapshots__/jsfmt.spec.js.snap
There is an off by one error which made the algorithm not work all the time. In many cases, it actually is the opposite, so whenever you save, it adds/removes that line. I noticed it during the --debug-check run on our codebase but didn't investigate.
Fixes #723
=> Fix trailing new lines preservation

README.md
Other places we say we default to yarn but then we use npm, was confusing a bit.
=> docs(README): use yarn add for consistency

bin/prettier.js, src/options.js, src/printer.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/rest/jsfmt.spec.js, tests/trailing_comma/__snapshots__/jsfmt.spec.js.snap, tests/trailing_comma/jsfmt.spec.js
#591 wants to remove support for trailing commas in function args. Let's just go ahead and make the option support multiple values and default to no commas in function args, but you can turn on commas everywhere with `--trailing-comma=all`. 
I wasn't sure what to name the `compat` level. The idea is it's a mode that's compatible with older JS environments. If you pass `--trailing-comma` it defaults to `compat` so users shouldn't need to explicitly type out that option.
Fixes #266
=> Make trailing-comma option support 2 different modes

src/fast-path.js, tests/async/__snapshots__/jsfmt.spec.js.snap, tests/async/await_parse.js
Big props to @bakkot for mentioning that yield shouldn't be applied the same treatment.
Fixes #728
=> Remove extra parenthesis around await inside of unary expression

src/printer.js
@jlongster here comes the PR for the missing comment, as requested in https://github.com/jlongster/prettier/pull/742#issuecomment-281090628.
=> Add missing explanatory comment in ForStatement case

src/comments.js, tests/conditional/__snapshots__/jsfmt.spec.js.snap, tests/conditional/comments.js
Previously we would blindly put leading comments of the next expression, but we didn't account for a real trailing comment. By checking if the leadingNode is on the same line, we can correctly put it there when needed
Fixes #685
=> Correctly place trailing comments in conditionals

src/fast-path.js, tests/conditional/__snapshots__/jsfmt.spec.js.snap, tests/conditional/new-expression.js
=> Remove extra parens around ternary arguments of a new call

src/comments.js, tests/try/__snapshots__/jsfmt.spec.js.snap, tests/try/jsfmt.spec.js, tests/try/try.js
We skip EmptyStatement when generating the list of preceding/enclosing/following nodes but didn't do the same for the exceptions.
Fixes #695
=> Do not attach comments to EmptyStatements in try/catch

src/printer.js, tests/jsx-stateless-arrow-fn/__snapshots__/jsfmt.spec.js.snap, tests/method-chain/__snapshots__/jsfmt.spec.js.snap, tests/method-chain/first_long.js
In addition to Observable, $ or _, we should also add `this` to the list of things that are likely factory and not objects you want to apply things on directly.
I added a way to make the function call break on its own line when it doesn't fit in one line and indent. But I think that only having the indentation is enough, having the call on its own line feels weird.
Fixes #777
=> Add `this` for Member factory whitelist and remove softline

src/printer.js, tests/flow/try/__snapshots__/jsfmt.spec.js.snap, tests/flow/type-at-pos/__snapshots__/jsfmt.spec.js.snap, tests/try/__snapshots__/jsfmt.spec.js.snap, tests/try/empty.js
I originally wanted to expand it but I think that it may not be a good decision because it's very common for them to be empty and you want it to take as little space as possible.
I tried to remove all those conditions but I think that there are valid places where we always want to expand like empty if/for/while loops.
Fixes #778
=> Do not expand empty catch

src/doc-utils.js, src/printer.js, tests/strings/__snapshots__/jsfmt.spec.js.snap, tests/strings/strings.js
This is my take at #721. It's a little smarter in that it does run our formatting on the code, but it just removes all the lines except hardlines. I think this will interact a little bit better, and still enforce consistency. Still some work to do but I wanted to put this up before I need to run for a little bit.
=> Do not format template literals

package.json, tests/es6modules/__snapshots__/jsfmt.spec.js.snap, yarn.lock
Diagnosing a bug with the export default async fix, reverting this for now until patches land.
=> Revert babylon bump

src/doc-builders.js, src/doc-printer.js, src/printer.js, tests/line_suffix_boundary/__snapshots__/jsfmt.spec.js.snap, tests/line_suffix_boundary/boundary.js, tests/line_suffix_boundary/jsfmt.spec.js
The idea is that if you reach the end of the `}` inside of a template literal, we have to flush the trailing comma, otherwise it would generate invalid code. We also need the same special case for JSX.
I don't like adding yet another type of document but it seems like the most elegant way to solve the problem.
Fixes #623
=> Introduce line-suffix-boundary

src/fast-path.js, tests/binary-expressions/__snapshots__/jsfmt.spec.js.snap, tests/flow/logical/__snapshots__/jsfmt.spec.js.snap, tests/flow/predicates-inferred/__snapshots__/jsfmt.spec.js.snap, tests/flow/refinements/__snapshots__/jsfmt.spec.js.snap
It seems like precedence for this combination of operators is very unclear to people (myself included) and consistently adding parenthesis there would be good.
Fixes #773
=> [RFC] Add parenthesis around && inside of ||

src/options.js
```js
// test.js
var prettier = require('./');
prettier.format('a=1');
```
```js
node test.js
// doesn't crash
```
Fixes #801
=> Fix empty options

src/printer.js, tests/strings/__snapshots__/jsfmt.spec.js.snap, tests/strings/jsfmt.spec.js, tests/strings/strings.js, tests/strings/template-literals.js
This should fix the problem with commas, but I wonder if we're going to run into anything else.
=> Eagerly evaluate `ifBreak` when processing template literals (fixes #795)

src/printer.js, tests/do/__snapshots__/jsfmt.spec.js.snap, tests/do/do.js, tests/do/jsfmt.spec.js
The code that supported `do` was likely from some recast time and didn't work anymore.
Fixes #810
=> Properly support `do`

src/fast-path.js, tests/conditional/__snapshots__/jsfmt.spec.js.snap, tests/es6modules/__snapshots__/jsfmt.spec.js.snap
We need to add parenthesis around function expressions if they are named otherwise the name leak, but if the function is not named then it's just superfluous.
The conditional change is due to a bad use of switch case where it would fall through the next one. We don't want parenthesis there.
=> Do not put parenthesis around not named default export

src/printer.js, tests/arrows/__snapshots__/jsfmt.spec.js.snap, tests/arrows/short_body.js
By adding a group, we can avoid adding a newline if the expression fits in a single line.
Fixes #800
=> Put short body of arrow functions on the same line

src/printer.js, tests/assignment_comments/__snapshots__/jsfmt.spec.js.snap, tests/assignment_comments/assignment_comments.js, tests/assignment_comments/jsfmt.spec.js
The `hasLeadingOwnLineComment` helper is going to be useful for other places where we just used `n.comments` as a proxy for it.
Fixes #660
=> Preserve new lines for comments after `=`

src/comments.js, tests/class_comment/__snapshots__/jsfmt.spec.js.snap, tests/class_comment/comments.js, tests/class_comment/jsfmt.spec.js
Instead of trying to figure out a complicated way to preserve their correct position, it's easier to just migrate those comments before the class.
Fixes #693
Fixes #694
=> Migrate class comments to the beginning

src/printer.js, tests/method-chain/__snapshots__/jsfmt.spec.js.snap, tests/method-chain/logical.js
I'm not really sure what a general rule is for those, but starting with LogicalExpressions should be good. Outside of identifiers, function calls and logical expressions, there aren't a lot of things you'd put there in real code anyway.
Fixes #822
=> Allow breaking for logical expressions in member chains

src/printer.js, tests/jsx/__snapshots__/jsfmt.spec.js.snap, tests/jsx/expression.js
Fixes https://github.com/prettier/prettier/issues/843
=> [JSX] Don't wrap JSX Elements in parentheses if they are inside JSX Expression Containers

src/comments.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/last-arg.js
The issue is that the comment algorithm attaches it to the return type / value but we want to attach it to the previous one.
Fixes #612
=> Fix comment after the last argument of a function

src/comments.js, tests/import/__snapshots__/jsfmt.spec.js.snap, tests/import/comments.js
Since this is extremely rare, I just took the easy way out and if you are adding a comment inside the "as" node, I just move it outside. We could be more fancy but that works.
Fixes #620
=> Stabilize `import as` comments

src/printer.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/jsx.js
In #596, I fixed a bunch of jsx expression comment edge cases and happened to add a softline there. But it turns out that it's not needed and is actually harmful :)
Fixes #712
=> Fix jsx expression comment that break

src/printer.js, tests/last_argument_expansion/__snapshots__/jsfmt.spec.js.snap, tests/last_argument_expansion/overflow.js
```js
SuperSuperSuperSuperSuperSuperSuperSuperSuperSuperSuperSuperLongCall((err, result) => {
// comment
});
```
currently breaks into
```js
SuperSuperSuperSuperSuperSuperSuperSuperSuperSuperSuperSuperLongCall((
err,
result,
) => {
// comment
});
```
which looks bad, instead this PR makes it break
```js
SuperSuperSuperSuperSuperSuperSuperSuperSuperSuperSuperSuperLongCall(
(err, result) => {
// comment
}
);
```
which look better
=> Inline last arg function arguments

src/fast-path.js, tests/es6modules/__snapshots__/jsfmt.spec.js.snap
It turns out that my fix was not correct. We should not add parenthesis for FunctionDeclaration instead of checking if the function expression is named.
Fixes #819
=> Keep parenthesis on export default function

src/fast-path.js, tests/flow/iter/__snapshots__/jsfmt.spec.js.snap, tests/flow/missing_annotation/__snapshots__/jsfmt.spec.js.snap, tests/flow/predicates-declared/__snapshots__/jsfmt.spec.js.snap, tests/flow/refinements/__snapshots__/jsfmt.spec.js.snap
This is a neat trick from the React codebase. It helps highlight the fact that this is an assignment and not a comparison which is subtle to realize.
Fixes #861
=> Add parenthesis around assignments

src/printer.js, tests/it/__snapshots__/jsfmt.spec.js.snap, tests/it/it.js, tests/it/jsfmt.spec.js
This happens very frequently that naming a test makes the entire line go > 80 columns and requires to indent everything which takes a lot more space. We've had this being reported multiple times and it also affects a lot of tests inside of fb.
Fixes #159
(Note, this is built on-top of #841 but github doesn't handle stacked pull requests well... You want to look at the second commit here: https://github.com/prettier/prettier/pull/842/commits/a4bab0c64e2a765b9968dcd49b6829b643235adc )
=> Do not break long it calls

src/comments.js, src/printer.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/flow_union.js
The comments infra has been architected with trailing operators and fails for leading `|`. Instead of having leading comments, we can put trailing comments on the previous one and use the same technique as assignment to deal with the indentation.
Fixes #849
=> Fix flow union comments

README.md
Simple change to add a real world example of CLI usage, because it wasn't immediately obvious to me how it should actually look
=> Add CLI Example to Readme

README.md
- Use double quotes for cmd.exe support. See #761.
- Remove redundant example and merge it into the previous.
=> Improve readme CLI usage example

src/printer.js, tests/jsx/__snapshots__/jsfmt.spec.js.snap, tests/jsx/open-break.js
Fixes https://github.com/prettier/prettier/issues/940
Made me a bit concerned about my use of `forcedBreak`, the incremental updating is good for perf but much less simple than running one giant `willBreak` at the end. Other bugs like this could result in the future if the code is changed and developers forget to update `forcedBreak` whenever a node is printed.
=> [JSX] Break if opening element breaks

src/printer.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/return-statement.js, tests/flow/generics/__snapshots__/jsfmt.spec.js.snap, tests/method-chain/__snapshots__/jsfmt.spec.js.snap
Fixes https://github.com/prettier/prettier/issues/916
What a beast! Code ended up being reasonably concise but was pretty hard for me to figure out. 
I'm pretty sure this is comprehensive, but my confidence has been higher. I also don't love my approach; open to suggestions!!
I went through every node type in [the spec](https://github.com/babel/babylon/blob/master/ast/spec.md) and tested every kind that I thought might have a leading sub-node to which a comment might be attached (eg; in binaryexpression, the "left" attribute can get the comment without the binaryexpression getting the comment as leading). 
Pretty much all the test cases are significant and fail without something in here; the only exception I think is a kitchen sink I threw in.
=> Recursively find leading comments inside ReturnStatements

src/comments.js, src/printer.js, tests/empty_paren_comment/__snapshots__/jsfmt.spec.js.snap, tests/empty_paren_comment/empty_paren_comment.js, tests/empty_paren_comment/jsfmt.spec.js
The logic was already implemented in #802 but for a single case. I just added all the cases added in the awesome @umidbekkarimov
Fixes #956
=> Make comments around empty parenthesis be inside

src/comments.js, tests/object_property_comment/__snapshots__/jsfmt.spec.js.snap, tests/object_property_comment/comment.js, tests/object_property_comment/jsfmt.spec.js
This is the largest firing unstability on the Facebook codebase.
Fixes #906
=> Stabilize comment after object label

src/printer.js, tests/arrows/__snapshots__/jsfmt.spec.js.snap, tests/arrows/call.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/method-chain/__snapshots__/jsfmt.spec.js.snap
In practice, trying to allow calls to be inlined is causing a lot of code to look very weird and unstable as seen by the four issues this is fixing. It also requires us to add a conditional group and do hackery around it.
Fixes #959
Fixes #760
Fixes #615
Fixes #625
=> Only allow same-line arrow-less body for explicit nodes

package.json
GH redirects, but no reason not to link directly to the org 😄
=> Update repo links

src/printer.js, tests/objects/__snapshots__/jsfmt.spec.js.snap, tests/objects/expand.js
This was intended for object expressions. I tried to remove it for ObjectTypeAnnotation but it changes a ton of stuff as it's used all over the place in many different contexts. We should clean it up but in a later PR :)
Fixes part of #975
=> Do not respect newlines for object destructuring pattern

editors/emacs/prettier-js.el
Use print-width instead of width, bringing prettier-js.el in line with https://github.com/prettier/prettier/blob/205458a8d12ab39a8ad0bb0e815e017481108f2e/bin/prettier.js#L33
=> Use correct print-width argument

src/printer.js, tests/assignment/__snapshots__/jsfmt.spec.js.snap, tests/assignment/binaryish.js, tests/assignment/jsfmt.spec.js, tests/assignment_comments/__snapshots__/jsfmt.spec.js.snap, tests/binary-expressions/__snapshots__/jsfmt.spec.js.snap
Printing the first line of a binary expression next to the `=` leads to weird cases where the first expression is parenthesised and doens't read well with chained conditionals as they don't align well. This makes it behave the same was as `if` tests.
Fixes #863
=> Add softline to assignment of binary expressions

src/printer.js, tests/exports/__snapshots__/jsfmt.spec.js.snap, tests/exports/jsfmt.spec.js, tests/exports/test.js
=> Fix exports

src/printer.js, tests/flow/annot/__snapshots__/jsfmt.spec.js.snap, tests/flow/annot/annot.js, tests/optional-type-name/__snapshots__/jsfmt.spec.js.snap
Experimental PR trying to solve #969.
=> No parenthesis for Flow shorthand with one arg

bin/prettier.js, src/fast-path.js, src/printer.js, src/util.js
A follow-up to @vjeux 's https://github.com/prettier/prettier/pull/936#discussion_r106489469. There are other functions declared in `printer.js` that are actually unused but I guess we want to keep them available.
=> Remove unused code.

src/printer.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/switch.js
=> Fix additional empty line switch case comment

src/comments.js, tests/import/__snapshots__/jsfmt.spec.js.snap, tests/import/comments.js
=> Fix import declaration comments

src/doc-utils.js, tests/break-calls/__snapshots__/jsfmt.spec.js.snap, tests/break-calls/parent.js, tests/last_argument_expansion/__snapshots__/jsfmt.spec.js.snap
=> Add breakParent support for willBreak

src/comments.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/last-arg.js
In #856, it handled a bunch of cases but missed class methods
Fixes #905
=> Preserve comment position for last arg or method

src/parser.js
Adding typescript broke the docs build and is causing issues with create-react-app bundler. Let's use a small hack to hide it from static analysis, but still works in node.
Fixes #986
=> Hide typescript parser from static analysis

src/printer.js, tests/arrows/__snapshots__/jsfmt.spec.js.snap, tests/arrows/call.js
I could go either way but it doesn't seem a big deal to inline them. I don't expect it to be very common anyway
Fixes #990
=> Inline class expressions for bracket-less arrow functions

src/printer.js, tests/first_argument_expansion/__snapshots__/jsfmt.spec.js.snap, tests/first_argument_expansion/jsfmt.spec.js, tests/first_argument_expansion/test.js, tests/flow/arraylib/__snapshots__/jsfmt.spec.js.snap, tests/flow/union_new/__snapshots__/jsfmt.spec.js.snap, tests/last_argument_expansion/__snapshots__/jsfmt.spec.js.snap, tests/last_argument_expansion/overflow.js
A more restricted heuristic to address #888. Allows:
```js
setTimeout(function() {
thing();
}, 500);
```
(and other literals and identifiers) but not,
```js
func(function() {
thing();
}, true, false); // too many args
func(() => {
thing();
}, {yes: true, cats: 5}); // too complex
```
=> Group first arg for inline functions

src/printer.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/flow/arrows/__snapshots__/jsfmt.spec.js.snap, tests/flow/intersection/__snapshots__/jsfmt.spec.js.snap, tests/return/__snapshots__/jsfmt.spec.js.snap, tests/return/binaryish.js, tests/return/jsfmt.spec.js
It looks better when the first element is aligned with the rest and this is consistent with the way we render `if` test.
Fixes #866
=> Add parens around return for binaryish expressions

src/printer.js, tests/method-chain/__snapshots__/jsfmt.spec.js.snap, tests/method-chain/comment.js
We already had a special case for it for a group of 2 elements but now that we are also going in this codepath for 3 if we merge, then we need to do the same here.
Fixes #930
=> Stabilize comment on member chain with three elements

src/printer.js, tests/flow/new_react/fakelib/__snapshots__/jsfmt.spec.js.snap, tests/flow/type_param_variance2/libs/__snapshots__/jsfmt.spec.js.snap, tests/flow_generic/__snapshots__/jsfmt.spec.js.snap, tests/flow_generic/break.js, tests/flow_generic/jsfmt.spec.js
While looking at an instability on the React codebase ( https://github.com/sebmarkbage/react/commit/ba1299acc2c3b66ec1e093c201bcede421a8caa0#diff-2550aa3d377452ae29361f5e53c51c10 ), I realized that we don't let them break which makes the code look weird.
So I added the ability for them to break :)
=> Add ability for flow generics to break

src/comments.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/flow/coverage/__snapshots__/jsfmt.spec.js.snap, tests/flow/declare_module_exports/flow-typed/__snapshots__/jsfmt.spec.js.snap, tests/flow_method/__snapshots__/jsfmt.spec.js.snap, tests/flow_method/comment.js
Right now it's only doing one test for begin/end, but in the issue #1037, we have two nodes that have the same start but different end. The current implementation incorrectly sorts them and the identifier ends up being before the container and therefore the comment search doesn't recurse into it.
Fixes #1037
Fixes #938
=> Fix comment sorting location

src/printer.js, tests/binary-expressions/__snapshots__/jsfmt.spec.js.snap, tests/binary-expressions/comment.js, tests/comments/__snapshots__/jsfmt.spec.js.snap
The root cause is that we're calling `printComments` with an empty string, meaning that the leading/trailing comments are not correctly inserted at the right location.
So, the way to fix it is to call `p => concat(parts)` but because we're mutating the array in place, it doesn't work. We need to mutate it and create a copy. But, the root call is actually checking the shape of the parts array which our code is now breaking...
```js
// Don't include the initial expression in the indentation
// level. The first item is guaranteed to be the first
// left-most expression.
parts.length > 0 ? parts[0] : "",
```
The consequence is that binary expressions are no longer indented correctly if expressions have a comment (but now it places the comment properly!), which seems like an okay trade-off. …
=> [RFC] Fix comment location for binary expressions

src/printer.js, tests/flow/async_iteration/__snapshots__/jsfmt.spec.js.snap, tests/flow/async_iteration/jsfmt.spec.js
Babylon 7 removed ForAwaitStatement in favor of ForOfStatement with `"await": true`.
estree discussion:
https://github.com/estree/estree/pull/138
babylon pr:
https://github.com/babel/babylon/pull/349
=> Add support for ForOfStatement with await flag

src/printer.js, tests/flow/def_site_variance/__snapshots__/jsfmt.spec.js.snap, tests/flow/def_site_variance/jsfmt.spec.js, tests/flow/dictionary/__snapshots__/jsfmt.spec.js.snap, tests/flow/dictionary/jsfmt.spec.js, tests/flow/getters_and_setters_enabled/__snapshots__/jsfmt.spec.js.snap, tests/flow/getters_and_setters_enabled/jsfmt.spec.js, tests/flow/more_annot/__snapshots__/jsfmt.spec.js.snap, tests/flow/more_annot/jsfmt.spec.js, tests/flow/object-method/__snapshots__/jsfmt.spec.js.snap, tests/flow/object-method/jsfmt.spec.js, tests/flow/typeapp_perf/__snapshots__/jsfmt.spec.js.snap, tests/flow/typeapp_perf/jsfmt.spec.js
Working on getting all the tests to pass with babylon.
This adds support for the variance node type [added in Babylon 7](https://github.com/babel/babel/issues/4722).
=> Fix parsing flow variance on babylon 7

src/printer.js
A couple node types were renamed in Babylon 7 to match their Flow counterparts.
NumericLiteralTypeAnnotation:
https://github.com/babel/babylon/pull/332
ExistsTypeAnnotation:
https://github.com/babel/babylon/pull/322
=> Remove a few node types

src/printer.js, tests/function_single_destructuring/__snapshots__/jsfmt.spec.js.snap, tests/function_single_destructuring/jsfmt.spec.js, tests/function_single_destructuring/test.js
This is very common for stateful react functional components. It also matches last object expansion. I think that we should only do that for a single argument in function definitions though, unlike the last for function calls.
Fixes #1019
=> Hug on single object destructuring function

src/printer.js, tests/flow/intersection/__snapshots__/jsfmt.spec.js.snap, tests/flow/union_new/__snapshots__/jsfmt.spec.js.snap, tests/intersection/__snapshots__/jsfmt.spec.js.snap, tests/intersection/intersection.js, tests/intersection/jsfmt.spec.js
We started using the same logic for union and intersection but then added a special case for `a & {}`. It turns out that they should be handled completely differently in practice.
The heuristic i'm using is if you go from object to non-object or vis-versa, then inline, otherwise go to the next line and indent (like &&).
Fixes #864
Fixes #1017
=> Special logic for flow intersection

src/printer.js, tests/arrows/__snapshots__/jsfmt.spec.js.snap, tests/arrows/currying.js
If you write your code in a functional way where you have an arrow function for each argument, it looks better for them to be inline. I can't imagine any case where it would be used in a different way if we limit to a single argument.
Fixes #1065
=> Add support for currying

README.md, bin/prettier.js, index.js
Hi friends!
I figured this was better as a PR instead of an issue. We'd like to adopt Prettier and part of that is build it into our continuous integration. We run everything through Gulp (hence why I also forked btholt/gulp-prettier too) which makes use of the Node API. The `list-different` which is available to the CLI is precisely what we need but since that lives in the bin and not in the Node library it can't be used. This moves this logic back into the library exported from `index.js` as a tiny function that just makes use of the `format` function.
Is it very hard to keep ahold of the old string and compare it with the new string from Prettier? No, definitely not. This is what I did with my fork of gulp-prettier (which I borrowed the idea from facebook/react#9187). But I figured if …
=> Add check method to Prettier Node API.

src/printer.js, tests/exact_object/__snapshots__/jsfmt.spec.js.snap, tests/exact_object/jsfmt.spec.js, tests/exact_object/test.js
Fixes #1089.
Where do you want me to add a test?
=> Fix printing of exact object flow type annotations

package.json, tests/flow/predicates-abstract/__snapshots__/jsfmt.spec.js.snap, tests/flow/predicates-abstract/jsfmt.spec.js, tests/flow/predicates-declared/__snapshots__/jsfmt.spec.js.snap, tests/flow/predicates-declared/jsfmt.spec.js, tests/flow/predicates-inferred/__snapshots__/jsfmt.spec.js.snap, tests/flow/predicates-inferred/jsfmt.spec.js, tests/flow/predicates-parsing/__snapshots__/jsfmt.spec.js.snap, tests/flow/predicates-parsing/jsfmt.spec.js, yarn.lock
We landed a number of fixes in latest beta, including:
- Allow statics in Flow interfaces ([#427](https://github.com/babel/babylon/pull/427))
- Fix Flow predicate handling ([#428](https://github.com/babel/babylon/pull/428))
Also (with https://github.com/prettier/prettier/pull/1064) there's support for object type spread!
=> Bump babylon to 7.0.0-beta.8

README.md
At first, I just wanted to fix a typo from https://github.com/prettier/prettier/pull/1104
I felt ridiculous trying to make a PR just for removing one word, so I checked the whole `README` and tried to make it a little bit nicer.
=> Update README.md: fixed typo, added links

src/printer.js, tests/interface/__snapshots__/jsfmt.spec.js.snap, tests/interface/break.js
We break on `class` before `extends` but didn't for `interface`. Now we do in the same way. Also TIL that `interface` was an actual keyword in JavaScript :P
=> Ability for interface to break

src/printer.js, tests/ignore/__snapshots__/jsfmt.spec.js.snap, tests/ignore/ignore.js
Pretty much took the example from #1109.
The important caveat is that `// prettier-ignore` has to be the only or _last_ comment attached to a node.
I could update this to use a `.filter(...).length` check so it can exist _anywhere_ in the comments, but felt that doesn't really make sense cosmetically to warrant it.
=> Support "// prettier-ignore" in comment blocks

src/printer.js, tests/ignore/__snapshots__/jsfmt.spec.js.snap, tests/ignore/ignore.js
Per @vjeux's comment:
> https://github.com/prettier/prettier/pull/1125#issuecomment-291930315
This now supports:
```js
function giveMeSome() {
a(  a  ); // prettier-ignore
// shouldn't I return something?  :shrug:
}
```
I'm using `comment.value.trim() === "prettier-ignore"`, as that is what property is what was there before.  @vjeux mentioned `comment.text === "prettier-ignore"`, but I don't know if this was pseudo-code or the "right way" now.
=> "// prettier-ignore" position within comments doesn't matter

src/printer.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/switch.js, tests/switch/__snapshots__/jsfmt.spec.js.snap, tests/switch/empty_lines.js
This changes how we print new lines between switch cases, thus fixing #945.
Instead of inserting lines after a case, this inserts before.
=> Fix trailing comment on switch case

README.md, bin/prettier.js, index.js, src/comments.js, src/doc-builders.js, src/doc-debug.js, src/doc-printer.js, src/options.js, src/printer.js
I'm really sorry for having to create another PR, don't want to spam this project, but Github doesn't allow me to reopen the previous PR #920 because the branch has been rebased while the PR was closed.
=> [RFC] Indent with tabs

src/printer.js, tests/flow/config_module_system_node_resolve_dirname/subdir/custom_resolve_dir/testproj2/__snapshots__/jsfmt.spec.js.snap, tests/variable_declarator/__snapshots__/jsfmt.spec.js.snap, tests/variable_declarator/jsfmt.spec.js, tests/variable_declarator/string.js
This is not a general fix but it solves some issues that people are seeing where prettier goes > 80 columns.
Fixes #1141
Also fixes part of #1110
=> Allow to break after = for strings

src/doc-debug.js
This fixes a bug where you are unable to print the doc representation for a doc that contains a `line-suffix-boundary`.
For example:
```
<a>{}</a>
```
(I imagine this was accidentally missed in https://github.com/prettier/prettier/pull/750)
https://prettier.github.io/prettier/#%7B%22content%22%3A%22%3Ca%3E%7B%7D%3C%2Fa%3E%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Atrue%7D%7D
=> Add doc debug printing for line-suffix-boundary

editors/emacs/README.md
Provide documentation for users who aren't using `js-mode` as their default JS major-mode.
=> Enhance prettier-js.el README

src/printer.js, tests/switch/__snapshots__/jsfmt.spec.js.snap, tests/switch/empty_lines.js
#1136 accidentally removed all the empty lines between statements inside of switch cases. I just brought back the logic and made sure to only use it for everything but the last line.
=> Fix switch new lines

src/printer.js, tests/flow/intersection/__snapshots__/jsfmt.spec.js.snap, tests/intersection/__snapshots__/jsfmt.spec.js.snap, tests/intersection/intersection.js
Now properly indents all the combinations of objects and non objects.
Fixes #1076
=> Improve printing of chained intersections

src/printer.js, tests/flow_return_arrow/__snapshots__/jsfmt.spec.js.snap, tests/flow_return_arrow/jsfmt.spec.js, tests/flow_return_arrow/parens.js
=> Add parens around arrow function return type

src/util.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/before-comma.js
We need to call the `skipToLineEnd` which skips `,` after an inline comment. So we have to put it inside of the while loop as you can have many comments, a comma and then many more comments.
Fixes #964
=> Fix comment detection before comma

src/fast-path.js, tests/binary_math/__snapshots__/jsfmt.spec.js.snap, tests/binary_math/jsfmt.spec.js, tests/binary_math/parens.js
=> Add parenthesis for binary operators

src/printer.js, tests/arrow-call/__snapshots__/jsfmt.spec.js.snap, tests/arrow-call/arrow_call.js, tests/arrow-call/jsfmt.spec.js, tests/arrows/__snapshots__/jsfmt.spec.js.snap, tests/last_argument_expansion/__snapshots__/jsfmt.spec.js.snap, tests/method-chain/__snapshots__/jsfmt.spec.js.snap
I've tried a lot of places where to fix this and this is the only one that gives correct results. This is likely not exhaustive but works for that use case. It's been reported twice in issues and I've seen it happen a few other times so we probably want to get it fixed.
Fixes #922
Fixes #797
Fixes #974
=> Add newline for bracket-less arrow functions that return calls

src/fast-path.js, tests/break-calls/__snapshots__/jsfmt.spec.js.snap, tests/conditional/__snapshots__/jsfmt.spec.js.snap, tests/conditional/no-confusing-arrow.js, tests/flow/dump-types/__snapshots__/jsfmt.spec.js.snap, tests/last_argument_expansion/__snapshots__/jsfmt.spec.js.snap
I'm unclear whether anyone was ever confused by this but the eslint page is kind of compelling
```js
// The intent is not clear
var x = a => 1 ? 2 : 3;
// Did the author mean this
var x = function (a) { return 1 ? 2 : 3 };
// Or this
var x = a <= 1 ? 2 : 3;
```
Adding a parenthesis makes it valid with `{"allowParens": true}` rule. Note that if this option is not enabled, the code would not pass lint in the first place.
=> Add parenthesis for no-confusing-arrow rule

src/printer.js, tests/jsx_template/__snapshots__/jsfmt.spec.js.snap, tests/jsx_template/jsfmt.spec.js, tests/jsx_template/styled-components.js
There are two commits in this PR:
We already hug a bunch of things inside of `{}`. It seems that it's a good idea to do it for template literals as well. I don't think I've seen anyone actually indent them.
If there is a single expression and a single template literal, then a lot of people in the jsx-style world inline it. I've also myself used this for markdown and printed it that way. So we probably should print it that way.
Note that I'm checking for children.length === 1, this means that if there's any whitespace, this is not going to be true and will not enter this case. So it WON'T reformat
```js
<style>
{`
color: red;
`}
</style>
```
into
```js
<style>{`
color: red;
`}</style>
```
which is great. You have to opt-in to the second style in order to get it.
Fixes for #1090
=> Improve jsx output for style components

src/printer.js, tests/flow/declare_export/__snapshots__/jsfmt.spec.js.snap, tests/flow/es6modules/__snapshots__/jsfmt.spec.js.snap, tests/method-chain/__snapshots__/jsfmt.spec.js.snap, tests/method-chain/break-last-member.js
It turns out that the top member expression doesn't go through the member chain logic. Let's give it the ability to break for now.
Fixes #1031
Fixes #1100
=> Add ability to break for top member expression

src/printer.js, tests/flow/getters_and_setters_enabled/__snapshots__/jsfmt.spec.js.snap, tests/member/__snapshots__/jsfmt.spec.js.snap
This should address a concern of #1036
=> Allow to break for member expressions after =

src/printer.js, tests/member/__snapshots__/jsfmt.spec.js.snap, tests/member/expand.js
The problem actually isn't in the last arg printing logic. We already appropriately propagate breaks [here](https://github.com/prettier/prettier/blob/master/src/printer.js#L2202) in that logic.
The problem is that member expressions are using `conditionalGroup` but not manually propagating breaks. This logic was suppressing it, so we need to propagate it.
=> Propagate hard breaks within member expressions (fixes #1117)

src/comments.js, tests/trailing_comma/__snapshots__/jsfmt.spec.js.snap, tests/trailing_comma/trailing_whitespace.js
It turns out that we can't reliably detect with the ast if a comment is before or after the ). In order to fix this same problem with `if` I added the `getNextNonSpaceNonCommentCharacter` function. We can use the same here to fix the problem.
Fixes #933
=> Fix function trailing comment location

src/printer.js, tests/last_argument_expansion/__snapshots__/jsfmt.spec.js.snap, tests/last_argument_expansion/overflow.js
In #847, I used a heuristic to find if the element was going to be expanded. But, it wasn't 100% accurate because we couldn't know in which conditionalGroup we would land. We added a way for the parent to tell that function if we should be in `expandLastArg`. By replacing the condition by this variable, it now fixes the issues!
This is so good that adding the right abstraction fixes problems across the board :)
Fixes #997
=> Fix overflow for last argument expansion

src/printer.js
We shouldn't be reading from the printed document but instead look at the AST. This was really easy, it can either be EmptyStatement, BlockStatement or anything else.
=> Remove isCurlyBracket and isEmptyBlock

src/printer.js, tests/rest/jsfmt.spec.js
We changed RestProperty/SpreadProperty to RestElement/SpreadElement in https://github.com/babel/babylon/pull/384.
=> Fix trailing comma for rest element in Babylon

src/doc-utils.js, tests/last_argument_expansion/__snapshots__/jsfmt.spec.js.snap, tests/last_argument_expansion/edge_case.js
This one is pretty crazy. In #927, I changed
```js
concat(["(", join(concat([", "]), printed), ")"]),
```
into
```js
concat(["(", join(concat([", "]), printedLastArgExpanded), ")"]),
```
which makes the example in #1203 look ugly. The crazy thing is that `JSON.stringify(printed) === JSON.stringify(printedLastArgExpanded)`. So they are deep equal but not the same object. In a non-mutative world, this should cause any problem, but we actually mutate those to propagate breaks.
In the break propagation, we only looked at the first one in case of a conditional group. But, because the two were the same object then it also applied to the second one and happened to be the correct behavior! When I changed that piece of code to be two distinct objects, it no longer worked by accident and caused a …
=> Fix edge cases triggered by newlines in arrow functions

README.md
Fixes #1242 by removing the (I hope) now outdated warning that Prettier is still in beta :tada:.  Congrats to the whole team on making it to 1.0!
=> [1242]: Prettier 1.0 is the stabler release we've been waiting for

src/doc-printer.js, tests/typescript/conformance/types/functions/__snapshots__/jsfmt.spec.js.snap, tests/typescript/conformance/types/tuple/__snapshots__/jsfmt.spec.js.snap
In #1257, I discovered that if there's a `""` doc at the end, it's not going to trim the previous one correctly. It also happens to fix a few existing things.
=> Remove trailing whitespace

src/comments.js, src/util.js, tests/flow/getters_and_setters_enabled/__snapshots__/jsfmt.spec.js.snap
As I was debugging #1248, I found out that the code to fix was actually making things worse. The other two branches are for decorators and deleting some random value of a function. I ran all the tests and the flow object is actually now preserving empty lines and didn't change anything else.
I'd rather remove all those and if something comes up then fix it properly upstream than having those crutches that we don't know why they exist anymore.
=> Get rid of fixFaultyLocations code

src/printer.js
This is in line with similar checks in printer.js
Fixes #1237
=> Fixing n.comments check in printer

src/comments.js, src/printer.js, tests/no-semi/__snapshots__/jsfmt.spec.js.snap, tests/no-semi/comments.js
=> no-semi comments

README.md
per Rahul Sethi on twitter: https://twitter.com/rahul1sethi/status/852811834964836352
I should have matched jsx as well as js with my pre-commit hook, I don't use
react myself so I didn't think about it.
=> Match jsx files in pre-commit hook

src/util.js, tests/switch/__snapshots__/jsfmt.spec.js.snap, tests/switch/empty_lines.js
Fixes #1262
```js
switch (a) {
case x:
case y:
call();
case z:
call();
}
```
becomes
```js
switch (a) {
case x:
case y:
call();
case z:
call();
}
```
=> Fix isPreviousLineEmpty on Windows

bin/prettier.js
This fixes the issue mentioned in #1287. To test it I I modified a single file (to introduce a linting mistake) and ran it across 100+ files. After I saw that that particular file had been fix I hit `Ctrl+C` to abort the process. I looked at the output of the files and saw that they had all been written and there were no empty files.
=> Write out change CLI changes synchronously. Fixes #1287.

README.md
When I read "🚫💩 lint-staged" in the list of possible pre-commit hooks my brains reads the emoji part as "not good, don't use it". For this reason, the first time I read the README I just skipped it as an option. It may be that I'm weird but maybe there are others like me 😉 
If you check [lint-staged's repo](https://github.com/okonet/lint-staged) they also don't use the emoji for the title so I don't think it would be a big problem if gets removed from the README.
=> Remove emoji part from lint-staged's name

bin/prettier.js
Closes #1246 
@vjeux:
> For this issue, I can see two things:
>
> 1. Use fs.readFileSync instead of going through glob is there is no special patterns. If you give the actual name of a file, we should throw if it's not there.
> […]
It turns out that`node-glob` has a handy function `.hasMagic`, which tells you if a given string has any globbable patterns in it. All I had to do was call it when we iterate over the filenames.
I tested this manually; I'm not sure how to add tests for the prettier cli.
```bash
$ stat non-existent-file.js
stat: cannot stat 'non-existent-file.js': No such file or directory
$ prettier non-existent-file.js; echo $?
0
```
```bash
$ stat non-existent-file.js
stat: cannot stat 'non-existent-file.js': No such file or directory
$ node bin/prettier.js …
```
=> Skip globbing filenames with node-glob when the filename is not a glob

src/comments.js, tests/template/__snapshots__/jsfmt.spec.js.snap, tests/template/comment.js
The implementation was checking if the comment was inside of the expression range, which seems like a good idea. Unfortunately, the expression range is not what's inside of `${}` but the actual AST node, which incidentally doesn't include comments. So the logic was off and returned `undefined` which threw afterwards.
Another solution is to find the first quasi where start is > comment start. This means that the comment appeared between the quasi before and this one... therefore in the expression before!
The flow parser has issues with unicode where it makes node location invalid, there are likely other places where node locations are off. So instead of throwing with a weird error, let's attach it to the first one if it doesn't work.
Fixes #1293
=> Fix template literal comments

index.js, src/printer.js
In #1250, @jeresig reported that adding // prettier-ignore on a file that has a ton of conditional group still took 1.7s. The issue is that we're printing before checking for the comment. Swaping the two had the unfortunate side effect of not marking the comments as being printed, so I had to skip that safety check if there's a prettier-ignore.
With this change, adding prettier-ignore makes the file be printed instantly!
=> Do not print the sub-tree when using prettier-ignore

src/doc-utils.js, tests/performance/__snapshots__/jsfmt.spec.js.snap, tests/performance/jsfmt.spec.js, tests/performance/nested-real.js, tests/performance/nested.js
This is the second part of the fix for the performance regression seen in #1250. In #1217, for correctness reasons, we're now traversing all the conditional groups. This means that we're now in O(n^2). But, in practice, many of those groups are === between each others. So we only need to recurse through one of the instances to know if it's going to break.
This makes the first example go from not terminating to being instant. The second one going from not terminating to taking ~1s. We can also make it instant by tweaking the printing phase, but that's for another PR.
=> Bail when traversing === groups

src/printer.js, tests/last_argument_expansion/__snapshots__/jsfmt.spec.js.snap, tests/last_argument_expansion/break.js
We've had this issue since the beginning and I tagged it as 1.0 but haven't managed to fix it by then. We shouldn't allow things to break in the argument list if we are in the last argument expansion mode. It turns out that we now have all the building blocks needed to fix this:
- have a special way to flag when we are printing the last argument expansion in the code that prints the argument list
- have a way to remove all the softlines from the argument list
Fixes #1301
=> Avoid breaking arguments for last arg expansion

bin/prettier.js
Now that typescript development has started, each contributor has been adding this as a supported flag themselves.
This just adds it as an allowed option, with a warning that support for this parser is experimental.
I also tried to structure this a bit future proof, in case other experimental parsers come along.
(This came up in pursuit of @vjeux's #1306)
=> Add typescript as a valid parser value

editors/jetbrains/README.md
=> Add jestbrains filewatcher docs

README.md
[prettier_d](https://github.com/josephfrazier/prettier_d.js) is like [eslint_d], but it runs `prettier` instead of`eslint`. This eliminates the Node.js startup delay from all but the first run of `prettier_d`, making it a snappier experience.
[eslint_d]: https://github.com/mantoni/eslint_d.js
Related discussion:
* https://github.com/prettier/prettier/issues/575#issuecomment-277368389
* https://github.com/prettier/prettier/issues/918#issuecomment-294130268
* https://github.com/prettier/prettier/pull/753#issuecomment-294339207
=> Add prettier_d to Related Projects

README.md
This lets you configure Vim to format your code even more frequently.
=> Add information about Vim's other autocmd events

src/printer.js, tests/typescript/conformance/types/firstTypeNode/__snapshots__/jsfmt.spec.js.snap, tests/typescript/conformance/types/firstTypeNode/firstTypeNode.ts, tests/typescript/conformance/types/firstTypeNode/jsfmt.spec.js
This adds the printer implementation for the `TSFirstTypeNode`. I'm not sure this is correct, since I call `path.getParentNode()` in the `TypeAnnotation` branch but instead of getting the direct parent (which would be `TSFirstTypeNode`) I actually get the parent's parent, thus I have to walk down that path one node again.
When looking for the parent node it probably just skips unknown nodes. I'll take a look at`path.getParentNode`'s implementation later this week.
=> add printer branch for TSFirstTypeNode

src/printer.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/function-declaration.js
`leadingComment` and `trailingComment` are babylon-specific, we should use `comments` which is what prettier adds.
Fixes #1335
=> Fix arrow function parenthesis with comments in flow

src/printer.js, tests/empty_paren_comment/__snapshots__/jsfmt.spec.js.snap, tests/empty_paren_comment/class.js
Turns out, you can't blindly print this node. We need a deeper fix but let's revert this fix for now.
Fixes #1348
=> Fix duplicate comments in classes

src/printer.js, tests/binary-expressions/__snapshots__/jsfmt.spec.js.snap, tests/binary-expressions/if.js
We only want to break for && and ||, not for ===.
Used to print
```js
if (
VeryVeryVeryVeryVeryVeryVeryVeryLong ===
VeryVeryVeryVeryVeryVeryVeryVeryLong
) {
}
```
This is a side effect of #1344.
=> Only break for conditionals

src/printer.js, tests/typescript/conformance/types/never/__snapshots__/jsfmt.spec.js.snap, tests/typescript/conformance/types/never/jsfmt.spec.js, tests/typescript/conformance/types/never/never.ts, tests/typescript/conformance/types/nonNullExpression/__snapshots__/jsfmt.spec.js.snap, tests/typescript/conformance/types/nonNullExpression/jsfmt.spec.js, tests/typescript/conformance/types/nonNullExpression/nonNullExpression.ts, tests/typescript/conformance/types/symbol/__snapshots__/jsfmt.spec.js.snap, tests/typescript/conformance/types/symbol/jsfmt.spec.js, tests/typescript/conformance/types/symbol/symbol.ts, tests/typescript/conformance/types/thisType/__snapshots__/jsfmt.spec.js.snap, tests/typescript/conformance/types/thisType/jsfmt.spec.js, tests/typescript/conformance/types/thisType/thisType.ts, tests/typescript/conformance/types/undefined/__snapshots__/jsfmt.spec.js.snap, tests/typescript/conformance/types/undefined/jsfmt.spec.js, tests/typescript/conformance/types/undefined/undefined.ts
This adds the printer implementation for some of the simpler TypeScript nodes mentioned in #1306.
It does not add tests since I haven't come around writing them (copy 'n pasting them from the TypeScript repo), maybe tomorrow though my week is pretty full.
Just thought I'd share this before someone else puts in the effort for this.
=> add printer branches for some TypeScript nodes

src/printer.js, tests/flow/objectTypeProperty/__snapshots__/jsfmt.spec.js.snap, tests/flow/objectTypeProperty/jsfmt.spec.js, tests/flow/objectTypeProperty/objectTypeProperty.js
Following up the discussion on #1367.
This PR separates the `TypeAnnotation` from the preceding colon that may or may not be there depending on the context. Instead of leaving it up to the `TypeAnnotation` to find out what the context is, it's now the `TypeAnnotation`'s parent's job.
I also added a test containing multiple `ObjectTypeProperties` since they were hard to get right.
=> parent decides how to print type annotations

src/printer.js
I broke master sry. I thought the `typeParameters` only existed in TypeScript :flushed:
=> fix typeParameters printing TSFunctionType w/o breaking flow

src/printer.js, tests/typescript/conformance/types/variableDeclarator/__snapshots__/jsfmt.spec.js.snap, tests/typescript/conformance/types/variableDeclarator/jsfmt.spec.js, tests/typescript/conformance/types/variableDeclarator/variableDeclarator.ts
Before the change it would have printed this:
```ts
type MyMap = Map<T, P>;
```
=> fix VariableDeclarator not printing type parameters

src/printer.js, tests/typescript/conformance/ambient/__snapshots__/jsfmt.spec.js.snap, tests/typescript/conformance/ambient/ambientDeclarations.ts, tests/typescript/conformance/ambient/jsfmt.spec.js, tests/typescript/conformance/types/thisType/__snapshots__/jsfmt.spec.js.snap, tests/typescript/custom/declare/__snapshots__/jsfmt.spec.js.snap, tests/typescript/custom/declare/declareModifier.d.ts, tests/typescript/custom/declare/jsfmt.spec.js
Also (accidentally) fixed a bug with flow `declare class`.
Declare modifier support for `enum` and `namespace` is obviously blocked on their respective implementations.
=> Add TypeScript delcare modifier support for variables, classes and functions

src/printer.js, tests/no-semi/__snapshots__/jsfmt.spec.js.snap, tests/no-semi/no-semi.js
Sorry I missed this [earlier](https://github.com/prettier/prettier/pull/1129#issuecomment-291997555).
=> Require '(a || b).c++' to have a preceding ; in no-semi style

src/printer.js, tests/strings/__snapshots__/jsfmt.spec.js.snap, tests/template/__snapshots__/jsfmt.spec.js.snap, tests/template/call.js
I'm not sure that this is a good idea. A current workaround is to remove the parenthesis.
Fixes #786
=> [RFC] Do not indent calls with a single template literal argument

src/printer.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/ternaries/__snapshots__/jsfmt.spec.js.snap, tests/ternaries/parenthesis.js
All of the discussions around ternaries are for the form
```js
cond1 ? elem1_if : cond2 ? elem2_if : elem_else
```
but some of them are for the form
```js
cond1 ? cond2 ? elem2_if : elem2_else : elem1_else
```
which is more rare and would be good to call out by adding parenthesis.
```js
cond1 ? (cond2 ? elem2_if : elem2_else) : elem1_else
```
Note that we only want parenthesis if it's written inline, otherwise the indentation is good enough to understand the flow:
```js
cond1
? cond2 ? elem2_if : elem2_else
: elem1_else
```
=> Add parenthesis for unusual nested ternaries

src/comments.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/last-arg.js
We already had the logic but only applied it for comments on their own line, we should also do it if they are inline.
Fixes #1380
=> Preserve inline comment as last argument

src/fast-path.js, src/printer.js, src/util.js, tests/last_argument_expansion/__snapshots__/jsfmt.spec.js.snap, tests/ternaries/__snapshots__/jsfmt.spec.js.snap, tests/ternaries/parenthesis.js
This was added in order to follow some eslint rule but it's only confusing when it doesn't break, when it breaks the indentation makes it clear what is happening and you don't need parenthesis.
Fixes #1379
=> Only add parenthesis on ternaries inside of arrow functions if doesn't break

src/printer.js, tests/flow/react/__snapshots__/jsfmt.spec.js.snap, tests/flow/type_args_nonstrict/__snapshots__/jsfmt.spec.js.snap, tests/flow/type_args_strict/__snapshots__/jsfmt.spec.js.snap, tests/flow/type_param_defaults/__snapshots__/jsfmt.spec.js.snap
We have a space for function arguments and it looks weird without.
=> Add space around `=` for flow generics default arguments

src/printer.js, tests/flow_function_parentheses/__snapshots__/jsfmt.spec.js.snap, tests/flow_function_parentheses/single.js
This has been reported internally. It looks --very-- weird to have it indented the way it was.
=> Don't break for unparenthesised single argument flow function

src/printer.js, tests/arrays/__snapshots__/jsfmt.spec.js.snap, tests/arrays/empty.js
We never want to break on those at it looks very weird. The reason why I didn't add this yet is because whenever it triggered in the past, the root cause was something else and it helped identify things to fix. But now the remaining ones I'm seeing are no longer underlying issues and they're just about this breaking unnecessarily, so we should just fix it.
=> Don't break on empty arrays and objects

src/printer.js, tests/method-chain/__snapshots__/jsfmt.spec.js.snap, tests/method-chain/bracket_0.js
In practice, we never want to break on `[0]`. By not doing that, it forces prettier to find a more suitable break placement.
Fixes #1418
=> Do not break on [0]

src/printer.js, tests/function/__snapshots__/jsfmt.spec.js.snap, tests/function/single_expand.js
This is getting subtle where the groups need to be in a precise position but that works :)
Fixes #1409
=> Break inline object first in function arguments

src/printer.js, tests/typescript/conformance/internalModules/importDeclarations/__snapshots__/jsfmt.spec.js.snap, tests/typescript/conformance/internalModules/importDeclarations/circularImportAlias.ts, tests/typescript/conformance/internalModules/importDeclarations/exportImportAlias.ts, tests/typescript/conformance/internalModules/importDeclarations/importAliasIdentifiers.ts, tests/typescript/conformance/internalModules/importDeclarations/invalidImportAliasIdentifiers.ts, tests/typescript/conformance/internalModules/importDeclarations/jsfmt.spec.js, tests/typescript/conformance/internalModules/importDeclarations/shadowedInternalModule.ts, tests/typescript/conformance/types/moduleDeclaration/__snapshots__/jsfmt.spec.js.snap
Adding the last big batch of TypeScript nodes:
* `TSAsyncKeyword`
* `TSExportKeyword`
* `TSNamespaceFunctionDeclaration`
* `TSProtectedKeyword`
* `TSPublicKeyword`
* `TSHeritageClause`
* `TSExpressionWithTypeArguments`
Some of the formatting is far from pretty at this point though.
#1480 #13
=> Implement TypeScript keywords, namespace functions and class heritage

.gitignore, src/printer.js, tests/typescript/conformance/classes/__snapshots__/jsfmt.spec.js.snap, tests/typescript/conformance/classes/classDeclarations/classAbstractKeyword/__snapshots__/jsfmt.spec.js.snap, tests/typescript/conformance/types/constructorType/__snapshots__/jsfmt.spec.js.snap, tests/typescript/custom/call/__snapshots__/jsfmt.spec.js.snap, tests/typescript/custom/call/callSignature.ts, tests/typescript/custom/call/jsfmt.spec.js, tests/typescript/custom/new/__snapshots__/jsfmt.spec.js.snap, tests/typescript/custom/new/jsfmt.spec.js, tests/typescript/custom/new/newKeyword.ts, tests/typescript/custom/typeParameters/__snapshots__/jsfmt.spec.js.snap, tests/typescript/custom/typeParameters/callAndConstructSignatureLong.ts, tests/typescript/custom/typeParameters/functionTypeLong.ts, tests/typescript/custom/typeParameters/interfaceParamsLong.ts, tests/typescript/custom/typeParameters/jsfmt.spec.js, tests/typescript/custom/typeParameters/typeParametersLong.ts
* Fix `interface<T> {}`
* Support `new <T>(): any` and `new <T> => any`
* Support `<T>() => any` and `<T>(): any`
* Refactor type parameter formatting to use the same code as flow.
* Add custom tests for long lines.
=> Fix handling of new keyword and call signatures and improve type parameter formatting

src/printer.js, tests/strings/__snapshots__/jsfmt.spec.js.snap, tests/template/__snapshots__/jsfmt.spec.js.snap, tests/template/inline.js
In 1.3.0, we shipped a change that makes template literal always inlined as single arguments of a function. The problem with template literals is that they whitespace is significant so we can't change it. There are two cases:
```js
call(`
template
template
`);
```
and
```js
call(
`template
template`
);
```
If you always make the same decision to inline, you're going to be wrong for the other use case. The solution that I found that works is to figure out if there's a `\n` before the backtick `` ` ``. If that's the case, then don't inline, otherwise do. We're trying to avoid looking at the source as much as possible but this is one example where we actually don't have a choice if we want to keep the output sane.
1.3.0 made the jest codebase significantly worse because of this. The issue is …
=> Respect template inline-ness

src/printer.js, tests/typescript/compiler/__snapshots__/jsfmt.spec.js.snap, tests/typescript/compiler/badArrayIndex.ts, tests/typescript/compiler/jsfmt.spec.js
I have no idea if it's even valid but it threw on 8 typescript tests, now it doesn't.
```js
TypeError: Cannot read property 'type' of null
at printMemberLookup (prettier/src/printer.js:3062:16)
```
=> Print empty member lookup

src/fast-path.js, tests/async/__snapshots__/jsfmt.spec.js.snap, tests/async/await_parse.js
Fixes #1512.
Also removes parentheses which were being inserted in `x[(await a)]`.
This is actually still too aggressive; `await` has the precedence of a unary operator, and needs parenthesization in exactly the cases a unary operator does. You can compare its case in fast-path with that of UnaryExpression to see the excess.
In particular, prettier inserts all of the parentheses below, none of which are necessary:
```js
async a => {
a + (await b);
a || (await b);
[...(await a)];
!{ ...(await a) };
(await a) ? b : c;
};
```
I'm going to leave those cases alone in this PR, since they're less obviously dumb.
=> Less aggressive parenthesization of await

editors/emacs/README.md, editors/emacs/prettier-js.el
Prettier would cause great havoc on some older projects that I work on. Disabling prettier when I work on these projects was really painful (modify init file, then restart emacs). This PR adds a new `prettier-mode` global minor mode that lets you quickly enable or disable prettier by just toggling the mode.
I am by no means an elisp guru, so it would be great if someone who has more experience writing emacs modes could review this change.
=> [Editor support] Make prettier into a global minor mode that can be toggled on and off

src/printer.js, tests/typescript/compiler/__snapshots__/jsfmt.spec.js.snap, tests/typescript/compiler/functionOverloadsOnGenericArity1.ts
Previously,
```ts
interface C {
f<T>(): string;
}
```
was printed as:
```ts
interface C {
f(): string;
}
```
#1480
=> TypeScript: print typeParameters on TSMethodSignature

src/printer.js, tests/regex/jsfmt.spec.js
Turns out n.value is NaN for regexes in typescript, go figure. Just moving the two if statements is working to fix the issue.
Fixes #1526
=> Fix TypeScript regex

src/fast-path.js, tests/typescript_as/__snapshots__/jsfmt.spec.js.snap, tests/typescript_as/as.js, tests/typescript_as/jsfmt.spec.js
I put it at the same place where `a in b` is handled.
Fixes #1524
=> Add parens around `as`

src/typescript-ast-nodes.js, tests/typescript/compiler/__snapshots__/jsfmt.spec.js.snap, tests/typescript/compiler/commentsInterface.ts
#1480
- defines `TSFunctionType` AST nodes
- fixes printing of comments inside function type node
- test is based on TypeScript's test `compiler/commentsInterface.ts` which was failing
fixes that:
```
../TypeScript/tests/cases/compiler/commentsInterface.ts
../TypeScript/tests/cases/compiler/commentsInterface.ts: Error: Comment "*param help" was not printed. Please report this error!
at astComments.forEach.comment (/mnt/c/Users/Lucas Azzola/Code/prettier/index.js:69:13)
at Array.forEach (native)
at ensureAllCommentsPrinted (/mnt/c/Users/Lucas Azzola/Code/prettier/index.js:67:15)
at format (/mnt/c/Users/Lucas Azzola/Code/prettier/index.js:85:3)
at formatWithShebang (/mnt/c/Users/Lucas Azzola/Code/prettier/index.js:91:12)
at Object.module.exports.format (/mnt/c/Users/Lucas …
```
=> TypeScript: define TSFunctionType AST node

src/printer.js, tests/typescript/conformance/internalModules/importDeclarations/__snapshots__/jsfmt.spec.js.snap
A large proportion of the `ast(prettier(input)) !== ast(input)` failures with the TypeScript parser are caused by this issue.
I've opened an issue (eslint/typescript-eslint-parser#257) on the parser side, but the workaround is simple enough for now.
=> TypeScript: workaround eslint/typescript-eslint-parser#257

src/fast-path.js, tests/typescript/conformance/expressions/asOperator/__snapshots__/jsfmt.spec.js.snap, tests/typescript/conformance/expressions/asOperator/asOperatorContextualType.ts, tests/typescript/conformance/expressions/asOperator/jsfmt.spec.js
Fixes this case:
```ts
-var x = (v => v) as (x: number) => string;
+var x = v => v as (x: number) => string;
```
#1480
=> TypeScript: ArrowFunctionExpression needs parens in TSAsExpression

src/printer.js, tests/typescript/conformance/internalModules/importDeclarations/__snapshots__/jsfmt.spec.js.snap, tests/typescript/custom/stability/__snapshots__/jsfmt.spec.js.snap, tests/typescript/custom/stability/jsfmt.spec.js, tests/typescript/custom/stability/moduleBlock.ts
This one was easier than I thought it would be 👍 
#1480
=> TypeScript: remove extraneous newline with namespace exports

src/typescript-ast-nodes.js, tests/typescript/compiler/__snapshots__/jsfmt.spec.js.snap, tests/typescript/compiler/commentInNamespaceDeclarationWithIdentifierPathName.ts, tests/typescript/webhost/__snapshots__/jsfmt.spec.js.snap, tests/typescript/webhost/jsfmt.spec.js, tests/typescript/webhost/webtsc.ts
This fixes `TypeError: parent.body.filter is not a function`  in a number of cases.
#1480
=> TypeScript: add TSNamespaceFunctionDeclaration to ast-types

bin/prettier.js, src/printer.js, tests/typescript/compiler/__snapshots__/jsfmt.spec.js.snap, tests/typescript/compiler/emptyGenericParamList.ts, tests/typescript/compiler/errorOnInitializerInInterfaceProperty.ts, tests/typescript/conformance/es6/Symbols/__snapshots__/jsfmt.spec.js.snap, tests/typescript/conformance/es6/Symbols/jsfmt.spec.js, tests/typescript/conformance/es6/Symbols/symbolProperty15.ts, tests/typescript/conformance/interfaces/interfaceDeclarations/__snapshots__/jsfmt.spec.js.snap, tests/typescript/conformance/interfaces/interfaceDeclarations/interfaceWithMultipleBaseTypes2.ts, tests/typescript/conformance/interfaces/interfaceDeclarations/jsfmt.spec.js
1.
```
-var x: I<>;
+var x: I;
```
2.
```
interface Foo {
-    bar: number = 5;
+  bar: number
}
```
3. (ignored in debug-check)
```
"type": "ClassProperty",
"key": {
-              "type": "Literal",
-              "value": "prop1"
+              "type": "Identifier",
+              "name": "prop1"
},
```
4.
```
interface I {
-    [Symbol.iterator]?: { x };
+  [Symbol.iterator]: { x }
}
```
5.
```
interface I {
-  3?<T>();
+  3<T>()
```
#1480
=> TypeScript: fix a handful of ast(prettier(input)) issues

src/fast-path.js, src/parser.js, src/printer.js, src/typescript-ast-nodes.js, tests/typescript/compiler/__snapshots__/jsfmt.spec.js.snap, tests/typescript/compiler/castOfAwait.ts, tests/typescript/compiler/castParentheses.ts, tests/typescript/compiler/castTest.ts, tests/typescript/conformance/es6/templates/__snapshots__/jsfmt.spec.js.snap, tests/typescript/conformance/es6/templates/jsfmt.spec.js, tests/typescript/conformance/es6/templates/templateStringWithEmbeddedTypeAssertionOnAdditionES6.ts, tests/typescript/conformance/expressions/functionCalls/__snapshots__/jsfmt.spec.js.snap, tests/typescript/conformance/expressions/functionCalls/callWithSpreadES6.ts, tests/typescript/conformance/expressions/functionCalls/jsfmt.spec.js
A lot of the parse errors with TypeScript are due to parsing `TSTypeAssertionExpression` (type casts, `<string>foo`) with JSX enabled.
We didn't actually have a print definition for `TSTypeAssertionExpression`, so I've added that.
I also added a super-naive attempt at detecting whether a document is JSX or not:
* If it contains `</`, it is JSX.
* If it contains `</` on a line that doesn't start with `//`, it is JSX. 
This is to prevent false-positives with `/// <reference path="" />`
#1480 #1538
=> TypeScript: add TSTypeAssertionExpression and naive TSX detection

src/parser.js, tests/typescript_tsx/__snapshots__/jsfmt.spec.js.snap, tests/typescript_tsx/jsfmt.spec.js, tests/typescript_tsx/not-react.ts, tests/typescript_tsx/react.tsx, tests_config/run_spec.js
Improves the existing JSX detection by making a naive guess, parsing in the guessed JSX mode, and falling back to the opposite if the code fails to parse.
#1538
=> TypeScript: add fallback for JSX detection

tests_config/run_spec.js
It previously referred to an undefined variable.
=> Fix variable name in getParsersToVerify()

tests_config/run_spec.js
This makes it easier to just use `AST_COMPARE=1 npm test`, instead of
having to run `npm test` separately.
=> Also run normal tests when AST_COMPARE=1

README.md, bin/prettier.js
This addresses https://github.com/prettier/prettier/issues/1552#issuecomment-300043294
As described in the comment linked above, these changes also prevent
using `--write` with `--debug-check`. Additionally, a `--debug-check`
failure causes the process to exit with a non-zero code.
=> Mention --debug-check in CLI section of README

tests_config/run_spec.js
This makes it match the environment variable, which is consistent with
the other variables.
=> tests: Rename `RUN_AST_TESTS` variable to `AST_COMPARE`

README.md
The options section in the README (which appears to be the primary source of truth for documentation) had incorrectly conflated the bracketSpacing and jsxBracketSameLine options into a single table row (using the human readable name for one, the machine readable names for another, and combined descriptions of both). This patch splits the row into two accurate ones.
=> Fix incorrect options documentation in README

README.md
Since Vim doesn't honor `formatprg` exit codes, let's recommend using
Neoformat instead.
Fixes https://github.com/prettier/prettier/issues/743
Fixes https://github.com/prettier/prettier/issues/1191
Fixes https://github.com/prettier/prettier/issues/1466
=> Add warning about vanilla Vim integration, recommend Neoformat

README.md
As discussed on #1564, improve the clarity of the descriptions for the bracketSpacing and semicolons options by describing what the options do rather than what their CLI overrides do; These were confusing as written because these options default to true, and their CLI overrides trigger the opposite behavior.
=> Improve clarity of boolean option documentation

src/printer.js, tests/flow/getters_and_setters_disabled/__snapshots__/jsfmt.spec.js.snap, tests/flow/getters_and_setters_enabled/__snapshots__/jsfmt.spec.js.snap, tests/flow/objectTypeProperty/__snapshots__/jsfmt.spec.js.snap, tests/flow/objectTypeProperty/objectTypeProperty.js
Before: `type T = { get method(): void }` -> `type T = { method: () => void };`
Demo: https://prettier.github.io/prettier/#%7B%22content%22%3A%22type%20T%20%3D%20%7B%20get%20method()%3A%20void%20%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D
---
After: `type T = { get method(): void }` -> `type T = { get method(): void };`
Demo: `echo 'type T = { get method(): void }' | prettier --stdin --parser flow`
Demo: `echo 'type T = { get method(): void }' | prettier --stdin --parser flow --debug-check`
---
This passes `AST_COMPARE=1 npm test -- …
=> (Flow) Preserve getter/setter info on ObjectTypeProperty

src/parser.js, tests/return-outside-function/__snapshots__/jsfmt.spec.js.snap, tests/return-outside-function/jsfmt.spec.js, tests/return-outside-function/return-outside-function.js
This makes it easier to format code snippets including a `return`
statement, without having to format the entire function. For example,
given the following code:
```js
function f() {
return someVeryLongStringA && someVeryLongStringB && someVeryLongStringC && someVeryLongStringD
}
```
a developer could select the line containing `return`, then use
prettier to format the code to:
```js
function f() {
return (
someVeryLongStringA &&
someVeryLongStringB &&
someVeryLongStringC &&
someVeryLongStringD
);
}
```
which can then be reindented by the editor.
---
Related to https://github.com/prettier/prettier/issues/593
=> (Babylon) Allow `return` outside function

README.md, Rationale.md
I didn't want to disrupt any of the original language in the readme intro, but I added a footnote and an asterisk anytime we mention that all original styling is removed, since it isn't really true anymore.
Added [multi-line objects](https://github.com/shaunlebron/prettier/blob/shaun-readme-clarify/Rationale.md#multi-line-objects) to the Rationale and linked to it in the footnote.
[Related to #1588](https://github.com/prettier/prettier/issues/1588)
=> Clarify when original styling is significant

editors/emacs/README.md, editors/emacs/prettier-js.el
Prettier should always run when prettier-mode is active. Also, disabling prettier as a global minor mode allows its users to hook prettier-mode to their favorite javascript mode(s) like this:
```
(require 'prettier-js)
(add-hook 'js2-mode-hook 'prettier-mode)
(add-hook 'web-mode-hook 'prettier-mode)
...
```
I believe this is how most of minor modes work, what do you think?
Cheers and thanks for this awesome tool! 😄
=> Always run prettier if prettier-mode is active

package.json, tests/typescript/conformance/internalModules/importDeclarations/__snapshots__/jsfmt.spec.js.snap, yarn.lock
The new typescript-eslint-parser version wraps interfaces in export declarations accordingly.
=> upgrade typescript-elint-parser and enable most ts tests again

scripts/run-external-typescript-tests.js
Output:
```
12873 good, 573 skipped, 314 bad
98% of 13760 files processed without errors.
83      TypeError: Cannot read property 'type' of undefined
62      Error: Value undefined is not a valid document
58      prettier(input) !== prettier(prettier(input))
56      Error: did not recognize object of type "TSInterfaceHeritage"
42      ast(input) !== ast(prettier(input))
6       TypeError: Cannot read property 'some' of undefined
4       Error: Comment "<omitted>" was not printed. Please report this error!
3       Error: Comment location overlaps with node location
Writing errors to './errors/' directory
```
=> TypeScript: do not report SyntaxErrors as errors when running external tests

bin/prettier.js
This makes it possible to simultaneously check for formatting errors and
fix them, which can be useful for CI services. For example, a CI service
could run:
prettier --list-different --write $FILES || git diff --exit-code
to show the formatting errors. Before this change, it would be necessary
to do:
prettier --list-different $FILES || (prettier --write $FILES; git diff --exit-code)
Here are some commands which are useful to verify that the outputs and
exit codes of `prettier --list-different` and `prettier --write` have
not changed:
./bin/prettier.js --list-different index.js src/*.js bin/*.js; echo $?
./bin/prettier.js --write index.js src/*.js bin/*.js; echo $?
=> Allow `--write` to be used with `--list-different`

README.md
I'm a vim user, and I use prettier on a few of my projects, but not all.
The Prettier docs listed ways to make prettier run automatically on save
(and other autocmd events), but I needed a way to invoke it manually.
After spending some time finding the right vim config, I decided it
could be useful to others as well.
Fixes #1615
=> Add instruction on how to set up key binding in vim

editors/emacs/prettier-js.el
Currently the package summary makes no sense when viewed from Emacs's package manager, this fixes it.
=> Make emacs package summary clearer

.travis.yml, package.json, src/parser.js, src/printer.js, yarn.lock
This fixes https://github.com/prettier/prettier/issues/1558
and uses `AST_COMPARE=1` on Travis tests, so we can make sure those
don't break going forward.
=> Upgrade typescript parser, fix and run AST tests on Travis

package.json, tests/flow/declare_export/jsfmt.spec.js, tests/flow/es_declare_module/flow-typed/jsfmt.spec.js, tests/flow/es_declare_module/jsfmt.spec.js, tests/flow/getters_and_setters_disabled/jsfmt.spec.js, tests/flow/getters_and_setters_enabled/jsfmt.spec.js, tests/flow/refinements/jsfmt.spec.js, tests/flow_generic/__snapshots__/jsfmt.spec.js.snap, tests/flow_generic/generic.js, tests/unicode/jsfmt.spec.js, yarn.lock
We finally dropped a new version of Babylon! Sorry been swamped :(
Fixes #1248.
Fixes #1268.
Fixes #1311.
Fixes #1430.
@vjeux worth enabling babylon on all the flow tests for coverage (as a separate PR of course)?
=> Bump Babylon and enable additional tests

src/printer.js, tests/jsx-text-wrap/__snapshots__/jsfmt.spec.js.snap, tests/jsx-text-wrap/test.js
There is a bug in the fill implementation in #1120 when text starts with a whitespace.
Input:
```javascript
leading_whitespace =
<div> First Second Third Fourth Fifth Sixth Seventh Eighth Ninth Tenth Eleventh Twelfth Thirteenth Fourteenth</div>
```
Output on master:
```javascript
leading_whitespace = (
<div>
{" "}
First Second Third Fourth Fifth Sixth Seventh Eighth Ninth Tenth Eleventh Twelfth Thirteenth Fourteenth
</div>
);
```
The `fill` algorithm expects to be passed alternating content and whitespace parts, starting with content. Before this PR it was possible for it to start with a whitespace, throwing off the algorithm.
Output with this PR:
```javascript
leading_whitespace = (
<div>
{" "}
First Second Third Fourth Fifth Sixth Seventh Eighth Ninth Tenth Eleventh
Twelfth Thirteenth …
```
=> Fix fill wrapping when text starts with whitespace

tests/flow_class_field/__snapshots__/jsfmt.spec.js.snap, tests/flow_class_field/jsfmt.spec.js, tests/flow_class_field/override.js
Fixed in latest Babylon, but forgot to add a test in https://github.com/prettier/prettier/pull/1668!
Fixes #1481.
=> Add test for flow class field override

src/printer.js, tests/jsx-whitespace/__snapshots__/jsfmt.spec.js.snap, tests/jsx-whitespace/jsfmt.spec.js, tests/jsx-whitespace/test.js, tests/jsx_escape/__snapshots__/jsfmt.spec.js.snap
This PR preserves unusual unicode whitespace characters.
Currently any whitespace that matches a unicode whitespace character gets converted to a normal space. This means we lose whitespace characters with special meanings (such as non-breaking spaces and zero width spaces).
In this PR we no longer treat anything other than newline, tab, and space characters as whitespace. This allows us to preserve these unusual unicode whitespace characters as is.
With this change I believe we no longer need to preserve multiple space characters when formatting JSX, because they can no longer contain unusual whitespace we know that they will collapse down to a single space when rendering so it is safe to do that in Prettier.
=> Preserve unusual unicode whitespace

src/printer.js, tests/jsx-split-attrs/__snapshots__/jsfmt.spec.js.snap, tests/jsx-text-wrap/__snapshots__/jsfmt.spec.js.snap, tests/jsx-text-wrap/test.js
A fix for https://github.com/prettier/prettier/issues/1581
This PR no longer allows a line break between tags and text in JSX. This fixes an issue that was blocking adoption at Facebook (https://github.com/prettier/prettier/issues/1581#issuecomment-300975032) with little adverse effects for our standard formatting.
=> Hug JSX text after multi line tags

src/comments.js, tests/import/__snapshots__/jsfmt.spec.js.snap, tests/import/comments.js
We used to use isBlock as a heuristic but the real thing we want is to know if the comment is on its own line. Now it works with both :)
Before it was printing
```js
import {
ExecutionResult,
DocumentNode,
/* tslint:disable */
SelectionSetNode,
} /* tslint:enable */ from 'graphql';
```
and was not stable.
This fixes the last issue for apollo-client.
=> Fix last comment of import

src/printer.js, tests/typescript_decorators/__snapshots__/jsfmt.spec.js.snap, tests/typescript_decorators/decorators.js, tests/typescript_decorators/jsfmt.spec.js
See this issue for creating the same decorators as babylon ( https://github.com/eslint/typescript-eslint-parser/issues/250 ), in the meantime, this is making a ton of files in vscode crash. So we can just support both :)
=> Handle TypeScript decorators

.gitignore, bin/prettier.js, package.json, tests_integration/.eslintrc.js, tests_integration/__tests__/__snapshots__/with-node-modules.js.snap, tests_integration/__tests__/with-node-modules.js, tests_integration/cli/with-node-modules/node_modules/node-module.js, tests_integration/cli/with-node-modules/not_node_modules/file.js, tests_integration/cli/with-node-modules/regular-module.js, tests_integration/runPrettier.js, yarn.lock
**Summary**
Inspired by this comment: https://github.com/prettier/prettier/pull/1048#issuecomment-287824396 I thought it may be a good idea to omit `node_modules` by default when running prettier through CLI. Kinda fixes https://github.com/prettier/prettier/issues/1358.
Notable changes:
* adds new `--with-node-modules` CLI flag to opt-out from default behavior
* adds integration tests inside `tests_integration` directory.
* adds new npm script command to run integration tests: `test-integration`
**Test plan**
Added an integration test suite.
=> Ignore node_modules when running prettier from CLI

src/printer.js, tests/method-chain/__snapshots__/jsfmt.spec.js.snap, tests/method-chain/comment.js
I kept adding places where comments could be but more use cases kept creeping in. So now this is a holistical approach, we check all the comments that can be between two nodes. This way we should be good to go :)
=> Make the comment chain comment detection more robust

src/fast-path.js, tests/typescript_as/__snapshots__/jsfmt.spec.js.snap, tests/typescript_as/as.js
The binary logic doesn't work if the node isn't a binary or logical expression
=> Properly add parenthesis for as inside of binary expression

src/fast-path.js, tests/typescript_as/__snapshots__/jsfmt.spec.js.snap, tests/typescript_as/as.js
Looks like we didn't properly support it for all the binary operators :p
=> Add parenthesis for as inside of class extends

CONTRIBUTING.md, README.md
It's easier to find it this way, and it's pretty popular convention to have a `CONTRIBUTING.md` file in repo root.
=> Extract contributing guide into separate document

src/printer.js, tests/jsx/__snapshots__/jsfmt.spec.js.snap, tests/jsx/flow_fix_me.js
This is very unfortunate that we have to change the generic function that prints code but we want the JSXElement node to handle its comments printing itself in order to write them inside of the parenthesis instead of outside.
Fixes #555
=> Put JSX comments inside of the parenthesis

src/comments.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/line_suffix_boundary/__snapshots__/jsfmt.spec.js.snap, tests/template/__snapshots__/jsfmt.spec.js.snap
We completely butcher comments inside of template literals. The fix is to not be able to attach comments to TemplateElement nodes and to avoid comments that are in one expression to be moved to another expression. We now have the boundary to prevent outputting invalid code.
Fixes #1617
=> Fix comments inside of template literals

src/printer.js, tests/switch/__snapshots__/jsfmt.spec.js.snap, tests/switch/comments.js
The function isPreviousLineEmpty comment doesn't skip comments (on purpose, see comment above that method :P) so the detection is messed up. Turns out, it's easier to just use isNextLineEmpty like everywhere else.
Fixes #1708
=> Fix empty lines with comments between switch cases

.flowconfig
I have no intention of using flow to type prettier but adding this file makes Nuclide run flow and get jump to definition and some datatips for what it can infer.
=> Add .flowconfig

README.md
The links are clearly about the WebStorm IDE and JetBrains is just the company's name.
This can be confusing for users.
=> Replace JetBrains with WebStorm in README.md

.ignore
This makes it easier to search through the code without getting
irrelevant results. It uses a .ignore file in order to cover at least
the three tools mentioned in the title. See the discussion here:
https://news.ycombinator.com/item?id=12568822
=> Ignore docs/prettier.min.js when searching with ag/ripgrep/sift

index.js, src/comments.js, tests/shebang/jsfmt.spec.js
That way, we won't have to do any arithmetic on range and cursor locations
when there is a shebang. See here for details:
https://github.com/prettier/prettier/pull/1637#issuecomment-303846507
This required changing comment printing such that comments that are
actually shebangs are just ignored.
=> Pass entire text through formatWithShebang() to format()

src/printer.js, tests/arrows/__snapshots__/jsfmt.spec.js.snap, tests/arrows/call.js
We don't always want to automatically forward this option but we can always forward it to `n.body`. If it's an arrow function, it's doing the intended behavior, otherwise, it's not going to ignore it and not forward it. What we don't want is for arrow -> blockStatement -> arrow to get it, but we're good.
Fixes #1652
=> Use expandLast for nested arrow functions

src/printer.js, tests/flow/es6modules/__snapshots__/jsfmt.spec.js.snap, tests/flow/unreachable/__snapshots__/jsfmt.spec.js.snap, tests/variable_declarator/__snapshots__/jsfmt.spec.js.snap, tests/variable_declarator/multiple.js
This keeps being requested and we're not using it at Facebook, so I don't particularly care which way it should be printed. We now force multiline if there's at least one declaration with a value. We don't want to break all the variables that are just declared.
Fixes #1607
=> Force \n for multiple variable declarations

src/printer.js, tests/flow_union/__snapshots__/jsfmt.spec.js.snap, tests/flow_union/jsfmt.spec.js, tests/flow_union/union.js
TypeScript doesn't have the concept of `?` for nullable options and instead you have to write `| null` and `| void`. This is annoying to have it use the long form, so we're now inlining them.
While working on this, I found out a few issues with the way we deal with those:
- We only align objects if the parent is a union. This means that if you have `Array<{ object }>`, the object is not aligned properly. The fix is to move the alignment logic to the union, and not the child.
- When doing so, it messes up with the comment alignment, so we have to manually handle children comment printing in the union code.
It doesn't yet fix #1727 because the hardcoded type names are different, i'll follow up in a PR.
=> Inline | null and | void

src/printer.js, tests/jsx-stateless-arrow-fn/__snapshots__/jsfmt.spec.js.snap, tests/jsx/__snapshots__/jsfmt.spec.js.snap, tests/last_argument_expansion/__snapshots__/jsfmt.spec.js.snap, tests/typescript_tsx/__snapshots__/jsfmt.spec.js.snap
I didn't intend for putting parenthesis there in the first place but it slept through. Since it was going to trigger a ton of changes I held up changing it, but I feel like we need to do it sooner than later otherwise we're not going to be able to do it. A lot of people writing functional components are going to be very happy about this change :)
Shoutout to @xixixao who sent a PR earlier that did this and that pushed me to do the right thing :)
=> Remove parenthesis for JSX inside of arrow functions

src/printer.js, tests/classes/__snapshots__/jsfmt.spec.js.snap, tests/classes/break.js, tests/flow/union/__snapshots__/jsfmt.spec.js.snap, tests/interface/__snapshots__/jsfmt.spec.js.snap, tests/typescript_as/__snapshots__/jsfmt.spec.js.snap
There can often be something that breaks inside of `extends` so it's looking weird to break twice. It now only breaks on `implements` and make sure to put each element on its own line.
Fixes #1520
=> Break on implements instead of extends

src/printer.js, tests/flow_import_type_specifier/__snapshots__/jsfmt.spec.js.snap, tests/flow_import_type_specifier/test.js, tests/import/__snapshots__/jsfmt.spec.js.snap, tests/import/inline.js
A long time ago I introduced the ability to break for import statements. Then, later on, we removed the ability for require to break and go over the 80 column mark. In order to be consistent, we should do the same for import statements as well.
=> Inline import type

src/fast-path.js, src/printer.js
- I want to get to a place where we don't use ast-types in order to do the traversal. This almost removes it from fast-path.
- Remove FastPath.from and copy
- Use .prototype instead of the weird Fpp
- Remove unused TODO
- Remove unused needsParen condition with a bunch of associated code
=> Cleanup fast-path

src/comments.js, src/parser.js, tests/typescript/conformance/internalModules/importDeclarations/__snapshots__/jsfmt.spec.js.snap, tests/typescript/webhost/__snapshots__/jsfmt.spec.js.snap
It's very annoying to have to have a static definition of the ast, we should instead just traverse the objects to discover it. We just need to make sure not to have any cycles, but it's also good for debugging anyway.
This fixed a few comments already :)
=> Remove ast-types from comments traversal

src/parser.js
Before
```js
test.css: SyntaxError: Unexpected token
```
After
```js
test.css: SyntaxError: Unexpected token
at Object.parse (native)
at new SourceMapConsumer (/Users/vjeux/random/prettier/node_modules/source-map/lib/source-map-consumer.js:17:22)
at PreviousMap.consumer (/Users/vjeux/random/prettier/node_modules/postcss-less/node_modules/postcss/lib/previous-map.js:69:34)
at new Input (/Users/vjeux/random/prettier/node_modules/postcss-less/node_modules/postcss/lib/input.js:84:28)
at Object.lessParse [as parse] (/Users/vjeux/random/prettier/node_modules/postcss-less/dist/less-parse.js:19:15)
at parseWithPostCSS (/Users/vjeux/random/prettier/src/parser.js:346:27)
at Object.parse (/Users/vjeux/random/prettier/src/parser.js:24:12)
at format (/Users/vjeux/random/prettier/index.js:59:22)
at …
```
=> Also add the stack for postcss errors

src/clean-ast.js, src/printer.js, tests/typescript_class/__snapshots__/jsfmt.spec.js.snap, tests/typescript_class/methods.ts, tests/typescript_interface/__snapshots__/jsfmt.spec.js.snap, tests/typescript_interface/abstract.ts, tests/typescript_interface/jsfmt.spec.js
Who are we to say no to completely nonsensical `abstract interface`s? 😉 
Fixes Some `ast(prettier(input)) !== ast(input)` checks by:
* ignoring `export` and `static` in constructor properties (massageAST).
* print `abstract interface` 
* print optional methods `method?() {}`
#1643
=> TypeScript: handle ExperimentalSpreadOperator, optional method, and abstract interface

src/clean-ast.js, tests/typescript/compiler/__snapshots__/jsfmt.spec.js.snap, tests/typescript/compiler/contextualSignatureInstantiation2.ts, tests/typescript/compiler/es5ExportDefaultClassDeclaration4.ts
Fixes remaining failing AST checks.
=> TypeScript: allow parens with TSFunctionType and ignore empty specifiers

src/printer.js, tests/typescript_method/__snapshots__/jsfmt.spec.js.snap, tests/typescript_method/jsfmt.spec.js, tests/typescript_method/type_literal_optional_method.ts
Might need to go through and figure out all the combinations of `optional` and `questionToken`, but this holds for now.
=> TypeScript: fix unstable optional method

src/printer.js, tests/stylefmt/at-media/__snapshots__/jsfmt.spec.js.snap, tests/stylefmt/media-queries-ranges/__snapshots__/jsfmt.spec.js.snap
The issue is really that the media query parser fails to parse the inner queries and just gives a raw string for the expression, but it should be safe to remove extra spaces. I can't make it rmeove spaces inside () that way unfortunately :(
=> Remove many spaces from media query

src/util.js, tests/decorators/__snapshots__/jsfmt.spec.js.snap, tests/decorators/comments.js
Babylon has a bug (I guess) with locations for classes where decorators are involved. Instead of the class starting at the first decorator, it starts at the beginning of the `class` keyword. By moving the location to the first comment, it solves --some-- of the issues with decorator comments.
=> Fix decorators location

package.json, tests/async/__snapshots__/jsfmt.spec.js.snap, tests/async/async-iteration.js, tests/typescript_class/__snapshots__/jsfmt.spec.js.snap, tests/typescript_class/dunder.ts, yarn.lock
Fixes #1769.
Reduces total errors to 16 in #1643.
```
13      prettier(input) !== prettier(prettier(input))
3       Error: Comment location overlaps with node location
```
=> TypeScript: upgrade typescript-eslint-parser to 992f1fa

package.json, src/clean-ast.js, src/parser.js, src/printer.js, tests/css_scss/__snapshots__/jsfmt.spec.js.snap, tests/css_scss/jsfmt.spec.js, tests/css_scss/scss.css, yarn.lock
We use a heuristic to figure out if it's a SCSS or Less file. And if it doesn't work, we try again with the other one. We do the same for JSX and TypeScript.
Fixes #1784
=> Add support for SCSS

.eslintignore, .flowconfig, .gitignore, .ignore, bin/prettier.js, index.js, package.json, parser.js, scripts/build/build.sh, scripts/build/rollup.bin.config.js, scripts/build/rollup.index.config.js, scripts/build/rollup.parser.config.js, src/parser-postcss.js, src/parser-typescript.js, tests_config/run_spec.js, yarn.lock
This is my least favorite part of the job, but well, someone needs to do it :)
So, this PR has a script `scripts/build/build.sh` that generates the following output:
This way we can `npm publish` the `dist/` folder and have exactly 0 dependencies, yay!
The eval trick is a bit gross and throws big warnings when running the release script but I couldn't find a better way: https://github.com/rollup/rollup/issues/1418
Running `./dist/bin/prettier.js` works without parsers, with flow, babylon and typescript. For postcss, there's currently an issue with the output
```js
test.js: TypeError: Super expression must either be null or a function, not undefined
at i (/Users/vjeux/random/prettier/dist/src/parser-postcss.js:1:116352)
at /Users/vjeux/random/prettier/dist/src/parser-postcss.js:1:117024
at …
```
=> Build the dist/ with rollup

package.json, src/printer.js, yarn.lock
This updates `typescript-eslint-parser` to latest master (currently #3dcba7d53f61f51069ed84b57e053802c014d703) and reenables the abstract interface test which was unblocked.
@vjeux Should we be updating the `docs/prettier.min.js` file by hand in this PR too, or does that get auto-generated as part of a build process?
=> Update tsep to latest master, reenable abstract interface test

src/printer.js, tests/css_comments/__snapshots__/jsfmt.spec.js.snap, tests/css_comments/trailing_star_slash.css
Reported in the original repo: https://github.com/postcss/postcss-scss/issues/64
=> Workaround bug with comment ending in */

src/printer.js, tests/ternaries/__snapshots__/jsfmt.spec.js.snap, tests/ternaries/indent.js
This avoids making it seems like it is indented by 4 characters instead of two. The downside is that if the condition is multi-line it's not going to be properly aligned, but I feel it's a better trade-offs. If you are doing nested ternaries, you usually have small conditions.
=> Do not indent nested ternaries

src/printer.js, tests/jsx-text-wrap/__snapshots__/jsfmt.spec.js.snap, tests/jsx-text-wrap/test.js
This changes makes us more strict about ensuring our JSX children follow the alternating content/whitespace format expected by the `fill` primitive.
Previously there were some cases where could get out of sync which would throw out the formatting.
This fixes up the unstable rendering reported here: https://github.com/prettier/prettier/issues/1703
=> Fix unstable JSX output by ensuring we follow `fill` rules.

src/printer.js, tests/flow/more_react/__snapshots__/jsfmt.spec.js.snap, tests/jsx-significant-space/__snapshots__/jsfmt.spec.js.snap, tests/jsx-stateless-arrow-fn/__snapshots__/jsfmt.spec.js.snap, tests/jsx-text-wrap/__snapshots__/jsfmt.spec.js.snap, tests/jsx-text-wrap/test.js
A potential fix for https://github.com/prettier/prettier/issues/1582
This tweaks our JSX formatting to only put a JSX whitespace `{" "}` on a line by itself when it comes before or after a multiline element.
When preceding a text or single line element it appear on the same line as that element.
With this input:
```javascript
x = <font size={-3}><i>Starting at minute {graphActivity.startTime}, running for {graphActivity.length} to minute {graphActivity.startTime + graphActivity.length}</i></font>
```
We used to output:
```javascript
x = (
<font size={-3}>
<i>
Starting at minute {graphActivity.startTime}, running for
{" "}
{graphActivity.length} to minute
{" "}
{graphActivity.startTime + graphActivity.length}
</i>
</font>
);
```
After this PR we will output:
```javascript
x = (
<font …
```
=> JSX whitespace on the same line as text

package.json, scripts/build/build.sh, yarn.lock
It turns out rollup doesn't use the same algorithm for bundling commonjs files when there are cycles as node, which breaks postcss: https://twitter.com/Rich_Harris/status/869021144191561729. Webpack works just fine with it.
This sucks to have this rollup/webpack frankenstein but I really want to be able to release and don't really want to spend yet another day or two trying to make it work well.
=> Introduce Webpack 2 to fix postcss bundling

bin/prettier.js
We have some files in directories that start with a `.` that we want prettified. This PR adds the `include-dot-directories` flag to let the glob match dot directories.
=> Add an option to include "dot" directories.

tests_config/run_spec.js
This silences the validation warnings like:
Unknown option "filename" with value "/home/travis/build/prettier/prettier/tests/flow/es_declare_module/flow-typed/declares.js" was found.
See here for an example:
https://travis-ci.org/prettier/prettier/jobs/238474756#L397
Related to commit 0d9b04b (https://github.com/prettier/prettier/pull/1835)
=> Use `filepath` option instead of `filename` in tests

src/printer.js, tests/typescript_tuple/__snapshots__/jsfmt.spec.js.snap, tests/typescript_tuple/trailing-comma.ts
=> TypeScript: do not print trailing comma in TS tuple type

.ignore
This makes it easier to search through the code without getting
irrelevant results.
=> Ignore docs/index.js when searching with ag/ripgrep/sift

src/printer.js, tests/no-semi-babylon-extensions/__snapshots__/jsfmt.spec.js.snap, tests/no-semi-babylon-extensions/no-semi.js
Fixes #1875.
(Man, class properties with no-semi are *so edge-case-y*. Ugh.)
=> Require semicolons before class props named 'in' or 'instanceof'

index.js
This fixes https://github.com/prettier/prettier/issues/1890, albeit in a
quick-and-dirty way. Note also that the cursor offset may be incorrect
when there is a shebang, but that's a separate issue.
=> Preserve shebang in CLI output

index.js, src/comments.js, src/parser-flow.js, src/parser-include-shebang.js, src/parser-typescript.js
Now we handle actually printing the shebang in `printComment`, rather than
lopping it off beforehand and reattaching it afterward, as suggested in
https://github.com/prettier/prettier/pull/1718#issuecomment-303876792
=> Add shebang comment nodes to Flow/TypeScript ASTs

package.json, parser.js, src/parser-babylon.js, src/parser-create-error.js, src/parser-flow.js, src/parser-postcss.js, src/parser-typescript.js, yarn.lock
New version takes a loc object directly. babel/babel#5646.
I messed up a `function` keyword for the purposes of this screenshot.
/cc @hzoo seems like it's consistent with old version to be off by one. But might be worth fixing as it seems most parsers has to get the column shifted, which makes it sorta painful to use...
=> Upgrade babel code frame

docs/index.html
I looked at what is being called with assert and couldn't find anything but `ok` and `strictEqual`.
Fixes #1903
=> Fix strictEqual throwing

src/printer.js, tests/typescript/conformance/classes/__snapshots__/jsfmt.spec.js.snap, tests/typescript_class/__snapshots__/jsfmt.spec.js.snap, tests/typescript_class/methods.ts
I looked through all the places where we display accessibility and all of them now have a consistent way of printing all those modifiers.
Fixes #1877
=> Move accessibility before static

src/printer.js, tests/typescript_tsx/__snapshots__/jsfmt.spec.js.snap, tests/typescript_tsx/this.tsx
Would be nice to get it properly handled in https://github.com/eslint/typescript-eslint-parser/issues/307
Fixes #1877
=> Fix <this.x />

src/printer.js, tests/template/jsfmt.spec.js, tests/typescript/compiler/__snapshots__/jsfmt.spec.js.snap, tests/typescript/conformance/interfaces/interfaceDeclarations/__snapshots__/jsfmt.spec.js.snap, tests/typescript/conformance/internalModules/importDeclarations/__snapshots__/jsfmt.spec.js.snap, tests/typescript/conformance/types/functions/__snapshots__/jsfmt.spec.js.snap, tests/typescript/conformance/types/methodSignature/__snapshots__/jsfmt.spec.js.snap, tests/typescript/conformance/types/union/__snapshots__/jsfmt.spec.js.snap, tests/typescript/custom/computedProperties/__snapshots__/jsfmt.spec.js.snap, tests/typescript_array/__snapshots__/jsfmt.spec.js.snap, tests/typescript_interface/__snapshots__/jsfmt.spec.js.snap, tests/typescript_interface/separator.ts, tests/typescript_tuple/__snapshots__/jsfmt.spec.js.snap, tests/typescript_union/__snapshots__/jsfmt.spec.js.snap
Looks like the convention for typescript separator is `;` whereas for flow it's `,`. Let's migrate to that.
Fixes #1896
Fixes #1879
Fixes #1874
=> Use semi-colon for object separator

commands.md
`multilineGroup` was removed in commit 3aa267d (https://github.com/prettier/prettier/pull/450)
=> Say "group" instead of "multilineGroup" in commands.md

src/printer.js, tests/method-chain/__snapshots__/jsfmt.spec.js.snap, tests/method-chain/comment.js
It turns out that leading comment is attached to the CallExpression which is the last one and not the first one if they fit in a single line, so we want to not check that one.
Fixes #1892
=> Fix leading comment

src/fast-path.js, src/printer.js, src/util.js, tests/typescript_as/__snapshots__/jsfmt.spec.js.snap, tests/typescript_as/as.js
Instead of doing it inside of object, we need to have them use the existing mechanism that checks if the left-most character is a paren.
=> Fix As parenthesis for real

src/printer.js, tests/typescript_trailing_comma/__snapshots__/jsfmt.spec.js.snap, tests/typescript_trailing_comma/trailing.ts
With `--trailing-comma all` and `es5` we can safely add a trailing comma in `enum`s.
Fixes #1932
=> TypeScript: fix trailing comma in enum

src/printer.js, tests/decorators/__snapshots__/jsfmt.spec.js.snap, tests/decorators/methods.js
Missed babylon using "ClassMethod" instead of "MethodDefinition".
Fixes #1933
=> Decorators: do not inline methods with decorators with babylon

README.md
* Mention TypeScript and CSS in the README.
* Collapse the table of contents with `<details>` tag.
* Clarifies the `--parser` option.
[Visible here](https://github.com/prettier/prettier/blob/1.4-update-readme/README.md)
=> Mention TypeScript and CSS in the README

package.json, yarn.lock
This returns us to latest master on `typescript-eslint-parser` and bumps TS to the latest stable
=> Revert to official tsep and bump TS

src/printer.js, tests/jsx-significant-space/__snapshots__/jsfmt.spec.js.snap, tests/jsx-stateless-arrow-fn/__snapshots__/jsfmt.spec.js.snap, tests/jsx-text-wrap/__snapshots__/jsfmt.spec.js.snap, tests/jsx-text-wrap/test.js
Currently we place JSX whitespace (`{" "}`) at the beginning of lines, this PR is an exploration of placing JSX whitespace at the end of lines instead.
It was inspired by @SimenB's comment in https://github.com/prettier/prettier/pull/1831#discussion_r119909463.
It works nicely, although with one drawback that it is now possible for a line ending with `{" "}` to be longer than the max line length.
I'd be interested in people's opinions on this. If people prefer this way of outputting whitespace I'm happy to have it merged and reviewed.
=> Position JSX whitespace (`{" "}`) at the end of lines

src/parser-flow.js
Closes https://github.com/prettier/prettier/issues/1986
I think ideally this should be addressed in `uglify-es` but this is more expedient.
=> Use var to fix SyntaxError on Node@4

index.js, tests/cursor/jsfmt.spec.js
This partially address https://github.com/prettier/prettier/issues/1981
See https://github.com/prettier/prettier/issues/1981#issuecomment-306326739
=> Translate cursor relative to nearest node, not SourceElement

src/printer-graphql.js, tests/graphql_fields/__snapshots__/jsfmt.spec.js.snap, tests/graphql_fields/fields.graphql, tests/graphql_fields/jsfmt.spec.js
This doesn't yet handle arguments or directives, and takes the opinion that fields should always be on separate lines. @jnwng
=> GraphQL: Add support for formatting fields in selection sets

src/printer-graphql.js, tests/graphql_definitions/__snapshots__/jsfmt.spec.js.snap, tests/graphql_definitions/fields.graphql, tests/graphql_definitions/jsfmt.spec.js, tests/graphql_hello/__snapshots__/jsfmt.spec.js.snap
This currently comes with the opinion that if someone didn't put the `query` keyword in front of an anonymous query, we shouldn't add it for them. It uses a hack that currently the GraphQL parser returns an operation name of `null` if there was no operation type, and `undefined` if there was. 😨
=> GraphQL: Add support for printing operation names

src/printer-graphql.js, tests/graphql_arguments/__snapshots__/jsfmt.spec.js.snap, tests/graphql_arguments/hello.graphql, tests/graphql_arguments/jsfmt.spec.js
This kind of depends on #1991 to actually be sane - the snapshot will change after that. But the arguments support definitely works.
=> GraphQL: Add support for arguments with soft line break

src/fast-path.js, tests/do/__snapshots__/jsfmt.spec.js.snap, tests/expression_statement/jsfmt.spec.js, tests/quotes/__snapshots__/jsfmt.spec.js.snap
This is the backed out change from #1940.
It fixes the problem that in all parses besides babylon this:
```js
("use strict");
```
will be turned into 
```js
"use strict";
```
The fix is to add parens around all string literals which are on top level (`Program, BlockStatement`) and could be treated as Directives by mistake.
In the other PR I had a more precise check for this which checked if the string literal at the current position could be interpreted as directive. Not sure what you think, but I thought it is really rare to write code like
```js
if (x) { ... }
"something";
```
So i decided to go for a probably more performant way and wrap every top level ExpressionStatement with a string literal (which is not marked as directive) in parens.
I could also restore the other method if you …
=> Add parens around all string literals at top level

src/clean-ast.js, src/printer.js, tests/jsx_template/__snapshots__/jsfmt.spec.js.snap, tests/template_literals/__snapshots__/jsfmt.spec.js.snap, tests/template_literals/jsfmt.spec.js, tests/template_literals/styled-jsx.js
New PR because I broke the other one (#1965)
Adding support for CSS formatting in template literals (for #1948).  
Right now it is only formatting styled-jsx without expressions.  
From this:
```jsx
<div>
<style jsx>{`
/* a comment */
div :global(.react-select) {
color: red; display: none
}`}</style>
</div>;
```  
To this:
```jsx
<div>
<style jsx>{`
/* a comment */
div :global(.react-select) {
color: red;
display: none;
}
`}</style>
</div>;
```
The current version of the code is pretty ugly, the idea is to refactor it in a way that makes adding new "sub tree formatters" easier.
=> Parse CSS in template literals (styled-jsx)

bin/prettier.js, tests_integration/__tests__/debug-check.js, tests_integration/runPrettier.js
This makes it easier to quickly test formatting code snippets with e.g.
pbpaste | prettier --debug-check
Before, the following would happen:
$ pbpaste | prettier --debug-check
stdin: TypeError: Invalid data, chunk must be a string or buffer, not undefined
at WriteStream.Socket.write (net.js:693:11)
at writeOutput (/Users/josephfrazier/workspace/prettier/bin/prettier.js:375:18)
at getStdin.then.input (/Users/josephfrazier/workspace/prettier/bin/prettier.js:275:7)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:169:7)
$
Now, it looks like this:
$ pbpaste | prettier --debug-check
(stdin)
$
=> Allow --debug-check to work with stdin

.yarnrc
Now, `yarn add` and `yarn upgrade` will write exact versions to
package.json and yarn.lock.
See commit fadbbeb (https://github.com/prettier/prettier/pull/291)
=> Add .yarnrc to use exact versions

package.json, src/comments.js, src/parser-babylon.js, yarn.lock
This corrects the regressions seen in commit
26e829b (https://github.com/prettier/prettier/pull/1888)
=> Upgrade prettier to v1.4.2, fix lint issues

src/printer.js, tests/typescript/conformance/types/functions/__snapshots__/jsfmt.spec.js.snap, tests/typescript_export/__snapshots__/jsfmt.spec.js.snap, tests/typescript_method/__snapshots__/jsfmt.spec.js.snap, tests/typescript_method/semi.js
We don't need to be overly restrictive and should add the semi if there's no body
Fixes #2003
=> Add semi for functions without body

src/printer.js, tests/typescript_semi/__snapshots__/jsfmt.spec.js.snap, tests/typescript_semi/jsfmt.spec.js, tests/typescript_semi/no-semi.ts
If there are, it's not ambiguous.
Fixes #2023
=> Only prevent lone `set` if there's no type annotations

src/printer.js, tests/flow_union/__snapshots__/jsfmt.spec.js.snap, tests/flow_union/union.js
We were a bit too aggressive around the `| null` heuristic.
Fixes #2002
=> Break if string | null

src/printer-postcss.js, tests/css_extend/__snapshots__/jsfmt.spec.js.snap, tests/css_extend/extend.css, tests/css_extend/jsfmt.spec.js
This is the only breakage that people ever reported with CSS so I'm happy adding one edge case like this.
Fixes #1967
=> Fix less &:extends when parsed with scss

src/printer.js, tests/typescript_interface/__snapshots__/jsfmt.spec.js.snap, tests/typescript_interface/comments.js
This ensures that the comment size is not taken into account during measurement
Fixes #1976
=> Add group around TSMethodSignature

src/printer.js, tests/typescript_nosemi/__snapshots__/jsfmt.spec.js.snap, tests/typescript_nosemi/type.js
shouldBreak is only a heuristic to enforce a break, if it breaks "naturally", then it won't be applied.
Fixes #2055
=> Use ifBreak instead of shouldBreak

bin/prettier.js, package.json, src/options.js, src/parser-parse5.js, src/parser.js, src/printer-htmlparser2.js, src/printer.js, tests/html_basics/__snapshots__/jsfmt.spec.js.snap, tests/html_basics/hello-world.html, tests/html_basics/jsfmt.spec.js, tests_config/run_spec.js, yarn.lock
This PR introduces the [parse5](https://github.com/inikulin/parse5) parser, producing a [htmlparser2](https://github.com/fb55/htmlparser2) AST.
Parse5 was chosen due to compliance, and the ability to switch between different AST representations.
The htmlparser2 AST was chosen since it is simpler to work with in prettier. parse5's default AST doesn't track `node.kind` in the way we would like.
Similar to the method used to implement CSS template string formatting (#1948), the idea is to first introduce a fully compliant HTML5 printer, then use heuristics to switch to:
* Glimmer parser, based on `<script type>` or `<template lang>`.
* TypeScript or Babylon parsers, based on `<script type>` or `<script lang>`.
* PostCSS parser, based on `<style>`.
#1951, #1882.
=> HTML: Add parse5/htmlparser2 printer

src/printer-postcss.js, tests/css_atrule/__snapshots__/jsfmt.spec.js.snap, tests/css_atrule/if-else.css, tests/css_atrule/jsfmt.spec.js
=> CSS: print @else on same line as }

src/printer-postcss.js, tests/css_comments/__snapshots__/jsfmt.spec.js.snap, tests/css_comments/prettier-ignore.css
=> CSS: implement prettier-ignore

src/printer.js, tests/method-chain/__snapshots__/jsfmt.spec.js.snap, tests/method-chain/computed.js
**Before:**
```js
nock(/test/)
.matchHeader("Accept", "application/json")[httpMethodNock(method)]("/foo")
.reply(200, {
foo: "bar",
});
```
**After:**
```js
nock(/test/)
.matchHeader('Accept', 'application/json')
[httpMethodNock(method)]('/foo')
.reply(200, {
foo: 'bar',
});
```
Fixes #2075
=> Break method chains on non-literal computed member expressions

src/clean-ast.js, src/multiparser.js, src/parser-parse5.js, src/printer-htmlparser2.js, src/printer.js, src/util.js, tests/multiparser_html_css/__snapshots__/jsfmt.spec.js.snap, tests/multiparser_html_css/html-with-css-style.html, tests/multiparser_html_css/jsfmt.spec.js, tests/multiparser_html_js/__snapshots__/jsfmt.spec.js.snap, tests/multiparser_html_js/html-with-js-script.html, tests/multiparser_html_js/jsfmt.spec.js, tests/multiparser_html_ts/__snapshots__/jsfmt.spec.js.snap, tests/multiparser_html_ts/html-with-ts-script.html, tests/multiparser_html_ts/jsfmt.spec.js, tests/multiparser_js_css/__snapshots__/jsfmt.spec.js.snap, tests/multiparser_js_css/jsfmt.spec.js, tests/multiparser_js_css/styled-components.js
This PR introduces a general method for switching between different parsers in the middle of a print.
To prove the concept, I have implemented:
```js
Button.extend` color: rebeccapurple`
styled.button` color: firebrick`
```
I also moved the existing styled-jsx support (#1984) to the new method.
Currently, styled-components and styled-jsx are only formatted if there are no expressions in the template string.
#1948, #1882.
=> Implement parser switching (HTML, Vue, styled-components)

src/clean-ast.js, src/multiparser.js, tests/multiparser_js_graphql/__snapshots__/jsfmt.spec.js.snap, tests/multiparser_js_graphql/graphql-tag.js, tests/multiparser_js_graphql/jsfmt.spec.js, tests/multiparser_js_graphql/react-relay.js
Pretty straightforward to add support for `react-relay`'s `graphql` and `graphql-tag`'s `gql` tagged template expressions.
Unfortunately I couldn't do `Relay.QL` as it throws syntax errors in the common (only?) case of anonymous fragments:
```js
Relay.QL`
fragment on User { name }
`
// Syntax Error: unexpected name: "on"
```
=> Add react-relay and graphql-tag parsing

src/printer.js, tests/flow_import_type_specifier/__snapshots__/jsfmt.spec.js.snap, tests/flow_import_type_specifier/test.js, tests/import/__snapshots__/jsfmt.spec.js.snap
Not specific to flow `import type`.
Fixes #2050
=> Allow break with both default and named import

src/printer.js, tests/typescript_typeparams/__snapshots__/jsfmt.spec.js.snap, tests/typescript_typeparams/jsfmt.spec.js, tests/typescript_typeparams/long-function-arg.ts
**Before:**
```ts
export const forwardS = R.curry(<
V,
T
>(prop: string, reducer: ReducerFunction<V, T>, value: V, state: { [name: string]: T }) =>
R.assoc(prop, reducer(value, state[prop]), state)
);
```
**After:**
```ts
export const forwardS = R.curry(
<V, T>(
prop: string,
reducer: ReducerFunction<V, T>,
value: V,
state: { [name: string]: T }
) => R.assoc(prop, reducer(value, state[prop]), state)
);
```
Fixes #2099
=> TypeScript: print arrow function type params on same line as params

src/clean-ast.js, src/fast-path.js, src/printer.js, tests/typescript/custom/typeParameters/__snapshots__/jsfmt.spec.js.snap, tests/typescript_union/__snapshots__/jsfmt.spec.js.snap, tests/typescript_union/union-parens.ts
Maybe this is taking on too much responsibility, but it does bring it more in line with how prettier handles parenthesization in regular JavaScript.
Fixes #1885
=> TypeScript: Remove parens from type annotations where possible

src/fast-path.js, src/printer.js, tests/directives/jsfmt.spec.js, tests/expression_statement/jsfmt.spec.js
This was introduced by #1999.
typescript-eslint-parser doesn't mark directives as such (see https://github.com/eslint/typescript-eslint-parser/issues/267)
This works around the problem by detecting a leading `(` in the source, which means we can enable these tests, and should suffice for all but extreme circumstances.
Fixes #2074
=> TypeScript: workaround - don't wrap directives in parens

editors/webstorm/README.md
In WebStorm file watcher, it doesn't make sense to reformat with Immediate file synchronization since the code jumps around while you type and if you sneak in a character while reformatting WebStorm pops a conflict alert.
So it's much saner to reformat on Save only.
=> Doc: Uncheck Immediate file synchronization

src/multiparser.js, src/printer.js
We don't want to be adding too much logic to `printer.js`, so I've moved the argument consolidation from `printer.js` to `multiparser.js`.
=> Move some logic from printer.js to multiparser.js

src/parser-babylon.js, tests/non-strict/__snapshots__/jsfmt.spec.js.snap, tests/non-strict/keywords.js
It turns out that by returning there, we didn't go through the line `delete ast.tokens` and the comments attachment logic would attach it to a random token. It's great that this fail-safe caught this bug!
Fixes #2111
=> Fix comments in non strict mode

src/multiparser.js, tests/multiparser_js_graphql/__snapshots__/jsfmt.spec.js.snap, tests/multiparser_js_graphql/react-relay.js
Followed in the footsteps of #2092 to add support for the `graphql.experimental` tag present in Relay modern.
=> Add `graphql.experimental` parsing for react-relay

src/multiparser.js, src/printer.js, tests/template_literals/__snapshots__/jsfmt.spec.js.snap, tests/template_literals/styled-components-with-expressions.js, tests/template_literals/styled-jsx-with-expressions.js
This adds support for formatting CSS inside template literals with expressions (#1948). For example:  
```jsx
<style jsx>{`
div {
animation: linear ${seconds}s ease-out;
}
`}</style>;
```
Currently is only working for styled-jsx, but if you like the approach, I can add styled-components too, it should be easy.
It works like this: 
1. It replace all the expressions from the template literal with `@prettier-placeholder` 
2. Parse and print the template literal (css) doc
3. Print the doc for each expression
4. Traverse the css doc replacing all the placeholders with the expression docs  
If it fails to find or replace any of the placeholders it throws an error and abort the formatting of the template literal.
=> Format CSS in template literals with expressions

tests/typescript_comments/__snapshots__/jsfmt.spec.js.snap, tests/typescript_comments/type-parameters.ts
The PR that upgraded TS to 2.4 (https://github.com/prettier/prettier/pull/2120) also fixed https://github.com/prettier/prettier/issues/2054 because it also included the fix commit in `typescript-eslint-parser`.
This PR just adds an explicit test case for https://github.com/prettier/prettier/issues/2054 to prevent regressions.
=> Add test for comment in TypeScript type parameters

src/comments.js, tests/cursor/jsfmt.spec.js
This fixes https://github.com/prettier/prettier/issues/2131
=> Don't insert a cursor placeholder for a value-less path

src/parser-typescript.js
This takes advantage of the new option in `typescript-eslint-parser` for providing your own logger function.
See https://github.com/eslint/typescript-eslint-parser/issues/321 for further details
=> Override tsep loggerFn with noop

bin/prettier.js, package.json, yarn.lock
This uses [get-stream] instead of [get-stdin], since the latter just
gives an empty string if process.stdin is a TTY
(see https://github.com/sindresorhus/get-stdin/issues/21)
[get-stream]: https://github.com/sindresorhus/get-stream
[get-stdin]: https://github.com/sindresorhus/get-stdin
=> Let `prettier --stdin` work with keyboard input

package.json, yarn.lock
There will be plenty of breaking changes in tsep over the next few weeks to align with TS Team on preferred AST structure.
One such change has been merged into master and I will be including it in the ts-2.4 branch accordingly.
I ran things locally and this will cause a test in prettier to fail, which will need to be addressed in a separate PR.
To protect users from these scenarios, we should definitely always lock to a specific commit, even though the branch name is obviously more readable.
This commit is the current latest on the ts-2.4 branch (before pulling in the breaking change from master)
=> Lock tsep to specific commit

scripts/build/build.sh
Here's an example of the error that happens upon `yarn build`:
sed: can't read : No such file or directory
=> Fix dist/ build on machines that don't support `sed -i ''`

package.json, yarn.lock
Before, this error happened upon `yarn build`:
🚨   (commonjs plugin) Binding arguments in strict mode (49161:16) in /Users/josephfrazier/workspace/prettier/node_modules/typescript/lib/typescript.js
=> Fix dist/ build by upgrading typescript to nightly

scripts/build/build.sh
Following up on https://github.com/prettier/prettier/pull/2173, this fixes the build, as shown by:
yarn build
yarn test --prod -- tests/json/
=> Add json parser to dist/ build

.travis.yml
This helps us keep track of whether or not the dist/ build actually
works (see https://github.com/prettier/prettier/pull/2174). Note that
the dist/ jobs are allowed to fail, and do not affect overall build
time, so they shouldn't slow anything down (see
https://blog.travis-ci.com/2013-11-27-fast-finishing-builds/).
=> Build/test dist/ on Travis

src/printer-postcss.js, tests/css_composes/__snapshots__/jsfmt.spec.js.snap, tests/css_composes/composes.css, tests/css_composes/jsfmt.spec.js
When using `css-modules` with `composes` formatting the source code using prettier's defaults seem to cause an error in the `css-loader`. 
```css
.reference {
composes: selector from "a/long/file/path/exceeding/the/maximum/length/forcing/a/line-wrap/file.css";
}
```
will be formatted to
```css
.reference {
composes: 
selector 
from "a/long/file/path/exceeding/the/maximum/length/forcing/a/line-wrap/file.css";
}
```
This pull request attempts to fix that by detecting the use of composition and by passing the normal formatting flow.
Closes #2189
=> Fix css-modules composes breaking with long line width

src/parser-babylon.js
This allows prettier to be used in environments which supports nested import statments, Meteor for example.
=> Turn allowImportExportEverywhere on

package.json, yarn.lock
This changes the eslint error formatting from:
/Users/josephfrazier/workspace/prettier/src/printer-postcss.js
3:31  error  Insert `;`  prettier/prettier
to:
✘  prettier/prettier  Insert `;`
src/printer-postcss.js:3:31
const util = require("./util")
^
which makes them clickable in terminals like iTerm2 and Guake. See
[eslint-friendly-formatter] for details.
[eslint-friendly-formatter]: https://github.com/royriojas/eslint-friendly-formatter
=> Use eslint-friendly-formatter to make errors clickable

src/options.js
When using `--trailing-comma all` trailing commas are added to json files. This will force it off if it's running on a json file.
=> Turn off trailing comma for json

src/multiparser.js, src/printer.js
I think we should move this logic out of `genericPrint` and into `transformCssDoc`, but I'm not sure of the best way to accomplish this.
This PR adds a second argument to `transformDoc` called `parent` which contains both the `path` and `print` functions of the parent context.
=> MultiParser: move css expression doc printing to transformCssDoc

src/doc-utils.js, src/printer.js, tests/jsx_escape/__snapshots__/jsfmt.spec.js.snap, tests/jsx_escape/nbsp.js
As raised in https://github.com/prettier/prettier/issues/2217 Prettier can currently cause `&nbsp;` to disappear when the JSX tag contains a new line.
This was caused by an incorrect algorithm to determine whether a JSX element is empty. We weren't checking the raw value of the text, so incorrectly thought that `&nbsp;` was whitespace (rather than text).
This PR fixes this by pulling in some code from https://github.com/prettier/prettier/pull/1831 that lets us determine whether a JSX element contains "meaningful" text.
=> Fix up empty JSX element detection

src/printer.js, tests/objects/__snapshots__/jsfmt.spec.js.snap
This is a "regression" from when we started using the same heuristic for `=` and `:`
Fixes #2129
=> Don't indent + in object value

src/printer.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/flow/more_react/__snapshots__/jsfmt.spec.js.snap, tests/flow/new_react/__snapshots__/jsfmt.spec.js.snap, tests/flow/react/__snapshots__/jsfmt.spec.js.snap, tests/jsx-multiline-assign/__snapshots__/jsfmt.spec.js.snap, tests/jsx-newlines/__snapshots__/jsfmt.spec.js.snap, tests/jsx-significant-space/__snapshots__/jsfmt.spec.js.snap, tests/jsx-split-attrs/__snapshots__/jsfmt.spec.js.snap, tests/jsx-stateless-arrow-fn/__snapshots__/jsfmt.spec.js.snap, tests/jsx-text-wrap/__snapshots__/jsfmt.spec.js.snap, tests/jsx-text-wrap/test.js, tests/jsx-whitespace/__snapshots__/jsfmt.spec.js.snap, tests/jsx/__snapshots__/jsfmt.spec.js.snap, tests/jsx_escape/__snapshots__/jsfmt.spec.js.snap, tests/typescript_comments/__snapshots__/jsfmt.spec.js.snap, tests/typescript_tsx/__snapshots__/jsfmt.spec.js.snap
This PR is an initial investigation into the feasibility to having Prettier recombine JSX lines that have already been split.
Inspired by: https://github.com/prettier/prettier/issues/1583
This still has a number of edge cases that need to be handled, but the basics are there.
For example:
```javascript
const Abc = () => {
return (
<div>
Please state your
{" "}
<b>name</b>
{" "}
and
{" "}
<b>occupation</b>
{" "}
for the board of directors.
</div>
);
};
```
Would become:
```javascript
const Abc = () => {
return (
<div>
Please state your <b>name</b> and <b>occupation</b> for the board of
directors.
</div>
);
}
```
Allowing lines of JSX to be recombined is a big change from our current approach where we always retain newlines in JSX.
Issue https://github.com/prettier/prettier/issues/1583 …
=> Allow JSX lines to be recombined

README.md
The options table in README was getting a bit unwieldy, and didn't look so great:
This commit moves the options to a top-level section, and makes each setting hyperlink-able. I've added links to each setting to the ToC, too.
The `cursorOffset` setting has been moved from the list to the documentation for `formatWithCursor`.
This should be a bit easier to maintain, too.
=> Explode the options table

index.js, tests/range/__snapshots__/jsfmt.spec.js.snap, tests/range/range-end.js, tests/range/range-start.js
Fix edge range formatting the entire file.
Fixes #2245 
This PR removes Program and File node type from valid ancestors as those 2 nodes cover the entire file.
This is my try to fix the issue with formatting the entire file on selecting an edge node.
Also added 2 tests to cover both start node and end node selection
=> Range Formatter: Remove Program/File from valid Ancestor

src/printer.js, tests/performance/__snapshots__/jsfmt.spec.js.snap, tests/performance/nested.js
For printing the last argument expansion, we need to print the same node a bit differently with a flag. It's not easy to re-print just the node that is different so we end up printing all the sub-tree twice. Since it is often nested, it means that we run into an exponential complexity.
I finally found a simple solution: we can use a Map to store the nodes and their printed values. It is really cheap to do so (I can't notice a time difference with or without on normal code) and allows us to stop going through the two sub-trees in the bad case.
Fixes #1250
=> Add caching for printing

src/multiparser.js, tests/multiparser_html_ts/__snapshots__/jsfmt.spec.js.snap, tests/multiparser_js_css/__snapshots__/jsfmt.spec.js.snap, tests/multiparser_text/__snapshots__/jsfmt.spec.js.snap, tests/multiparser_text/jsfmt.spec.js, tests/multiparser_text/text.js, tests/template_literals/__snapshots__/jsfmt.spec.js.snap
If we don't, all the places where we read from the original text (mostly comments) are reading into random places.
Fixes #2258
=> Forward originalText in multiparser

src/printer.js, tests/flow_variance/__snapshots__/jsfmt.spec.js.snap, tests/flow_variance/jsfmt.spec.js, tests/flow_variance/variance.js
Turns out when we refactored for TS, we moved it before "static" and it no longer parses. Oops.
=> Fix variance location

src/printer.js, tests/arrows/__snapshots__/jsfmt.spec.js.snap, tests/arrows/comment.js, tests/comments/__snapshots__/jsfmt.spec.js.snap
It outputted which is completely wrong
```js
<FlatList
renderItem={info => <span>{info.item.widget.missingProp // $FlowExpectedError - bad widgetCount type 6, should be Object
}</span>}
/>;
```
=> Fix unstable arrow comments

index.js, tests/range/__snapshots__/jsfmt.spec.js.snap, tests/range/class-declaration.js, tests/range/module-export1.js, tests/range/module-export2.js, tests/range/module-export3.js, tests/range/module-import.js
Added various missing types for babylon, flow and typescript parsers.
It now allows to *range format* those node types.
Added tests to cover module and class.
Fixes #2246
I'm not sure if it's good to mix all those node types for every parser. We may end with a long list. They would certainly fit better in their respective parser list but duplicating nodes between javascript parsers.
Neither postcss parser nor *future parser* are included
@josephfrazier as asked, but it may still miss some nodes.
=> Add module, class and typed nodes to sourceElements (Range formater)

src/printer.js, tests/flow/more_react/__snapshots__/jsfmt.spec.js.snap, tests/jsx-newlines/__snapshots__/jsfmt.spec.js.snap, tests/jsx-significant-space/__snapshots__/jsfmt.spec.js.snap, tests/jsx-stateless-arrow-fn/__snapshots__/jsfmt.spec.js.snap, tests/jsx-text-wrap/__snapshots__/jsfmt.spec.js.snap, tests/jsx-text-wrap/test.js
As mentioned in https://github.com/prettier/prettier/issues/2233#issuecomment-310850386 the current master won't work for Facebook as it breaks the formatting of their translation pipeline.
This PR aims to be a short term fix to add that support back in, so that the Prettier release is no longer blocked.
This PR also affects https://github.com/prettier/prettier/issues/2231, as it tweaks/improves formatting when there are consecutive tag/expression elements with no white space between them  (as this was the quickest way to fix the FB issue).
=> Tweak to support FB translation pipeline

src/printer.js, tests/arrows/__snapshots__/jsfmt.spec.js.snap, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/flow/multiflow/__snapshots__/jsfmt.spec.js.snap, tests/flow/new_react/__snapshots__/jsfmt.spec.js.snap, tests/flow/react/__snapshots__/jsfmt.spec.js.snap, tests/flow/react_modules/__snapshots__/jsfmt.spec.js.snap, tests/jsx-stateless-arrow-fn/__snapshots__/jsfmt.spec.js.snap, tests/last_argument_expansion/__snapshots__/jsfmt.spec.js.snap, tests/typescript_tsx/__snapshots__/jsfmt.spec.js.snap
This adds the improvement discussed in https://github.com/prettier/prettier/issues/2232
When outputting a JSX element that contains a single expression (code wrapped in `{` `}`) we ensure the output is multiline when there is no parent element, or the parent element does not contain text:
```jsx 
<div>
{variable}
</div>
```
But when the parent element contains text we allow the JSX element to be inlined.
```jsx
// The expression can stay inlined here
<div>
First <span>{variable}</span>
</div>
```
Fixes #2264 
Fixes #2232
=> Improve JSX output when there is a single expression

src/printer.js, tests/jsx-significant-space/__snapshots__/jsfmt.spec.js.snap, tests/jsx-significant-space/comments.js
We had two occurrences on fb codebase where people attached comments on `{' '}` which would be swallowed. Instead of dropping the comments, let's make the algorithm a bit less naive.
=> Print comments attached to {' '}

src/parser-graphql.js, tests/graphql_comments/__snapshots__/jsfmt.spec.js.snap, tests/graphql_comments/tokens.graphql
The tokens are attached to the location via the prototype (so they are not visible when you JSON.stringify) but the various places where we traverse the ast see them. It causes stack overflows and comments that are not printed because they are attached to tokens instead of real nodes.
Fixes #2302 
Fixes #2299
=> GraphQL: Remove circular dependency in ast

src/printer-graphql.js, tests/graphql_arguments/__snapshots__/jsfmt.spec.js.snap, tests/graphql_comments/__snapshots__/jsfmt.spec.js.snap, tests/graphql_lists/__snapshots__/jsfmt.spec.js.snap, tests/graphql_objects/__snapshots__/jsfmt.spec.js.snap, tests/graphql_trailing_comma/__snapshots__/jsfmt.spec.js.snap, tests/graphql_variable_definitions/__snapshots__/jsfmt.spec.js.snap
"Daniel Schafer: Yeah, that's definitely what I'd describe as the canonical style; anytime you have two "things" on a line, use commas, but if you have a newline it's not needed."
=> GraphQL: Use spaces instead of commas

src/printer-graphql.js, tests/graphql_directive_decl/__snapshots__/jsfmt.spec.js.snap, tests/graphql_directive_decl/directive_decl.graphql
I couldn't figure out what the separator was, I tried `,`, `on` but none of them worked. Turns out it is `|`!
=> GraphQL: Fix directives separator

src/printer.js, tests/typescript_module/__snapshots__/jsfmt.spec.js.snap, tests/typescript_module/global.js
TIL this is valid in ambient contexts.
Fixes #2327
=> TypeScript: don't add namespace keyword to global declaration

index.js, tests/range_graphql/__snapshots__/jsfmt.spec.js.snap, tests/range_graphql/issue2296.graphql, tests/range_graphql/jsfmt.spec.js
As mentioned in https://github.com/prettier/prettier/issues/2296#issuecomment-311527787, `isSourceElement()` did not account for GraphQL. This fixes https://github.com/prettier/prettier/issues/2296
=> Add support for range-formatting GraphQL

src/clean-ast.js, src/multiparser.js, tests/template_literals/__snapshots__/jsfmt.spec.js.snap, tests/template_literals/styled-components-with-expressions.js
This is my fix for #2330 
I also added the keyword `keyframes` that is used in the [same way](https://www.styled-components.com/docs/api#helpers) as `css`
The AST for them is slightly different since they are not `MemberExpression` but simple `Identifier`
=> Add support for css, keyframes and injectGlobal keywords

src/options.js
GraphQL files are also commonly used with the `.gql` file extension. This makes files using that extension parsed as GraphQL.
Here's a search on GitHub showing the usage of the `.gql` extension: https://github.com/search?utf8=%E2%9C%93&q=extension%3A.gql+query&type=Code
=> Add `.gql` file extension to be parsed as GraphQL

src/printer.js, tests/while/__snapshots__/jsfmt.spec.js.snap, tests/while/indent.js
Fixes #2353. Use the same printing code for both `WhileStatement` and `DoWhileStatement`. Fix calculation of `isInsideParenthesis` when printing a `LogicalExpression`. There is no such thing as `DoStatement` -- it should be `DoWhileStatement`.
=> Fix indentation of a do-while condition

index.js, package.json, tests/css_bom/__snapshots__/jsfmt.spec.js.snap, tests/css_bom/bom.css, tests/css_bom/jsfmt.spec.js
We don't reprint the BOM anyway so we may as well remove it as early as possible.
Fixes #2362
=> Strip BOM before parsing

README.md
README's "Pre-commit Hook" section describes 3 ways to put Prettier as pre-commit hook. One one hand where the lint-staged example demonstrates auto formatting and adding to git staging, the bash script example show a different workflow of showing errors and failing the hook if unformatted code find.
1. All the examples should result in same thing to be considered alternatives of each other and create less confusion for developers to try each method
2. IMO failing a pre-commit hook goes against the philosophy of prettier. Why should the workflow break, when Prettier can automatically format things just before committing!
I have updated the bash script to work exactly same as lint-staged example i.e. auto-fix the formatting of staged files and add them back to git staging.
=> Update bash script in README to mimic lint-staged behaviour

.eslintrc.js, package.json, website/.eslintrc.js, yarn.lock
This solves the same problem as https://github.com/prettier/prettier/pull/2386, but at lint-time with [eslint-plugin-import](https://www.npmjs.com/package/eslint-plugin-import), rather than only on Travis.
=> Use eslint-plugin-import to detect devDependencies used in production

src/printer.js
Which avoids building an array for the result, and is also slightly clearer.
=> Switch a use of .map to .each

.eslintrc.js, bin/prettier.js, index.js, scripts/build/rollup.parser.config.js, src/comments.js, src/doc-builders.js, website/static/worker.js
I experimented with simplifying the eslint config to just use [eslint-config-standard](https://github.com/standard/eslint-config-standard) and [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier). There were too many errors to make it a quick change, but I did find a few useful rules we could adopt instead.
=> Add some standardjs-esque eslint rules

src/printer.js, tests/flow_generic/__snapshots__/jsfmt.spec.js.snap, tests/flow_generic/type.js
There was a path in the code when `isFlowShorthandWithOneArg` is true that prints the function parameters without parens or type parameters.
I fixed it by adding a condition that the node must have empty `typeParameters` to enter the branch.
Fixes #2404.
=> (#2404) Print TypeParameter even when unary function type

src/clean-ast.js, src/printer-postcss.js, tests/css_combinator/__snapshots__/jsfmt.spec.js.snap, tests/css_combinator/combinator.css, tests/css_comments/__snapshots__/jsfmt.spec.js.snap, tests/css_comments/selector.css, tests/css_selector_list/__snapshots__/jsfmt.spec.js.snap
Fix is trivial, use `line` instead of arbitrary whitespace.
However due to comments being AST nodes this breaks a test.
Fixes #2410
=> Trim whitespace in descendant combinator, fixes #2410

.pre-commit-hooks.yaml, README.md
Hi! [pre-commit](https://github.com/pre-commit/pre-commit) maintainer here :D
Figured you guys could simplify the pre-commit install instructions (and release burden with having to bump the version in the README over-and-over) by adding the metadata directly to this repository.
=> Add pre-commit metadata directly to prettier

.eslintrc.js, index.js
This required a small refactoring, but the code is less nested as a result.
See discussion at https://github.com/prettier/prettier/pull/2401#discussion_r125750068
http://eslint.org/docs/rules/yoda#exceptrange
=> lint: Add yoda rule with range exception

README.md
> Prettier makes this whole category of rules not needed anymore
The wording of this sentence was a bit awkward. I changed "not needed anymore" to "redundant" so it flows better. Another alternative is "Prettier alleviates the need for this whole category of rules".
=> Clean up "not needed anymore" sentence in README

README.md
https://github.com/prettier/prettier/issues/2375
Have used @k15a's explanation as a base.
Can you please give me feedback as to whether the new one is any clearer.
=> Make "print width" documentation clearer

README.md, bin/prettier.js, tests_integration/__tests__/__snapshots__/config-resolution.js.snap, tests_integration/__tests__/config-resolution.js
`--resolve-config` is different to `prettier.resolveConfig` in return value, so I'm changing it to `--find-config-path`.
=> Rename --resolve-config to --find-config-path

src/printer.js, tests/arrows/__snapshots__/jsfmt.spec.js.snap, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/flow/multiflow/__snapshots__/jsfmt.spec.js.snap, tests/flow/new_react/__snapshots__/jsfmt.spec.js.snap, tests/flow/react/__snapshots__/jsfmt.spec.js.snap, tests/flow/react_modules/__snapshots__/jsfmt.spec.js.snap, tests/jsx-stateless-arrow-fn/__snapshots__/jsfmt.spec.js.snap, tests/last_argument_expansion/__snapshots__/jsfmt.spec.js.snap, tests/typescript_tsx/__snapshots__/jsfmt.spec.js.snap
This PR changes the behaviour of JSX printing to allow single expressions to be output inline. It follows a discussion in: https://github.com/prettier/prettier/issues/2324
The following:
```jsx
<h3>
{stage.title}
</h3>
```
Will now be formatted as:
```jsx
<h3>{stage.title}</h3>
```
However as multiple expressions are still output multiline.
```jsx
<h3>{stage.title}{stage.body}</h3>
```
Will still be formatted as:
```jsx
<h3>
{stage.title}
{stage.body}
</h3>
```
=> Allow single expressions in JSX to be inline

src/printer.js, tests/typescript_tsx/__snapshots__/jsfmt.spec.js.snap, tests/typescript_tsx/this.tsx
This is a workaround while waiting on https://github.com/eslint/typescript-eslint-parser/issues/337.
Fixes #2471
=> Fix <this.Component />

src/printer.js, tests/flow_union/__snapshots__/jsfmt.spec.js.snap, tests/flow_union/union.js, tests/function_single_destructuring/__snapshots__/jsfmt.spec.js.snap, tests/function_single_destructuring/test.js
We only want to hug arguments if it is a single object as an argument. #1734 was too aggressive.
Fixes #2458
=> Don't call shouldHugType for function arguments

package.json, src/fast-path.js, src/printer.js, yarn.lock
In order to resolve https://github.com/JamesHenry/tsep-babylon-test/issues/5, tsep has been updated.
We are now explicitly using `TSTypeReference` in places where we previously used `GenericTypeAnnotation` (please see that issue for more context).
I have updated the dependency and made one minor code change to account for parens, but there is one broken test remaining and its failure is subjective so I just wanted to leave it open for now.
The case for printing `GenericTypeAnnotation` (and therefore the current behaviour on master is:
```js
case "GenericTypeAnnotation":
return concat([
path.call(print, "id"),
path.call(print, "typeParameters")
]);
``` 
The case for printing `TSTypeReference` (and therefore breaking the 1 remaining test):
```js
case "TSTypeReference":
return concat([ …
```
=> Update tsep and account for TSTypeReference change

docs/en/usage.md
echo "jsfiles" will not work. The example references a variable, not a static string. This commit makes the example functionally correct.
=> Fix variable name in git precommit example

src/comments.js, src/fast-path.js, src/util.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/closure-compiler-type-cast.js
Fixes https://github.com/prettier/prettier/issues/1445
=> Handle closure compiler type cast syntax correctly

package.json, src/printer.js, tests/flow_type_declarations/__snapshots__/jsfmt.spec.js.snap, tests/flow_type_declarations/opaque.js, yarn.lock
Support added in Babylon 7.0.0-beta.17 and Flow 0.51
=> Add support for flow opaque types

bin/prettier.js, package.json, src/resolve-config.js, yarn.lock
Due to a small bug in cosmiconfig (which I fixed in https://github.com/davidtheclark/cosmiconfig/pull/68), I had to pass the config path from our `argv` all the way to `cosmiconfig`, despite it already parsing the `process.argv` itself.
As this is fixed we no longer need to do this.
=> Don't pass config path through to cosmiconfig

src/clean-ast.js, src/multiparser.js, tests/multiparser_js_css/__snapshots__/jsfmt.spec.js.snap, tests/multiparser_js_css/styled-components.js
Supports the syntax:
```js
styled(ExistingComponent)`
color: papayawhip;
`;
```
Fixes #2545
=> Support styled-components with existing component

src/fast-path.js, tests/flow_annotation/__snapshots__/jsfmt.spec.js.snap, tests/flow_annotation/array_of_functions.js, tests/flow_annotation/jsfmt.spec.js
Without this, this:
const actionArray: (() => void)[] = [];
is formatted as:
const actionArray: () => void[] = [];
Fixes #2559
=> Keep parens around FunctionTypeAnnotation inside ArrayTypeAnnotation

.ignore, .npmignore
`.ignore` file was out of date since the new website was built.
`.npmignore` is no longer needed as we publish from the `dist/` directory.
=> Remove .npmignore and update .ignore

README.md
The lint-staged example under pre-commit hooks has a limitation where if you use the [Github Desktop](https://desktop.github.com/) app to commit specific lines, this approach will stage the whole file after regardless. See this [issue](https://github.com/okonet/lint-staged/issues/62) for more info.
=> Update README.md to add a notice about using lint-staged

README.md, docs/en/usage.md
Because `.eslintrc` is deprecated and should not be used anymore.
=> Purge usage of `.eslintrc`

docs/CNAME, docs/editors.md, docs/options.md, docs/usage.md, docs/why-prettier.md, website/package.json, website/sidebars.json, website/siteConfig.js, website/static/CNAME, website/users.json
Docusaurus, which is used to generate Prettier's website, will go through some API changes. The actual site will not change, but there are a few changes to how things are set-up. These are the changes I've made to the repo: 
- Move document markdown files from `docs/en` to `docs/`. Site urls will not be changed due to new `siteConfig` field, `useEnglishUrl: true`. If that field is removed, site urls will use, for example, `docs/why-prettier.html` instead of `docs/en/why-prettier.html`.
- Change document markdown headers to only use `id` and `title` fields. Sidebar information is now inside the `website/sidebars.json` file.
- Update `siteConfig.js` to remove unnecessary fields and update how header navbar links are made using `headerLinks`.
- Add new `cname` field to `siteConfig.js` so …
=> Update website setup to use latest version of Docusaurus

README.md
Added a link and description to rollup-plugin-prettier (https://github.com/mjeanroy/rollup-plugin-prettier) to the 'Related Projects' section
=> Added rollup-plugin-prettier to Related Projects in README.md

src/printer.js, tests/typescript_declare/__snapshots__/jsfmt.spec.js.snap, tests/typescript_declare/declare_var.ts
This will fix #2604, but not the general case, which is tracked in https://github.com/eslint/typescript-eslint-parser/issues/185.
=> Do not accept declare on previous line

package.json, src/printer.js, yarn.lock
No changes for users, this is the latest version of `typescript-eslint-parser` and includes a structural change to TS enums
=> Update: tsep version upgrade and changes to TS enum structure

src/parser-postcss.js, tests/css_import/__snapshots__/jsfmt.spec.js.snap, tests/css_import/multiple.css
parser-postcss parses `@import` at-rules specially, and unfortunately
buggily. This monkey-patches parser-postcss to parse all at-rules the
same way.
Fixes #2584.
postcss-less bug: https://github.com/shellscape/postcss-less/issues/88
=> Work around issue #2584

src/comments.js, src/printer.js, tests/class_comment/__snapshots__/jsfmt.spec.js.snap
We used to be very naive and just push all the comments at the top of the class, but it's very brute force (and breaks some flow annotations inside of fb) so we can do better :)
=> Better fix for class comments

src/comments.js, tests/decorators/__snapshots__/jsfmt.spec.js.snap, tests/decorators/comments.js
I wrote this fix a while ago but it conflicted with the class heuristic, now that #2660 fixes it, we can ship this one as well!
Fixes #1460
Fixes #2507
=> Fix interleaved comments in class decorators

README.md
Thought the setting wasn't working properly when it didn't apply to self closing elements, and was about to open an issue until I found out it's working as intended.
=> Clarifying JSX Brackets option

src/printer.js, tests/method-chain/__snapshots__/jsfmt.spec.js.snap, tests/method-chain/computed-merge.js
```js
// Before
data
[key]('foo')
.then(() => console.log('bar'))
.catch(() => console.log('baz'));
// After
data[key]('foo')
.then(() => console.log('bar'))
.catch(() => console.log('baz'));
```
Fixes #1313 
----
I'm not 100% sure if it's worth adding a special case for computeds here though? This issue is the [second-highest upvoted bug](https://github.com/prettier/prettier/issues?q=is%3Aopen+is%3Aissue+label%3Abug+sort%3Areactions-%2B1-desc) though.
=> Merge computed MemberExpression in member chain

package.json, tests/optional_catch_binding/jsfmt.spec.js, yarn.lock
This points typescript-eslint-parser to the latest commit on the `ts-2.5` branch (PR: https://github.com/eslint/typescript-eslint-parser/pull/370).
Only change is the support for optional catch binding in TypeScript, too :tada:.
Bumping the bundled TypeScript version to 2.5.1 (RC, [Release notes](https://blogs.msdn.microsoft.com/typescript/2017/08/17/announcing-typescript-2-5-rc/))
@vjeux Do you want to sneak this in to 1.6 release?
=> Support TypeScript 2.5 RC

README.md, package.json, scripts/build/build.js, scripts/table-of-contents.js, yarn.lock
Fixes #2698 
The README is missing docs for `--ignore-path`, `--no-config` and `--write`.  This PR adds them.
The README is also quite lengthy with options spread between multiple places (API, CLI, Options, dedicated headings).  It might be worth refactoring this into a more cohesive read in future PRs.
=> docs(readme): add and sort cli options

src/fast-path.js, tests/spread/__snapshots__/jsfmt.spec.js.snap, tests/spread/jsfmt.spec.js, tests/spread/spread.js
Also, noticed we didn't have any tests covering this case for any of the parsers.
Fixes #2708
=> Ensure parens around LogicalExpression inside ExperimentalSpreadProperty

README.md, package.json, src/resolve-config.js, tests_integration/__tests__/config-resolution.js, yarn.lock
I'd like to use `resolveConfig` in [tslint-plugin-prettier](https://github.com/ikatyang/tslint-plugin-prettier) to support config file, but unfortunately tslint did not provide async way to load rules. (There is also a feature request for https://github.com/prettier/eslint-plugin-prettier/issues/46, but I'm not sure if eslint supported async or not.)
Then I found cosmiconfig itself supports `sync` option so I started to write this PR, but after I wrote this PR, I realized that it just supports `sync` at 3.0 branch (https://github.com/davidtheclark/cosmiconfig/pull/78). 😅
=> feat(resolve-config): add `.sync()` method

package.json, yarn.lock
The `3.0` branch was [merged] and [deleted],
so we should use the default branch now.
[merged]: https://github.com/davidtheclark/cosmiconfig/pull/78#event-1232367869
[deleted]: https://github.com/davidtheclark/cosmiconfig/pull/78#event-1232367884
=> Fix cosmiconfig dependency branch

package.json, yarn.lock
This fixes a warning when installing prettier from github:
warning prettier > chalk@2.0.1: Please upgrade to Chalk 2.1.0 - template literals in this version (2.0.1) are quite buggy.
=> Upgrade chalk to v2.1.0

scripts/run-external-typescript-tests.js, src/cli-util.js
The old version had quite a bit of code related to grouping errors,
showing the number of errors per group and saving the groups of errors
to different files. However, now there are only 12 bad tests so I didn't
bother porting that logic to the new version. Instead, the errors a
simply printed to stdout.
=> Make run-external-typescript-tests.js cross-platform

package.json, yarn.lock
It seems the only usage of `cross-spawn` was in `runPrettier.js`, but it was removed in #2730.
=> chore(deps): remove devDependency `cross-spawn`

README.md
lint-staged use [minimatch](https://github.com/isaacs/minimatch). It's a good idea to add more than one filetype since prettier handle several kind of languages :)
=> Improve lint-staged setup example by adding more filetypes

.pre-commit-hooks.yaml
See https://github.com/prettier/prettier/issues/2745
=> Use `files:` over `types:` in pre-commit configuration

src/printer.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/last_argument_expansion/__snapshots__/jsfmt.spec.js.snap, tests/last_argument_expansion/empty-object.js
```
func({
// comment
})
```
was changing to
```
func(
{
// comment
}
);
```
[playground link](https://prettier.io/playground/#%7B%22content%22%3A%22func(%7B%5Cn%20%20%2F%2Fcomment%5Cn%7D)%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)
I'm not sure this was intended but this fixes #2617. Let me know if this should target only the case in that issue or not.
=> Group last argument if it's an empty object with a comment

src/cli-constant.js, src/cli-util.js, tests_integration/__tests__/__snapshots__/config-invalid.js.snap
Still a lot of room for improvement, but at least we get correct error messages.
@mitermayer I made some changes to the `config-precedence` option too, trying to avoid extra  calls to `minimist` and additional Object.assigns where possible. Not sure if I made it better or worse...
=> Refactor error handling

src/printer.js, tests/jsx/__snapshots__/jsfmt.spec.js.snap, tests/jsx/conditional-expression.js
As it was decided in #2729, prettier should print ternaries in normal mode, even in JSX, when it does n't contain JSXElements. This commit changes this check and updates the test.
Also, this commit changes how to print nested conditionals in the consequents (shown on https://github.com/prettier/prettier/issues/2729#issuecomment-327232494), so prettier now won't wrap only `null` and a conditional expression if it's the consequent.
Fixes #2729
=> Change when to print ternaries in JSX mode

src/printer.js, tests/binary-expressions/__snapshots__/jsfmt.spec.js.snap, tests/binary-expressions/return.js
Fixes #2777
Since we can't break after `return` and don't add `()` around
ConditionalExpressions' tests, we end up with some weird indentation when
breaking.
See [playground](https://prettier.io/playground/#%7B%22content%22%3A%22function%20foo()%20%7B%5Cn%20%20%2F%2F%20happy%20path%5Cn%20%20return%20this.hasPlugin(%5C%22dynamicImports%5C%22)%20%26%26%20this.lookahead().type%20%3D%3D%3D%20tt.parenLeft.right%3B%5Cn%7D%5Cn%5Cnfunction%20foo()%20%7B%5Cn%20%20%2F%2F%20logical%20chain%5Cn%20%20return%20this.hasPlugin(%5C%22dynamicImports%5C%22)%20%26%26%20this.lookahead().type%20%3D%3D%3D%20tt.parenLeft.right%5Cn%20%20%20%20%3F%20true%5Cn%20%20%20%20%3A%20false%3B%5Cn%7D%5Cn%5Cnfunction%20foo()%20%7B%5Cn%20%20%2F%2F%20binary%20expression%5Cn%20%20return%20this.calculate().compute().first.numberO …
=> Fix break on conditional expressions inside return

src/printer.js, tests/method-chain/__snapshots__/jsfmt.spec.js.snap, tests/method-chain/conditional.js
Fixes #2775.
This commit will make conditional expressions to match the behavior of
logical expression in method chains:
```js
(a ? b : c).map()
// if the conditional fits in oneline
(a ? b : c)
.map()
// if the conditional doesn't fit
(a
? b
: c)
.map()
=> Keep conditional expressions in one line on method chains

src/printer.js, tests/member/__snapshots__/jsfmt.spec.js.snap, tests/member/conditional.js, tests/member/logical.js, tests/method-chain/__snapshots__/jsfmt.spec.js.snap, tests/method-chain/conditional.js, tests/method-chain/logical.js
Still related to #2775, maybe a better way to print this case.
```js
(a
? b
: c
).prop;
(a
? b
: c
).call();
(a
? b
: c
)
.call1()
.call2();
```
If you guys think this is cool, let me know if I should do the same for LogicalExpression (I believe so) and we can do it in a single commit
Thanks!
=> Break closing paren of ConditionalExpression in member chains

editors/webstorm/README.md
The request fixes two issues in the docs:
1. When `prettier` is installed locally, we have to provide the absolute path to the executable. Otherwise, Webstorm will throw `Cannot run program ".\node_modules\.bin\prettier.cmd"` error. Checked in v2017.2.2 on Win10 but may vary depending on the version or platform.
2. The glob pattern in the `Process directories` section is incorrect.
=> fix webstorm integration guide

README.md, docs/options.md
Currently, the docs are not synchronized between `options.md` and `README.md`. 
We should do this in the future: https://github.com/prettier/prettier/pull/2767#issuecomment-327744705.
=> docs(readme): port requirePragma docs to README.md

README.md, docs/options.md
...Sorry, I didn't realize there's also missing `: <bool>` in the previous [PR](https://github.com/prettier/prettier/pull/2812).
=> docs: `requirePragma: <bool>`

.github/ISSUE_TEMPLATE.md, scripts/build/build.js, website/pages/playground/index.html, website/static/lib/prettier-version.js, website/static/markdown.js, website/static/playground.js, website/static/service-worker.js, website/static/worker.js
- Add helpful buttons:
- "Clear" to empty the code input.
- "Copy link" for those who don't see that the URL changes.
- "Copy markdown" to copy a markdown link and inline code snippets.
- "Report issue" to open a new issue with the playground prefilled.
- Add "show second format (debug)" checkbox for debugging idempotency issues. 
- Update the issue template on build to be in sync with the "Report issue" button.
- Extra things I did while at it:
- Change CodeMirror mode based on parser.
- Fix some HTML errors and warnings.
- Clean up CSS.
- Minor design tweaks.
- Updated the default example code.
- And more...
Example "Copy as markdown" output:
**Prettier 1.6.1**
[Playground link](http://localhost:3000/playground/#%7B%22content%22%3A%22const%20Hello%20%3D%20(%7Bname%7D)%20%3D%3E%20%3Cdiv%2 …
=> Improve the playground

src/printer-postcss.js, tests/css_case/__snapshots__/jsfmt.spec.js.snap, tests/css_case/case.less, tests/css_case/case.scss
Fixes #2820. While that issue is about `@media (--fooBar)` in
particular, this commit changes to never lowercase stuff starting with
`--` in general, as it seems like those `--customStuff` things can pop
up kind of anywhere.
=> Don't lowercase CSS custom media names

package.json, src/cli-constant.js, src/cli-util.js, src/cli.js, tests_integration/__tests__/__snapshots__/early-exit.js.snap, tests_integration/__tests__/early-exit.js, yarn.lock
main:
- Fixes #2826
side:
- replace `or` with `,`, e.g. `--help or -h` -> `-h, --help`
- add DidYouMean redirection for `--help <typo>` using leven
=> feat: support detailed `--help`

website/static/service-worker.js
have our own implementation of it under install-service-worker.js
The file `sw-toolbox-companion.js` (https://raw.githubusercontent.com/GoogleChromeLabs/sw-toolbox/master/companion.js) is
```javascript
/*
Copyright 2016 Google Inc. All Rights Reserved.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
(function() {
'use …
```
=> We do not need to have a reference to the toolbox-companion since we

package.json, src/cli-constant.js, src/cli-util.js, src/cli-validator.js, src/cli.js, tests_integration/__tests__/__snapshots__/config-invalid.js.snap, tests_integration/__tests__/__snapshots__/with-config-precedence.js.snap, tests_integration/__tests__/with-config-precedence.js, tests_integration/cli/config-precedence/.prettierrc, yarn.lock
Main:
- Fixes #2890
Side:
- before
- validation errors -> "--trailing-comma ..."
- after
- validation errors from cli -> "--trailing-comma ..."
- validation errors from config files -> "trailingComma ..."
=> fix(cli): validate options for every `config-precedence`

src/printer.js, tests/test_declarations/__snapshots__/jsfmt.spec.js.snap, tests/test_declarations/test_declarations.js
Inlines the following forms:
```js
it.only(...)
it.skip(...)
xit(...)
fit(...)
describe.only(...)
describe.skip(...)
xdescribe(...)
fdescribe(...)
test.only(...)
test.skip(...)
xtest(...)
ftest(...)
```
Closes #2855
=> Support fit(), xit(), it.only(), etc

src/printer.js, tests/preserve_line/__snapshots__/jsfmt.spec.js.snap, tests/preserve_line/argument-list.js
For https://github.com/prettier/prettier/issues/2367, so that empty lines in an argument list will be kept and printed. For example,
```
f(
// hi
adbldsaklfkljadskljasdklfklasdfkladsklfkladsfkladsklfkadlsflkadskfladsklfdsaf,
// hey
adbldsaklfkljadskljasdklfklasdfkladsklfkladsfkladsklfkadlsflkadskfladsklfdsaf,
);
```
will be printed without any change and hence the empty line in the middle will be kept.
Let me know if my approach is appropriate or/and you have any improvement in mind for this PR. Any feedback is greatly appreciated! 😄
=> Keep original empty lines in argument list

src/printer.js, tests/test_declarations/__snapshots__/jsfmt.spec.js.snap, tests/test_declarations/test_declarations.js
Fixes #1473
Basically this prevents breaking a test declaration when the 2nd argument is a function declaration:
```js
// current output
test("long string", function(
done
) {
// body
});
// with this PR
test("long string", function(done) {
// body
});
```
I wasn't sure how recommended it is to use `removeLines` but since this case was quite specific, I didn't think it would be much trouble. Let me know if I should solve this some other way!
=> Fix line break in test declarations with 2nd argument as a function

website/static/playground.js
Fixes https://github.com/prettier/prettier/issues/2881
Currently when an empty playground loads, [`setValue`](https://github.com/prettier/prettier/blob/master/website/static/playground.js#L138) is called with an empty string which means the change doesn't fire. Since editor styling happens as part of `formatAsync`, the editor can show the wrong debug panes and rulers on the initial load.
This PR fixes that by extracting the editor styling into its own function, `setEditorStyles`, and calls it as part of `window.onload` so that the editor always gets styled, even if the change event doesn't happen.
I also moved the `editor.setOption("mode", mode)` calls into the new function, just to keep editor styling logic happening in one place. If you'd like those to remain in `formatAsync`, I'm happy …
=> Fix editor styling on empty editors

tests_integration/__tests__/config-invalid.js, tests_integration/__tests__/config-resolution.js, tests_integration/__tests__/invalid-ignore.js, tests_integration/path-serializer.js
Some unit tests were failing on Windows due to path separators.
<details>
```
● resolves json configuration file with --find-config-path file
expect(value).toMatchSnapshot()
Received value does not match stored snapshot 1.
- Snapshot
+ Received
- "rc-json/.prettierrc.json
+ "rc-json\\.prettierrc.json
"
at Object.<anonymous> (tests_integration/__tests__/config-resolution.js:47:25)
at Promise (<anonymous>)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:169:7)
● resolves yaml configuration file with --find-config-path file
expect(value).toMatchSnapshot()
Received value does not match stored snapshot 1.
- Snapshot
+ Received
- "rc-yaml/.prettierrc.yaml
+ "rc-yaml\\.prettierrc.yaml
"
at Object.<anonymous> (tests_integration/__tests__/config-resolution.js:56:25)
at …
```
=> Fix unit tests on Windows

src/cli-util.js, tests_integration/__tests__/__snapshots__/config-invalid.js.snap, tests_integration/__tests__/config-invalid.js, tests_integration/cli/config/invalid/option/unknown
Context: https://github.com/prettier/prettier/issues/2908#issuecomment-332839291
- before: throw `TypeError: Cannot read property 'name' of undefined`
- after: warn `Ignored unknown option: unknown-key`
=> fix: ignore and show warning for unknown option from config file

CONTRIBUTING.md
Also remove `--` that was required in `yarn` v0.
=> Mention labels docs in CONTRIBUTING.md

src/multiparser.js, tests/multiparser_js_css/__snapshots__/jsfmt.spec.js.snap, tests/multiparser_js_css/styled-components.js
There isn't a specific issue for this, but it was mentioned in https://github.com/prettier/prettier/issues/2291#issuecomment-311489067 and https://github.com/prettier/prettier/issues/2350#issuecomment-328346243.
```js
// input
const Dropdown = styled.div`position: relative`;
// output
const Dropdown = styled.div`
position: relative;
`;
```
=> Force template literals to break after ` for styled-components

tests/css_case/__snapshots__/jsfmt.spec.js.snap, tests/css_case/case.less
I added the test in css_case/case.less because it also tests that
`!important` is lowercased in this case.
=> Add test for #2880

src/printer.js, tests/jsx-text-wrap/__snapshots__/jsfmt.spec.js.snap, tests/jsx-text-wrap/test.js
Fix for: https://github.com/prettier/prettier/issues/2680
This fixes up the issue where JSX formatting occasionally needed to be run twice to become stable. This occurred when you had multiple JSX whitespace elements or JSX whitespace followed by a space.
Input:
```jsx
x =
<div>
{" "} <Badge src={notificationIconPng} />
</div>
// NOTE: Multiple JSX whitespaces are collapsed into a single space.
x =
<div>
{" "}{" "}{" "}
</div>
```
Output:
```jsx
x = (
<div>
{" "}
<Badge src={notificationIconPng} />
</div>
);
// NOTE: Multiple JSX whitespaces are collapsed into a single space.
x = <div> </div>;
```
=> Collapse multiple JSX whitespaces

src/cli-util.js, tests_integration/__tests__/__snapshots__/ignore-relative-path.js.snap, tests_integration/__tests__/__snapshots__/multiple-patterns.js.snap, tests_integration/__tests__/__snapshots__/with-node-modules.js.snap, tests_integration/__tests__/ignore-relative-path.js, tests_integration/cli/ignore-relative-path/.prettierignore, tests_integration/cli/ignore-relative-path/level1-glob/level2-glob/level3-glob/shouldNotBeFormat.js, tests_integration/cli/ignore-relative-path/level1-glob/level2-glob/level3-glob/shouldNotBeIgnored.scss, tests_integration/cli/ignore-relative-path/level1-glob/shouldNotBeIgnored.js, tests_integration/cli/ignore-relative-path/level1/level2/level3/shouldNotBeFormat.js, tests_integration/cli/ignore-relative-path/shouldNotBeIgnored.js
Fixes #2964
@ikatyang I need some pointers for the tests. I thought about adding another test inside [`tests_integration/__tests__/ignore-absolute-path.js`](https://github.com/prettier/prettier/blob/master/tests_integration/__tests__/ignore-absolute-path.js)
=> Use relative paths with CLI

src/multiparser.js, tests/multiparser_js_graphql/__snapshots__/jsfmt.spec.js.snap, tests/multiparser_js_graphql/expressions.js
Related to #2640 and #2857.
I'll take a shot in trying to support expressions in GQL template literals, but anyway, failing to do that, this PR should prevent breaking people's code.
=> Prevent formatting GQL template literals with expressions

src/cli-util.js, tests_integration/__tests__/__snapshots__/piped-output.js.snap, tests_integration/__tests__/piped-output.js, tests_integration/runPrettier.js
I've tried to pipe the output of `--list-differences` into `xargs git add`, but due to the progress information, the stdout is not really usable.
This commit could fix that by suppressing output information. I think it might make sense to change `process.stdout`/`console.log` to `process.stderr`/`console.error` in case of errors, but I did not want to put multiple things into one PR.
Doing `yarn` did not work for me as it currently cannot find the Git commit of `postcss-values-parser` referenced in the `package.json`. I've installed the `latest` version of it to get it to run, but this is probably the cause why the `css_numbers/jsfmt.spec.js` test fails for me locally.
**Edit:** Forgot `yarn lint` initially, which is now fixed :)
=> Don't use ANSI codes if stdout isn't a TTY

src/comments.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/function-declaration.js
Fixes #2808
I **wasn't** able to fix anonymous function expressions though, as there's no node to attach the comment to.
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22(%2F*%20before%20*%2F%20function%20%2F*%20anon%20*%2F(%2F*%20args%20*%2F)%20%2F*%20returns%20*%2F%20%7B%7D%20%2F*%20after%20*%2F)%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%2C%22output2%22%3Afalse%7D%7D)
**Input:**
```jsx
(/* before */ function /* anon */(/* args */) /* returns */ {} /* after */)
```
**Output:**
```jsx …
```
=> Handle comments between function name and open paren

src/printer.js, tests/method-chain/__snapshots__/jsfmt.spec.js.snap, tests/method-chain/multiple-members.js
fixes #2832
This PR fixes the formatting for this input:
**Input:**
```jsx
wrapper.find('SomewhatLongNodeName').prop('longPropFunctionName')().then(function() {
doSomething();
});
```
**Before:**
```jsx
wrapper
.find("SomewhatLongNodeName")
.prop("longPropFunctionName")().then(function() {
doSomething();
});
```
**After:**
```jsx
wrapper
.find("SomewhatLongNodeName")
.prop("longPropFunctionName")()
.then(function() {
doSomething();
});
```
This is my first PR for Prettier, so I'm more than happy to make any adjustments as needed. Thanks!
=> fix: support sequential CallExpressions in member chains

tests_config/run_spec.js
This PR makes jest's verbose test output more readable; now if one of the flow tests fails, the filename will be included in the test description. This change won't affect any snapshots since those are indexed using the filename.
Before:
```
$ jest method-chain
PASS  tests/method-chain/jsfmt.spec.js
✓ flow - undefined-verify (4ms)
✓ bracket_0.js - typescript-verify (263ms)
✓ flow - undefined-verify (6ms)
✓ break-last-call.js - typescript-verify (27ms)
✓ flow - undefined-verify
✓ break-last-member.js - typescript-verify (7ms)
✓ flow - undefined-verify
✓ break-multiple.js - typescript-verify (2ms)
✓ flow - undefined-verify
✓ comment.js - typescript-verify (16ms)
✓ flow - undefined-verify
✓ computed-merge.js - typescript-verify (6ms)
✓ flow - undefined-verify
✓ computed.js - …
```
=> fix: add filenames to flow-verify test descriptions

README.md
This was done with `yarn toc`. Maybe we should add a CI step that runs
`yarn toc` and fails if the README changes?
=> Add missing "Require pragma" to Table of Contents

docs/options.md
I visited https://prettier.io/docs/en/options.html#content and noticed that the Markdown table for the `insertPragma` option is broken:
So I fixed it. :)
=> docs: fix table for `insertPragma`

README.md
“Styled” sounds like a CSS or CSS-like thing to me — Prettier is a code formatter
=> Change badge to say “formatted”

package.json, tests/ternaries/__snapshots__/jsfmt.spec.js.snap, tests/ternaries/nested.js, yarn.lock
Fixes #2194.
While looking at https://github.com/prettier/prettier/pull/3036 I was reminded that we _can_ bump Babylon even with the TS/Flow type name split due to `typescript-eslint-parser`.
Sigh, so many things to keep straight in the head :)
=> Add test for nested ternary with arrow func

package.json, src/fast-path.js, src/parser-babylon.js, src/printer.js, src/util.js, tests/nullish_coalescing/__snapshots__/jsfmt.spec.js.snap, tests/nullish_coalescing/jsfmt.spec.js, tests/nullish_coalescing/nullish_coalesing_operator.js, tests/pipeline_operator/__snapshots__/jsfmt.spec.js.snap, tests/pipeline_operator/jsfmt.spec.js, tests/pipeline_operator/pipeline_operator.js, yarn.lock
Adds printer for two new operators!
Proposal: https://github.com/tc39/proposal-pipeline-operator/
This operator makes functional chains much easier to read.
```js
// Before
baz(bar(foo(x)));
// After
x |> foo |> bar |> baz;
```
Proposal: https://github.com/tc39-transfer/proposal-nullish-coalescing
This operator is much like `||` except it only evaluates the RHS if the LHS is `null` or `undefined`, instead of falsy.
```js
const foo = object.foo ?? "default";
```
----
* Bumps babylon to beta 28
=> Print pipeline and nullish-coalescing operators

src/printer.js, src/util.js, tests/preserve_line/__snapshots__/jsfmt.spec.js.snap, tests/preserve_line/member-chain.js
Fixes https://github.com/prettier/prettier/issues/1957, so that for common long chained method call patterns, one empty line will be preserved before each call if there is any originally.
For example, 
```
angular.module('AngularAppModule')
// Constants.
.constant('API_URL', 'http://localhost:8080/api')
// App configuration.
.config(appConfig)
.run(appRun);
```
will be formatted to 
```
angular
.module("AngularAppModule")
// Constants.
.constant("API_URL", "http://localhost:8080/api")
// App configuration.
.config(appConfig)
.run(appRun);
```
. If two calls are separated by a parenthesis, one of the empty lines outside the parentheses before the next call will be preserved.
Not sure if the decisions I made here are acceptable. 😅  I am happy to make any change regarding the implementation …
=> Account for empty lines in long member call chain

src/printer-postcss.js, tests/css_scss/__snapshots__/jsfmt.spec.js.snap, tests/css_scss/scss.css
Resolves prettier/prettier#3056
This makes prettier format SCSS maps like CSS rules (line breaks after each rule). e.g.
```sass
$map: (color: #111111, text-shadow: 1px 1px 0 salmon)
```
will format to
```sass
$map: (
color: #111111,
text-shadow: 1px 1px 0 salmon
);
```
=> Format SCSS maps like CSS rules

src/doc-printer.js, tests/jsx-significant-space/__snapshots__/jsfmt.spec.js.snap, tests/jsx-text-wrap/__snapshots__/jsfmt.spec.js.snap
It turns out there was a subtle bug in the `fill` algorithm that was spotted by @acthp in https://github.com/prettier/prettier/issues/3071.
This PR fixes that issue, and updates the snapshot tests for the few edges cases it changes.
=> Fix calculation of whether doc parts fit

website/pages/playground/index.html, website/static/playground.js, website/static/service-worker.js
This allow the playground  to have shorter URL's while providing backwards compatibility to the older URI scheme.
playground with content:
```javascript
const a = 1;
```
Used to create uri as:
`
.../#%7B%22content%22%3A%22const%20a%20%3D%201%3B%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D
`
the same now is:
`.../#N4Igxg9gdgLgprEAuc0DOMAEBDTBeTARgG4QAaECABxgEt1lRsNkAzbAGzTgoCMAnbGADWcGAGUqQ2lADmyGPwCuPEABMIYNp24UAVmgAeAIUEix47AFs4AGRlxtXVRCUwqbgExPdIKf25+ZBBebF4ATw5ocj9+GRgAdVo1GAALZAAOAAYKbitaBWVVNBl …
=> Making sure playground can have shorter urls

src/printer.js, tests/member/__snapshots__/jsfmt.spec.js.snap, tests/method-chain/__snapshots__/jsfmt.spec.js.snap, tests/method-chain/logical.js, tests/preserve_line/__snapshots__/jsfmt.spec.js.snap
Fixes #2934 (previous related work: #2786)
This will make binaries break like:
```js
(
a &&
b &&
c
).member
```
The snippet in the issue would be formatted as:
```js
// before
const someLongVariable = (idx(
this.props,
props => props.someLongPropertyName
) || []
).map(edge => edge.node);
// after
const someLongVariable = (
idx(this.props, props => props.someLongPropertyName) || []
).map(edge => edge.node);
=> Break parens for binaries in member expression

website/static/playground.js
Unfortunately with PR https://github.com/prettier/prettier/pull/3063 I introduced a few bugs to the playground
1. The previous playground could parse config directly from the URL without having to wait any dependency to be available, due to the inclusion of lz-string as a dependencie for URL parsing we should have moved the logic of extracting config to go inside `window.onload`
2. I Naively thought that I could have simply update all encodeUriComponent to the lz-string variant, but that was not the behaviour that we needed for `report-bug` button, that particular one should have kept the old behaviour of encodeUriComponent.
Apologies for leading to a broken PR being merged into `prettier`. Tested this PR and it seems to fix all the above issues.
=> Fixing playground report issue button and options parsing

src/printer.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/jsx.js, tests/comments_jsx_same_line/__snapshots__/jsfmt.spec.js.snap, tests/comments_jsx_same_line/jsfmt.spec.js, tests/comments_jsx_same_line/jsx_same_line.js
=> Don't print JSX bracket on same line when it has trailing comments

src/printer.js, tests/member/__snapshots__/jsfmt.spec.js.snap, tests/member/expand.js, tests/method-chain/__snapshots__/jsfmt.spec.js.snap, tests/method-chain/computed-merge.js
This was only accounting for a single element in the first group. Now it handles arbitrary elements. Only the last element being capitalized matters.
This fixes one issue in #3107
=> Make the factory detection handle multiple elements

editors/vim/README.md
ALE does not enable config files by default in an effort to
avoid breaking installations using older versions of prettier:
https://github.com/w0rp/ale/issues/983
=> Add vim ALE setup for config files

README.md
To tie up #575, I thought it would be good to have a note on how to watch for files in the README, considering it is a much requested feature in Issues. However, I feel like a watcher doesn't need to be in the code base considering there are other packages out there that implement this.
Hopefully this pull request will please everyone that wants a watcher.
=> Add watching for changes to README

src/printer-postcss.js, tests/css_grid/__snapshots__/jsfmt.spec.js.snap, tests/css_grid/grid.css, tests/css_grid/jsfmt.spec.js
Fix #2703 
So this basically preserves the user's line breaks in CSS `grid` (or `grid-template*`) declarations, but continues to normalize quotes, numbers, etc.
=> Preserve line breaks in css grid declaration

src/printer-graphql.js, tests/graphql_string/__snapshots__/jsfmt.spec.js.snap, tests/graphql_string/jsfmt.spec.js, tests/graphql_string/string.graphql
When I ran it on all the graphql files of fb, none of them had escape, but someone reported this issue!
Fixes #3142
=> [graphql] Escape strings

docs/editors.md
The repository does a redirect already.
But if you are on mobile, you probably do like 2 roundtrips, so to prevent that, we link the the correct repo.
=> Link to correct editor repository url for vscode extension

src/printer.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/jsx.js, tests/comments_jsx_same_line/__snapshots__/jsfmt.spec.js.snap, tests/comments_jsx_same_line/jsx_same_line.js
Fix #3152 
**Input:**
```jsx
<div
className="foo" // comment
>
{children}
</div>;
<div
className="foo"
// comment
>
{children}
</div>;
```
**Current in master:**
```jsx
<div className="foo"> // comment
{children}
</div>;
<div className="foo">
// comment
{children}
</div>;
```
=> fix(jsx): Break opening elements with single text attribute if there's a comment

src/comments.js, src/printer.js, tests/jsx_spread/__snapshots__/jsfmt.spec.js.snap, tests/jsx_spread/attribute.js, tests/jsx_spread/child.js, tests/jsx_spread/jsfmt.spec.js
=> Add support for JSXSpreadChild and fix comments inside JSXSpread

src/printer-markdown.js, tests/markdown_paragraph/__snapshots__/jsfmt.spec.js.snap, tests/markdown_paragraph/special-prefix.md
Fixes #3168
The unstable is caused by the AST change, should be stable now.
=> fix(markdown): do not break before special prefix

README.md
API doc is here: https://prettier.io/docs/en/api.html
https://prettier.io/docs/en/usage-options.html `404`s
=> Update README to point to API doc

website/static/playground.js
Sometimes I'd like to check if the input hit the print width and where are they, but I could only copy-paste it in my editor to see them. Adding a light-gray ruler should be fine I guess.
=> chore(playground): add ruler for inputEditor

src/printer.js, tests/typescript_interface/__snapshots__/jsfmt.spec.js.snap, tests/typescript_interface/ignore.js
Fixes #3102
Not sure this is the right fix. Let me know what you think!
=> Prevent adding semi in TypeScript interfaces when type has prettier-ignore

src/doc-printer.js, src/printer-markdown.js, tests/markdown_indentation/__snapshots__/jsfmt.spec.js.snap, tests/markdown_indentation/example.md, tests/markdown_indentation/jsfmt.spec.js
Fixes partial #3223 and also fixes a little bug that I forgot to handle the string type `n` in `align.tabs`.
=> fix(markdown): force print spaces

src/util.js, tests/markdown_paragraph/__snapshots__/jsfmt.spec.js.snap, tests/markdown_paragraph/cjk.md
Fixes #3241
The root cause here is the regex mismatching, I thought `RegExp#lastIndex` only affected `RegExp#exec()`. 😭
=> fix(markdown): no extra whitespace between non-cjk and cjk-punctuation

src/printer-graphql.js, tests/graphql_directives/__snapshots__/jsfmt.spec.js.snap, tests/graphql_newline/__snapshots__/jsfmt.spec.js.snap, tests/graphql_newline/__snapshots__/obj_type_def.graphql, tests/graphql_newline/directive_decl.graphql, tests/graphql_newline/directives.graphql, tests/graphql_newline/enum.graphql, tests/graphql_newline/fields.graphql, tests/graphql_newline/input.graphql, tests/graphql_newline/interface.graphql, tests/graphql_newline/jsfmt.spec.js, tests/graphql_newline/object_type_def.graphql, tests/graphql_newline/schema.graphql, tests/multiparser_js_graphql/__snapshots__/jsfmt.spec.js.snap
=> Preserve intentional new lines in GraphQL

src/printer.js, tests/comments_jsx_same_line/__snapshots__/jsfmt.spec.js.snap, tests/comments_jsx_same_line/jsx_same_line.js, tests/jsx-text-wrap/__snapshots__/jsfmt.spec.js.snap, tests/jsx-text-wrap/test.js
=> Don't break self closing elements with no attributes

scripts/build/rollup.index.config.js, src/doc-builders.js, src/doc-printer.js
Context: https://github.com/prettier/prettier/issues/3263#issuecomment-344275152
When `printDocToString` calls `fill`, it's not necessary to call `assertDoc` for all of the remaining elements since they already checked when the doc was originally created (somewhere in `printAstToDoc`).
=> Skip assertDoc calls in production

src/doc-printer.js
Context: https://github.com/prettier/prettier/issues/3263#issuecomment-344275152
Slicing the array means copying the array's content for every pair, which makes the algorithm quadratic. This PR changes the copying to mutating the array directly to prevent that. It's a more dangerous approach but the way `fill` works it's a valid solution.
I'm not 100% comfortable with that and I'll take suggestions.
=> Mutate the doc.parts array when printing fill

src/printer.js, tests/flow_type_parameters/__snapshots__/jsfmt.spec.js.snap, tests/flow_type_parameters/empty_generic_break.js, tests/flow_type_parameters/jsfmt.spec.js
Not only does breaking look bad but when you have trailing comma enabled, it puts a comma there which is not valid.
=> [flow] Do not break on empty type parameters

src/printer-markdown.js, tests/markdown_list/__snapshots__/jsfmt.spec.js.snap, tests/markdown_list/nested-checkbox.md
=> fix(markdown): only indent the first non-list node in checkbox list item

src/printer.js, tests/line_suffix_boundary/__snapshots__/jsfmt.spec.js.snap, tests/template_literals/__snapshots__/jsfmt.spec.js.snap, tests/template_literals/expressions.js
Context: https://github.com/prettier/prettier/issues/3280#issuecomment-345882038
=> Template literals: Don't break on identifiers but break if comments

website/static/worker.js
Fixes #3300
If there's an exception when formatting the code in playground, we check if it's because the parser was not yet loaded. This check was wrong for json and css|less|scss causing the code to recursive infinitely.
=> Fix infinite recursion in the playground

src/printer.js, tests/typescript_trailing_comma/__snapshots__/jsfmt.spec.js.snap, tests/typescript_trailing_comma/trailing.ts
For some reason the rest property in objects in typescript is a `ExperimentalRestProperty` node in the AST and we were not checking for it when printing trailing commas in object expressions.
Fixes #3311
=> Don't add trailing comma in object rest spread

src/clean-ast.js, src/printer-postcss.js, tests/css_case/__snapshots__/jsfmt.spec.js.snap, tests/css_case/case.less, tests/css_case/case.scss, tests/css_combinator/__snapshots__/jsfmt.spec.js.snap
https://www.w3.org/TR/css3-selectors/#casesens
> All Selectors syntax is case-insensitive within the ASCII range (i.e.
> [a-z] and [A-Z] are equivalent), except for parts that are not under the
> control of Selectors. The case sensitivity of document language element
> names, attribute names, and attribute values in selectors depends on the
> document language. For example, in HTML, element names are
> case-insensitive, but in XML, they are case-sensitive.
Fixes #3304.
=> Don't lowercase element names and attribute names in selectors

docs/options.md
=> docs(options): add available version for `arrow-parens`

docs/index.md
These links didn't work: https://prettier.io/docs/en/index.html#footnotes
Now they do!
=> (docs) Fix broken footnote links

docs/options.md
A user in gitter was wondering how to disable prose wrapping in markdown, but hadn't noticed the option; he was thinking he'd need to set `printWidth` somehow to change this. I added a small note for clarity, since `proseWrap` is at the bottom of the page where some people don't notice it.
=> Add note about proseWrap option under printWidth for clarity

docs/index.md
Inline links with `*.md` to [get them converted by Docusaurus](https://docusaurus.io/docs/en/doc-markdown.html#linking-other-documents) so as to display properly on both website and GitHub.
=> docs(index): fix links on GitHub

src/multiparser.js, src/printer.js, tests/multiparser_js_graphql/__snapshots__/jsfmt.spec.js.snap, tests/multiparser_js_graphql/expressions.js, tests/multiparser_js_graphql/graphql-tag.js
=> Support toplevel interpolations in graphql tags

src/comments.js, tests/decorator_comments/__snapshots__/jsfmt.spec.js.snap, tests/decorator_comments/comments.js, tests/decorator_comments/jsfmt.spec.js, tests/typescript_decorators/__snapshots__/jsfmt.spec.js.snap, tests/typescript_decorators/decorators-comments.js
Fixes #3351
Looks like #2906 wasn't general enough.
=> Fix printing of comments around decorators and class properties

website/static/overrides.css
The footer was not showing on mobile devices. This was because docusaurus was hiding it. I used `static/overrides.css` to override docusaurus and give the footer some mobile styling. 
I used the exact same size (735) max-width media query that docusaurus uses, that is where that width came from.
=> Fixed website footer on mobile (#3335)

src/printer.js, tests/flow_mixins/__snapshots__/jsfmt.spec.js.snap, tests/flow_mixins/jsfmt.spec.js, tests/flow_mixins/type.js
Partially fixes #3390.
Only works with babylon, since flow's parser [doesn't seem to put the mixin into the AST](https://astexplorer.net/#/gist/7e956da8da57d5eafdde0e04de9b95a1/5b6fb6f97bbd1e61134d323f2e8b320a51206e9e) (???).
=> Add support for flow mixins when using babylon

src/cli-constant.js, website/pages/playground/index.html, website/static/playground.js
=> chore(playground): add new options

website/pages/playground/index.html
The focus outline doesn't makes much sense there
=> Change cursor and remove outline in summaries on playground

docs/webstorm.md
Re-use the instructions for setting the File Watcher program path in WebStorm when prettier is installed locally.
=> Update instructions for File Watcher in WebStorm

index.js, tests/insert-pragma/__snapshots__/jsfmt.spec.js.snap, tests/insert-pragma/trailing-spaces-first-line.js
A whitespace right after `/**` is parsed as the docblock comment. Initially I thought we should report this to jest, but I'm not sure this is a bug in jest and since we already strip leading new lines it seemed better we handle this case here.
Fixes #3426
(cc @SimenB, @vjeux)
=> Ignore whitespace in docblock right after /**

package.json, yarn.lock
This fixes https://github.com/prettier/prettier/issues/3432, I think. See https://github.com/josephfrazier/editorconfig-to-prettier/commit/29aa34459dfec238ce179f1eb5a4fdcefb9c4961
=> Treat absent .editorconfig correctly

src/comments.js, tests/class_comment/__snapshots__/jsfmt.spec.js.snap, tests/class_comment/comments.js, tests/object_property_comment/jsfmt.spec.js
Fixes #3429
Looks like that was introduced back in the day to fix issues but they don't seem necessary anymore.
- class method comments: #1074
- obj property comments: #958
=> Fix babylon misplacing comments in class method args

src/printer.js, tests/typescript_non_null/__snapshots__/jsfmt.spec.js.snap, tests/typescript_non_null/member-chain.js
Fixes #3312
When checking if we should inline a member chain, don't consider a `TSNonNullExpression` as a "non member" parent.
=> Consider TSNonNullExpression part of member chain

src/printer.js, tests/ignore/__snapshots__/jsfmt.spec.js.snap, tests/ignore/ignore.js, tests/typescript_interface/__snapshots__/jsfmt.spec.js.snap, tests/typescript_interface/ignore.js, tests/typescript_interface/jsfmt.spec.js
When trying to fix a bug of double printing separators in TypeScript interfaces in combination with `//prettier-ignore`, #3103 introduced a regression of not printing commas in regular objects. This commit restricts the "not print" the separator for TypeScript only. The problem is the parser considers the trailing `;` part of the node, but not `,` for objects - so when prettier prints the node as-is, sometimes it prints the separator, sometimes it doesn't.
Added a regression test + more tests for the TS bug
=> Fix printing separator in objects with prettier-ignore

docs/cli.md, docs/ignore.md
While working on #3321, I needed to ignore an entire file, but the [Ignoring Code](https://prettier.io/docs/en/ignore.html) section of the docs only describes how to ignore blocks of code, so I wasn't aware of the default ignore file.
_(The `.prettierignore` file **is** mentioned in the [CLI](https://prettier.io/docs/en/cli.html) section, but easily overlooked there.)_
* Commit fccf98a extends the introduction sentence of the "Ignoring Code" section and adds a new subsection to explain how to ignore files.
> Prettier offers an escape hatch to ignore a block of code <ins>or prevent entire files </ins>from being formatted.
> ## Ignoring Files
>To exclude files from formatting, add entries to a `.prettierignore` file in the project root or set the `--ignore-path` …
=> Docs: Add info on ignore file to "Ignoring Code"

package.json, src/clean-ast.js, src/fast-path.js, src/printer.js, yarn.lock
This has not officially been released yet, but I am opening the PR to get an advanced review.
For that reason, it reverts tsep back to using a commit hash as the version. I will update this once an applicable version of tsep has been released.
The relevant PR is here: https://github.com/eslint/typescript-eslint-parser/pull/388
=> Update tsep and apply breaking changes

docs/editors.md
is now called 'Prettier - Code formatter'
=> Update VS Code extension name

docs/webstorm.md
As webstorm has already integrated eslint support I find this more easy to setup and might be nice for ohers to know about.
=> chore(docs): Add webstorm setup with eslint integration

src/support.js, tests_integration/__tests__/__snapshots__/support-info.js.snap
Without this, the VS Code extension doesn't enable prettier for files of this type (settings.json, tsconfig.json, etc.).
=> Add "JSON with comments" to vscodeLanguageIds

README.md
Light logo doesn't get as much use. Which do we prefer?
=> Switch to light logo in README

.eslintrc.yml
This ensures that peoples’ ESLint configurations in parent directories aren’t used when linting Prettier.
=> Add `root: true` to .eslintrc.yml

src/support.js, tests_integration/__tests__/__snapshots__/support-info.js.snap
Fixes PostCSS integration for VS Code
Extension ([prettier-vscode](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)) is [querying](https://github.com/prettier/prettier-vscode/blob/master/src/utils.ts#L47) prettier for supported languages, and is not getting any information about `postcss`. As a result engineer sees that is no any formatter for `postcss`:
After exposing information that prettier supports `postcss` everything works fine.
=> Fix PostCSS VS Code integration

src/clean-ast.js
This reduces nesting and handles the edge cases first.
This change is best viewed ignoring whitespace differences: https://github.com/prettier/prettier/pull/3522/files?w=1
=> Return early from `massageAST()`

package.json, src/parser.js, yarn.lock
This way it shows up when you do `yarn outdated` 🙂 
Only code change in it is https://github.com/babel/babel/pull/6550
=> chore: use scoped babel package

README.md, docs/language-support.md, scripts/build/build-docs.js, scripts/build/build.js, src/cli-constant.js, src/multiparser.js, src/parser-vue.js, src/parser.js, src/printer-vue.js, src/printer.js, src/support.js, tests/multiparser_vue/__snapshots__/jsfmt.spec.js.snap, tests/multiparser_vue/jsfmt.spec.js, tests/multiparser_vue/vue-component.vue, tests_integration/__tests__/__snapshots__/early-exit.js.snap, website/data/languages.yml
There's a lot of demand for vue sfc (#2097). This introduces partial support for them: all the html is printed as is, except for the script and style tags which are printed using prettier. I believe that this should cover a lot of the use cases while being simple to support and if we want we can extend to more in the future.
I copy pasted the html parser used by vue (it's just a single 400 lines file) so that we don't run the chancesof conflicts. I'm also very conservative: I only print the style and script at the top level and for the lang attributes we support.
I expect this to be landable as is and provide value, review welcome :)
=> [vue] Introduce proper support for Vue Single File Components (SFC)

src/language-js/embed.js, tests/multiparser_js_graphql/__snapshots__/jsfmt.spec.js.snap, tests/multiparser_js_graphql/react-relay.js
Relay Classic uses `Relay.QL`, which was not previously picked up here.
=> Support Relay Classic

tests/object_colon_bug/__snapshots__/jsfmt.spec.js.snap, tests_config/run_spec.js
VERIFY_ALL_PARSERS doesn't make sense any more, let's delete it.
Also set the amount of `~` to match the print width of the test (only affects one snapshot)
Closes #2845
=> Remove ALL_PARSERS, print ~ printWidth times

scripts/build/build-docs.js, website/static/playground.js, website/static/worker.js
Revert #3613 and apply another solution since we don't actually expose `prVersion` from `prettier` module, which cause the wrong version on <kbd>copy markdown</kbd>.  😂
cc @azz
=> fix(playground): fix report version

src/language-js/printer-estree.js, tests/flow_function_parentheses/__snapshots__/jsfmt.spec.js.snap, tests/flow_function_parentheses/jsfmt.spec.js
Fixes #3550 
See the 2nd commit for the snapshot changes
=> Print parens in FunctionTypeAnnotation when arrowParens is "always"

package.json, src/language-graphql/printer-graphql.js, tests/graphql_directive_decl/__snapshots__/jsfmt.spec.js.snap, tests/graphql_directive_decl/directive_decl.graphql, tests/graphql_kitchen_sink/__snapshots__/jsfmt.spec.js.snap, tests/graphql_kitchen_sink/kitchen_sink.graphql, tests/graphql_kitchen_sink/schema_kitchen_sink.graphql, tests/graphql_newline/__snapshots__/jsfmt.spec.js.snap, tests/graphql_newline/directive_decl.graphql, tests/graphql_object_type_def/__snapshots__/jsfmt.spec.js.snap, tests/graphql_object_type_def/implements.graphql, tests/graphql_string/__snapshots__/jsfmt.spec.js.snap, tests/graphql_string/string.graphql, yarn.lock
Fixes #3601
This adds support for
- description as strings
- extending all the possible types
- block strings
- allow removing {} if there's no implementation for all graphql types
This is a breaking change but shouldn't be a big issue.
- Empty types are no longer allowed (there's an option to enable it but it hasn't been released yet). The fix is to remove `{}`
Something that hasn't been changed because not released:
- Doesn't support the new `&` separator for implementing multiple interfaces
A bug has been fixed:
- Now properly prints @directives for unions.
=> Update GraphQL parser

website/static/overrides.css
The default CSS for docusaurus is really terrible. I've long wanted to spend time fixing it upstream but until then, it's easier to just hack the CSS.
I tried to be as close as possible to how github displays it, which looked great.
=> Tweak CSS of the blog section

src/main/comments.js
I'm working on a plugin that contains all the child nodes in a "layout" array.
While I could somehow generate indexed properties to work around it, it seems cleaner to allow plugins to specify how to traverse their AST.
=> [Plugins] Allow custom getCommentChildNodes

README.md
No more ![image](https://user-images.githubusercontent.com/8341033/34648007-5cf9f898-f3cc-11e7-848b-8e6c72e5677f.png) caused by branches other than master.
=> docs(readme): travis master badge

docs/precommit.md
Adding docs for integration with [`pretty-quick`](https://github.com/azz/pretty-quick).
I'm replacing the previous option (`pre-commit`) as it does a `git add .` which it really shouldn't be doing.
As it's a brand new package I'll leave it in the number two spot for now, but I think this could potentially be the recommended pre-commit hook in the future as it should be the fastest, and it's the easiest to set up.
[🌐](https://deploy-preview-3675--prettier.netlify.com/docs/en/precommit.html#option-2-pretty-quick-https-githubcom-azz-pretty-quick)
=> Add pretty-quick pre-commit docs

website/data/users.yml
(except the ones redirecting to `/en/` or similar)
Also, remove trailing slashes on domains (i.e. `https://example.com/` → `https://example.com`).
=> Follow redirects in the user URLs
