prettier/prettier

src/language-css/parser-postcss.js, tests/css_case/__snapshots__/jsfmt.spec.js.snap, tests/css_comments/__snapshots__/jsfmt.spec.js.snap, tests/css_less/__snapshots__/jsfmt.spec.js.snap
Improve speed and fix places where we can break code
=> refactor: `parseNestedCSS` function

scripts/generate-schema.js, tests_integration/__tests__/__snapshots__/schema.js.snap, tests_integration/__tests__/schema.js
Forgot to take `option.array` into account.
=> fix(schema): support array type

src/common/util.js, src/language-js/comments.js, src/language-js/needs-parens.js, src/language-js/printer-estree.js, src/main/comments.js
=> feat: adding plugin ability for isBlockComment

docs/api.md
=> docs(api): language.since is now optional

docs/plugins.md
=> docs(plugins): add parser.preprocess

src/language-css/printer-postcss.js, src/language-css/utils.js
1. Move utils to `utils.js`.
2. Remove dead branches.
3. Remove dead code.
4. Improve readability variable names, function names and code.
5. Increase perf in some places.
It is first part of refactor and improvement, next parser and clean.
=> refactor: `printer-postcss`

website/static/_redirects
I was looking through [Google’s crawl errors](https://www.google.com/webmasters/tools/crawl-errors?siteUrl=https://prettier.io/) for the website <sup>(link only works if you have access)</sup>, and this should fix most of them.
=> Add a redirects file

index.js, jest.config.js, src/main/core.js, src/main/range-util.js, web.js
Follow up on #4364. This PR extracts core functionality that was present in `index.js` to `main/` and creates a `web.js` entry point.
It's still not exposed after the build, gonna do that in follow-up PRs but I'd like to get that merged in already to prevent conflicts later :joy:
=> Separate entry for web bundle

website/static/separate-css/playground.css
fixes problems in safari discussed in https://github.com/prettier/prettier/pull/4394.
Now the options panel will not outgrow editors panel.
=> [playground] fix overflow in safari

docs/editors.md, website/data/editors.yml
https://github.com/duailibe/atom-miniprettier
=> Add miniprettier to website and docs

src/common/util.js, tests/arrows/__snapshots__/jsfmt.spec.js.snap, tests/binary-expressions/__snapshots__/jsfmt.spec.js.snap, tests/binary_math/__snapshots__/jsfmt.spec.js.snap, tests/binary_math/parens.js
Context: https://github.com/prettier/prettier/issues/187#issuecomment-385495801
=> Prevent flattening multiplicative operations

src/common/util.js, src/language-js/needs-parens.js, tests/binary_math/__snapshots__/jsfmt.spec.js.snap, tests/binary_math/parens.js
Follow-up: https://github.com/prettier/prettier/pull/4407#issuecomment-386056544
> What do you think about turning `a % 10 - 5` into `(a % 10) - 5`?
=> Wrap modulo operation in parens inside additive operation

src/language-js/comments.js, src/language-js/printer-estree.js, tests/typescript_comments/__snapshots__/jsfmt.spec.js.snap, tests/typescript_comments/mapped_types.ts
=> Fix TSMappedType comments

src/language-css/printer-postcss.js, src/language-css/utils.js, tests/css_postcss_plugins/__snapshots__/jsfmt.spec.js.snap, tests/css_postcss_plugins/postcss-simple-vars.css
=> fix spacing issue in postcss simple vars

src/language-js/embed.js, tests/multiparser_js_css/__snapshots__/jsfmt.spec.js.snap, tests/multiparser_js_css/styled-components.js
=> Support styled-components Foo.extend.attrs()``

src/language-css/printer-postcss.js, tests/css_variables/__snapshots__/jsfmt.spec.js.snap, tests/css_variables/variables.scss
=> fix: css variables and scss interpolation

src/language-js/needs-parens.js, tests/flow_function_parentheses/__snapshots__/jsfmt.spec.js.snap, tests/flow_function_parentheses/test.js
=> Wrap ?() => T in parens when needed.

src/main/comments.js, src/main/range-util.js
Just a minor fix I found while going through the codebase. Should pass all tests and is formatted correctly :)
=> Remove unused text parameter from Comments#getSortedChildNodes

src/language-css/clean.js, src/language-css/parser-postcss.js, src/language-css/printer-postcss.js, src/language-css/utils.js, tests/css_case/__snapshots__/jsfmt.spec.js.snap
Description:
1. Use `*-unknown` for all what we can't parse and output this as is
2. `try/catch` in `parse*` functions
=> refactor: parser-postcss

src/language-css/parser-postcss.js, src/language-css/printer-postcss.js, src/language-css/utils.js
Just refactoring - consistently naming
=> refactor: `css` language

src/language-css/clean.js, src/language-css/printer-postcss.js, src/language-css/utils.js, tests/css_atrule/__snapshots__/jsfmt.spec.js.snap, tests/css_atrule/include.css, tests/css_scss/__snapshots__/jsfmt.spec.js.snap, tests/css_scss/scss.css, tests/css_trailing_comma/__snapshots__/jsfmt.spec.js.snap, tests/css_trailing_comma/at-rules.css
fixes #3235
Feedback welcome :+1:
=> fix: better output scss maps

tests_integration/__tests__/file-info.js
An async test wasn't really being asserted
=> Fix wrong test

src/language-js/printer-estree.js, tests/method-chain/__snapshots__/jsfmt.spec.js.snap, tests/method-chain/d3.js, tests/method-chain/short-names.js
=> Only break chains with short names if inside ExpressionStatement

src/common/util.js, src/language-markdown/parser-markdown.js, src/language-markdown/printer-markdown.js, tests/markdown_paragraph/__snapshots__/jsfmt.spec.js.snap, tests/markdown_paragraph/cjk.md
Fixes #4503
---
**Prettier pr-4504**
[Playground link](https://deploy-preview-4504--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuZSkAIDuBDATlASygHN1ALm0HhDAHSkFPowRX9BNr0Ap1QX7VA0TUAPTQVZtB+6MDvUwDD-gUVNAp3KBoOUAo9oC5PToAlTGmhQAaEBAAOMAtADOyUHlwRMABTwI9KbADcIBACYhVAI1zYwAazgwAyuvdExMgwuACucKpEOnC4MCZuxAC22MgAZtgANtGqAFY6AB4AQm6e3j7YiXAAMkRwaZnZIP640bjIIMm4HvbGUE5NuEQwAOoOMAAWyAAcAAyq6kbRw27q7QtwrdZ1qrhwAI6hBLvx2EkpSOlZESDRiQTBYdc6gRlwAIqhEPD1V6ow2M5RvYJsgAEx-NwEDKBADCEESyXaUGg2xAoWiABUAZZLtEAL54oA)
```sh
--parser markdown
```
**Input:**
```markdown
::: warning 注意
该网站在国外无法访问，故以下演示无效
:::
```
**Output:**
```markdown
::: warning 注意
该网站在国外无法访问，故以下演示无效
:::
```
=> fix(markdown): do not merge continuous cjk if proseWrap=preserve

website/pages/en/index.js
[155,216](https://github.com/prettier/prettier/network/dependents) now!
=> Update dependent count in website

tests/html_handlebars/__snapshots__/jsfmt.spec.js.snap, tests/html_handlebars/basic-handlebars.hbs
Closes #3983 by adding a test for it.
=> Add spec for multiple items in  class attributes in handle bars

src/language-css/printer-postcss.js, src/language-css/utils.js
=> refactor: `value-comma_group` node

src/language-css/printer-postcss.js, src/language-css/utils.js
I rewrote complex logic for a more readable. Also require for https://github.com/prettier/prettier/issues/4492
=> refactor: math operator

website/playground/util.js, website/static/new-worker.js
=> Fix playground

docs/browser.md, website/sidebars.json
cc @suchipi @azz @j-f1 for help :-)
=> Add standalone docs

src/language-js/printer-estree.js, tests/method-chain/__snapshots__/jsfmt.spec.js.snap, tests/method-chain/d3.js
=> Short rule should only apply to the first identifier

.appveyor.yml, tests_integration/__tests__/plugin-extensions.js, tests_integration/__tests__/plugin-preprocess.js, tests_integration/__tests__/plugin-resolution.js
=> Get tests passing on Windows

src/language-js/comments.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/variable_declarator.js
=> Handle comments in assignments before template literals

src/cli/util.js, src/main/options.js, tests_integration/__tests__/__snapshots__/infer-parser.js.snap, tests_integration/__tests__/infer-parser.js
=> Revert no parser error for API

.github/ISSUE_TEMPLATE.md
=> docs: replace NO-BREAK SPACE with the normal one

src/language-css/printer-postcss.js
=> Fix comment around color adjusters

scripts/build/build.js, scripts/build/util.js
Re-apply #4197 and #2791 (the updating issue template part)
=> chore(scripts): update ISSUE_TEMPLATE and exclude tarball

src/language-js/printer-estree.js, tests/method-chain/__snapshots__/jsfmt.spec.js.snap, tests/method-chain/inline_merge.js
=> Inline _ or $ in the root of a method chain

README.md
=> Add AppVeyor and Blazing to Badges

package.json, tests/typescript_decorators/__snapshots__/jsfmt.spec.js.snap, tests/typescript_decorators/interface.ts, yarn.lock
=> fix(typescript): preserve decorator on interface

website/static/worker.js
=> fix(playground): no unnecessary import

src/common/util.js, src/language-js/printer-estree.js, tests/jsx/__snapshots__/jsfmt.spec.js.snap, tests/jsx/array-iter.js
Closes #2707
I couldn't figure out a better heuristic to match this case
=> Break JSX in arrow functions in JSX expressions

src/language-js/printer-estree.js, tests/first_argument_expansion/__snapshots__/jsfmt.spec.js.snap, tests/first_argument_expansion/jsfmt.spec.js, tests/first_argument_expansion/test.js
=> Always expand first argument if the second argument is also a call expression

package.json, src/language-js/printer-estree.js, yarn.lock
Just some followup from https://github.com/prettier/prettier/pull/4543.
Flow commit:
https://github.com/facebook/flow/commit/dc71ec7e46851beaccf2908d022761af2c490b2d
=> flow-parser@0.74.0

src/language-css/clean.js, src/language-css/parser-postcss.js, src/language-css/pragma.js, src/language-css/printer-postcss.js, tests/insert-pragma/css/__snapshots__/jsfmt.spec.js.snap, tests/insert-pragma/css/front-matter.css, tests/insert-pragma/css/jsfmt.spec.js, tests/insert-pragma/css/simple.css, tests/insert-pragma/css/start-with-comment.css, tests/require-pragma/css/__snapshots__/jsfmt.spec.js.snap, tests/require-pragma/css/empty-front-matter-with-pragma.css, tests/require-pragma/css/empty-front-matter-without-pragma.css, tests/require-pragma/css/front-matter-with-pragma.css, tests/require-pragma/css/front-matter-without-pragma.css, tests/require-pragma/css/jsfmt.spec.js, tests/require-pragma/css/with-pragma-in-multiline.css, tests/require-pragma/css/with-pragma.css, tests/require-pragma/css/without-pragma.css
=> feat(css): support pragma

.travis.yml
I tried not running files with "flow" in them, but it doesn't stop segfaults :(
I'm setting `allow_failures` now, but we might as well just stop running tests in node 6 :(
=> Travis - Allow failures in Node 6

src/language-js/parser-babylon.js, tests/throw_expressions/__snapshots__/jsfmt.spec.js.snap, tests/throw_expressions/jsfmt.spec.js, tests/throw_expressions/throw_expression.js, tests_integration/__tests__/__snapshots__/debug-check.js.snap
=> Add support for parsing babylons throwExpressions

src/language-css/printer-postcss.js, tests/css_yaml/__snapshots__/jsfmt.spec.js.snap, tests/css_yaml/comment_after.css, tests/css_yaml/without-newline-after.css, tests/insert-pragma/css/__snapshots__/jsfmt.spec.js.snap, tests/require-pragma/css/__snapshots__/jsfmt.spec.js.snap
=> fix: newline between front-matter and comment

CHANGELOG.md
Fix excessive spacing in a few lists; update link text
=> A few changelog updates

src/language-graphql/parser-graphql.js, src/language-graphql/pragma.js, src/language-graphql/printer-graphql.js, tests/insert-pragma/graphql/__snapshots__/jsfmt.spec.js.snap, tests/insert-pragma/graphql/jsfmt.spec.js, tests/insert-pragma/graphql/with-pragma.graphql, tests/insert-pragma/graphql/without-pragma.graphql, tests/require-pragma/graphql/__snapshots__/jsfmt.spec.js.snap, tests/require-pragma/graphql/jsfmt.spec.js, tests/require-pragma/graphql/with-pragma.graphql, tests/require-pragma/graphql/without-pragma.graphql
=> feat(graphql): support pragma

src/language-js/printer-estree.js, tests/jsx/__snapshots__/jsfmt.spec.js.snap, tests/jsx/conditional-expression.js
Reverts prettier/prettier#4731
=> Revert "Ternary Operators in JSX Expression Containers"

src/language-yaml/index.js, tests/markdown/__snapshots__/jsfmt.spec.js.snap, tests_integration/__tests__/__snapshots__/support-info.js.snap
Just noticed I forgot to add it.
=> fix(yaml): add missing `since` field

docs/webstorm.md
File-Watcher is an extra plugin which needs to be installed.
=> It should be said that filewatcher is a plugin

src/language-vue/parser-vue.js, src/language-vue/pragma.js, src/language-vue/printer-vue.js, tests/insert-pragma/vue/__snapshots__/jsfmt.spec.js.snap, tests/insert-pragma/vue/jsfmt.spec.js, tests/insert-pragma/vue/with-pragma.vue, tests/insert-pragma/vue/without-pragma.vue, tests/require-pragma/vue/__snapshots__/jsfmt.spec.js.snap, tests/require-pragma/vue/jsfmt.spec.js, tests/require-pragma/vue/with-pragma.vue, tests/require-pragma/vue/without-pragma.vue
=> feat(vue): support pragma

package.json, src/language-js/printer-estree.js, tests/typescript_optional_type/__snapshots__/jsfmt.spec.js.snap, tests/typescript_optional_type/jsfmt.spec.js, tests/typescript_optional_type/simple.ts, tests/typescript_rest_type/__snapshots__/jsfmt.spec.js.snap, tests/typescript_rest_type/jsfmt.spec.js, tests/typescript_rest_type/simple.ts, yarn.lock
Ref: Microsoft/TypeScript#24897
=> feat(typescript): support TSOptionalType and TSRestType

src/language-js/needs-parens.js, tests/bind_expressions/__snapshots__/jsfmt.spec.js.snap, tests/bind_expressions/await.js
=> fix(javascript): add parens for await in bind

website/playground/Playground.js, website/playground/panels.js, website/static/separate-css/playground.css, website/static/service-worker.js
Closes #4769
[preview playground](https://deploy-preview-4770--prettier.netlify.com/playground/)
=> feat(playground): use real code sample

src/language-js/index.js, src/main/options.js, tests_integration/__tests__/__snapshots__/support-info.js.snap
Fixes #4234
Ref: https://flow.org/en/docs/libdefs/creation/#toc-declaring-a-module
=> feat: support .js.flow

docs/precommit.md
=> Adds closing quote to "hooks" in husky config

src/language-graphql/printer-graphql.js, tests/graphql_string/__snapshots__/jsfmt.spec.js.snap, tests/graphql_string/string.graphql
=> fix(grahpql): linebreak in non-block stringValue

package.json, src/language-js/needs-parens.js, src/language-js/printer-estree.js, yarn.lock
Ref: eslint/typescript-eslint-parser#429
=> refactor(typescript): remove unnecessary experimental types

website/data/editors.yml
Added `unibeautify-vscode` plugin for VSCode as an alternative prettier for VSCode
=> Added Unibeautify

src/doc/doc-utils.js
In addition to a tiny performance improvement outlined below,
the CPU profile of traverseDoc is now more readable.
Also anonymous arrow functions changed to named regular functions
so that they are properly displayed in the CPU profile,
and moved to outer scope where there's no closure
so that they aren't re-created (this change's performance is dependent
on JS engine implementation and optimization details).
Before (profile):
```
7129.9 ms       5.43 %    13349.9 ms     10.18 %    traverseDocRec
7067.4 ms       5.39 %    11285.5 ms      8.60 %      traverseDocRec
31.5 ms       0.02 %     1031.9 ms      0.79 %      traverseDoc
23.6 ms       0.02 %    12313.4 ms      9.39 %      traverseDoc
2.6 ms       0.00 %       0.3 ms       0.00 %      (anonymous)
1.7 ms       0.00 %       1.7 ms …
```
=> fix(perf): convert traverseDoc from recursion to stack (#4776)

scripts/build/build.js
Thanks to @SimenB for pointing this out!
=> Remove code removing a key I removed from package.json

package.json, src/main/support.js, tests/markdown/__snapshots__/jsfmt.spec.js.snap, tests_integration/__tests__/__snapshots__/schema.js.snap, tests_integration/__tests__/__snapshots__/support-info.js.snap
=> chore: use pre-release version number on master

src/language-vue/parser-vue.js, src/language-vue/printer-vue.js, src/main/range-util.js, tests/range_vue/__snapshots__/jsfmt.spec.js.snap, tests/range_vue/example.vue, tests/range_vue/jsfmt.spec.js, tests_integration/__tests__/format.js, website/playground/codeSamples.js
=> fix(vue): no error on range format

docs/webstorm.md
Add about file watcher template in available in WebStorm 2018.2
=> Updated WebStorm docs

docs/webstorm.md
https://prettier.io/docs/en/webstorm.html#using-prettier-with-eslint
=> docs(webstorm): Typo "Kymap"

package.json, scripts/build/build.js, scripts/build/config.js, src/config/resolve-config.js, tests_integration/__tests__/__snapshots__/config-invalid.js.snap, yarn.lock
Context: #4877
Ref: https://github.com/davidtheclark/cosmiconfig/blob/master/CHANGELOG.md#501
cc @jorgegonzalez
=> refactor: upgrade to cosmiconfig@5

docs/related-projects.md
Context: https://github.com/prettier/prettier/issues/4911#issuecomment-408932009
=> docs(related): add prettylint

docs/api.md, src/language-js/index.js, tests_integration/__tests__/__snapshots__/support-info.js.snap
=> fix: update flow support info

src/language-vue/embed.js, tests/vue_examples/__snapshots__/jsfmt.spec.js.snap, tests/vue_examples/script_src.vue
=> fix(vue): do not pass <script src> into multiparser

src/language-markdown/printer-markdown.js, tests/markdown_footnoteDefinition/__snapshots__/jsfmt.spec.js.snap, tests/markdown_footnoteDefinition/jsfmt.spec.js, tests/markdown_footnoteDefinition/long.md
=> fix(markdown): inline footnote def if there's only one 1-line paragraph

docs/plugins.md, src/common/util-shared.js, tests_integration/__tests__/util-shared.js
We need this utils for comments in `php` plugin
=> feat: newline and space utils to shared

docs/why-prettier.md
On https://prettier.io/docs/en/why-prettier.html, added hyperlink to 'Why Coding Style Matters' article.
=> added link to style guideline benefits, fixed issue #4894

src/language-js/printer-estree.js, tests/flow_generic/__snapshots__/jsfmt.spec.js.snap, tests/flow_generic/single-identifier.js
=> Inline Generics with a single identifier

src/language-js/printer-estree.js, tests/jsx/__snapshots__/jsfmt.spec.js.snap, tests/jsx/array-iter.js
=> fix: no false positive for arrow function in jsx expression

scripts/build/build.js
=> chore: copy LICENSE to dist

src/utils/front-matter.js, tests/markdown_yaml/__snapshots__/jsfmt.spec.js.snap, tests/markdown_yaml/trailing-spaces.md
Fixes #5106
```md
---···· <--- allowed
yaml
---···· <--- allowed
markdown
```
---
**Prettier pr-5107**
[Playground link](https://deploy-preview-5107--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEBadAdKAVAljAGziQAI9C4t1USssAfEp5l1tlx9r7n35zvoKb0GJauImSJJRlLnyFi9DLFK1NEVEYAZAIYBXAGYAvOPiHCSACgIHDCEgGoSALTMwAlCQAKcAE64EAAmJBCGJABqugS4QfgAnkKM3n5wAA66saEAFlBwJHpGpuZsmowAgka2QXDGAO66UADmDtyMVpWG1Q7OLg3NXgDC2bp+cc0kAPIARjFNujCBUDzJqRlZELn5nd31jU38om7403BNqVDG+hNt1scwTiSn5whXA2S4ALb52l8lFioUulMiFNnlXO5nhc3gcyiQACJwXQAa0WADdcP5rk0AM7FGB+AAn+m+KisiJR6Mxfmxj3uRJJcA8FLA6IWSx8-kCQRxKgBfDh5VmdiCCxJgkYAFEAB5pXB+dnQBELfL8iwCNVcOFo-yGaJEZZJMgQEhwWXy1WatUaq2sQWo3AYmCEmB49z2KA4+B+Xkqcqsx0JEiLUl1XBQIIQOq+20cWPsTRUdAgAA0IAgaUW0BxyFAoz8Ue8owQOZQujREFiqZA0wVYGRcBgAGUMmBw01kAT9HA0+Gcf4YCldE1PrpkHqCP20wArHH …
=> fix(markdown): trailing spaces after front matters are allowed

src/language-html/embed.js, src/language-html/parser-html.js, src/language-html/printer-htmlparser2.js, tests/html_js/__snapshots__/jsfmt.spec.js.snap, tests/html_js/something-else.html
- do not format unknown script
- do not normalize spaces in script tags
---
=> fix(html): do not format unknown script

docs/options.md
Fix broken "strings rationale" link
- [x ] I’ve added tests to confirm my change works.
- [ x] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).
=> Fix broken "strings rationale" link

package.json, yarn.lock
=> Bump babel-related deps

docs/related-projects.md
It belongs to the prettier organization now
=> Update link to stylelint-prettier

src/language-js/printer-estree.js, tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/variable_declarator.js
=> Fix comment in variable declarator

docs/vim.md
=> Add coc-prettier

README.md
I noticed that the space between badges was still a link. This PR fixes that issue, and makes the download statistic more immediate.
=> Adjust badges on the README

docs/precommit.md
Fix a typo in precommit.md Option 4.
=> Fix a typo in precommit.md Option 4.

src/language-js/comments.js, src/language-js/printer-estree.js, tests/try/__snapshots__/jsfmt.spec.js.snap, tests/try/catch.js
=> Fix printing of catch clause with a comment

src/language-js/printer-estree.js, tests/no-semi-typescript/__snapshots__/jsfmt.spec.js.snap, tests/no-semi-typescript/non-null.ts
=> Add ASI protection for TSNonNullExpression

website/pages/en/index.js
There isn‘t a `boolean` prop type, so this was throwing an error when Netlify built the site.
=> Fix prop type error

docs/eslint.md
I'm just updating some wording to make things clearer: when I read "Why not both?" I understood it more as a statement: "Why you should not use both: ..." until I understood the true meaning. I'd probably understand right away if it were 9 am but it's evening now and I think this makes it super clear.
=> [docs] Update eslint.md

website/data/languages.yml
Looks like they were overlooked.
=> Update some plugin links

src/language-js/printer-estree.js, tests/interface/__snapshots__/jsfmt.spec.js.snap, tests/interface/break.js
Fixes #4944 by listing each interface declaration on a seperate line.
This is my first contribution to prettier, still trying to wrap my head around the codebase and commands. Please let me know if I've done anything wrong.
=> Fix flow extends not breaking out into new lines

docs/plugins.md
Adds the Apex language plugin to the community section of the plugins page.
=> Added Apex plugin

src/language-js/printer-estree.js, tests/ternaries/__snapshots__/jsfmt.spec.js.snap, tests/ternaries/nested.js
=> fix(javascript): no regression for ternary#test alignment

package.json, tests/flow_object_inexact/jsfmt.spec.js, yarn.lock
Follows https://github.com/prettier/prettier/pull/5304 with flow inexact support in @babel/parser!
=> Bump @babel/parser

src/language-html/printer-html.js, src/language-html/utils.js, tests/html_vue/__snapshots__/jsfmt.spec.js.snap, tests/html_vue/pre-child.vue
=> feat(html): handle pre with interpolation

src/language-html/utils.js, tests/html_angular/__snapshots__/jsfmt.spec.js.snap, tests/html_angular/interpolation.component.html, tests/html_angular/jsfmt.spec.js
Context: https://github.com/prettier/prettier/pull/5259#issuecomment-436779557
cc @michaeljota
=> fix(ng|vue): whitespaces between interpolation and text are sensitive

docs/rationale.md
=> Update rationale to expand on sorting

docs/index.md
I am not sure if this omission is on purpose (e.g. "beta" support, etc.) but in any case, here it is :)
- ~I’ve added tests to confirm my change works.~
- ~(If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)~
~**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**~
=> Add HTML to the list of supported language in the docs

package.json, yarn.lock
Use `postcss@7` and drop `node@4` (some perf increase)
=> chore(deps): update `postcss-scss`

src/language-html/printer-html.js, tests/html_vue/__snapshots__/jsfmt.spec.js.snap, tests/html_vue/attributes.vue
=> fix(vue): group slot-scope correctly

tests/range_vue/__snapshots__/jsfmt.spec.js.snap, tests/range_vue/example.vue, website/playground/codeSamples.js
=> Update example for *.vue since templates are formatted as well now

package.json, src/language-js/parser-babylon.js, src/language-js/printer-estree.js, tests/classes_private_fields/__snapshots__/jsfmt.spec.js.snap, tests/classes_private_fields/private_fields.js, yarn.lock
=> Add support for class private methods

docs/options.md, src/common/internal-plugins.js, src/language-js/parser-babylon.js, src/main/core-options.js, tests/empty/__snapshots__/jsfmt.spec.js.snap, tests/flow_all/__snapshots__/jsfmt.spec.js.snap, tests/flow_all/generic.js, tests/flow_all/jsfmt.spec.js, tests_integration/__tests__/__snapshots__/early-exit.js.snap, tests_integration/__tests__/__snapshots__/help-options.js.snap, tests_integration/__tests__/__snapshots__/schema.js.snap, tests_integration/__tests__/__snapshots__/support-info.js.snap, website/static/worker.js
=> feat: add babel-flow

package.json, src/language-js/printer-estree.js, yarn.lock
This should be last set of major node changes for a little bit, things are pretty mature now.
=> chore: update typescript-estree to 18.0.0

src/common/load-plugins.js, src/utils/partition.js, tests_integration/__tests__/__snapshots__/format.js.snap, tests_integration/__tests__/format.js
=> fix: allow plugin instance (#5760)

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.unreleased.md
Ref: https://github.com/prettier/prettier/issues/5735#issuecomment-452784056
=> docs: add CHANGELOG.unreleased.md

docs/plugins.md
Adding a link to my plugin for svelte on the plugins page as suggested to me in #5511
=> Add svelte plugin to plugins page

docs/options.md
Another possible option is `if it gets`
=> fix: grammar `if it get` -> `if it goes`

docs/plugins.md, website/data/languages.yml, website/versioned_docs/version-stable/plugins.md
I left iamsolankiamit's package (it's still a community package), but replaced the one on the main website.
=> Add prettier-ruby package to docs

website/versioned_docs/version-stable/plugins.md
- Java  plugin link (in Jhipster org now)
- Added TOML plugin to stable docs (already in the regular docs).
=> update stable-docs plugins.md

src/common/util.js
=> pref: remove duplicated getLast

website/pages/en/index.js
=> Update dependent repos and integrations

website/data/languages.yml, website/pages/en/index.js, website/static/overrides.css
I removed the code formatting since code formatting is not for English, and updated the display a little to make it clearer which languages we support.
=> Update the language display on the homepage

website/package.json, website/yarn.lock
`webpack@4.29.6` update in `website/package.json` (and `website/yarn.lock`)
to work on Node.js version 10(+)
as discussed in <https://github.com/prettier/prettier/pull/5982#issuecomment-474412212> and <https://github.com/prettier/prettier/pull/5982#issuecomment-474514051>
/cc @thorn0 
- ~~(If the change is user-facing) I’ve added my changes to the `CHANGELOG.unreleased.md` file following the template.~~
=> webpack@4.29.6 update in website/package.json

CHANGELOG.unreleased.md, src/language-js/printer-estree.js, tests/preserve_line/__snapshots__/jsfmt.spec.js.snap, tests/preserve_line/argument-list.js, tests/preserve_line/parameter-list.js, tests/typescript_decorators/__snapshots__/jsfmt.spec.js.snap, tests/typescript_decorators/argument-list-preserve-line.ts
=> fix(js): respect blank lines in parameters

CHANGELOG.unreleased.md, src/language-js/printer-estree.js, tests/objects/__snapshots__/jsfmt.spec.js.snap, tests/objects/expression.js
=> fix(javascript): do not hug sequence expression in object properties

CHANGELOG.unreleased.md, package.json, src/language-js/printer-estree.js, tests/typescript_comments/__snapshots__/jsfmt.spec.js.snap, tests/typescript_comments/after_jsx_generic.ts, yarn.lock
=> Print comment following a JSX generic

CHANGELOG.unreleased.md, src/language-handlebars/parser-glimmer.js, src/language-handlebars/printer-glimmer.js, tests/glimmer/__snapshots__/jsfmt.spec.js.snap, tests/glimmer/curly.hbs, tests/handlebars/__snapshots__/jsfmt.spec.js.snap
Fixes https://github.com/prettier/prettier/issues/6184
**Input:**
```hbs
<p>Your username is @{{name}}</p>
<p>Hi {{firstName}} {{lastName}}</p>
```
**Output before this PR:**
```hbs
<p>
Your username is @
{{name}}
</p>
<p>
Hi
{{firstName}}
{{lastName}}
</p>
```
**Output after this PR:**
```hbs
<p>
Your username is @{{name}}
</p>
<p>
Hi {{firstName}} {{lastName}}
</p>
```
=> [Glimmer] improve text/mustache formatting

src/common/fast-path.js
Rewrite FastPath to ES class, and use rest parameters
=> Rewrite FastPath class

src/common/fast-path.js
Reverts prettier/prettier#6225
=> Revert "Rewrite FastPath class"

docs/plugins.md
ref #6245
I will release the plugin in an alpha state around next weekend?!
Then it can be found at https://www.npmjs.com/package/prettier-plugin-pug
=> Add Pug plugin to the list of plugins

docs/plugins.md
=> Remove Python plugin

CHANGELOG.md
=> Swap bases in changelog

docs/plugins.md, website/versioned_docs/version-stable/plugins.md
Move link up to Official Plugins
Update link to new repo location
=> Update docs - Plugin pug official

docs/plugins.md, website/versioned_docs/version-stable/plugins.md
Added a link to the kotlin plugin I'm currently working on.
=> add kotlin-plugin to plugins doc

tests/binary-expressions/__snapshots__/jsfmt.spec.js.snap, tests/binary-expressions/arrow.js, tests/binary-expressions/comment.js, tests/mdx/__snapshots__/jsfmt.spec.js.snap, tests/mdx/mixed.mdx, website/blog/2017-04-13-1.0.0.md, website/playground/codeSamples.js
=> docs: fix possible typo AFAIK

.eslintrc.yml, scripts/.eslintrc.yml
use Prettier format `.eslintrc.yml`
=> Fix `.eslintrc.yml` code style

docs/option-philosophy.md
... to more closely align with what we’ve learned the past 3 years.
Note: These are not my personal opinions. It’s my attempt at distilling
internal core discussions into a short document.
=> Update option philosophy

docs/precommit.md
Noticed that files I renamed+modified were not being reformatted on commit. This fixes that.
~~- [x] I’ve added tests to confirm my change works.~~
~~- [x] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)~~
~~- [x] (If the change is user-facing) I’ve added my changes to the `CHANGELOG.unreleased.md` file following the template.~~
=> include renames in git pre-commit hook

docs/configuration.md, website/versioned_docs/version-stable/configuration.md
Refs. #6415.
**✨[Try the docs for this PR](https://deploy-preview-6416--prettier.netlify.com/docs/en/configuration.html#configuration-overrides)✨**
=> Improve overrides documentation

CHANGELOG.unreleased.md, src/language-js/printer-estree.js, tests/typescript_decorators/__snapshots__/jsfmt.spec.js.snap, tests/typescript_decorators/decorators.js
=> JavaScript: object destructuring with parameter decorators

website/playground/Playground.js, website/playground/buttons.js, website/playground/markdown.js
Fix #6297
Check if report url is too long (>8000), change report url to _short report_ and copy full report to clipboard.
Example: [report issue](https://github.com/prettier/prettier/issues/new?body=%3C!--%20The%20full%20report%20is%20copied%20to%20your%20clipboard%2C%20paste%20it%20here.%20---%3E%0A%0A%3C!--%20Short%20report%3A%20---%3E%0A**Prettier%201.18.2**%0A%5BPlayground%20link%5D(http%3A%2F%2Flocalhost%3A3001%2Fplayground%2F%23N4Igxg9gdgLgprEAuc0DOMAEAzOMwAWAKgIYA2A1gMoEQDuamAvJgBRq0MA0mJADgEsA0nACePMiQwAJCAFcATmgCUzAHyZgAHSiZMCvIt0AFBRAC2AtHAB05Mu05ob5-q0IkoUOGXWadepBQGJiKviwABgQwMHxoSAD0CXQpNgDmEBBpZHD8VjaQ5gmi8jByAEZwCQBuAMwJ1iQKhAD8FGJMACTAeSKiAL4AZB5ePgCSACZdwCPeZEN8TTBMaFACfHx4XAITgxAKE3AKTBMk8IOuAB4ASnBocmQwaEwATAAMEQDcOgH6hgq6XD4AisMLKX56PQ2GAEBCsAxoPjoOB%2BBFI4K2ABWaGgrGU4N …
=> Playground: Fix "Report issue" 414 bug

CHANGELOG.unreleased.md, src/language-html/constants.evaluate.js, tests/html_script/__snapshots__/jsfmt.spec.js.snap, tests/html_script/script.html
=> HTML: treat scripts as blocks (not inline)

CHANGELOG.unreleased.md, src/language-js/printer-estree.js, tests/export_extension/__snapshots__/jsfmt.spec.js.snap, tests/export_extension/export.js
=> JavaScript: Fix formatting on long named exports

website/pages/en/index.js
Fix lint error happened since #6455
I noticed the error when  I fixed conflicts at #6382 . CI was failing where it was not related to my changes.
If unnecessary, please close this pr.
=> Fix lint error

package.json, src/language-css/index.js, src/language-graphql/index.js, src/language-handlebars/index.js, src/language-html/index.js, src/language-js/index.js, src/language-markdown/index.js, src/language-yaml/index.js, src/utils/create-language.js, tests_integration/__tests__/__snapshots__/support-info.js.snap, yarn.lock
Update linguist-languages to v7
=> Update linguist-languages to v7

CHANGELOG.unreleased.md, src/language-js/printer-estree.js, tests/switch/__snapshots__/jsfmt.spec.js.snap, tests/switch/switch.js
=> JavaScript: Fix inconsistent indentation in switch statement

package.json, yarn.lock
=> Update `mem` to latest v4

package.json, yarn.lock
=> Update `cross-env` to latest v5

package.json, yarn.lock
see https://github.com/prettier/prettier/pull/6548#issuecomment-536205661
=> Update `execa` to v1

package.json, yarn.lock
=> Update `string-width` to latest v3

CHANGELOG.unreleased.md, src/language-handlebars/printer-glimmer.js, tests/handlebars-attr-node/__snapshots__/jsfmt.spec.js.snap, tests/handlebars-attr-node/brackets.hbs, tests/handlebars-attr-node/jsfmt.spec.js, tests/handlebars-basics/__snapshots__/jsfmt.spec.js.snap, tests/handlebars-block-statement/__snapshots__/jsfmt.spec.js.snap, tests/handlebars-concat-statement/__snapshots__/jsfmt.spec.js.snap, tests/handlebars-element-node/__snapshots__/jsfmt.spec.js.snap
Closes https://github.com/prettier/prettier/issues/6376
=> fix(handlebars): Use quotes from config in AttrNode

package.json, yarn.lock
https://github.com/prettier/prettier/pull/6224#issuecomment-536538898
=> Update `yaml` to v1.1

docs/api.md, website/versioned_docs/version-stable/api.md
Fix #6567
I don't familiar to contribution to prettier documentation..., please review
=> Website: Update documentation of `resolveConfigFile`

package.json, yarn.lock
=> Update `@babel/core` & `@babel/preset-env` to v7.6.3

website/playground/codeSamples.js
=> Add code sample for `babel-flow` parser in playground

package.json, yarn.lock
=> Update `yaml-unist-parser` to support yaml@1.7.1

website/versioned_docs/version-stable/configuration.md
follow #6638 (ref: https://github.com/prettier/prettier/pull/6638#issuecomment-541390973)
=> Website: Update website to follow #6638

scripts/build/config.js
1. cache babel-plugin path
2. use `require.resolve` everywhere
=> Minor tweaks for build configs

src/common/get-file-info.js, tests_integration/__tests__/file-info.js
=> Fix an expired todo test

docs/api.md, website/versioned_docs/version-stable/api.md
=> Docs: update docs to follow #6665

docs/integrating-with-linters.md, docs/precommit.md, website/versioned_docs/version-stable/integrating-with-linters.md, website/versioned_docs/version-stable/precommit.md
As disscussed in https://github.com/prettier/prettier/pull/6475#issuecomment-531452177
Fixes: #6475
=> Docs: add link to `devDependencies`

CHANGELOG.unreleased.md, src/language-handlebars/printer-glimmer.js, tests/glimmer/preserved-spaces-and-breaks.hbs, tests/handlebars-basics/__snapshots__/jsfmt.spec.js.snap, tests/handlebars-block-statement/__snapshots__/jsfmt.spec.js.snap, tests/handlebars-comment/__snapshots__/jsfmt.spec.js.snap, tests/handlebars-concat-statement/__snapshots__/jsfmt.spec.js.snap, tests/handlebars-element-node/__snapshots__/jsfmt.spec.js.snap, tests/handlebars-mustache-statement/__snapshots__/jsfmt.spec.js.snap, tests/handlebars-newline/__snapshots__/jsfmt.spec.js.snap, tests/handlebars-sub-expression/__snapshots__/jsfmt.spec.js.snap, tests/handlebars-text-wrap/__snapshots__/jsfmt.spec.js.snap, tests/handlebars-whitespace/__snapshots__/jsfmt.spec.js.snap, tests/handlebars-whitespace/curly.hbs
=> Glimmer: Improve whitespace handling

package.json, yarn.lock
Actual change is add attribute `autofocus`
=> Update `html-element-attributes` to v2.2.0

package.json, yarn.lock
=> Update `jest-junit` to v9

package.json
pin `cspell` version to latest `4.0.31`, discuss in https://github.com/prettier/prettier/pull/6684#issuecomment-547838869
=> Pin `cspell` version

CHANGELOG.unreleased.md, src/language-js/needs-parens.js, src/language-js/utils.js, tests/flow_return_arrow/__snapshots__/jsfmt.spec.js.snap, tests/flow_return_arrow/in_object_type.js, tests/flow_return_arrow/parens.js
Fix https://github.com/prettier/prettier/issues/5831#issuecomment-462886440 .
**Input**
```js
var example = (): {p: (string => string)} => (0: any);
```
**output(stable)**
```js
var example = (): {p: string => string} => (0: any);
```
attempting to format the above output again results in a syntax error.([Playground Link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA3AhgJwARwB7oC2ADgDZzYC82AFAJRLbDGMDOMmAllAOZUB82dl14BfAbQAMjdFACedANwAdKCAA0ICMRidorZKCyYIAdwAKWBAZTpUETgBMNIAEaZ0YANZwYAZWJPbh5kDgBXOE0ACxhCUgB1KM54VkCwOD9rZM5UZLlkcFYDTW5WOEwYcw8eQnRkADN0UjLNACtWPAAhD29fPyI4ABluOAamlpB2vD9g8gBFMIh4MebIkEDMMswC13RXOFIAWnrSMxdiERh4pxgo5AAOSU0LiDL4j2ICi7gt1FHNACOi3gVW0NhA6FYhygcDgjjhLkwcCBnCRVXQNTqSEaq00ZUInFCmAieNmcAWS1G2PGaxge2ujluyAATJoOOhOKRggBhCCEWoFKDQf4gMJlAAqexsOLKolEQA))
``` …
```
=> Flow: Keep parentheses wrap specific FunctionTypeAnnotation

azure-pipelines.yml
Node 12 is already LTS, let's run CI scripts on Node 12
https://nodejs.org/en/blog/release/v12.13.0/
=> Run CI on node 12

docs/index.md
safer and saves a HTTP requests :-)
=> HTTPS external links

docs/plugins.md, src/common/util.js, src/main/comments.js, website/versioned_docs/version-stable/plugins.md
Added types based on https://prettier.io/docs/en/plugins.html#utility-functions
Referencing #6703 
=> JSDoc type added in `src/common/util.js`

package.json, yarn.lock
=> Bump `eslint` from 6.5.1 to 6.6.0

tests/comments/__snapshots__/jsfmt.spec.js.snap, tests/comments/jsdoc.js
fixes #6283
Just tests, it seems we already solved this problem
=> test: issue #6283

CHANGELOG.unreleased.md, src/language-js/printer-estree.js, tests/async/__snapshots__/jsfmt.spec.js.snap, tests/async/inline_await.js
=> better formatting for AwaitExpression in CallExpression/MemberExpression

src/language-js/postprocess.js, tests/flow_enums/__snapshots__/jsfmt.spec.js.snap, tests/flow_enums/enum-comments.js
=> fix formatting of comments in flow enums

yarn.lock
fix [warning](https://dev.azure.com/prettier/prettier/_build/results?buildId=2715&view=logs&jobId=afd2db75-0a23-56ec-00f6-5aec6de004e8&taskId=bdbf96c4-18ba-5e53-f741-af2442c390ef&lineStart=18&lineEnd=19&colStart=1&colEnd=1) when running build script 
=> Update browerslist in yarn.lock

CHANGELOG.unreleased.md, src/cli/util.js, tests_integration/__tests__/__snapshots__/config-invalid.js.snap, tests_integration/path-serializer.js
Show invalid config filename in error message, makes it easier to find problem
=> Show invalid config filename in error message

cspell.json, docs/browser.md, scripts/release/steps/update-version.js
=> Fix unpkg links in docs

CHANGELOG.unreleased.md, src/language-html/utils.js, tests/html_vue/__snapshots__/jsfmt.spec.js.snap, tests/html_vue/style.vue
=> Format `style[lang="css"]`

package.json, yarn.lock
=> Update `@rollup/plugin-replace` to v2.2.1

package.json, yarn.lock
=> Update `flow-parser` to v0.111.3

package.json, yarn.lock
=> Update `@babel/core` to v7.7.2

package.json, yarn.lock
fixes #6806
the reason we use the one from code base https://github.com/prettier/prettier/pull/5611 , it's resolved https://github.com/codecov/codecov-node/pull/114
=> Update `codecov` to v3.6.1

yarn.lock
I used this tool: https://github.com/atlassian/yarn-deduplicate
=> deduplicate entries in yarn.lock

.azure-pipelines/jobs/prod-build.yml, scripts/build/build.js, scripts/build/rollup-plugins/executable.js
fixes: #6900 , this is a bug introduced in #6200
=> Fix bin permissions

yarn.lock
fix `yarn install` [fails on macOS](https://dev.azure.com/prettier/prettier/_build/results?buildId=2886&view=logs&jobId=d355a03b-aec9-56f2-3bda-a3f1ad325fa8&taskId=c669dcab-d2a2-5f5c-c9b6-69dcdd9d2c61&lineStart=489&lineEnd=490&colStart=1&colEnd=1)
=> Update `fsevents` in yarn.lock

scripts/build/config.js
Fixes #6903 (tested with `yarn link` and webpack)
Thanks to @j-f1 for figuring out the fix
=> Remove typescript-etw from build

package.json, tests_integration/__tests__/__snapshots__/support-info.js.snap, yarn.lock
=> Update `snapshot-diff` to v0.6.1

tests/typescript_error_recovery/__snapshots__/jsfmt.spec.js.snap, tests/typescript_error_recovery/generic.ts, tests/typescript_error_recovery/jsfmt.spec.js
=> fix: issue #5839

docs/rationale.md
=> Fix a code example in docs

.eslintrc.yml, package.json, src/cli/util.js, src/common/util.js, src/language-css/clean.js, src/language-css/parser-postcss.js, src/language-css/printer-postcss.js, src/language-css/utils.js, src/language-handlebars/printer-glimmer.js, src/language-html/printer-html.js, src/language-html/utils.js, src/language-js/pragma.js, src/language-js/printer-estree.js, src/language-js/utils.js, src/language-markdown/embed.js, src/language-markdown/parser-markdown.js, src/language-markdown/printer-markdown.js, src/language-yaml/printer-yaml.js, src/language-yaml/utils.js, src/main/core.js, src/main/options-normalizer.js, src/main/options.js, src/main/range-util.js, src/main/support.js, tests_integration/path-serializer.js, website/playground/urlHash.js, yarn.lock
=> Replace `indexOf` with `includes`

scripts/build/babel-plugins/replace-array-includes-with-indexof.js
=> Update `includes -> indexof` plugin

src/language-graphql/printer-graphql.js, src/language-js/printer-estree.js, src/language-markdown/pragma.js, src/language-markdown/preprocess.js, src/language-markdown/printer-markdown.js, src/language-yaml/utils.js, src/main/core.js
=> Replace `trim{Left,Right}` with `trim{Start,End}`

tests/multiparser_js_css/__snapshots__/jsfmt.spec.js.snap, tests/multiparser_js_css/styled-components.js
Just tests
fixes #2601 fixes #2291 fixes #2623
=> test: css-in-js

src/language-js/parser-typescript.js
=> refactoring: tokens requested from TS parser were immediately dismissed

changelog_unreleased/handlebars/pr-7052.md, src/language-handlebars/printer-glimmer.js, tests/handlebars-mustache-statement/__snapshots__/jsfmt.spec.js.snap, tests/handlebars-mustache-statement/basics.hbs
Will fix:
```hbs
{{!-- input --}}
<GlimmerComponent @progress={{aPropertyEndingAfterEightiethColumnToHighlightAWeirdClosingParenIssue}} />
{{!-- stable --}}
<GlimmerComponent
@progress={{aPropertyEndingAfterEightiethColumnToHighlightAWeirdClosingParenIssue
}}
/>
{{!-- master --}}
<GlimmerComponent
@progress={{aPropertyEndingAfterEightiethColumnToHighlightAWeirdClosingParenIssue}}
/>
```
=> Fix a falling mustache issue

changelog_unreleased/javascript/pr-7087.md, src/language-js/printer-estree.js, tests/ternaries/__snapshots__/jsfmt.spec.js.snap, tests/ternaries/nested-in-condition.js, tests/typescript_conditional_types/__snapshots__/jsfmt.spec.js.snap, tests/typescript_conditional_types/nested-in-condition.ts
=> fix indentation in ternaries nested in conditions of other ternaries

tests/typescript_array/__snapshots__/jsfmt.spec.js.snap, tests/typescript_array/key.ts
=> typescript: add test for ugly array key format

changelog_unreleased/handlebars/pr-7051.md, src/language-handlebars/printer-glimmer.js, tests/handlebars-concat-statement/__snapshots__/jsfmt.spec.js.snap, tests/handlebars-concat-statement/in-attr-node.hbs, tests/handlebars-mustache-statement/__snapshots__/jsfmt.spec.js.snap, tests/handlebars-mustache-statement/basics.hbs
Fix https://github.com/prettier/prettier/issues/6252 and improve (fix?) https://github.com/prettier/prettier/issues/6207
=> handlebars: Fix superfluous line breaks in ConcatStatement

changelog_unreleased/vue/pr-7180.md, src/language-html/utils.js, tests/multiparser_vue/__snapshots__/jsfmt.spec.js.snap, tests/multiparser_vue/lang-jsx.vue
=> Vue: format sfc jsx

docs/plugins.md
Ref https://github.com/prettier/prettier/issues/5536#issuecomment-443689832
**✨[Updated plugin docs](https://deploy-preview-5594--prettier.netlify.com/docs/en/plugins)✨**
=> Remove the beta label from the plugin docs

package.json, scripts/build/bundler.js, scripts/build/config.js, src/common/third-party.js, src/config/resolve-config.js, tests_integration/__tests__/__snapshots__/config-invalid.js.snap, tests_integration/runPrettier.js, yarn.lock
=> Update `cosmiconfig` to v6

website/core/Footer.js
From the conversation on Twitter
=> Add a Netlify badge to the footer

package.json, yarn.lock
https://github.com/prettier/prettier/pull/6684#issuecomment-547837420
=> Add `cspell` as `devDependencies`

package.json, yarn.lock
=> Update `eslint` to v6.8.0

changelog_unreleased/handlebars/pr-7051.md, changelog_unreleased/javascript/pr-7070.md, changelog_unreleased/javascript/pr-7140.md, changelog_unreleased/scss/pr-7211.md, changelog_unreleased/typescript/pr-7075.md, changelog_unreleased/vue/pr-7180.md, package.json
=> Run `lint-docs` on changelogs

package.json, src/main/support.js, yarn.lock
fixes: https://github.com/prettier/prettier/pull/7151
=> Update `semver` to v7

tests_integration/__tests__/util-shared.js
Add test for `sharedUtil.getMaxContinuousCount`, prepare for https://github.com/prettier/prettier/pull/6730
=> Add tests for `sharedUtil.getMaxContinuousCount`

package.json, yarn.lock
fixes: https://github.com/prettier/prettier/pull/6925
=> Update `strip-ansi` to v6

website/package.json, website/yarn.lock
=> Update `codemirror-graphql` to v0.11.6

.editorconfig, tests_integration/__tests__/plugin-default-options.js, tests_integration/__tests__/with-config-precedence.js, tests_integration/cli/config/js/.editorconfig
=> Add `.editorconfig`

.eslintrc.yml, scripts/build/rollup-plugins/evaluate.js, scripts/release/steps/validate-new-version.js, src/config/resolve-config.js, src/language-css/printer-postcss.js, src/language-html/printer-html.js, src/language-html/syntax-attribute.js, tests_integration/__tests__/cursor-offset.js, tests_integration/__tests__/early-exit.js, tests_integration/__tests__/file-info.js, tests_integration/__tests__/format.js, tests_integration/runPrettier.js
=> Fix quote style, enable `quote` rule

package.json, yarn.lock
=> Update `@babel/code-frame` to v7.8.0

.eslintrc.yml, src/cli/index.js, src/cli/util.js, src/language-js/printer-estree.js, tests_config/run_spec.js
=> Style: enable `dot-notation`

.eslintrc.yml, src/doc/doc-builders.js, src/doc/doc-debug.js, src/index.js, src/language-css/parser-postcss.js, src/language-js/embed.js, src/language-js/printer-estree.js, src/main/range-util.js, src/standalone.js, website/static/worker.js
=> Style: enable `object-shorthand`

package.json, yarn.lock
=> Update `rollup-plugin-terser` to v5.2.0

.eslintrc.yml, src/utils/arrayify.js
=> Simplify `arrayify`

.eslintrc.yml, src/language-css/index.js, src/language-graphql/index.js, src/language-handlebars/index.js, src/language-html/index.js, src/language-js/index.js, src/language-markdown/index.js, src/language-yaml/index.js
=> Use object spread for `createLanguage`

.eslintrc.yml, src/language-handlebars/printer-glimmer.js, src/language-js/embed.js, src/language-js/printer-estree.js, src/language-js/utils.js
=> Style: enable `eqeqeq`

yarn.lock
Lock file in `next` seems not right.
=> Fix `yarn.lock` for next

src/language-js/parser-flow.js
=> Remove a old fix

src/language-js/comments.js
=> Tiny refactor `comment.js`

package.json, yarn.lock
Original PR #6730 closed by force push again... create new one.
=> Update `escape-string-regexp` to v2

.eslintrc.yml, src/main/support.js
=> Simplify `getSupportInfo`

src/main/core.js, src/main/multiparser.js, src/main/options-normalizer.js, src/main/options.js
=> Fix `prefer-object-spread` in `src/main`

src/common/load-plugins.js
=> Fix `prefer-object-spread` in `src/common`

package.json, yarn.lock
=> Update `tempy` to v0.3.0

changelog_unreleased/angular/pr-7371.md, src/language-html/printer-html.js, tests/html_angular/__snapshots__/jsfmt.spec.js.snap
fixes https://github.com/prettier/prettier/issues/5875#issuecomment-575051597
=> angular: fix i18n attr with @@

package.json, yarn.lock
=> Update `snapshot-diff` to v0.6.2

tests/typescript_class/__snapshots__/jsfmt.spec.js.snap, tests/typescript_class/constructor.ts
=> Add test for typed constructor

scripts/build/build.js, scripts/release/utils.js, website/playground/markdown.js
=> Some `String#repeat`

tests/css_loose/__snapshots__/jsfmt.spec.js.snap, tests/css_loose/jsfmt.spec.js, tests/css_loose/loose.css, tests/css_loose/loose.js
Case added in #1766 , but not tested.
Closes: #3214
=> Add missing snapshot

package.json, yarn.lock
This module was updated in #6731 , downgraded in #6894 , for compatible reason. Should good to do this in `next`.
=> Update `get-stream` to v5

src/language-js/parser-babylon.js
=> Fix `prefer-object-spread` in `src/language-js` (part 4)

src/language-js/embed.js, src/language-js/parser-angular.js, src/language-js/parser-flow.js, src/language-js/parser-typescript.js, src/language-js/pragma.js, src/language-js/preprocess.js
=> Fix `prefer-object-spread` in `src/language-js` (part 1)

src/language-js/printer-estree.js
=> Fix `prefer-object-spread` in `src/language-js` (part 2)

src/document/doc-debug.js, src/document/doc-printer.js, src/document/doc-utils.js
=> Fix `prefer-object-spread` in `src/document`

src/language-js/postprocess.js
=> Fix `prefer-object-spread` in `src/language-js` (part 3)

src/cli/minimist.js, src/cli/util.js
=> Fix `prefer-object-spread` in `src/cli`

src/language-html/ast.js, src/language-html/constants.evaluate.js, src/language-html/preprocess.js, src/language-html/printer-html.js
=> Fix `prefer-object-spread` in `src/language-html`

src/language-css/parser-postcss.js
=> Fix `prefer-object-spread` in `src/language-css`

src/language-yaml/utils.js
Part of https://github.com/prettier/prettier/pull/7339
=> Fix `prefer-object-spread` in `src/language-yaml`

.eslintrc.yml, tests/.eslintrc.yml, tests_config/.eslintrc.yml, tests_config/require_standalone.js, tests_config/run_spec.js, tests_integration/.eslintrc.yml, tests_integration/__tests__/help-options.js, tests_integration/__tests__/support-info.js, tests_integration/runPrettier.js
=> Fix `prefer-object-spread` in `/tests*`

src/language-markdown/parser-markdown.js, src/language-markdown/preprocess.js, src/language-markdown/utils.js
=> Fix `prefer-object-spread` in `src/language-markdown`

src/config/resolve-config.js
=> Fix `prefer-object-spread` in `src/config`

src/language-js/printer-estree.js
=> Tiny refactor

.eslintrc.yml
All fixes already merged, this PR enable this rule.
=> Enable eslint rule `prefer-object-spread`

src/document/doc-printer.js
=> chore(doc-printer): Fixed minor typo

website/pages/en/users/index.js
Fixes: #4062
https://deploy-preview-7379--prettier.netlify.com/en/users/
=> Add title to the `/en/users/` page

changelog_unreleased/graphql/pr-7305.md, src/language-graphql/printer-graphql.js, tests/graphql_interface/__snapshots__/jsfmt.spec.js.snap, tests/graphql_interface/separator-detection.graphql, tests/graphql_interface/test-substr.graphql
- [stable playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAKpuARmwEsBbDAGzjIRgGdsBBAGmwCEAdKAYm2GwAybNgA8AWnHYASjQgA3HDAAWJRpDK1Y2MMoCGUAOZxG9OBj0AnPTAiXSUbPRh6ARtW7A9SbHoC+3HwAyuZWNnbYANZw5r6MJDCk8Y4qajp6ZtzoWHgEAEykFNRaDMxs7ELYAMJePv4gLCAQGDAk0PTIoFaWEADuAApWCB0oevIQJAAmDSCu1mDRMEEWYCRGyDCWAK5wjcowZJQA6qrw9CtwIVD0CSTyCWjI4PQdjWtmljD91oZkesgAMz0lDMjQAVvQAB7seaLIJ6WgAGTWcEBwNBIAhkKCa0M1AAilsIPA0SDdiALJYPk9DNYMMoAI6UGYYSxrGBHKYqZAADgADI1WRAzEc6U9WSY4JZFDMGUT4N9miMQBlxFAYpM4NNGpY4HKSLrvnpfv8kECyY0zGQSBttuSbkYCfLUWb0eSXK5OZNuUg8o1NnoSJRcVUIJpTSAoNBUY0tmZcG4RuaMfIdgBJKCa2BBMBslpMTNBdDUUlmPx+IA)
=> Improve separator between interfaces detection

website/static/landing.js
=> Remove `eslint-disable` in landing.js

package.json, scripts/build/bundler.js, scripts/build/shims/tty.js, yarn.lock
=> Update `chalk` to v3

src/utils/get-last.js
Returning `undefined` instead of `null` on empty array.
=> Simplify `getLast`

docs/for-enterprise.md, website/pages/en/index.js, website/sidebars.json
This adds the Tidelift enterprise language to the prettier website. Once implemented, prettier will be eligible to receive a lead referral bonus!
=> website: add Tidelift enterprise language

src/cli/util.js
=> Simplify `createUsage`

changelog_unreleased/api/pr-6963.md, docs/options.md
Motiviation: https://github.com/prettier/prettier/pull/6963#issuecomment-578434520
cc @fisker 
- ~I’ve added tests to confirm my change works.~
- ~(If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)~
=> Document changes in 6963

package.json, scripts/build/config.js, yarn.lock
=> Bump @glimmer/syntax from 0.41.0 to 0.47.0

package.json, scripts/build/build.js, scripts/build/bundler.js, scripts/build/config.js
https://github.com/prettier/prettier/pull/7400#issuecomment-576396242
=> Update babel target

scripts/build/config.js
=> Always set parser bundle target to `universal`

website/pages/playground/index.html
Update versions to latest, and use minified version.
=> Update cdn files version

changelog_unreleased/flow/pr-7472.md, src/language-js/printer-estree.js, tests/flow/symbol/__snapshots__/jsfmt.spec.js.snap, tests/flow/symbol/symbol.js
=> Flow: add typing support for the `symbol` type

changelog_unreleased/flow/pr-7484.md, src/language-js/printer-estree.js, tests/flow/get-def/__snapshots__/jsfmt.spec.js.snap, tests/flow/get-def/class.js, tests/flow/optional_chaining/__snapshots__/jsfmt.spec.js.snap, tests/flow/optional_chaining/jsfmt.spec.js, tests/flow/optional_chaining/private_properties.js, tests/flow/private_class_fields/__snapshots__/jsfmt.spec.js.snap, tests/flow/private_class_fields/jsfmt.spec.js, tests/flow/private_class_fields/test.js, tests/flow_private_class_fields/__snapshots__/jsfmt.spec.js.snap, tests/flow_private_class_fields/jsfmt.spec.js, tests/flow_private_class_fields/quotes.js
- [Stable Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgGIQQ7ADEADgE4CWAbuvAAoURlI5QCuAtgEZwUBuAL4gANCBYwq0TMlDoKzAO4MFCWSnQ0IVACZiQPCujABrODADKZE1SgBzZDAoc44gBYwuqAOruq8Jg2YHCW6gG0AQCeyODYBnaY-DBM6PZc6MgAZuioSeIAVpgAHgBCxmYWluhccAAydnDZufkgRcWWdvaocACKHBDwzXluIDYUSRSxWagQSgaUdjA+ejDuyAAcAAzilBBJPsZksZRwkzRN4gCOA4zMZBogWAC0UHBwuh8GFHA3VD+pdKZJA5EbiJJcKhOFyjTBdHr9QZNEEtUYwdA8Fa6NbIABM4mc6CoqC6AGEIFwMrEoNBLiAOEkACoYjSg1o0VwASSgn1gljA1DIMAAgjzLDAoj1hkkhEIgA)
- [PR Playground](https://deploy-preview-7484--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgGIQQ7ADEADgE4CWAbuvAAoURlI5QCuAtgEZwUBuAL4gANCBYwq0TMlDoKzAO4MFCWSnQ0IVACZiQPCujABrODADKZE1SgBzZDAoc44gBYwuqAOruq8Jg2YHCW6gG0AQCeyODYBnaY-DBM6PZc6MgAZuioSeIAVpgAHgBCxmYWluhccAAydnDZufkgRcWWdvaocACKHBDwzXluI …
=> Flow: Add support for `ClassPrivateProperty`

scripts/build/bundler.js, scripts/generate-schema.js, src/cli/minimist.js, src/cli/util.js, src/document/doc-builders.js, src/language-html/constants.evaluate.js, src/main/options-normalizer.js, src/main/options.js
=> Refactor some `Object.assign`

src/language-handlebars/clean.js, src/language-handlebars/printer-glimmer.js
This PR proposes to extract clean function from glimmer-printer to its file, similarly to what is done with language-js / language-html.
=> refactoring(glimmer): Create a clean file

docs/technical-details.md
=> Add missing comma in `technical-details.md`

changelog_unreleased/html/pr-7395.md, src/language-html/printer-html.js, tests/html_angular/__snapshots__/jsfmt.spec.js.snap, tests/html_tags/__snapshots__/jsfmt.spec.js.snap, tests/html_tags/tags.html, tests/html_vue/__snapshots__/jsfmt.spec.js.snap, tests/html_vue/self_closing.vue
- [stable playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAzgBwIZQHyoCWUmArjAAQwCemcAvADrgAWcYA1gEYQAezAejwVUArLjyMoGHPhkSiJclVoNmYNpx78QQ0eLljZk6QYLEylGnSat23PoIJGJIADQgImGIWjpkoNgATkEQAO4ACsEI-ijYAG4QhAAm7iBcQdiccDAAyjhgxADmyDBBpHAeLDAAtgA2AOoshPDiYHC5MS2E8S3UyODo-h7E6HBBMBGZRTXYyABm2HVjHgBW6LwAQpnZedg1cAAyxHALSysg67y5xXVwAIqkEPBny5UgOEFjQQPV9WmYILEGANFIwFjIAAcAAYPICIGMGplMANAXBvvFTh4AI5PeBTLyxEDYdAAWigcDgySpaSCcFxhDpU2wMzmSEWbw8YxqhFK5Xe6FuDzxp3Z53eMGwXFByXByAATB4ythCHVigBhCA1WYDKDQLEgUhjAAqUtiHIu8QqAEkoNTYLkwEDvABBO25Gh3V5jAC+PqAA)
- [PR playground](https://deploy-preview-7395--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAeAzgBwIZQHyoCWUmArjAAQwCemcAvADrgAWcYA1gEYQAezAejwVUArLjyMoGHPhkSiJclVoNmYNpx78QQ0eLljZk6QYLEylGnSat23PoIJGJIADQgImGIWjpkoNgATkEQAO4ACsEI-ijYAG …
=> HTML: Fix inconsistent formatting of self-closing tags

src/common/fast-path.js
=> Remove unnecessary type-casting in `FastPath`

src/language-css/index.js, src/language-graphql/index.js, src/language-handlebars/index.js, src/language-html/index.js, src/language-js/index.js, src/language-markdown/index.js, src/language-yaml/index.js, src/utils/create-language.js
=> Simplify `createLanguage`

src/config/resolve-config.js
=> Remove usage of cosmiconfig v4 interface

package.json, yarn.lock
`@angular/compiler` already released for a while, why the bot haven't send PR?
=> Update `@angular/compiler` to v9

tests_integration/__tests__/plugin-resolution.js, tests_integration/plugins/automatic/prettier-plugin-bar.js
Add a test with same packageName and fileName, fix a missing case from #7508
=> Improve `plugin-resolution` test

tests/css_scss/__snapshots__/jsfmt.spec.js.snap, tests/css_scss/scss.scss
Initially I wanted to fix the bug described in #4659 but it turns out it's already fixed. So I added a bit of test code to illustrate that and prevent regressions.
> (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
If I should do this, I'm more than willing to. I don't know how it works though and I didn't see any reference to it in the Contributing markdown.
=> Added a test to verify that #4659 is closed

changelog_unreleased/api/pr-7533.md, scripts/build/config.js, src/common/internal-plugins.js, src/language-js/parser-babel.js, src/main/core-options.js, tests_config/require_standalone.js, tests_integration/__tests__/deprecated-parser.js, tests_integration/__tests__/parser-api.js, website/playground/codeSamples.js, website/playground/markdown.js, website/static/service-worker.js, website/static/worker.js
=> Remove `babylon` parser

changelog_unreleased/api/pr-7536.md, src/common/common-options.js, src/language-js/options.js, tests_integration/__tests__/__snapshots__/arg-parsing.js.snap, tests_integration/__tests__/arg-parsing.js
=> Remove deprecated options

changelog_unreleased/api/pr-7511.md, src/main/core-options.js, tests_integration/__tests__/__snapshots__/arg-parsing.js.snap, tests_integration/__tests__/arg-parsing.js
=> Remove `--flow-parser/useFlowParser`

changelog_unreleased/api/pr-5813.md, tests_integration/__tests__/__snapshots__/config-resolution.js.snap, tests_integration/__tests__/__snapshots__/with-config-precedence.js.snap, tests_integration/cli/config/jest/__best-tests__/.file.js
Include dot files in overrides pattern matching.
=> include dot files in overrides pattern matching

changelog_unreleased/cli/pr-7668.md, docs/vim.md, src/cli/constant.js, src/cli/index.js, tests_integration/__tests__/__snapshots__/early-exit.js.snap, tests_integration/__tests__/__snapshots__/help-options.js.snap, tests_integration/__tests__/infer-parser.js, tests_integration/__tests__/plugin-precedence.js, tests_integration/__tests__/syntax-error.js, tests_integration/__tests__/with-config-precedence.js
Closes https://github.com/prettier/prettier/issues/4559
See https://github.com/prettier/prettier/issues/4097
=> remove --stdin

package.json, src/language-css/parser-postcss.js, src/language-css/printer-postcss.js, src/language-css/utils.js, tests/css_case/__snapshots__/jsfmt.spec.js.snap, tests/css_case/case.less, tests/css_comments/__snapshots__/jsfmt.spec.js.snap, tests/css_less/__snapshots__/jsfmt.spec.js.snap, tests/css_less/function-each.less, yarn.lock
=> Update `postcss-less` to v3

changelog_unreleased/less/pr-6981.md, cspell.json
=> add changelog entry for #6981

changelog_unreleased/vue/pr-7781.md, src/language-js/printer-estree.js, tests/html_vue/__snapshots__/jsfmt.spec.js.snap, tests/html_vue/v-if.vue
=> Fix vue attributes indention

website/blog/2020-03-21-2.0.0.md
Context: https://github.com/prettier/prettier/pull/7417#issuecomment-602108600
- ~~(If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.~~
=> Fix version references in v2.0 blog post

package.json, src/cli/index.js, tests_integration/__tests__/__snapshots__/early-exit.js.snap, tests_integration/__tests__/early-exit.js, yarn.lock
https://github.com/typicode/please-upgrade-node#readme
- (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
=> Add please-upgrade-node

src/language-js/printer-estree.js, src/language-js/utils.js
tiny refactor for `isBinaryish`.
=> [JavaScript] Tiny refactor for `isBinaryish`.

.github/workflows/dev-test.yml, .github/workflows/lint.yml, .github/workflows/prod-test.yml, tests_config/run_spec.js
- Only run CI on `master` branch push , https://github.com/prettier/prettier/pull/7824#issuecomment-603144486
- Add missing `TEST_CRLF` https://github.com/prettier/prettier/pull/7824#issuecomment-602921159
=> Tweak CI configs

.github/workflows/dev-test.yml, jest.config.js
Ref: #7401
Remove `verbose` as requested in https://github.com/prettier/prettier/pull/7866#issuecomment-605892388
=> Try upload coverage with token

.codecov.yml, src/common/internal-plugins.js, src/language-css/parser-postcss.js
Clear logic, prepare for #7740
=> Split css parsers

docs/cli.md, docs/options.md, docs/vim.md, docs/watching-files.md
- (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
=> Update docs code style

src/language-handlebars/printer-glimmer.js, src/language-handlebars/utils.js
I'm doing a POC to introduce a `hbsWhitespaceSensitivity` option.
On the way, I noticed that we could group / simplify / extract / remove some code. It might be easier to review it commit by commit. I could split this PR in smaller chunks if you'd like.
=> Refactor glimmer-printer

.eslintrc.yml, src/language-css/utils.js, src/language-handlebars/utils.js, src/language-js/utils.js, src/language-markdown/printer-markdown.js, src/main/range-util.js
=> Enable `unicorn/prefer-set-has`

.github/workflows/dev-test.yml, .github/workflows/lint.yml, .github/workflows/prod-test.yml
=> Enable GitHub Actions for a patch-release branch

.github/workflows/prod-test.yml
Seems the master ref is not right, let's see if this PR hit the cache.
Fix  mistake in  https://github.com/prettier/prettier/pull/8027
=> Fix master ref

src/language-js/parser-babel.js, tests/errors/json/__snapshots__/jsfmt.spec.js.snap, tests/errors/json/jsfmt.spec.js
=> Test json parse errors

package.json, yarn.lock
=> Bump `angular-html-parser` to `v1.5.0`

.eslintignore, .eslintrc.yml, scripts/build/shims/assert.js, scripts/build/shims/os.js, scripts/build/shims/path.js, scripts/build/shims/tty.js
=> Missing files on lint

tests/html_script/__snapshots__/jsfmt.spec.js.snap, tests/html_script/script.html
It's already fixed by #8023, closes #8147
=> Add test for issue 8147

tests/destructuring_ignore/__snapshots__/jsfmt.spec.js.snap, tests/destructuring_ignore/ignore.js, tests/destructuring_ignore/jsfmt.spec.js, tests/object_property_ignore/__snapshots__/jsfmt.spec.js.snap, tests/object_property_ignore/ignore.js
=> Add `ObjectPattern` tests for #8111

changelog_unreleased/less/pr-8178.md, src/language-css/parser-postcss.js, src/language-css/printer-postcss.js, tests/css_less/__snapshots__/jsfmt.spec.js.snap, tests/css_less/less.less
=> Less: parse `:extend` as selector

cspell.json, package.json, yarn.lock
Fix yarn warning  https://github.com/prettier/prettier/runs/620978815#step:4:11
=> Add missing peer dependency `tslib`

website/playground/Playground.js, website/playground/panels.js, website/playground/util.js
=> playground: auto-fold some AST nodes

changelog_unreleased/graphql/pr-7721.md, src/language-graphql/printer-graphql.js, tests/graphql_bracket_spacing/__snapshots__/jsfmt.spec.js.snap, tests/graphql_directives/__snapshots__/jsfmt.spec.js.snap, tests/graphql_newline/__snapshots__/jsfmt.spec.js.snap, tests/graphql_trailing_comma/__snapshots__/jsfmt.spec.js.snap
=> Improve wrapping of GraphQL fragment directives

tests/lwc/lwc/__snapshots__/jsfmt.spec.js.snap, tests/lwc/lwc/jsfmt.spec.js
=> Remove extra parser option in lwc tests

scripts/build/config.js, tests_integration/__tests__/third-party.js
=> Test bundled `cosmiconfig`

docs/index.md
=> HTTPS link

scripts/build/bundler.js
=> Build: Remove working directory from `parser-typescript.js`

scripts/build/bundler.js, scripts/build/config.js
=> Minify `standalone.js`

docs/configuration.md, docs/ignore.md, docs/options.md, docs/rationale.md
closes #7805 
closes #5571
closes #5121
partially addresses #8094
=> Close simple docs related issues

website/playground/BottomBar.js, website/playground/EditorState.js, website/playground/Playground.js, website/playground/PrettierFormat.js, website/playground/VersionLink.js, website/playground/buttons.js, website/playground/index.js, website/playground/panels.js, website/playground/sidebar/SidebarOptions.js, website/playground/sidebar/components.js, website/playground/sidebar/inputs.js, website/playground/sidebar/options.js
see https://twitter.com/sebmarkbage/status/1250284377138802689
=> Playground: fix how React is imported

website/playground/util.js
=> Playground: autofold for Markdown and other languages

changelog_unreleased/vue/pr-8326.md, src/language-html/parser-html.js, tests/misc/errors/vue/__snapshots__/jsfmt.spec.js.snap, tests/misc/errors/vue/upper-case.html, tests/vue/html-vue/__snapshots__/jsfmt.spec.js.snap, tests/vue/html-vue/elastic-header.html, tests/vue/html-vue/hello-world.html, tests/vue/html-vue/upper-case-2.html
Alternative #8281, after #8153 
=> Vue: Support Vue DOM template formatting

tests/scss/scss/__snapshots__/jsfmt.spec.js.snap, tests/scss/scss/scss.scss
It should be a mixin
https://github.com/prettier/prettier/pull/4490/files#diff-c1e4c9b5b4a1d2b704fc42cc31cd6764R982
=> Fix invalid scss test

changelog_unreleased/yaml/pr-8355.md, src/language-yaml/printer-yaml.js, tests_config/run_spec.js
=> Fix unstable yaml print

changelog_unreleased/html/pr-8371.md, src/language-html/utils.js, tests/html/script/__snapshots__/jsfmt.spec.js.snap, tests/html/script/script.html
ref: https://github.com/prettier/prettier/issues/8344#issuecomment-630674307
=> HTML: Support `<script type="text/html">`

changelog_unreleased/javascript/pr-8376.md, docs/options.md, src/language-js/pragma.js, tests/misc/insert-pragma/js/__snapshots__/jsfmt.spec.js.snap, tests/misc/insert-pragma/js/shebang-with-pragma.js, tests/misc/insert-pragma/js/shebang-without-pragma.js, tests/misc/require-pragma/js/__snapshots__/jsfmt.spec.js.snap, tests/misc/require-pragma/js/shebang-with-pragma.js, tests/misc/require-pragma/js/shebang-without-pragma.js
=> JS: `pragma` support files with shebang

.github/ISSUE_TEMPLATE/integration.md
We don't need keep them up to date, but they are too old.
=> Bump issue template runtime versions

changelog_unreleased/flow/pr-8365.md, src/language-js/needs-parens.js, tests/flow/function-type-param/__snapshots__/jsfmt.spec.js.snap, tests/flow/function-type-param/issue-5283.js, tests/flow/function-type-param/jsfmt.spec.js
=> Flow: fix function type param

changelog_unreleased/handlebars/pr-8375.md, src/language-handlebars/printer-glimmer.js, tests/handlebars/block-statement/__snapshots__/jsfmt.spec.js.snap, tests/handlebars/concat-statement/__snapshots__/jsfmt.spec.js.snap, tests/handlebars/mustache-statement/__snapshots__/jsfmt.spec.js.snap
This would close https://github.com/prettier/prettier/issues/8374
=> Respect singleQuote option around attribute value more complex than a bare text

src/main/core.js, src/main/range-util.js
=> refactor(range): minor cleanup

.github/workflows/prod-test.yml
We've released v2. That includes a lot of improvements.
https://github.com/actions/cache/releases
https://github.com/actions/upload-artifact/releases
https://github.com/actions/download-artifact/releases
---
=> CI: Update production test settings

tests/css/inline-url/__snapshots__/jsfmt.spec.js.snap, tests/css/inline-url/inline_url.css
The issue #5692 trying to solve is already fixed by #7592, add some tests from that one, and close it.
=> Add tests from pr-5692

src/document/doc-utils.js
=> Minor refactor `doc-utils`

tests/typescript/optional-method/__snapshots__/jsfmt.spec.js.snap, tests/typescript/optional-method/jsfmt.spec.js, tests/typescript/optional-method/optional-method.ts
=> Add tests for issue 6678

commands.md
=> Document: Fix h4 => h3 for `dedentToRoot` in commands.md

src/language-js/printer-estree.js, tests/js/directives/jsfmt.spec.js
Fixes #2081 , this issue is quite a edge case, don't think it needs a changelog
=> Remove extra line after directive with comment

changelog_unreleased/javascript/pr-8557.md, src/language-js/comments.js, tests/typescript/conditional-types/__snapshots__/jsfmt.spec.js.snap, tests/typescript/conditional-types/comments.ts
=> TypeScript: Prefer leading comment when there is a comment on after "?" in conditional types

.github/dependabot.yml
Ref: https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/
Syntax: https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#about-the-dependabotyml-file
Adding this file will enable [this page](https://github.com/prettier/prettier/network/updates)
=> Migrate to native dependabot

docs/rationale.md
=> Add a disclaimer about non-standard syntax

website/package.json, website/yarn.lock
=> website: remove dependencies shared with root package.json

scripts/build/bundler.js, src/common/internal-plugins.js
=> Build: Auto set parsers as external

package.json
@lydell We can't update this script yet. See https://github.com/prettier/prettier/issues/8114 , Sorry that I missed this in #8510
=> Temporary fix for prettier lint script

.eslintrc.yml, src/common/parser-include-shebang.js, src/language-js/clean.js, src/language-js/loc.js, src/language-js/parser-typescript.js, src/language-js/postprocess.js
They all wrote for other languages.
https://github.com/czosel/prettier/blame/830b22b5d32360e5dde28eacb949789536b2c4d3/src/common/util.js#L262
&
https://github.com/czosel/prettier/blame/830b22b5d32360e5dde28eacb949789536b2c4d3/src/common/util.js#L274
=> JS: Cleanup `loc.js`

src/language-handlebars/parser-glimmer.js, src/language-handlebars/postprocess.js, src/language-handlebars/printer-glimmer.js
#8634 Increased bundle size ~500k, change `preprocess` to `postprocess` to fix it. 
Ref https://github.com/prettier/prettier/pull/8634#issuecomment-649952364
=> Change handlebars `preprocess` to `postprocess`

src/main/comments.js, yarn.lock
=> Generate fresh `yarn.lock`

src/common/util.js, src/language-js/needs-parens.js, src/language-js/printer-estree.js, src/language-js/utils.js
=> Move js-only utils to `language-js` dir

tsconfig.json
Avoid to run tsc for local `test.ts` file
=> tsc ignore `test*.*`

src/language-js/utils.js
=> Refactor: `getLeftMost` use while loop instead of recurse

src/language-js/print/ternary.js
=> Refactor: Use FastPath type def in JSDoc type comments

tests/handlebars/block-statement/__snapshots__/jsfmt.spec.js.snap, tests/handlebars/block-statement/if-else.hbs
This PR adds a test to confirm https://github.com/prettier/prettier/issues/8693 is fixed on master. fixes #8693
It was fixed in https://github.com/prettier/prettier/pull/7967.
=> Add a test to confirm issue #8693 is fixed

changelog_unreleased/javascript/pr-8742.md, src/language-js/printer-estree.js, tests/js/ignore/__snapshots__/jsfmt.spec.js.snap, tests/js/ignore/ignore-2.js, tests/js/ignore/jsfmt.spec.js
=> Fix duplicated comments

src/language-js/postprocess.js, src/language-js/printer-estree.js, src/main/comments.js
=> Use `locStart`/`locEnd`  instead of start/end

scripts/build-docs.js, website/static/service-worker.js, website/static/worker.js
=> Auto generate parsers for playground

src/common/util.js, src/language-css/printer-postcss.js, src/language-js/print/call-arguments.js, src/language-js/print/ternary.js, src/language-js/printer-estree.js, src/language-js/utils.js, src/main/options.js
=> Minor refactor

jest.config.js, tests/vue/with-plugins/jsfmt.spec.js, tests_config/require_standalone.js
=> Test: fix standalone tests with `plugins` option

tests_config/require_standalone.js
=> Auto include `parser-*.js` in standalone test

scripts/build/babel-plugins/transform-custom-require.js, src/common/resolve.js
=> Build: Simplify `transform-custom-require` plugin

src/language-js/loc.js, src/language-js/parser-babel.js, src/language-js/postprocess.js, src/language-js/printer-estree-json.js
=> Simplify `composeLoc`

changelog_unreleased/api/pr-7875.md, src/language-markdown/printer-markdown.js, tests/misc/embedded_language_formatting/mdx/__snapshots__/jsfmt.spec.js.snap, tests/misc/embedded_language_formatting/mdx/import-export.mdx, tests/misc/embedded_language_formatting/mdx/jsfmt.spec.js, tests/misc/embedded_language_formatting/mdx/jsx.mdx
=> MDX: fix unstable format when embedded off

docs/related-projects.md
=> [docs] Add spotless integrations (maven and gradle)

docs/options.md, website/versioned_docs/version-stable/options.md
Swaps link that results in 404
fixes #8781 
=> Docs: Fix links

tests/markdown/list/__snapshots__/jsfmt.spec.js.snap, tests/markdown/list/nested-tab.md
Close #3223 
I was looking for a issue fixed by updating remark parser but I could not find, so we can probably check `go through all the open Markdown-related issues to check whether this PR fixed them and add tests` on #8630 after this PR is merged.
If you know a issue fixed by updating remark parser, please add to #8630 
=> Markdown: Add tests for #3223

scripts/release/steps/update-dependents-count.js, website/pages/en/index.js
=> Fix `update-dependents-count` script

netlify.toml
=> Update `yarn` version for netlify build

package.json, yarn.lock
=> Add `fix` & `lint` scripts

tests_config/prettier-plugins/prettier-plugin-uppercase-rocks/main.js, tests_integration/__tests__/__snapshots__/patterns-dirs.js.snap, tests_integration/__tests__/patterns-dirs.js, tests_integration/cli/dirs/plugins/javascript.js, tests_integration/cli/dirs/plugins/plugin.uppercase-rocks, tests_integration/env.js
=> Add test to confirm `prettier .` work with plugins

src/common/util.js, website/.eslintrc.yml, website/static/install-service-worker.js, website/static/landing.js, website/static/service-worker.js, website/static/worker.js
=> Update ESLint settings

src/document/doc-printer.js
=> Rewrite a deep nested ternary `makeAlign`

changelog_unreleased/cli/pr-8934.md, src/main/options-normalizer.js, tests_integration/__tests__/__snapshots__/arg-parsing.js.snap, tests_integration/__tests__/arg-parsing.js
=> CLI: Don't suggest `-_` for unknown flags

tests_integration/cli/config/rc-cjs/prettier-config-cjs-in-type-commonjs/package.json, tests_integration/cli/config/rc-cjs/prettier-config-cjs-in-type-module/package.json, tests_integration/cli/config/rc-cjs/prettier-config-cjs-in-type-none/package.json, tests_integration/cli/config/rc-cjs/prettierrc-cjs-in-type-commonjs/package.json, tests_integration/cli/config/rc-cjs/prettierrc-cjs-in-type-module/package.json, tests_integration/cli/config/rc-cjs/prettierrc-cjs-in-type-none/package.json
To kill this warning https://github.com/prettier/prettier/runs/970067437#step:7:10
=> Fix `name` field in `tests_integration/**/package.json`

src/common/create-ignorer.js
=> cleanup param types in src/common/create-ignorer.js

src/common/util.js
=> Simplify `getPenultimate`

package.json, scripts/build/build.js
It seems we don't need it anymore.
=> Build: remove `--max-old-space-size`

src/language-js/printer-estree.js, tests/typescript/class/__snapshots__/jsfmt.spec.js.snap, tests/typescript/class/extends_implements.ts
=> Fix class implements with long type parameters

src/language-js/clean.js, tests_config/run_spec.js
Fixes https://github.com/prettier/prettier/issues/8960
=> Run AST_COMPARE test for verifyParsers too

.github/workflows/dev-package-test.yml, .github/workflows/dev-test.yml, .github/workflows/prod-test.yml
=> CI: add `timeout-minutes: 60`

src/language-js/pragma.js, tests/misc/insert-pragma/js/__snapshots__/jsfmt.spec.js.snap, tests/misc/insert-pragma/js/shebang-only-with-pragma.js, tests/misc/insert-pragma/js/shebang-only-without-pragma.js
=> JS: DRY `hasPragma` & `insertPragma`

.pre-commit-hooks.yaml, changelog_unreleased/cli/pr-8829.md, docs/cli.md, docs/install.md, docs/precommit.md, docs/watching-files.md, src/cli/constant.js, src/cli/util.js, tests_integration/__tests__/__snapshots__/early-exit.js.snap, tests_integration/__tests__/__snapshots__/help-options.js.snap, tests_integration/__tests__/__snapshots__/ignore-unknown.js.snap, tests_integration/__tests__/ignore-unknown.js, tests_integration/cli/ignore-unknown/.prettierignore, tests_integration/cli/ignore-unknown/.prettierrc, tests_integration/cli/ignore-unknown/javascript.js, tests_integration/cli/ignore-unknown/override.as-js-file, tests_integration/cli/ignore-unknown/unkown-file-extension.unknown, tests_integration/cli/ignore-unknown/unkown-filename
=>  CLI: Add `--ignore-unknown`

src/common/end-of-line.js, src/language-js/pragma.js, src/main/core.js
=> Minor tweak

package.json
=> Chore: Update `lint:prettier` script

jest.config.js, tests_config/run_spec.js, tests_config/setup.js
When running `integration` test, usually we don't need this global `run_spec`.
=> Turn test setup file to lazy load

changelog_unreleased/javascript/pr-9078.md, src/language-css/printer-postcss.js, src/language-css/utils.js, tests/js/multiparser-css/__snapshots__/jsfmt.spec.js.snap, tests/js/multiparser-css/issue-9072.js
=> Respect spacing between template values in embedded css

src/language-handlebars/printer-glimmer.js
=> Glimmer: Use common `locationToOffset`

.gitignore
I'm working on yarn@2 support, there are lots of untracked files when switching branches.
=> Add Yarn 2 files to .gitignore

tests/js/multiparser-css/__snapshots__/jsfmt.spec.js.snap, tests/js/multiparser-css/issue-5961.js
=> Test: add test for issue 5961

src/language-yaml/printer-yaml.js
=> Refactor: Use set instead of array

scripts/release/steps/update-dependents-count.js
I did this manually when I ran the release script before, but I think it useful to be able to do it automatically.
=> Release script: Commit and push after updating dependents count

website/pages/en/index.js, website/pages/en/users/index.js
Context: https://github.com/prettier/prettier/pull/9156#issuecomment-688266854
=> Website: Remove `add users` link

changelog_unreleased/mdx/pr-9267.md, src/language-markdown/printer-markdown.js, tests/mdx/embedded-language-formatting/__snapshots__/jsfmt.spec.js.snap, tests/mdx/embedded-language-formatting/issue-9260.mdx, tests/mdx/embedded-language-formatting/jsfmt.spec.js, tests/misc/embedded_language_formatting/mdx/__snapshots__/jsfmt.spec.js.snap
=> MDX: fix JSX format

.github/workflows/prod-test.yml, jest.config.js
"Size check" is not reportting correct size for files, we'll have to ignore `esm/*`
https://github.com/prettier/prettier/pull/9283#issuecomment-699776244
=> Disable Jest verbose, remove pattern for size check job

src/language-js/comments.js
=> Refactor: Remove duplicated condition

changelog_unreleased/typescript/pr-9318.md, src/language-js/printer-estree.js, tests/typescript/interface/__snapshots__/jsfmt.spec.js.snap, tests/typescript/interface/ignore.ts
=> TypeScript: Preserve a last separator for ignored object and interface types

changelog_unreleased/typescript/pr-9318.md
=> Add missing prettier-ignore comment in changelog

.github/workflows/dev-test.yml
https://github.com/prettier/prettier/pull/9332#issuecomment-704180053
=> Use `Jest@26`

changelog_unreleased/less/pr-9356.md, src/language-css/loc.js, src/language-css/parser-postcss.js, tests/less/comments/__snapshots__/jsfmt.spec.js.snap, tests/less/comments/value-lists.less
=> LESS: fix comments in value lists

tests/typescript/class/jsfmt.spec.js, tests/typescript/compiler/jsfmt.spec.js, tests/typescript/conformance/classes/classDeclarations/classAbstractKeyword/jsfmt.spec.js, tests/typescript/conformance/classes/constructorDeclarations/constructorParameters/jsfmt.spec.js, tests/typescript/conformance/parser/ecmascript5/Statements/jsfmt.spec.js, tests/typescript/conformance/types/abstractKeyword/jsfmt.spec.js, tests/typescript/conformance/types/decorator/jsfmt.spec.js, tests/typescript/conformance/types/functions/jsfmt.spec.js, tests/typescript/custom/abstract/jsfmt.spec.js, tests/typescript/decorators/jsfmt.spec.js, tests/typescript/error-recovery/jsfmt.spec.js, tests/typescript/interface/jsfmt.spec.js, tests/typescript/keywords/jsfmt.spec.js, tests_config/run_spec.js, tests_config/utils/compose-options-for-snapshot.js, tests_config/utils/stringify-options-for-title.js
=> Test: use `errors` options instead of `disableBabelTS` 

docs/plugins.md
=> Moved hack plugins to experimental section

.git-blame-ignore-revs, scripts/release/steps/bump-prettier.js
Inspired by https://github.com/babel/babel/pull/12063
=> Add `.git-blame-ignore-revs`

changelog_unreleased/typescript/pr-9484.md, src/language-js/needs-parens.js, tests/js/objects/assignment-expression/__snapshots__/jsfmt.spec.js.snap, tests/js/objects/assignment-expression/jsfmt.spec.js, tests/js/objects/assignment-expression/object-property.js, tests/js/objects/assignment-expression/object-value.js
=> Add parens to object value that it's an assignment

.github/workflows/dev-test.yml, .github/workflows/prod-test.yml
=> Run tests on `Node.js` 15

src/language-js/utils.js, tests/typescript/typeparams/consistent/__snapshots__/jsfmt.spec.js.snap, tests/typescript/typeparams/consistent/flow-only.ts
=> Refactor: Improve readability

jest.config.js, src/language-js/needs-parens.js
=> Refactor `needs-parens.js` (part 2)

changelog_unreleased/flow/pr-9543.md, src/language-js/utils.js, tests/typescript/typeparams/consistent/__snapshots__/jsfmt.spec.js.snap, tests/typescript/typeparams/consistent/simple-types.ts, tests/typescript/typeparams/consistent/typescript-only.ts
=> Treat more types as simple type

src/common/util.js
=> Remove dead code

src/common/util.js, src/language-html/parser-html.js, src/language-html/utils.js, src/language-markdown/embed.js
=> Refactor: `getParserName` -> `inferParserByLanguage`

changelog_unreleased/api/pr-8983.md, changelog_unreleased/javascript/pr-9000.md, changelog_unreleased/typescript/pr-9473.md
Preparing for the 2.2 release blog. Are there any other changes that should be highlighted?
=> Add HIGHLIGHT mark to CHANGELOG

src/language-css/clean.js, src/language-graphql/printer-graphql.js, src/language-handlebars/clean.js, src/language-html/clean.js, src/language-js/printer-estree-json.js, src/language-markdown/clean.js, src/language-markdown/printer-markdown.js
=> Refactor: Use `ignoredProperties` for all languages

.eslintrc.yml, scripts/tools/eslint-plugin-prettier-internal-rules/directly-loc-start-end.js, src/language-css/loc.js, src/language-css/parser-postcss.js, src/language-css/printer-postcss.js, src/language-css/utils.js
=> Enable `directly-loc-start-end` in `language-css`

src/language-js/print/call-arguments.js, src/language-js/print/function-parameters.js, src/language-js/printer-estree.js
=> Refactor: Extract `printFunctionParameters`

src/language-js/printer-estree.js, src/language-js/utils.js, tests/flow-repo/def_site_variance/__snapshots__/jsfmt.spec.js.snap, tests/flow-repo/def_site_variance/jsfmt.spec.js, tests/flow/variance/__snapshots__/jsfmt.spec.js.snap, tests/flow/variance/jsfmt.spec.js
Flow aligned this with babel https://github.com/facebook/flow/commit/3742cef6cebb0976108dd0e131e332672f5a8e4d
=> Simplify flow `Variance` node print

src/language-js/printer-estree.js, src/language-js/utils.js
Make related part little safer for other parsers.
=> Add parser check to flow-comment related checks

.eslintrc.yml, src/language-graphql/loc.js, src/language-graphql/parser-graphql.js, src/language-graphql/printer-graphql.js, src/language-html/loc.js, src/language-html/parser-html.js, src/language-html/printer-html.js, src/language-markdown/loc.js, src/language-markdown/parser-markdown.js, src/language-markdown/printer-markdown.js, src/language-markdown/utils.js, src/language-yaml/loc.js, src/language-yaml/parser-yaml.js, src/language-yaml/printer-yaml.js
=> Enable `directly-loc-start-end` for all languages

src/language-js/print/template-literal.js, src/language-js/printer-estree.js
Prepare for [`TSTemplateLiteralType`](https://github.com/prettier/prettier/pull/9636/files#diff-2d1bdf87289eb31aa17e4e2b93c673bbe5eded98d2ce133024672f40bbd63f1aR175)
=> Extract `printTemplateLiteral`

changelog_unreleased/markdown/pr-9654.md, src/language-markdown/printer-markdown.js, tests/markdown/table/empty-table/__snapshots__/jsfmt.spec.js.snap, tests/markdown/table/empty-table/empty-table.md, tests/markdown/table/empty-table/jsfmt.spec.js
=> Markdown: Fix extra empty line added after empty table

changelog_unreleased/javascript/pr-9670.md, src/language-js/printer-estree.js, tests/js/call/no-argument/__snapshots__/jsfmt.spec.js.snap, tests/js/call/no-argument/import.js, tests/js/call/no-argument/jsfmt.spec.js, tests/js/call/no-argument/special-cases.js
=> Fix comments in `require()` with no argument

src/language-js/embed.js, src/language-js/embed/css.js, src/language-js/embed/graphql.js, src/language-js/embed/html.js, src/language-js/embed/markdown.js, src/language-js/print/template-literal.js, src/language-js/printer-estree.js, src/language-js/utils.js
=> JS: Refactor embed

scripts/draft-blog-post.js
=> Reuse `dirPath` variable in `./scripts/draft-blog-post.js`

changelog_unreleased/yaml/pr-9669.md, src/language-yaml/printer-yaml.js, tests/yaml/comment/__snapshots__/jsfmt.spec.js.snap, tests/yaml/comment/flow-sequence-mapping.yml
=> YAML: Fix comments in `flowMapping` and `flowSequence`

src/main/comments.js
=> Refactor: Improve location compare

website/blog/2020-08-24-2.1.0.md
=> Fix link to GitHub profile

src/language-js/parse-postprocess.js, src/language-js/types/estree.d.ts
=> Remove unused parenStart

src/language-js/print/module.js, src/language-js/printer-estree.js, tests/js/comments/__snapshots__/jsfmt.spec.js.snap
=> Refactor: Module releated format

src/language-js/print/array.js, src/language-js/print/object.js, src/language-js/print/type-annotation.js, src/language-js/printer-estree.js
=> Extract array and object print

src/language-js/comments.js, src/language-js/print/jsx.js, src/language-js/printer-estree.js
=> Extract JSX related print functions

src/language-js/print/assignment.js, src/language-js/print/binaryish.js, src/language-js/print/comment.js, src/language-js/print/misc.js, src/language-js/printer-estree.js
=> Extract `printAssignment`, `printBinaryishExpression`, and `printComment`

src/language-js/print/block.js, src/language-js/print/member-chain.js, src/language-js/print/member.js, src/language-js/print/misc.js, src/language-js/print/statement.js, src/language-js/printer-estree.js
=> Extract `printStatementSequence`, `printMemberExpression`, and `printBlock`

package.json, yarn.lock
[TypeScript 4.1 has been released!](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/)
Fixes #9234 
Context: https://github.com/prettier/prettier/pull/9636#issuecomment-729319369
=> Update to TypeScript 4.1.2

src/language-js/print/class.js, src/language-js/print/flow.js, src/language-js/print/misc.js, src/language-js/printer-estree.js
=> Refactor class related functions

src/language-js/print/property.js, src/language-js/printer-estree.js
=> Extract `printProperty`

src/language-js/print/function.js, src/language-js/printer-estree.js
=> Refactor function related functions

src/language-js/print/ternary.js, src/language-js/printer-estree.js
Move all logic into `printTernary`
=> Refactor `ConditionalExpression` and `TSConditionalType` print

src/language-js/print/flow.js, src/language-js/print/interface.js, src/language-js/print/misc.js, src/language-js/print/module.js, src/language-js/print/type-annotation.js, src/language-js/printer-estree.js
=> Move `Declare*` node to `print/flow.js`

src/language-js/print/typescript.js, src/language-js/printer-estree.js
=> Move some "TS*" node to `print/typescript.js`

src/language-js/print/array.js, src/language-js/print/class.js, src/language-js/print/flow.js, src/language-js/print/function.js, src/language-js/print/misc.js, src/language-js/print/object.js, src/language-js/print/type-annotation.js, src/language-js/print/typescript.js, src/language-js/printer-estree.js
=> Extract some type annotation to `flow.js` and `typescript.js`

src/language-js/clean.js
Introduced by #9748, didn't notice there is a test failure.
=> Test: Fix AST_COMPARE test

src/main/comments.js
=> Rename a variable

src/document/doc-printer.js
It's faster
```js
string = '+'.repeat(5e3)+'\n'.repeat(5e3)
console.time('check and replace')
for (let i = 0; i < 1e3; i++)
if (string.includes('\n')) string.replace(/\n/g, '')
console.timeEnd('check and replace')
console.time('replace')
for (let i = 0; i < 1e3; i++)
string.replace(/\n/g, '')
console.timeEnd('replace')
VM354:5 check and replace: 556.920166015625 ms
VM354:9 replace: 493.8759765625 ms
```
```js
string = '\n'.repeat(1e4)
console.time('check and replace')
for (let i = 0; i < 1e3; i++)
if (string.includes('\n')) string.replace(/\n/g, '')
console.timeEnd('check and replace')
console.time('replace')
for (let i = 0; i < 1e3; i++)
string.replace(/\n/g, '')
console.timeEnd('replace')
VM364:5 check and replace: 1082.6298828125 ms
VM364:9 replace: 972.475830078125 ms
```
**✨[Try the …
=> `printDocToString`: Don't check existance before replacing newLine

commands.md
=> Add a link to the "Example" part

src/main/comments.js
=> Refactor: Stop mutating AST during `getSortedChildNodes`

cspell.json, website/blog/2020-12-11-plugin-ruby-1.0.md
=> Correct name for Ruby blog post

docs/options.md, website/versioned_docs/version-stable/options.md
- Add a link to MDN
- Fix link to babel website
Fixes #9855
=> Fix link to babel website

docs/browser.md, website/versioned_docs/version-stable/browser.md
- Add `<script>` tag
- Add version to esm example, consistent with others
=> doc: improve examples in browser

changelog_unreleased/javascript/9866.md, src/language-js/print/jsx.js, src/language-js/utils.js, tests/jsx/whitespace/jsfmt.spec.js
=> Fix unstable JSX formatting with U+3000

src/language-js/print/block.js, src/language-js/print/class.js, src/language-js/print/statement.js, src/language-js/printer-estree.js
=> Refactor: Extract `printBody`

scripts/build/build.js
=> Fix params mistaking at #9900

src/language-js/print/call-arguments.js, src/language-js/print/member-chain.js, src/language-js/printer-estree.js, src/main/ast-to-doc.js
=> Fix `comments.js` import style

src/language-js/print/statement.js, src/language-js/utils.js
=> Move `isLastStatement` to `print/statement.js`

.eslintrc.yml, src/language-css/utils.js, src/language-html/print-preprocess.js, src/language-js/embed/css.js, src/language-js/print/type-parameters.js, src/language-js/printer-estree.js, src/language-markdown/mdx.js, src/language-markdown/printer-markdown.js, src/language-markdown/utils.js, src/main/options-normalizer.js, tests_integration/__tests__/config-resolution.js, website/pages/en/index.js, website/pages/en/users/index.js, website/playground/markdown.js
Suggested by @sosukesuzuki https://github.com/prettier/prettier/pull/9916#pullrequestreview-554264674
=> Enable `arrow-body-style` rule

.eslintrc.yml, scripts/tools/eslint-plugin-prettier-internal-rules/index.js, scripts/tools/eslint-plugin-prettier-internal-rules/prefer-is-non-empty-array.js, src/common/util.js, src/language-css/printer-postcss.js, src/language-css/utils.js, src/language-graphql/printer-graphql.js, src/language-html/ast.js, src/language-html/printer-html.js, src/language-js/comments.js, src/language-js/embed/css.js, src/language-js/loc.js, src/language-js/print/assignment.js, src/language-js/print/block.js, src/language-js/print/class.js, src/language-js/print/interface.js, src/language-js/print/misc.js, src/language-js/print/module.js, src/language-js/printer-estree.js, src/language-js/utils.js, src/language-markdown/printer-markdown.js, src/language-yaml/utils.js, src/main/comments.js
Add `isNonEmptyArray` and enforce to use it.
=> Add `isNonEmptyArray`

.eslintrc.yml, scripts/release/steps/update-dependents-count.js, src/document/doc-builders.js, src/document/doc-debug.js, src/document/doc-printer.js, src/language-css/clean.js, src/language-html/utils.js, src/language-js/print/template-literal.js, src/language-yaml/utils.js, src/main/core-options.js, src/main/core.js, tests/html/comments/jsfmt.spec.js, tests/html/tags/jsfmt.spec.js, tests_config/utils/create-snapshot.js, tests_config/utils/stringify-options-for-title.js, tests_config/utils/visualize-range.js, website/playground/Playground.js, website/playground/sidebar/inputs.js
=> Enable `unicorn/prefer-number-properties`

.github/workflows/eslint-rules.yml, .gitignore, scripts/tools/eslint-plugin-prettier-internal-rules/better-parent-property-check-in-needs-parens.js, scripts/tools/eslint-plugin-prettier-internal-rules/no-node-comments.js, scripts/tools/eslint-plugin-prettier-internal-rules/package.json, scripts/tools/eslint-plugin-prettier-internal-rules/test.js
Log https://github.com/prettier/prettier/pull/9929/checks?check_run_id=1574646327#step:4:12
=> Test internal eslint rules

tests/misc/errors/invalid-typescript-decorators/__snapshots__/jsfmt.spec.js.snap, tests/misc/errors/invalid-typescript-decorators/issue-9102.ts
Add test for #9102 to close it, it's fixed by #9636
Closes #9102 
=> Add test to close issue 9102

src/cli/context.js, src/cli/core.js, src/cli/index.js, src/cli/option.js
Doesn't touch logics. Just refactor to class.
=> Refactor CLI context with ES2015 class

.eslintrc.yml, src/document/doc-printer.js, src/language-markdown/mdx.js, src/language-markdown/parser-markdown.js, website/playground/VersionLink.js, website/static/landing.js
=> Enable `unicorn/prefer-regexp-test`

website/playground/markdown.js
=> Add meriyah to getMarkdownSyntax for Playground Markdown

tests/html/whitespace/__snapshots__/jsfmt.spec.js.snap, tests/html/whitespace/nested-inline-without-whitespace.html
=> Add a test for HTML formatting

docs/options.md
https://github.com/prettier/prettier/pull/9885 added the support for --htmlWhitespaceSensitivity=strict option for Handlebars.
This PR documents the change.
Will close https://github.com/prettier/prettier/issues/9881
=> Document --htmlWhitespaceSensitivity option for Handlebars

package.json, yarn.lock
I want enable some useful new rules like [`no-array-for-each`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/no-array-for-each.md)
[Release note](https://github.com/sindresorhus/eslint-plugin-unicorn/releases/tag/v27.0.0)
=> Update `eslint-plugin-unicorn` to v27

.eslintrc.yml, scripts/draft-blog-post.js, src/document/doc-printer.js, src/language-graphql/printer-graphql.js, src/language-js/print/array.js, src/language-js/print/class.js, src/language-js/print/jsx.js, src/language-js/print/module.js, src/language-js/print/type-parameters.js, src/language-js/print/typescript.js, src/language-js/printer-estree.js
=> Enable `unicorn/no-array-push-push`

changelog_unreleased/handlebars/9885.md
Let's add a changelog entry for #9885. Related issue: https://github.com/prettier/prettier/issues/9881.
=> Add changelog entry for #9885

src/cli/expand-patterns.js, src/cli/option.js, src/cli/usage.js, src/language-html/ast.js, src/language-html/utils.js, src/language-js/utils.js, src/main/comments.js, src/main/massage-ast.js, src/main/options.js
=> Use `Object.{entries,values}` if possible

docs/options.md, website/versioned_docs/version-stable/options.md
=> Document that Prettier never unquotes numeric properties in TS and Flow

src/utils/front-matter.js
I'm not sure if I made this harder to read.
=> Simplify frontMatter parse

.eslintrc.yml, cspell.json, src/common/util.js, src/document/doc-builders.js, src/language-markdown/printer-markdown.js, src/language-markdown/utils.js, src/main/core.js, src/main/options.js, src/main/parser.js, tests_config/utils/create-snapshot.js, tests_integration/runPrettier.js
=> Use default parameters where possible and other microrefactoring

docs/related-projects.md, website/versioned_docs/version-stable/related-projects.md
see https://github.com/microsoft/parallel-prettier
=> Add parallel-prettier to "Related Projects"

src/language-js/clean.js
=> JS: Simplify `clean` function

changelog_unreleased/javascript/10158.md, src/language-js/print/assignment.js, tests/js/assignment/__snapshots__/jsfmt.spec.js.snap, tests/js/assignment/unary.js
=> Break assignment whose rhs is wrapped by an unary expression

changelog_unreleased/javascript/10106.md, src/language-js/print/array.js, tests/js/arrays/__snapshots__/jsfmt.spec.js.snap, tests/js/arrays/issue-10159.js
=> Fix regression after pr-10106

.eslintrc.yml, jest.config.js, src/cli/format.js, src/config/resolve-config.js, src/document/doc-builders.js, src/language-css/utils.js, src/language-graphql/printer-graphql.js, src/language-js/embed/html.js, src/language-js/needs-parens.js, src/language-js/print/class.js, src/language-js/print/jsx.js, src/language-js/printer-estree.js, src/language-js/utils.js, src/language-markdown/printer-markdown.js, src/main/multiparser.js, tests_integration/runPrettier.js
Enable [`no-implicit-coercion`](https://eslint.org/docs/rules/no-implicit-coercion) rule.
=> Enable `no-implicit-coercion` rule

commands.md
* added some important unobvious details
* minor edits
BTW, isn't it time to move this info to https://prettier.io/docs/en/technical-details.html?
=> docs: revise commands.md

.github/workflows/mark-issue-duplicate.yml
Optimized API request times.
The comment body will be judged internally, so the `if` will not added to the action.
=> CI: Fix `Mark Issue Duplicate` job

.github/workflows/dev-test.yml
=> CI: Fix coverage report

tests/js/last-argument-expansion/__snapshots__/jsfmt.spec.js.snap, tests/js/last-argument-expansion/function-expression-issue-2239.js
=> Add tests for #2239

jest.config.js, scripts/install-prettier.js, tests_config/require_prettier.js, tests_config/setup.js, tests_integration/env.js
standalone test eval from code, no need install, just read file from `dist/`
=> Test: Skip install for standalone test

src/document/doc-utils.js, src/language-js/print/jsx.js, src/language-js/printer-estree.js
This function is silly... it check if `n === ""`
=> Remove `isEmpty`

src/language-js/print/ternary.js
There is no need to recurse, and we can return earlier.
=> Refactor `conditionalExpressionChainContainsJsx`

.eslintrc.yml, src/document/doc-debug.js, src/document/doc-utils.js, src/language-js/comments.js, src/language-js/needs-parens.js, src/language-js/utils.js, src/language-yaml/printer-yaml.js
=> Style: Disallow else if in `no-else-return`

.github/dependabot.yml
=> chore: Check for updates every Sunday

changelog_unreleased/typescript/10341.md, src/language-js/print/typescript.js, tests/typescript/as/__snapshots__/jsfmt.spec.js.snap, tests/typescript/as/nested-await-and-as.ts
=> Indent type assertions in heads of call and member expressions

.eslintrc.yml, src/document/doc-debug.js, src/language-html/parser-html.js, src/language-js/print/type-parameters.js, src/language-js/printer-estree.js, src/language-markdown/printer-markdown.js, src/main/options.js, src/main/range-util.js, website/playground/markdown.js
=> Style: Disallow `==`

package.json, yarn.lock
=> Switch `ci-info` to npm version

src/language-handlebars/printer-glimmer.js, src/language-yaml/printer-yaml.js, src/main/ast-to-doc.js
=> Consistent `document` import style

changelog_unreleased/typescript/10390.md, src/language-js/print/typescript.js, tests/typescript/intrinsic/__snapshots__/jsfmt.spec.js.snap, tests/typescript/intrinsic/intrinsic.ts, tests/typescript/intrinsic/jsfmt.spec.js
=> Support TS 4.1 intrinsic keyword

src/language-js/print/literal.js, src/language-js/printer-estree.js
=> Refactor(JS): Extract `printLiteral`

.github/workflows/support.yml
It'll close issues marked `type:question` and suggest using Stack Overflow instead.
See https://github.com/dessant/support-requests
=> Add Support Requests action config file

docs/ignore.md
Doc changes inspired by [this question](https://stackoverflow.com/q/66299219/76173) on SO.
=> docs: how to ignore files using negative patterns

src/language-js/parser/json.js, tests/misc/errors/json/__snapshots__/jsfmt.spec.js.snap, tests/misc/errors/json/jsfmt.spec.js, tests/misc/errors/json/json-stringify/__snapshots__/jsfmt.spec.js.snap, tests/misc/errors/json/json-stringify/jsfmt.spec.js
=> JSON: Better error message

src/language-js/parser-babel.js
Use `optionsCombinations` instead of `pluginCombinations`, makes logic easier to understand.
=> Simplify babel parser

changelog_unreleased/typescript/10418.md, package.json, tests/misc/typescript-babel-only/__snapshots__/jsfmt.spec.js.snap, tests/misc/typescript-babel-only/ts-4.2-abstract-constructor-type.ts, tests/typescript/abstract-construct-types/__snapshots__/jsfmt.spec.js.snap, tests/typescript/abstract-construct-types/abstract-construct-types.ts, tests/typescript/abstract-construct-types/jsfmt.spec.js, yarn.lock
=> Support TS 4.2 abstract construct types via ts-estree

.eslintrc.yml, scripts/tools/eslint-plugin-prettier-internal-rules/prefer-is-non-empty-array.js
Ref: https://github.com/prettier/prettier/commit/c7e354e38cfd051d3f64b56aeda35e9a0a669de6#r47946398
=> Fix a wrong condition

src/language-css/parser-postcss.js
Attempt to fix build script on `next` branch
=> Fix build script

docs/api.md, website/versioned_docs/version-stable/api.md
=> Clarify prettier.format docs

tests/json/json-superset/jsfmt.spec.js, tests_config/utils/check-parsers.js
=> Test json superset

changelog_unreleased/javascript/10528.md, src/language-js/print/call-expression.js, tests/js/require-amd/__snapshots__/jsfmt.spec.js.snap, tests/js/require-amd/named-amd-module.js, tests/js/require-amd/non-amd-define.js
=> Improve detection of AMD define

docs/browser.md
I believe I've managed to improve the way the information is organized on this page.
=> docs: refine browser.md

docs/plugins.md, website/data/languages.yml
=> Remove stale plugins from home page and docs

scripts/tools/eslint-plugin-prettier-internal-rules/no-identifier-n.js
Fix bad variable name, remove unused schema.
=> Update `no-identifier-n` rule

.eslintrc.yml, scripts/tools/eslint-plugin-prettier-internal-rules/index.js, scripts/tools/eslint-plugin-prettier-internal-rules/no-unnecessary-ast-path-call.js, scripts/tools/eslint-plugin-prettier-internal-rules/test.js, src/language-css/printer-postcss.js, src/language-graphql/printer-graphql.js, src/language-js/print/binaryish.js, src/language-js/print/call-arguments.js, src/language-js/print/function-parameters.js, src/language-js/print/function.js, src/language-js/print/member-chain.js, src/language-js/print/type-annotation.js, src/language-js/printer-estree.js, src/language-markdown/printer-markdown.js
=> Forbid `AstPath.call` without name

changelog_unreleased/handlebars/10290.md, changelog_unreleased/handlebars/x.md, scripts/draft-blog-post.js, src/language-handlebars/index.js, src/main/core-options.js, tests_integration/__tests__/__snapshots__/early-exit.js.snap, tests_integration/__tests__/__snapshots__/help-options.js.snap, tests_integration/__tests__/__snapshots__/plugin-options-string.js.snap, tests_integration/__tests__/__snapshots__/plugin-options.js.snap, tests_integration/__tests__/__snapshots__/schema.js.snap, tests_integration/__tests__/__snapshots__/support-info.js.snap, website/data/languages.yml
🎉
I have added a changelog entry, it is largely stolen from HTML and mardown release blog posts. I need to detail it a bit. Please feel free to modify it or to correct the potential spelling and syntax issues, I'm not an English native speaker.
=> Move Handlebars support out of alpha to release 

website/static/worker.js
Useful for checking Babel's recovered errors.
**✨[Try the playground for this PR](https://deploy-preview-10548--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDTBeTARgG4AdKSKDHfTAJmJABoQIAHGAS3WVGwCd+EAO4AFAQjTIQ2ADbDsATyksARv2xgA1nBgBlNps5QA5shj8ArnBZwAtqrgATJ84Ay2U5ewm4AMQh+O2wYLlNpbEsYCGYQAAsYO1kAdTjOeDRDMDg9SXTOADd0xWkwNBUQYzQ4fhhRDRNg5AAzOWqWACs0AA8AIQ1tXT1sOzg3YzgWtpsQLu69YxNZOABFSwh4Kdl2kEN+av5pVWxHWVi2fmMYZM4nGDjkAA4ABhYLiGrkjTZpC7gDgqTFgAR3W8Hq7CkKGwaAAtFA4M5nLF+HBQZxUfUfE0kK1tjNqnZOOYrATFss1htJrjpiwYCcbncHkg6HSNJxZIsAMIQOw4kD-ACssUs1QAKicoXidgVrABJKCuWB6MCXDgAQUVehgimWW2qAF8DUA)✨**
=> Playground: serialize errors in AST

.github/ISSUE_TEMPLATE/formatting.md, scripts/release/steps/update-version.js
Now people tend to ignore this "tip".
=> issue template: insist on using the Playground

.eslintrc.yml, scripts/tools/eslint-plugin-prettier-internal-rules/consistent-negative-index-access.js, scripts/tools/eslint-plugin-prettier-internal-rules/index.js, scripts/tools/eslint-plugin-prettier-internal-rules/test.js, src/document/doc-printer.js, src/document/doc-utils.js, src/language-css/parser-postcss.js, src/language-css/printer-postcss.js, src/language-handlebars/utils.js, src/language-html/ast.js, src/language-html/parser-html.js, src/language-html/print-preprocess.js, src/language-html/syntax-attribute.js, src/language-js/comments.js, src/language-js/needs-parens.js, src/language-js/print/function.js, src/language-js/print/member-chain.js, src/language-js/print/template-literal.js, src/language-markdown/print-preprocess.js, src/language-markdown/printer-markdown.js, src/main/options-normalizer.js, src/utils/get-last.js
=> Add `consistent-negative-index-access` rule

docs/plugins.md
A more detailed example should be more helpful to newcomers.
=> docs: improve example for printer print function

changelog_unreleased/typescript/10418.md
Modify to mention about type imports in import require declaration(#10546, #10589) in the changelog for TypeScript 4.2 syntax.
=> Fix changelog for support TypeScript 4.2

website/playground/util.js
Fewer things to scroll through when testing/debugging.
=> Playground: autofold more AST properties

.github/dependabot.yml
The default value is `5`, will make weekly update take many rounds to complete.
=> Increase dependabot `open-pull-requests-limit`

docs/precommit.md
This updates installation instructions to match current version of husky and mrm lint-staged.
=> docs(precommit): update husky installation

.github/workflows/dev-package-test.yml
=> Dev package test: lock pnpm to pnpm@5

src/main/comments.js
=> Minor refactoring of `printComments`

changelog_unreleased/javascript/10695.md, src/document/doc-utils.js, tests/js/multiparser-html/__snapshots__/jsfmt.spec.js.snap, tests/js/multiparser-html/issue-10691.js
=> Process conditional groups in mapDoc

docs/install.md
Fixed a few command errors and made one small improvement
=> Fixed Command Errors

.github/workflows/dev-test.yml, .github/workflows/prod-test.yml, netlify.toml
=> Run test on Node.js v16

docs/install.md, website/versioned_docs/version-stable/install.md
=> docs: update git hooks instructions in install.md

.eslintrc.yml, scripts/tools/eslint-plugin-prettier-internal-rules/index.js, scripts/tools/eslint-plugin-prettier-internal-rules/no-conflicting-comment-check-flags.js, scripts/tools/eslint-plugin-prettier-internal-rules/test.js
=> Add `no-conflicting-comment-check-flags` rule

tests/format/flow/indexed-access/__snapshots__/jsfmt.spec.js.snap, tests/format/flow/indexed-access/jsfmt.spec.js, tests/format/flow/optional-indexed-access/__snapshots__/jsfmt.spec.js.snap, tests/format/flow/optional-indexed-access/jsfmt.spec.js
Following up for #10788, #10594
=> Add tests for indexed access via Babel

changelog_unreleased/javascript/10813.md, src/language-js/parser-babel.js, src/language-js/printer-estree.js, tests/format/js/async-do-expressions/__snapshots__/jsfmt.spec.js.snap, tests/format/js/async-do-expressions/async-do-expressions.js, tests/format/js/async-do-expressions/jsfmt.spec.js, tests/format/js/babel-plugins/__snapshots__/jsfmt.spec.js.snap, tests/format/js/babel-plugins/async-do-expressions.js, tests/format/js/babel-plugins/jsfmt.spec.js
Support [async do expression](https://github.com/tc39/proposal-async-do-expressions) proposal that is supported since Babel 7.14.0.
=> Support async do expressions proposal

.github/workflows/dev-test.yml, .github/workflows/prod-test.yml
=> Skip test on Node.js v15

.eslintignore
`test.mjs` should not be linted
=> Fix `.eslintignore`

src/utils/get-file-content-or-null.js
=> Use fsPromise in `getFileContentOrNull`

src/cli/usage.js, src/language-html/print-preprocess.js, src/main/parser.js, src/main/support.js
=> Reduce use of `Array#reduce()`

src/common/util.js
This improves auto completion on editor.
=> Add JSDoc type for isNonEmptyArray

src/language-js/clean.js, src/language-js/comments.js, src/language-js/index.js, src/language-js/parser-babel.js, src/language-js/print/call-arguments.js, src/language-js/print/literal.js, src/language-js/utils.js, src/main/range-util.js, tests/config/format-test.js, tests/format/flow/comments/__snapshots__/jsfmt.spec.js.snap, tests/format/flow/comments/jsfmt.spec.js, tests/format/js/call/invalid/__snapshots__/jsfmt.spec.js.snap, tests/format/js/call/invalid/jsfmt.spec.js, tests/format/js/tuple/__snapshots__/jsfmt.spec.js.snap, tests/format/js/tuple/jsfmt.spec.js, tests/format/typescript/typeparams/consistent/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/typeparams/consistent/jsfmt.spec.js
=> Add `__babel_estree` parser

.github/workflows/prod-test.yml, src/language-graphql/parser-graphql.js
=> Reduce `parser-graphql` size

changelog_unreleased/cli/10924.md, src/language-yaml/embed.js, src/language-yaml/index.js, tests/integration/__tests__/__snapshots__/support-info.js.snap, tests/integration/__tests__/with-parser-inference.js
Treat filename `.stylelintrc` (without any extension) [as YAML/JSON format](https://stylelint.io/user-guide/configure#configuration). 
Related issue #10920 
=> Support stylelintrc

changelog_unreleased/typescript/10916.md, src/language-js/print/assignment.js, tests/format/flow/assignments/__snapshots__/jsfmt.spec.js.snap, tests/format/flow/assignments/issue-10850.js, tests/format/flow/assignments/jsfmt.spec.js, tests/format/typescript/assignment/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/assignment/issue-10850.ts
=> Add heuristics to detect assignments whose id has complex type annotations

scripts/build/rollup-plugins/externals.mjs, scripts/draft-blog-post.mjs, tests/integration/__tests__/support-info.js
=> Remove more `Array#reduce()`

src/language-js/comments.js, src/language-js/embed.js, src/language-js/needs-parens.js, src/language-js/print/assignment.js, src/language-js/print/binaryish.js, src/language-js/print/call-arguments.js, src/language-js/utils.js
=> refactor: Add isObjectProperty util function

src/language-js/print/flow.js, src/language-js/print/misc.js, src/language-js/printer-estree.js
=> Move `flow` node to `flow.js`

changelog_unreleased/typescript/10961.md, src/language-js/print/class.js, tests/format/typescript/override-modifiers/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/override-modifiers/override-modifier.ts
https://github.com/prettier/prettier/issues/10642#issuecomment-850210102
=> Fix order of override modifiers

docs/vim.md
Need to change 'M' to 'm' otherwise it won't work. You may refer to https://github.com/neoclide/coc-prettier/pull/47
- [x ] I’ve added tests to confirm my change works.
- [ x] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).
=> Fix a typo

cspell.json, scripts/release/steps/publish-to-npm.js
Currently, if to enter OTP is failed, all steps are failed.
=> Retry "npm publish" when to enter OTP is faeild

tests/config/utils/check-parsers.js
In the #10415 where the tests folders where restructured, this file was missed.
=> Small detail in tests config

tests/config/utils/check-parsers.js
In #11034 I forgot to remove the tests folder
=> remove tests folder from path

scripts/generate-schema.js, tests/integration/__tests__/__snapshots__/schema.js.snap
Follow these PRs:
- https://github.com/SchemaStore/schemastore/pull/1636
- https://github.com/SchemaStore/schemastore/pull/1642
=> Update generate-schema script

CHANGELOG.md
=> Add PR and users link for changelog of 2.3.1

package.json, yarn.lock
=> Update angular to `v12.1.1`

package.json, yarn.lock
`yarn add flow-parser@0.155.0`
Closes #11189
=> Bump flow-parser from 0.154.0 to 0.155.0

scripts/build/rollup-plugins/replace-module.mjs
=> Fix replace-module plugin name

package.json, tests/format/js/top-level-await/__snapshots__/jsfmt.spec.js.snap, tests/format/js/top-level-await/jsfmt.spec.js, tests/format/misc/errors/js/async-await/__snapshots__/jsfmt.spec.js.snap, tests/format/misc/errors/js/async-await/jsfmt.spec.js, yarn.lock
support top-level await  https://github.com/meriyah/meriyah/pull/197
=> Update `meriyah` to v4.2.0

src/config/resolve-config.js
Add types for cosmiconfig explorer
=> Add types for cosmiconfig explorer

package.json, yarn.lock
Published a npm package, but still running `scripts/tools/eslint-plugin-prettier-internal-rules/`, [code](https://github.com/prettier/eslint-plugin-prettier-internal-rules/blob/main/index.js)
Fixes #10707
=> Use `eslint-plugin-prettier-internal-rules` package

changelog_unreleased/javascript/11246.md, src/language-js/embed.js, tests/format/js/comments-closure-typecast/__snapshots__/jsfmt.spec.js.snap, tests/format/js/comments-closure-typecast/styled-components.js
=> Support parenthesized tagged template literals for styled components

docs/install.md
=> docs: Require npm version for set-script command

package.json, src/language-js/parse/babel.js, tests/format/misc/errors/js/__snapshots__/jsfmt.spec.js.snap, tests/format/misc/errors/js/smart-pipeline/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/custom/abstract/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/custom/abstract/jsfmt.spec.js, tests/format/typescript/namespace/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/namespace/jsfmt.spec.js, yarn.lock
https://babel.dev/blog/2021/07/26/7.15.0
This PR just do update. I'll support new features at other PRs.
=> Update to babel/parser 7.15.0

src/language-js/parse/babel.js
=> Follow up #11314

package.json, src/language-js/parse/babel.js, yarn.lock
Release note https://github.com/babel/babel/releases/tag/v7.15.2
=> Update `@babel/parser` to 7.15.2

src/language-js/parse/babel.js
Tweaks type definitions for babel/parser
=> Improve types for using babel parser

package.json
Cspell logs fill up my terminal. So use below options:
- `--no-progress`: `Turn off progress messages` 
- `--relative`: `Issues are displayed relative to root.`
**After log:**
```
$  yarn lint:spellcheck
yarn run v1.22.5
$ cspell --no-progress --relative
./src/cli/index.js:13:4 - Unknown word (tyyypooooo)
CSpell: Files checked: 1711, Issues found: 1 in 1 files
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
=> Use some cspell options

package.json, yarn.lock
=> Update `postcss-scss` from `v4` to `v5`

package.json, yarn.lock
Targeting `next` branch.
Changelog https://github.com/postcss/postcss/releases
=> Update `postcss` from v8.2.7 to v8.3.6

types/espree/index.d.ts
I just fixed comment about espree link :)
=> Fix comment about espree link

tests/format/js/classes/__snapshots__/jsfmt.spec.js.snap, tests/format/js/classes/class-fields-features.js
Flow 0.158.0 supports class fields features. So this PR adds tests for it.
=> Update tests for new flow parser

changelog_unreleased/typescript/11426.md, package.json, tests/format/typescript/static-blocks/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/static-blocks/jsfmt.spec.js, tests/format/typescript/static-blocks/multiple.ts, tests/format/typescript/static-blocks/nested.ts, tests/format/typescript/static-blocks/static-blocks.ts, yarn.lock
=> Support TypeScript 4.4

scripts/generate-changelog.mjs
=> Improve generate changelog script

changelog_unreleased/cli/10924.md, cspell.json, src/language-yaml/embed.js, src/language-yaml/index.js, tests/integration/__tests__/__snapshots__/support-info.js.snap, tests/integration/__tests__/with-parser-inference.js
Reverts prettier/prettier#11016
Restore changes in #10924
We may want keep this open until we decide not to do path release for v2.3
=> Revert "Revert features for minor"

src/language-html/printer-html.js
Here is too nested so I refactor it.
https://github.com/prettier/prettier/blob/a547330ca97277037d10b60ff5e6b9c3c5cdca1f/src/language-html/printer-html.js#L279-L283
=> Improve `printer-html.js` readability

scripts/draft-blog-post.mjs
=> Fix blog draft script

changelog_unreleased/typescript/11426.md
See https://github.com/babel/proposals/issues/76#issuecomment-909289863
=> Update ECMAScript proposal status

jest.config.js, tests/config/install-prettier.js
Move to `tests/` dir, it's only used for test.
=> Refactor `installPrettier`

website/playground/Playground.js
=> Revert workaround for fixing playground

.github/workflows/dev-package-test.yml
We pin it to v5 because [v6 don't support Node.js 10](https://github.com/prettier/prettier/pull/10694), we already [drop support for development "build"](https://github.com/prettier/prettier/pull/10842)
=> Use pnpm 6

.eslintrc.js, scripts/build/config.mjs, scripts/build/rollup-plugins/evaluate.mjs, scripts/build/rollup-plugins/executable.mjs, scripts/build/rollup-plugins/replace-module.mjs, scripts/build/shims/fs.mjs, scripts/build/shims/os.mjs, scripts/build/shims/tty.mjs, scripts/release/steps/bump-prettier.js, scripts/release/steps/check-git-status.js, scripts/release/steps/generate-bundles.js, scripts/release/steps/install-dependencies.js, scripts/release/steps/post-publish-steps.js, scripts/release/steps/publish-to-npm.js, scripts/release/steps/push-to-git.js, scripts/release/steps/run-tests.js, scripts/release/steps/update-changelog.js, scripts/release/steps/update-dependents-count.js, scripts/release/steps/update-version.js, scripts/release/steps/validate-new-version.js, website/playground/BottomBar.js, website/playground/EditorState.js, website/playground/VersionLink.js, website/playground/WorkerApi.js, website/playground/codeSamples.js, website/playground/sidebar/SidebarOptions.js, website/playground/sidebar/options.js
ref: https://github.com/import-js/eslint-plugin-import/blob/v2.24.1/docs/rules/no-anonymous-default-export.md#importno-anonymous-default-export
For consistently name between importer and exporter, and improve editor intellisense.
=> Enable `import/no-anonymous-default-export`
