prettier/prettier

src/language-html/printer-html.js, tests/html/text/__snapshots__/jsfmt.spec.js.snap, tests/html/text/jsfmt.spec.js, tests/html/text/tag-should-in-fill.html
I think this part only need use `fill` for the text part.
=> HTML: Remove use of `normalizeParts` in "text" print

src/language-js/printer-estree.js
`isBlockComment` and `isLineComment` have complete comment types
=> Use `isBlockComment`/`isLineComment` in `canAttachComment`

.eslintrc.yml, scripts/tools/eslint-plugin-prettier-internal-rules/index.js, scripts/tools/eslint-plugin-prettier-internal-rules/jsx-identifier-case.js, src/language-js/comments.js, src/language-js/print/binaryish.js, src/language-js/print/call-arguments.js, src/language-js/print/function.js, src/language-js/print/jsx.js, src/language-js/print/statement.js, src/language-js/print/ternary.js, src/language-js/printer-estree.js, src/language-js/utils.js
=> Consistent `Jsx` case in variables

changelog_unreleased/javascript/9850.md, src/language-js/print/block.js, src/language-js/printer-estree.js, tests/js/ignore/semi/__snapshots__/jsfmt.spec.js.snap, tests/js/ignore/semi/directive.js, tests/js/ignore/semi/jsfmt.spec.js
Other parser [print semi in `ExpressionStatement`](https://github.com/prettier/prettier/blob/19a8df2f572f1bc4504cebe0614f45f868b786fa/src/language-js/printer-estree.js#L303), let's move semi to `Directive`.
Fixes #3009
=> Fix inconsistent directive print

src/language-js/loc.js, src/language-js/parse-postprocess.js
This function accept too many cases, it makes code less readable.
=> Refactor: Remove `composeLoc` function

src/language-js/printer-estree.js
=> Use `index` instead of `.getName()` in `FastPath#each()`

src/common/fast-path.js, src/language-css/printer-postcss.js, src/language-graphql/printer-graphql.js, src/language-js/print/jsx.js, src/language-js/printer-estree.js
Similar to [`Array#map()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map#Parameters), send array as third argument, this is useful when need access array in the callback.
=> Send array to `FastPath#{each,map}` callback

src/language-js/print/array.js, src/language-js/print/block.js, src/language-js/print/call-arguments.js, src/language-js/print/function-parameters.js, src/language-js/print/member-chain.js, src/language-js/print/object.js, src/language-js/print/statement.js, src/language-js/printer-estree.js, src/language-js/utils.js
Simplify use of `isNextLineEmpty`
=> Add JS version `isNextLineEmpty`

src/language-js/print/jsx.js, src/language-js/printer-estree.js, src/language-js/utils.js
=> Refactor: Move `jsx` related function to `jsx.js`

changelog_unreleased/css/9966.md, src/language-css/printer-postcss.js, tests/css/url/__snapshots__/jsfmt.spec.js.snap, tests/css/url/jsfmt.spec.js, tests/css/url/url.css
At Facebook we have some custom pre-processor `-fb-url(/abs/path/)` that gets messed up as `-fb-url(/ abs/path)`  with the current version of prettier.
The parser has hardcoded logic to only parse as path things that use `url()` but not `-fb-url()` and it parses it as `division /` and `abs/path/`. Because we put a space after division, the bug is introduced.
I don't really know the impact of changing the parser, but on the printer side, it is straightforward to not add a space after `/` if it's the first element in a group. I can't think of any reason why you could write `(/ something` in CSS so I think it's a safe change.
=> Fix absolute path in custom CSS url() calls

.eslintrc.yml, scripts/tools/eslint-plugin-prettier-internal-rules/index.js, scripts/tools/eslint-plugin-prettier-internal-rules/no-single-doc-concat.js, scripts/tools/eslint-plugin-prettier-internal-rules/test.js, src/language-css/printer-postcss.js, src/language-graphql/printer-graphql.js, src/language-handlebars/printer-glimmer.js, src/language-js/print/call-arguments.js, src/language-js/print/jsx.js, src/language-js/printer-estree.js, src/language-yaml/print/mapping-item.js
Ref https://github.com/prettier/prettier/pull/9993#discussion_r551101841
I'm going to keep this ESLint rule until we remove use of `concat()`
=> Fix using `concat()` on single `Doc`

scripts/build/build.js, scripts/build/cache.js, scripts/build/util.js
Use [fs.promises](https://nodejs.org/api/fs.html#fs_fs_promises_api) in build script.
=> Use fs.promises in build script

.eslintrc.yml, scripts/tools/eslint-plugin-prettier-internal-rules/index.js, scripts/tools/eslint-plugin-prettier-internal-rules/no-concat-in-concat.js, scripts/tools/eslint-plugin-prettier-internal-rules/test.js, src/language-css/printer-postcss.js, src/language-graphql/printer-graphql.js, src/language-handlebars/printer-glimmer.js, src/language-html/printer-html.js, src/language-js/print/binaryish.js, src/language-js/print/call-arguments.js, src/language-js/print/call-expression.js, src/language-js/print/function-parameters.js, src/language-js/print/function.js, src/language-js/print/jsx.js, src/language-js/print/module.js, src/language-js/print/object.js, src/language-js/printer-estree.js, src/language-markdown/printer-markdown.js
Another simplification before we merge #9993
The only possible effect should be https://github.com/prettier/prettier/blob/181a325c1c07f1a4f3738665b7b28288dfb960bc/src/language-markdown/printer-markdown.js#L95-L97
But we are not having this problem in `printChildren` function.
Any other place convert `concat` to other doc type?
=> Forbid use `concat()` in `concat()`

scripts/build/bundler.js
When `--purge-cache` is `true`,  always `cached` isn't `true`.
=> Check cache only when purge-cache is off

scripts/build/bundler.js, scripts/build/cache.js
Tiny refactoring. Move `checkCache` function to `Cache` class as as instance method.
=> Move checkCache to Cache class

changelog_unreleased/handlebars/9978.md, src/language-handlebars/printer-glimmer.js, tests/handlebars/block-statement/__snapshots__/jsfmt.spec.js.snap, tests/handlebars/element-node/__snapshots__/jsfmt.spec.js.snap, tests/handlebars/element-node/element-node.hbs
This PR implements the change proposed in https://github.com/prettier/prettier/issues/8502.
Given these options:
```
--parser glimmer
--print-width 40
```
**Input:**
```hbs
<MyComponent @prop={{true}} @prop2={{true}} as |thing|></MyComponent>
```
**Current Output:**
```hbs
<MyComponent
@prop={{true}}
@prop2={{true}} as |thing|
/>
```
**Proposal:**
```hbs
<MyComponent
@prop={{true}}
@prop2={{true}}
as |thing|
/>
```
cc @pzuraq
=> handlebars: Print final blockParam on its own line

src/language-js/print/statement.js
Tiny refactoring.
It is often the case that the last statement is not an `EmptyStatement`. it is useless to run the `filter` in that case.
=> Refactor: Use getLastStatement function in printStatementSequence

src/language-markdown/printer-markdown.js
Double negative is hard to read, so rename it
=> refactor: Rename shouldNotPrePrintHardline to shouldPrePrintHardline

scripts/build/bundler.js
A workaround is added in #9804. It is unnecessary now because it's fixed in rollup/plugin-node-resolve 11.1.0.
=> Remove workaround for @rollup/plugin-node-resolve 11

src/language-handlebars/printer-glimmer.js, src/language-handlebars/utils.js, tests/handlebars/html-whitespace-sensitivity/__snapshots__/jsfmt.spec.js.snap, tests/handlebars/html-whitespace-sensitivity/jsfmt.spec.js
This PR proposes an implementation of the `htmlWhitespaceSensitivity=strict` option for Handlebars.
Step 2 out of 3 of https://github.com/prettier/prettier/issues/9881
The git diff is not yet meaningful since the target branch is master. To get an idea of the changes, [see this PR](https://github.com/dcyriller/prettier/pull/1/files) (it targets the branch 2 / 3 on my fork).
=> handlebars: Support `htmlWhitespaceSensitivity=strict` option (2/3)

docs/rationale.md
I think it'd make a useful addition to the docs.
=> docs: add a note on formatting reversibility

website/static/overrides.css
Now it doesn't look like a heading at all:
> ![image](https://user-images.githubusercontent.com/94334/105849461-1a686500-5fe9-11eb-8cb1-b8ddd429d754.png)
=> website: bigger font for <h5> in blog

.github/workflows/issue-mark-duplicate.yml, .github/workflows/mark-issue-duplicate.yml
Add a workflow help you automatically manage issues.
ref: https://github.com/prettier/prettier/issues/9601 https://github.com/prettier/prettier/issues/10036
When you enter "Duplicate of #xxx",  the GitHub Actions will help you add the label `type:duplicate` and close the issue.
At the same time it supports concise commands, such as "/d", I don't know if you need it.
More details can see https://github.com/actions-cool/issues-helper/blob/main/README.en-US.md#mark-duplicate
=> CI: Add `Mark issue duplicate` job

changelog_unreleased/cli/10124.md, docs/plugins.md, src/cli/constant.js, src/cli/format.js, src/common/util.js, src/main/comments.js, src/main/core.js, tests/js/cursor/jsfmt.spec.js, tests_integration/__tests__/__snapshots__/debug-print-comments.js.snap, tests_integration/__tests__/debug-print-comments.js, website/playground/EditorState.js, website/playground/Playground.js, website/playground/PrettierFormat.js, website/static/worker.js
A new `--debug-print-comments` CLI flag and corresponding functionality for the Playground.
=> Add CLI flag for debugging comment attachment issues

changelog_unreleased/api/10122.md, src/document/doc-printer.js, tests_integration/__tests__/line-suffix-boundary.js, tests_integration/printDoc.js
There is a bug in the implementation of the `lineSuffixBoundary` command: the [`fits` function][fits] in the doc printer doesn't consider `lineSuffixBoundary` to be a potential line break. That's why `lineSuffixBoundary` doesn't break groups, the line length limit is calculated incorrectly after a line break caused by `lineSuffixBoundary`, etc. This PR fixes this bug.
[fits]: https://github.com/prettier/prettier/blob/dd606d9ce1810f970c57e09f2f8cde5adcfbdb01/src/document/doc-printer.js#L147
I couldn't find any open issues that this PR would directly fix. This is because `lineSuffixBoundary` is very little used. It hasn't really been useful because of this bug. I got ugly results every time I tried to use it. But now it should become a great help in solving comments-related issues.
For …
=> Fix lineSuffixBoundary

.gitignore, changelog_unreleased/cli/8233.md, docs/cli.md, src/cli/constant.js, src/cli/expand-patterns.js, tests_integration/__tests__/__snapshots__/early-exit.js.snap, tests_integration/__tests__/__snapshots__/error-on-unmatched-pattern.js.snap, tests_integration/__tests__/__snapshots__/help-options.js.snap, tests_integration/__tests__/error-on-unmatched-pattern.js, tests_integration/cli/error-on-unmatched-pattern/some.js, tests_integration/cli/error-on-unmatched-pattern/some.json, tests_integration/cli/error-on-unmatched-pattern/some.yml
Fixes: https://github.com/prettier/prettier/issues/8233
=> Add CLI option to prevent errors on unmatched patterns

src/language-handlebars/printer-glimmer.js
Simplify this part, the docs changed a little bit, before `[line, doc, line, doc]`, now it's `[[line, doc], [line, doc]]`.
/cc @dcyriller
=> Simplify `printStartingTag` in glimmer printer

changelog_unreleased/typescript/10109.md, src/language-js/print/type-parameters.js, tests/typescript/trailing-comma/__snapshots__/jsfmt.spec.js.snap, tests/typescript/trailing-comma/arrow-functions.tsx, tests/typescript/trailing-comma/jsfmt.spec.js, tests/typescript/trailing-comma/type-parameters.ts
Fixes #3662.
I think we can do this at next major.
=> Print trailing comma for type parameters

changelog_unreleased/cli/10169.md, commands.md, cspell.json, src/document/doc-builders.js, src/document/doc-debug.js, src/document/doc-utils.js, src/language-markdown/printer-markdown.js, tests_integration/__tests__/__snapshots__/debug-api.js.snap, tests_integration/__tests__/debug-api.js, tests_integration/__tests__/debug-print-doc.js
The idea is to make the output of `--debug-print-doc` closer to actual code for generating docs. Ideally, it should be possible for it to work without modification after copy-pasting into a JS file. That ideal probably hasn't been reached by this PR, but it's pretty close. I believe this will make `--debug-print-doc` (and the corresponding part of the Playground) more useful.
[Before:](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwA64NIATqt7DAIy2wCY0oBfKkAGhAgAcYBLaAZ2VAEMAnPhADuABX4IuKHgBshPAJ5cGRPjzABrODADKTNaygBzZDD4BXOAzgBbInAAm9hwBkeRsz0NwAYhD7WeGDYjZBAeMxgIehAACxhraQB1GNZ4Dj0wOG0JVNYAN1T5ULAOJRADDjg+GBFVQwDkADMZSoYAKw4ADwAhVQ0tbR5rOGcDOCaWyxAOzu0DQ2k4AEUzCHgJ6VaQPT5KvlCO6GimPgMYRNZ7GBjkAA4ABgYTiErE1SZQk7g9vPGGAEdVvBasxJGEOABaKBwBwOaJ8OCA1gI2qeBpIZqbKaVaysEzmbHzRYrNbjDGTBgwHhEC5X …
=> Round-trippable --debug-print-doc

changelog_unreleased/cli/10169.md, src/cli/format.js, src/document/doc-debug.js, src/main/core.js, tests_integration/__tests__/__snapshots__/debug-api.js.snap, tests_integration/__tests__/__snapshots__/debug-print-doc.js.snap, tests_integration/__tests__/debug-api.js, tests_integration/__tests__/debug-print-doc.js, website/playground/Playground.js, website/playground/markdown.js
* I overlooked how things like `dedentToRoot(hardline)` are printed (`dedentToRoot([hardline])` instead of the expected result)
* Print without the trailing semicolon
* Fix printing for invalid `fill`
* Add a "Copy doc" button to the Playground
=> Followup for #10169: minor tweaks

website/playground/EditorState.js
Why do we need that extra click?
=> Playground: show sidebar by default

src/cli/context.js, src/cli/core.js, src/cli/index.js, src/cli/option.js, tests_integration/__tests__/plugin-resolution.js
1. Move `logger` out `Context`, so we don't need a extra `Context#initContext()` call.
2. Parse `plugin`/`plugin-search-dir` argument in a later stage, so we can use logger to log errors.
stable:
```console
npx prettier --plugin=ninjia
Cannot find module 'ninjia'
Require stack:
- ...
```
this pr:
```console
node bin/prettier --plugin=ninjia
[error] Cannot find module 'ninjia'
[error] Require stack:
[error] - ...
```
stable:
```console
npx prettier --plugin-search-dir=ninjia
ninjia does not exist or is not a directory
```
this pr:
```console
node bin/prettier --plugin-search-dir=ninjia
[error] ninjia does not exist or is not a directory
```
3. Fix a possible bug 
This line https://github.com/prettier/prettier/blob/main/src/cli/index.js#L65 , should not use `context.args["stdin-filepath"]`, …
=> Refactor CLI

website/playground/EditorState.js, website/playground/Playground.js
When `show doc`, I think user mean to focus checking `Doc`, don't care "output" that much.
=> Playground: Allow hide `input` and `output`

.eslintrc.yml, changelog_unreleased/api/10221.md, commands.md, scripts/tools/eslint-plugin-prettier-internal-rules/index.js, scripts/tools/eslint-plugin-prettier-internal-rules/prefer-indent-if-break.js, scripts/tools/eslint-plugin-prettier-internal-rules/test.js, src/document/doc-builders.js, src/document/doc-debug.js, src/document/doc-printer.js, src/language-html/printer-html.js, src/language-js/print/binaryish.js, src/language-js/print/class.js, src/language-js/print/interface.js, tests_integration/__tests__/debug-api.js
`indentIfBreak(doc, { groupId })` is an optimized version of `ifBreak(indent(doc), doc, { groupId })`.
- a convenient shortcut
- reduces the size of the doc
- processed faster by doc traversing functions like `mapDoc`
`indentIfBreak(doc, { groupId, negate: true })` corresponds to `ifBreak(doc, indent(doc), { groupId })`
`groupId` is required because "indent only if broken" is the default behavior of `indent`, so it doesn't make sense to apply `indentIfBreak` to the current group.
This is intended to be used for solving issues with assignments, for which conditional indentation seems to be a [useful tool](https://deploy-preview-10183--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEAKVBKABAXgHxbAA6UWWAZgK5RgwCW0WdUAJgjAKpQA2cAznwBCAJzgBDANaoWEMABosAc2ERKABwCSLbMVJksomJWGk65EeKkz5TVu2myMC …
=> RFC: indentIfBreak

src/language-js/comments.js, src/language-js/needs-parens.js, src/language-js/print/binaryish.js, src/language-js/print/call-arguments.js, src/language-js/print/call-expression.js, src/language-js/print/jsx.js, src/language-js/print/member-chain.js, src/language-js/print/member.js, src/language-js/print/template-literal.js, src/language-js/print/ternary.js, src/language-js/printer-estree.js, src/language-js/utils.js
- Rename `isCallOrOptionalCallExpression` to `isCallExpression`, they are all `CallExpression` in ESTree
- Add `isMemberExpression`
- Replace related checks
=> Refactor `ChainElement` related parts

changelog_unreleased/cli/10217.md, cspell.json, package.json, src/cli/format.js, src/cli/logger.js, yarn.lock
Fixes #9061
This can't be tested on CI, local test try 
`npx prettier tests/flow-repo/config_module_system_node_resolve_dirname --check`
and 
`node bin/prettier tests/flow-repo/config_module_system_node_resolve_dirname --check`
to see differences.
=> CLI: clear printed long filenames

changelog_unreleased/cli/10208.md, src/cli/core.js, tests_integration/__tests__/__snapshots__/config-resolution.js.snap, tests_integration/__tests__/config-resolution.js
=> CLI: Print error message when `--find-config-path` can't find config file

changelog_unreleased/handlebars/10179.md, src/language-handlebars/clean.js, src/language-handlebars/printer-glimmer.js, tests/handlebars/block-statement/__snapshots__/jsfmt.spec.js.snap, tests/handlebars/element-node/__snapshots__/jsfmt.spec.js.snap, tests/handlebars/html-whitespace-sensitivity/__snapshots__/jsfmt.spec.js.snap, tests/handlebars/mustache-statement/__snapshots__/jsfmt.spec.js.snap, tests/handlebars/newline/__snapshots__/jsfmt.spec.js.snap, tests/handlebars/text-wrap/__snapshots__/jsfmt.spec.js.snap, tests/handlebars/text-wrap/test.hbs, tests/handlebars/whitespace/__snapshots__/jsfmt.spec.js.snap
```handlebars
{{!-- Input --}}
<div>
A long enough string to trigger a line break that would prevent wrapping more and more.
</div>
{{!-- Prettier stable --}}
<div>
A long enough string to trigger a line break that would prevent wrapping more and more.
</div>
{{!-- Prettier main --}}
<div>
A long enough string to trigger a line break that would prevent wrapping more
and more.
</div>
```
=> handlebars: Split text content on multiple lines

src/language-html/ast.js, src/main/options.js, src/main/parser.js, src/main/support.js
=> Refactor: Use `fromPairs` instead of `Array#reduce`

src/language-handlebars/printer-glimmer.js
This PR brings two small refactoring to Handlebars printer:
- simplify `generateHardlines` function by removing the second argument (the max number of newlines to preserve is documented [here](https://prettier.io/docs/en/rationale.html#empty-lines) so it is not necessary to make the function configurable with a second argument)
- use the right regex to assess a TextNode is whitespace only (`!/\S/.test(text)` -> `/^[\t\n\f\r ]*$/.test(text)`)
=> Handlebars printer: two small refactorings

.eslintrc.yml, docs/plugins.md, scripts/tools/eslint-plugin-prettier-internal-rules/index.js, scripts/tools/eslint-plugin-prettier-internal-rules/prefer-ast-path-each.js, scripts/tools/eslint-plugin-prettier-internal-rules/test.js, src/common/ast-path.js, src/language-js/comments.js, src/language-js/print/angular.js, src/language-js/print/jsx.js, src/language-js/print/statement.js, src/language-js/print/ternary.js, src/language-js/print/type-annotation.js, src/language-js/utils.js, src/main/ast-to-doc.js, website/versioned_docs/version-stable/plugins.md
`FastPath` is a misleading name. Is there also a `SlowPath`? 
=> Refactor: rename FastPath → AstPath

commands.md, src/document/doc-builders.js, src/document/doc-debug.js, src/document/doc-printer.js, src/document/doc-utils.js, src/language-js/print/member-chain.js, tests_integration/__tests__/debug-api.js
Introduces a new doc builder: `label(label: string, doc: Doc): Doc`
It marks a doc with a string label. This doesn't affect how the doc is printed, but can be useful for heuristics based on doc introspection.
E.g., to decide how to print an assignment expression, we might want to know whether its right-hand side has been printed as a method call chain, not as a plain function call. If the method chain printing code uses `label` to mark its result, checking that condition can be as easy as `rightHandSideDoc.label === 'method-chain'`.
=> RFC: label doc

changelog_unreleased/api/9733.md
I think this can help plugin authors migrate with the `concat()` deprecation.
=> Add a link to `prettier-doc/no-concat` ESLint rule

src/document/doc-utils.js, src/language-js/print/jsx.js
This function is testing `Doc` contains `{type: 'line'}`, but obviously should only allow `line`, `softline`, `hardline`.
=> Remove `isLineNext`

changelog_unreleased/javascript/10187.md, src/language-js/print/ternary.js, src/language-js/utils.js, tests/js/ternaries/__snapshots__/jsfmt.spec.js.snap, tests/js/ternaries/indent-after-paren.js
=> Fix inconsistent indentation for ternary in call expressions

changelog_unreleased/typescript/10316.md, src/language-js/print/call-arguments.js, tests/typescript/typeparams/print-width-120/__snapshots__/jsfmt.spec.js.snap, tests/typescript/typeparams/print-width-120/issue-7542.ts, tests/typescript/typeparams/print-width-120/jsfmt.spec.js
=> Allow arg hugging for non-concise arrow functions with return type

changelog_unreleased/json/10323.md, docs/options.md, src/common/util.js, tests/json/json5-as-json-with-trailing-commas/__snapshots__/jsfmt.spec.js.snap, tests/json/json5-as-json-with-trailing-commas/jsfmt.spec.js, tests/json/json5-as-json-with-trailing-commas/nested-quotes.json
Fixes #5708
More specifically, addresses https://github.com/prettier/prettier/issues/5708#issuecomment-510571797
With the `quoteProps` option set to `preserve` and `singleQuotes` to `false` (default), double quotes are always used for printing strings, including situations like this: `"bla\"bla"`. This effectively allows using `--parser json5` for "JSON with comments and trailing commas".
=> Don't use smart quotes for JSON5 with --quote-props=preserve

changelog_unreleased/typescript/10337.md, src/language-js/needs-parens.js, src/language-js/utils.js, tests/typescript/non-null/__snapshots__/jsfmt.spec.js.snap, tests/typescript/non-null/braces.ts
Fixes #10336
Necessary parentheses sometimes weren't printed in expressions containing non-null assertions. This has been fixed.
=> Correct parentheses for non-null assertions

website/playground/markdown.js
I often paste copied markdown from playground to a text editor that support Prettier integration.
=> Add prettier-ignore comment for copying markdown from Playground

src/language-js/clean.js
=> Remove `OptionalMemberExpression` clean

changelog_unreleased/javascript/10342.md, src/common/ast-path.js, src/language-js/printer-estree.js, tests/js/async/__snapshots__/jsfmt.spec.js.snap, tests/js/async/nested.js, tests/js/async/simple-nested-await.js
=> Better formatting for nested await in member/call expression heads

src/language-js/print/binaryish.js, src/language-js/print/class.js, src/language-js/print/jsx.js, src/language-js/print/member-chain.js, src/language-js/print/property.js, src/language-js/print/type-annotation.js, src/main/ast-to-doc.js, src/main/comments.js
=> Refactor: Switch second parameter of `printComments` from `function` to `Doc`

src/language-js/loc.js
I think `Node.range` include `typeAnnotation` range in all parsers.
=> Simplify JS `locEnd`

changelog_unreleased/json/10346.md, src/language-js/parser-babel.js, tests/markdown/multiparser-json/__snapshots__/jsfmt.spec.js.snap, tests/markdown/multiparser-json/invalid-json.md, tests/misc/errors/json/__snapshots__/jsfmt.spec.js.snap, tests/misc/errors/json/jsfmt.spec.js
Make JSON parser stricter, I don't think we should allow all expressions.
And we don't need all the `plugins` and `errorRecovery`.
Fixes #10333
=> Make JSON parser stricter

changelog_unreleased/typescript/10024.md, src/language-js/print/function-parameters.js, src/language-js/print/function.js, src/language-js/print/type-annotation.js, src/language-js/print/typescript.js, tests/flow-repo/dictionary/__snapshots__/jsfmt.spec.js.snap, tests/flow-repo/missing_annotation/__snapshots__/jsfmt.spec.js.snap, tests/flow-repo/spread/__snapshots__/jsfmt.spec.js.snap, tests/flow/method/__snapshots__/jsfmt.spec.js.snap, tests/flow/method/consistent-breaking.js, tests/typescript/generic/__snapshots__/jsfmt.spec.js.snap, tests/typescript/generic/ungrouped-parameters.ts, tests/typescript/method/__snapshots__/jsfmt.spec.js.snap, tests/typescript/method/issue-10352-consistency.ts, tests/typescript/method/method-signature-with-wrapped-return-type.ts
closes #10352
The change looks repetitive and it is. Would be good later to refactor these files and unify the code that prints signatures for different types of function-like nodes to make sure the formatting for them stays consistent.
=> Heuristic for grouping parameters in method signatures

src/common/util.js, src/language-js/printer-estree.js
Another step to simplify `printString`.
=> Add `printDirective`

.eslintrc.yml, scripts/tools/eslint-plugin-prettier-internal-rules/better-parent-property-check-in-needs-parens.js, scripts/tools/eslint-plugin-prettier-internal-rules/flat-ast-path-call.js, scripts/tools/eslint-plugin-prettier-internal-rules/index.js, scripts/tools/eslint-plugin-prettier-internal-rules/test.js, src/language-js/printer-estree.js
Enfore `path.call(print, "a", "b")` over `path.call((childPath) => childPath.call(print, "b"), "a")`.
This rule only handle simple cases, we can add more complicated cases in feature.
It only caught one place in codebase 😄 
---
I remember there was unneeded `.map()` in `.call()` somewhere, but couldn't find it.
=> Add `flat-ast-path-call` rule

changelog_unreleased/typescript/10418.md, src/language-js/print/typescript.js, tests/misc/typescript-babel-only/__snapshots__/jsfmt.spec.js.snap, tests/misc/typescript-babel-only/ts-4.2-abstract-constructor-type.ts
TS 4.2 supports [abstract constructor signature](https://devblogs.microsoft.com/typescript/announcing-typescript-4-2/#abstract-construct-signatures).
=> Support TS 4.2 abstract constructor signature

jest.config.js
https://jestjs.io/docs/en/next/code-transformation#defaults
Without this change, I get an error when Babel tries to resolve Browserslist, but `fs.statSync` is mocked.
I get this error not always, but I wasn't able to find what exactly triggers it. E.g., this error disappears if I rename the directory with the repo from `prettier` to `prttrtmp`. =) I use WSL/Ubuntu on Windows 10.
If the test setup depends on this default transformer, and it can't be disabled, then I'll try to debug this deeper. Otherwise, let's just disable it.
````
● plugin search should not crash when prettier isn't inside a directory › encountered a declaration exception
ENOENT: no such file or directory, stat '/mnt/d/dev/prettier/tests_integration/mnt/d/dev/prettier/tests_integration/runPrettier.js'
52 | …
```
=> Disable Jest's default transformer (Babel)

src/language-js/print/type-parameters.js
Maybe those conditions are unnecessary because there is a condition that validate `GenericTypeAnnotation` and `TSTypeReference` in `isSimpleType` function called by `shouldHugType`.
https://github.com/prettier/prettier/blob/3efa3d3c58fbf563809d7cf205c1830d22364cf4/src/language-js/utils.js#L477-L483
=> Remove unnecessary conditions for printing type parameters

package.json, src/language-js/printer-estree-json.js, tests_config/run_spec.js, yarn.lock
https://github.com/babel/babel/issues/12915 has been fixed so we can remove unstable AST testing.
=> Remove unstable AST testing

package.json, src/language-js/types/estree.d.ts
@typescript-eslint/typescript-estree reexports these types.
=> typechecking: remove @typescript-eslint/types from devDependencies

docs/cli.md, docs/options.md
`--require-pragma` and `--insert-pragma` are core options, but somehow the docs for them ended up on the CLI page too. This PR cleans that up and fixes #3644
=> Clarify docs about pragma

website/playground/Playground.js
Before
```sh
--no-bracket-spacing
--embedded-language-formatting off
--html-whitespace-sensitivity strict
--insert-pragma
--jsx-bracket-same-line
--jsx-single-quote
--parser babel
--print-width 81
--prose-wrap never
--quote-props consistent
--range-end 2
--range-start 1
--require-pragma
--no-semi
--single-quote
--tab-width 3
--trailing-comma none
--use-tabs
--vue-indent-script-and-style
```
After
```sh
--parser babel
--print-width 81
--tab-width 3
--use-tabs
--no-semi
--single-quote
--no-bracket-spacing
--jsx-single-quote
--jsx-bracket-same-line
--quote-props consistent
--trailing-comma none
--prose-wrap never
--html-whitespace-sensitivity strict
--insert-pragma
--require-pragma
--vue-indent-script-and-style
--embedded-language-formatting off
--range-start 1
--range-end 2
```
Especially …
=> Playground: Order options

changelog_unreleased/javascript/10517.md, src/language-js/print/array.js, src/language-js/print/call-arguments.js, tests/js/last-argument-expansion/__snapshots__/jsfmt.spec.js.snap, tests/js/last-argument-expansion/number-only-array.js
=> Avoid last-argument hugging for number-only arrays

changelog_unreleased/javascript/9992.md, src/language-js/print/function.js, src/language-js/printer-estree.js, src/main/ast-to-doc.js, src/main/comments.js, tests/js/arrows/__snapshots__/jsfmt.spec.js.snap, tests/js/arrows/arrow-chain-with-trailing-comments.js
Fixing this:
**Prettier pr-10511**
[Playground link](https://deploy-preview-10511--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEAPABAXnQCgIYCUWAfLjgEZGanAA6U66YOBA3PQL7oD0AVOhAgAHAM7pe3AiAA0IYTACW0EclB4ATuogB3AAoaEKlHgA22vAE8Vs8urxgA1nBgBlIfYVQA5shjqArnCycAC25HAAJhGRADJ43v54XnAAYhDqIXgwit7IIHj+MBAyIAAWMCEmAOqlCvAi7mBwLoZ1CgBudRZ5YCLWIJ4icOowunZemcgAZqZDsgBWIqgAQnaOzi54IXAxnnDTs0Egi6gunl4mcACK-hDwByZzIO7qQ+p55HjhJiVC6p4wKoKCIwUrIAAcAAZZH8IEMqnYhHk-nA3u19rIAI63eBjYRGfIiAC0UDgkUiJXUcGxCipYySkyQM0eRyGIQUvgCrPOlxud32TMOshgXyBILBSAATMK7AoTOcAMIQEKMkCogCsJX8QwAKl8jMynu1AgBJKDRWAuMD-IQwACC5pcMAslweQw4HCAA)
```sh
--parser babel
```
**Input:**
```jsx
x = (a) => ((b) => {
c();
} /* oops */)
```
**Output:**
```jsx
x = (a) => (b) /* oops */ => {
c();
};
``` …
=> Fix edge case with trailing comments in arrow chains

src/language-js/parser-babel.js, tests/js/call/no-argument/__snapshots__/jsfmt.spec.js.snap, tests/js/call/no-argument/import.js, tests/js/call/no-argument/jsfmt.spec.js, tests/misc/errors/js/import/__snapshots__/jsfmt.spec.js.snap, tests/misc/errors/js/import/jsfmt.spec.js
To avoid unexpected cases, I don't think anyone can use this code in real world, so I'm not going to add changelog for it.
=> Disallow `import` without argument and `new import(…)`

yarn.lock
This updates `@typescript‑eslint/experimental‑utils`, which is used by `eslint‑plugin‑jest`, to deduplicate `@typescript‑eslint/typescript-estree`, `@typescript‑eslint/types`, and `@typescript‑eslint/visitor‑keys`.
---
**Refs:** [#10589](https://github.com/prettier/prettier/pull/10589/files#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2de) ([`f0a612a`](https://github.com/prettier/prettier/commit/f0a612a3029b53ffc4ef130fe40b92b519231f8b#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2de))
=> Build(deps): Deduplicate `@typescript‑eslint/typescript‑estree`

docs/precommit.md
`Lint staged` along with `mrm` recently [migrated](https://github.com/okonet/lint-staged/pull/954) from `husky` to `simple-git-hooks`.
It is now reflected in their [docs](https://github.com/okonet/lint-staged):
> It will install and configure simple-git-hooks and lint-staged depending on code quality tools from package.json dependencies so please make sure you install (npm install --save-dev) and configure all code quality tools like Prettier, ESlint prior that.
Migration brought these benefits for users: 
* lighter `node_modules` 
`simple-git-hooks` (10 kb) is lighter then husky4 (1mb) and husky5 (25kb)
* Out of the box `Yarn 2` support
* No worry for licensing. 
Simple git hooks has MIT license, like husky 4
P.S didn't check the checkboxes. Don't know If I should add challengelog for …
=> [Docs] Change `husky` to `simple-git-hooks`

docs/precommit.md
Apply prettier on all files.
Without `--ignore-unknown`, files without an extension or with an unknown extension would trigger the following error :
```
.gitignore[error] No parser could be inferred for file: ansible.cfg
```
=> Ignore unknown files + apply prettier on all possible files

changelog_unreleased/handlebars/10586.md, src/language-handlebars/printer-glimmer.js, tests/handlebars/concat-statement/__snapshots__/jsfmt.spec.js.snap, tests/handlebars/html-whitespace-sensitivity/__snapshots__/jsfmt.spec.js.snap, tests/handlebars/mustache-statement/__snapshots__/jsfmt.spec.js.snap, tests/handlebars/mustache-statement/basics.hbs, tests/handlebars/mustache-statement/issue-8691.hbs, tests/handlebars/text-wrap/__snapshots__/jsfmt.spec.js.snap, tests/handlebars/whitespace/__snapshots__/jsfmt.spec.js.snap
In Ember ecosystem, the opening mustache and the path are often printed on a same line (see [this comment](https://github.com/prettier/prettier/issues/8691#issuecomment-652589072) and [this comment](https://github.com/prettier/prettier/issues/8691#issuecomment-652557920) for more details).
```handlebars
{{!-- Input --}}
<GlimmerComponent
@errors={{or this.aVeryLongProperty (and this.aProperty (v-get bike "number" "message"))}}
data-test-beneficiary-account-number
/>
<GlimmerComponent
@progress={{aPropertyEngdingAfterEightiethColumnToHighlightAWeirdClosingParenIssue}}
/>
{{!-- Prettier stable --}}
<GlimmerComponent
@errors={{
or
this.aVeryLongProperty
(and this.aProperty (v-get bike "number" "message"))
}}
data-test-beneficiary-account-number
/>
<GlimmerComponent
@progress={{ …
```
=> Ember / Handlebars: Do not break opening mustache and path

changelog_unreleased/javascript/10666.md, src/main/ast-to-doc.js, src/main/comments.js, tests/js/ignore/__snapshots__/jsfmt.spec.js.snap, tests/js/ignore/issue-10661.js
=> JS: Fix duplicated `prettier-ignore` comments

changelog_unreleased/javascript/10693.md, src/language-js/print/call-arguments.js, tests/js/do/__snapshots__/jsfmt.spec.js.snap, tests/js/do/call-arguments.js
=> Improve formatting for do expression

src/language-js/print/object.js
Avoid sorting properties of object-literal-like constructions when they're taken only from one source.
=> Minor refactoring of printObject

changelog_unreleased/graphql/10689.md, src/language-graphql/printer-graphql.js, tests/graphql/comments/__snapshots__/jsfmt.spec.js.snap, tests/graphql/definitions/__snapshots__/jsfmt.spec.js.snap, tests/graphql/definitions/fields.graphql
Fixes #10655 
Added an additional condition to check if a space (`" "`) should be inserted after the keyword.
=> GraphQL: Fix missing space after keyword in anonymous operations

changelog_unreleased/typescript/10702.md, src/language-js/needs-parens.js, tests/typescript/argument-expansion/__snapshots__/jsfmt.spec.js.snap, tests/typescript/as/__snapshots__/jsfmt.spec.js.snap, tests/typescript/assignment/__snapshots__/jsfmt.spec.js.snap
These parens are useless.
https://github.com/prettier/prettier/issues/9732#issuecomment-731074219
=> TS: don't print parens around nested type assertions

changelog_unreleased/typescript/10418.md
I found this issue when reading https://deploy-preview-10659--prettier.netlify.app/blog/2021/04/12/2.3.0.html#support-typescript-42-10418httpsgithubcomprettierprettierpull10418-10466httpsgithubcomprettierprettierpull10466-10546httpsgithubcomprettierprettierpull10546-10589httpsgithubcomprettierprettierpull10589-by-sosukesuzukihttpsgithubcomsosukesuzuki
=> docs: fix incorrect version comment in changelog

changelog_unreleased/flow/10788.md, package.json, src/language-js/needs-parens.js, src/language-js/print/flow.js, src/language-js/print/type-annotation.js, tests/format/flow/optional-indexed-access/__snapshots__/jsfmt.spec.js.snap, tests/format/flow/optional-indexed-access/jsfmt.spec.js, tests/format/flow/optional-indexed-access/optional-indexed-access.js, yarn.lock
This adds support for Flow's "Optional Indexed Access Types" (e.g `type T = Obj?.[K]`), a follow on to the support for "Indexed Access Types" added in https://github.com/prettier/prettier/pull/10594
=> Support for Flow's Optional Indexed Access type

docs/cli.md
**Note:** I changed “opt-out” to “opt out”, because there was only 1 use of the former and 2 uses of the latter.
Minor formatting tweaks.
=> Minor formatting tweaks

bin/prettier.js, src/cli/index.js, tests/integration/__tests__/__snapshots__/early-exit.js.snap, tests/integration/__tests__/__snapshots__/plugin-options-string.js.snap, tests/integration/__tests__/__snapshots__/plugin-options.js.snap, tests/integration/__tests__/check.js, tests/integration/__tests__/early-exit.js, tests/integration/__tests__/list-different.js, tests/integration/__tests__/loglevel.js, tests/integration/__tests__/patterns-dirs.js, tests/integration/__tests__/piped-output.js, tests/integration/__tests__/plugin-options-string.js, tests/integration/__tests__/plugin-options.js, tests/integration/runPrettier.js
This PR didn't actually use any async API in CLI, just make it async and make test pass.
This is a necessary step for #4459 and #4980
Finally, I figured how to test it.
~There is still [one failed test](https://github.com/prettier/prettier/pull/10804/files#diff-d30da97d630a4c42ca81fcfd745d6b2ac8f4f757e1e7c786e9189bc0a7110f21R90), I can't debug it on windows, maybe @thorn0 or @connor4312 can help me out?~ Fixed
=> Switch CLI to async

docs/precommit.md
In the provided example, `pretty-quick` is installed locally, not globally, which may cause the hook to fail:
```
❯ git commit
.husky/pre-commit: 4: pretty-quick: not found
husky - pre-commit hook exited with code 127 (error)
```
This problem can be fixed by running `"npx pretty-quick --staged"` instead of just `"pretty-quick --staged"` 
Maybe @typicode can confirm?
____
**N.B** I've made changes to documentation only, so everything below is not applicable
=> [Docs] Fix pre-commit hook setup command

package.json, src/cli/core.js, src/cli/expand-patterns.js, src/cli/format.js, src/cli/index.js, src/cli/option.js, tests/integration/runPrettier.js, yarn.lock
=> Use async APIs in CLI

.github/workflows/dev-package-test.yml, .github/workflows/dev-test.yml, .github/workflows/prod-test.yml, package.json, scripts/build/build.js, src/cli/index.js, tests/integration/__tests__/__snapshots__/early-exit.js.snap, tests/integration/__tests__/early-exit.js
The production build still support v10
Like #4537
=> Drop Node.js 10 support for development "build"

changelog_unreleased/yaml/10874.md, src/language-yaml/print/mapping-item.js, tests/format/yaml/comment/__snapshots__/jsfmt.spec.js.snap, tests/format/yaml/comment/collection.yml, tests/format/yaml/mapping/__snapshots__/jsfmt.spec.js.snap, tests/format/yaml/mapping/explicit-key.yml
Hi, this PR fixes #5599, in which long YAML keys cause us to print using yaml's explicit mapping syntax. The intent of the code was to use explicit mapping syntax to accommodate multiline keys, but it had the unintended effect of using explicit mapping syntax for long single-line keys too. This is bad because:
* Doing so has the effect of further _increasing_ the line length
* Explicit mappings are obscure and most people have never seen them. It causes confusion to introduce them needlessly, as shown in the issue
As others in the issue have noted, this is a pretty non-obvious area of code, so I've added some comments and used what I believe are more helpful variable names.
It might be interesting to someone with more experience to see the (pre-existing) (ab)use of `conditionalGroup` …
=> Fix #5599, long yaml keys trigger explicit mapping

.eslintrc.yml, package.json, src/document/doc-utils.js, src/language-css/printer-postcss.js, src/language-js/printer-estree.js, src/language-yaml/utils.js, yarn.lock
Added `regexp/no-useless-flag` rule, but it's not really helping, hope it can catch more problems in future. https://github.com/ota-meshi/eslint-plugin-regexp/issues/205
=> Style: Remove useless flags

changelog_unreleased/typescript/10901.md, src/language-js/print/assignment.js, tests/format/flow/type-alias/__snapshots__/jsfmt.spec.js.snap, tests/format/flow/type-alias/issue-100857.js, tests/format/flow/type-alias/jsfmt.spec.js, tests/format/typescript/type-alias/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/type-alias/issue-100857.ts
=> Add heuristics to detect type aliases that has complex typeparameters

changelog_unreleased/html/10906.md, src/language-html/syntax-attribute.js, tests/format/html/attributes/__snapshots__/jsfmt.spec.js.snap, tests/format/html/attributes/class-colon.html
Allow colon as class prefix. This is useful when working with tailwind and various breakpoints.
=> Allow `:` as class prefix-delimeter

changelog_unreleased/typescript/10940.md, src/language-js/print/function.js, tests/format/typescript/argument-expansion/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/argument-expansion/arrow-with-return-type.ts
=> Fix incorrectly wrapped arrow functions with return types

jest.config.js, scripts/tools/eslint-plugin-prettier-internal-rules/no-identifier-n.js, src/language-js/print/angular.js, src/language-js/print/function.js, src/language-js/print/typescript.js, src/language-js/printer-estree.js, src/language-js/utils.js
- Handle `NG-*` node in `angular.js`
- Rename `printFunctionDeclaration` to `printFunction` to be more correct, it handles expressions too.
- Move `expandArg` logic to `printFunction`
- Rename `printReturnAndThrowArgument` to `printReturnOrThrowArgument`
- Move `returnArgumentHasLeadingComment` from `utils.js` to `function.js`
`returnArgumentHasLeadingComment` should have a better name, because it also checks `throw` argument, but `returnOrThrowArgumentHasLeadingComment` seems too long, any idea? 
=> Minor tweak to js printer

src/language-js/print/literal.js
This workaround was added in #10910, already fixed in babel side.
=> Fix `StringLiteral` print

website/blog/2021-05-09-2.3.0.md
$ symbol before CLI command
- [ x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).
=> Update v2.3 blog post

scripts/tools/eslint-plugin-prettier-internal-rules/directly-loc-start-end.js, scripts/tools/eslint-plugin-prettier-internal-rules/jsx-identifier-case.js, scripts/tools/eslint-plugin-prettier-internal-rules/no-conflicting-comment-check-flags.js, scripts/tools/eslint-plugin-prettier-internal-rules/no-doc-builder-concat.js, scripts/tools/eslint-plugin-prettier-internal-rules/no-empty-flat-contents-for-if-break.js, scripts/tools/eslint-plugin-prettier-internal-rules/no-identifier-n.js, scripts/tools/eslint-plugin-prettier-internal-rules/no-node-comments.js, scripts/tools/eslint-plugin-prettier-internal-rules/no-unnecessary-ast-path-call.js, scripts/tools/eslint-plugin-prettier-internal-rules/prefer-ast-path-each.js, scripts/tools/eslint-plugin-prettier-internal-rules/prefer-indent-if-break.js, scripts/tools/eslint-plugin-prettier-internal-rules/prefer-is-non-empty-array.js, scripts/tools/eslint-plugin-prettier-internal-rules/require-json-extensions.js
The path to `eslint-plugin-prettier-internal-rules` has changed but the URLs haven't all been updated. This PR updates all docs URLs to use the correct path, `scripts/tools/eslint-plugin-prettier-internal-rules`, fixing docs links.
=> Fix docs urls for internal lint rules

package.json, src/language-js/print/function.js, src/main/comments.js, yarn.lock
https://github.com/microsoft/TypeScript/issues/38379 has been fixed, not needed any more. Previous discussion https://github.com/prettier/prettier/pull/8759#discussion_r455937302
=> Remove `@types/node` package

changelog_unreleased/handlebars/10958.md, src/language-handlebars/printer-glimmer.js, tests/format/handlebars/attr-node/__snapshots__/jsfmt.spec.js.snap, tests/format/handlebars/attr-node/order.hbs
Closes https://github.com/prettier/prettier/issues/10203
=> Preserve attributes order for element node

changelog_unreleased/cli/10924.md, src/language-yaml/embed.js, src/language-yaml/index.js, tests/integration/__tests__/__snapshots__/support-info.js.snap, tests/integration/__tests__/with-parser-inference.js
I'm now preparing for the 2.3.1 release. Some new feature implementations have already been included in the main branch. These features should be released as minor, not as a patch. So this PR reverts commits that adds these features for now.
I'll revert this PR after the release of 2.3.1.
**new features that is reverted by this PR:**
- https://github.com/prettier/prettier/commit/f8cb7857587527267c4cff06631415ced3f06a89
=> Revert features for minor

scripts/check-deps.mjs
The `check-deps` script is failing because of a mistake from #10867 in creating the URL to read `package.json`. This failure can be [seen in CI runs of lint:deps](https://github.com/prettier/prettier/runs/2572587849#step:5:6), but for whatever reason, it is not causing the `Lint` action to fail.
This PR [allows the script to pass](https://github.com/prettier/prettier/pull/11038/checks?check_run_id=2767164627#step:5:5).
=> Fix lint:deps script

changelog_unreleased/cli/11000.md, src/cli/expand-patterns.js, tests/integration/__tests__/__snapshots__/patterns-dirs.js.snap, tests/integration/__tests__/patterns-dirs.js
=> CLI: Fix failure on dir with trailing slash

changelog_unreleased/flow/11051.md, src/language-js/needs-parens.js, tests/format/flow/indexed-access/__snapshots__/jsfmt.spec.js.snap, tests/format/flow/indexed-access/indexed-access.js, tests/format/flow/optional-indexed-access/__snapshots__/jsfmt.spec.js.snap, tests/format/flow/optional-indexed-access/optional-indexed-access.js
Previously, we were not adding parens to the `objectType` of a `IndexedAccess`/`OptionalIndexedAccess` in the appropriate situations. Now we do. 
E.g. previous output for 
```
type A = (T & S)['bar'];
type B = (T | S)['bar'];
type C = (?T)['bar'];
type D = (typeof x)['bar'];
type E = (string => void)['bar'];
```
would be
```
type A = T & S["bar"];
type B = T | S["bar"];
type C = ?T["bar"];
type D = typeof x["bar"];
type E = (string) => void["bar"];
```
now it's
```
type A = (T & S)["bar"];
type B = (T | S)["bar"];
type C = (?T)["bar"];
type D = (typeof x)["bar"];
type E = ((string) => void)["bar"];
```
=> Fix handling of parenthesis with Flow's {Optional}IndexedAccess

.editorconfig
Keep editor from removing trailing whitespace in format test files and snapshots.
Configures editorconfig to avoid trimming EOL whitespace in format test files and snapshots.
This change was originally proposed downstream in https://github.com/brodybits/prettierx/pull/549 but was determined to be a better candidate for an upstream change. (cc @brodybits)
=> Keep editor from removing trailing whitespace in format test files and snapshots

scripts/changelog-for-patch.mjs, scripts/draft-blog-post.mjs, scripts/release/steps/update-changelog.js, scripts/utils/changelog.mjs
- Add `./scripts/changelog-for-patch.mjs`
- Extract common functions to `./scripts/utils/changelog`
- Use `changelog-for-patch.mjs` from release script
=> Add a script that generates changelog for patch release

website/package.json
There was a warning info printed 
```text
WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value.
Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/
```
The script for development was fixed in  https://github.com/prettier/prettier/commit/2bb6cc4bf8fe0f09568d85ebce4e42ea899d5a69
=> Website: Add `mode` to webpack command

src/language-html/ast.js, src/language-html/print-preprocess.js
I have reduced the number of times the AST is copied in `src\language-html\print-preprocess.js`.
The basic change policy is the same as in [this issue comment](https://github.com/prettier/prettier/issues/4776#issuecomment-741460246).
Previously, the preprocess kept copying the AST for each process.
My change is to copy the AST once and make changes as needed.
The equivalence of this change is explained in [this pull request](https://github.com/ryoha000/prettier/pull/4).
In the following test case, the output of the changed part has changed (the test itself passes without any change).
However, as the pull request states, it is consistent with the rest of the test cases and I think it is rather correct.
- tests\format\html\basics\issue-9368.html
- tests\format\html\basics\issue-9368-2.html …
=> Reduced the copying of AST done in the html preprocess

src/language-js/parser-espree.js, tsconfig.json, types/espree/index.d.ts
Adds [espree](https://github.com/eslint/espree)'s type definition.
Because:
- espree has no type definitions (ref: https://github.com/eslint/espree/pull/321#issuecomment-282048994)
- Also there are no type definitions in DefinitelyTyped for espree.
=> Adds type definitions for espree 8.0

.github/workflows/dev-package-test.yml, .github/workflows/dev-test.yml, .github/workflows/lint.yml, .github/workflows/prod-test.yml, cspell.json
Fixes workflow files according to [actionlint](https://github.com/rhysd/actionlint).
actionlint says:
```
this expression must be contained within ${{ }} like `if: ${{ ... }}` since it contains operator ".".
see https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idif for more details
```
I want to install and use actionlint, but it is written in Go and not distributed with npm. I'm trying to figure out how to use it from Node.js, but just fix for now.
=> Fix workflow files according to actionlint

website/yarn.lock
Fixes warning
```console
$ concurrently "docusaurus-start" "webpack --mode=development --watch"
[0] Browserslist: caniuse-lite is outdated. Please run:
[0] npx browserslist@latest --update-db
[0]
[0] Why you should do it regularly:
[0] https://github.com/browserslist/browserslist#browsers-data-updating
[1] Browserslist: caniuse-lite is outdated. Please run:
[1] npx browserslist@latest --update-db
```
=> Regenerate `yarn.lock` file for website

.github/workflows/dev-package-test.yml, .github/workflows/dev-test.yml, .github/workflows/eslint-rules.yml, .github/workflows/lint.yml, .github/workflows/prod-test.yml
To cache dependencies, it's much simpler now. The installation step is actually fast, normally just seconds, bring this up because mentioned in  https://github.com/prettier/prettier/pull/11241 CI installation can be faster.
=> Use setup-node cache yarn dependencies

scripts/build/bundler.mjs
This should be introduced by #11261.
`rollup-plugin-polyfill-node` commit https://github.com/snowpackjs/rollup-plugin-polyfill-node/commit/e4776e47224ca905060ee6c519b5ef62627e8d36
=> Fix a rollup warning

package.json, yarn.lock
update to node-actionlint to 1.1 that uses actionlint 1.5.
=> Update node-actionlint to 1.1

src/language-js/parse/babel.js
=> Use regex instead of two `includes` methods

src/common/parser-create-error.js, src/common/resolve.js, src/common/util.js, src/document/doc-builders.js, src/index.js, src/language-html/ast.js, src/language-html/parser-html.js, src/language-js/comments.js, src/language-js/parse/babel.js, src/language-js/parse/json.js, src/language-markdown/printer-markdown.js
Use [`@ts-expect-error`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#-ts-expect-error-comments).
=> Use `@ts-expect-error` instead of `@ts-ignore`

changelog_unreleased/less/11343.md, package.json, tests/format/less/interpolation/__snapshots__/jsfmt.spec.js.snap, tests/format/less/interpolation/interpolation.less, tests/format/less/interpolation/jsfmt.spec.js, yarn.lock
Targeting `next` branch.
Changelog https://github.com/shellscape/postcss-less/releases/tag/v5.0.0
=> Update `postcss-less` from v4 to v5

src/language-html/printer-html.js
Fixes https://github.com/prettier/prettier/pull/11425#issuecomment-908296566
=> Reduce ternary operator in `printer-html.js` (after #11425)

.github/workflows/dev-package-test.yml, tests/format/js/babel-plugins/__snapshots__/jsfmt.spec.js.snap, tests/format/js/babel-plugins/jsfmt.spec.js, tests/format/js/binary-expressions/__snapshots__/jsfmt.spec.js.snap, tests/format/js/binary-expressions/jsfmt.spec.js, tests/format/js/class-static-block/__snapshots__/jsfmt.spec.js.snap, tests/format/js/class-static-block/jsfmt.spec.js, yarn.lock
Address https://github.com/prettier/prettier/pull/11454#issuecomment-913657122
=> Regenerate lockfile

.eslintrc.js, .github/workflows/release-script-test.yml, jest.config.js, package.json, scripts/release/__tests__/foo.spec.js, scripts/release/__tests__/steps/validate-new-version.spec.js, scripts/release/package.json, scripts/release/yarn.lock, yarn.lock
Adds tests for release script.
This PR adds test for one step (`validate-new-version`). In other PR, I'll add tests for other steps.
=> Add tests for release script

src/language-js/parse/babel.js, src/language-js/print/ternary.js
=> Fix comments

.github/workflows/dev-test.yml, .github/workflows/prod-test.yml
Our CI fails by using 16.9.0.
Maybe https://github.com/nodejs/node/issues/40030
=> Use node 16.8.0 for GitHub Actions

website/blog/2020-03-21-2.0.0.md
=> Fix the `trailingComma` value from `"always"` to `"all"` in v2 blog post

scripts/release/__tests__/setup.js, scripts/release/__tests__/steps/publish-to-npm.spec.js, scripts/release/get-formatted-date.js, scripts/release/jest.config.js, scripts/release/package.json, scripts/release/steps/publish-to-npm.js, scripts/release/steps/update-changelog.js, scripts/release/utils.js, scripts/release/yarn.lock
Currently, release script outputs an URL to create release on GitHub. Like `https://github.com/prettier/prettier/releases/new?tag=2.4.0`.  This is very useful. 
However we can add more info to the URL as query parameters. (ref: https://docs.github.com/en/repositories/releasing-projects-on-github/automation-for-release-forms-with-query-parameters)
=> Adds more info for release URL

.github/workflows/dev-test.yml, .github/workflows/prod-test.yml
Node.js 16.9.1 is released https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V16.md#16.9.1
Revert #11470
=> Revert workaround for node 16.9

docs/precommit.md
Fix instructions to install lint-staged, as per https://github.com/okonet/lint-staged#installation-and-setup
The previous ones were not working.
- minor documentation fix
=> fix(docs): lint-staged install instructions

changelog_unreleased/scss/11487.md, src/language-css/printer-postcss.js, tests/format/scss/quotes/__snapshots__/jsfmt.spec.js.snap, tests/format/scss/quotes/quotes.scss
=> Fix wildcard syntax in `@forward` (#11482)

src/language-js/print/binaryish.js
Alternative for #11532, use "early return" to reduce indent level.
Closes #11532
=> Minor refactor

src/language-js/needs-parens.js
`PipelineTopicExpression` and `PipelinePrimaryTopicReference` are nodes for Smart Pipeline Operator.  But now we have not supported it ([blog](https://prettier.io/blog/2021/09/09/2.4.0.html#support-hack-style-pipeline-proposal-11335httpsgithubcomprettierprettierpull11335-by-sosukesuzukihttpsgithubcomsosukesuzuki)).
=> Remove `PipelineTopicExpression` and `PipelinePrimaryTopicReference`

src/common/util.js, src/language-handlebars/printer-glimmer.js, src/language-js/print/jsx.js
Later on we will be able to use it in HTML's printer (https://github.com/prettier/prettier/pull/11559#discussion_r713525169).
The changes to the `getPreferredQuote`'s arguments and return statement would be possible because it is not exposed (as it is not in the file `src/common/util-shared.js`).
The review should be easier commit by commit.
=> Refactor and use `getPreferredQuote` in both jsx and handlebars printers

package.json, src/language-js/needs-parens.js, src/language-js/parse/babel.js, src/language-js/parse/postprocess.js, src/language-js/print/binaryish.js, src/language-js/utils.js, tests/format/js/pipeline-operator/__snapshots__/jsfmt.spec.js.snap, tests/format/misc/errors/js/hack-pipeline/__snapshots__/jsfmt.spec.js.snap, yarn.lock
Hack-style pipeline operators are right-associative. `babel/parser@7.15.5` treats it as left-associative, `babel/parser@7.15.6` treats it as right-associative.
ref: https://github.com/babel/babel/pull/13668
ref: https://github.com/babel/babel/pull/13668#issuecomment-896965830
Clsoes #11540
=> Support right precedence hack-style pipeline

.eslintrc.js, tests/integration/__tests__/infer-parser.js, tests/integration/__tests__/loglevel.js, tests/integration/__tests__/parser-api.js, tests/integration/__tests__/third-party.js, tests/integration/__tests__/util-shared.js, tests/integration/__tests__/with-parser-inference.js, tests/integration/runPrettier.js
~~Base on #11616~~
Enables [jest/prefer-to-be](https://github.com/jest-community/eslint-plugin-jest/blob/HEAD/docs/rules/prefer-to-be.md).
=> Enable `jest/prefer-to-be`

.editorconfig
When EditorConfig is enabled in your text editor, you cannot use line breaking by adding two whitespaces at the end of lines in Markdown files in the project root or `changelog_unreleased`.
=> [editorconfig] Turn off trim_trailing_whitespace in Markdown in root or changelog_unreleased

changelog_unreleased/typescript/11721.md, src/language-js/index.js, tests/integration/__tests__/__snapshots__/support-info.js.snap
Partial of #11600
See https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-beta/#new-file-extensions for details.
=> Handle TypeScript 4.5 new file extensions `.mts` and `.cts`

changelog_unreleased/typescript/11884.md, src/language-js/print/type-annotation.js, tests/format/typescript/tuple/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/tuple/jsfmt.spec.js, tests/format/typescript/tuple/trailing-comma-for-empty-tuples.ts
=> Improve formatting for empty tuple types

docs/configuration.md, docs/options.md
Add documentation for editorconfig to the "options" and "configuration" sections.
#2760 initially added a paragraph to configuration, but this was reverted in #3213, and the reintroduction in #3255 only added to the "API" and "CLI" sections.
This change copies the paragraph from API's `resolveConfig` to the bottom of "configuration", and adds sentences to the relevant parts of "options" to increase discoverability of this feature.
Fixes #8044.
=> docs: add docs for editorconfig to configuration and options

changelog_unreleased/handlebars/11899.md, src/language-handlebars/utils.js, tests/format/handlebars/basics/__snapshots__/jsfmt.spec.js.snap, tests/format/handlebars/basics/named-block.hbs
=> [handlebars] Named blocks can't be self closing

src/language-css/parser-postcss.js, src/language-html/parser-html.js, src/language-js/parse/espree.js, src/language-js/parse/flow.js, src/language-js/parse/meriyah.js, src/language-js/parse/typescript.js, tests/integration/__tests__/parser-api.js
=> Make `options` argument in parsers optional

changelog_unreleased/graphql/11901.md, src/language-graphql/printer-graphql.js, tests/format/graphql/schema/__snapshots__/jsfmt.spec.js.snap, tests/format/graphql/schema/schema.graphql
This change adds printing descriptions which are attached to a graphql schema definition node. Currently these are omitted.
[Playground reproduction / example](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdNGDKYAWcC2AhgCJwBmAllBTBdAAQAmcAzmAE4UAOtDFL9ADYQWMdOLRQ2eIvWCoo9egEcArnHYBPJPQCK6rQoC+C0xnQB5AEYArOGBgAVTVzilK1XouZtOPOor89FycsHCMEuKwLnB6BppyCkqEOgCSsMYKIAA0IBD+0CzIoITs7BAA7gAKpQhFKISCFYSaRblW7IRgANZwMJiE+HAAMlRwyGSNLHDtnT19mFxdVADmyDDs6rkEVuHMjMOEUCuqhCtwAGIQ7EQwtMfIIISqMBA5IDgw+IIA6jg0rCWYDgmDqNAoADcaJpHmAWG0QFRpuwYFVOisiBMpjMQDYWAAPTCrQRwfQQeBYwTTXJLdjIx4rTpcHDKQTvEJUGA-CiMGA4ZAADgADDTytMfkzHiFWBoIeNcmpyXA0fl6k8WABaKBwcLhd7sOBqCgGtFnTFISZUnHTfAUdaba3E0mqJWU6kgGCEKzc3n8pAAJlyG0IFEEqwAwhB8OaQKwAKzvVTTRxe+qW90Q9TpZiwbB+GAAQSgjEwME0JLdcCMRiAA) …
=> Print descriptions on graphql schema definition nodes

changelog_unreleased/html/6644.md, docs/options.md, src/common/common-options.js, tests/integration/__tests__/__snapshots__/support-info.js.snap
Added changelog and updated the "first available in" version for the new `singleAttributePerLine` option.
=> Added changelog and updated the "first available in" version for singleAttributePerLine

tests/integration/__tests__/early-exit.js, tests/integration/__tests__/loglevel.js, tests/integration/__tests__/piped-output.js, tests/integration/runPrettier.js
=> Test: Make `runPrettier` result "thenable"

docs/vim.md, website/versioned_docs/version-stable/vim.md
Recently addressed in sbdchd/neoformat#363, this calls out the necessary steps to take to ensure that Neoformat uses the locally-installed `prettier`.
=> Update instructions for configuring Neoformat

changelog_unreleased/javascript/11992.md, src/language-js/utils.js, tests/format/js/test-declarations/__snapshots__/jsfmt.spec.js.snap, tests/format/js/test-declarations/angular_waitForAsync.js
Would close #11991.
This PR would recognize the usage of `waitForAsync` as a valid test statement.`waitForAsync` replaces `async` in Angular 12.
=> recognize waitForAsync as test-statement in Angular

changelog_unreleased/flow/12009.md, src/language-js/print/flow.js, tests/format/flow/declare-class/__snapshots__/jsfmt.spec.js.snap, tests/format/flow/declare-class/indexer.js, tests/format/flow/declare-class/jsfmt.spec.js
Fix Flow's class declaration's  indexer formatting:
```jsx
// Input
declare class A {
static [string]: boolean;
}
// Before:
declare class A {
[string]: boolean;
}
// After:
declare class A {
static [string]: boolean;
}
```
=> Fix Flow's class declaration's  indexer formatting

.eslintrc.js, scripts/tools/eslint-plugin-prettier-internal-rules/index.js, scripts/tools/eslint-plugin-prettier-internal-rules/no-legacy-format-test-fixtures.js, scripts/tools/eslint-plugin-prettier-internal-rules/test.js
New test from `main` branch can run this rule to auto-fix to the new format (changed in #11902).
=> Add internal ESLint rule `no-legacy-format-test-fixtures`

src/language-html/ast.js, src/language-html/clean.js, src/language-html/parser-html.js, src/language-html/print-preprocess.js, src/language-html/utils.js, src/main/comments.js
I reduced copying AST like #11108. 
On [this case](https://github.com/prettier/prettier/issues/4776#issuecomment-740791694), the result of `yarn run perf:benchmark` became about 8.6x faster.
before
```
[debug] resolve config from 'test.html'
[debug] loaded options `{"useTabs":false,"tabWidth":2,"endOfLine":"lf"}`
[debug] applied config-precedence (cli-override): {"endOfLine":"lf","tabWidth":2,"useTabs":false}
[debug] '--debug-benchmark' option found, measuring formatWithCursor with 'benchmark' module.
[debug] '--debug-benchmark' measurements for formatWithCursor: {
[debug]   "benchmark": "format x 0.80 ops/sec ±3.60% (7 runs sampled)",
[debug]   "hz": 0.8011225145560241,
[debug]   "ms": 1248.2485285714286
[debug] }
```
after
```
[debug] resolve config from 'test.html'
[debug] loaded …
```
=> Improved performance with large HTML files

changelog_unreleased/javascript/12088.md, src/language-js/print/jsx.js, tests/format/jsx/jsx/__snapshots__/jsfmt.spec.js.snap, tests/format/jsx/jsx/await.js
This change inlines `await` expressions when inside JSX:
```jsx
// Before:
{
await Promise.all(
someLongExpression
)
}
// After:
{await Promise.all(
someLongExpression
)}
```
- ~(If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).~
=> Inline `await` expressions in JSX

package.json, yarn.lock
Release  note https://github.com/shellscape/postcss-less/releases/tag/v6.0.0
=> Update `postcss-less` to v6

docs/options.md, website/versioned_docs/version-stable/options.md
I was trying to understand the proseWrap options, and the existing documentation was very confusing to me. Because `"never"` was described as "opt-out", I thought it meant it would be opting out of Prettier formatting - which is very much not the case. I think it's also unclear what it means to "wrap as-is" - if you're just leaving it as-is, you're not actually doing any _wrapping_ one way or the other - you're just leaving it as-is.
Trying to figure out what "_wrap_ as-is" meant, I thought maybe there was some sort of algorithm where it would not wrap really long lines, but would re-wrap lines that were under or maybe just a little over `printWidth`, so as to wrap blocks that were "supposed" to be wrapped, but not ones that weren't. But it appears that the default `"preserve"` option is …
=> Clarify documentation around proseWrap

scripts/build/config.mjs
```text
8756 -rw-r--r-- 1 fisker None 8965844 Jan 26 20:48 parser-typescript.main.js
3488 -rw-r--r-- 1 fisker None 3569944 Jan 26 20:49 parser-typescript.main.min.js
8712 -rw-r--r-- 1 fisker None 8917563 Jan 26 20:47 parser-typescript.working.js
3464 -rw-r--r-- 1 fisker None 3546949 Jan 26 20:46 parser-typescript.working.min.js
```
~25k
esbuild is so stupid, it leaves uncalled functions there, so I have to remove them one by one.
=> Remove useless `TypeScriptServices` from `parser-typescript.js`

scripts/build/README.md, scripts/build/build.mjs, scripts/build/bundler.mjs
Added `--save-as`, allow mutiple `--file`, the CLI output changed.
```text
Building packages
index.js...............................................................   DONE
doc.js.................................................................   DONE
esm/doc.mjs..........................................................   DONE
standalone.js..........................................................   DONE
esm/standalone.mjs...................................................   DONE
bin-prettier.js........................................................   DONE
third-party.js.........................................................   DONE
parser-babel.js........................................................   DONE
esm/parser-babel.mjs.................................................   DONE …
```
=> Update build script

src/common/util.js, src/language-js/loc.js, src/language-js/parse/babel.js, src/language-js/parse/postprocess/index.js, src/language-js/pragma.js, src/language-js/utils/get-shebang.js, src/utils/is-non-empty-array.js
Reduce bundle size of `parser-espree.js` and `parser-meriyah.js` by 39kb
**Before:**
```
$ node ./scripts/build/build.mjs --file=parser-meriyah.js --file=parser-espree.js --file=parser-babel.js --print-size
parser-babel.js.................................................338 kB    DONE  
parser-espree.js................................................199 kB    DONE  
parser-meriyah.js...............................................202 kB    DONE  
```
**After:**
```
$ node ./scripts/build/build.mjs --file=parser-meriyah.js --file=parser-espree.js --file=parser-babel.js --print-size
parser-babel.js.................................................338 kB    DONE  
parser-espree.js................................................160 kB    DONE …
```
=> Reduce JS parsers bundle size 2

cspell.json, package.json, scripts/tools/eslint-plugin-prettier-internal-rules/test.js
Use `--dot` and `--gitignore`  flags, https://github.com/streetsidesoftware/cspell/tree/main/packages/cspell
Before: 
```text
CSpell: Files checked: 1774, Issues found: 0 in 0 files
```
After
```text
CSpell: Files checked: 1837, Issues found: 0 in 0 files
```
Don't know why more files matched. Some dot files in dirs matched?
=> Update cSpell config

src/cli/format.js, src/main/core.js
```text
520 -rw-r--r-- 1 fisker None 529175 Jan 27 10:45 main.js
500 -rw-r--r-- 1 fisker None 509950 Jan 27 10:46 working.js
```
~ 20k
```text
440 -rwxr-xr-x 1 fisker None 449592 Jan 27 11:11 after.js
476 -rwxr-xr-x 1 fisker None 486907 Jan 27 11:09 before.js
```
~ 36k
=> Reduce bundled size of `diff` package

scripts/build/config.mjs
```diff
yarn build --print-size --file=parser-yaml.js
- parser-yaml.js..................................................142 kB    DONE
+ parser-yaml.js..................................................130 kB    DONE
```
=> Replace `tslib` entry when bundling `parser-yaml.js`

src/common/util.js, src/language-js/clean.js, src/language-js/comments.js, src/language-js/loc.js, src/language-js/parse/babel.js, src/language-js/parse/postprocess/index.js, src/language-js/pragma.js, src/language-js/print/comment.js, src/language-js/print/ternary.js, src/language-js/print/typescript.js, src/language-js/printer-estree.js, src/language-js/utils/get-shebang.js, src/language-js/utils/index.js, src/language-js/utils/is-block-comment.js, src/language-js/utils/is-ts-keyword-type.js, src/language-js/utils/is-type-cast-comment.js, src/utils/is-non-empty-array.js
Address https://github.com/prettier/prettier/pull/12164#discussion_r793308438
=> refactor: Use default export for some utils

src/common/util.js, src/document/doc-printer.js, src/document/doc-utils.js, src/utils/get-string-width.js
Reduce bundle size of `doc.js` by 113.9 kb
Address https://github.com/prettier/prettier/pull/12168#issuecomment-1022946262
**Before:**
```
$ node ./scripts/build/build.mjs --file=doc.js --print-size --report
doc.js..........................................................178 kB    DONE  
```
**After:**
```
$ node ./scripts/build/build.mjs --file=doc.js --print-size --report
doc.js.........................................................63.1 kB    DONE  
```
=> Reduce bundle size of `doc.js`

scripts/build/config.mjs
Reduce bundle size of `parser-espree.js` by 6kb
**Before:**
```
$ node ./scripts/build/build.mjs --file=parser-espree.js --print-size
parser-espree.js................................................160 kB    DONE  
```
**After:**
```
$ node ./scripts/build/build.mjs --file=parser-espree.js --print-size
parser-espree.js................................................154 kB    DONE  
```
=> Remove unused API from `espree` at build time

scripts/build/config.mjs
```diff
$ node ./scripts/build/build.mjs --file=parser-markdown.js --print-size
- parser-markdown.js..............................................173 kB    DONE
+ parser-markdown.js..............................................163 kB    DONE
```
=> Reduce size of `inherits` module in `parser-markdown.js`

scripts/build/bundler.mjs, scripts/build/config.mjs
We didn't ship ESM version `doc.js` in last version https://unpkg.com/browse/prettier@2.5.1/esm/ , this is a mistake during build script refactoring .
=> Remove `esm/doc.mjs`

src/cli/options/get-options-for-file.js, src/cli/options/parse-cli-arguments.js, src/main/options-normalizer.js
Closes #12146, instead of removing colors, pass `chalk` from the cli.
```diff
yarn build --no-babel --print-size
- index.js.......................................................1.61 MB    DONE
+ index.js.......................................................1.56 MB    DONE
- standalone.js...................................................499 kB    DONE
+ standalone.js...................................................477 kB    DONE
-  esm/standalone.mjs............................................499 kB    DONE
+  esm/standalone.mjs............................................476 kB    DONE
- bin-prettier.js.................................................438 kB    DONE
+ bin-prettier.js.................................................439 kB    DONE
``` …
=> Remove `chalk` from `standalone.js`

src/language-html/embed.js, src/language-html/parser-html.js, src/language-html/print-preprocess.js, src/language-html/print/children.js, src/language-html/print/element.js, src/language-html/print/tag.js, src/language-html/printer-html.js, src/language-html/utils/array-to-map.js, src/language-html/utils/html-elements-attributes.js, src/language-html/utils/html-tag-names.js, src/language-html/utils/index.js, src/language-html/utils/is-unknown-namespace.js, src/language-html/utils/map-object.js
**Before:**
```
$ node ./scripts/build/build.mjs --file=parser-html.js --print-size
parser-html.js..................................................179 kB    DONE  
```
**After:**
```
$ node ./scripts/build/build.mjs --file=parser-html.js --print-size
parser-html.js..................................................156 kB    DONE  
```
=> Reduce bundle size of `parser-html.js`

scripts/build/esbuild-plugins/visualizer.mjs
Not very pretty, but more useful
<details>
<summary>Before</summary>
```text
parser-babel.js........................................................
dist/parser-babel.js                                           583.8kb  100.0%
├ node_modules/@babel/parser/lib/index.js                     491.5kb   84.2%
├ src/common/util.js                                           11.5kb    2.0%
├ node_modules/emoji-regex/index.js                            10.2kb    1.7%
├ src/main/core-options.js                                      8.1kb    1.4%
├ node_modules/semver/classes/semver.js                         7.2kb    1.2%
├ src/language-js/parse/babel.js                                5.8kb    1.0%
├ node_modules/outdent/lib/index.js                             4.9kb    0.8%
├ …
```
=> Build: Verbose text report

scripts/build/esbuild-plugins/umd.mjs
For text transform should use `.transform()` instead of `.build()`
=> Build: Minor tweak to the umd plugin

src/main/options.js, src/utils/get-interpreter.js
```diff
$ node ./scripts/build/build.mjs --file=standalone.js --print-size
Building packages
- standalone.js...................................................487 kB    DONE
+ standalone.js...................................................484 kB    DONE
```
Not too much, but removed `fs` shim and `n-readlines` module.
=> Exclude `getInterpreter` from 'standalone.js'

changelog_unreleased/javascript/12177.md, src/language-js/comments.js, src/language-js/printer-estree.js, tests/format/js/switch/__snapshots__/jsfmt.spec.js.snap, tests/format/js/switch/comments.js
Fixes #12108 
`default:` doesn't have a node we can attach the comments to so it requires special handling
=> Keep comments of `default` cases in the same line of the case

scripts/build/bundler.mjs
=> Build: Remove `define` on second run

changelog_unreleased/javascript/12185.md, src/language-js/comments.js, tests/format/typescript/comments/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/comments/abstract_methods.ts, tests/format/typescript/comments/methods.ts
Fixes #11145
When handling comments between the method name and the arguments (i.e. `foo /* comment */ ()`) it was mistakenly affecting cases of `foo(/* comment */ arg)`. This restricts the handling of that case, and let the comments in arguments follow the same path of regular methods.
=> Fix comment in abstract methods

src/common/util.js, src/language-js/parse/babel.js, src/language-js/parse/json.js, src/utils/text/get-next-non-space-non-comment-character-index-with-start-index.js, src/utils/text/skip-inline-comment.js, src/utils/text/skip-newline.js, src/utils/text/skip-trailing-comment.js, src/utils/text/skip.js
Reduce `parser-babel.js` by 35kb.
**Before:**
```
$ node ./scripts/build/build.mjs --print-size --report --file=parser-babel.js
parser-babel.js.................................................337 kB    DONE  
```
**After:**
```
$ node ./scripts/build/build.mjs --print-size --report --file=parser-babel.js
parser-babel.js.................................................302 kB    DONE  
```
=> Reduce bundle size of `parser-babel.js`

scripts/build-website.mjs, scripts/build/README.md, scripts/build/build.mjs, scripts/release/steps/generate-bundles.js
I noticed that when running `yarn build`, it doesn't fail when `rimraf` can't remove `dist` dir, this may cause problems when doing release, let's add an explicit flag to ensure an empty `dist`.
I also added `--print-size` to the release script, so we can notice obvious unexpected file size when do release.
=> Build: Add `--clean` flag

changelog_unreleased/css/12210.md, src/language-css/printer-postcss.js, tests/format/css/atrule/__snapshots__/jsfmt.spec.js.snap, tests/format/css/parens/__snapshots__/jsfmt.spec.js.snap, tests/format/css/parens/empty-lines.css
Related to #12053, will improve the comment placement from the example in another PR
=> Preserve empty lines in CSS/SCSS paren groups

changelog_unreleased/scss/12213.md, src/language-css/printer-postcss.js, tests/format/css/atrule/__snapshots__/jsfmt.spec.js.snap, tests/format/css/atrule/mixin.css
Fixes #10291, this is an improvement on #8707
What happens here is that when there's a newline before the closing `)`, the parser reports the `endOffset` of that close group is equal to `startOffset + 1`, which is why the code using `locEnd(node.end) - 1` worked. But when there's no newline the parser reports `startOffset == endOffset`, so using `locEnd(node.end) - 1` gets part of the content of the selector.
The fix is to simply use `locStart(node.end)` which works and is also what we really want (get the slice of original text until the *start* of the close group)
=> Fix printing of CSS selector() function

package.json, scripts/build-website.mjs, scripts/clean-changelog-unreleased.mjs, scripts/sync-flow-tests.js, src/common/load-plugins.js, tests/config/require-standalone.js, tests/integration/__tests__/bundle.js, yarn.lock
There is already fast-glob used in src/cli/expand-patterns.js
Here I migrate everywhere to it from globby which is a thin wrapper with
a couple of unused here features.
```
du -ck dist
```
before: 17280 kB
after: 17260 kB
=> Replace globby with fast-glob

scripts/build/bundler.mjs, scripts/build/esbuild-plugins/replace-module.mjs
Main purpose is to make `replace-module` work better with `@esbuild-plugins/node-modules-polyfill`.
=> Improve build script

.prettierignore, cspell.json, scripts/vendors/bundle-vendors.mjs, scripts/vendors/esbuild-plugin-ts-nocheck.mjs, vendors/mem.js, vendors/string-width.js
Tests on Node.js 10(prod), we cannot use `"imports"` in `package.json`. So we should use directly `require` from `/vendors/*.js`. But, TS type checker warns to the `require`.
So this PR adds esbuild plugin to add `@ts-nocheck` annotation for vendors.
=> Add an esbuild plugin to add `@ts-nocheck` annotation for vendors

jest.config.js, package.json, scripts/vendors/bundle-vendors.mjs, scripts/vendors/esbuild-plugin-ts-nocheck.mjs, src/common/load-plugins.js, src/config/resolve-config-editorconfig.js, src/config/resolve-config.js, src/utils/get-string-width.js, vendors/mem.d.ts, vendors/mem.js, vendors/string-width.d.ts, vendors/string-width.js, vendors/types.d.ts, yarn.lock
This includes the `vendors` directory in the package when installing from Github `(i.e. npm install prettier/prettier`).
Previously, Prettier would not be able to run because npm removes everything not listed in `files` when installing from GitHub. I’ve confirmed on a local project that installing Prettier from this branch does work correctly.
Closes #12253.
- [N/A] I’ve added tests to confirm my change works.
=> Include vendors/ when installing from GitHub

docs/plugins.md
I updated the plugin docs to reflect the changes I made in my previous PR (#11248). I did some cleanup to the wording/ordering of some things as well. For example, generally `--plugin` and `--plugin-search-dir` are mentioned in that order. I made that consistent throughout the rest of the page.
=> Update plugin docs

changelog_unreleased/javascript/12268.md, src/language-js/comments.js, tests/format/flow/comments/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/comments/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/comments/type_literals.ts
While fixing #11521 I noticed this weird behavior introduced in #1214:
**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACACgJwgwGdsBebAekuwAoARAS2IwEMYwALAo0gMmwBlGOzg8SASgDc2AOoAJAJrZ6AeQByAcgAq2RaoCqc1QCUA0tgBiAGVWyAhI6dOAOlGzZgbjx+a4ANqxojFAA5kjYAEYQEP5wrFDe2AC+Um4gADQgRDCM0MTIoKz4hADuuMUIBSis-qVBBVmR+KxgANZwMIKsALZw1iFwyABmtcRwTS3tnYJsYCGhyDD4AK4TIHA9kXAAJju71gmhK6yhcJYQ+D3suWHIIKwrMBCZIJwwPf6ynIzwLK1wQRVX6MABuvzQ9zAxEaIBC43wMAIp2uIzG6wAVsQAB6CBZxACKKwg8DR-nGWTY+AR92G-ggpVeGHwIRgskYOxgnGQAA4AAyUwjjWQtDD3ZlwBGgoZZACOxPg4mqD2IAFooHBdrtXvg4PLGLrkaFUUhRuT1uMeowlqsLfi4ESSUNTeisiJIuzOdykAAmN0tRj+BYAYQgPRNG2IAFZXitxtpWJFqmaKSBQWsAJJQfawQRgFkYGAAQWzwjQcTJ42SySAA)
```sh
--parser flow
```
**Input:**
```jsx
type Props = // (DispatchProps & …
```
=> Improve printing of comments in type aliases

package.json, src/config/resolve-config.js, yarn.lock
Micromatch already used inside fast-glob. It makes more sense to reuse
it. Though its behaviour slightly different I found a way to match
minimatch.
```
du -ck dist
```
before: 17260 kB
after: 17232
=> Replace `minimatch` with `micromatch`

cspell.json, docs/plugins.md
Adding a link to our plugin for [JSONata language](https://jsonata.org/) to the plugins page.
=> Add prettier-plugin-jsonata to the Plugins page in docs

package.json, yarn.lock
https://github.com/chalk/chalk/releases/tag/v5.0.0
`bin-prettier.js` size reduced ~34KB
=> Update `chalk` to v5

package.json, yarn.lock
https://github.com/sindresorhus/escape-string-regexp/releases/tag/v5.0.0
=> Update `escape-string-regexp` to v5

.github/workflows/release-script-test.yml, .github/workflows/validate-vendor-versions.yml
> We removed deprecated version input (https://github.com/actions/setup-node/pull/424). Please use node-version input instead.
https://github.com/actions/setup-node/releases/tag/v3.0.0
=> CI: Use `node-version` instead of deprecated `version`

scripts/build/config.mjs
The old one may fail because of "content security policy", we already polyfill `globalThis`, so this won't change the bundle size.
=> Build: Use `globalThis` instead of `new Function()`

scripts/build/bundler.mjs
So `esbuild` won't do unnecessary transform on first run, minor improvement.
=> Build: Unset `target` on esbuild first run

scripts/build/config.mjs, scripts/build/shims/parent-module.cjs
Reduce bundled `third-party.js` size a little bit.
=> Replace `parent-module`

scripts/build/config.mjs, src/cli/format.js, src/main/core.js
Lucky we only use one method in `cli.js`, `index.js`, and `standalone.js`, so we can easily replace them.
This didn't change the output.
This reverts #12160
Fixes #12275
=> Fix `diff` package import

.eslintrc.js, scripts/release/utils.js, tests/config/install-prettier.js, tests/config/utils/check-parsers.js, tests/format/js/cursor/jsfmt.spec.js, tests/integration/__tests__/__snapshots__/format.js.snap, tests/integration/__tests__/doc-trim.js, tests/integration/__tests__/format.js, tests/integration/__tests__/ignore-in-subdirectories.js, tests/integration/__tests__/line-suffix-boundary.js, tests/integration/__tests__/load-toml.js, tests/integration/__tests__/stdin-filepath.js, tests/integration/__tests__/with-parser-inference.js
[unicorn/template-indent](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/template-indent.md)
=> Enable `unicorn/template-indent` rule

changelog_unreleased/typescript/12508.md, src/language-js/print/assignment.js, tests/format/flow/assignments/__snapshots__/jsfmt.spec.js.snap, tests/format/flow/assignments/issue-12413.js, tests/format/typescript/assignment/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/assignment/issue-12413.ts
=> Fix non-idempotent formatting of function calls with complex type arguments

changelog_unreleased/misc/12485.md, scripts/build/bundler.mjs, scripts/build/config.mjs, scripts/tools/bundle-test/index.js
Error before this fix https://github.com/prettier/prettier/runs/5654297511?check_suite_focus=true#step:6:38
Fixes #12493
=> Fix error when bundle prettier with webpack

scripts/release/package.json, scripts/release/steps/publish-to-npm.js, scripts/release/yarn.lock
https://github.com/prettier/prettier/pull/12513#issuecomment-1077038547
=> Fix OTP interface in release script

.eslintrc.js, scripts/generate-changelog.mjs, scripts/release/steps/update-changelog.js, scripts/release/utils.js, scripts/vendors/bundle-vendors.mjs
[`unicorn/text-encoding-identifier-case`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/text-encoding-identifier-case.md)
=> Enable `unicorn/text-encoding-identifier-case` rule

docs/integrating-with-linters.md, docs/related-projects.md
TSLint [has been deprecated](https://medium.com/palantir/tslint-in-2019-1a144c2317a9) as of 2019.
I want to remove the TSLint description from docs.
- [integrating-with-linters](https://prettier.io/docs/en/integrating-with-linters.html)
- [related-projects](https://prettier.io/docs/en/related-projects)
=> Remove the TSLint from docs

changelog_unreleased/less/12536.md, src/language-css/printer-postcss.js, tests/format/less/parens/2.less, tests/format/less/parens/__snapshots__/jsfmt.spec.js.snap, tests/format/scss/parens/2.scss, tests/format/scss/parens/__snapshots__/jsfmt.spec.js.snap
Fixes #12504
`value-paren_group` seems  missing location info, we should fix the ast, but I'm going to ignore them for now.
=> Fix less/scss format error

tests/config/format-test.js
Due to limitation of Jest, we have to move `mainParserFormatResult` to `beforeAll`, because [can't use async function in `describe`](https://github.com/facebook/jest/issues/2235), removed some test title, because `Tests cannot be nested.` 
Prepare for #4459
=> Refactor format test to async

src/cli/options/get-options-for-file.js, src/cli/options/normalize-cli-options.js, src/cli/options/parse-cli-arguments.js, tsconfig.json
=> Refactor: Add a wrapped `normalizeCliOptions` version for CLI usage

.eslintrc.js, src/cli/context.js, src/main/options-normalizer.js
- [unicorn/no-unreadable-iife](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-unreadable-iife.md) Idea come from our codebase https://github.com/prettier/prettier/blob/5a6897fe32eafa497f84e235a7ad878397a94951/.eslintrc.js#L44-L45
- [unicorn/prefer-native-coercion-functions](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-native-coercion-functions.md)
=> Enable `unicorn/no-unreadable-iife` and `unicorn/prefer-native-coercion-functions` rule

website/playground/sidebar/SidebarOptions.js
The `groupBy` function added in fa3b95c2e1a3a3351dc1b0168aa2c26f0cc4e9b3 does not support the property name shorthand from lodash.
Fixes #12641
=> Fix `groupBy` usage in playground sidebar

changelog_unreleased/api/12574.md, docs/api.md, src/cli/file-info.js, src/cli/format.js, src/cli/index.js, src/index.js, src/main/core.js, src/standalone.js, tests/config/format-test.js, tests/format/js/cursor/jsfmt.spec.js, tests/integration/__tests__/bundle.js, tests/integration/__tests__/debug-api.js, tests/integration/__tests__/format.js, tests/integration/__tests__/infer-parser.js, tests/integration/__tests__/line-suffix-boundary.js, tests/integration/__tests__/parser-api.js, tests/integration/__tests__/with-parser-inference.js, website/playground/PrettierFormat.js, website/playground/index.js, website/static/worker.js
~We haven't decided yet, just a test.~
Part of https://github.com/prettier/prettier/issues/4459
=> `prettier.{format,formatWithCursor,check}()` are now async

changelog_unreleased/javascript/12746.md, src/language-js/comments.js, tests/format/js/export/__snapshots__/jsfmt.spec.js.snap, tests/format/js/export/blank-line-between-specifiers.js
=> Preserve blank line between export specifiers

src/language-js/comments.js
Just refactor to use optional chaining in `src/language-js/comments.js`
=> Refactor: Use optional chaining in `src/language-js/comments.js`

cspell.json, docs/plugins.md
Add prettier-plugin-glsl to list of community plugins in the docs.
=> Add prettier-plugin-glsl to community plugins

docs/configuration.md
This PR adds an example `.editorconfig` file to the documentation that makes it easy to align your editor to Prettier’s behavior. [See the deploy preview here](https://deploy-preview-12756--prettier.netlify.app/docs/en/next/configuration.html#editorconfig)
- (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
=> Provide an example `.editorconfig`

changelog_unreleased/api/12748.md, docs/plugins.md, src/cli/format.js, src/main/core.js, src/main/multiparser.js, src/main/parser.js, tests/config/format-test.js, tests/config/prettier-plugins/prettier-plugin-async-parser/index.cjs, tests/config/prettier-plugins/prettier-plugin-async-parser/package.json, tests/format/misc/plugins/async-parser/__snapshots__/jsfmt.spec.js.snap, tests/format/misc/plugins/async-parser/async-parser.txt, tests/format/misc/plugins/async-parser/jsfmt.spec.js, tests/format/misc/plugins/embed-async-parser/__snapshots__/jsfmt.spec.js.snap, tests/format/misc/plugins/embed-async-parser/jsfmt.spec.js, tests/format/misc/plugins/embed-async-parser/with-aync-parser-code-block.md, tests/integration/__tests__/debug-api.js, website/static/worker.js
=> Support async parser

changelog_unreleased/api/12574.md, docs/api.md, src/common/create-ignorer.js, src/common/get-file-info.js, src/common/third-party.cjs, src/config/resolve-config-editorconfig.js, src/config/resolve-config.js, src/index.js, src/utils/get-file-content-or-null.js, tests/integration/__tests__/config-resolution.js, tests/integration/__tests__/file-info.js, tests/integration/__tests__/resolve-config-file.js, tests/integration/__tests__/third-party.js, tests/integration/run-prettier.js
Ref: https://github.com/prettier/prettier/issues/4459#issuecomment-982661922
=> Remove `{resolveConfig,resolveConfigFile,getFileInfo}.sync`

src/index.js, src/standalone.js
Maintain `cursorOffset` seems expensive to me, and it's useless in `format()` and `check()`
=> Ignore `cursorOffset` in `format()` and `check()`

website/yarn.lock, yarn.lock
Updated caniuse-lite to remove yarn build:website warning.
The warning...
```shell
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
```
Has been removed on website build due to this fix.
=> Updated caniuse-lite to remove yarn build:website warning.

jest.config.mjs
We use a temp dir to run production test, but when debugging tests locally, keep installing packages is annoying, add a env flag to allow skip install.
=> Test: Add env flag to allow skip production install

tests/format/misc/typescript-babel-only/__snapshots__/jsfmt.spec.js.snap, tests/format/misc/typescript-babel-only/ts-4.7-infer-extends.ts
(babel-ts only)
Partial of #12640 
Just add tests for https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-rc/#extends-constraints-on-infer-type-variables
=> Support TS 4.7 `extends` constraints for `infer` (tests)

src/language-js/print/type-parameters.js, tests/format/misc/typescript-babel-only/__snapshots__/jsfmt.spec.js.snap, tests/format/misc/typescript-babel-only/ts-4.7-optional-variance-with-jsx.tsx, tests/format/misc/typescript-babel-only/ts-4.7-optional-variance.ts
(babel-ts only)
Partial of https://github.com/prettier/prettier/issues/12640
https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-rc/#optional-variance-annotations-for-type-parameters
=> Support TS 4.7 optional variance

changelog_unreleased/typescript/12930.md, src/language-js/print/typescript.js, tests/format/typescript/enum/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/enum/computed-members.ts, tests/format/typescript/enum/jsfmt.spec.js
=> fix formatting for typescript Enum with computed members

src/language-js/print/misc.js
This reverts commit f49114141a21f4f3cb1bb569e241ce1dbcdece44.
The commit f49114141a21f4f3cb1bb569e241ce1dbcdece44 in https://github.com/prettier/prettier/pull/12706 is a workaround for https://github.com/babel/babel/issues/14498.
Now, https://github.com/babel/babel/issues/14498 had fixed by https://github.com/babel/babel/pull/14500 and this change has released [v7.17.12](https://github.com/babel/babel/releases/tag/v7.17.12), moreover prettier uses v7.18.0 by https://github.com/prettier/prettier/pull/12896.
So, I reverted commit f49114141a21f4f3cb1bb569e241ce1dbcdece44.
=> Revert "print as instead of colon for babel-ts parser"

changelog_unreleased/typescript/12982.md, src/language-js/parse/postprocess/index.js, src/language-js/parse/postprocess/throw-syntax-error.js, src/language-js/parse/postprocess/typescript.js, tests/format/misc/errors/invalid/__snapshots__/jsfmt.spec.js.snap, tests/format/misc/errors/invalid/jsfmt.spec.js
=> Throw errors for invalid `TSEmptyBodyFunctionExpression` node

changelog_unreleased/graphql/13013.md, src/language-graphql/printer-graphql.js, tests/format/graphql/string/__snapshots__/jsfmt.spec.js.snap, tests/format/graphql/string/description.graphql
fixes https://github.com/prettier/prettier/issues/13011
=> bugfix(graphql): Keep useful empty lines in description

tests/format/js/import-assertions/__snapshots__/jsfmt.spec.js.snap, tests/format/js/import-assertions/re-export.js
Updated the import-assertions js formatter test, as the JSON modules spec [disallows named exports](https://github.com/tc39/proposal-json-modules#why-dont-json-modules-support-named-exports). For example, `export { foo2 } from "./foo.json" assert { type: "json" }` is invalid.
Currently blocking https://github.com/babel/babel/pull/14668. Babel plans to throw named JSON module imports/exports in the future, hence I update the test so the Babel update won't break our tests.
=> fix: JSON modules disable named exports

src/language-js/print/jsx.js
=> Refactor: Extract `printEndOfOpeningTag`

scripts/build/config.mjs, src/cli/format.js, src/cli/is-tty.js, src/common/load-plugins.js, src/common/third-party.cjs, src/common/third-party.js, src/config/resolve-config.js, tests/integration/__tests__/third-party.js, tests/integration/cli-worker.js, tests/integration/env.js
=> Migrate third-party.js to ES Module

src/document/doc-printer.js
`fits` currently contains indentation-related logic, but it's not needed. `fits` deals with the remainder of the line when the indentation has been already printed.
=> Refactor: simplify `fits`

tests/config/format-test.js, tests/format/js/strings/__snapshots__/jsfmt.spec.js.snap, tests/format/js/strings/jsfmt.spec.js, tests/format/typescript/optional-variance/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/optional-variance/jsfmt.spec.js, tests/format/typescript/optional-variance/with-jsx.tsx
I reverted #13159.
And removed `<in T>() => {}</in>;` as it was not legal.
https://www.typescriptlang.org/play?noImplicitAny=false&ts=4.8.0-beta#code/DwSwdgBAKgfAFASggXhhA3gX2AenDAbiA
Ref: https://github.com/babel/babel/pull/14779#discussion_r928144602
cc @fisker 
=> Update some tests

changelog_unreleased/cli/13019.md, docs/cli.md, src/cli/constant.js, src/cli/find-cache-file.js, src/cli/format.js, src/cli/utils.js, tests/integration/__tests__/__snapshots__/early-exit.js.snap, tests/integration/__tests__/__snapshots__/help-options.js.snap, tests/integration/__tests__/cache.js
Fixes #13010
- Create issue: https://github.com/prettier/prettier/pull/13019#issuecomment-1179655187
- Create issue: JSON checks with low memory usage https://github.com/prettier/prettier/pull/13019#discussion_r922671608
- Create issue: More safety JSON checks https://github.com/prettier/prettier/pull/13019#discussion_r922675171
=> Add `--cache-location` option

docs/install.md
set-script is deprecated, use `npm pkg set scripts.scriptname="cmd"` instead.
=> Docs: Use `npm pkg set` instead of deprecated `npm set-script`

changelog_unreleased/api/13227.md, website/playground/EditorState.js, website/playground/Playground.js, website/playground/PrettierFormat.js, website/static/worker.js
I'm going to make this checkbox unchecked by default. Reason: https://github.com/prettier/prettier/issues/10602#issuecomment-808602535
fixes https://github.com/prettier/prettier/issues/10602
=> Playground: "Rethrow embed errors" checkbox

src/cli/usage.js, tests/integration/__tests__/__snapshots__/early-exit.js.snap
Unstable orders seem to cause random failure on tests. https://github.com/prettier/prettier/runs/7702032774?check_suite_focus=true#step:6:56
=> Sort plugin default values when create usage

cspell.json, docs/api.md, docs/options.md, website/versioned_docs/version-stable/api.md, website/versioned_docs/version-stable/options.md
see https://github.com/prettier/prettier/issues/13232
https://deploy-preview-13252--prettier.netlify.app/docs/en/api.html#custom-parser-api
=> Custom parser API: deprecation notice

src/language-yaml/embed.js
Found this during other PRs, I thought there are more, but this seems the only one left.
=> Remove unnecessary spreading `options` in `textToDoc`

src/main/parser.js
=> Use `import()` to load `@babel/code-frame`

package.json, yarn.lock
This feature we need already merged https://github.com/nicolo-ribaudo/jest-light-runner/pull/47
=> Switch `jest-light-runner` back to npm version

changelog_unreleased/api/12574.md, docs/api.md, src/index.js
Reason https://github.com/prettier/prettier/issues/8772#issuecomment-1209163206
All public APIs are async now.
=> Make `prettier.clearConfigCache` async

changelog_unreleased/scss/13286.md, src/language-css/printer-postcss.js, tests/format/scss/variables/__snapshots__/jsfmt.spec.js.snap, tests/format/scss/variables/variables.scss
**fix:** https://github.com/prettier/prettier/issues/13185
=> fix: extra space between '#' and '{'

changelog_unreleased/typescript/13289.md, src/language-js/needs-parens.js, tests/format/typescript/conditional-types/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/conditional-types/issue-13275.ts
Parentheses shouldn't be removed from inferred function return types with extends constraints
fix for https://github.com/prettier/prettier/issues/13275
=> fix: paren shouldn't be removed from infer func 

src/document/printer.js
Easier to inspect `Command`, especially it was an array before #13154, very unidentifiable.
```text
{
ind: { value: '', length: 0, queue: [] },
mode: Symbol(MODE_FLAT),
doc: [
'{',
{ type: 'indent', contents: [Array] },
{
type: 'if-break',
breakContents: ',',
flatContents: undefined,
groupId: undefined
},
{ type: 'line' },
'}'
]
}
```
VS
```text
{
ind: { value: '', length: 0, queue: [] },
mode: 2,
doc: [
'{',
{ type: 'indent', contents: [Array] },
{
type: 'if-break',
breakContents: ',',
flatContents: undefined,
groupId: undefined
},
{ type: 'line' },
'}'
]
}
```
=> Use `symbol` for doc print mode

website/playground/Playground.js, website/playground/panels.js, website/static/worker.js
=> Playground: fix 'show doc', add folding for doc-explorer

src/document/builders.js, src/document/printer.js
The symbol don't need be in the doc, if printer use different `doc.js` to build doc, even will cause problems. (edge case, but possible.)
=> Remove `placeholder` from `doc.builders.cursor`

src/language-js/print/type-parameters.js, src/language-js/printer-estree.js, src/language-js/traverse/visitor-keys.evaluate.js, tests/unit/__snapshots__/visitor-keys.js.snap
=> Forbid pass non-node object to `print()`

src/document/utils.js, src/language-handlebars/printer-glimmer.js, src/language-html/embed.js, src/language-html/print/children.js, src/language-html/print/element.js, src/language-html/print/tag.js, src/language-html/printer-html.js, src/language-html/utils/index.js, src/language-js/print/comment.js, src/language-js/print/flow.js, src/language-js/print/literal.js, src/language-js/printer-estree.js, src/language-markdown/printer-markdown.js, src/language-yaml/printer-yaml.js
=> Replace `replaceTextEndOfLine` with `replaceEndOfLine`

src/language-graphql/printer-graphql.js, src/language-js/printer-estree.js, src/utils/create-print-pre-check-function.js
=> Forbid pass non-node object to graphql printer

docs/plugins.md
Document `getCommentChildNodes` on the plugins documentation page.
related: https://github.com/prettier/prettier/pull/3639
=> docs: plugins.md: add getCommentChildNodes

changelog_unreleased/api/13397.md, src/language-css/printer-postcss.js, src/language-graphql/printer-graphql.js, src/language-handlebars/printer-glimmer.js, src/language-js/printer-estree.js, src/main/ast-to-doc.js
Should be safe, things like hole in array should checked by printer like [we did](https://github.com/prettier/prettier/blob/5a627651ff648edd38bd0b5e667210a8a1f4e4a1/src/language-js/printer-estree-json.js#L19)
=> Stop passing `undefine` and `null` to printer

changelog_unreleased/flow/13396.md, src/language-js/print/function-parameters.js, src/language-js/print/object.js, tests/format/flow/function-single-destructuring/__snapshots__/jsfmt.spec.js.snap, tests/format/flow/function-single-destructuring/object-type-in-declare-function.js, tests/format/typescript/declare/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/declare/object-type-in-declare-function.ts
=> Hug object types in function parameters in Flow like in TS

cspell.json, docs/plugins.md
This PR adds the [Motoko language's official Prettier plugin](https://github.com/dfinity/prettier-plugin-motoko) to the community plugin list.
[Motoko](https://internetcomputer.org/docs/current/developer-docs/build/cdks/motoko-dfinity/motoko/) is a smart contract language for the [Internet Computer](https://internetcomputer.org/) ecosystem. 
=> Add `prettier-plugin-motoko` to community plugin list

changelog_unreleased/javascript/13410.md, src/language-js/print/function.js, tests/format/typescript/last-argument-expansion/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/last-argument-expansion/forward-ref.ts
=> Don't break signature of hugged function expression if parameters are identifiers without types

package.json, yarn.lock
fixes #13217
```console
$ time prettier test-slow.md -c
Checking formatting...
All matched files use Prettier code style!
real    0m18.831s
user    0m18.844s
sys     0m0.141s
$ time prettier test-slow.md -c
Checking formatting...
All matched files use Prettier code style!
real    0m1.664s
user    0m1.359s
sys     0m0.375s
```
=> Override version for the trim package to fix Markdown perf

changelog_unreleased/typescript/13427.md, src/language-js/print/type-parameters.js, src/language-js/print/typescript.js, tests/format/typescript/mapped-type/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/mapped-type/issue-11098.ts
Fixes https://github.com/prettier/prettier/issues/11098
@sosukesuzuki I believe this is a more optimal fix than #11190. There is no need to support comments between the modifier and identifier. I used the tests from your PR.
=> Fix leading comments in mapped types with `readonly`

scripts/build/config.mjs, scripts/build/modify-typescript-module.mjs
Separated from #13381, I think better target "main" branch, so the package size can be smaller if we still want publish v2.
**Size Change:** -4.28 MB (-27%) 🎉
**Total Size:** 11.6 MB
| `./dist/esm/parser-typescript.mjs` | 1.44 MB | -2.14 MB (-60%) | 🏆 |
| `./dist/parser-typescript.js` | 1.44 MB | -2.14 MB (-60%) | 🏆 |
<details><summary>ℹ️ <strong>View Unchanged</strong></summary>
| Filename | Size |
| :--- | :---: |
| `./dist/bin-prettier.js` | 1.98 kB |
| `./dist/cli.js` | 501 kB |
| `./dist/doc.js` | 69.8 kB |
| `./dist/esm` | 4.1 kB |
| `./dist/esm/parser-angular.mjs` | 58.8 kB |
| `./dist/esm/parser-babel.mjs` | 317 kB |
| `./dist/esm/parser-espree.mjs` | 154 kB |
| `./dist/esm/parser-flow.mjs` | 1.05 MB |
| …
=> Reduce size of `parser-typescript.js`

src/document/printer.js, tests/unit/print-doc-to-string.js
see https://github.com/prettier/prettier/pull/13415#issuecomment-1236294897
=> Get rid of regexp and handle cursor in trim in doc printer

scripts/build/config.mjs
It use `globalThis` now. Since v0.181.0
=> Remove outdated hack for `flow` parser

src/language-graphql/printer-graphql.js, src/language-js/needs-parens.js, src/language-js/print/call-arguments.js, src/language-js/print/function.js, src/language-js/print/literal.js, src/language-js/print/module.js, src/language-js/print/property.js, src/language-js/print/statement.js, src/language-js/print/template-literal.js, src/language-js/utils/index.js
=> Refactor: use path.getValue() everywhere instead of getNode()

src/common/ast-path.js, src/language-markdown/printer-markdown.js
This PR adds getters to the path object that can be used, in particular, for convenient destructuring. See https://github.com/prettier/prettier/pull/10565#issuecomment-1231520272. Also, this PR uses the added getters in the Markdown printer.
=> Add getters to path object

src/language-js/comments/handle-comments.js, src/language-js/comments/printer-methods.js, src/language-js/print/jsx.js, src/language-js/printer-estree.js, src/language-js/utils/index.js
=> Move comment-related printer methods to separate directory

scripts/build/esbuild-plugins/replace-module.mjs
If we don't need to consider about prototypes here, we can use `Object.hasOwn` instead of `Reflect.has`. What do you think? @fisker 
=> Use `Object.hasOwn` instead of `Reflect.has` in build script

changelog_unreleased/scss/13487.md, src/language-css/printer-postcss.js, tests/format/scss/quotes/__snapshots__/jsfmt.spec.js.snap, tests/format/scss/quotes/escape-in-string.scss
=> SCSS: Fix formatting string value that includes escape `\`

.github/workflows/prod-test.yml, scripts/build/build.mjs, scripts/build/config.mjs
My idea is to use 
- `.cjs` for CommonJS modules, `bin-prettier.cjs` `index.cjs`
- `.mjs` for ESM modules, `cli.mjs` `index.mjs` `third-party.mjs`(#13509) `esm/*`
- `.js` for UMD modules, `standalone.js`, `parser-*.js`
FYI:
I'm planning to 
- move `esm/parser-*` and `parser-*` to `plugins/`
- move `third-party.mjs*`  to `interal/`
So there will be
`babel.js` and `babel.mjs` in `plugins/`, should we use `.common.cjs` / `.esm.mjs` / `.umd.js` to be more clear?
=> Rename `bin-prettier.js` bundle to `bin-prettier.cjs`

changelog_unreleased/handlebars/13507.md, src/language-handlebars/printer-glimmer.js, tests/format/handlebars/block-statement/__snapshots__/jsfmt.spec.js.snap, tests/format/handlebars/block-statement/custom-else.hbs
A template transform can be used to create custom block keywords that behave similar to `if`. This updates printer-glimmer to correctly recognize and format the "else if" case when "if" is a custom keyword.
```hbs
{{! Input }}
{{#when isAtWork}}
Ship that code!
{{else when isReading}}
You can finish War and Peace eventually...
{{else}}
Go to bed!
{{/when}}
{{! Prettier stable }}
{{#when isAtWork}}
Ship that code!
{{else}}{{#when isReading}}
You can finish War and Peace eventually...
{{else}}
Go to bed!
{{/when}}{{/when}}
{{! Prettier main }}
{{#when isAtWork}}
Ship that code!
{{else when isReading}}
You can finish War and Peace eventually...
{{else}}
Go to bed!
{{/when}}
```
=> [handlebars] correctly format custom "else if" blocks

changelog_unreleased/css/13577.md, src/language-css/printer-postcss.js, tests/format/css/indent/__snapshots__/jsfmt.spec.js.snap, tests/format/css/pseudo-call/__snapshots__/jsfmt.spec.js.snap, tests/format/css/pseudo-call/is.css, tests/format/css/pseudo-call/where.css
Currently, pseudo-selector arguments are formatted all on one line (using `", "` as a separator. This results in [undesirable formatting](https://twitter.com/scriptraccoon/status/1576320682245267456):
```css
:where(#p0:checked ~ #play:checked ~ #c1:checked, #p1:checked
~ #play:checked
~ #c2:checked, #p2:checked ~ #play:checked ~ #cO:checked)
~ #result
> #c {
display: block;
}
```
My change formats them more like function arguments in other languages (using the `group`/`indent` primitives).
Additionally, tests for `:where`/`:is` were missing from the codebase, so this issue was not apparent in the tests. I’ve added the above code, as well as some examples from MDN to make sure we don’t regress in the future.
The current logic was implemented in #1792 back in 2017, which I believe is before …
=> Format pseudo-selector args like a function call

changelog_unreleased/markdown/11373.md, src/language-markdown/print-preprocess.js, tests/format/markdown/prose-wrap-preserve/__snapshots__/jsfmt.spec.js.snap, tests/format/markdown/prose-wrap-preserve/inline-code-newline.md, tests/format/markdown/prose-wrap-preserve/jsfmt.spec.js
=> markdown: Preserve inline code line breaks if --prose-wrap=preserve

src/cli/format.js, src/main/core.js, tests/config/format-test.js, tests/config/require-standalone.cjs, website/playground/EditorState.js, website/playground/Playground.js, website/playground/PrettierFormat.js, website/playground/util.js, website/static/worker.js
This can be especially useful for the Markdown printer as its preprocessing is really complex. HTML is interesting too.
=> Playground: show preprocessed AST

changelog_unreleased/typescript/13608.md, src/language-js/print/array.js, src/language-js/print/type-annotation.js, tests/format/typescript/tuple/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/tuple/dangling-comments.ts
Fixes #13588
This is not a refactoring of the dangling comments format that thorn0 was mention to, just a consistent formatting of the dangling comments in arrays and tuple types.
=> Consistent dangling comments formatting for tuple and array

src/language-js/print/template-literal.js, src/language-js/utils/index.js
- Move `isJestEachTemplateLiteral` from `utils/index.js` into `print/template-literal.js`
- Use `AstPath` getters
- Rename variables https://github.com/prettier/prettier/pull/13621#discussion_r993334531
- Use `quasi.tail`
- Earlier return
=> Refactor template literal print

scripts/tools/eslint-plugin-prettier-internal-rules/jsx-identifier-case.js, scripts/tools/eslint-plugin-prettier-internal-rules/no-node-comments.js
Adds `meta.schema` for `jsx-identifier-case` and `no-node-comments` rule to remove the below warnings:
```
$ node ./scripts/tools/eslint-plugin-prettier-internal-rules/test.js
(node:81036) DeprecationWarning: "jsx-identifier-case" rule has options but is missing the "meta.schema" property and will stop working in ESLint v9. Please add a schema: https://eslint.org/docs/developer-guide/working-with-rules#options-schemas
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:81036) DeprecationWarning: "no-node-comments" rule has options but is missing the "meta.schema" property and will stop working in ESLint v9. Please add a schema: https://eslint.org/docs/developer-guide/working-with-rules#options-schemas
``` …
=> Add `meta.schema` to internal ESLint rules for removing warnings

package.json, scripts/build/build-package-json.js
It seems
```
{
"./*": "./"
}
```
is incorrect.
https://github.com/prettier/yaml-unist-parser/pull/289
=> Fix package.json `exports` field

.codecov.yml, .github/workflows/dev-test.yml, jest.config.mjs, package.json
https://github.com/prettier/prettier/pull/11597#issuecomment-1279336969
As tested in #13643, the check is missing because there are too many files generate by `c8`, add `files` config should fix it.
=> Fix codecov status check

scripts/build/modify-typescript-module.mjs
**Size Change:** -52.9 kB (-1%) 
**Total Size:** 10.5 MB
| `./dist/plugins/typescript.js` | 1.35 MB | -26.4 kB (-2%) |
| `./dist/plugins/typescript.mjs` | 1.35 MB | -26.4 kB (-2%) |
=> Reduce size of `typescript` plugin

package.json, src/language-js/utils/index.js, src/language-js/utils/is-es5-identifier-name.js, yarn.lock
Ref https://github.com/prettier/prettier/issues/12144#issuecomment-1023251590
=> Replace `esutils` with `@prettier/is-es5-identifier-name`

scripts/build/config.mjs
**Size Change:** -20 kB (0%) 
**Total Size:** 10.4 MB
| `./dist/plugins/glimmer.js` | 120 kB | -10 kB (-8%) | ✅ |
| `./dist/plugins/glimmer.mjs` | 119 kB | -10 kB (-8%) | ✅ |
=> Reduce size of `glimmer` plugin

changelog_unreleased/flow/13687.md, src/language-js/comments/printer-methods.js, src/language-js/needs-parens.js, src/language-js/parse/babel.js, src/language-js/print/call-expression.js, src/language-js/print/comment.js, src/language-js/print/flow.js, src/language-js/print/function.js, src/language-js/print/misc.js, src/language-js/printer-estree.js, src/language-js/utils/index.js, tests/format/flow-repo/union_new/__snapshots__/jsfmt.spec.js.snap, tests/format/flow/comments/__snapshots__/jsfmt.spec.js.snap, tests/format/flow/comments/babel-only/__snapshots__/jsfmt.spec.js.snap
See https://github.com/prettier/prettier/issues/13142#issuecomment-1239479444
Issues to check and close: https://github.com/prettier/prettier/issues?q=is%3Aopen+is%3Aissue+label%3A%22area%3Aflow+comment+types%22
=> Remove support for Flow comment types

docs/api.md, package.json, scripts/generate-schema.mjs, src/cli/options/get-context-options.js, src/cli/usage.js, src/common/common-options.js, src/language-css/languages.evaluate.js, src/language-graphql/languages.evaluate.js, src/language-handlebars/languages.evaluate.js, src/language-html/languages.evaluate.js, src/language-html/options.js, src/language-js/languages.evaluate.js, src/language-js/options.js, src/language-markdown/languages.evaluate.js, src/language-yaml/languages.evaluate.js, src/main/core-options.js, src/main/options.js, src/main/support.js, tests/integration/__tests__/__snapshots__/schema.js.snap, tests/integration/__tests__/__snapshots__/support-info.js.snap, website/playground/Playground.js, website/static/worker.js, yarn.lock
Since v2.0.0, we removed `version` option from `getSupportInfo` #7620, `since` became useless, let's remove it.
=> Remove `since` from options and languages

package.json, scripts/draft-blog-post.mjs, scripts/sync-flow-tests.cjs, tests/integration/__tests__/cache.js, yarn.lock
Prettier v3 supports only Node.js >= 14 that support [`fs.rm`](https://nodejs.org/api/fs.html#fsrmpath-options-callback) and [`fs.rmSync`](https://nodejs.org/api/fs.html#fsrmsyncpath-options).
So we can remove `rimraf`.
=> Remove `rimraf` package

.eslintrc.cjs, scripts/build/build-license.js, tests/integration/__tests__/cache.js
`prettier-internal-rules/prefer-fs-promises-submodule` should be applied to all JS files.
=> Enable `prettier-internal-rules/prefer-fs-promises-submodule` for all files

src/cli/format-results-cache.js, src/cli/format.js, tests/integration/__tests__/cache.js, tests/integration/run-prettier.js
Do not save formatted cache if without `--write` option and the file is modifies by prettier.
Before fixed, always save formatted cache if with `--cache` option.
Therefore, unformatted files will never be formatted.
I think this is a bug.
```sh
> prettier --cache foo.js
> prettier --cache --write foo.js
foo.js 2ms (cached)
```
```sh
> prettier --cache foo.js
> prettier --cache --write foo.js
foo.js 2ms
```
=> Fix --cache set only if with --write or no-different

commands.md, src/document/builders.js, src/document/debug.js, src/document/utils.js, src/document/utils/traverse-doc.js
So it will always be a valid doc, we don't need do `if (flatContents);`. This shouldn't breaking things, unless plugin use old version of doc to build.
=> Make `flatContents` in `ifBreak` default to `""`

changelog_unreleased/cli/11369.md, docs/cli.md, src/cli/format.js, tests/integration/__tests__/__snapshots__/check.js.snap, tests/integration/__tests__/__snapshots__/ignore-unknown.js.snap, tests/integration/__tests__/__snapshots__/infer-parser.js.snap
The term "Forgot to run Prettier?" can be offputting for some (as documented in #6885). I believe that informing what needs to be done, rather than assuming someone did something "wrong", no matter how fine that "wrong" thing is, will provide a more even and calming message.
I debated adding more information (like a link to the logs or an example command to run) but I thought that was a separate initiative that could be picked up regardless of this change.
All I was after was attempting to remove some language that some find offputting if not condescending. 
Thanks!
=> Style: updated failure message to be more formal

src/main/parser.js, tests/integration/__tests__/plugin-override-buitin-plugins.js
Since I'm going to release a fix for #13731, so I'm going to temporarily restore the behavior of this function until we find a better solution.
=> Make `resolveParser` work like v2

scripts/build/build-javascript-module.js, scripts/build/esbuild-plugins/primitive-define.mjs
Non-primitive value will cause esbuild inject a function call in every file
=> Build: improve use of `define` option

scripts/build/config.mjs
**Size Change:** -45.5 kB (0%) 
**Total Size:** 9.72 MB
| `./dist/LICENSE` | 226 kB | -1.26 kB (-1%) |  |
| `./dist/plugins/postcss.js` | 124 kB | -22.1 kB (-15%) | 👏 |
| `./dist/plugins/postcss.mjs` | 124 kB | -22.2 kB (-15%) | 👏 |
=> Reduce size of `postcss` plugin

scripts/build/build-license.js
Add description, homepage & contributors
<details>
<summary>Details</summary>
```patch
@@ -19,17 +19,22 @@ MIT, ISC, BSD-2-Clause, BSD-3-Clause, 0BSD, Apache-2.0
+> Angular - the compiler library
+
License: MIT
-By: angular
Repository: <https://github.com/angular/angular.git>
+Author: angular
----------------------------------------
+> Generate errors that contain a code frame that point to source locations.
+
License: MIT
-By: The Babel Team
+Homepage: <https://babel.dev/docs/en/next/babel-code-frame>
Repository: <https://github.com/babel/babel.git>
+Author: The Babel Team (https://babel.dev/team)
> MIT License
>
@@ -58,9 +63,11 @@ Repository: <https://github.com/babel/babel.git>
+> Validate identifier/keywords name
+
License: MIT
-By: The Babel Team
Repository: …
```
=> Minor tweak to bundled dependencies license

package.json, src/language-js/needs-parens.js, tests/format/typescript/satisfies-operators/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/satisfies-operators/lhs.ts, yarn.lock
Follow up https://github.com/prettier/prettier/pull/13764
https://github.com/babel/babel/issues/15095 has been fixed so we can add more tests for `satisfies` as LHS.
=> Add more tests for `satisfies`

.eslintrc.cjs, src/language-js/print/jsx.js
https://ota-meshi.github.io/eslint-plugin-regexp/rules/no-useless-non-capturing-group.html
=> Enable `regexp/no-useless-non-capturing-group` rule

src/language-js/needs-parens.js
I tried to address https://github.com/prettier/prettier/pull/13783#issuecomment-1302942619.
Then I noticed some conditions are not actually used.
I'll backport this PR  to `main` after merge this into `next`.
=> Remove needless conditions for `YeildExpression` in `needs-parens`

changelog_unreleased/cli/13016.md
Adds changelog for #13016
@Milly We should have added the changelog in #13016 but we forgot, so I'll add it in this PR
=> Add missing changelog for #13016

changelog_unreleased/typescript/13764.md
I forgot to add changelog in https://github.com/prettier/prettier/pull/13783
=> Add changelog for #13783

src/language-js/parse/babel.js, src/language-js/parse/postprocess/typescript.js, src/language-js/print/typescript.js, tests/config/format-test.js, tests/format/misc/errors/typescript/__snapshots__/jsfmt.spec.js.snap, tests/format/misc/errors/typescript/babel-ts/__snapshots__/jsfmt.spec.js.snap, tests/format/misc/errors/typescript/babel-ts/jsfmt.spec.js, tests/format/misc/errors/typescript/jsfmt.spec.js, tests/format/misc/typescript-babel-only/__snapshots__/jsfmt.spec.js.snap, tests/format/misc/typescript-babel-only/invalid-modifiers.ts, tests/format/misc/typescript-only/__snapshots__/jsfmt.spec.js.snap, tests/format/misc/typescript-only/invalid-modifiers.ts, tests/format/typescript/class/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/class/jsfmt.spec.js, tests/format/typescript/class/methods.ts, tests/format/typescript/compiler/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/compiler/modifiersOnInterfaceIndexSignature1.ts
=> TypeScript: Throw errors for invalid modifier on type parameter

package.json, src/language-js/parse/postprocess/typescript.js, yarn.lock
=> Update typescript to v4.9

.eslintrc.cjs, src/common/util.js, src/language-markdown/clean.js, src/language-markdown/printer-markdown.js, website/playground/index.js
https://ota-meshi.github.io/eslint-plugin-regexp/rules/prefer-lookaround.html
=> Enable `regexp/prefer-lookaround` rule

changelog_unreleased/typescript/13764.md, package.json, src/language-js/utils/index.js, tests/format/typescript/satisfies-operators/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/satisfies-operators/jsfmt.spec.js, yarn.lock
~~It is still alpha (ref: https://github.com/typescript-eslint/typescript-eslint/issues/5688#issuecomment-1321006190).~~
=> Update `@typescript-eslint/typescript-estree` to support `satisfies`

changelog_unreleased/typescript/13860.md, src/language-js/print/type-annotation.js, tests/format/typescript/union/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/union/inlining.ts
Fix the problem that type should not be considered as hug type when there are comments (#13858)
=> Fix union type should be printed in the multi-line variant when there are comments

netlify.toml, website/playground/Playground.js
Just adds the new [`--single-attribute-per-line`](https://prettier.io/docs/en/options.html#single-attribute-per-line) option to the Playground.
(_I presumed this step wouldn't be necessary for such a minor update as this — apologies if I'm mistaken_)
=> Add '--single-attribute-per-line' option to Playground

src/language-css/clean.js
=> Remove an empty `String#replace` call

.eslintrc.cjs, package.json, src/language-js/embed/html.js, yarn.lock
https://github.com/ota-meshi/eslint-plugin-regexp/releases/tag/v1.11.0
[regexp/no-extra-lookaround-assertions](https://ota-meshi.github.io/eslint-plugin-regexp/rules/no-extra-lookaround-assertions.html)
[regexp/no-useless-assertions](https://ota-meshi.github.io/eslint-plugin-regexp/rules/no-useless-assertions.html)
=> Update eslint-plugin-regexp to v1.11.0

src/language-js/print/array.js
Make `printArrayItems` and `printArrayItemsConcisely` have similar logic.
=> Minor refactor to array item print

tests/format/typescript/instantiation-expression/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/instantiation-expression/logical-expr.ts
- added test for formating logical expression with instantiation expression (#13856)
Close #13856
=> test: format instantiation expr in logical expr

changelog_unreleased/handlebars/13930.md, src/language-handlebars/printer-glimmer.js, tests/format/handlebars/block-statement/__snapshots__/jsfmt.spec.js.snap, tests/format/handlebars/block-statement/custom-else.hbs
This is a follow-up to #13507 to allow block params in custom "else if"-like blocks.
```hbs
{{! Input }}
{{#when isAtWork as |work|}}
Ship that
{{work}}!
{{else when isReading as |book|}}
You can finish
{{book}}
eventually...
{{else}}
Go to bed!
{{/when}}
{{! Prettier stable }}
{{#when isAtWork as |work|}}
Ship that
{{work}}!
{{else when isReading}}
You can finish
{{book}}
eventually...
{{else}}
Go to bed!
{{/when}}
{{! Prettier main }}
{{#when isAtWork as |work|}}
Ship that
{{work}}!
{{else when isReading as |book|}}
You can finish
{{book}}
eventually...
{{else}}
Go to bed!
{{/when}}
```
```
--parser glimmer
```
CC: @dcyriller
=> [handlebars] allow custom "else if"-like with block params

changelog_unreleased/scss/13931.md, src/language-css/printer-postcss.js, tests/format/scss/parens/__snapshots__/jsfmt.spec.js.snap
Empty lines between SCSS maps nested within other maps are not being preserved by prettier. This resolves that.
No issue was found for this particular bug. As a reference, it relates to #12536, which mentioned the issue via code comment and in the pull request.
=> fix: preserve empty lines between nested SCSS maps

src/document/printer.js
Plugins like `@prettier/plugin-pug` prints a big string instead of doc commands, it cost time when measuring width.
Ideally it should only measure the last line, or even better should measure from `out` when use the `pos`, we should improve it in future.
=> Skip measure width of last string in `printDocToString`

changelog_unreleased/javascript/14000.md, src/language-js/needs-parens.js, tests/format/js/identifier/for-of/__snapshots__/jsfmt.spec.js.snap, tests/format/js/identifier/for-of/await.js, tests/format/js/identifier/for-of/jsfmt.spec.js, tests/format/js/identifier/for-of/let.js
=> Add missing parentheses to `let` in `for..of` loop

changelog_unreleased/less/14008.md, src/language-css/printer-postcss.js, tests/format/less/parens/__snapshots__/jsfmt.spec.js.snap, tests/format/less/parens/parens.less, tests/format/scss/parens/__snapshots__/jsfmt.spec.js.snap
Fix #13998.
Less online compiler https://lesscss.org/less-preview/ can be used to verify, added space can change the meaning of the data.
The problem is solely with `-`, `+` is not supported by less before `(`.
Also solely for LESS/SCSS, as regular CSS supports calculations only inside `calc()` where space has no special meaning.
=> Fix no space after unary minus when followed by opening parenthesis in LESS

src/language-js/print/decorators.js, src/language-js/utils/index.js
`ExportDefaultSpecifier` was there since [the first commit](https://github.com/prettier/prettier/commit/9b4535e9f8a7040f2fbc65b22c9713632f3731be#diff-9c0ec1b0a889e599f3ff81590864dd9dc65684a86b41f1da75acc53fafed12e3R276), but I don't think it should be considered export declaration.
=> Fix `isExportDeclaration`

changelog_unreleased/flow/14073.md, src/language-js/print/type-parameters.js, tests/format/typescript/assignment/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/typeparams/empty-parameters-with-arrow-function/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/typeparams/empty-parameters-with-arrow-function/issue-13817.ts, tests/format/typescript/typeparams/empty-parameters-with-arrow-function/jsfmt.spec.js
=> Fix formatting of empty type parameters

changelog_unreleased/javascript/14047.md, src/language-js/comments.js, tests/format/js/switch/__snapshots__/jsfmt.spec.js.snap, tests/format/js/switch/comments2.js
fixes https://github.com/prettier/prettier/issues/12481
=> Fix displacing of comments in default switch case

src/language-js/needs-parens.js, tests/format/js/identifier/for-of/__snapshots__/jsfmt.spec.js.snap, tests/format/js/identifier/for-of/await.js, tests/format/js/identifier/for-of/let.js
I forgot to test 
```js
for await((let) of foo);
```
in #14044, but it's handled by `if` bellow.
Minor tweak to the logic, to avoid `findAncestor` call.
=> Improve `let` check in `for..of`

changelog_unreleased/less/14034.md, src/language-css/parser-postcss.js, src/language-css/printer-postcss.js, tests/format/less/case/__snapshots__/jsfmt.spec.js.snap, tests/format/less/case/case.less, tests/format/less/case/variable.less
Simple example:
```
@var: {
camelCase: 0;
};
div {
margin: @var[camelCase];
};
```
when `preserveCase` is changed to `preservecase`, LESS compilation fails.
This PR fixes such problem and handles also variable declaration with nested ruleset correctly.
=> Do not change case of property name if inside a variable declaration in LESS

src/main/ast-to-doc.js, src/main/comments.js
So we can still track cursorOffset even node `willPrintOwnComments`.
=> Move cursor tracking from `printComments` to `printAstToDoc`

src/language-js/print/array.js, src/language-js/print/enum.js, src/language-js/print/object.js
It's more reasonable to use `printObject` instead of `printArrayItems` to print members.
=> Refactor Enum print

tests/format/handlebars/prettier-ignore/__snapshots__/jsfmt.spec.js.snap, tests/format/handlebars/prettier-ignore/prettier-ignore.hbs
This PR adds test cases for {{! prettier-ignore}} when it is above or before:
- a text element
- a mustache element
- a block element
- a comment element
@fisker it should help with https://github.com/prettier/prettier/pull/13690
=> Handlebars: Add tests for `{{! prettier-ignore}}`

src/language-js/print/typescript.js, tests/format/typescript/module/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/module/global.ts
Use `node.global` instead of checking originalText.
```ts
declare /* module */ global {}
```
was printed as
```ts
declare module /* module */ global {}
```
=> Minor refactor to `TSModuleDeclaration` print

website/siteConfig.js, website/static/css/code-block-buttons.css, website/static/js/code-block-buttons.js, website/yarn.lock
This PR adds a copy to clipboard button to code blocks as part of #14006 
=> feat: add copy to clipboard in code blocks

src/language-js/print/block.js, src/language-js/print/class.js, src/language-js/print/statement.js, src/language-js/printer-estree.js
The `ClassBody` is different than normal statement sequence,
It can't have `directives` and `EmptyStatement` , it have different logic in no-semi mode.
Let's split it.
=> Extract `printClassBody`

src/cli/expand-patterns.js
In [Sapling SCM](https://sapling-scm.com/), `.sl/` is the folder where it stores its state, analogous to `.git/` in Git. It should be ignored in Prettier like the other SCM folders.
=> Add .sl to the list of silentlyIgnoredDirs

changelog_unreleased/javascript/14192.md, src/language-js/printer-estree.js, tests/format/js/async/__snapshots__/jsfmt.spec.js.snap, tests/format/js/async/nested2.js
=> Avoid adding unnecessary indent to nested await

src/language-js/print/type-annotation.js, src/language-js/print/typescript.js, tests/format/typescript/function-type/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/function-type/consistent.ts
=> Reuse `printFunctionType`

src/language-js/print/function.js, src/language-js/print/typescript.js
Print `value` node of method through `print`, I'm not sure if there are comment/cursor related issue there, but I think it's better to print node through `print`.
=> Refactor method value print

src/language-js/print/array.js, tests/format/flow/tuple-types/__snapshots__/jsfmt.spec.js.snap, tests/format/flow/tuple-types/jsfmt.spec.js, tests/format/flow/tuple-types/trailing-comma.js, tests/format/typescript/tuple/__snapshots__/jsfmt.spec.js.snap
=> Treat `--trailing-comma=es5` as `all` when printing tuple types

changelog_unreleased/api/14108.md, docs/api.md, src/common/get-file-info.js, tests/integration/__tests__/file-info.js
=> Resolves config by default in `getFileInfo()`

changelog_unreleased/less/14109.md, src/language-css/parser-postcss.js, tests/format/less/inline-javascript/__snapshots__/jsfmt.spec.js.snap, tests/format/less/inline-javascript/inline-javascript.less, tests/format/less/inline-javascript/jsfmt.spec.js
Closes #11340, since this feature already deprecated, I don't think changelog is necessary.
=> Skip parsing inline JavaScript code in Less

src/language-js/parse/postprocess/typescript.js, src/language-js/print/typescript.js, src/language-js/traverse/visitor-keys.evaluate.js, tests/format/misc/errors/typescript/modifiers/__snapshots__/jsfmt.spec.js.snap, tests/format/misc/errors/typescript/modifiers/jsfmt.spec.js, tests/unit/__snapshots__/visitor-keys.js.snap
`TSModuleDeclaration` can't have `modifiers`.
https://github.com/typescript-eslint/typescript-eslint/pull/4863
Related #14265
=> Remove printing `modifiers` of `TSModuleDeclaration`

src/language-js/parse/postprocess/typescript.js, src/language-js/print/enum.js, src/language-js/print/misc.js, src/language-js/traverse/visitor-keys.evaluate.js, tests/format/misc/errors/typescript/modifiers/__snapshots__/jsfmt.spec.js.snap, tests/format/misc/errors/typescript/modifiers/jsfmt.spec.js, tests/unit/__snapshots__/visitor-keys.js.snap
`TSEnumDeclaration` can't have `modifiers`.
https://github.com/typescript-eslint/typescript-eslint/pull/4863
=> Remove printing `modifiers` of `TSEnumDeclaration`

src/language-js/parse/postprocess/index.js, src/language-js/print/typescript.js, src/language-js/traverse/visitor-keys.evaluate.js, tests/format/misc/errors/typescript/interface/__snapshots__/jsfmt.spec.js.snap, tests/format/misc/errors/typescript/interface/jsfmt.spec.js, tests/format/typescript/compiler/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/compiler/errorOnInitializerInInterfaceProperty.ts, tests/format/typescript/compiler/jsfmt.spec.js, tests/unit/__snapshots__/visitor-keys.js.snap
Ref: https://github.com/typescript-eslint/typescript-eslint/pull/6243#discussion_r1090246389
=> Forbid `initializer` of `TSPropertySignature`

tests/config/utils/check-parsers.js, tests/format/typescript/arrows/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/arrows/jsfmt.spec.js, tests/format/typescript/class-comment/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/class-comment/jsfmt.spec.js, tests/format/typescript/classes/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/classes/jsfmt.spec.js, tests/format/typescript/comments-2/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/comments-2/jsfmt.spec.js, tests/format/typescript/end-of-line/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/end-of-line/jsfmt.spec.js, tests/format/typescript/function/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/function/jsfmt.spec.js, tests/format/typescript/functional-composition/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/functional-composition/jsfmt.spec.js, tests/format/typescript/interface2/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/interface2/jsfmt.spec.js, tests/format/typescript/method-chain/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/method-chain/jsfmt.spec.js, tests/format/typescript/multiparser-css/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/multiparser-css/jsfmt.spec.js, tests/format/typescript/test-declarations/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/test-declarations/jsfmt.spec.js
All those places mean to test with `flow`. (`babel-flow` auto tested #14245)
=> Forbid test `babel` parser in `typescript/`

src/language-js/parse/babel.js, src/language-js/parse/postprocess/typescript.js, src/language-js/print/typescript.js, src/language-js/traverse/visitor-keys.evaluate.js, tests/format/misc/errors/typescript/modifiers/__snapshots__/jsfmt.spec.js.snap, tests/format/misc/errors/typescript/modifiers/jsfmt.spec.js, tests/format/typescript/class/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/class/constructor.ts, tests/format/typescript/class/jsfmt.spec.js, tests/format/typescript/conformance/types/parameterProperty/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/conformance/types/parameterProperty/parameterProperty.ts, tests/unit/__snapshots__/visitor-keys.js.snap
Apply changes from https://github.com/typescript-eslint/typescript-eslint/pull/6243
~TODO: Test~ done.
=> Stop checking invalid properties

src/language-js/print/array.js, src/language-js/print/block.js, src/language-js/print/call-arguments.js, src/language-js/print/class.js, src/language-js/print/function-parameters.js, src/language-js/print/function.js, src/language-js/print/jsx.js, src/language-js/print/module.js, src/language-js/print/object.js, src/language-js/print/type-parameters.js, src/language-js/print/typescript.js, src/language-js/printer-estree.js, src/main/comments.js
- Combine `sameIndent` and `filter` into object
- Change `sameIndent` default to true
- Support `marker`
=> Refactor `printDanglingComments`

src/language-js/print/class.js
The old one consider empty array as one heritage, found this when working on #14259, we haven't decide what to do with #14259, [ts parser is making some changes may effect this part](https://github.com/typescript-eslint/typescript-eslint/pull/6274).
=> Fix `hasMultipleHeritage` logic

changelog_unreleased/typescript/14279.md, src/language-js/needs-parens.js, tests/format/typescript/conditional-types/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/conditional-types/issue-13275.ts, tests/format/typescript/conditional-types/parentheses.ts
=> Fix incorrect removal of parentheses when using an `infer` with a constraint in a function predicate

changelog_unreleased/typescript/13427.md, src/language-js/print/type-parameters.js, src/language-js/print/typescript.js, tests/format/typescript/mapped-type/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/mapped-type/issue-11098.ts
As requested https://github.com/prettier/prettier/pull/13427#issuecomment-1419998324
=> Fix leading comments in mapped types with `readonly` (Cherry-pick #13427)

src/language-js/comments/printer-methods.js, src/language-js/print/binaryish.js, src/language-js/print/call-arguments.js, src/language-js/print/function.js, src/language-js/print/jsx.js, src/language-js/print/statement.js, src/language-js/print/ternary.js, src/language-js/utils/index.js
The old one feels like it includes any `JSX*` node.
=> Rename `isJsxNode` as `isJsxElement`

src/common/util.js, src/language-js/comments/handle-comments.js, src/language-js/print/function-parameters.js
Accept `startIndex` instead of `node` + `locEnd`
Prepare for #14317
=> Simplify `getNextNonSpaceNonCommentCharacter`

src/common/util-shared.js, src/common/util.js, src/language-js/comments/handle-comments.js, src/language-js/parse/babel.js, src/language-js/print/function.js, src/language-js/print/member-chain.js, src/utils/text/get-next-non-space-non-comment-character-index.js
=> Replace `getNextNonSpaceNonCommentCharacterIndex` with `getNextNonSpaceNonCommentCharacterIndexWithStartIndex` internally

changelog_unreleased/api/14317.md, docs/plugins.md, src/common/util-shared.js, src/common/util.js, tests/integration/__tests__/util-shared.js
=> Add `getNextNonSpaceNonCommentCharacter` to `prettier.util`

src/language-js/print/assignment.js, src/language-js/print/literal.js, src/language-js/print/misc.js, src/language-js/printer-estree.js, src/language-js/utils/index.js
Remove `TemplateLiteral`, `TSTypeLiteral`, and `JSXText` from `isLiteral`
They are not Literal in ESTree, only used [here](https://github.com/prettier/prettier/blob/be84156d43805a281369c934ae28148065d6316e/src/language-js/print/assignment.js#L404), they can't be an argument or handled above.
Move `DirectiveLiteral` into `literal.js`, since the same Node represent as `Literal` in ESTree.
=> Refactor literal related code

src/language-js/print/print-semicolon.js, src/language-js/print/semicolon.js, src/language-js/print/statement.js, src/language-js/printer-estree.js
Move the leading semicolon check from `printStatementSequence` to `genericPrint`, so we don't need pass `args.needsSemi` (which breaks print cache)
=> Refactor leading semicolon print

docs/rationale.md, website/versioned_docs/version-stable/rationale.md
Add a note about how Prettier won't auto-fix all ASI issues.
This is being done to help remove confusion in the community about how Prettier deals with ASI hazards.
I've noticed that a lot of developers feel that they can run with a no-semicolon style of programming by simply throwing in prettier and not bothering to actually learn the rules behind ASI. This isn't entirely true. Prettier can help fix some issues before they become a problem, but if you write code that already contains an ASI-related bug, Prettier won't auto-fix that bug for you. While it's true that Prettier will still reformat ASI-related buggy code in such a way as to make it more obvious that there was a bug there, developers aren't generally in the habit of double-checking how Prettier is reformatting their code.
The …
=> Explain ASI issues aren't always auto-fixed

changelog_unreleased/cli/14333.md, cspell.json, src/cli/expand-patterns.js, src/cli/format.js, src/cli/utils.js
Before:
```console
Checking formatting...
[warn] src\utils\create-get-visitor-keys.js
[warn] src\utils\unexpected-node-error.js
[warn] Code style issues found in 2 files. Forgot to run Prettier?
```
After:
```console
Checking formatting...
[warn] src/utils/create-get-visitor-keys.js
[warn] src/utils/unexpected-node-error.js
[warn] Code style issues found in 2 files. Forgot to run Prettier?
```
=> CLI: Display posix style paths on Windows

src/language-js/comments/printer-methods.js
We have full vistorKeys, so this function can't receive comments or other non-node objects.
=> Simplify `canAttachComment`

changelog_unreleased/javascript/14393.md, src/language-js/needs-parens.js, tests/config/format-test.js, tests/format/js/decorators/__snapshots__/jsfmt.spec.js.snap, tests/format/js/decorators/member-expression.js
=> Add missing parentheses for decorator

src/common/ast-path.js
Hi, I hope this drive by PR is okay. 
I was profiling some of the the tools I use at $work looking for some easy performance gains, and out of curiosity I tried the "next" branch hoping that it would be faster than main. When I was profiling on my own app I saw that `AstPath.node` was a very hot function taking about 2% of the time. I saw that the implementation was using `Array#at(-1)`, and I switched it back to using the `stack[stack.length - 1]` pattern that is used in the main branch, and after running the benchmark script a few time I'm seeing a ~10% performance improvement.
I also took into account [the comments made about the benchmark script about i/o caching](https://github.com/prettier/prettier/pull/13224#issuecomment-1228161394) and adjusted the benchmark script locally to copy …
=> Perf: Array#at is slow for a hot function like `AstPath.node`

src/language-css/parser-postcss.d.ts, src/language-graphql/parser-graphql.d.ts, src/language-handlebars/parser-glimmer.d.ts, src/language-html/parser-html.d.ts, src/language-js/parse/acorn-and-espree.d.ts, src/language-js/parse/angular.d.ts, src/language-js/parse/babel.d.ts, src/language-js/parse/flow.d.ts, src/language-js/parse/meriyah.d.ts, src/language-js/parse/typescript.d.ts, src/language-markdown/parser-markdown.d.ts, src/language-yaml/parser-yaml.d.ts
TS5 seems not allow use `export =`, [CI log](https://github.com/prettier/prettier/actions/runs/4311945857/jobs/7521900909#step:6:5)
I've tested locally, it works.
Also, these modules are prettier plugins, not parsers, so renamed `parser` -> `plugin`.
cc @sosukesuzuki 
=> Use `export default` in `.d.ts` files

src/language-html/parser-html.js, src/language-html/utils/index.js, src/language-markdown/embed.js, src/utils/infer-parser-by-language.js
Remove use of `getSupportInfo`.
=> Simplify `inferParserByLanguage`

src/language-css/loc.js, src/language-js/parse/postprocess/index.js, src/main/core.js, src/main/get-cursor-node.js
Before this change, it use `findNodeAtOffset` it checkes `canAttachComment` and `isSourceElement`, cursorNode should not care.
After this change, the `cursorNode` can be the most inside node, will make the "cursorNodeText" smaller and easier to locate new cursor.
=> Improve `cursorNode` find logic

src/main/infer-parser.js
Similar to #14437, remove use of `getSupportInfo`.
=> Simplify `inferParser`

src/document/printer.js, src/main/ast-to-doc.js
`printAstToDoc` should not do it.
=> Move `propagateBreaks` to `printDocToString`

src/language-handlebars/printer-glimmer.js, src/language-html/printer-html.js, src/language-js/print/jsx.js, src/language-markdown/printer-markdown.js, src/utils/get-preferred-quote.js, src/utils/print-string.js
We can use `String#replaceAll` now, unnecessary to return an object.
=> Simplify `getPreferredQuote`

changelog_unreleased/misc/14516.md, package.json, yarn.lock
This fixes https://github.com/prettier/prettier/issues/14514 by upgrading `editorconfig-to-prettier` with the fix from https://github.com/josephfrazier/editorconfig-to-prettier/pull/10
=> Support `max_line_length=off` when parsing `.editorconfig`

changelog_unreleased/typescript/14548.md, src/language-js/parse/postprocess/typescript.js, tests/format/js/decorators/class-expression/__snapshots__/jsfmt.spec.js.snap, tests/format/js/decorators/class-expression/jsfmt.spec.js, tests/format/typescript/decorators/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/decorators/legacy.ts, tests/format/typescript/type-arguments-bit-shift-left-like/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/type-arguments-bit-shift-left-like/jsfmt.spec.js
=> Allow decorator on private members and class expressions

changelog_unreleased/typescript/14584.md, src/language-js/parse/postprocess/typescript.js, tests/format/typescript/decorators/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/decorators/jsfmt.spec.js
=> Allow multiple decorators on same getter/setter

changelog_unreleased/vue/14587.md, src/language-html/print-preprocess.js, tests/format/vue/multiparser/__snapshots__/jsfmt.spec.js.snap, tests/format/vue/multiparser/lang-ts-multiple-script-tags.vue
Fix https://github.com/prettier/prettier/issues/14575
=> Format TS expressions when any script tag has `lang="ts"`

scripts/lint-changelog.mjs, website/blog/2021-05-09-2.3.0.md
https://github.com/prettier/prettier/pull/13436#issuecomment-1483890362
=> `lint-changelog` should warn for second template comment

scripts/build/build-package-json.js
~To indicate `.js` files are not in ESM. (Only `.mjs` files are in ESM, `.js` files are UMD)~ I forget that The default is `commonjs`.
=> Whitelist keys when build package.json file

docs/options.md
Fix a typo on a single line in the Parser section and the less parser option
=> correct typo (feel free to --fixup!)

src/cli/print-support-info.js, src/main/support.js, src/utils/object-omit.js, tests/integration/__tests__/__snapshots__/support-info.js.snap
- Merge `.filter` +`.map` + `.map` into one loop
- Move sort into CLI
=> Improve `getSupportInfo`

src/cli/options/get-context-options.js, src/cli/print-support-info.js, src/cli/utils.js, src/index.js, src/main/support.js
This option only hide `cli*` value from options, API user should not care about it, only hide them when run CLI with `--support-info` .
=> Remove `showInternal` option from `getSupportInfo()`

package.json, scripts/build/build-package-json.js
Not sure if it's necessary, but https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing
> The "types" condition should always come first in "exports".
=> Put `types` first in `exports`

src/document/printer.js
Ref: https://github.com/prettier/prettier/issues/14514#issuecomment-1471000708
In #14634, maybe we should also print the doc with `printWidth: Infinity` and check the printed string instead?
=> Improve doc printer when `printWidth: Infinity`

src/index.d.ts
index.d.ts: Printer: add missing getCommentChildNodes
This is already documented in the docs #12502 .
Does this count as "user-facing" considering it only affects plugin authors?
=> index.d.ts: Printer: add missing getCommentChildNodes

.gitignore
Vendors dir is now unnecessary
=> Remove `/vendors` and `/scripts/vendors` from `.gitignore`

src/language-js/traverse/visitor-keys.evaluate.js, tests/unit/__snapshots__/visitor-keys.js.snap
=> Remove outdated visitor key for `TSAbstractMethodDefinition`

.eslintrc.cjs, scripts/build/config.js, src/cli/format.js, src/cli/is-tty.js, src/common/mockable.js, src/common/third-party.js, src/config/get-prettier-config-explorer.js, src/main/plugins/search-plugins.js, tests/integration/__tests__/mockable.js, tests/integration/cli-worker.js, tests/integration/env.js
Mock `thirdParty.writeFormattedFile` instead of `fs.writeFile`, so other files like cache file can write normally even if it use `fs.promises.writeFile` in future.
=> Add a `writeFormattedFile` to mock

src/main/normalize-format-options.js, tests/integration/__tests__/printer-and-parser.js
=> Don't apply plugin default options from unused plugins

changelog_unreleased/typescript/14672.md, src/language-js/print/type-parameters.js, tests/format/typescript/typeparams/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/typeparams/line-breaking-after-extends.ts
Fixes #14666 
Adds a newline and indent after `extends` in the type param to respect `printWidth`.
=> Line breaking after `extends` in type parameters

src/language-js/print/estree.js, src/language-js/print/html-binding.js, src/language-js/print/index.js, src/language-js/printer.js, src/plugins/estree.js
=> Move estree printer into `print/`

src/language-js/comments/handle-comments.js
Hey there, I've found this small issue.
By the way, this is a great project! I've been using it since its beginning :)
It is needlessly complex to invert the result of a boolean comparison. The opposite comparison should be made instead.
In other words, instead of `!(a === b)` use `a !== b`.
=> Boolean checks should not be inverted

changelog_unreleased/typescript/14830.md, src/language-js/print/object.js, tests/format/typescript/call-signature/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/call-signature/call-signature.ts, tests/format/typescript/call-signature/jsfmt.spec.js
Fixes #14786 
Fix to not insert a semicolon at the end of a call signature line with prettier-ignore comment.
=> TypeScript: Fix issue with double semicolon caused by `// prettier-ignore` on a call signature line

docs/plugins.md
The mention was previously added with https://github.com/prettier/prettier/pull/13180 but is missing on this page.
=> Add `prettier-plugin-rust` to community plugin list

src/language-js/print/call-arguments.js, tests/format/flow/type-cast/__snapshots__/jsfmt.spec.js.snap, tests/format/flow/type-cast/argument-expansion.js
Comparing formatting of prettier v2 vs prettier v3 on the Meta codebases i noticed argument expansion no longer works when the second arg is a Flow type cast. My guess is it was related to the changes in #13341 which explicitly handles TS `TSAsExpression` nodes. This change adds similar support for Flow `TypeCastExpression` nodes.
```js
// Input
const bar1 = [1,2,3].reduce((carry, value) => {
return [...carry, value];
}, ([]: Array<string>));
// Prettier stable
const bar1 = [1,2,3].reduce(
(carry, value) => {
return [...carry, value];
},
([]: Array<string>)
);
// Prettier main
const bar1 = [1,2,3].reduce((carry, value) => {
return [...carry, value];
}, ([]: Array<string>));
```
This change doesn't bring full parity to the current v2.8 logic but it should cover most of the cases and at …
=> Consider Flow type cast expressions when expanding call arguments

website/static/worker.js
`prettier.__debug.parse` has different signatures in v2 and v3. Currently the playground on prettier.io uses the v3 signature for v2, that's why AST is shown incomplete (massaged).
=> Fix playground: AST is massaged for Prettier 2.x

src/plugins/builtin-plugins-proxy.js
- Fix function name `createParsersAndParsers` to `createParsersAndPrinters`.
=> Fix typo in function name

src/cli/format.js, src/common/errors.js, tests/unit/errors.js
When creating a [custom error](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error#custom_error_types), it's recommended to set the value of the [`name`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/name) property.
This pull request makes it easier to filter errors:
```JavaScript
try {
const result = prettier.check(source, config);
// ...
} catch (err) {
// CURRENTLY: Need to use ".constructor" for Prettier custom errors.
// if ("UndefinedParserError" === err.constructor.name) {
//     console.log("FATAL: No parseri found!");
// } else if ("SyntaxError" === err.name) {
//     console.log("FATAL: Syntax error!");
// }
// WITH THIS PULL REQUEST: Only use ".name" for all errors.
if ("UndefinedParserError" === …
```
=> feat: Add name to errors

changelog_unreleased/angular/14961.md, src/language-js/print/binaryish.js, tests/format/angular/angular/__snapshots__/jsfmt.spec.js.snap, tests/format/angular/angular/attributes.component.html, tests/format/angular/angular/ignore-attribute.component.html, tests/format/angular/angular/interpolation.component.html, tests/format/angular/bracket-same-line/__snapshots__/jsfmt.spec.js.snap, tests/format/angular/interpolation/__snapshots__/jsfmt.spec.js.snap
As per discussion in the linked issue, the most desired format was to keep spaces around semicolon separating pipe arguments, but remove space after pipe name.
Closes #13887 
=> Remove space after pipe name

changelog_unreleased/api/15018.md, scripts/build/build-types.js
=> fix estree plugin type declaration

docs/cli.md
Add `.gitignore` to the default in the docs of `--ignore-path` CLI option.
ref: #14731
=> docs: Add `.gitignore` to the default ignore path

changelog_unreleased/javascript/15037.md, src/language-js/print/function.js, tests/format/js/comments/__snapshots__/jsfmt.spec.js.snap, tests/format/js/comments/return-statement.js
Fixes https://github.com/prettier/prettier/issues/15013
There is no such problem with JSX ([playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEqUAFAJT7AA6U++ATnDOnTcdbbQPQBU37H3fACkAygA1+tbp3wAeACY4AbgD5ZnRav6lqAXxAAaEBAAOuaAGdkoAIZ06EAO4AFOwisobAG0c2AnlZGAEZ0NmAA1owiNgC2cAAyOFBwyKjeFnDBoRFRJmFJAObIMHTomSAZMTjFpeUWhV5wAIroEPCp6eUAVhYAHiINza3tSGleGUYAjsNwzg4mHiA2FgC0yXDyG4YgJTY4XoUAwhAxMTbIS15e2-VQBY0AgjAlOEHo8M5wdInJHePlAAsYDEvAB1AE4eAWPJgOAidyQ5SQvwXMAWQIgJRlACSUE2sBEYDoODMDzxIhgfkafwmIBMDgyoNCJgu9LgGToShSRiSHJgcxsBTONPKeToHIuQRsQTg1yM9KSMFBOHkMAByAAHAAGIwMaY4BgCoXnUadIwwaXK1XqpAAJiM6AyABVpR4xrS4DEZfJNvJ4jY7uhBXAAGIQOhnZ6FC42d4QEC6XRAA)), so I excluded it from the condition to avoid duplicate parenthesis …
=> Add parenthesis around leading multiline comment in return statement

docs/browser.md, website/versioned_docs/version-stable/browser.md
Update Browser documentation with `estree` plugin when needed and add a quick note to inform that the plugin is required when parsing JavaScript, TypeScript, Flow, or JSON.
Close https://github.com/prettier/prettier/issues/15078
- [x ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).
=> doc(browser): add requirement for estree plugin when parsing js, ts, flow or json

website/package.json, website/yarn.lock
In Windows, `yarn build:website` for `$PULL_REQUEST = "true"` fails bacause `rm` doesn't exist in Windows.
```
PS> $env:PULL_REQUEST = "true"
PS> yarn build:website
Building prettier...
Building packages
index.mjs.............................................................. SKIPPED
index.d.ts............................................................ SKIPPED
index.cjs............................................................. SKIPPED
index.d.ts............................................................ SKIPPED
bin/prettier.cjs....................................................... SKIPPED
internal/cli.mjs....................................................... SKIPPED
internal/internal.mjs.................................................. SKIPPED …
```
=> Use `rimraf` instead of `rm -rf`, which is not available in Windows

changelog_unreleased/api/15127.md, src/index.d.ts, tests/dts/unit/cases/print.ts
Closes: #15034
[TS Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAksECcAKCD2kHAJYQM4B4AVAPigF4pCoIAPeAOwBNcoBDekAbQF0AoKKAH5YTWinSJseIsX5QAXFACCCBKxDiMUgiQDcvXqEjLV6zZJw7SFAN5zOAaShZ6UANYQQqAGaVuigDlUegCAVwAbcNYAI3CIIkduUloGZigECFZGYPCQNg4eISgnRXoIADdEfQBfTg8vX0JuXSgAelaBTq7unt7OgD0oAAtECAMjaBhRGnNMSyJqOggmFhsoOPoAc2Ah0tCAW2jEKGrrWFxCULA4mUXUlmAEULGBYQBRGgBjcNDGeKRWHNWOEZJwAEQbbZDMHcAA0lHBkJ2MNkAj2hyq43AkwuVxuJHIlDuyzSPDkwkezzkiioKRJLE4Lm8xwAYlgELhgPCAHS8pnHABKEH2rBcfFe50u13iQpFLlRCig3mBuAg+gMvBc8AQys+0CUnIBOwWFHYIFIdgEIrA+AAqvCkABGYkrWDa2baGTEAAUcgEn2B4WirE+bkU3oAlORSGbYX6oGA0GBHYonXGBBHFLaeDUNVrELroIQ8MAgn8oJb0hBNhFASo1CBFJyEC5Njm5BksjkQPX1IpO9l6LkoM3W+3qgZPsFOQnWDtFAbgEahkQS2WIGdQqJvC4IIw2Cwzer2lAAOqoBBuFg7sq8MBzobc63eyPRqBgsHwsEZGtRBC9kAwQjfQTyCAB3KAwIvK8lV3KBgFQVA7wfJ …
=> Add typing to support `readonly` array properties of AST Node

changelog_unreleased/api/15125.md, src/index.d.ts
Closes #15121
Reference: https://prettier.io/docs/en/plugins.html#optional-getvisitorkeys
=> Add missing 'getVisitorKeys' method type definition for 'Printer'

changelog_unreleased/api/15123.md, src/index.d.ts
> Also, the preprocess method of a printer can return a promise now.
In the blog, preprocess in allowed to return a promise now. However the types are wrong.
I guess the blog is wrong too because preprocess belongs to parser?
Maybe address #12683
(I'm unable to provide a changelog now but soon)
=> fix: add missing `printer.preprocess` definition

changelog_unreleased/javascript/15076.md, src/language-js/comments/handle-comments.js, tests/format/js/if/__snapshots__/jsfmt.spec.js.snap, tests/format/js/if/expr_and_same_line_comments.js, tests/format/js/if/jsfmt.spec.js
=> Fix comments print in `IfStatement`

changelog_unreleased/scss/15217.md, src/language-css/print/parenthesized-value-group.js, tests/format/scss/scss/__snapshots__/jsfmt.spec.js.snap, tests/format/scss/scss/scss.scss
Fixes https://github.com/prettier/prettier/issues/15193
=> Do not add trailing comma for grouped scss comments

docs/configuration.md, website/versioned_docs/version-stable/configuration.md
This lets VSCode validate the `overrides` property.
=> Fix type annotations for config docs

docs/index.md, website/data/languages.yml, website/versioned_docs/version-stable/index.md
Not a few people misunderstand Prettier supports MDX v2. We see a non-negligible number of issues based on misinterpretations of the MDX version. This PR will state that Prettier only supports v1 and prevents them from misunderstanding the supported version until #12209 is fixed.
I may have to change the link to <https://v1.mdxjs.com/>.
After it is fixed, the "v1" that has been added can be changed to "v2" or simply removed.
=> State that the supported version of MDX is 1 until #12209 is fixed

changelog_unreleased/javascript/15256.md, src/language-js/print/call-expression.js, tests/format/js/require/__snapshots__/jsfmt.spec.js.snap, tests/format/js/require/require.js
=> Allow break `require()` argument

src/document/public.d.ts, src/index.d.ts
When working on migrating `prettier-plugin-solidity` to typescript I discovered some missing details in the types exported by Prettier.
=> Missing types

scripts/release/package.json, scripts/tools/bundle-test/package.json, scripts/tools/eslint-plugin-prettier-internal-rules/package.json, website/package.json
renovate PRs start failing, maybe this will help?
https://github.com/prettier/prettier/pull/15147#issuecomment-1646716831
=> Add `packageManager` to submodules

src/cli/expand-patterns.js
I found that `fast-glob` can't glob any file with `**/{*.js}` (single extension), the original code works because we always have many `extensions` and `filenames` in `languages`.
I guess better pass an array to `fast-glob` instead to be safer.
=> Minor refactor to `expandPatterns`

scripts/build/README.md, scripts/build/build-javascript-module.js, scripts/build/parse-arguments.js
=> Fix build script `--report` option

changelog_unreleased/api/15233.md, src/config/load-external-config.js, tests/integration/__tests__/config-resolution.js, tests/integration/cli/config/external-config/esm-package-forbids-require/index.js, tests/integration/cli/config/external-config/esm-package-forbids-require/node_modules/prettier-config-forbids-require/index.js, tests/integration/cli/config/external-config/esm-package-forbids-require/node_modules/prettier-config-forbids-require/package.json, tests/integration/cli/config/external-config/esm-package-forbids-require/package.json
=> Support shared config that forbids `require()`

src/cli/format.js, src/cli/index.js
Move it together with other conflict flags check. `exitCode` changed to `1`.
=> Move `--cache-strategy` check into `index.js`

src/cli/index.js
=> Use `process.exitCode` instead of `process.exit()`

src/cli/index.js, tests/integration/__tests__/stdin-filepath.js
There is no `context.argv.filePath`, only `context.argv.filepath`.
`
=> Fix `--stdin-file-path`

.prettierrc, bin/prettier.cjs, bin/prettier.js, package.json, scripts/build/config.js, src/cli/index.js, tests/integration/cli-worker.js
1. Use `--cache` ourself
2. Add `debug` script, so we can use `yarn debug test.js` without using `--ignore-path=.prettierignore` everytime.
=> Meta tweak

docs/integrating-with-linters.md, website/versioned_docs/version-stable/integrating-with-linters.md
removed recommendation to use `stylelint-config-prettier` since it is not needed in v15 and above. 
more information here:
https://stylelint.io/migration-guide/to-15/
- [ V ] I’ve added tests to confirm my change works.
- [ V  ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).
=> Update integrating-with-linters.md to match stylelint v15

src/language-css/loc.js
Accidently removed it in #15345 when fixing the offset.
=> Add `node.source.end.offset` back

.github/workflows/dev-test.yml
https://github.com/nodejs/node/issues/49497 has been fixed and released.
=> Unpin Node.js v20 version

changelog_unreleased/scss/15370.md, src/language-css/print/comma-separated-value-group.js, tests/format/scss/scss/__snapshots__/jsfmt.spec.js.snap, tests/format/scss/scss/scss.scss
Fixes https://github.com/prettier/prettier/issues/15369
=> Do not split call of scss function with leading dash

docs/install.md, website/versioned_docs/version-stable/install.md
Tested on `cmd`, `powershell`, work as expected.
```console
node --eval "fs.writeFileSync('.prettierrc','{}\n')" && node -p "JSON.stringify(fs.readFileSync('.prettierrc','utf8'))"
```
Fixes #13926
Fixes #11751
Closes #11692
Note to myself: copy to stable version after we decide what to use.
=> Fix empty Prettier config file create command

package.json, src/config/editorconfig-to-prettier.js, src/config/resolve-editorconfig.js, tests/unit/editorconfig-to-prettier.js, yarn.lock
I'd like to vendor/upstream this code because it's been the topic of a handful of issues in its repo over the years, including https://github.com/josephfrazier/editorconfig-to-prettier/issues/9, https://github.com/josephfrazier/editorconfig-to-prettier/issues/21, and most recently https://github.com/josephfrazier/editorconfig-to-prettier/issues/24, and I feel that having it in-repo would be more appropriate (not to mention [the issues in _this_ repo that pertain to editorconfig parsing](https://github.com/search?q=repo%3Aprettier%2Fprettier+editorconfig++&type=issues&state=open)). I've elaborated on my thoughts in https://github.com/josephfrazier/editorconfig-to-prettier/issues/24#issuecomment-1718405985, which I'll quote below:
> hey @Drakmyth, thanks for continuing this conversation! I …
=> Move editorconfig-to-prettier package into repo

changelog_unreleased/api/15332.md, docs/api.md, src/common/get-file-info.js, src/index.d.ts, src/utils/ignore.js, src/utils/read-file.js, tests/integration/__tests__/file-info.js
=> Support `URL` as `ignorePath` in `getFileInfo()`

src/config/editorconfig-to-prettier.js, src/config/resolve-editorconfig.js, tests/unit/editorconfig-to-prettier.js
Now that https://github.com/prettier/prettier/pull/15394 has been
merged, this addresses https://github.com/prettier/prettier/issues/14514#issuecomment-1471056464
_EDIT: Note that this is just a code cleanup, and does not change the behavior of Prettier_
=> cleanup EditorConfig handling: Remove unused parsing/ignoring of `insert_final_newline` to `insertFinalNewline`

changelog_unreleased/flow/15130.md, src/language-js/needs-parens.js, src/language-js/print/call-arguments.js, src/language-js/print/cast-expression.js, src/language-js/print/flow.js, src/language-js/print/template-literal.js, src/language-js/print/ternary.js, src/language-js/print/typescript.js, src/language-js/traverse/visitor-keys.evaluate.js, src/language-js/types/estree.d.ts, src/language-js/utils/index.js, tests/format/flow/as-satisfies-expression/__snapshots__/jsfmt.spec.js.snap, tests/format/flow/as-satisfies-expression/as-const.js, tests/format/flow/as-satisfies-expression/as.js, tests/format/flow/as-satisfies-expression/assignment.js, tests/format/flow/as-satisfies-expression/export_default_as.js, tests/format/flow/as-satisfies-expression/jsfmt.spec.js, tests/format/flow/as-satisfies-expression/long-identifiers.js, tests/format/flow/as-satisfies-expression/nested-await-and-as.js, tests/format/flow/as-satisfies-expression/return.js, tests/format/flow/as-satisfies-expression/satisfies.js, tests/format/flow/as-satisfies-expression/ternary.js, tests/unit/__snapshots__/visitor-keys.js.snap
Adds support for  printing `as` and `satisfies` expressions in Flow.
```
const x = y as T;
```
This is accomplished first by factoring out TypeScript's logic and using/extending that.
Tests are mostly copied from TS's tests. I did a `diff` of Flow's and TS's snapshot file to confirm that that differences were expected (from input change).
=> Support `as` and `satisfies` expressions for Flow

changelog_unreleased/typescript/15408.md, src/language-js/embed/graphql.js, src/language-js/embed/html.js, src/language-js/embed/utils.js, tests/format/flow/as-const/__snapshots__/jsfmt.spec.js.snap, tests/format/flow/as-const/embedded.js, tests/format/flow/as-const/jsfmt.spec.js, tests/format/typescript/as/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/as/as-const-embedded.ts
=> Support embedded formatting in template literals annotated with `as const`

changelog_unreleased/typescript/15409.md, src/language-js/comments/handle-comments.js, tests/format/flow/union/__snapshots__/jsfmt.spec.js.snap, tests/format/flow/union/comments.js, tests/format/typescript/union/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/union/comments.ts
=> Fix printing comment for the last operand of union types

src/language-js/print/assignment.js, src/language-js/print/estree.js, src/language-js/print/literal.js, src/language-js/utils/index.js
This is a refactor pulled out of https://github.com/prettier/prettier/pull/13183 which is mostly unrelated to ternaries. I think it fixed some bugs but I can't remember what they were at this point.
- [N/A] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [N/A] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
=> Refactor simple member expressions etc

package.json
- `not dead` includes `not ie 11`.
> dead: browsers without official support or updates for 24 months. Right now it is IE 11, IE_Mob 11, BlackBerry 10, BlackBerry 7, Samsung 4, OperaMobile 12.1 and all versions of Baidu.
- `not safari 5.1` is obsolete.
=> Improve browserslist in `package.json`

changelog_unreleased/flow/15466.md, src/language-js/print/type-annotation.js, src/language-js/traverse/visitor-keys.evaluate.js, tests/format/flow/typeof/__snapshots__/jsfmt.spec.js.snap, tests/format/flow/typeof/jsfmt.spec.js, tests/format/flow/typeof/typeof-with-type-arguments.js, tests/unit/__snapshots__/visitor-keys.js.snap
Flow now supports `typeof MyGenericClass<string, number>` syntax (ref: https://github.com/prettier/prettier/pull/15455 )
=> Support type arguments after `typeof`

changelog_unreleased/javascript/15468.md, src/language-js/needs-parens.js, tests/format/flow-repo/binary/__snapshots__/jsfmt.spec.js.snap, tests/format/js/binary-expressions/__snapshots__/jsfmt.spec.js.snap, tests/format/js/binary-expressions/in_instanceof.js
Fixes https://github.com/prettier/prettier/issues/15434
=> Disambiguate unary expr in instanceof and in

changelog_unreleased/javascript/15472.md, src/language-css/printer-postcss.js, tests/format/js/multiparser-css/__snapshots__/jsfmt.spec.js.snap, tests/format/js/multiparser-css/issue-8352.js
=> Fix name case of selectors in styled components interpolation

docs/plugins.md
This PR adds the [Prettier Plugin Jinja Template](https://github.com/davidodenwald/prettier-plugin-jinja-template) to the community plugin list.
[Jinja](https://jinja.palletsprojects.com/en/3.1.x/) is a template engine for python.
=> Add prettier-plugin-jinja-template to community plugin list

changelog_unreleased/cli/15467.md, src/cli/format.js, tests/integration/__tests__/__snapshots__/line-after-filepath-with-errors.js.snap, tests/integration/__tests__/__snapshots__/write.js.snap, tests/integration/__tests__/cache.js
Fixes #15396.
As described in the issue, this:
* resolves the accessibility concern by distinguishing unchanged files from changed files using the keyword `(unchanged)` instead of merely using grey color.
=> Show `(unchanged)` keyword for accessibility in CLI `--write`

changelog_unreleased/typescript/15514.md, src/language-js/needs-parens.js, tests/format/flow/as-satisfies-expression/__snapshots__/jsfmt.spec.js.snap, tests/format/flow/as-satisfies-expression/as-const.js, tests/format/flow/as-satisfies-expression/as.js, tests/format/flow/as-satisfies-expression/satisfies.js, tests/format/typescript/as/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/as/expression-statement.ts, tests/format/typescript/satisfies-operators/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/satisfies-operators/expression-statement.ts
Fixes https://github.com/prettier/prettier/issues/15491.
=> Support `(type) satisfies never;`

src/language-markdown/constants.evaluate.js, src/language-markdown/utils.js
=> Switch `kRegex` to use RegExp with `u` directly

src/language-markdown/constants.evaluate.js, src/language-markdown/utils.js
Reverts prettier/prettier#15584
Looks like it's not supported in browsers targeted. https://github.com/prettier/prettier/actions/runs/6841921595/job/18602833438?pr=15630#step:5:46
=> Revert "Switch `kRegex` to use RegExp with `u` directly"

package.json, src/common/mockable.js, tests/integration/cli-worker.js, yarn.lock
It appears that the `findParentDir` method `mockable.js` isn't used anywhere in the code base. I suspect that this code wasn't cleaned after a refactor, but I wasn't able the specific commit in the history.
=> Remove unused `findParentDir` from mockable

scripts/build/esbuild-plugins/evaluate.js, src/language-markdown/constants.evaluate.js, src/language-markdown/printer-markdown.js, src/language-markdown/utils.js
=> Improve `RegExp`s in markdown printer

cspell.json, website/blog/2023-11-13-curious-ternaries.md
This PR fixes the spelling of "clamoring" in the latest release blog post.
=> Fix spelling issue in ternaries blog post

website/playground/Playground.js
=> Enable `--experimental-ternaries` in playground

changelog_unreleased/typescript/15708.md, src/language-js/comments/handle-comments.js, tests/format/typescript/comments/15707.ts, tests/format/typescript/comments/__snapshots__/jsfmt.spec.js.snap
=> Fix unstable and ugly formatting for comments in destructuring patterns

src/index.js
```
> p=await import('./index.js')
> await p.__internal.inferParser('package.json',{})
'json-stringify'
> await p.__internal.inferParser('.prettierrc',{})
'yaml'
> await p.__internal.inferParser('node_modules/.bin/acorn',{})
'babel'
> await p.__internal.inferParser('node_modules/.bin/acorn',{parser:'yaml'})
'yaml'
> await p.__internal.inferParser('foo.java', {plugins:["prettier-plugin-java"]})
'java'
> await p.__internal.inferParser('foo.java', {plugins:["prettier-plugin-java1"]})
Uncaught:
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'prettier-plugin-java1',,,
```
=> `prettier.__internal.inferParser` for new CLI

commands.md
=> documenting the `hardline` within an `ifBreak` odd behaviour

tests/dts/unit/run.js
Jest's `expect` iterates all the properties of diagnostic objects triggering a deprecation error in a getter. That's why now it gets an array of formatted messages instead. Also formatted messages are easier to understand when the test fails.
=> Fix expect call in dts test

website/playground/Playground.js, website/playground/panels.js
=> Add cursorOffset to Playground

website/blog/2023-11-13-curious-ternaries.md
The blogpost shows one of the experimental ternaries examples written a way that doesn't match the actual format that prettier chooses.
It might be there though for illustrational purposes though. Up to you if you decide to merge this.
=> fix example to fit the actual experimentalTernaries behaviour

CONTRIBUTING.md
`CONTRIBUTING.md` now briefly discusses the option philosophy and links to `docs/options-philosophy.md`.
=> Update contributing.md to mention options philosophy

tests/format/html/cursor/__snapshots__/jsfmt.spec.js.snap, tests/format/html/cursor/cursor-0.html, tests/format/html/cursor/cursor-1.html, tests/format/html/cursor/cursor-2.html, tests/format/html/cursor/cursor-3.html, tests/format/html/cursor/cursor-4.html, tests/format/html/cursor/cursor-5.html, tests/format/html/cursor/cursor-6.html, tests/format/html/cursor/cursor-7.html, tests/format/html/cursor/cursor-8.html, tests/format/html/cursor/jsfmt.spec.js, tests/format/js/cursor/__snapshots__/jsfmt.spec.js.snap, tests/format/js/cursor/cursor-11.js, tests/format/js/cursor/cursor-12.js, tests/format/js/cursor/cursor-13.js
As a prerequisite for being comfortable putting https://github.com/prettier/prettier/pull/15709 up for review, I wanted more tests of cursor positioning, to convince me that I'm not breaking anything, especially with regard to embedded documents. I've therefore added a bunch of test cases here, including test cases where the cursor position we currently output is clearly perverse. In particular, these tests seem to show that we get cursor position bizarrely wrong a lot of the time when formatting HTML. I do _not_ currently understand whatsoever why that is the case, and my changes in #15709 will not fix it (nor make it worse). I may try to debug it at a later date.
I *do* understand why we get the perverse output in cursor-11.js and cursor-12.js, and it's worth discussing a bit - and here …
=> Add a bunch more cursor position test cases

tests/dts/unit/run.js
Previously, this failed to handle kinds of objects that `getPreEmitDiagnostics` sometimes returns.
To demonstrate the problem, open `standalone.ts` and replace the line `prettierStandalone.formatWithCursor(" 1", { cursorOffset: 2, parser: "babel" });` with `prettierStandalone.formatWithCursor(" 1", {});`, then run `yarn test dts`.
On main, you'll see this unhelpful output with "object Object":
```
$ yarn test dts
FAIL  tests/dts/unit/run.js
Unit tests for dts files
✕ no errors (2676 ms)
Unit tests for dts files > no errors
Error: expect(received).toEqual(expected) // deep equality
- Expected  - 1
+ Received  + 3
- Array []
+ Array [
+   "/home/mark/prettier/tests/dts/unit/cases/standalone.ts:3:43 TS2345: [object Object]",
+ ]
at file:///home/mark/prettier/tests/dts/unit/run.js?170247558199 …
```
=> Fix formatDiagnostic in tests/dts/unit/run.js

src/language-html/embed.js
=> Remove useless `{stripTrailingHardline: true}`

scripts/release/README.md, scripts/release/parse-arguments.js, scripts/release/steps/bump-prettier.js, scripts/release/steps/check-git-status.js, scripts/release/steps/post-publish-steps.js, scripts/release/steps/show-instructions-after-npm-publish.js, scripts/release/steps/update-changelog.js, scripts/release/steps/update-dependents-count.js, scripts/release/steps/update-version.js, scripts/release/steps/validate-new-version.js, scripts/release/steps/wait-for-bot-release.js
Add the `--next` flag to your release script. When this flag is enabled, we only update the version of `package.json`, add Git tags, and push to GitHub.
=> Add `--next` flag to release script

scripts/build/config.js
=> Remove `xhtmlEntities` from typescript plugin

cspell.json, package.json, scripts/build/esbuild-plugins/visualizer.js, yarn.lock
This reverts #15807, since they changed the API back.
https://github.com/btd/esbuild-visualizer/commit/1a3fa4cffa7e34bdf3f29405d9c5f37c3df5bd41
=> Update `esbuild-visualizer` to v0.5.1

docs/install.md, website/versioned_docs/version-stable/install.md
It is the appropriate file extension. In addition, the extension is already used in line 170. So this creates consistency.
=> Use `.prettierrc` consistently in docs

changelog_unreleased/graphql/15870.md, src/language-graphql/printer-graphql.js, tests/format/graphql/union-types/__snapshots__/jsfmt.spec.js.snap, tests/format/graphql/union-types/union_types.graphql
Issue: 14234 - Improve GraphQL union types formatting
Fixes #14234
=> Improve GraphQL union types formatting

changelog_unreleased/api/15854.md, src/index.d.ts, tests/dts/unit/cases/index.ts, tests/dts/unit/cases/plugins.ts
Fixes https://github.com/prettier/prettier/issues/15849
In addition to the `getFileInfo`, I noticed that the `getSupportInfo` type definition is also outdated https://github.com/prettier/prettier/blob/84c169ecc20f6776639d67ed9ab371dacf1db3b8/src/main/support.js#L8-L16
=> Fix `getFileInfo` and `getSupportInfo` type definitions

changelog_unreleased/angular/15887.md, src/language-js/print/angular.js, tests/format/angular/control-flow/__snapshots__/jsfmt.spec.js.snap, tests/format/angular/control-flow/for.html
=> Avoid adding colon for `track` in 3rd expression of `for` blocks

CHANGELOG.md
Fixes typo in https://github.com/prettier/prettier/commit/29f299f73edf9dea28aae9d44a52377a8d12620f#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed
I’ve already updated https://github.com/prettier/prettier/releases/tag/3.2.0. Are there any other places where this link can be broken?
=> Fix release notes URL in CHANGELOG.md

scripts/release/get-formatted-date.js
https://github.com/prettier/prettier/pull/15913 happened because draft-blog-post uses ISOString and release script uses Date.prototype.getDate()
=> Use `ISOString` for `getFormattedDate`

docs/plugins.md
Add `prettier-plugin-gherkin` to the community plugins list
=> Add `prettier-plugin-gherkin` to the community plugins list

changelog_unreleased/javascript/15920.md, src/language-js/utils/index.js, tests/format/js/chain-expression/__snapshots__/jsfmt.spec.js.snap, tests/format/js/chain-expression/issue-15916.js
=> Fix formatting error on optional call expression and member chain

docs/api.md
=> Update documentation for `prettier.resolveConfig()`

src/language-js/parse/babel.js
This restriction has been removed https://github.com/babel/babel/pull/15896
=> Remove outdated babel reasonCode

src/language-js/print/module.js, src/language-js/print/typescript.js, src/language-js/utils/get-text-without-comments.js, tests/format/typescript/module/__snapshots__/jsfmt.spec.js.snap, tests/format/typescript/module/keyword.ts
=> Improve keyword detection in `TSModuleDeclaration`

src/language-js/utils/index.js
Ref: https://github.com/prettier/prettier/pull/15920#discussion_r1451647312
=> Simplify `isSimpleCallArgument`

.prettierrc, .vscode/extensions.json, .vscode/settings.example.json, changelog_unreleased/api/15927.md, src/utils/infer-parser.js, tests/integration/__tests__/file-info.js
Should infer parser by filenames first, then by extensions.
=> Fix parser inference

changelog_unreleased/json/15947.md, cspell.json, src/language-json/languages.evaluate.js, tests/integration/__tests__/__snapshots__/support-info.js.snap, tests/integration/__tests__/with-parser-inference.js
=> Fix JSONC filenames list

eslint.config.js
Our codebase is now pure ESM, we can't omit extensions, we can write anything that works directly, so we don't need it anymore.
=> Remove `import/extensions`

changelog_unreleased/angular/15968.md, src/language-js/embed/utils.js, tests/format/typescript/angular-component-examples/15934-computed.component.ts, tests/format/typescript/angular-component-examples/15934.component.ts, tests/format/typescript/angular-component-examples/__snapshots__/jsfmt.spec.js.snap
=> Support Angular inline styles as single template literal

changelog_unreleased/api/16012.md, cspell.json, src/language-json/languages.evaluate.js, src/utils/infer-parser.js, tests/integration/__tests__/__snapshots__/support-info.js.snap, tests/integration/__tests__/file-info.js
Implement @fisker's proposal (https://github.com/prettier/prettier/issues/15956#issuecomment-1906252034).
Closes #15958
=> Use `"json"` parser for `tsconfig.json` by default

src/language-js/print/estree.js, src/language-js/print/flow.js, src/language-js/print/function-parameters.js, src/language-js/print/function.js, src/language-js/print/type-annotation.js, src/language-js/utils/index.js
=> Minor refactor to property print

src/document/printer.js, src/document/utils.js, src/language-css/print/parenthesized-value-group.js, src/language-js/print/binaryish.js
This is a legacy feature, we used have `array`, `concat`, and `fill`.
=> Remove `getDocParts`

src/language-js/utils/index.js
The `isUnitTestSetUp` function uses the regular expression `/^(?:before|after)(?:Each|All)$/`. This regex matches the following four strings:
- `beforeEach`
- `beforeAll`
- `afterEach`
- `afterAll`
When the options are limited to about four, using a `Set` is generally faster than performing calculations with a regular expression.
Below are the total execution times of the `isUnitTestSetUp` function against the source code of Babel and Prettier, comparing the `main` branch to this PR:
|repo |  `main` | this PR |
|--------|-------|---|
|prettier | 1.0767030000051818 ms   | 0.8237229999981537 ms |
|babel | 2.696221000274363 ms | 1.9283900000140193 ms |
=> perf: Use logical expression instead of regexp for `isUnitTestSetUp`

changelog_unreleased/flow/16066.md, package.json, src/language-js/needs-parens.js, src/language-js/print/flow.js, tests/format/flow/type-declarations/__snapshots__/jsfmt.spec.js.snap, tests/format/flow/type-declarations/declare_module.js, tests/format/flow/type-declarations/declare_namespace.js, tests/format/flow/type-declarations/jsfmt.spec.js, tests/unit/__snapshots__/visitor-keys.js.snap, yarn.lock
Support `declare namespace` pretty-printing for Flow.
=> feat: `declare namespace` printing support for Flow

docs/cli.md, src/cli/format.js, tests/integration/__tests__/__snapshots__/check.js.snap, tests/integration/__tests__/__snapshots__/ignore-unknown.js.snap, tests/integration/__tests__/__snapshots__/infer-parser.js.snap, website/blog/2023-07-05-3.0.0.md, website/versioned_docs/version-stable/cli.md
- Mention --write in the failure output
- This will help folks move on quickly without needing to look at docs
- It also helps with folks who are used to --fix
=> Add "--write" to the prettier failure output

package.json, yarn.lock
Yesterday I released version 5.2.0 of jsdiff, which contains significant performance improvements and should be completely backwards-compatible. As long as I didn't screw anything up, upgrading to 5.2.0 in Prettier should be a no-brainer; it will majorly mitigate the performance problems described in https://github.com/prettier/prettier/issues/4801.
To test the performance improvement, I tried formatting this file...
```
['abandon', 'ability', 'able', 'abortion', 'about', 'above', 'abroad', 'absence', 'absolute', 'absolutely', 'absorb', 'abuse', 'academic', 'accept', 'access', 'accident', 'accompany', 'accomplish', 'according', 'account', 'accurate', 'accuse', 'achieve', 'achievement', 'acid', 'acknowledge', 'acquire', 'across', 'act', 'action', 'active', 'activist', 'activity', 'actor', …
```
=> Bump `diff` dependency to the faster version I released yesterday

tests/format/markdown/liquid/__snapshots__/jsfmt.spec.js.snap, tests/format/markdown/liquid/unbalanced-mismatched-braces.md, tests/format/markdown/liquid/unbalanced-object-close-only.md, tests/format/markdown/liquid/unbalanced-object-open-only.md, tests/format/markdown/liquid/unbalanced-template-close-only.md, tests/format/markdown/liquid/unbalanced-template-open-only.md
I'm working on #11828 and feel that it's better to have more tests around liquid.
As far as I know, with latest remark-parse, we can't extend syntax with regex as current in-house plugins does. To reduce risk in migration, it should be better to add test in advance.
=> Add tests of edge cases around liquid

src/language-js/utils/index.js
=> Fix `getCallArgumentSelector`

changelog_unreleased/javascript/16058.md, src/language-js/print/property.js, tests/format/js/quote-props/__snapshots__/jsfmt.spec.js.snap, tests/format/js/quote-props/jsfmt.spec.js, tests/format/js/quote-props/objects.js
=> Fix `isStringKeySafeToUnquote`

src/language-js/print/jsx.js, src/language-js/print/property.js, src/language-js/utils/index.js
=> Minor tweak to `printPropertyKey`

package.json, yarn.lock
=> Update `angular-estree-parser` to v10

src/language-js/utils/index.js, tests/format/js/test-declarations/__snapshots__/jsfmt.spec.js.snap, tests/format/js/test-declarations/optional.js
Fix inconsistent between babel and other parser 
Ref: https://github.com/prettier/prettier/pull/16035#issuecomment-1933334644
=> Exclude optional call from `isTestCall`

scripts/build/config.js, src/cli/format.js, src/cli/prettier-internal.js, src/index.js, src/main/core.js
=> Remove outdated hack for `diff` package

changelog_unreleased/javascript/16116.md, src/language-js/print/template-literal.js, src/language-js/utils/index.js, tests/format/js/strings/__snapshots__/jsfmt.spec.js.snap, tests/format/js/strings/template-literals.js
Allow linebreaks in even simple template interpolations when the user already has one there.
Fixes https://github.com/prettier/prettier/issues/16114. This is a followup to https://github.com/prettier/prettier/pull/15209 - now that we have a more flexible heuristic ("treat interpolations as valid places to break only if the user already had linebreak"), we can use it instead of the old "do not break in simple interpolations" heuristic. I mentioned the possibility of doing this in the original PR but no one commented on it either way; now that someone has explicitly requested this I figure we might as well.
Incidentally, it's pretty weird that most expressions _don't_ treat the `${}` as valid places to break. [This is just kinda weird](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAE …
=> allow linebreaks in member expressions in template interpolations

changelog_unreleased/javascript/16064.md, src/language-js/embed/utils.js, tests/format/js/multiparser-graphql/__snapshots__/jsfmt.spec.js.snap, tests/format/js/multiparser-graphql/comment-tag.js
=> Format embedded GQL in template literal statements

website/blog/2017-04-13-1.0.0.md, website/blog/2018-02-26-1.11.0.md, website/blog/2020-03-21-2.0.0.md, website/blog/2020-08-24-2.1.0.md
=> chore: fix some typos in comments

docs/precommit.md
Pre-commit has [archived the prettier package](https://github.com/pre-commit/mirrors-prettier) with the following comment:
> prettier made some changes that breaks plugins entirely
=> Remove pre-commit from precommit.md

docs/plugins.md
`getValue` function is deprecated.
https://github.com/prettier/prettier/blob/1264a4cdfe11f1c5b5ea6968fedebcb3747ca759/src/index.d.ts#L110-L113
However, [the plugin documentation](https://prettier.io/docs/en/plugins) still uses `getValue` function.
=> docs: `getValue()` replaced with `node`

CONTRIBUTING.md
This pull request adds a couple of direct links to files in `CONTRIBUTING.md` for reader convenience. At least one other path in `CONTRIBUTING.md` already had a direct link.
=> docs: directly link files in `CONTRIBUTING.md`

.github/renovate.json5
=> Use `matchDepNames` instead of `matchPackageNames` in renovate.json5

changelog_unreleased/api/16157.md, docs/configuration.md, src/config/prettier-config/config-searcher.js, src/config/prettier-config/load-config.js, src/config/prettier-config/loaders.js, tests/integration/__tests__/config-resolution.js, tests/integration/cli/config/package-yaml/package.yaml
Enable support for reading `prettier` configuration directly from [`package.yaml`](https://github.com/pnpm/pnpm/pull/1799).
=> feat: add support for `package.yaml` config

src/language-js/parse/babel.js, tests/format/misc/errors/js/__snapshots__/format.test.js.snap
Always enable `recordAndTuple` plugin, but removed `syntaxType` https://github.com/babel/babel/pull/16458
=> Always enable `recordAndTuple`

changelog_unreleased/javascript/16267.md, src/language-js/print/call-expression.js, tests/format/js/dynamic-import/__snapshots__/format.test.js.snap, tests/format/js/dynamic-import/format.test.js, tests/format/js/dynamic-import/import-phase.js, tests/format/js/dynamic-import/template-literal.js
=> Fix dynamic import when the module source is a template literal

changelog_unreleased/flow/16271.md, src/language-js/print/array.js, tests/format/flow/tuples/__snapshots__/format.test.js.snap, tests/format/flow/tuples/inexact.js
Inexact tuple types are like inexact object types - they have a trailing `...` in their element list, e.g. `type T = [number, ...]`.
If you have an idea of a better way to add support for this within `print/array.js` let me know.
=> Flow: add support for inexact tuple types

changelog_unreleased/flow/16272.md, package.json, src/language-js/print/type-annotation.js, tests/format/flow/type-guards/__snapshots__/format.test.js.snap, tests/format/flow/type-guards/format.test.js, tests/format/flow/type-guards/test.js, yarn.lock
Adds support for Flow's `implies x is T` type guards, along with the basic one and the asserts varient. 
=> Flow: add support for 'implies' type guard variant

website/versioned_docs/version-stable/precommit.md
`pnpm exec husky-init` should be `pnpm exec husky init` according to [official documentation](https://typicode.github.io/husky/get-started.html#husky-init-recommended)
=> fix(docs): precommit.md pnpm husky init

changelog_unreleased/markdown/16063.md, src/language-markdown/printer-markdown.js, tests/format/markdown/footnoteDefinition/__snapshots__/format.test.js.snap
Ensures there are newlines between markdown footnote definitions, to comply with the standard set by Pandoc (https://pandoc.org/MANUAL.html#footnotes):
> Each footnote should be separated from surrounding content (including other footnotes) by blank lines.
Resolves #8301
=> Add newline between markdown footnote definitions

docs/browser.md, scripts/build-website.js, scripts/release/steps/update-version.js, website/package.json, website/scripts/replace-version-placeholder.mjs
We don't need update files in `docs/` when doing a release.
=> Use prettier version placeholder in `docs/`

changelog_unreleased/handlebars/16358.md, src/language-handlebars/clean.js, src/language-handlebars/printer-glimmer.js, src/language-handlebars/visitor-keys.evaluate.js, tests/format/handlebars/path-expressions/__snapshots__/format.test.js.snap, tests/format/handlebars/path-expressions/literal-expressions.hbs, tests/unit/__snapshots__/visitor-keys.js.snap
Fixed #16356
Changed print('head') to print(node.tail) as mentioned in the comment: https://github.com/prettier/prettier/issues/16356#issuecomment-2150771806
=> Fix handlebars path expressions starts with `@`

docs/related-projects.md
Hi there,
first of all I'd really like to thank you for such an amazing code formatter. It has proven to be life-saving for me - I'm using it in many of my open source projects and it has always helped me keeping my codebases clean and properly formatted! 🚀 
I recently developed [reviewdog-action-prettier](https://github.com/EPMatt/reviewdog-action-prettier), a project which allows to run Prettier as an action in GitHub Actions CI/CD workflows. The action is based on [reviewdog](https://github.com/reviewdog/reviewdog) and provides both code annotations and suggestions as GitHub checks. You can find the documentation, as well as several examples of the tool in action, on the project's repo.
This PR adds a link to reviewdog-action-prettier in the _Related Projects_ section in Prettier docs …
=> Add link to reviewdog-action-prettier

src/language-js/parse/babel.js
It is now always enabled, and will be removed in the future.
Ref: https://github.com/babel/babel/pull/16572
=> chore: Remove unused Babel parser plugins

package.json, src/language-markdown/constants.evaluate.js, src/language-markdown/printer-markdown.js, src/language-markdown/utils.js, yarn.lock
=> Switch `PUNCTUATION_REGEXP` to use RegExp with `u` directly

docs/configuration.md
Resolves part of: https://github.com/prettier/prettier/issues/15255
Docs mention a `options.editorconfig` option that does not exist and merely confuses users.
=> Remove mention of `options.editorconfig` which does not exist.

scripts/release/README.md, scripts/release/run.js, scripts/release/steps/bump-prettier.js, scripts/release/steps/choose-version.js, scripts/release/steps/index.js
=> Release script: choose version instead of passing argument

src/language-css/printer-postcss.js, src/language-css/utils/index.js
=> Remove `isLastNode` in favor of `AstPath#isLast`

.github/workflows/dev-test.yml, .github/workflows/prod-test.yml
This reverts commit 484ecde4307d3f535256ef83e9b09c5a0445bc77.
GH Actions supports Node.js 22.5.1 now https://github.com/actions/node-versions/pull/182
=> Revert "Pin Node.js v22 version (#16491)"

changelog_unreleased/api/13315.md, changelog_unreleased/javascript/13315-2.md, src/document/printer.js, tests/format/js/template-literals/__snapshots__/format.test.js.snap, tests/format/js/template-literals/expressions.js, tests/unit/doc-printer.js
Stop mutate the parts, by only copy it once to a mutable `fill`.
The playground link in #3263 is broken, I can't test the original case.
//cc @duailibe It will be great if you can review, since you bring this in #3273
Fixes #16493
=> Stop mutate `doc.parts` when printing `fill`

docs/rationale.md
Provides documentation under the "Rationale" section explaining that machine-generated files like `package.json` may be handled using a different formatter, and why that is.
Closes #11553
- N/A
- N/A
- N/A
=> docs: document the special treatment of machine-generated files

src/language-js/print/member-chain.js
`AstPath` is a state machine, don't need pass around.
=> Simplify `printMemberChain`

docs/api.md
The code example for `prettier.resolveConfig` does not works correctly.
```js
const text = await fs.readFile(filePath, "utf8");
const options = await prettier.resolveConfig(filePath);
const formatted = await prettier.format(text, options);
```
When I run the above code, the following error is thrown:
```
UndefinedParserError: No parser and no file path given, couldn't infer a parser.
```
This error occurs because the parser is not specified. To fix this, I changed the code to the following:
```js
const text = await fs.readFile(filePath, "utf8");
const options = await prettier.resolveConfig(filePath);
const formatted = await prettier.format(text, {
...options,
filepath: filePath,
});
```
=> Fix code example for `prettier.resolveConfig`

docs/options.md
I added an Oxford comma because when I read this I got a little confused.
=> Add oxford comma to Single Attribute Per Line doc

docs/plugins.md
`getPreferredQuote` is mainly used to get the quote for `makeString` so it makes more sense to have them close by in the documentation.
=> reorganizing `getPreferredQuote` documentation

changelog_unreleased/typescript/16578.md, src/language-js/comments/handle-comments.js, tests/format/typescript/comments/16065-2.ts, tests/format/typescript/comments/__snapshots__/format.test.js.snap
https://github.com/prettier/prettier/pull/16574#issuecomment-2290621095
=> Preserve a comment between modifier and the decorated property name

tests/format/scss/quotes/__snapshots__/format.test.js.snap, tests/format/scss/quotes/quotes.scss
Just correct invalid test case. No user facing change.
It resulted syntax error. [Sass playground](https://sass-lang.com/playground/#eJwdyTEOgzAMBdCdU3wFhlYiFcmYqSPXMOCoVgNIdmjF7asyPr0QnocxXJFJSU+Hr9QXbg3QTYXmd0IbY+wv77qweqVFDksYHkF5/Ufet+ozrVLOBDdy+XCVmXoYbeaNVbJr7j+ZvCBm).
```
expected ")".
╷
4 │   $font-family: "Helvetica, sans-serif"
│               ^
╵
- 4:15  root stylesheet
```
=> correct invalid scss test input

changelog_unreleased/typescript/16586.md, src/language-js/print/arrow-function.js, tests/format/typescript/arrow/16067.ts, tests/format/typescript/arrow/__snapshots__/format.test.js.snap
=> Don't print an extra line break for arrow function with type parameter in assignment

scripts/build/build-package-json.js
We use `.js` extension for UMD modules, let's  make it explicitly mark `.js` files are not ESM. 
Not sure if this will effect [this change](https://nodejs.org/en/blog/release/v22.7.0#module-syntax-detection-is-now-enabled-by-default) in Node.js
=> Add `type: "commonjs"` to bundled package.json

changelog_unreleased/cli/16684.md, docs/ignore.md, src/cli/expand-patterns.js, tests/integration/__tests__/ignore-vcs-files.js, tests/integration/cli/ignore-vcs-files/.jj/file.js
[Jujutsu](https://martinvonz.github.io/jj/latest/) is a version control system that's Git-compatible.
Jujutsu, like the other VCSs, stores state to disk. Jujutsu uses the `.jj` directory for this.
This change updates the `silentlyIgnoredDirs` list to include this directory, which makes prettier treat it like other VCSs.
https://github.com/prettier/prettier/blob/724bb0cdf5fd1a86a4940cbb31f6623ad81afaa6/src/cli/expand-patterns.js#L48
In this change:
https://github.com/prettier/prettier/blob/a3c763c75abc608ce8041b115b3f1723af036851/src/cli/expand-patterns.js#L48
=> Ignore files in the Jujutsu directory

tests/format/js/import-assertions/__snapshots__/format.test.js.snap, tests/format/js/import-assertions/format.test.js, tests/format/js/import-assertions/keyword-detect.js, tests/format/js/import-attributes/__snapshots__/format.test.js.snap, tests/format/js/import-attributes/keyword-detect.js
Doing this because ["JSON modules"](https://github.com/tc39/proposal-json-modules) proposal forbids "named exports".
Meriyah also added support for "import attributes", but not "import assertions".
=> Rewrite tests for importing JSON

.github/renovate.json5, eslint.config.js, package.json, scripts/tools/eslint-plugin-prettier-internal-rules/no-identifier-n.js, scripts/tools/eslint-plugin-prettier-internal-rules/test.js, src/cli/format.js, website/siteConfig.js, yarn.lock
`eslint-plugin-import` is slow, `knip` should good enough to catch dependencies issues
=> Remove `eslint-plugin-import`

tests/unit/doc-printer.js
Test for computational complexity sometimes fails. I loosen the check.
- https://github.com/prettier/prettier/actions/runs/10918652303/job/30304586314
- https://github.com/prettier/prettier/actions/runs/10926551730/job/30330691083
- https://github.com/prettier/prettier/actions/runs/11074432534/job/30773198271
- https://github.com/prettier/prettier/actions/runs/10926464116/job/30330396707
- https://github.com/prettier/prettier/actions/runs/10821470528/job/30023526559
- https://github.com/prettier/prettier/actions/runs/11099612409/job/30834112908?pr=16700
=> loosen computational complexty check for printing fill

src/language-js/parse/babel.js
Part of #16801
[#​babel-16841](https://redirect.github.com/babel/babel/pull/16841) Always enable parsing of Flow enums
=> Remove outdated options for babel "flow" plugin

docs/install.md
The pre-commit hook currently specifies `npx` instead of `yarn` for the Yarn project.
Use the correct package manager for the Yarn installation instructions.
=> Fix Yarn installation instructions to use yarn

changelog_unreleased/javascript/16563.md, src/utils/print-string.js, tests/format/css/quotes/__snapshots__/format.test.js.snap, tests/format/js/quotes/__snapshots__/format.test.js.snap, tests/format/js/strings/__snapshots__/format.test.js.snap, tests/format/js/strings/escaped.js
We already  stop unescaping characters in #16563.
It makes sense to skip `makeString()` when the original quote matches the desired quote.
However, this will make the following code
```js
const foo = "\"\'"
```
untouched when using `--no-single-quote`,  but [unescape `"` when using `--single-quote`](https://deploy-preview-16763--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzCFMC8mAOiMeWcQOSkgA0IEADjAJbrKgCGATjxAHcACrwRpkILgBsBXAJ7iGAIx5cwAazgwAylwC2cADKsocZNmlo4y1Rq3amakwHNkMHgFdrIK3tZvPbzgADyY4HlYDWGkAFXCoXlY4cSQLKSsGNBcpOABFDwh4AK8GACs0YO1svIKi1MtvAEdauCF+JhTJNABaUzgAEwH6EHcuVikXAGEIPT0uCWkpYayoZxyAQRh3ViUPeCFw41NzBoYACxg9KQB1M9Z4NEcwOG0xe9YAN3u5CTA0RRAHy8AEkoINYNowBEWOswdoYHIcid0t4mPwrNdVEwJGjkuEPmYGCYrDwYG0uM45siMiBHDwSRIlFwlHAlgw0SYYNdWP0YGdkAAOAAMDB4cGarDF5Mp83qKIYMGZ3N5 …
=> Improve string print perfomance

changelog_unreleased/markdown/16816.md, src/language-markdown/constants.evaluate.js, tests/format/markdown/splitCjkText/non-bmp/format.test.js
non-BMP CJK characters and IVS are not recognized to CJK now.
`.toString` and `.toRegExp` in `regexp-util`.`CharSet`  generate regexps incompatible with the `u` flag by default.
We have to pass the `"u"` argument to make them compatible with `u`.
https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDABIdW10e79AOlIOYbgvHtGBa2UWZSADQgQAOMAltAM7KioBOvEAO4AFPgi4pUAG0GoAnlwYAjXqjABrODADKqALZwAMqyhxkAM2kc4y1Rq3amakwHNkMXgFcbIa3tbuXj5wAB5McLysBrDSACoRUHyscBKWUtYMHK5ScACKnhDwFlY+AFYcIdrZeQVFSGkZIACOtXDCAkwSaBwAtKZwACaD9CAeqKxSrgDCEHp6qMhoUlIjWVAuOQCCMB6sSp7wwhHGpsXpPgAWMHpSAOoXrPAcTmBw2uKPrABuj3KLYBxFCAvt4AJJQIawbRgSIsTYQ7QwOQ5M6NJgCay3VRMRamL4REYmay8GDtVAueaonxOXjExbzXjqAZCKAjdEmGC3VgDGAXZAADgADAxeHAWqxRWSKQt6iUGDBUEouTy+UgAEwMTzWWKK1JykBwPRKQZDAaGVDrTzkuAAMQgvHmO1ci1QBwgIAAvh6gA …
=> Tell regexp-util to generate regex compatible with u flag

bin/prettier.cjs
https://nodejs.org/en/blog/release/v22.8.0#new-js-api-for-compile-cache
```console
$ hyperfine --warmup 3 --min-runs 100 "node dist-without-cache/bin/prettier.cjs -v"
Benchmark 1: node dist-without-cache/bin/prettier.cjs -v
Time (mean ± σ):      87.6 ms ±   3.1 ms    [User: 67.8 ms, System: 22.9 ms]
Range (min … max):    83.8 ms … 104.2 ms    100 run
$ hyperfine --warmup 3 --min-runs 100 "node dist-with-cache/bin/prettier.cjs -v"
Benchmark 1: node dist-with-cache/bin/prettier.cjs -v
Time (mean ± σ):      75.9 ms ±   3.6 ms    [User: 56.5 ms, System: 22.5 ms]
Range (min … max):    71.5 ms …  98.9 ms    100 runs
```
```console
$ hyperfine --warmup 3 --min-runs 100 "node dist-without-cache/bin/prettier.cjs index.js"
Benchmark 1: node dist-without-cache/bin/prettier.cjs index.js
Time (mean ± …
```
=> Use compile cache

changelog_unreleased/api/16857.md, src/config/prettier-config/load-external-config.js
Fixes #16812
I don't add tests for this change due to https://github.com/jestjs/jest/issues/15363, but I was able to test it locally.
=> Fix loading ESM-style shared config file in Node.js 23

docs/index.md, website/versioned_docs/version-stable/index.md
Update the old link of angular.io to angular.dev
=> docs: fix angular link

changelog_unreleased/vue/16887.md, src/language-js/needs-parens.js, tests/format/vue/event-binding/__snapshots__/format.test.js.snap, tests/format/vue/event-binding/assignment.vue
=> Remove unnecessary parentheses around assignment in `v-on`

src/language-js/print/typescript.js
This property has been removed long time ago, https://github.com/typescript-eslint/typescript-eslint/pull/3076
Tests exits https://github.com/prettier/prettier/blob/d52e905869dffd6e870fed453f25aaf2f78b736c/tests/format/typescript/import-type/import-type.ts#L7
=> Remove check on `TSImportType.isTypeOf`

changelog_unreleased/javascript/16899.md, src/document/printer.js, tests/format/jsx/text-wrap/__snapshots__/format.test.js.snap, tests/format/jsx/text-wrap/issue-16897.js
Fixes #16897
It was caused by https://github.com/prettier/prettier/pull/16595. I forgot to reflect change in fill doc to fit().
=> Correct fit() for fill()

changelog_unreleased/flow/16947.md, package.json, src/language-js/print/type-parameters.js, tests/format/flow/type-parameters/flow-only/__snapshots__/format.test.js.snap, tests/format/flow/type-parameters/flow-only/const-type-params.js, tests/format/flow/type-parameters/flow-only/format.test.js, yarn.lock
Adds support for `const` type params in Flow.
=> Suppport const type params in Flow

docs/install.md
This PR adapts the Husky setup documentation for PNPM users by updating npm commands to their PNPM equivalents.
- Replace `npx husky init` with `pnpm exec husky init`
=> docs: Update Husky setup commands for PNPM users

changelog_unreleased/vue/16920.md, src/language-html/embed/vue-attributes.js, tests/format/vue/multiparser/__snapshots__/format.test.js.snap, tests/format/vue/multiparser/template-bind.vue
`.foo` is shorthand for `v-bind:foo.prop`. See [`v-bind` builtin directive](https://vuejs.org/api/built-in-directives.html#v-bind) for details.
=> Support Vue `.prop` shorthand

.github/workflows/prod-test.yml
Consistently failing CI are harmful
context: https://github.com/prettier/prettier/issues/16964
=> Disable CI on MacOS x Node.js

changelog_unreleased/api/16828.md, tests/integration/__tests__/config-file-typescript.js
Node.js v23 unflagged `--experimental-strip-types` https://nodejs.org/zh-cn/blog/release/v23.6.0
=> Fix tests for ts config

scripts/release/package.json, scripts/release/steps/generate-bundles.js, scripts/release/steps/post-publish-steps.js, scripts/release/steps/show-instructions-after-npm-publish.js, scripts/release/steps/update-changelog.js, scripts/release/steps/update-dependents-count.js, scripts/release/steps/validate-new-version.js, scripts/release/steps/wait-for-bot-release.js, scripts/release/tests/validate-new-version.test.js, scripts/release/utils.js, scripts/release/yarn.lock
`node-style-text` is built on top of `node:util.styleText`, but provide chainable API, see <https://github.com/fisker/node-style-text#motivation>
It's super small (<300 B)
=> Replace `chalk` with `node-style-text` in release script

changelog_unreleased/javascript/16163.md, docs/options.md, docs/rationale.md, src/common/common-options.evaluate.js, src/index.d.ts, src/language-js/options.js, src/language-js/print/mapped-type.js, src/language-js/print/object.js, tests/dts/unit/cases/parsers.ts, tests/format/flow/object-multiline/__snapshots__/format.test.js.snap, tests/format/flow/object-multiline/format.test.js, tests/format/flow/object-multiline/multiline.js, tests/format/js/object-multiline/format.spec.js, tests/format/js/object-multiline/multiline.js, tests/format/json/json/__snapshots__/format.test.js.snap, tests/format/json/json/format.test.js, tests/format/typescript/object-multiline/__snapshots__/format.test.js.snap, tests/format/typescript/object-multiline/format.test.js, tests/format/typescript/object-multiline/multiline.ts, tests/integration/__tests__/__snapshots__/early-exit.js.snap, tests/integration/__tests__/__snapshots__/help-options.js.snap, tests/integration/__tests__/__snapshots__/plugin-options-string.js.snap, tests/integration/__tests__/__snapshots__/plugin-options.js.snap, tests/integration/__tests__/__snapshots__/schema.js.snap, tests/integration/__tests__/__snapshots__/support-info.js.snap, website/playground/Playground.js
Implement `multilineObject` config option to control how multi-line JavaScript objects are formatted.
This is the default. Objects are kept on multiple lines if there is a newline between the opening brace and the first property key. (I.e. the existing behavior of Prettier.)
Objects ignore whitespace-only formatting from the source, and are collapsed to a single line when possible.
<details>
<summary>Input</summary>
```js
const obj1 = {
name1: "value1",
name2: "value2",
};
const obj2 = {
name1: "value1", name2: "value2",
};
const obj3 = {
name1: "value1",
name2: "value2", };
const obj4 = { name1: "value1",
name2: "value2",
};
const obj5 = { name1: "value1", name2: "value2", };
```
</details>
<details>
<summary>"preserve"</summary>
```js
const obj1 = {
name1: "value1",
name2: "value2",
}; …
```
=> Implement `objectWrap` config option

tests/format/js/deferred-import-evaluation/__snapshots__/format.test.js.snap, tests/format/js/deferred-import-evaluation/dynamic-import-attributes-expression.js, tests/format/js/deferred-import-evaluation/dynamic-import.js, tests/format/js/deferred-import-evaluation/format.test.js
Fixtures copied from https://github.com/babel/babel/tree/6516c18c825249c0d44179c9ec8745544e1a638b/packages/babel-parser/test/fixtures/experimental/deferred-import-evaluation
=> Add tests for `import.defer()`

changelog_unreleased/misc/16958.md, package.json, scripts/build/build-package-json.js
Pros:
- The extra process in `index.cjs` will be skipped for Node 22.12 or later or bundlers supporting sync ESMs.
- Can be clarify that Prettier can be `require(ESM)`ed because it doesn't contain top-level awaits.
Cons:
~~The following unpleasant warning will be out when we run `require("prettier")`:~~ Only 22.12.x
```
(node:23928) ExperimentalWarning: The REPL is loading ES Module I:\prettier\src\index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
```
~~We may not be possible to accept this PR now due to this.~~
~~If require(ESM) is stable in the future (Node 24?), we will be able to merge without hesitation.~~
The warning is not shown since …
=> Use ESM entrypoint for `require(ESM)`

src/index.cjs
Note this change only effect `yarn add prettier@prettier/prettier`, the bundled version already available.
=> Make `prettier.util` and `prettier.doc` available in development cjs version on Node.js>=22

changelog_unreleased/api/17041.md, src/config/prettier-config/loaders.js
Fixes #17039
Local tested, config successfully loaded from `package.json`, and with overrides, it can be formatted.
=> Support read config from `package.json` with JSONC syntax on Bun

docs/options.md, website/versioned_docs/version-stable/options.md
I noticed some of the content on https://prettier.io/docs/options/ broke as part of https://github.com/prettier/prettier/pull/17043. I did a quick spot check and think these are the two main changes that are wrong from that change.
=> docs: fix content change from docusaurus migration

website/docusaurus.config.js, website/src/css/custom.css, website/src/pages/index.module.css
While playing around with the spacing during the docusaurus migration, some places were left with too much, or too little whitespace. This PR fixes them.
Before:
After:
Before:
After:
=> docs: fix spacing issues on the home page

docs/ignore.md
I added a line to the documentation explaining that Markdown ignore comments must be preceded by an empty line to work.
=> Include note about Markdown ignore comments

website/playground/Playground.js
v3.5.0 introduced these 2 options.
- `objectWrap`
- `experimentalOperatorPosition`
This PR allows playground to use them.
=> Playground: Enable v3.5.0 features

netlify.toml, scripts/release/tests/publish-to-npm.test.js, scripts/release/utils.js
Similar to https://github.com/prettier/prettier/pull/17079/ which removes the `.html` extension from a lot of existing URLs, this PR aims to remove that for new release blog posts.
This is important, because otherwise opening the blog posts from the GitHub release notes renders the page twice. This is known issue in docusaurus that will be fixed in later versions: https://github.com/facebook/docusaurus/issues/10053
For handling old URLs with the `.html` extension, I enabled Netlify's "Pretty URLs" option, recommended here: https://github.com/facebook/docusaurus/issues/9552#issuecomment-1821481582
As an example, opening the blog post for the 3.5 release now in the deploy preview works even with the `.html` in the URL: https://deploy-preview-17090--prettier.netlify.app/blog/2025/02/09/3.5.0. …
=> docs: avoid using `.html` extension for blog posts

src/index.d.ts, tests/dts/unit/cases/parsers.ts
This PR adds missing types for options `experimentalOperatorPosition`.
=> Add missing option `experimentalOperatorPosition` types

changelog_unreleased/yaml/17101.md, cspell.json, src/language-yaml/languages.evaluate.js, tests/integration/__tests__/__snapshots__/support-info.js.snap
This adds support for the `dockercompose` and `github-actions-workflow` languages in VSCode. The `dockercompose` language is registered by https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker. The `github-actions-workflow` language is registered by https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-github-actions. Both these languages apply to regular YAML files that can be formatted with Prettier.
=> Support dockercompose and github-actions-workflow

.github/renovate.json5, .github/workflows/lint.yml, knip.config.js
https://github.com/prettier/prettier/pull/17070#issuecomment-2645952994
=> Update renovate.json5 to ignore `codemirror@6.65.7`

src/common/get-file-info.js
parser can't config via `.editorconfig`, no need read it in `getParser`
=> Prevent reading `.editorconfig` in `getParser`

docs/cli.md, docs/install.md, website/versioned_docs/version-stable/cli.md, website/versioned_docs/version-stable/install.md
Prettier is installed locally in the project and can be run with the `pnpm prettier` command.
And the CLI in the codeblock appears to be a typo, as the info box below uses `pnpm prettier` instead of `pnpm exec prettier`.
=> Docs: update cli commands

changelog_unreleased/markdown/17143.md, src/language-markdown/printer-markdown.js
In most markdown implementations `1***2***3` is considered strong emphasis but `1**_2_**3` is not.
Also most guides strongly recommend `***` instead of `**_` (see https://www.markdownguide.org/basic-syntax/#bold-and-italic-best-practices).
See the issue right here on github:
`1***2***3` ➡️ 1***2***3
`1**_2_**3` ➡️ 1**_2_**3
This PR prefers`***` in the cases where needed but doesn't default to it.
=> fix(markdown): fix strong emphasis

changelog_unreleased/flow/17196.md, src/language-js/comments/handle-comments.js, src/language-js/needs-parens.js, src/language-js/print/ternary.js, src/language-js/print/type-annotation.js, src/language-js/utils/index.js, tests/format/flow/conditional-types/parentheses/__snapshots__/format.test.js.snap, tests/format/flow/conditional-types/parentheses/format.test.js, tests/format/flow/conditional-types/parentheses/union.js
=> Fix missing parentheses in `ConditionalTypeAnnotation`

src/cli/format.js, src/cli/logger.js, src/cli/options/normalize-cli-options.js, src/cli/prettier-internal.js, src/index.js
Reduce size of CLI, not much since they are quite small.
**Size Change:** -4.76 kB (-0.06%) 
**Total Size:** 7.87 MB
| `./dist/index.mjs` | 730 kB | +73 B (+0.01%) |
| `./dist/internal/cli.mjs` | 130 kB | -4.84 kB (-3.59%) |
=> Share `picocolors` and `leven` with CLI

website/playground/Playground.jsx, website/playground/index.jsx, website/static/worker.mjs
When set cursorOffset and range, there will be errors.
Also hide "doc" and "second output" panel.
=> Improve playground when using `doc-explorer` parser

src/main/core.js, tests/integration/__tests__/debug-api.js
I don't think users really need it, so I'm not going to add changelog for it.
Adding this making us easier to debug in playground.
For example: https://github.com/prettier/prettier/issues/17227
[Link](https://deploy-preview-17256--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEBiABAQSgcwK4A2AhgE7pQTwA6UNABgzAJ4AOcAzmCQJYsw3p03ALYsIJGOmABhCKOgIYAX3QAzEnPQByAAJFchUgHpIJOFoDcA9NZ2z5URQApg1wezgE4YGOKTaiFhYAWg1KLQAaN3R2GH0AEyICBX8YEjw4KKhBQRExCXZ-AG0AXSyc9HhRYnh-OmjBAB4ACwBGAD4Gm2yKqWBK7hgvdCUlRqM2zp7BOnKc2KYvAFUSAkL0Iq0AOiNAli3IB0UD9nYtMuslAEprOAAPfMkwYlOsIPsxR1gpaJhB4YAvNp4nBVERCDBLJd6AwQBEQBA+NxoOxkKBSBoAO4ABVICFRKCSmKITFR8IARiQiGAANZwGAAZSIwjgABluI5kGC1pkEeSAFbeGAAdSpLGQIBYZg8JAAbnA4SBKdS6YyWNSOThkGkMvCPMJuNr0rz7mweCzYEkAPJmoi+EjYiDsQbIqAShDxRWmuDmxRJAAqPqgpG4HC5SQ8es1XgAinhKAqkNzIyB+ew …
=> Support `cursorOffset` in `prettier.__debug.printToDoc()`

package.json, src/document/utils.js, yarn.lock
Fix Security issue https://github.com/prettier/prettier/security/code-scanning/5
If non dependency solution is prefered, I can change it to 
```js
doc.replace(/(^|[^\n\r])[\n\r]*$/u, "$1");
```
Should be equivalent.
https://devina.io/redos-checker
=> Fix ReDoS vulnerability

src/main/comments/attach.js
I guess this logic exists because the `JsonRoot` and `JsExpressionRoot` has wrong location before.
First introduced in https://github.com/prettier/prettier/pull/3187
=> Remove special logic in comment attach

package.json, src/cli/find-cache-file.js, yarn.lock
`find-cache-dir` has been renamed https://github.com/sindresorhus/find-cache-directory/releases/tag/v6.0.0
=> Update `find-cache-directory` to v6

changelog_unreleased/angular/17280.md, src/language-js/print/angular.js, tests/format/angular/control-flow/__snapshots__/format.test.js.snap, tests/format/angular/control-flow/for.html
Previously prettier appended a colon to the 'track' in an angular @for-of control-flow, if the index of the 'track' (a 'NGMicrosyntaxKey') was not 2 or 3. 
This means that
`@for (item of items; let i = $index; let count = $count; track block) {}`
would still be formatted to 
`@for (item of items; let i = $index; let count = $count; track: block) {}`.
I.e. a colon would be inserted after the 'track'. 
I have removed the `index === 3` check, because, as I see it, this was specifically added to fix the same problem. (In [pr-15887](https://github.com/prettier/prettier/pull/15887) here, but it is not a complete fix, as discussed in [#15698](https://github.com/prettier/prettier/issues/15698).)
fixes #15698
=> Remove extra colon after `track` in angular `@for` control-flow

src/config/prettier-config/loaders.js
`loadConfigFromPackageJson` is a hot path.
Check `process.versions.bun` when define it, instead of checking it in every call, .
=> Minor improvement to config loader

bin/prettier.cjs, jest.config.js, package.json, scripts/build/config.js
So we don't need set `PRETTIER_LEGACY_CLI` every time we want use CLI
=> [V4] Use legacy CLI by default during development

website/data/editors.yml
I renamed the extension to Prettier⁺ – because it just looks better 😎.
Sorry for the fuzz.
=> Rename Prettier+ to Prettier⁺

src/cli/format.js, src/common/mockable.js, tests/integration/cli-worker.js, tests/integration/run-cli.js
We run tests in `child_process` now, so we can use `stdin` directly without mocking.
=> Remove `stdin` mock

src/cli/format.js, src/common/mockable.js, tests/integration/cli-worker.js
=> Measure time with `performance.now()` instead of `Date.now()`

package.json, src/cli/format.js, src/cli/utilities/get-stdin.js, yarn.lock
<https://github.com/sindresorhus/get-stdin#tip>
Requires Node.js v16
=> [V4] Replace `get-stdin` with native alternative

package.json, src/cli/utilities/clear-stream-text.js, yarn.lock
=> [V4] Replace `strip-ansi` with `stripVTControlCharacters` from `node:util`

tests/format/js/reserved-word/__snapshots__/format.test.js.snap, tests/format/js/reserved-word/interfaces.js, tests/format/js/reserved-word/let.js, tests/format/js/reserved-word/yield.js
closes: #10603
Just added missing test cases for the reserved words `yield` and `let`.
These words are mentioned in https://github.com/prettier/prettier/issues/10603#issuecomment-845466073.
These words would be contextual keywords that can be used as identifiers in certain contexts.
Adding missing test cases are required in https://github.com/prettier/prettier/issues/10603#issuecomment-845468319.
In https://github.com/o-m12a/prettier/commit/1980a53bfefe841a608c762eb40ad4ee5d04ed01, I also unified to use `var` in test snippets.
This was done because, using `const` or `let` instead of `var` like the following in `let.js`
```.ts
const let = "foo"; // using `const` instead of `var`
let let = "foo"; // using `let` instead of `var`
```
causes the TypeScript error `'let' is not allowed to be …
=> Add more tests for reserved words

.github/workflows/dev-test.yml, .github/workflows/prod-test.yml, tests/config/install-prettier.js
Remove Node.js v23, add Node.js v24
Dev:
Linux: 20, 22, 24
MacOS & Windows: 20, 24
Prod:
Linux: 14, 16, 18, 20, 22, 24
MacOS & Windows: 14, 24
=> Run tests on Node.js v24

src/cli/logger.js
When I work on https://github.com/prettier/prettier/pull/17226, I noticed this, I thought it doesn't matter, but apparently it breaks #13097
I try to add test for it, but it's hard to do, I'm going to give up. Added comment how to test instead.
=> Fix colors detect for logger

changelog_unreleased/html/17501.md, src/language-html/utils/index.js, tests/format/html/tags/object-prototype-properties/__snapshots__/format.test.js.snap, tests/format/html/tags/object-prototype-properties/format.test.js, tests/format/html/tags/object-prototype-properties/object-prototype-properties.html
=> Fix HTML format that tag name is an object prototype property

src/language-js/parse/acorn.js, src/language-js/parse/babel.js, src/language-js/parse/oxc.js, src/language-js/parse/postprocess/index.js, src/language-js/utils/is-type-cast-comment.js
Fixes #17552
With this the timing for parsing+postprocess of the typescript compiler in node_modules went from 750ms to 250ms, which is close enough to the timing of skipping this step that you get noise depending on which one runs first
=> Improve postprocess perf for type cast comments

src/language-js/parse/postprocess/index.js, src/language-js/print/comment.js, src/language-js/utils/is-indentable-block-comment.js
Similar to change for `isTypeCastComment` in #17566, add a cache for it, since the comment value can be big.
Note: this cache may not hit in production, since printer and parser are bundled separately. But will make https://github.com/prettier/prettier/pull/17567 faster.
=> Improve `isIndentableBlockComment`

.github/workflows/dev-package-test.yml, .github/workflows/dev-test.yml, .github/workflows/prod-test.yml
This job hangs for 90 mins https://github.com/prettier/prettier/actions/runs/15631246601/job/44035926724#step:9:1376
=> Decrease CI `timeout-minutes` to 15mins

changelog_unreleased/javascript/17491.md, src/language-js/parse/espree.js, tests/config/run-format-test.js
This reverts commit 3b0f335.
They refuse to add support https://github.com/eslint/js/issues/661
=> Revert "Support type cast comments for `espree` parser (#17587)"

src/index.d.ts, src/language-js/needs-parens.js, tests/dts/unit/cases/plugins.ts, tests/dts/unit/run.js
They have been removed in #13699
=> Remove `since` from `SupportLanguage` and `ChoiceSupportOption.options` types

changelog_unreleased/typescript/17650.md, src/language-js/parse/babel.js, tests/format/misc/errors/js/variable-declarator/__snapshots__/format.test.js.snap, tests/format/misc/errors/js/variable-declarator/format.test.js, tests/format/misc/errors/typescript/modifiers/__snapshots__/format.test.js.snap, tests/format/typescript/d-ts-files/__snapshots__/format.test.js.snap, tests/format/typescript/d-ts-files/const-without-initializer-in-namespace.d.ts, tests/format/typescript/d-ts-files/const-without-initializer.d.ts, tests/format/typescript/d-ts-files/format.test.js
=> Allow const without initializer in `babel-ts` parser

website/blog/2025-06-23-3.6.0.md
Unbalanced `*` in the example text
=> Fix typo in v3.6.0 release notes for markdown

packages/plugin-oxc/package.json, src/language-js/parse/oxc.js
It fails tests on my machine, let's try this later. Besides, it seems `experimentalRawTransfer:true` is not faster when I test for parsing a small file.
=> Disable `experimentalRawTransfer` for oxc parser

docs/configuration.md, website/versioned_docs/version-stable/configuration.md
Node.js v24.3.0 "removed experimental warning from type stripping" https://nodejs.org/en/blog/release/v24.3.0
=> Update docs about "TypeScript Configuration Files"

tests/integration/__tests__/config-file-typescript.js
Node.js v22.18.0 
[Type stripping is enabled by default](https://nodejs.org/zh-cn/blog/release/v22.18.0#type-stripping-is-enabled-by-default)
=> Fix typescript config test on Node.js v22

changelog_unreleased/flow/17792.md, src/language-js/print/type-annotation.js, src/language-js/traverse/visitor-keys.evaluate.js, tests/format/flow/type-declarations/__snapshots__/format.test.js.snap, tests/format/flow/type-declarations/opaque.js, tests/unit/__snapshots__/visitor-keys.js.snap
This diff adds support for upcoming Flow feature that allows you to specify both the lower and upper bounds of opaque type using `super` and `extends` keyword.
=> Support new Flow feature: opaque type with lower and upper bounds

changelog_unreleased/css/17929.md, src/language-css/printer-postcss.js, src/language-css/utils/index.js, tests/format/css/modules/__snapshots__/format.test.js.snap, tests/format/css/modules/modules.css
Fix: #10057 
- treat css rules as ICSS whenever any ancestor selector starts with :import or :export
`path.findAncestor((node) => node.type === "css-rule")` only returns the *closest* css-rule ancestor.
For nested blocks like `nest { myColor: ... }`, the closest selector is `nest`, so `selector.startsWith(":export")` is `false` and `insideICSSRuleNode` returns `false`.
The printer then calls `maybeToLowerCase` on `myColor`, which forces it to lowercase.
`path.hasAncestor((node) => { ... })` walks upward through every ancestor.
Whenever it encounters a css-rule, it checks whether the selector starts with `:import/:export`, and if any level matches it returns `true`.
For declarations inside `nest`, it skips the `nest` rule, finds the outer `:export`, and returns `true`, so …
=> Fix ICSS detection for nested exports
